#ifdef CH_LANG_CC
/*
 *      _______              __
 *     / ___/ /  ___  __ _  / /  ___
 *    / /__/ _ \/ _ \/  V \/ _ \/ _ \
 *    \___/_//_/\___/_/_/_/_.__/\___/
 *    Please refer to Copyright.txt, in Chombo's root directory.
 */
#endif

#ifndef _CH_ASSERT_H__
#define _CH_ASSERT_H__

#include "Proto_PAssert.H"

#include "BaseNamespaceHeader.H"


#define CH_assert(cond) PR_assert(cond)

#include "BaseNamespaceFooter.H"

#endif /* include guard*/
