Chombo_4: Chombo_parstream.H File Reference
Chombo_parstream.H File Reference
#include <iostream>
#include <iomanip>
#include <string>
#include "Chombo_BaseNamespaceHeader.H"
#include "Chombo_BaseNamespaceFooter.H"
Macros
#define _Chombo_PARSTREAM_H_
Functions
std::ostream & pout ()
Use this in place of std::cout for program output.
void setPoutBaseName (const std::string &a_Name)
Changes the base part of the filename for pout() files.
const std::string & poutFileName ()
Accesses the filename for the local pout() file.
Macro Definition Documentation
_Chombo_PARSTREAM_H_
#define _Chombo_PARSTREAM_H_
Function Documentation
pout()
std::ostream& pout ()
Use this in place of std::cout for program output.
Replaces std::cout in most of the Chombo code. In serial this just returns std::cout. In parallel, this creates a separate file for each proc called <basename>.n where n is the procID and <basename> defaults to "pout" but can be set by calling setPoutBaseName(). Output is then directed to these files. This keeps the output from different processors from getting all jumbled up. If you want fewer files, you can do setenv CH_OUTPUT_INTERVAL nproc and it will only output every nproc processors pout.n files (where nnproc == 0).
Referenced by BoxLayoutData< FArrayBox >::allocateBuffers(), EBCM::PETSc_Framework< ebcm_order >::Base_PETSc_Op::Base_PETSc_Op(), Proto::HostBoxData< Proto::CellNode, 1 >::charsize(), Proto::HostIrregData< cent, data_t, ncomp >::charsize(), Proto::EBGraph::charsize(), EBCM::Algorithm_Framework< ebcm_order >::checkKappa(), CH4_Data_Choreography::DistributedData< EBFluxData< Real, NUMCOMPS > >::communicate(), CH4_Data_Choreography::CommunicationMetaData< fabtype_t >::CommunicationMetaData(), EBCM::EBCM_Graph< order >::consolidateFaces(), EBCM::EBCM_Graph< order >::copy(), CH4_Data_Choreography::DistributedData< EBFluxData< Real, NUMCOMPS > >::copyTo(), EBLevelBoxData< cent, NUMCOMPS >::copyToCPUOnly(), EBLevelBoxData< cent, NUMCOMPS >::copyToWithGPU(), EBCM::PETSc_Framework< ebcm_order >::Base_PETSc_Op::createMatrixRowMap(), LevelGeometryService< order >::defineFinestLevel(), Proto::dumpArea(), Proto::EBGraph::EBGraph(), Proto::HostIrregData< cent, data_t, ncomp >::energize(), Proto::EBGraph::energize(), LevelData< FArrayBox >::exchange(), EBLevelFluxData< NUMCOMPS >::exchange(), CH4_Data_Choreography::DistributedData< EBFluxData< Real, NUMCOMPS > >::exchange(), LevelGeometryService< order >::exchange(), EBLevelBoxData< cent, NUMCOMPS >::exchangeWithGPU(), EBCM::faceSign(), EBCM::Algorithm_Framework< ebcm_order >::neighborhood_t::fillDerived(), EBCM::Algorithm_Framework< ebcm_order >::fillDirichletDomBCRow(), EBCM::Algorithm_Framework< ebcm_order >::fillDirichletEBBCRow(), EBCM::Algorithm_Framework< ebcm_order >::fillNeumannDomBCRow(), EBCM::Algorithm_Framework< ebcm_order >::fillNeumannEBBCRow(), GeometryService< order >::GeometryService(), EBCM::Algorithm_Framework< ebcm_order >::getEBSystemMatrix(), EBCM::Algorithm_Framework< ebcm_order >::neighborhood_t::getFaceInfo(), EBCM::Algorithm_Framework< ebcm_order >::getImplicitFunction(), EBCM::Algorithm_Framework< ebcm_order >::getMomentMatrix(), EBCM::IrregFace< order >::getNormalMoment(), EBCM::EBCM_Graph< order >::getRefinedCoarseVolume(), EBCM::Algorithm_Framework< ebcm_order >::getSystemMatrix(), EBCM::Algorithm_Framework< ebcm_order >::getWorstConditionNumberInfo(), EBCM::Algorithm_Framework< ebcm_order >::getWorstEBConditionNumberInfo(), Proto::HostIrregData< cent, data_t, ncomp >::HostIrregData(), LevelGeometryService< order >::LevelGeometryService(), Proto::HostBoxData< Proto::CellNode, 1 >::linearIn(), Proto::EBHostData< cent, data_t, ncomp >::linearIn(), Proto::EBGraph::linearIn(), EBCM::EBCM_Graph< order >::linearIn(), CH4_SPMD::linearListIn(), CH4_SPMD::linearListOut(), Proto::HostBoxData< Proto::CellNode, 1 >::linearOut(), Proto::EBHostData< cent, data_t, ncomp >::linearOut(), Proto::EBGraph::linearOut(), BoxLayoutData< FArrayBox >::makeItSo(), EBCM::Algorithm_Framework< ebcm_order >::makeMergedGeometry(), EBCM::EBCM_Graph< order >::makeTheBlobs(), EBCM::EBCM_Graph< order >::mergeSmallVolumesWithNeighbors(), EBCM::SubVolumeVector< order >::operator()(), LayoutIndex::output(), IndexTM< T, N >::p(), ch_eigen::Matrix::poutAll(), ch_eigen::Matrix::poutDiag(), ch_eigen::Matrix::poutEigenvalues(), EBCM::Algorithm_Framework< ebcm_order >::condition_t::poutLatexTable(), ch_eigen::Matrix::poutMaxMins(), ch_eigen::Matrix::poutRow(), EBCM::EBCM_Face< cent, order >::print(), Proto::LocalStencil< cent, data_t >::print(), Proto::IndexedMoments< DIM-1, order >::print(), EBCM::IrregFace< order >::print(), EBCM::EBCM_Volu< order >::print(), BoxLayout::printBalance(), CH4_Data_Choreography::DistributedData< EBFluxData< Real, NUMCOMPS > >::printGrids(), CH4_Data_Choreography::BoxPattern::printStuff(), Proto::LocalStencil< cent, data_t >::printSum(), EBCM::Algorithm_Framework< ebcm_order >::run_hoeb_petsc_tests(), EBCM::Algorithm_Framework< ebcm_order >::shiftMomentAndFillRow(), EBCM::SubVolumeVector< order >::SubVolumeVector(), BaseFab< Real >::testBoxAndComp(), write(), and WriteMultiData< T >::writeData().
setPoutBaseName()
void setPoutBaseName (const std::string & a_Name)
Changes the base part of the filename for pout() files.
When in parallel, changes the base name of the pout() files. If pout() has already been called, it closes the current output file and opens a new one (unless the name is the same, in which case it does nothing). In serial, ignores the argument and does nothing.
poutFileName()
const std::string& poutFileName ()
Accesses the filename for the local pout() file.
Returns the name used for the local pout() file. In parallel this is "<pout_basename>.<procID>", where <pout_basename> defaults to "pout" and can be modified by calling setPoutBaseName(), and <procID> is the local proc number. In serial, this always returns the string "cout". It is an error (exit code 111) to call this in parallel before MPI_Initialize().