Chombo_4: Chombo_GeometryService.H File Reference
Chombo_GeometryService.H File Reference
#include "Chombo_EBChombo.H"
#include "Proto_MomentHolder.H"
#include "Chombo_LevelData.H"
#include "Chombo_EBDataChoreography.H"
#include "Chombo_AMRIO.H"
#include "Chombo_ProtoInterface.H"
#include "Chombo_BRMeshRefine.H"
#include "Chombo_LoadBalance.H"
#include "Chombo_ParmParse.H"
#include <memory>
#include "Chombo_NamespaceHeader.H"
#include "Chombo_GeometryServiceImplem.H"
#include "Chombo_NamespaceFooter.H"
Classes
struct typenameTag< CENTERING >
class LevelGeometryService< order >
class GeometryService< order >
Macros
#define _Chombo_GeometryService_H_
Functions
template<int order>
void fillFaceAlpha (EBHostData< XFACE, Real, 1 > &a_alpha, const Box &a_grbx, const DataIndex &a_dit, const LevelGeometryService< order > &a_geo)
template<int order>
void fillFaceAlpha (EBHostData< YFACE, Real, 1 > &a_alpha, const Box &a_grbx, const DataIndex &a_dit, const LevelGeometryService< order > &a_geo)
template<CENTERING cent, int order>
shared_ptr< CH4_Data_Choreography::DistributedData< HostIrregData< cent, IndexedMoments< DIM-1, order >, 1 > > > getFaceData (const shared_ptr< GeometryService< order > > &a_geoserv, const Box &a_domain, const EBIndex< cent > &a_dummy)
template<int order>
shared_ptr< CH4_Data_Choreography::DistributedData< HostIrregData< XFACE, IndexedMoments< DIM-1, order >, 1 > > > getFaceData (const shared_ptr< GeometryService< order > > &a_geoserv, const Box &a_domain, const EBIndex< XFACE > &a_dummy)
template<int order>
shared_ptr< CH4_Data_Choreography::DistributedData< HostIrregData< YFACE, IndexedMoments< DIM-1, order >, 1 > > > getFaceData (const shared_ptr< GeometryService< order > > &a_geoserv, const Box &a_domain, const EBIndex< YFACE > &a_dummy)
Macro Definition Documentation
_Chombo_GeometryService_H_
#define _Chombo_GeometryService_H_
Function Documentation
fillFaceAlpha() [1/2]
template<int order> void fillFaceAlpha (EBHostData< XFACE, Real, 1 > & a_alpha, const Box & a_grbx, const DataIndex & a_dit, const LevelGeometryService< order > & a_geo) inline
References LevelGeometryService< order >::dx(), LevelGeometryService< order >::getGraphs(), Proto::EBHostData< cent, data_t, ncomp >::getIrrData(), ProtoCh::getPoint(), Proto::EBHostData< cent, data_t, ncomp >::getRegData(), LevelGeometryService< order >::getXFaceData(), BoxIterator::ok(), and Proto::XFACE.
Referenced by fillFaceAlpha().
fillFaceAlpha() [2/2]
template<int order> void fillFaceAlpha (EBHostData< YFACE, Real, 1 > & a_alpha, const Box & a_grbx, const DataIndex & a_dit, const LevelGeometryService< order > & a_geo) inline
References LevelGeometryService< order >::dx(), fillFaceAlpha(), LevelGeometryService< order >::getGraphs(), Proto::EBHostData< cent, data_t, ncomp >::getIrrData(), ProtoCh::getPoint(), Proto::EBHostData< cent, data_t, ncomp >::getRegData(), LevelGeometryService< order >::getYFaceData(), LevelGeometryService< order >::getZFaceData(), and BoxIterator::ok().
getFaceData() [1/3]
template<CENTERING cent, int order> shared_ptr<CH4_Data_Choreography::DistributedData<HostIrregData<cent, IndexedMoments<DIM-1, order> , 1> > > getFaceData (const shared_ptr< GeometryService< order > > & a_geoserv, const Box & a_domain, const EBIndex< cent > & a_dummy) inline
References Proto::XFACE.
Referenced by getFaceData().
getFaceData() [2/3]
template<int order> shared_ptr<CH4_Data_Choreography::DistributedData<HostIrregData<XFACE, IndexedMoments<DIM-1, order> , 1> > > getFaceData (const shared_ptr< GeometryService< order > > & a_geoserv, const Box & a_domain, const EBIndex< XFACE > & a_dummy) inline
References Proto::YFACE.
getFaceData() [3/3]
template<int order> shared_ptr<CH4_Data_Choreography::DistributedData<HostIrregData<YFACE, IndexedMoments<DIM-1, order> , 1> > > getFaceData (const shared_ptr< GeometryService< order > > & a_geoserv, const Box & a_domain, const EBIndex< YFACE > & a_dummy) inline
References getFaceData(), and Proto::ZFACE.