Chombo_4: Chombo_IntVect.H File Reference
Chombo_IntVect.H File Reference
#include <cstddef>
#include <cstdlib>
#include <cstring>
#include <iostream>
#include <vector>
#include "Chombo_SPACE.H"
#include "Chombo_SPMD.H"
#include "Chombo_CH_assert.H"
#include <cstdint>
#include <functional>
#include "Proto.H"
#include "Chombo_NamespaceHeader.H"
#include "Chombo_NamespaceFooter.H"
Classes
class IntVect
An integer vector in SpaceDim-dimensional space.
struct std::less< IntVect >
Namespaces
BLfacade
std
CH4_SPMD
functions for linearization
Macros
#define _Chombo_INTVECT_H_
Functions
IntVect operator+ (int s, const IntVect &p)
IntVect operator- (int s, const IntVect &p)
IntVect operator* (int s, const IntVect &p)
IntVect scale (const IntVect &p, int s)
const IntVect absolute (const IntVect &p)
IntVect diagShift (const IntVect &p, int s)
IntVect min (const IntVect &p1, const IntVect &p2)
IntVect max (const IntVect &p1, const IntVect &p2)
IntVect BASISV (int dir)
IntVect reflect (const IntVect &a, int ref_ix, int idir)
IntVect coarsen (const IntVect &p, int s)
IntVect coarsen (const IntVect &p1, const IntVect &p2)
Macro Definition Documentation
_Chombo_INTVECT_H_
#define _Chombo_INTVECT_H_
Function Documentation
operator+()
IntVect operator+ (int s, const IntVect & p) inline
Returns an IntVect that is an IntVect p with a scalar s added to each component.
Referenced by IntVect::copy(), and Box::copy().
operator-()
IntVect operator- (int s, const IntVect & p) inline
Returns s - p.
Referenced by IntVect::copy(), and Box::copy().
operator*()
IntVect operator* (int s, const IntVect & p) inline
Returns an IntVect that is an IntVect p with each component multiplied by a scalar s.
Referenced by IntVect::copy().
scale()
IntVect scale (const IntVect & p, int s) inline
Returns an IntVect obtained by multiplying each of the components of the given IntVect by a scalar.
Referenced by IntVect::min().
absolute()
const IntVect absolute (const IntVect & p) inline
Referenced by IntVect::min().
diagShift()
IntVect diagShift (const IntVect & p, int s) inline
Returns IntVect obtained by adding a scalar to each of the components of the given IntVect.
Referenced by grow(), and IntVect::min().
min()
IntVect min (const IntVect & p1, const IntVect & p2) inline
Returns the IntVect that is the component-wise minimum of two argument IntVects.
References IntVect::min().
Referenced by Proto::IFData< dim >::BrentRootFinder(), EBCM::Algorithm_Framework< ebcm_order >::checkKappa(), IntVect::copy(), EBCM::EBCM_Graph< order >::makeTheBlobs(), IntVect::min(), and Proto::PointSet::minBox().
max()
IntVect max (const IntVect & p1, const IntVect & p2) inline
Returns the IntVect that is the component-wise maximum of two argument IntVects.
References IntVect::max().
Referenced by EBCM::Algorithm_Framework< ebcm_order >::checkKappa(), Proto::LSProblem< dim >::computeBounds(), IntVect::copy(), Proto::EBStencilArchive< CELL, CELL, order, double >::getIrregLocations(), IntVect::max(), EBLevelBoxData< cent, NUMCOMPS >::max(), Proto::IndexedMoments< DIM-1, order >::maxAbs(), Proto::maxCell(), Proto::EBHostFluxData< data_t, ncomp >::maxNorm(), EBLevelBoxData< cent, NUMCOMPS >::maxNorm(), Proto::maxNormCell(), EBLevelBoxData< cent, NUMCOMPS >::maxNormSplit(), IntVect::min(), EBLevelBoxData< cent, NUMCOMPS >::min(), Proto::PointSet::minBox(), and Proto::minCell().
BASISV()
IntVect BASISV (int dir) inline
Returns a basis vector in the given coordinate direction.
In 3-D: BASISV(0) == (1,0,0); BASISV(1) == (0,1,0); BASISV(2) == (0,0,1).
In 2-D: BASISV(0) == (1,0); BASISV(1) == (0,1).
Note that the coordinate directions are based at zero.
References CH_assert, SpaceDim, IntVect::vect, and IntVect::Zero.
Referenced by IntVect::min().
reflect()
IntVect reflect (const IntVect & a, int ref_ix, int idir) inline
Returns an IntVect that is the reflection of the given IntVect in the plane which passes through ref_ix and normal to the coordinate direction idir.
References CH_assert, SpaceDim, and IntVect::vect.
Referenced by IntVect::min().
coarsen() [1/2]
IntVect coarsen (const IntVect & p, int s) inline
Returns an IntVect that is the component-wise integer projection of p by s.
References CH_assert, and IntVect::vect.
Referenced by IntVect::min().
coarsen() [2/2]
IntVect coarsen (const IntVect & p1, const IntVect & p2) inline
Returns an IntVect which is the component-wise integer projection of IntVect p1 by IntVect p2.
References CH_assert, IntVect::vect, and IntVect::Zero.