Chombo_4: Chombo_EBLevelBoxData.H File Reference
Chombo_EBLevelBoxData.H File Reference
#include "Chombo_EBChombo.H"
#include "Chombo_LevelData.H"
#include "Chombo_AMRIO.H"
#include "Chombo_ProtoInterface.H"
#include "Chombo_ProtoFactories.H"
#include "Chombo_LevelBoxData.H"
#include "Chombo_SPMD.H"
#include "Proto_EBBoxData.H"
#include "Proto_EBHostData.H"
#include "Chombo_EBDataChoreography.H"
#include "Chombo_GeometryService.H"
#include <memory>
#include "Chombo_NamespaceHeader.H"
#include "Chombo_NamespaceFooter.H"
Classes
class ScalarAliasFactory< srcComp, dstComp >
class EBLevelBoxData< cent, NUMCOMPS >
Macros
#define _EBLEVELBoxDATA_H____
Functions
template<int NUMCOMPS>
void writeEBLevelHDF5 (const string &a_filename, const EBLevelBoxData< CELL, NUMCOMPS > &a_data, const EBLevelBoxData< CELL, 1 > &a_kapp, const Box &a_domain, shared_ptr< CH4_Data_Choreography::DistributedData< EBGraph > > a_graphs, Real a_coveredval=0.0, Real a_dx=1.0, Real a_dt=1.0, Real a_time=1.0, std::vector< std::string > a_varNames={})
write EB file so visit can recognize it as EB
Macro Definition Documentation
_EBLEVELBoxDATA_H____
#define _EBLEVELBoxDATA_H____
Function Documentation
writeEBLevelHDF5()
template<int NUMCOMPS> void writeEBLevelHDF5 (const string & a_filename, const EBLevelBoxData< CELL, NUMCOMPS > & a_data, const EBLevelBoxData< CELL, 1 > & a_kapp, const Box & a_domain, shared_ptr< CH4_Data_Choreography::DistributedData< EBGraph > > a_graphs, Real a_coveredval = 0.0, Real a_dx = 1.0, Real a_dt = 1.0, Real a_time = 1.0, std::vector< std::string > a_varNames = {}) inline
write EB file so visit can recognize it as EB
References EBLevelBoxData< cent, NUMCOMPS >::copyToHost(), CH4_Data_Choreography::DistributedData< EBBoxData< cent, Real, NUMCOMPS > >::disjointBoxLayout(), ProtoCh::getIntVect(), CH4_Data_Choreography::DistributedData< EBBoxData< cent, Real, NUMCOMPS > >::ghostVect(), Proto::EBGraph::isCovered(), Proto::EBIndex< cent >::m_isBoundary, Proto::EBIndex< cent >::m_pt, Proto::EBIndex< cent >::m_vofIDLo, Proto::EBIndex< cent >::m_vofIDMe, Proto::PointSetIterator::ok(), BaseFab< T >::setVal(), WriteAMRHierarchyHDF5(), and IntVect::Zero.