Chombo_4: Chombo_DisjointBoxLayout.H File Reference
Chombo_DisjointBoxLayout.H File Reference
#include "Chombo_BoxLayout.H"
#include "Chombo_ProblemDomain.H"
#include "Chombo_NamespaceHeader.H"
#include "Chombo_NamespaceFooter.H"
Classes
class DisjointBoxLayout
A BoxLayout that has a concept of disjointedness.
Macros
#define _Chombo_DISJOINTBOXLAYOUT_H_
Functions
void adjCellLo_dbl (DisjointBoxLayout &a_output, const DisjointBoxLayout &a_input, int a_dir, int a_len)
void adjCellHi_dbl (DisjointBoxLayout &a_output, const DisjointBoxLayout &a_input, int a_dir, int a_len)
void coarsen_dbl (DisjointBoxLayout &output, const DisjointBoxLayout &input, int refinement)
void refine_dbl (DisjointBoxLayout &output, const DisjointBoxLayout &input, int refinement)
void adjCellLo (DisjointBoxLayout &a_output, const DisjointBoxLayout &a_input, int a_dir, int a_len=1)
void adjCellHi (DisjointBoxLayout &a_output, const DisjointBoxLayout &a_input, int a_dir, int a_len=1)
Macro Definition Documentation
_Chombo_DISJOINTBOXLAYOUT_H_
#define _Chombo_DISJOINTBOXLAYOUT_H_
Function Documentation
adjCellLo_dbl()
void adjCellLo_dbl (DisjointBoxLayout & a_output, const DisjointBoxLayout & a_input, int a_dir, int a_len) inline
References adjCellLo().
adjCellHi_dbl()
void adjCellHi_dbl (DisjointBoxLayout & a_output, const DisjointBoxLayout & a_input, int a_dir, int a_len) inline
References adjCellHi().
coarsen_dbl()
void coarsen_dbl (DisjointBoxLayout & output, const DisjointBoxLayout & input, int refinement) inline
References BoxLayout::coarsen.
refine_dbl()
void refine_dbl (DisjointBoxLayout & output, const DisjointBoxLayout & input, int refinement) inline
References adjCellHi(), adjCellLo(), DisjointBoxLayout::DisjointBoxLayout(), and BoxLayout::refine().
adjCellLo()
void adjCellLo (DisjointBoxLayout & a_output, const DisjointBoxLayout & a_input, int a_dir, int a_len = 1)
Returns the set of boxes which you get from calling Box::adjCellLo on each box in input. Output must be open, is closed upon exit from this function. A negative length results in the set of boxes of width a_len on the low side of, but inside the original boxes.
Referenced by adjCellLo_dbl(), refine_dbl(), and DisjointBoxLayout::setDomain().
adjCellHi()
void adjCellHi (DisjointBoxLayout & a_output, const DisjointBoxLayout & a_input, int a_dir, int a_len = 1)
Returns the set of boxes which result from calling Box::adjCellHi on each box in input. Output must be open, will be closed upon exiting this function. A negative length results in the set of boxes of width a_len on the low side of, but inside the original boxes.
Referenced by adjCellHi_dbl(), refine_dbl(), and DisjointBoxLayout::setDomain().