Chombo_4: Chombo_HDF5Portable.H File Reference
Chombo_HDF5Portable.H File Reference
#include <vector>
#include <hdf5.h>
#include "Chombo_Box.H"
#include "Chombo_Interval.H"
#include "Chombo_NamespaceHeader.H"
#include "Chombo_NamespaceFooter.H"
Macros
#define _Chombo_HDF5PORTABLE_H_
Functions
template<class T >
void dataTypes (std::vector< hid_t > &a_types, const T &a_dummySpecializationArg)
template<class T >
void dataSize (const T &a_item, std::vector< int > &a_sizes, const Box &a_box, const Interval &a_comps)
template<class T >
void write (const T &a_item, std::vector< void *> &a_allocatedBuffers, const Box &a_box, const Interval &a_comps)
template<class T >
void read (T &a_item, std::vector< void *> &a_allocatedBuffers, const Box &a_box, const Interval &a_comps)
template<class T >
const char * name (const T &a_dummySpecializationArg)
Macro Definition Documentation
_Chombo_HDF5PORTABLE_H_
#define _Chombo_HDF5PORTABLE_H_
Function Documentation
dataTypes()
template<class T > void dataTypes (std::vector< hid_t > & a_types, const T & a_dummySpecializationArg) inline
dataSize()
template<class T > void dataSize (const T & a_item, std::vector< int > & a_sizes, const Box & a_box, const Interval & a_comps) inline
References Interval::begin(), and Interval::size().
write()
template<class T > void write (const T & a_item, std::vector< void *> & a_allocatedBuffers, const Box & a_box, const Interval & a_comps) inline
References Interval::begin(), and Interval::size().
read()
template<class T > void read (T & a_item, std::vector< void *> & a_allocatedBuffers, const Box & a_box, const Interval & a_comps) inline
References Interval::begin(), and Interval::size().
name()
template<class T > const char* name (const T & a_dummySpecializationArg) inline
References name().