Chombo_4: Chombo_BoxLayout.H File Reference
Chombo_BoxLayout.H File Reference
#include "Chombo_Box.H"
#include "Chombo_RefCountedPtr.H"
#include "Chombo_DataIndex.H"
#include "Chombo_SPMD.H"
#include "Chombo_LoHiSide.H"
#include "Chombo_ProblemDomain.H"
#include "Chombo_NamespaceHeader.H"
#include "Chombo_NamespaceFooter.H"
Classes
class BaseTransform
Base class to transform boxes in an existing layout.
struct Entry
class BoxLayout
A not-necessarily-disjoint collective of boxes.
Macros
#define _Chombo_BOXLAYOUT_H_
Functions
void coarsen_bl (BoxLayout &output, const BoxLayout &input, int refinement)
void refine_bl (BoxLayout &output, const BoxLayout &input, int refinement)
void mortonOrdering (std::vector< Box > &a_boxes)
void serialMortonOrdering (std::vector< Box > &a_boxes)
std::ostream & operator<< (std::ostream &os, const BoxLayout &a_layout)
Macro Definition Documentation
_Chombo_BOXLAYOUT_H_
#define _Chombo_BOXLAYOUT_H_
Function Documentation
coarsen_bl()
void coarsen_bl (BoxLayout & output, const BoxLayout & input, int refinement) inline
References coarsen().
refine_bl()
void refine_bl (BoxLayout & output, const BoxLayout & input, int refinement) inline
References mortonOrdering(), refine(), and serialMortonOrdering().
mortonOrdering()
void mortonOrdering (std::vector< Box > & a_boxes)
Referenced by refine_bl().
serialMortonOrdering()
void serialMortonOrdering (std::vector< Box > & a_boxes)
Referenced by refine_bl().
operator<<()
std::ostream& operator<< (std::ostream & os, const BoxLayout & a_layout)
Referenced by Box::coarsenable(), IntVect::min(), ProblemDomain::operator<(), and BoxLayout::setProcID().