Chombo_4: Chombo_BFM.H File Reference
Chombo_BFM.H File Reference
#include "Chombo_Box.H"
#include "Chombo_NamespaceHeader.H"
#include "Chombo_NamespaceFooter.H"
Classes
struct BFMImpl< D, T1, T2, F >
struct BFMImpl< 0, T1, T2, F >
struct BFMImpl1< D, T1, F >
struct BFMImpl1< 0, T1, F >
Macros
#define _Chombo_BFM_H_
Functions
template<unsigned char R>
void rcount (int *c, const Box &r)
template<>
void rcount< 0 > (int *c, const Box &r)
template<unsigned char R>
void gridStride (int *stride, int *lo, const Box &b, const Box &r)
template<>
void gridStride< 0 > (int *stride, int *lo, const Box &b, const Box &r)
template<unsigned char D, typename T1 , typename T2 , typename F >
void BFM (T1 *__restrict t1, const T2 *__restrict t2, const Box &b1, const Box &b2, int c1, int c2, int ncomp, const Box &r, F f)
This is the user template meta program function, everything above here is to support this function.
template<unsigned char D, typename T1 , typename F >
void BFM1 (T1 *__restrict t1, const Box &b1, int c1, int ncomp, const Box &r, F f)
Macro Definition Documentation
_Chombo_BFM_H_
#define _Chombo_BFM_H_
Function Documentation
rcount()
template<unsigned char R> void rcount (int * c, const Box & r) inline
References Box::bigEnd(), and Box::smallEnd().
Referenced by BFM(), and BFM1().
rcount< 0 >()
template<> void rcount< 0 > (int * c, const Box & r) inline
gridStride()
template<unsigned char R> void gridStride (int * stride, int * lo, const Box & b, const Box & r) inline
References Box::smallEnd().
Referenced by BFM(), and BFM1().
gridStride< 0 >()
template<> void gridStride< 0 > (int * stride, int * lo, const Box & b, const Box & r) inline
BFM()
template<unsigned char D, typename T1 , typename T2 , typename F > void BFM (T1 *__restrict t1, const T2 *__restrict t2, const Box & b1, const Box & b2, int c1, int c2, int ncomp, const Box & r, F f)
This is the user template meta program function, everything above here is to support this function.
Example usage of BFM template meta-program. the performCopy operation that I made for CFArrayBox in Chombo 3
void CFArrayBox::performCopy(const BaseFab<Complex>& a_src, const Box& a_srcbox, int a_srccomp, const Box& a_destbox, int a_destcomp, int a_numcomp) { BaseFab<Complex>::performCopy(a_src, a_srcbox, a_srccomp, a_destbox, a_destcomp, a_numcomp); Box r = a_srcbox BFM<CH_SPACEDIM>(dataPtr(),a_src.dataPtr(), box(), a_src.box(), a_destcomp, a_srccomp,a_numcomp,r, [](Complex* restrict d, Complex s){(*d)=s;}); }
References CH_assert, Box::contains(), D, BFMImpl< D, T1, T2, F >::f(), gridStride(), and rcount().
BFM1()
template<unsigned char D, typename T1 , typename F > void BFM1 (T1 *__restrict t1, const Box & b1, int c1, int ncomp, const Box & r, F f)
References CH_assert, Box::contains(), D, BFMImpl1< D, T1, F >::f(), gridStride(), and rcount().