Chombo_4: EBCM::PETSc_Framework< ebcm_order > Class Template Reference
EBCM::PETSc_Framework< ebcm_order > Class Template Reference
#include <Chombo_EBCM_PETSc_Framework.H>
Classes
class Base_PETSc_Op
class DummyDerivedOp
class HelmholtzOp
struct local_stencil_t
Public Types
typedef Chombo4::Box ch_box
typedef Chombo4::DisjointBoxLayout ch_dbl
typedef Chombo4::BoxIterator ch_bit
typedef Chombo4::IntVect ch_iv
typedef Chombo4::DataIterator ch_dit
typedef ::Mat petsc_mat
typedef Proto::Point pr_pt
typedef EBCM::MetaDataLevel< ebcm_order > ebcm_meta
typedef EBCM::EBCM_Graph< ebcm_order > ebcm_graph
typedef EBCM::HostLevelData< int, 1, ebcm_order > ebcm_data
typedef EBCM::SubVolumeVector< ebcm_order > ebcm_subvol_vec
typedef EBCM::Algorithm_Framework< ebcm_order > ebcm_framework
Static Public Member Functions
template<CENTERING cent>
static local_stencil_t getHelmholtzFluxStencil (const EBCM_Face< cent, ebcm_order > &a_face, const int &a_facedir)
static void run_hoeb_truncation_tests ()
test function for example/EBCM/hoeb_truncation
Member Typedef Documentation
ch_box
template<int ebcm_order> typedef Chombo4::Box EBCM::PETSc_Framework< ebcm_order >::ch_box
ch_dbl
template<int ebcm_order> typedef Chombo4::DisjointBoxLayout EBCM::PETSc_Framework< ebcm_order >::ch_dbl
ch_bit
template<int ebcm_order> typedef Chombo4::BoxIterator EBCM::PETSc_Framework< ebcm_order >::ch_bit
ch_iv
template<int ebcm_order> typedef Chombo4::IntVect EBCM::PETSc_Framework< ebcm_order >::ch_iv
ch_dit
template<int ebcm_order> typedef Chombo4::DataIterator EBCM::PETSc_Framework< ebcm_order >::ch_dit
petsc_mat
template<int ebcm_order> typedef ::Mat EBCM::PETSc_Framework< ebcm_order >::petsc_mat
pr_pt
template<int ebcm_order> typedef Proto::Point EBCM::PETSc_Framework< ebcm_order >::pr_pt
ebcm_meta
template<int ebcm_order> typedef EBCM::MetaDataLevel<ebcm_order> EBCM::PETSc_Framework< ebcm_order >::ebcm_meta
ebcm_graph
template<int ebcm_order> typedef EBCM::EBCM_Graph<ebcm_order> EBCM::PETSc_Framework< ebcm_order >::ebcm_graph
ebcm_data
template<int ebcm_order> typedef EBCM::HostLevelData<int, 1, ebcm_order> EBCM::PETSc_Framework< ebcm_order >::ebcm_data
ebcm_subvol_vec
template<int ebcm_order> typedef EBCM::SubVolumeVector< ebcm_order> EBCM::PETSc_Framework< ebcm_order >::ebcm_subvol_vec
ebcm_framework
template<int ebcm_order> typedef EBCM::Algorithm_Framework< ebcm_order> EBCM::PETSc_Framework< ebcm_order >::ebcm_framework
Member Function Documentation
getHelmholtzFluxStencil()
template<int ebcm_order> template<CENTERING cent> static local_stencil_t EBCM::PETSc_Framework< ebcm_order >::getHelmholtzFluxStencil (const EBCM_Face< cent, ebcm_order > & a_face, const int & a_facedir) inline static
Referenced by EBCM::PETSc_Framework< ebcm_order >::HelmholtzOp::getLocalStencil().
run_hoeb_truncation_tests()
template<int ebcm_order> static void EBCM::PETSc_Framework< ebcm_order >::run_hoeb_truncation_tests () inline static
test function for example/EBCM/hoeb_truncation
testing compilation of the base framework
Helmholtz operator declaration
References ParmParse::get(), and EBCM::Algorithm_Framework< ebcm_order >::makeMergedGeometry().
The documentation for this class was generated from the following file:
Chombo_EBCM_PETSc_Framework.H