Chombo_4: TimedDataIterator Class Reference
TimedDataIterator Class Reference
#include <Chombo_TimedDataIterator.H>
Public Member Functions
virtual ~TimedDataIterator ()
virtual bool ok () const
virtual void operator++ ()
void clearTime ()
sets m_time values to zero
std::vector< unsigned long long > & getTime ()
gets current time data
std::vector< Box > getBoxes ()
const std::vector< unsigned long long > & getTime () const
gets current time data in microseconds
void enableTime ()
enables timing. does not set to zero. use clear time for that
void disableTime ()
turns off timing
void mergeTime ()
After you are finished timing your local elements, call mergeTimes to fill-in off-processor times.
Private Member Functions
void defineTime ()
TimedDataIterator ()
TimedDataIterator (const BoxLayout &boxlayout, const int *layoutID)
Private Attributes
int m_size
std::vector< unsigned long long > m_time
bool m_timeEnabled
bool m_timeDefined
unsigned long long m_startTime
int m_ibox
Friends
class BoxLayout
class DisjointBoxLayout
Constructor & Destructor Documentation
~TimedDataIterator()
virtual TimedDataIterator::~TimedDataIterator () inline virtual
References clearTime(), ok(), and operator++().
TimedDataIterator() [1/2]
TimedDataIterator::TimedDataIterator () private
TimedDataIterator() [2/2]
TimedDataIterator::TimedDataIterator (const BoxLayout & boxlayout, const int * layoutID) private
Member Function Documentation
ok()
virtual bool TimedDataIterator::ok () const virtual
Referenced by ~TimedDataIterator().
operator++()
virtual void TimedDataIterator::operator++ () virtual
Referenced by ~TimedDataIterator().
clearTime()
void TimedDataIterator::clearTime ()
sets m_time values to zero
Referenced by ~TimedDataIterator().
getTime() [1/2]
std::vector<unsigned long long>& TimedDataIterator::getTime () inline
gets current time data
References m_time.
getBoxes()
std::vector<Box> TimedDataIterator::getBoxes () inline
getTime() [2/2]
const std::vector<unsigned long long>& TimedDataIterator::getTime () const inline
gets current time data in microseconds
References m_time.
enableTime()
void TimedDataIterator::enableTime () inline
enables timing. does not set to zero. use clear time for that
References defineTime(), and m_timeEnabled.
disableTime()
void TimedDataIterator::disableTime () inline
turns off timing
References m_timeEnabled, and mergeTime().
mergeTime()
void TimedDataIterator::mergeTime ()
After you are finished timing your local elements, call mergeTimes to fill-in off-processor times.
Referenced by disableTime().
defineTime()
void TimedDataIterator::defineTime () private
Referenced by enableTime().
Friends And Related Function Documentation
BoxLayout
friend class BoxLayout friend
DisjointBoxLayout
friend class DisjointBoxLayout friend
Member Data Documentation
m_size
int TimedDataIterator::m_size private
m_time
std::vector<unsigned long long> TimedDataIterator::m_time private
Referenced by getTime().
m_timeEnabled
bool TimedDataIterator::m_timeEnabled private
Referenced by disableTime(), and enableTime().
m_timeDefined
bool TimedDataIterator::m_timeDefined private
m_startTime
unsigned long long TimedDataIterator::m_startTime private
m_ibox
int TimedDataIterator::m_ibox private
The documentation for this class was generated from the following file:
Chombo_TimedDataIterator.H