Chombo_4: Proto::IrregData< cent, data_t, ncomp > Class Template Reference
Proto::IrregData< cent, data_t, ncomp > Class Template Reference
#include <Proto_IrregData.H>
Public Types
typedef EBIndex< cent > index_t
Public Member Functions
IrregData ()
int nComp () const
to conform with mpi interface
IrregData (Box a_box, data_t *a_data, std::vector< index_t > &a_indicies)
constructor by copying
virtual ~IrregData ()
IrregData (const Box &a_box, bool a_stackAllocation=true)
needed for leveldata
std::size_t size () const
bool defined () const
void setVal (const data_t &a_val)
data_t * dataPtr (unsigned int a_ivar=0)
const data_t * dataPtr (unsigned int a_ivar=0) const
data_t * data ()
const data_t * data () const
size_t index (const EBIndex< cent > &a_vof, const int &a_ivar) const
IrregData< cent, data_t, ncomp > & operator+= (const IrregData< cent, data_t, ncomp > &a_input)
IrregData< cent, data_t, ncomp > & operator-= (const IrregData< cent, data_t, ncomp > &a_input)
IrregData< cent, data_t, ncomp > & operator*= (const IrregData< cent, data_t, ncomp > &a_input)
IrregData< cent, data_t, ncomp > & operator/= (const IrregData< cent, data_t, ncomp > &a_input)
data_t operator() (const index_t &a_vof, int a_comp) const
debugging only–will not work on the device
vector< EBIndex< cent > > getIndices () const
unsigned int vecsize () const
Box inputBox () const
template<unsigned int srccomp>
void define (IrregData< cent, data_t, srccomp > &a_input, unsigned int &a_comp)
shared_ptr< vector< index_t > > getIndicies () const
shared_ptr< data_t > getData () const
void define (const Box &a_box, const EBGraph &a_graph)
void defineEBIrregData ()
EBIrregStruct< cent, data_t, ncomp > * getEBIrregDataPtr ()
bool hasIndex (const EBIndex< cent > &a_ind) const
Protected Member Functions
void define (const shared_ptr< vector< index_t > > &a_indicies)
IrregData (const IrregData< cent, data_t, ncomp > &a_src)
IrregData & operator= (const IrregData< cent, data_t, ncomp > &a_src)
Protected Attributes
bool m_boxdefined
for fast forall
Box m_inputBox
shared_ptr< vector< index_t > > m_indicies = nullptr
shared_ptr< data_t > m_data = nullptr
data_t * m_rawPtr = nullptr
EBIrregStruct< cent, data_t, ncomp > * m_EBIrregDataPtr = nullptr
Member Typedef Documentation
index_t
template<CENTERING cent, class data_t, unsigned int ncomp> typedef EBIndex<cent> Proto::IrregData< cent, data_t, ncomp >::index_t
Constructor & Destructor Documentation
IrregData() [1/4]
template<CENTERING cent, class data_t, unsigned int ncomp> Proto::IrregData< cent, data_t, ncomp >::IrregData () inline
References Proto::IrregData< cent, data_t, ncomp >::m_boxdefined.
IrregData() [2/4]
template<CENTERING cent, class data_t, unsigned int ncomp> Proto::IrregData< cent, data_t, ncomp >::IrregData (Box a_box, data_t * a_data, std::vector< index_t > & a_indicies) inline
constructor by copying
References Proto::IrregData< cent, data_t, ncomp >::defineEBIrregData(), Proto::IrregData< cent, data_t, ncomp >::m_data, Proto::IrregData< cent, data_t, ncomp >::m_indicies, Proto::IrregData< cent, data_t, ncomp >::m_inputBox, Proto::IrregData< cent, data_t, ncomp >::m_rawPtr, and Proto::IrregData< cent, data_t, ncomp >::size().
~IrregData()
template<CENTERING cent, class data_t, unsigned int ncomp> virtual Proto::IrregData< cent, data_t, ncomp >::~IrregData () inline virtual
IrregData() [3/4]
template<CENTERING cent, class data_t, unsigned int ncomp> Proto::IrregData< cent, data_t, ncomp >::IrregData (const Box & a_box, bool a_stackAllocation = true) inline
needed for leveldata
IrregData() [4/4]
template<CENTERING cent, class data_t, unsigned int ncomp> Proto::IrregData< cent, data_t, ncomp >::IrregData (const IrregData< cent, data_t, ncomp > & a_src) protected
Member Function Documentation
nComp()
template<CENTERING cent, class data_t, unsigned int ncomp> int Proto::IrregData< cent, data_t, ncomp >::nComp () const inline
to conform with mpi interface
size()
template<CENTERING cent, class data_t, unsigned int ncomp> std::size_t Proto::IrregData< cent, data_t, ncomp >::size () const inline
References Proto::IrregData< cent, data_t, ncomp >::m_boxdefined, and Proto::IrregData< cent, data_t, ncomp >::m_indicies.
Referenced by Proto::IrregData< cent, data_t, ncomp >::index(), Proto::IrregData< cent, data_t, ncomp >::IrregData(), Proto::IrregData< cent, data_t, ncomp >::operator*=(), Proto::IrregData< cent, data_t, ncomp >::operator+=(), Proto::IrregData< cent, data_t, ncomp >::operator-=(), and Proto::IrregData< cent, data_t, ncomp >::operator/=().
defined()
template<CENTERING cent, class data_t, unsigned int ncomp> bool Proto::IrregData< cent, data_t, ncomp >::defined () const inline
References Proto::IrregData< cent, data_t, ncomp >::m_data, and Proto::IrregData< cent, data_t, ncomp >::setVal().
setVal()
template<CENTERING cent, class data_t , unsigned int ncomp> void Proto::IrregData< cent, data_t, ncomp >::setVal (const data_t & a_val) inline
Referenced by Proto::IrregData< cent, data_t, ncomp >::define(), and Proto::IrregData< cent, data_t, ncomp >::defined().
dataPtr() [1/2]
template<CENTERING cent, class data_t, unsigned int ncomp> data_t* Proto::IrregData< cent, data_t, ncomp >::dataPtr (unsigned int a_ivar = 0) inline
References Proto::IrregData< cent, data_t, ncomp >::m_indicies, and Proto::IrregData< cent, data_t, ncomp >::m_rawPtr.
Referenced by Proto::HostIrregData< cent, data_t, ncomp >::define(), and Proto::IrregData< cent, data_t, ncomp >::define().
dataPtr() [2/2]
template<CENTERING cent, class data_t, unsigned int ncomp> const data_t* Proto::IrregData< cent, data_t, ncomp >::dataPtr (unsigned int a_ivar = 0) const inline
References Proto::IrregData< cent, data_t, ncomp >::m_indicies, and Proto::IrregData< cent, data_t, ncomp >::m_rawPtr.
data() [1/2]
template<CENTERING cent, class data_t, unsigned int ncomp> data_t* Proto::IrregData< cent, data_t, ncomp >::data () inline
References Proto::IrregData< cent, data_t, ncomp >::m_rawPtr.
Referenced by Proto::getEBIrregStruct().
data() [2/2]
template<CENTERING cent, class data_t, unsigned int ncomp> const data_t* Proto::IrregData< cent, data_t, ncomp >::data () const inline
References Proto::IrregData< cent, data_t, ncomp >::m_rawPtr.
index()
template<CENTERING cent, class data_t, unsigned int ncomp> size_t Proto::IrregData< cent, data_t, ncomp >::index (const EBIndex< cent > & a_vof, const int & a_ivar) const inline
References Proto::IrregData< cent, data_t, ncomp >::m_indicies, and Proto::IrregData< cent, data_t, ncomp >::size().
Referenced by Proto::getEBIrregStruct(), and Proto::IrregData< cent, data_t, ncomp >::operator()().
operator+=()
template<CENTERING cent, class data_t, unsigned int ncomp> IrregData<cent, data_t, ncomp>& Proto::IrregData< cent, data_t, ncomp >::operator+= (const IrregData< cent, data_t, ncomp > & a_input) inline
References Proto::IrregData< cent, data_t, ncomp >::m_inputBox, Proto::IrregData< cent, data_t, ncomp >::m_rawPtr, and Proto::IrregData< cent, data_t, ncomp >::size().
operator-=()
template<CENTERING cent, class data_t, unsigned int ncomp> IrregData<cent, data_t, ncomp>& Proto::IrregData< cent, data_t, ncomp >::operator-= (const IrregData< cent, data_t, ncomp > & a_input) inline
References Proto::IrregData< cent, data_t, ncomp >::m_boxdefined, Proto::IrregData< cent, data_t, ncomp >::m_inputBox, Proto::IrregData< cent, data_t, ncomp >::m_rawPtr, and Proto::IrregData< cent, data_t, ncomp >::size().
operator*=()
template<CENTERING cent, class data_t, unsigned int ncomp> IrregData<cent, data_t, ncomp>& Proto::IrregData< cent, data_t, ncomp >::operator*= (const IrregData< cent, data_t, ncomp > & a_input) inline
References Proto::IrregData< cent, data_t, ncomp >::m_boxdefined, Proto::IrregData< cent, data_t, ncomp >::m_inputBox, Proto::IrregData< cent, data_t, ncomp >::m_rawPtr, and Proto::IrregData< cent, data_t, ncomp >::size().
operator/=()
template<CENTERING cent, class data_t, unsigned int ncomp> IrregData<cent, data_t, ncomp>& Proto::IrregData< cent, data_t, ncomp >::operator/= (const IrregData< cent, data_t, ncomp > & a_input) inline
References Proto::IrregData< cent, data_t, ncomp >::m_boxdefined, Proto::IrregData< cent, data_t, ncomp >::m_inputBox, Proto::IrregData< cent, data_t, ncomp >::m_rawPtr, and Proto::IrregData< cent, data_t, ncomp >::size().
operator()()
template<CENTERING cent, class data_t, unsigned int ncomp> data_t Proto::IrregData< cent, data_t, ncomp >::operator() (const index_t & a_vof, int a_comp) const inline
debugging only–will not work on the device
References Proto::IrregData< cent, data_t, ncomp >::index(), and Proto::IrregData< cent, data_t, ncomp >::m_rawPtr.
getIndices()
template<CENTERING cent, class data_t, unsigned int ncomp> vector<EBIndex<cent> > Proto::IrregData< cent, data_t, ncomp >::getIndices () const inline
References Proto::IrregData< cent, data_t, ncomp >::m_indicies.
vecsize()
template<CENTERING cent, class data_t, unsigned int ncomp> unsigned int Proto::IrregData< cent, data_t, ncomp >::vecsize () const inline
References Proto::IrregData< cent, data_t, ncomp >::m_boxdefined, and Proto::IrregData< cent, data_t, ncomp >::m_indicies.
Referenced by Proto::getEBIrregStruct(), Proto::protoEBForAllIrreg(), and Proto::protoEBForAllIrreg_i().
inputBox()
template<CENTERING cent, class data_t, unsigned int ncomp> Box Proto::IrregData< cent, data_t, ncomp >::inputBox () const inline
References Proto::IrregData< cent, data_t, ncomp >::m_inputBox.
Referenced by Proto::HostIrregData< cent, data_t, ncomp >::define(), and Proto::IrregData< cent, data_t, ncomp >::define().
define() [1/3]
template<CENTERING cent, class data_t, unsigned int ncomp> template<unsigned int srccomp> void Proto::IrregData< cent, data_t, ncomp >::define (IrregData< cent, data_t, srccomp > & a_input, unsigned int & a_comp) inline
References Proto::IrregData< cent, data_t, ncomp >::dataPtr(), Proto::IrregData< cent, data_t, ncomp >::defineEBIrregData(), Proto::IrregData< cent, data_t, ncomp >::getData(), Proto::IrregData< cent, data_t, ncomp >::getIndicies(), Proto::IrregData< cent, data_t, ncomp >::inputBox(), Proto::IrregData< cent, data_t, ncomp >::m_boxdefined, Proto::IrregData< cent, data_t, ncomp >::m_data, Proto::IrregData< cent, data_t, ncomp >::m_indicies, Proto::IrregData< cent, data_t, ncomp >::m_inputBox, and Proto::IrregData< cent, data_t, ncomp >::m_rawPtr.
Referenced by Proto::IrregData< cent, data_t, ncomp >::define(), and Proto::IrregData< cent, data_t, ncomp >::hasIndex().
getIndicies()
template<CENTERING cent, class data_t, unsigned int ncomp> shared_ptr<vector< index_t > > Proto::IrregData< cent, data_t, ncomp >::getIndicies () const inline
References Proto::IrregData< cent, data_t, ncomp >::m_indicies.
Referenced by Proto::HostIrregData< cent, data_t, ncomp >::define(), and Proto::IrregData< cent, data_t, ncomp >::define().
getData()
template<CENTERING cent, class data_t, unsigned int ncomp> shared_ptr<data_t> Proto::IrregData< cent, data_t, ncomp >::getData () const inline
References Proto::IrregData< cent, data_t, ncomp >::m_data.
Referenced by Proto::HostIrregData< cent, data_t, ncomp >::define(), and Proto::IrregData< cent, data_t, ncomp >::define().
define() [2/3]
template<CENTERING cent, class data_t, unsigned int ncomp> void Proto::IrregData< cent, data_t, ncomp >::define (const Box & a_box, const EBGraph & a_graph) inline
References Proto::IrregData< cent, data_t, ncomp >::define(), Proto::IrregData< cent, data_t, ncomp >::defineEBIrregData(), Proto::EBGraph::getDomain(), Proto::IrregData< cent, data_t, ncomp >::m_boxdefined, and Proto::IrregData< cent, data_t, ncomp >::m_inputBox.
defineEBIrregData()
template<CENTERING cent, class data_t, unsigned int ncomp> void Proto::IrregData< cent, data_t, ncomp >::defineEBIrregData () inline
References Proto::getEBIrregStruct(), Proto::IrregData< cent, data_t, ncomp >::m_EBIrregDataPtr, and Proto::IrregData< cent, data_t, ncomp >::m_indicies.
Referenced by Proto::IrregData< cent, data_t, ncomp >::define(), and Proto::IrregData< cent, data_t, ncomp >::IrregData().
getEBIrregDataPtr()
template<CENTERING cent, class data_t, unsigned int ncomp> EBIrregStruct<cent, data_t, ncomp>* Proto::IrregData< cent, data_t, ncomp >::getEBIrregDataPtr () inline
References Proto::IrregData< cent, data_t, ncomp >::m_EBIrregDataPtr.
Referenced by Proto::protogetEBIrregStruct().
hasIndex()
template<CENTERING cent, class data_t, unsigned int ncomp> bool Proto::IrregData< cent, data_t, ncomp >::hasIndex (const EBIndex< cent > & a_ind) const inline
References Proto::IrregData< cent, data_t, ncomp >::define(), and Proto::IrregData< cent, data_t, ncomp >::m_indicies.
define() [3/3]
template<CENTERING cent, class data_t , unsigned int ncomp> void Proto::IrregData< cent, data_t, ncomp >::define (const shared_ptr< vector< index_t > > & a_indicies) inline protected
References Proto::IrregData< cent, data_t, ncomp >::setVal().
operator=()
template<CENTERING cent, class data_t, unsigned int ncomp> IrregData& Proto::IrregData< cent, data_t, ncomp >::operator= (const IrregData< cent, data_t, ncomp > & a_src) protected
Member Data Documentation
m_boxdefined
template<CENTERING cent, class data_t, unsigned int ncomp> bool Proto::IrregData< cent, data_t, ncomp >::m_boxdefined protected
for fast forall
Referenced by Proto::IrregData< cent, data_t, ncomp >::define(), Proto::IrregData< cent, data_t, ncomp >::IrregData(), Proto::IrregData< cent, data_t, ncomp >::operator*=(), Proto::IrregData< cent, data_t, ncomp >::operator-=(), Proto::IrregData< cent, data_t, ncomp >::operator/=(), Proto::IrregData< cent, data_t, ncomp >::size(), and Proto::IrregData< cent, data_t, ncomp >::vecsize().
m_inputBox
template<CENTERING cent, class data_t, unsigned int ncomp> Box Proto::IrregData< cent, data_t, ncomp >::m_inputBox protected
Referenced by Proto::IrregData< cent, data_t, ncomp >::define(), Proto::IrregData< cent, data_t, ncomp >::inputBox(), Proto::IrregData< cent, data_t, ncomp >::IrregData(), Proto::IrregData< cent, data_t, ncomp >::operator*=(), Proto::IrregData< cent, data_t, ncomp >::operator+=(), Proto::IrregData< cent, data_t, ncomp >::operator-=(), and Proto::IrregData< cent, data_t, ncomp >::operator/=().
m_indicies
template<CENTERING cent, class data_t, unsigned int ncomp> shared_ptr<vector< index_t > > Proto::IrregData< cent, data_t, ncomp >::m_indicies = nullptr protected
Referenced by Proto::IrregData< cent, data_t, ncomp >::dataPtr(), Proto::IrregData< cent, data_t, ncomp >::define(), Proto::IrregData< cent, data_t, ncomp >::defineEBIrregData(), Proto::IrregData< cent, data_t, ncomp >::getIndices(), Proto::IrregData< cent, data_t, ncomp >::getIndicies(), Proto::IrregData< cent, data_t, ncomp >::hasIndex(), Proto::IrregData< cent, data_t, ncomp >::index(), Proto::IrregData< cent, data_t, ncomp >::IrregData(), Proto::IrregData< cent, data_t, ncomp >::size(), and Proto::IrregData< cent, data_t, ncomp >::vecsize().
m_data
template<CENTERING cent, class data_t, unsigned int ncomp> shared_ptr<data_t> Proto::IrregData< cent, data_t, ncomp >::m_data = nullptr protected
Referenced by Proto::IrregData< cent, data_t, ncomp >::define(), Proto::IrregData< cent, data_t, ncomp >::defined(), Proto::IrregData< cent, data_t, ncomp >::getData(), and Proto::IrregData< cent, data_t, ncomp >::IrregData().
m_rawPtr
template<CENTERING cent, class data_t, unsigned int ncomp> data_t* Proto::IrregData< cent, data_t, ncomp >::m_rawPtr = nullptr protected
Referenced by Proto::IrregData< cent, data_t, ncomp >::data(), Proto::IrregData< cent, data_t, ncomp >::dataPtr(), Proto::IrregData< cent, data_t, ncomp >::define(), Proto::IrregData< cent, data_t, ncomp >::IrregData(), Proto::IrregData< cent, data_t, ncomp >::operator()(), Proto::IrregData< cent, data_t, ncomp >::operator*=(), Proto::IrregData< cent, data_t, ncomp >::operator+=(), Proto::IrregData< cent, data_t, ncomp >::operator-=(), and Proto::IrregData< cent, data_t, ncomp >::operator/=().
m_EBIrregDataPtr
template<CENTERING cent, class data_t, unsigned int ncomp> EBIrregStruct<cent, data_t, ncomp>* Proto::IrregData< cent, data_t, ncomp >::m_EBIrregDataPtr = nullptr protected
Referenced by Proto::IrregData< cent, data_t, ncomp >::defineEBIrregData(), and Proto::IrregData< cent, data_t, ncomp >::getEBIrregDataPtr().
The documentation for this class was generated from the following files:
Proto_IrregData.H
Proto_IrregDataImplem.H