Chombo_4: CH4_Data_Choreography::BoxPattern Class Reference
CH4_Data_Choreography::BoxPattern Class Reference
#include <Chombo_BoxPattern.H>
Public Member Functions
BoxPattern (const Chombo4::DisjointBoxLayout &a_grids, const IntVect &a_ghost, bool a_printStuff=false)
void printStuff (string a_prefix) const
BoxPattern (const Chombo4::DisjointBoxLayout &a_src, const Chombo4::DisjointBoxLayout &a_dst, bool a_printStuff=false)
Define for copyTo — does NOT include ghost cells.
void sortAllPatterns ()
Public Attributes
vector< box_interaction_t > m_localPattern
vector< vector< box_interaction_t > > m_recvPattern
outer loop is per proc
vector< vector< box_interaction_t > > m_sendPattern
outer loop is per proc
Private Member Functions
BoxPattern ()
I like strong construction.
BoxPattern (const BoxPattern &a_input)
void operator= (const BoxPattern &a_input)
Detailed Description
BoxPattern is a class which deals with all the Box intersections associated with copyTo or exchange. Periodic boundary conditions are not supported.
Constructor & Destructor Documentation
BoxPattern() [1/4]
CH4_Data_Choreography::BoxPattern::BoxPattern (const Chombo4::DisjointBoxLayout & a_grids, const IntVect & a_ghost, bool a_printStuff = false) inline
Define for exchange–fills ghost cells around boxes if neighboring boxes are adjacent
References CH_TIME, CH4_SPMD::numProc(), and CH4_SPMD::procID().
BoxPattern() [2/4]
CH4_Data_Choreography::BoxPattern::BoxPattern (const Chombo4::DisjointBoxLayout & a_src, const Chombo4::DisjointBoxLayout & a_dst, bool a_printStuff = false) inline
Define for copyTo — does NOT include ghost cells.
References LayoutIterator::begin(), CH_TIME, CH4_SPMD::numProc(), LayoutIterator::ok(), and CH4_SPMD::procID().
BoxPattern() [3/4]
CH4_Data_Choreography::BoxPattern::BoxPattern () private
I like strong construction.
BoxPattern() [4/4]
CH4_Data_Choreography::BoxPattern::BoxPattern (const BoxPattern & a_input) private
Member Function Documentation
printStuff()
void CH4_Data_Choreography::BoxPattern::printStuff (string a_prefix) const inline
References CH4_SPMD::numProc(), and pout().
sortAllPatterns()
void CH4_Data_Choreography::BoxPattern::sortAllPatterns () inline
operator=()
void CH4_Data_Choreography::BoxPattern::operator= (const BoxPattern & a_input) private
Member Data Documentation
m_localPattern
vector<box_interaction_t> CH4_Data_Choreography::BoxPattern::m_localPattern
Referenced by CH4_Data_Choreography::DistributedData< EBFluxData< Real, NUMCOMPS > >::doLocalCopiesWithCopy(), and CH4_Data_Choreography::DistributedData< EBFluxData< Real, NUMCOMPS > >::doLocalCopiesWithSerialization().
m_recvPattern
vector< vector<box_interaction_t> > CH4_Data_Choreography::BoxPattern::m_recvPattern
outer loop is per proc
Referenced by CH4_Data_Choreography::DistributedData< EBFluxData< Real, NUMCOMPS > >::communicate(), and CH4_Data_Choreography::CommunicationMetaData< fabtype_t >::CommunicationMetaData().
m_sendPattern
vector< vector<box_interaction_t> > CH4_Data_Choreography::BoxPattern::m_sendPattern
outer loop is per proc
Referenced by CH4_Data_Choreography::DistributedData< EBFluxData< Real, NUMCOMPS > >::communicate(), and CH4_Data_Choreography::CommunicationMetaData< fabtype_t >::CommunicationMetaData().
The documentation for this class was generated from the following file:
Chombo_BoxPattern.H