Chombo_4: IndexTM< T, N > Class Template Reference
IndexTM< T, N > Class Template Reference
#include <IndexTM.H>
Public Member Functions
template<typename OP >
bool operatorCompare (const IndexTM< T, N > &a_p, const OP &a_op) const
template<typename OP >
IndexTM< T, N > & operatorOpEquals (const IndexTM< T, N > &a_p, const OP &a_op)
template<typename OP >
IndexTM< T, N > & operatorOpEquals (const T &a_p, const OP &a_op)
IndexTM & reciprocal ()
int minDir (bool a_doAbs) const
int maxDir (bool a_doAbs) const
T integer_factorial (int n) const
T factorial () const
Constructors and Accessors
See derived class IndexTM for more constructors.
IndexTM ()
~IndexTM ()
IndexTM (T a_i)
IndexTM (T a_i, T a_j)
IndexTM (T a_i, T a_j, T a_k)
IndexTM (T a_i, T a_j, T a_k, T a_l)
IndexTM (T a_i, T a_j, T a_k, T a_l, T a_m)
IndexTM (T a_i, T a_j, T a_k, T a_l, T a_m, T a_n)
IndexTM (const T *a_a)
IndexTM (const IndexTM &a_rhs)
IndexTM copy () const
IndexTM & operator= (const IndexTM &a_rhs)
T & operator[] (int a_i)
T operator[] (int a_i) const
void setVal (int a_i, T a_val)
void setAll (T a_val)
Data pointer functions
const T * getVect () const
const T * dataPtr () const
T * dataPtr ()
Comparison Operators
bool operator== (const IndexTM &a_p) const
bool operator!= (const IndexTM &a_p) const
bool lexLT (const IndexTM &a_s) const
bool operator< (const IndexTM &a_s) const
bool componentwiseLE (const IndexTM &a_s)
bool lexGT (const IndexTM &a_s) const
Unary operators
IndexTM operator+ () const
IndexTM operator- () const
T dotProduct (const IndexTM &a_rhs) const
T sum () const
T product () const
Other arithmetic operators
IndexTM & min (const IndexTM &a_p)
IndexTM & max (const IndexTM &a_p)
IndexTM & scale (T a_s)
IndexTM & reflect (T a_refIx, int a_idir)
IndexTM & shift (int a_coord, T a_s)
IndexTM & shift (const IndexTM &a_iv)
IndexTM & diagShift (T a_s)
IndexTM & coarsen (const IndexTM &a_p)
IndexTM & coarsen (T a_p)
Public Member Functions inherited from Proto::GenericArithmeticable< T, IndexTM< T, N > >
virtual ~GenericArithmeticable ()
GenericArithmeticable (IndexTM< T, N > *s)
bool operator< (const IndexTM< T, N > &) const
bool operator> (const IndexTM< T, N > &) const
bool operator<= (const IndexTM< T, N > &) const
bool operator>= (const IndexTM< T, N > &) const
IndexTM< T, N > & operator+= (const IndexTM< T, N > &)
IndexTM< T, N > & operator+= (const T &)
IndexTM< T, N > & operator-= (const IndexTM< T, N > &)
IndexTM< T, N > & operator-= (const T &)
IndexTM< T, N > & operator*= (const IndexTM< T, N > &)
IndexTM< T, N > & operator*= (const T &)
IndexTM< T, N > & operator/= (const IndexTM< T, N > &)
IndexTM< T, N > & operator/= (const T &)
Protected Member Functions
IndexTM (const char *)
Protected Attributes
T m_vect [N]
I/O Functions
void printOn (std::ostream &a_os) const
void p () const
void dumpOn (std::ostream &a_os) const
std::ostream & operator<< (std::ostream &a_os, const IndexTM &a_iv)
std::istream & operator>> (std::istream &a_os, IndexTM &a_iv)
Constants
static const IndexTM Zero
static const IndexTM Unit
void linearIn (const void *a_inBuf)
void linearOut (void *a_outBuf) const
static int InitStatics ()
Additional Inherited Members
Public Types inherited from Proto::GenericArithmeticable< T, IndexTM< T, N > >
typedef T scalar_type
typedef IndexTM< T, N > self_type
Constructor & Destructor Documentation
IndexTM() [1/10]
template<typename T, int N = CH_SPACEDIM> IndexTM< T, N >::IndexTM () inline
Construct an IndexTM whose components are uninitialized.
Referenced by IndexTM< T, N >::factorial(), and IndexTM< T, N >::~IndexTM().
~IndexTM()
template<typename T, int N = CH_SPACEDIM> IndexTM< T, N >::~IndexTM () inline
Destructor.
References IndexTM< T, N >::IndexTM().
IndexTM() [2/10]
template<typename T , int N> IndexTM< T, N >::IndexTM (T a_i) explicit
References IndexTM< T, N >::m_vect, and N.
IndexTM() [3/10]
template<typename T , int N> IndexTM< T, N >::IndexTM (T a_i, T a_j)
References IndexTM< T, N >::m_vect, and N.
IndexTM() [4/10]
template<typename T , int N> IndexTM< T, N >::IndexTM (T a_i, T a_j, T a_k)
References IndexTM< T, N >::m_vect, and N.
IndexTM() [5/10]
template<typename T , int N> IndexTM< T, N >::IndexTM (T a_i, T a_j, T a_k, T a_l)
References IndexTM< T, N >::m_vect, and N.
IndexTM() [6/10]
template<typename T , int N> IndexTM< T, N >::IndexTM (T a_i, T a_j, T a_k, T a_l, T a_m)
References IndexTM< T, N >::m_vect, and N.
IndexTM() [7/10]
template<typename T , int N> IndexTM< T, N >::IndexTM (T a_i, T a_j, T a_k, T a_l, T a_m, T a_n)
References IndexTM< T, N >::m_vect, and N.
IndexTM() [8/10]
template<typename T , int N> IndexTM< T, N >::IndexTM (const T * a_a) inline explicit
Construct an IndexTM setting the coordinates to the corresponding values in the integer array a_a.
References IndexTM< T, N >::m_vect, and N.
IndexTM() [9/10]
template<typename T , int N> IndexTM< T, N >::IndexTM (const IndexTM< T, N > & a_rhs) inline
The copy constructor.
References IndexTM< T, N >::m_vect, and N.
IndexTM() [10/10]
template<typename T , int N> IndexTM< T, N >::IndexTM (const char * a_reference) inline protected
References MayDay::Error(), and IndexTM< T, N >::setAll().
Member Function Documentation
copy()
template<typename T, int N = CH_SPACEDIM> IndexTM IndexTM< T, N >::copy () const inline
References IndexTM< T, N >::dataPtr(), IndexTM< T, N >::getVect(), IndexTM< T, N >::lexLT(), IndexTM< T, N >::operator!=(), IndexTM< T, N >::operator=(), IndexTM< T, N >::operator==(), IndexTM< T, N >::operator[](), IndexTM< T, N >::setAll(), and IndexTM< T, N >::setVal().
operator=()
template<typename T , int N> IndexTM< T, N > & IndexTM< T, N >::operator= (const IndexTM< T, N > & a_rhs) inline
The assignment operator.
References IndexTM< T, N >::m_vect, and N.
Referenced by IndexTM< T, N >::copy().
operator[]() [1/2]
template<typename T , int N> T & IndexTM< T, N >::operator[] (int a_i) inline
Returns a modifiable lvalue reference to the i'th coordinate of the IndexTM.
References CH_assert, IndexTM< T, N >::m_vect, and N.
Referenced by IndexTM< T, N >::copy().
operator[]() [2/2]
template<typename T , int N> T IndexTM< T, N >::operator[] (int a_i) const inline
Returns the i'th coordinate of the IndexTM.
References CH_assert, IndexTM< T, N >::m_vect, and N.
setVal()
template<typename T , int N> void IndexTM< T, N >::setVal (int a_i, T a_val) inline
Set i'th coordinate of IndexTM to val.
References CH_assert, IndexTM< T, N >::m_vect, and N.
Referenced by IndexTM< T, N >::copy().
setAll()
template<typename T , int N> void IndexTM< T, N >::setAll (T a_val) inline
set all values to val
References IndexTM< T, N >::m_vect, and N.
Referenced by IndexTM< T, N >::copy(), LevelGeometryService< order >::fillGraph(), LevelGeometryService< order >::fillNewNode(), Proto::IndexTM< double, N >::IndexTM(), and IndexTM< T, N >::IndexTM().
getVect()
template<typename T , int N> const T * IndexTM< T, N >::getVect () const inline
Returns a const pointer to an array of coordinates of the IndexTM. Useful for arguments to FORTRAN calls.
References IndexTM< T, N >::m_vect.
Referenced by IndexTM< T, N >::copy().
dataPtr() [1/2]
template<typename T , int N> const T * IndexTM< T, N >::dataPtr () const inline
Only for sending to Fortran
References IndexTM< T, N >::m_vect.
Referenced by BASISV_TM(), and IndexTM< T, N >::copy().
dataPtr() [2/2]
template<typename T , int N> T * IndexTM< T, N >::dataPtr () inline
Only for sending to Fortran
References IndexTM< T, N >::m_vect.
operator==()
template<typename T , int N> bool IndexTM< T, N >::operator== (const IndexTM< T, N > & a_p) const inline
Returns true if this IndexTM is equivalent to argument IndexTM. All comparisons between analogous components must be satisfied.
References IndexTM< T, N >::m_vect.
Referenced by IndexTM< T, N >::copy(), IndexTM< T, N >::operator!=(), and Proto::IndexTM< double, N >::operator!=().
operator!=()
template<typename T , int N> bool IndexTM< T, N >::operator!= (const IndexTM< T, N > & a_p) const inline
Returns true if this IndexTM is different from argument IndexTM. All comparisons between analogous components must be satisfied.
References IndexTM< T, N >::operator==().
Referenced by IndexTM< T, N >::copy().
lexLT()
template<typename T , int N> bool IndexTM< T, N >::lexLT (const IndexTM< T, N > & a_s) const inline
Returns true if this IndexTM is lexically less than the argument. An IndexTM MUST BE either lexically less than, lexically greater than, or equal to another IndexTM.
iv1 is lexically less than iv2 if:
in 2-D:
(iv1[0] < iv2[0]) || ((iv1[0] == iv2[0]) && (iv1[1] < iv2[1]));
in 3-D:
(iv1[0] < iv2[0]) || (iv1[0]==iv2[0] && ((iv1[1] < iv2[1] || ((iv1[1] == iv2[1]) && (iv1[2] < iv2[2])))));
References IndexTM< T, N >::m_vect.
Referenced by IndexTM< T, N >::copy(), and IndexTM< T, N >::operator<().
operator<()
template<typename T, int N = CH_SPACEDIM> bool IndexTM< T, N >::operator< (const IndexTM< T, N > & a_s) const inline
Returns true if this IndexTM is lexically less than the argument. An IndexTM MUST BE either lexically less than, lexically greater than, or equal to another IndexTM.
iv1 is lexically less than iv2 if:
in 2-D:
(iv1[0] < iv2[0]) || ((iv1[0] == iv2[0]) && (iv1[1] < iv2[1]));
in 3-D:
(iv1[0] < iv2[0]) || (iv1[0]==iv2[0] && ((iv1[1] < iv2[1] || ((iv1[1] == iv2[1]) && (iv1[2] < iv2[2])))));
References IndexTM< T, N >::lexLT().
componentwiseLE()
template<typename T, int N = CH_SPACEDIM> bool IndexTM< T, N >::componentwiseLE (const IndexTM< T, N > & a_s) inline
Does operator <= the same way that intvect does it Intvect code looks like this: return D_TERM6(vect[0] >= p[0], && vect[1] >= p[1], && vect[2] >= p[2], && vect[3] >= p[3], && vect[4] >= p[4], && vect[5] >= p[5]);
References IndexTM< T, N >::coarsen(), IndexTM< T, N >::diagShift(), IndexTM< T, N >::dotProduct(), IndexTM< T, N >::dumpOn(), IndexTM< T, N >::lexGT(), IndexTM< T, N >::max(), IndexTM< T, N >::maxDir(), IndexTM< T, N >::min(), IndexTM< T, N >::minDir(), N, IndexTM< T, N >::operator+(), IndexTM< T, N >::operator-(), IndexTM< T, N >::operatorCompare(), IndexTM< T, N >::operatorOpEquals(), IndexTM< T, N >::p(), IndexTM< T, N >::printOn(), IndexTM< T, N >::product(), IndexTM< T, N >::reciprocal(), IndexTM< T, N >::reflect(), IndexTM< T, N >::scale(), IndexTM< T, N >::shift(), and IndexTM< T, N >::sum().
lexGT()
template<typename T , int N> bool IndexTM< T, N >::lexGT (const IndexTM< T, N > & a_s) const inline
Returns true if this IndexTM is lexically greater than the argument. An IndexTM MUST BE either lexically less than, lexically greater than, or equal to another IndexTM.
iv1 is lexically less than iv2 if:
in 2-D:
(iv1[0] > iv2[0]) || ((iv1[0] == iv2[0]) && (iv1[1] > iv2[1]));
in 3-D:
(iv1[0] > iv2[0]) || (iv1[0]==iv2[0] && ((iv1[1] > iv2[1] || ((iv1[1] == iv2[1]) && (iv1[2] > iv2[2])))));
References IndexTM< T, N >::m_vect.
Referenced by IndexTM< T, N >::componentwiseLE().
operator+()
template<typename T , int N> IndexTM< T, N > IndexTM< T, N >::operator+ () const inline
Unary plus – for completeness.
Referenced by IndexTM< T, N >::componentwiseLE().
operator-()
template<typename T , int N> IndexTM< T, N > IndexTM< T, N >::operator- () const inline
Unary minus – negates all components of this IndexTM.
References IndexTM< T, N >::m_vect, and N.
Referenced by IndexTM< T, N >::componentwiseLE().
dotProduct()
template<typename T , int N> T IndexTM< T, N >::dotProduct (const IndexTM< T, N > & a_rhs) const inline
References IndexTM< T, N >::m_vect, and N.
Referenced by IndexTM< T, N >::componentwiseLE().
sum()
template<typename T , int N> T IndexTM< T, N >::sum () const inline
Sum of all components of this IndexTM.
References IndexTM< T, N >::m_vect.
Referenced by IndexTM< T, N >::componentwiseLE().
product()
template<typename T , int N> T IndexTM< T, N >::product () const inline
Product of all components of this IndexTM.
References IndexTM< T, N >::m_vect.
Referenced by IndexTM< T, N >::componentwiseLE().
operatorCompare()
template<typename T , int N> template<typename OP > bool IndexTM< T, N >::operatorCompare (const IndexTM< T, N > & a_p, const OP & a_op) const
Used by GenericArithmeticable to implement all pointwise arithmetic and comparison functions.
References IndexTM< T, N >::m_vect.
Referenced by IndexTM< T, N >::componentwiseLE().
operatorOpEquals() [1/2]
template<typename T , int N> template<typename OP > IndexTM< T, N > & IndexTM< T, N >::operatorOpEquals (const IndexTM< T, N > & a_p, const OP & a_op) inline
References IndexTM< T, N >::m_vect.
Referenced by IndexTM< T, N >::componentwiseLE().
operatorOpEquals() [2/2]
template<typename T , int N> template<typename OP > IndexTM< T, N > & IndexTM< T, N >::operatorOpEquals (const T & a_p, const OP & a_op) inline
References IndexTM< T, N >::m_vect.
reciprocal()
template<typename T , int N> IndexTM< T, N > & IndexTM< T, N >::reciprocal () inline
Modifies this IndexTM by division of each component into T(1).
References IndexTM< T, N >::m_vect, and N.
Referenced by IndexTM< T, N >::componentwiseLE().
minDir()
template<typename T , int N> int IndexTM< T, N >::minDir (bool a_doAbs) const inline
Component with the minimum value of this Index(returns 0 if they are all the same). a_doAbs : if true then take the absolute value before comparing
References IndexTM< T, N >::m_vect, and N.
Referenced by IndexTM< T, N >::componentwiseLE().
maxDir()
template<typename T , int N> int IndexTM< T, N >::maxDir (bool a_doAbs) const inline
Component with the maximum value of this Index (returns 0 if they are all the same). a_doAbs : if true then take the absolute value before comparing.
References IndexTM< T, N >::m_vect, and N.
Referenced by IndexTM< T, N >::componentwiseLE().
min()
template<typename T , int N> IndexTM< T, N > & IndexTM< T, N >::min (const IndexTM< T, N > & a_p) inline
Modifies this IndexTM by taking component-wise min with IndexTM argument.
References IndexTM< T, N >::m_vect, and N.
Referenced by IndexTM< T, N >::componentwiseLE(), and min().
max()
template<typename T , int N> IndexTM< T, N > & IndexTM< T, N >::max (const IndexTM< T, N > & a_p) inline
Modifies this IndexTM by taking component-wise max with IndexTM argument.
References IndexTM< T, N >::m_vect, and N.
Referenced by IndexTM< T, N >::componentwiseLE(), and max().
scale()
template<typename T , int N> IndexTM< T, N > & IndexTM< T, N >::scale (T a_s) inline
Modifies this IndexTM by multiplying each component by a scalar.
Referenced by IndexTM< T, N >::componentwiseLE().
reflect()
template<typename T , int N> IndexTM< T, N > & IndexTM< T, N >::reflect (T a_refIx, int a_idir) inline
Modifies IndexTM by reflecting it in the plane defined by the index ref_ix and with normal in the direction of idir. Directions are based at zero.
References CH_assert, IndexTM< T, N >::m_vect, and N.
Referenced by IndexTM< T, N >::componentwiseLE(), and reflect().
shift() [1/2]
template<typename T , int N> IndexTM< T, N > & IndexTM< T, N >::shift (int a_coord, T a_s) inline
Modifies this IndexTM by adding s to component in given coordinate direction.
References CH_assert, IndexTM< T, N >::m_vect, and N.
Referenced by IndexTM< T, N >::componentwiseLE().
shift() [2/2]
template<typename T , int N> IndexTM< T, N > & IndexTM< T, N >::shift (const IndexTM< T, N > & a_iv) inline
Modifies this IndexTM by component-wise addition with IndexTM argument.
diagShift()
template<typename T , int N> IndexTM< T, N > & IndexTM< T, N >::diagShift (T a_s) inline
Modifies this IndexTM by adding a scalar s to each component.
Referenced by IndexTM< T, N >::componentwiseLE().
coarsen() [1/2]
template<typename T , int N> IndexTM< T, N > & IndexTM< T, N >::coarsen (const IndexTM< T, N > & a_p) inline
Modify IndexTM by component-wise integer projection.
References CH_assert, IndexTM< T, N >::m_vect, and N.
Referenced by coarsen(), and IndexTM< T, N >::componentwiseLE().
coarsen() [2/2]
template<typename T , int N> IndexTM< T, N > & IndexTM< T, N >::coarsen (T a_p) inline
Modify IndexTM by component-wise integer projection.
References CH_assert, IndexTM< T, N >::m_vect, and N.
printOn()
template<typename T, int N = CH_SPACEDIM> void IndexTM< T, N >::printOn (std::ostream & a_os) const
Print an IndexTM to the ostream.
Referenced by IndexTM< T, N >::componentwiseLE().
p()
template<typename T , int N> void IndexTM< T, N >::p () const
Print an IndexTM to the pout().
References pout().
Referenced by IndexTM< T, N >::componentwiseLE().
dumpOn()
template<typename T, int N = CH_SPACEDIM> void IndexTM< T, N >::dumpOn (std::ostream & a_os) const
Print an IndexTM to the ostream a bit more verbosely.
Referenced by IndexTM< T, N >::componentwiseLE().
InitStatics()
template<typename T, int N = CH_SPACEDIM> static int IndexTM< T, N >::InitStatics () static
Initializes Zero and Unit.
linearIn()
template<typename T , int N> void IndexTM< T, N >::linearIn (const void * a_inBuf)
Low-level data copy.
References IndexTM< T, N >::m_vect, and N.
linearOut()
template<typename T , int N> void IndexTM< T, N >::linearOut (void * a_outBuf) const
References IndexTM< T, N >::m_vect, and N.
integer_factorial()
template<typename T, int N = CH_SPACEDIM> T IndexTM< T, N >::integer_factorial (int n) const inline
References CH_assert.
Referenced by IndexTM< T, N >::factorial().
factorial()
template<typename T, int N = CH_SPACEDIM> T IndexTM< T, N >::factorial () const inline
References IndexTM< T, N >::IndexTM(), IndexTM< T, N >::integer_factorial(), IndexTM< T, N >::m_vect, and N.
Friends And Related Function Documentation
operator<<
template<typename T, int N = CH_SPACEDIM> std::ostream& operator<< (std::ostream & a_os, const IndexTM< T, N > & a_iv) friend
Print the IndexTM to given output stream in ASCII.
operator>>
template<typename T, int N = CH_SPACEDIM> std::istream& operator>> (std::istream & a_os, IndexTM< T, N > & a_iv) friend
Read next IndexTM from given input stream.
Member Data Documentation
Zero
template<typename T, int N = CH_SPACEDIM> const IndexTM< T, N > IndexTM< T, N >::Zero static
This is an IndexTM all of whose components are equal to zero.
Unit
template<typename T, int N = CH_SPACEDIM> const IndexTM< T, N > IndexTM< T, N >::Unit static
This is an IndexTM all of whose components are equal to one.
m_vect
template<typename T, int N = CH_SPACEDIM> T IndexTM< T, N >::m_vect[N] protected
The individual components of this IndexTM.
Referenced by IndexTM< T, N >::coarsen(), Proto::IndexTM< double, N >::coarsen(), IndexTM< T, N >::dataPtr(), Proto::IndexTM< double, N >::dataPtr(), IndexTM< T, N >::dotProduct(), Proto::IndexTM< double, N >::dotProduct(), IndexTM< T, N >::factorial(), IndexTM< T, N >::getVect(), Proto::IndexTM< double, N >::getVect(), IndexTM< T, N >::IndexTM(), Proto::IndexTM< double, N >::IndexTM(), IndexTM< T, N >::lexGT(), Proto::IndexTM< double, N >::lexGT(), IndexTM< T, N >::lexLT(), Proto::IndexTM< double, N >::lexLT(), Proto::IndexTM< double, N >::linearIn(), IndexTM< T, N >::linearIn(), Proto::IndexTM< double, N >::linearOut(), IndexTM< T, N >::linearOut(), IndexTM< T, N >::max(), Proto::IndexTM< double, N >::max(), IndexTM< T, N >::maxDir(), Proto::IndexTM< double, N >::maxDir(), IndexTM< T, N >::min(), Proto::IndexTM< double, N >::min(), IndexTM< T, N >::minDir(), Proto::IndexTM< double, N >::minDir(), IndexTM< T, N >::operator-(), IndexTM< T, N >::operator=(), Proto::IndexTM< double, N >::operator=(), IndexTM< T, N >::operator==(), Proto::IndexTM< double, N >::operator==(), IndexTM< T, N >::operator[](), Proto::IndexTM< double, N >::operator[](), IndexTM< T, N >::operatorCompare(), Proto::IndexTM< double, N >::operatorCompare(), IndexTM< T, N >::operatorOpEquals(), Proto::IndexTM< double, N >::operatorOpEquals(), IndexTM< T, N >::product(), Proto::IndexTM< double, N >::product(), IndexTM< T, N >::reciprocal(), Proto::IndexTM< double, N >::reciprocal(), IndexTM< T, N >::reflect(), Proto::IndexTM< double, N >::reflect(), IndexTM< T, N >::setAll(), Proto::IndexTM< double, N >::setAll(), IndexTM< T, N >::setVal(), Proto::IndexTM< double, N >::setVal(), IndexTM< T, N >::shift(), Proto::IndexTM< double, N >::shift(), IndexTM< T, N >::sum(), and Proto::IndexTM< double, N >::sum().
The documentation for this class was generated from the following files:
IndexTM.H
IndexTMI.H