Chombo_4: LayoutIndex Class Reference
LayoutIndex Class Reference
An index for LayoutIterator.
#include <Chombo_DataIndex.H>
Public Member Functions
LayoutIndex ()
virtual ~LayoutIndex ()
bool operator== (const LayoutIndex &a_rhs) const
bool eq (const LayoutIndex &a_rhs) const
bool operator!= (const LayoutIndex &a_rhs) const
bool isNull () const
returns 'true' if this DataIndex has been null constructed.
int intCode () const
int datInd () const
LayoutIndex (const LayoutIndex &a_input)
virtual void output () const
Private Member Functions
LayoutIndex (int a_indexIntoBoxes, int a_indexIntoData, const int *a_layoutID)
Private Attributes
int m_index
int m_datInd
const int * m_layoutIntPtr
Friends
class DataIterator
class LayoutIterator
class TimedDataIterator
class NeighborIterator
class BoxLayout
class DataIndex
class DisjointBoxLayout
std::ostream & operator<< (std::ostream &os, const LayoutIndex &dit)
Detailed Description
An index for LayoutIterator.
Constructor & Destructor Documentation
LayoutIndex() [1/3]
LayoutIndex::LayoutIndex () inline
~LayoutIndex()
virtual LayoutIndex::~LayoutIndex () inline virtual
References operator==().
LayoutIndex() [2/3]
LayoutIndex::LayoutIndex (const LayoutIndex & a_input) inline
References m_datInd, m_index, and m_layoutIntPtr.
LayoutIndex() [3/3]
LayoutIndex::LayoutIndex (int a_indexIntoBoxes, int a_indexIntoData, const int * a_layoutID) inline private
Member Function Documentation
operator==()
bool LayoutIndex::operator== (const LayoutIndex & a_rhs) const inline
References m_index.
Referenced by ~LayoutIndex().
eq()
bool LayoutIndex::eq (const LayoutIndex & a_rhs) const inline
operator!=()
bool LayoutIndex::operator!= (const LayoutIndex & a_rhs) const inline
References intCode(), and isNull().
isNull()
bool LayoutIndex::isNull () const inline
returns 'true' if this DataIndex has been null constructed.
References m_layoutIntPtr.
Referenced by operator!=().
intCode()
int LayoutIndex::intCode () const inline
References m_index.
Referenced by operator!=().
datInd()
int LayoutIndex::datInd () const inline
References m_datInd, and m_index.
output()
virtual void LayoutIndex::output () const inline virtual
Print to the given output stream in ASCII.
References operator<<, and pout().
Friends And Related Function Documentation
DataIterator
friend class DataIterator friend
LayoutIterator
friend class LayoutIterator friend
TimedDataIterator
friend class TimedDataIterator friend
NeighborIterator
friend class NeighborIterator friend
BoxLayout
friend class BoxLayout friend
DataIndex
friend class DataIndex friend
DisjointBoxLayout
friend class DisjointBoxLayout friend
operator<<
std::ostream& operator<< (std::ostream & os, const LayoutIndex & dit) friend
Referenced by output().
Member Data Documentation
m_index
int LayoutIndex::m_index private
Referenced by datInd(), BoxLayout::get(), BoxLayout::index(), intCode(), LayoutIndex(), operator==(), BoxLayout::operator[](), BoxLayout::procID(), and BoxLayout::setProcID().
m_datInd
int LayoutIndex::m_datInd private
Referenced by datInd(), and LayoutIndex().
m_layoutIntPtr
const int* LayoutIndex::m_layoutIntPtr private
Referenced by BoxLayout::check(), isNull(), and LayoutIndex().
The documentation for this class was generated from the following file:
Chombo_DataIndex.H