Chombo_4: Proto::EBStencilArchive< srcCenter, dstCenter, order, data_t > Class Template Reference
Proto::EBStencilArchive< srcCenter, dstCenter, order, data_t > Class Template Reference
#include <Proto_EBStencilArchive.H>
Public Types
typedef IndexedMoments< DIM, order > IndMomDIM
typedef IndexedMoments< DIM-1, order > IndMomSDMinOne
typedef MomentIterator< DIM, order > MomItDIM
typedef MomentIterator< DIM-1, order > MomItSDMinOne
typedef HostIrregData< CELL, IndMomDIM, 1 > VoluData
typedef HostIrregData< BOUNDARY, IndMomDIM, 1 > EBFaData
typedef HostIrregData< XFACE, IndMomSDMinOne, 1 > XFacData
typedef HostIrregData< YFACE, IndMomSDMinOne, 1 > YFacData
typedef HostIrregData< ZFACE, IndMomSDMinOne, 1 > ZFacData
Public Member Functions
EBStencilArchive ()
~EBStencilArchive ()
Static Public Member Functions
static bool getStencil (vector< EBIndex< dstCenter > > &a_dstVoFs, vector< LocalStencil< srcCenter, data_t > > &a_stencil, Stencil< data_t > &a_regStencilInterior, vector< Stencil< data_t > > a_regStencilBCS[2 *DIM], vector< Box > a_BCApplyBoxes[2 *DIM], Box &a_regApplyBox, bool &a_bcOnly, bool &a_irregOnly, string a_stencilName, string a_domainBCName[2 *DIM], string a_ebbcName, const Box &a_srcValid, const Box &a_dstValid, const Box &a_srcDomain, const Box &a_dstDomain, const Point &a_srcGhost, const Point &a_dstGhost, const EBGraph &a_srcGraph, const EBGraph &a_dstGraph, const VoluData &a_voludata, const EBFaData &a_ebfadata, const XFacData &a_xfacdata, const YFacData &a_yfacdata, const ZFacData &a_zfacdata, double a_dx, bool a_periodiconly, Point a_dstGrown)
returns true if there are domain boundary conditions (not all ops have them)
Member Typedef Documentation
IndMomDIM
template<CENTERING srcCenter, CENTERING dstCenter, int order, typename data_t > typedef IndexedMoments<DIM , order> Proto::EBStencilArchive< srcCenter, dstCenter, order, data_t >::IndMomDIM
IndMomSDMinOne
template<CENTERING srcCenter, CENTERING dstCenter, int order, typename data_t > typedef IndexedMoments<DIM-1, order> Proto::EBStencilArchive< srcCenter, dstCenter, order, data_t >::IndMomSDMinOne
MomItDIM
template<CENTERING srcCenter, CENTERING dstCenter, int order, typename data_t > typedef MomentIterator<DIM , order> Proto::EBStencilArchive< srcCenter, dstCenter, order, data_t >::MomItDIM
MomItSDMinOne
template<CENTERING srcCenter, CENTERING dstCenter, int order, typename data_t > typedef MomentIterator<DIM-1, order> Proto::EBStencilArchive< srcCenter, dstCenter, order, data_t >::MomItSDMinOne
VoluData
template<CENTERING srcCenter, CENTERING dstCenter, int order, typename data_t > typedef HostIrregData<CELL, IndMomDIM , 1> Proto::EBStencilArchive< srcCenter, dstCenter, order, data_t >::VoluData
EBFaData
template<CENTERING srcCenter, CENTERING dstCenter, int order, typename data_t > typedef HostIrregData<BOUNDARY, IndMomDIM , 1> Proto::EBStencilArchive< srcCenter, dstCenter, order, data_t >::EBFaData
XFacData
template<CENTERING srcCenter, CENTERING dstCenter, int order, typename data_t > typedef HostIrregData<XFACE, IndMomSDMinOne, 1> Proto::EBStencilArchive< srcCenter, dstCenter, order, data_t >::XFacData
YFacData
template<CENTERING srcCenter, CENTERING dstCenter, int order, typename data_t > typedef HostIrregData<YFACE, IndMomSDMinOne, 1> Proto::EBStencilArchive< srcCenter, dstCenter, order, data_t >::YFacData
ZFacData
template<CENTERING srcCenter, CENTERING dstCenter, int order, typename data_t > typedef HostIrregData<ZFACE, IndMomSDMinOne, 1> Proto::EBStencilArchive< srcCenter, dstCenter, order, data_t >::ZFacData
Constructor & Destructor Documentation
EBStencilArchive()
template<CENTERING srcCenter, CENTERING dstCenter, int order, typename data_t > Proto::EBStencilArchive< srcCenter, dstCenter, order, data_t >::EBStencilArchive () inline
~EBStencilArchive()
template<CENTERING srcCenter, CENTERING dstCenter, int order, typename data_t > Proto::EBStencilArchive< srcCenter, dstCenter, order, data_t >::~EBStencilArchive () inline
Member Function Documentation
getStencil()
template<CENTERING srcCenter, CENTERING dstCenter, int order, typename data_t > static bool Proto::EBStencilArchive< srcCenter, dstCenter, order, data_t >::getStencil (vector< EBIndex< dstCenter > > & a_dstVoFs, vector< LocalStencil< srcCenter, data_t > > & a_stencil, Stencil< data_t > & a_regStencilInterior, vector< Stencil< data_t > > a_regStencilBCS[2 *DIM], vector< Box > a_BCApplyBoxes[2 *DIM], Box & a_regApplyBox, bool & a_bcOnly, bool & a_irregOnly, string a_stencilName, string a_domainBCName[2 *DIM], string a_ebbcName, const Box & a_srcValid, const Box & a_dstValid, const Box & a_srcDomain, const Box & a_dstDomain, const Point & a_srcGhost, const Point & a_dstGhost, const EBGraph & a_srcGraph, const EBGraph & a_dstGraph, const VoluData & a_voludata, const EBFaData & a_ebfadata, const XFacData & a_xfacdata, const YFacData & a_yfacdata, const ZFacData & a_zfacdata, double a_dx, bool a_periodiconly, Point a_dstGrown) inline static
returns true if there are domain boundary conditions (not all ops have them)
Referenced by Proto::EBStencilArchive< CELL, CELL, order, double >::getColor(), Proto::EBStencilArchive< fcent, CELL, order, double >::getFaceToCellAveStencil(), Proto::EBStencilArchive< CELL, fcent, order, double >::getMACGradientStencil(), Proto::EBStencilArchive< CELL, CELL, order, double >::getRegularPoissonBoundaryStencil(), Proto::EBStencilArchive< YFACE, XFACE, order, double >::getStencil(), Proto::EBStencilArchive< XFACE, YFACE, order, double >::getStencil(), Proto::EBStencilArchive< XFACE, ZFACE, order, double >::getStencil(), Proto::EBStencilArchive< YFACE, ZFACE, order, double >::getStencil(), Proto::EBStencilArchive< ZFACE, XFACE, order, double >::getStencil(), Proto::EBStencilArchive< ZFACE, YFACE, order, double >::getStencil(), Proto::EBStencilArchive< CELL, BOUNDARY, order, double >::getStencil(), Proto::EBCrossStencilArchive< srcCenter, dstCenter, order >::getStencil(), Proto::EBStencilArchive< fcent, fcent, order, double >::~EBStencilArchive(), Proto::EBStencilArchive< CELL, fcent, order, double >::~EBStencilArchive(), Proto::EBStencilArchive< fcent, CELL, order, double >::~EBStencilArchive(), Proto::EBStencilArchive< YFACE, XFACE, order, double >::~EBStencilArchive(), Proto::EBStencilArchive< XFACE, YFACE, order, double >::~EBStencilArchive(), Proto::EBStencilArchive< XFACE, ZFACE, order, double >::~EBStencilArchive(), Proto::EBStencilArchive< YFACE, ZFACE, order, double >::~EBStencilArchive(), Proto::EBStencilArchive< ZFACE, XFACE, order, double >::~EBStencilArchive(), Proto::EBStencilArchive< ZFACE, YFACE, order, double >::~EBStencilArchive(), Proto::EBStencilArchive< CELL, BOUNDARY, order, double >::~EBStencilArchive(), and Proto::EBStencilArchive< BOUNDARY, CELL, order, double >::~EBStencilArchive().
The documentation for this class was generated from the following file:
Proto_EBStencilArchive.H