Chombo_4: Proto::HostBoxData< data_t, ncomp > Class Template Reference
Proto::HostBoxData< data_t, ncomp > Class Template Reference
Multidimensional Rectangular Array that lives on the host.
#include <Proto_HostBoxData.H>
Public Member Functions
HostBoxData ()
int nComp () const
HostBoxData (const Box &a_box, bool a_useStackAlloc=false)
HostBoxData (const BoxData< data_t, ncomp > &a_input)
aliasing for when the device is a lie
void define (const BoxData< data_t, ncomp > &a_input)
aliasing for when the device is a lie
void define (const Box &a_box, bool a_useStackAlloc=false)
virtual ~HostBoxData ()
Destructor.
template<unsigned int Csrc>
void copy (const HostBoxData< data_t, Csrc > &a_dsrc, const Box &a_srcBox, unsigned int a_srcComp, const Box &a_destBox, unsigned int a_destComp, unsigned int a_numcomp)
virtual std::size_t charsize (const Box &a_bx, unsigned int a_startcomp, unsigned int a_numcomps, bool a_printStuff=false) const
this DOES include sizeof(data_t)
virtual void linearIn (void *a_buf, size_t a_expectedCharSize, const Box &a_bx, unsigned int a_startcomp, unsigned int a_numcomps, bool a_printStuff=false)
virtual void linearOut (void *a_buf, size_t a_expectedCharSize, const Box &a_bx, unsigned int a_startcomp, unsigned int a_numcomps, bool a_printStuff=false) const
const data_t & operator() (const Point &a_pt, unsigned int a_c) const
data_t & operator() (const Point &a_pt, unsigned int a_c)
Box box () const
std::size_t size () const
bool defined () const
void setVal (const data_t &a_val)
data_t * data ()
const data_t * data () const
size_t index (const Point a_pt, unsigned int a_c) const
Static Public Member Functions
static int preAllocatable ()
Private Member Functions
HostBoxData (const HostBoxData< data_t, ncomp > &a_src)
Copy constructor/assignment forbidden for all the usual reasons.
HostBoxData & operator= (const HostBoxData< data_t, ncomp > &a_src)
Private Attributes
bool m_stackAlloc
Box m_box
Box defining the domain of *this.
::std::shared_ptr< data_t > m_data
Data array.
data_t * m_rawPtr
Raw pointer to the data.
Detailed Description
template<class data_t = double, unsigned int ncomp = 1>
class Proto::HostBoxData< data_t, ncomp >
Multidimensional Rectangular Array that lives on the host.
this is mainly for graph-like data thave lives on the host
Constructor & Destructor Documentation
HostBoxData() [1/4]
template<class T , unsigned int C> Proto::HostBoxData< T, C >::HostBoxData ()
Referenced by Proto::HostBoxData< Proto::CellNode, 1 >::index(), and Proto::HostBoxData< Proto::CellNode, 1 >::nComp().
HostBoxData() [2/4]
template<class T , unsigned int C> Proto::HostBoxData< T, C >::HostBoxData (const Box & a_box, bool a_useStackAlloc = false)
HostBoxData() [3/4]
template<class T, unsigned int C> Proto::HostBoxData< T, C >::HostBoxData (const BoxData< T, C > & a_input)
aliasing for when the device is a lie
~HostBoxData()
template<class T , unsigned int C> Proto::HostBoxData< T, C >::~HostBoxData () virtual
Destructor.
Referenced by Proto::HostBoxData< Proto::CellNode, 1 >::nComp().
HostBoxData() [4/4]
template<class data_t = double, unsigned int ncomp = 1> Proto::HostBoxData< data_t, ncomp >::HostBoxData (const HostBoxData< data_t, ncomp > & a_src) private
Copy constructor/assignment forbidden for all the usual reasons.
Member Function Documentation
nComp()
template<class data_t = double, unsigned int ncomp = 1> int Proto::HostBoxData< data_t, ncomp >::nComp () const inline
define() [1/2]
template<class T, unsigned int C> void Proto::HostBoxData< T, C >::define (const BoxData< T, C > & a_input)
aliasing for when the device is a lie
Referenced by Proto::HostBoxData< Proto::CellNode, 1 >::nComp().
define() [2/2]
template<class T , unsigned int C> void Proto::HostBoxData< T, C >::define (const Box & a_box, bool a_useStackAlloc = false)
copy()
template<class T, unsigned int C> template<unsigned int Csrc> void Proto::HostBoxData< T, C >::copy (const HostBoxData< T, Csrc > & a_dsrc, const Box & a_srcBox, unsigned int a_srcComp, const Box & a_destBox, unsigned int a_destComp, unsigned int a_numcomp)
Referenced by Proto::HostBoxData< Proto::CellNode, 1 >::nComp().
charsize()
template<class data_t = double, unsigned int ncomp = 1> virtual std::size_t Proto::HostBoxData< data_t, ncomp >::charsize (const Box & a_bx, unsigned int a_startcomp, unsigned int a_numcomps, bool a_printStuff = false) const inline virtual
this DOES include sizeof(data_t)
linearIn()
template<class data_t = double, unsigned int ncomp = 1> virtual void Proto::HostBoxData< data_t, ncomp >::linearIn (void * a_buf, size_t a_expectedCharSize, const Box & a_bx, unsigned int a_startcomp, unsigned int a_numcomps, bool a_printStuff = false) inline virtual
linearOut()
template<class data_t = double, unsigned int ncomp = 1> virtual void Proto::HostBoxData< data_t, ncomp >::linearOut (void * a_buf, size_t a_expectedCharSize, const Box & a_bx, unsigned int a_startcomp, unsigned int a_numcomps, bool a_printStuff = false) const inline virtual
preAllocatable()
template<class data_t = double, unsigned int ncomp = 1> static int Proto::HostBoxData< data_t, ncomp >::preAllocatable () inline static
operator()() [1/2]
template<class T , unsigned int C> const T & Proto::HostBoxData< T, C >::operator() (const Point & a_pt, unsigned int a_c) const inline
Referenced by Proto::HostBoxData< Proto::CellNode, 1 >::preAllocatable().
operator()() [2/2]
template<class T , unsigned int C> T & Proto::HostBoxData< T, C >::operator() (const Point & a_pt, unsigned int a_c) inline
box()
template<class data_t = double, unsigned int ncomp = 1> Box Proto::HostBoxData< data_t, ncomp >::box () const inline
Referenced by EBCM::EBCM_Graph< order >::getRegularNeighborPoint().
size()
template<class data_t = double, unsigned int ncomp = 1> std::size_t Proto::HostBoxData< data_t, ncomp >::size () const inline
defined()
template<class data_t = double, unsigned int ncomp = 1> bool Proto::HostBoxData< data_t, ncomp >::defined () const inline
setVal()
template<class T, unsigned int C> void Proto::HostBoxData< T, C >::setVal (const T & a_val)
Referenced by Proto::EBGraph::copy(), and Proto::HostBoxData< Proto::CellNode, 1 >::defined().
data() [1/2]
template<class data_t = double, unsigned int ncomp = 1> data_t* Proto::HostBoxData< data_t, ncomp >::data () inline
data() [2/2]
template<class data_t = double, unsigned int ncomp = 1> const data_t* Proto::HostBoxData< data_t, ncomp >::data () const inline
index()
template<class data_t = double, unsigned int ncomp = 1> size_t Proto::HostBoxData< data_t, ncomp >::index (const Point a_pt, unsigned int a_c) const inline
Referenced by Proto::HostBoxData< Proto::CellNode, 1 >::operator()().
operator=()
template<class data_t = double, unsigned int ncomp = 1> HostBoxData& Proto::HostBoxData< data_t, ncomp >::operator= (const HostBoxData< data_t, ncomp > & a_src) private
Referenced by Proto::HostBoxData< Proto::CellNode, 1 >::index().
Member Data Documentation
m_stackAlloc
template<class data_t = double, unsigned int ncomp = 1> bool Proto::HostBoxData< data_t, ncomp >::m_stackAlloc private
m_box
template<class data_t = double, unsigned int ncomp = 1> Box Proto::HostBoxData< data_t, ncomp >::m_box private
Box defining the domain of *this.
Referenced by Proto::HostBoxData< Proto::CellNode, 1 >::box(), Proto::HostBoxData< Proto::CellNode, 1 >::charsize(), Proto::HostBoxData< Proto::CellNode, 1 >::index(), Proto::HostBoxData< Proto::CellNode, 1 >::linearIn(), Proto::HostBoxData< Proto::CellNode, 1 >::linearOut(), and Proto::HostBoxData< Proto::CellNode, 1 >::size().
m_data
template<class data_t = double, unsigned int ncomp = 1> ::std::shared_ptr<data_t> Proto::HostBoxData< data_t, ncomp >::m_data private
Data array.
Referenced by Proto::HostBoxData< Proto::CellNode, 1 >::defined().
m_rawPtr
template<class data_t = double, unsigned int ncomp = 1> data_t* Proto::HostBoxData< data_t, ncomp >::m_rawPtr private
Raw pointer to the data.
Referenced by Proto::HostBoxData< Proto::CellNode, 1 >::data().
The documentation for this class was generated from the following files:
Proto_HostBoxData.H
Proto_HostBoxDataImplem.H