Chombo_4: Proto::LSquares Class Reference
Proto::LSquares Class Reference
#include <Proto_LSquares.H>
Public Member Functions
void LeastSquares (double **A, vector< double > &x, const vector< double > &rhs)
int gaussElim (double **A, vector< double > &rhs)
gaussian elimination with partial pivoting
void swapRows (double **A, const int &rowi, const int &rowj, const int &numberOfCols)
void swapRows (vector< double > &rhs, const int &currRow, const int &pivot)
int findPivot (double **A, const int &currCol, const int &currRow, const int &numRows, int &pivot)
void addRows (vector< double > &rhs, const int &rowi, const double &alpha, const int &rowj)
void addRows (double **A, const int &rowi, const double &alpha, const int &rowj, const int &numberOfCols)
void timesBeta (vector< double > &rhs, const int &currRow, const double &Beta)
void timesBeta (double **A, const int &rowi, const double &Beta, const int &numberOfcols)
void transpose (double **a_A, double **a_Atrans, const int &a_numRows, const int &a_numCols)
void matMul (double **a_A, double **a_B, double **a_C, const int &a_numRowsA, const int &a_numColsA, const int &a_numColsB)
void backSolve (double **a_A, const vector< double > &a_rhs, const int &a_numArows, vector< double > &a_x)
void AtimesX (double **A, const vector< double > &x, const int &numRowsA, vector< double > &Ax)
void allocArray (const int &rows, const int &cols, double **&A)
void freeArray (const int &rows, const int &cols, double **&A)
Detailed Description
This class solves least squares problems
Member Function Documentation
LeastSquares()
void Proto::LSquares::LeastSquares (double ** A, vector< double > & x, const vector< double > & rhs) inline
References allocArray(), AtimesX(), backSolve(), freeArray(), gaussElim(), matMul(), and transpose().
Referenced by Proto::LSProblem< dim >::invertNormalEq(), Proto::Moments::momentCalc2D(), and Proto::Moments::momentCalc3D().
gaussElim()
int Proto::LSquares::gaussElim (double ** A, vector< double > & rhs) inline
gaussian elimination with partial pivoting
References addRows(), findPivot(), swapRows(), and timesBeta().
Referenced by LeastSquares().
swapRows() [1/2]
void Proto::LSquares::swapRows (double ** A, const int & rowi, const int & rowj, const int & numberOfCols) inline
Referenced by gaussElim().
swapRows() [2/2]
void Proto::LSquares::swapRows (vector< double > & rhs, const int & currRow, const int & pivot) inline
findPivot()
int Proto::LSquares::findPivot (double ** A, const int & currCol, const int & currRow, const int & numRows, int & pivot) inline
References Proto::max().
Referenced by gaussElim().
addRows() [1/2]
void Proto::LSquares::addRows (vector< double > & rhs, const int & rowi, const double & alpha, const int & rowj) inline
Referenced by gaussElim().
addRows() [2/2]
void Proto::LSquares::addRows (double ** A, const int & rowi, const double & alpha, const int & rowj, const int & numberOfCols) inline
timesBeta() [1/2]
void Proto::LSquares::timesBeta (vector< double > & rhs, const int & currRow, const double & Beta) inline
Referenced by gaussElim().
timesBeta() [2/2]
void Proto::LSquares::timesBeta (double ** A, const int & rowi, const double & Beta, const int & numberOfcols) inline
transpose()
void Proto::LSquares::transpose (double ** a_A, double ** a_Atrans, const int & a_numRows, const int & a_numCols) inline
Referenced by LeastSquares().
matMul()
void Proto::LSquares::matMul (double ** a_A, double ** a_B, double ** a_C, const int & a_numRowsA, const int & a_numColsA, const int & a_numColsB) inline
Referenced by LeastSquares().
backSolve()
void Proto::LSquares::backSolve (double ** a_A, const vector< double > & a_rhs, const int & a_numArows, vector< double > & a_x) inline
References N.
Referenced by LeastSquares().
AtimesX()
void Proto::LSquares::AtimesX (double ** A, const vector< double > & x, const int & numRowsA, vector< double > & Ax) inline
Referenced by LeastSquares().
allocArray()
void Proto::LSquares::allocArray (const int & rows, const int & cols, double **& A) inline
Referenced by LeastSquares(), Proto::Moments::momentCalc2D(), and Proto::Moments::momentCalc3D().
freeArray()
void Proto::LSquares::freeArray (const int & rows, const int & cols, double **& A) inline
References A.
Referenced by LeastSquares(), Proto::Moments::momentCalc2D(), and Proto::Moments::momentCalc3D().
The documentation for this class was generated from the following files:
Proto_LSquares.H
Proto_LSquaresImplem.H