Chombo_4: EBLinearInFused< cent, data_t, ncomp > Class Template Reference
EBLinearInFused< cent, data_t, ncomp > Class Template Reference
#include <Proto_fusedLinear.H>
Public Attributes
unsigned int m_numberOfIteration = 0
bool isAllocated = false
unsigned int * m_end = nullptr
EBIndex< cent > ** m_indiciesDst = nullptr
unsigned int * m_indiciesSizeDst = nullptr
void ** m_buf = nullptr
data_t ** m_dst = nullptr
Proto::Point * m_box_inf = nullptr
Proto::Point * m_box_high = nullptr
Private Member Functions
EBLinearInFused ()
void allocate (unsigned int a_numberOfIteration)
template<typename T >
void fillparams (Chombo4::CopierBuffer *a_buffer, T &a_dst, unsigned int a_destComps_begin, unsigned int a_destComps_size)
void fillparam (unsigned int a_it, void *a_dst, IrregData< cent, data_t, ncomp > &a_src, ::Proto::Box a_bx)
void fillOne (unsigned int it, EBIndex< cent > *indiciesDst, unsigned int indiciesSizeDst, void *buf, data_t *dst, Point box_inf, Point box_high)
void launch ()
Constructor & Destructor Documentation
EBLinearInFused()
template<CENTERING cent, class data_t , unsigned int ncomp> EBLinearInFused< cent, data_t, ncomp >::EBLinearInFused () inline private
Member Function Documentation
allocate()
template<CENTERING cent, class data_t , unsigned int ncomp> void EBLinearInFused< cent, data_t, ncomp >::allocate (unsigned int a_numberOfIteration) inline private
References EBBoxDataIndexerFused< cent, data_t, ncomp >::m_box_high, EBBoxDataIndexerFused< cent, data_t, ncomp >::m_box_inf, EBBoxDataIndexerFused< cent, data_t, ncomp >::m_dst, EBBoxDataIndexerFused< cent, data_t, ncomp >::m_indiciesDst, EBBoxDataIndexerFused< cent, data_t, ncomp >::m_indiciesSizeDst, and EBBoxDataIndexerFused< cent, data_t, ncomp >::m_numberOfIteration.
fillparams()
template<CENTERING cent, class data_t , unsigned int ncomp> template<typename T > void EBLinearInFused< cent, data_t, ncomp >::fillparams (Chombo4::CopierBuffer * a_buffer, T & a_dst, unsigned int a_destComps_begin, unsigned int a_destComps_size) inline private
References EBBoxDataIndexerFused< cent, data_t, ncomp >::fillparam().
fillparam()
template<CENTERING cent, class data_t , unsigned int ncomp> void EBLinearInFused< cent, data_t, ncomp >::fillparam (unsigned int a_it, void * a_dst, IrregData< cent, data_t, ncomp > & a_src, ::Proto::Box a_bx) inline private
References EBBoxDataIndexerFused< cent, data_t, ncomp >::fillone().
fillOne()
template<CENTERING cent, class data_t , unsigned int ncomp> void EBLinearInFused< cent, data_t, ncomp >::fillOne (unsigned int it, EBIndex< cent > * indiciesDst, unsigned int indiciesSizeDst, void * buf, data_t * dst, Point box_inf, Point box_high) inline private
References EBBoxDataIndexerFused< cent, data_t, ncomp >::m_box_high, EBBoxDataIndexerFused< cent, data_t, ncomp >::m_box_inf, EBBoxDataIndexerFused< cent, data_t, ncomp >::m_dst, EBBoxDataIndexerFused< cent, data_t, ncomp >::m_indiciesDst, and EBBoxDataIndexerFused< cent, data_t, ncomp >::m_indiciesSizeDst.
launch()
template<CENTERING cent, class data_t , unsigned int ncomp> void EBLinearInFused< cent, data_t, ncomp >::launch () inline private
References kernel_eblinearout(), EBBoxDataIndexerFused< cent, data_t, ncomp >::m_box_high, EBBoxDataIndexerFused< cent, data_t, ncomp >::m_box_inf, EBBoxDataIndexerFused< cent, data_t, ncomp >::m_dst, EBBoxDataIndexerFused< cent, data_t, ncomp >::m_indiciesDst, EBBoxDataIndexerFused< cent, data_t, ncomp >::m_indiciesSizeDst, and EBBoxDataIndexerFused< cent, data_t, ncomp >::m_numberOfIteration.
Member Data Documentation
m_numberOfIteration
template<CENTERING cent, class data_t , unsigned int ncomp> unsigned int EBLinearInFused< cent, data_t, ncomp >::m_numberOfIteration = 0
isAllocated
template<CENTERING cent, class data_t , unsigned int ncomp> bool EBLinearInFused< cent, data_t, ncomp >::isAllocated = false
m_end
template<CENTERING cent, class data_t , unsigned int ncomp> unsigned int* EBLinearInFused< cent, data_t, ncomp >::m_end = nullptr
m_indiciesDst
template<CENTERING cent, class data_t , unsigned int ncomp> EBIndex<cent>** EBLinearInFused< cent, data_t, ncomp >::m_indiciesDst = nullptr
m_indiciesSizeDst
template<CENTERING cent, class data_t , unsigned int ncomp> unsigned int* EBLinearInFused< cent, data_t, ncomp >::m_indiciesSizeDst = nullptr
m_buf
template<CENTERING cent, class data_t , unsigned int ncomp> void** EBLinearInFused< cent, data_t, ncomp >::m_buf = nullptr
m_dst
template<CENTERING cent, class data_t , unsigned int ncomp> data_t** EBLinearInFused< cent, data_t, ncomp >::m_dst = nullptr
m_box_inf
template<CENTERING cent, class data_t , unsigned int ncomp> Proto::Point* EBLinearInFused< cent, data_t, ncomp >::m_box_inf = nullptr
m_box_high
template<CENTERING cent, class data_t , unsigned int ncomp> Proto::Point* EBLinearInFused< cent, data_t, ncomp >::m_box_high = nullptr
The documentation for this class was generated from the following file:
Proto_fusedLinear.H