Chombo_4: Proto::PointSetIterator Class Reference
Proto::PointSetIterator Class Reference
#include <Proto_PointSet.H>
Public Member Functions
PointSetIterator ()
PointSetIterator (const PointSet &ivs)
void define (const PointSet &ivs)
const Point & operator() () const
bool ok () const
void operator++ ()
void begin ()
void end ()
void clear ()
Private Attributes
const PointSet * m_ivs
std::set< Point >::iterator m_iter
Constructor & Destructor Documentation
PointSetIterator() [1/2]
Proto::PointSetIterator::PointSetIterator () inline
Referenced by Proto::PointSet::numPts().
PointSetIterator() [2/2]
Proto::PointSetIterator::PointSetIterator (const PointSet & ivs) inline
References define(), and Proto::PointSet::m_stdSet.
Member Function Documentation
define()
void Proto::PointSetIterator::define (const PointSet & ivs) inline
References Proto::PointSet::m_stdSet, and operator()().
Referenced by PointSetIterator().
operator()()
const Point & Proto::PointSetIterator::operator() () const inline
References ok().
Referenced by define().
ok()
bool Proto::PointSetIterator::ok () const inline
References operator++().
Referenced by EBLevelBoxData< cent, NUMCOMPS >::copyHostToFAB(), Proto::getAllFaces(), Proto::EBGraph::getCutFaces(), Proto::getIrregFaces(), Proto::EBStencilArchive< fcent, CELL, order, double >::getIrregLocations(), Proto::EBStencilArchive< CELL, CELL, order, double >::getIrregLocations(), Proto::EBGraph::getIrregVoFs(), operator()(), and writeEBLevelHDF5().
operator++()
void Proto::PointSetIterator::operator++ () inline
References begin().
Referenced by ok().
begin()
void Proto::PointSetIterator::begin () inline
References end().
Referenced by operator++().
end()
void Proto::PointSetIterator::end () inline
References clear().
Referenced by begin().
clear()
void Proto::PointSetIterator::clear () inline
Referenced by end().
Member Data Documentation
m_ivs
const PointSet* Proto::PointSetIterator::m_ivs private
m_iter
std::set<Point>::iterator Proto::PointSetIterator::m_iter private
The documentation for this class was generated from the following files:
Proto_PointSet.H
Proto_PointSetImplem.H