Chombo_4: ScalarFluxAliasFactory< srcComp, dstComp > Class Template Reference
ScalarFluxAliasFactory< srcComp, dstComp > Class Template Reference
#include <Chombo_EBLevelFluxData.H>
Public Types
typedef CH4_Data_Choreography::DistributedData< EBFluxData< Real, srcComp > > devi_src_comp_t
typedef CH4_Data_Choreography::DistributedData< EBHostFluxData< Real, srcComp > > host_src_comp_t
typedef CH4_Data_Choreography::DistributedData< EBFluxData< Real, dstComp > > devi_dst_comp_t
typedef CH4_Data_Choreography::DistributedData< EBHostFluxData< Real, dstComp > > host_dst_comp_t
typedef CH4_Data_Choreography::DistributedData< EBGraph > graph_distrib_t
Public Member Functions
ScalarFluxAliasFactory (devi_src_comp_t *a_source, unsigned int a_whichcomp)
virtual ~ScalarFluxAliasFactory ()
virtual EBFluxData< Real, dstComp > * create (const Chombo4::Box &a_box, int ncomps, const DataIndex &a_datInd) const
factory function. creates a new 'T' object
Public Member Functions inherited from DataFactory< EBFluxData< Real, dstComp > >
virtual ~DataFactory ()
virtual EBFluxData< Real, dstComp > * create (const Box &box, int ncomps, const DataIndex &a_datInd) const=0
factory function. creates a new 'T' object
virtual bool callDelete () const
virtual bool graphConstructor () const
Private Member Functions
ScalarFluxAliasFactory ()
Private Attributes
devi_src_comp_t * m_source
unsigned int m_whichcomp
Member Typedef Documentation
devi_src_comp_t
template<unsigned int srcComp, unsigned int dstComp> typedef CH4_Data_Choreography::DistributedData<EBFluxData< Real, srcComp> > ScalarFluxAliasFactory< srcComp, dstComp >::devi_src_comp_t
host_src_comp_t
template<unsigned int srcComp, unsigned int dstComp> typedef CH4_Data_Choreography::DistributedData<EBHostFluxData<Real, srcComp> > ScalarFluxAliasFactory< srcComp, dstComp >::host_src_comp_t
devi_dst_comp_t
template<unsigned int srcComp, unsigned int dstComp> typedef CH4_Data_Choreography::DistributedData<EBFluxData< Real, dstComp> > ScalarFluxAliasFactory< srcComp, dstComp >::devi_dst_comp_t
host_dst_comp_t
template<unsigned int srcComp, unsigned int dstComp> typedef CH4_Data_Choreography::DistributedData<EBHostFluxData<Real, dstComp> > ScalarFluxAliasFactory< srcComp, dstComp >::host_dst_comp_t
graph_distrib_t
template<unsigned int srcComp, unsigned int dstComp> typedef CH4_Data_Choreography::DistributedData<EBGraph> ScalarFluxAliasFactory< srcComp, dstComp >::graph_distrib_t
Constructor & Destructor Documentation
ScalarFluxAliasFactory() [1/2]
template<unsigned int srcComp, unsigned int dstComp> ScalarFluxAliasFactory< srcComp, dstComp >::ScalarFluxAliasFactory (devi_src_comp_t * a_source, unsigned int a_whichcomp) inline
References ScalarFluxAliasFactory< srcComp, dstComp >::m_source, and ScalarFluxAliasFactory< srcComp, dstComp >::m_whichcomp.
~ScalarFluxAliasFactory()
template<unsigned int srcComp, unsigned int dstComp> virtual ScalarFluxAliasFactory< srcComp, dstComp >::~ScalarFluxAliasFactory () inline virtual
ScalarFluxAliasFactory() [2/2]
template<unsigned int srcComp, unsigned int dstComp> ScalarFluxAliasFactory< srcComp, dstComp >::ScalarFluxAliasFactory () private
Referenced by ScalarFluxAliasFactory< srcComp, dstComp >::create().
Member Function Documentation
create()
template<unsigned int srcComp, unsigned int dstComp> virtual EBFluxData<Real, dstComp>* ScalarFluxAliasFactory< srcComp, dstComp >::create (const Chombo4::Box & a_box, int ncomps, const DataIndex & a_datInd) const inline virtual
factory function. creates a new 'T' object
creates a new 'T' object and returns a pointer to it.
References Proto::EBFluxData< data_t, ncomp >::define(), ScalarFluxAliasFactory< srcComp, dstComp >::m_whichcomp, and ScalarFluxAliasFactory< srcComp, dstComp >::ScalarFluxAliasFactory().
Member Data Documentation
m_source
template<unsigned int srcComp, unsigned int dstComp> devi_src_comp_t* ScalarFluxAliasFactory< srcComp, dstComp >::m_source private
Referenced by ScalarFluxAliasFactory< srcComp, dstComp >::ScalarFluxAliasFactory().
m_whichcomp
template<unsigned int srcComp, unsigned int dstComp> unsigned int ScalarFluxAliasFactory< srcComp, dstComp >::m_whichcomp private
Referenced by ScalarFluxAliasFactory< srcComp, dstComp >::create(), and ScalarFluxAliasFactory< srcComp, dstComp >::ScalarFluxAliasFactory().
The documentation for this class was generated from the following file:
Chombo_EBLevelFluxData.H