Chombo_4: Proto::CutCellMoments< dim > Class Template Reference
Proto::CutCellMoments< dim > Class Template Reference
#include <Proto_CutCellMoments.H>
Public Types
typedef IndexTM< int, dim > IvDim
typedef IndexTM< double, dim > RvDim
typedef map< IvDim, double > PthMoment
typedef map< IndexTM< int, dim-1 >, double > PthMomentLesserDimension
typedef map< IndexTM< int, 1 >, double > OneDMoments
typedef map< int, IvDim > LocPthMoment
typedef map< IvDim, int > PthMomentLoc
typedef map< Iv2, CutCellMoments< dim-1 > > BdCutCellMoments
Public Member Functions
CutCellMoments ()
CutCellMoments (const CutCellMoments< dim > &a_cutCellMoments)
CutCellMoments (const IFData< dim > &a_info)
~CutCellMoments ()
const CutCellMoments< dim - 1 > getBdCutCellMoments (const Iv2 &a_bdId) const
double changeMomentCoordinates (PthMoment &a_refinedMomentMap, const IndexTM< int, dim > &a_monomial, const IndexTM< double, dim > &a_refinedCenterDelta)
void changeMomentCoordinatesToCellCenter ()
void changeMomentCoordinatesToParentCenter ()
void initialize (CutCellMoments< dim > &a_refinedCutCell)
void initializeMap (PthMoment &a_map1, PthMoment &a_map2)
void initializeMap (PthMomentLesserDimension &a_map1, PthMomentLesserDimension &a_map2)
double getBdMoment (const IvDim &a_mono, const IFData< dim+1 > &a_IFData, const IndexTM< double, dim > &a_refinedCenterDelta, PthMoment a_fullCellMap=PthMoment())
double getBdEBMoment (const IvDim &a_mono, const IFData< dim+1 > &a_IFData, const IndexTM< double, dim > &a_refinedCenterDelta)
void addBdMoments (CutCellMoments< dim > &a_coarseCutCell, const IFData< dim+1 > &a_IFData, const int &a_degreePmax, const bool &a_useConstraints, const IndexTM< double, dim > &a_refinedCenterDelta, const IndexTM< int, dim > &a_localHilo)
double fullCellQuadrature (const IndexTM< int, dim > &a_mono, const CoordinateSystem< dim > &a_coord)
double getMoment (const IvDim &a_mono, const EBorVol &a_EBorVOL) const
double getVol (const EBorVol &a_EBorVol) const
RvDim getCentroid (const EBorVol &a_EBorVOL) const
double getResidual (const int &a_iDegree, const int &a_normJ) const
void setResidual (const double &a_value, const int &a_iDegree, const int &a_normJ)
std::vector< double > sliceResidual (const int &a_iDegree) const
bool isCovered () const
bool isRegular () const
void operator= (const CutCellMoments< dim > &a_cutCellMoments)
Public Attributes
PthMoment m_moments
PthMoment m_EBmoments
BdCutCellMoments m_bdCutCellMoments
IFData< dim > m_IFData
bool m_bdCCOn
std::vector< std::vector< double > > m_residual
int m_numActiveBounds
bool m_badNormal
Member Typedef Documentation
IvDim
template<int dim> typedef IndexTM<int,dim> Proto::CutCellMoments< dim >::IvDim
RvDim
template<int dim> typedef IndexTM<double,dim> Proto::CutCellMoments< dim >::RvDim
PthMoment
template<int dim> typedef map<IvDim,double > Proto::CutCellMoments< dim >::PthMoment
PthMomentLesserDimension
template<int dim> typedef map<IndexTM<int,dim-1>,double > Proto::CutCellMoments< dim >::PthMomentLesserDimension
OneDMoments
template<int dim> typedef map<IndexTM<int,1>,double > Proto::CutCellMoments< dim >::OneDMoments
LocPthMoment
template<int dim> typedef map<int,IvDim> Proto::CutCellMoments< dim >::LocPthMoment
PthMomentLoc
template<int dim> typedef map<IvDim,int > Proto::CutCellMoments< dim >::PthMomentLoc
BdCutCellMoments
template<int dim> typedef map<Iv2,CutCellMoments<dim-1> > Proto::CutCellMoments< dim >::BdCutCellMoments
Constructor & Destructor Documentation
CutCellMoments() [1/3]
template<int dim> Proto::CutCellMoments< dim >::CutCellMoments () inline
CutCellMoments() [2/3]
template<int dim> Proto::CutCellMoments< dim >::CutCellMoments (const CutCellMoments< dim > & a_cutCellMoments) inline
CutCellMoments() [3/3]
template<int dim> Proto::CutCellMoments< dim >::CutCellMoments (const IFData< dim > & a_info) inline
References BDID_DIR, BDID_HILO, Proto::CutCellMoments< dim >::m_badNormal, Proto::CutCellMoments< dim >::m_bdCCOn, Proto::CutCellMoments< dim >::m_bdCutCellMoments, and Proto::IFData< dim >::m_maxOrder.
~CutCellMoments()
template<int dim> Proto::CutCellMoments< dim >::~CutCellMoments () inline
Member Function Documentation
getBdCutCellMoments()
template<int dim> const CutCellMoments< dim - 1 > Proto::CutCellMoments< dim >::getBdCutCellMoments (const Iv2 & a_bdId) const inline
References Proto::CutCellMoments< dim >::m_bdCutCellMoments.
Referenced by Proto::CutCellMoments< dim >::initialize().
changeMomentCoordinates()
template<int dim> double Proto::CutCellMoments< dim >::changeMomentCoordinates (PthMoment & a_refinedMomentMap, const IndexTM< int, dim > & a_monomial, const IndexTM< double, dim > & a_refinedCenterDelta) inline
References Proto::factorial().
Referenced by Proto::CutCellMoments< dim >::changeMomentCoordinatesToCellCenter(), Proto::CutCellMoments< 1 >::changeMomentCoordinatesToCellCenter(), Proto::CutCellMoments< dim >::changeMomentCoordinatesToParentCenter(), Proto::CutCellMoments< 1 >::changeMomentCoordinatesToParentCenter(), Proto::CutCellMoments< dim >::getBdEBMoment(), Proto::CutCellMoments< dim >::getBdMoment(), and Proto::CutCellMoments< 1 >::getBdMoment().
changeMomentCoordinatesToCellCenter()
template<int dim> void Proto::CutCellMoments< dim >::changeMomentCoordinatesToCellCenter () inline
References Proto::CutCellMoments< dim >::changeMomentCoordinates(), Proto::CutCellMoments< dim >::m_EBmoments, Proto::CutCellMoments< dim >::m_IFData, and Proto::CutCellMoments< dim >::m_moments.
changeMomentCoordinatesToParentCenter()
template<int dim> void Proto::CutCellMoments< dim >::changeMomentCoordinatesToParentCenter () inline
References Proto::CutCellMoments< dim >::changeMomentCoordinates(), Proto::CutCellMoments< dim >::m_EBmoments, Proto::CutCellMoments< dim >::m_IFData, and Proto::CutCellMoments< dim >::m_moments.
initialize()
template<int dim> void Proto::CutCellMoments< dim >::initialize (CutCellMoments< dim > & a_refinedCutCell) inline
References Proto::CutCellMoments< dim >::getBdCutCellMoments(), Proto::CutCellMoments< dim >::initializeMap(), Proto::CutCellMoments< dim >::m_bdCutCellMoments, Proto::CutCellMoments< dim >::m_EBmoments, and Proto::CutCellMoments< dim >::m_moments.
initializeMap() [1/2]
template<int dim> void Proto::CutCellMoments< dim >::initializeMap (PthMoment & a_map1, PthMoment & a_map2) inline
Referenced by Proto::CutCellMoments< dim >::initialize(), and Proto::CutCellMoments< 1 >::initialize().
initializeMap() [2/2]
template<int dim> void Proto::CutCellMoments< dim >::initializeMap (PthMomentLesserDimension & a_map1, PthMomentLesserDimension & a_map2) inline
getBdMoment()
template<int dim> double Proto::CutCellMoments< dim >::getBdMoment (const IvDim & a_mono, const IFData< dim+1 > & a_IFData, const IndexTM< double, dim > & a_refinedCenterDelta, PthMoment a_fullCellMap = PthMoment()) inline
References Proto::CutCellMoments< dim >::changeMomentCoordinates(), LARGEREALVAL, Proto::IFData< dim >::m_allVerticesIn, Proto::IFData< dim >::m_allVerticesOut, and Proto::CutCellMoments< dim >::m_moments.
Referenced by Proto::CutCellMoments< dim >::addBdMoments(), and Proto::CutCellMoments< 1 >::addBdMoments().
getBdEBMoment()
template<int dim> double Proto::CutCellMoments< dim >::getBdEBMoment (const IvDim & a_mono, const IFData< dim+1 > & a_IFData, const IndexTM< double, dim > & a_refinedCenterDelta) inline
References Proto::CutCellMoments< dim >::changeMomentCoordinates(), LARGEREALVAL, Proto::IFData< dim >::m_allVerticesIn, Proto::IFData< dim >::m_allVerticesOut, and Proto::CutCellMoments< dim >::m_EBmoments.
Referenced by Proto::CutCellMoments< dim >::addBdMoments().
addBdMoments()
template<int dim> void Proto::CutCellMoments< dim >::addBdMoments (CutCellMoments< dim > & a_coarseCutCell, const IFData< dim+1 > & a_IFData, const int & a_degreePmax, const bool & a_useConstraints, const IndexTM< double, dim > & a_refinedCenterDelta, const IndexTM< int, dim > & a_localHilo) inline
References Proto::CutCellMoments< dim >::fullCellQuadrature(), Proto::CutCellMoments< dim >::getBdEBMoment(), Proto::CutCellMoments< dim >::getBdMoment(), Proto::LSProblem< dim >::getMonomialLocMapDegreeP(), Proto::LSProblem< dim >::getMonomialLocMapDegreePLess1(), LARGEINTVAL, Proto::IFData< dim >::m_allVerticesIn, Proto::CutCellMoments< dim >::m_bdCutCellMoments, Proto::CutCellMoments< dim >::m_EBmoments, Proto::CutCellMoments< dim >::m_IFData, and Proto::CutCellMoments< dim >::m_moments.
fullCellQuadrature()
template<int dim> double Proto::CutCellMoments< dim >::fullCellQuadrature (const IndexTM< int, dim > & a_mono, const CoordinateSystem< dim > & a_coord) inline
References Proto::CoordinateSystem< dim >::convertDir(), and Proto::CutCellMoments< dim >::m_IFData.
Referenced by Proto::CutCellMoments< dim >::addBdMoments().
getMoment()
template<int dim> double Proto::CutCellMoments< dim >::getMoment (const IvDim & a_mono, const EBorVol & a_EBorVOL) const inline
References Proto::EBMoment, LARGEREALVAL, Proto::CutCellMoments< dim >::m_EBmoments, Proto::CutCellMoments< dim >::m_moments, and Proto::VolMoment.
Referenced by Proto::CutCellMoments< dim >::getCentroid(), Proto::CutCellMoments< 1 >::getCentroid(), Proto::CutCellMoments< 1 >::getMoment(), Proto::CutCellMoments< dim >::getVol(), and Proto::CutCellMoments< 1 >::getVol().
getVol()
template<int dim> double Proto::CutCellMoments< dim >::getVol (const EBorVol & a_EBorVol) const inline
References Proto::CutCellMoments< dim >::getMoment(), and Proto::IndexTM< T, N >::Zero.
Referenced by Proto::CutCellMoments< dim >::getCentroid(), and Proto::CutCellMoments< 1 >::getCentroid().
getCentroid()
template<int dim> IndexTM< double, dim > Proto::CutCellMoments< dim >::getCentroid (const EBorVol & a_EBorVOL) const inline
References Proto::CutCellMoments< dim >::getMoment(), and Proto::CutCellMoments< dim >::getVol().
getResidual()
template<int dim> double Proto::CutCellMoments< dim >::getResidual (const int & a_iDegree, const int & a_normJ) const inline
References Proto::CutCellMoments< dim >::isCovered(), Proto::CutCellMoments< dim >::isRegular(), and Proto::CutCellMoments< dim >::m_residual.
setResidual()
template<int dim> void Proto::CutCellMoments< dim >::setResidual (const double & a_value, const int & a_iDegree, const int & a_normJ) inline
References Proto::CutCellMoments< dim >::isCovered(), Proto::CutCellMoments< dim >::isRegular(), and Proto::CutCellMoments< dim >::m_residual.
sliceResidual()
template<int dim> vector< double > Proto::CutCellMoments< dim >::sliceResidual (const int & a_iDegree) const inline
References Proto::CutCellMoments< dim >::isCovered(), Proto::CutCellMoments< dim >::isRegular(), and Proto::CutCellMoments< dim >::m_residual.
isCovered()
template<int dim> bool Proto::CutCellMoments< dim >::isCovered () const inline
References Proto::CutCellMoments< dim >::m_IFData.
Referenced by Proto::CutCellMoments< dim >::getResidual(), Proto::CutCellMoments< dim >::setResidual(), and Proto::CutCellMoments< dim >::sliceResidual().
isRegular()
template<int dim> bool Proto::CutCellMoments< dim >::isRegular () const inline
References Proto::CutCellMoments< dim >::m_bdCCOn, and Proto::CutCellMoments< dim >::m_IFData.
Referenced by Proto::CutCellMoments< dim >::getResidual(), Proto::CutCellMoments< dim >::setResidual(), and Proto::CutCellMoments< dim >::sliceResidual().
operator=()
template<int dim> void Proto::CutCellMoments< dim >::operator= (const CutCellMoments< dim > & a_cutCellMoments) inline
References Proto::CutCellMoments< dim >::m_badNormal, Proto::CutCellMoments< dim >::m_bdCCOn, Proto::CutCellMoments< dim >::m_bdCutCellMoments, Proto::CutCellMoments< dim >::m_EBmoments, Proto::CutCellMoments< dim >::m_IFData, Proto::CutCellMoments< dim >::m_moments, Proto::CutCellMoments< dim >::m_numActiveBounds, and Proto::CutCellMoments< dim >::m_residual.
Member Data Documentation
m_moments
template<int dim> PthMoment Proto::CutCellMoments< dim >::m_moments
Referenced by Proto::CutCellMoments< dim >::addBdMoments(), Proto::CutCellMoments< dim >::changeMomentCoordinatesToCellCenter(), Proto::CutCellMoments< 1 >::changeMomentCoordinatesToCellCenter(), Proto::CutCellMoments< dim >::changeMomentCoordinatesToParentCenter(), Proto::CutCellMoments< 1 >::changeMomentCoordinatesToParentCenter(), Proto::LSProblem< dim >::computeBounds(), Proto::CutCellMoments< dim >::getBdMoment(), Proto::CutCellMoments< 1 >::getBdMoment(), Proto::CutCellMoments< dim >::getMoment(), Proto::CutCellMoments< 1 >::getMoment(), Proto::CutCellMoments< dim >::initialize(), Proto::CutCellMoments< 1 >::initialize(), Proto::CutCellMoments< dim >::operator=(), and Proto::CutCellMoments< 1 >::operator=().
m_EBmoments
template<int dim> PthMoment Proto::CutCellMoments< dim >::m_EBmoments
Referenced by Proto::CutCellMoments< dim >::addBdMoments(), Proto::CutCellMoments< dim >::changeMomentCoordinatesToCellCenter(), Proto::CutCellMoments< dim >::changeMomentCoordinatesToParentCenter(), Proto::LSProblem< dim >::computeBounds(), Proto::CutCellMoments< dim >::getBdEBMoment(), Proto::CutCellMoments< dim >::getMoment(), Proto::CutCellMoments< dim >::initialize(), Proto::CutCellMoments< 1 >::initialize(), and Proto::CutCellMoments< dim >::operator=().
m_bdCutCellMoments
template<int dim> BdCutCellMoments Proto::CutCellMoments< dim >::m_bdCutCellMoments
Referenced by Proto::CutCellMoments< dim >::addBdMoments(), Proto::CutCellMoments< dim >::CutCellMoments(), Proto::CutCellMoments< dim >::getBdCutCellMoments(), Proto::CutCellMoments< dim >::initialize(), and Proto::CutCellMoments< dim >::operator=().
m_IFData
template<int dim> IFData<dim> Proto::CutCellMoments< dim >::m_IFData
Referenced by Proto::CutCellMoments< dim >::addBdMoments(), Proto::CutCellMoments< 1 >::addBdMoments(), Proto::CutCellMoments< dim >::changeMomentCoordinatesToCellCenter(), Proto::CutCellMoments< 1 >::changeMomentCoordinatesToCellCenter(), Proto::CutCellMoments< dim >::changeMomentCoordinatesToParentCenter(), Proto::CutCellMoments< 1 >::changeMomentCoordinatesToParentCenter(), Proto::LSProblem< dim >::computeBounds(), Proto::CutCellMoments< dim >::fullCellQuadrature(), Proto::CutCellMoments< 1 >::getBdMoment(), Proto::CutCellMoments< dim >::isCovered(), Proto::CutCellMoments< 1 >::isCovered(), Proto::CutCellMoments< dim >::isRegular(), Proto::CutCellMoments< 1 >::isRegular(), Proto::CutCellMoments< dim >::operator=(), and Proto::CutCellMoments< 1 >::operator=().
m_bdCCOn
template<int dim> bool Proto::CutCellMoments< dim >::m_bdCCOn
Referenced by Proto::CutCellMoments< dim >::CutCellMoments(), Proto::CutCellMoments< dim >::isRegular(), and Proto::CutCellMoments< dim >::operator=().
m_residual
template<int dim> std::vector<std::vector<double> > Proto::CutCellMoments< dim >::m_residual
Referenced by Proto::CutCellMoments< dim >::getResidual(), Proto::CutCellMoments< dim >::operator=(), Proto::CutCellMoments< dim >::setResidual(), and Proto::CutCellMoments< dim >::sliceResidual().
m_numActiveBounds
template<int dim> int Proto::CutCellMoments< dim >::m_numActiveBounds
Referenced by Proto::CutCellMoments< dim >::operator=().
m_badNormal
template<int dim> bool Proto::CutCellMoments< dim >::m_badNormal
Referenced by Proto::CutCellMoments< dim >::CutCellMoments(), Proto::CutCellMoments< 1 >::CutCellMoments(), and Proto::CutCellMoments< dim >::operator=().
The documentation for this class was generated from the following files:
Proto_CutCellMoments.H
Proto_CutCellMomentsImplem.H