Chombo_4: EBCM::PETSc_Framework< ebcm_order >::HelmholtzOp Class Reference
EBCM::PETSc_Framework< ebcm_order >::HelmholtzOp Class Reference
#include <Chombo_EBCM_PETSc_Framework.H>
Public Types
typedef Proto::Side pr_sd
typedef Proto::Box pr_box
Public Member Functions
HelmholtzOp (const double &a_alpha, const double &a_beta, const int &a_weight_power, const shared_ptr< ebcm_meta > &a_meta_ptr, const int &a_ghost, bool a_print=false)
virtual ~HelmholtzOp ()
virtual shared_ptr< local_stencil_t > getLocalStencil (const pr_pt &a_pt, const ebcm_graph &a_graph, bool a_print=false)
this gets done by the derived class
Public Member Functions inherited from EBCM::PETSc_Framework< ebcm_order >::Base_PETSc_Op
virtual ~Base_PETSc_Op ()
Base_PETSc_Op (const shared_ptr< ebcm_meta > &a_meta_ptr, const int &a_ghost, bool a_print=false)
Public Attributes
double m_alpha
double m_beta
int m_weight_power
Public Attributes inherited from EBCM::PETSc_Framework< ebcm_order >::Base_PETSc_Op
shared_ptr< petsc_mat > m_mat_ptr
shared_ptr< ebcm_data > m_row_map_ptr
shared_ptr< ebcm_meta > m_meta_ptr
int m_ghost
std::vector< int > m_numPtsPerBox
int m_numPtsThisProc
int m_numPtsAllProcs
int m_startPtThisProc
Additional Inherited Members
Protected Member Functions inherited from EBCM::PETSc_Framework< ebcm_order >::Base_PETSc_Op
PetscInt createMatrixRowMap (bool a_print=false)
makes m_row_map_ptr (operator uses this to map between volumes and petsc matrix rows)
PetscInt createOperatorPetscMatrix (bool a_print=false)
makes m_mat_ptr (operator uses this to map between volumes and petsc matrix rows)
PetscInt formMatrix (bool a_print=false)
sets the actual values in *m_mat_ptr
Detailed Description
template<int ebcm_order>
class EBCM::PETSc_Framework< ebcm_order >::HelmholtzOp
Class which forms a helmholtz operator. This creates an operator of the form L(phi) = alpha phi + beta * div(F(phi))
Member Typedef Documentation
pr_sd
template<int ebcm_order> typedef Proto::Side EBCM::PETSc_Framework< ebcm_order >::HelmholtzOp::pr_sd
pr_box
template<int ebcm_order> typedef Proto::Box EBCM::PETSc_Framework< ebcm_order >::HelmholtzOp::pr_box
Constructor & Destructor Documentation
HelmholtzOp()
template<int ebcm_order> EBCM::PETSc_Framework< ebcm_order >::HelmholtzOp::HelmholtzOp (const double & a_alpha, const double & a_beta, const int & a_weight_power, const shared_ptr< ebcm_meta > & a_meta_ptr, const int & a_ghost, bool a_print = false) inline
~HelmholtzOp()
template<int ebcm_order> virtual EBCM::PETSc_Framework< ebcm_order >::HelmholtzOp::~HelmholtzOp () inline virtual
Member Function Documentation
getLocalStencil()
template<int ebcm_order> virtual shared_ptr<local_stencil_t> EBCM::PETSc_Framework< ebcm_order >::HelmholtzOp::getLocalStencil (const pr_pt & a_pt, const ebcm_graph & a_graph, bool a_print = false) inline virtual
this gets done by the derived class
Implements EBCM::PETSc_Framework< ebcm_order >::Base_PETSc_Op.
References EBCM::faceSign(), EBCM::PETSc_Framework< ebcm_order >::getHelmholtzFluxStencil(), EBCM::EBCM_Graph< order >::getVolumeCoveringPoint(), and EBCM::EBCM_Volu< order >::m_xfaces.
Member Data Documentation
m_alpha
template<int ebcm_order> double EBCM::PETSc_Framework< ebcm_order >::HelmholtzOp::m_alpha
m_beta
template<int ebcm_order> double EBCM::PETSc_Framework< ebcm_order >::HelmholtzOp::m_beta
m_weight_power
template<int ebcm_order> int EBCM::PETSc_Framework< ebcm_order >::HelmholtzOp::m_weight_power
The documentation for this class was generated from the following file:
Chombo_EBCM_PETSc_Framework.H