Chombo_4: Proto::LSProblem< dim > Class Template Reference
Proto::LSProblem< dim > Class Template Reference
#include <Proto_LSProblem.H>
Public Member Functions
~LSProblem ()
LSProblem (const int &a_degreeP, const bool &a_useConstraints)
LSProblem (const int &a_orderAccuracy, const int &a_degreeP, const bool &a_useConstraints, const IndexTM< double, dim > &a_normal)
int invertNormalEq (const vector< double > &a_rhs, vector< double > &a_residual)
int getDegree ()
int getOrderAccuracy ()
void getMatrix (double **a_matrix)
void getRhs (vector< double > &a_rhs)
void getUnknowns (vector< double > &a_unknown)
void monoMaxMin (double &a_maxVal, double &a_minVal, const IndexTM< int, dim > &a_mono, const IFData< dim > &a_IFData)
void computeBounds (const IndexTM< double, dim > &a_dx, const CutCellMoments< dim > &a_ccm)
const LocPthMoment & getLocMonomialMapDegreeP () const
const PthMomentLoc & getMonomialLocMapDegreeP () const
const PthMomentLoc & getMonomialLocMapDegreePLess1 () const
double getUnknown (int loc)
int getNumberDegP ()
int getNumberDegPLess1 ()
int numActiveBounds () const
void setRhs (const vector< double > &a_rhs)
void setMatrix ()
void momentBounds (double &a_lobnd, double &a_hibnd, const IvDim &a_mono, const IFData< dim > &a_ifData)
void differentiate (int &a_coeff, IvDim &a_Dmono, int &a_idir, const IvDim &a_mono)
int nChooseR (int a_n, int a_r)
void fillMap (PthMomentLoc &a_monoLoc, LocPthMoment &a_locMono, const int &a_degree)
int numMonomials (const int &a_monoDegree)
int factorial (const int &a_n, const int &a_m=0)
void allocArray (const int &a_rows, const int &a_cols, double **&a_A)
void freeArray (const int &a_rows, const int &a_cols, double **&a_A)
Public Attributes
int m_order
int m_degreeP
int m_numActiveBounds
bool m_useConstraints
IndexTM< double, dim > m_normal
PthMomentLoc m_monoLocP
LocPthMoment m_locMonoP
int m_numP
PthMomentLoc m_monoLocPLess1
LocPthMoment m_locMonoPLess1
int m_numPLess1
double ** m_matrix
vector< double > m_unknowns
vector< double > m_rhs
vector< double > m_lowerBound
vector< double > m_upperBound
Private Types
typedef IndexTM< int, dim > IvDim
typedef map< IvDim, int > PthMomentLoc
typedef map< int, IvDim > LocPthMoment
Member Typedef Documentation
IvDim
template<int dim> typedef IndexTM<int,dim> Proto::LSProblem< dim >::IvDim private
PthMomentLoc
template<int dim> typedef map<IvDim,int > Proto::LSProblem< dim >::PthMomentLoc private
LocPthMoment
template<int dim> typedef map<int,IvDim> Proto::LSProblem< dim >::LocPthMoment private
Constructor & Destructor Documentation
~LSProblem()
template<int dim> Proto::LSProblem< dim >::~LSProblem () inline
LSProblem() [1/2]
template<int dim> Proto::LSProblem< dim >::LSProblem (const int & a_degreeP, const bool & a_useConstraints) inline
References Proto::LSProblem< dim >::fillMap(), Proto::LSProblem< dim >::m_degreeP, Proto::LSProblem< dim >::m_locMonoP, Proto::LSProblem< dim >::m_locMonoPLess1, Proto::LSProblem< dim >::m_matrix, Proto::LSProblem< dim >::m_monoLocP, Proto::LSProblem< dim >::m_monoLocPLess1, Proto::LSProblem< dim >::m_numP, Proto::LSProblem< dim >::m_numPLess1, and Proto::LSProblem< dim >::numMonomials().
LSProblem() [2/2]
template<int dim> Proto::LSProblem< dim >::LSProblem (const int & a_orderAccuracy, const int & a_degreeP, const bool & a_useConstraints, const IndexTM< double, dim > & a_normal) inline
References Proto::LSProblem< dim >::fillMap(), Proto::LSProblem< dim >::m_degreeP, Proto::LSProblem< dim >::m_locMonoP, Proto::LSProblem< dim >::m_locMonoPLess1, Proto::LSProblem< dim >::m_lowerBound, Proto::LSProblem< dim >::m_monoLocP, Proto::LSProblem< dim >::m_monoLocPLess1, Proto::LSProblem< dim >::m_numP, Proto::LSProblem< dim >::m_numPLess1, Proto::LSProblem< dim >::m_rhs, Proto::LSProblem< dim >::m_unknowns, Proto::LSProblem< dim >::m_upperBound, Proto::LSProblem< dim >::numMonomials(), and Proto::LSProblem< dim >::setMatrix().
Member Function Documentation
invertNormalEq()
template<int dim> int Proto::LSProblem< dim >::invertNormalEq (const vector< double > & a_rhs, vector< double > & a_residual) inline
References Proto::LSquares::LeastSquares(), Proto::LSProblem< dim >::m_matrix, Proto::LSProblem< dim >::m_numActiveBounds, Proto::LSProblem< dim >::m_numP, Proto::LSProblem< dim >::m_numPLess1, Proto::LSProblem< dim >::m_rhs, and Proto::LSProblem< dim >::m_unknowns.
Referenced by Proto::MinimalCCCM< dim >::computeMomentsRecursively().
getDegree()
template<int dim> int Proto::LSProblem< dim >::getDegree () inline
References Proto::LSProblem< dim >::m_degreeP.
getOrderAccuracy()
template<int dim> int Proto::LSProblem< dim >::getOrderAccuracy () inline
References Proto::LSProblem< dim >::computeBounds(), Proto::LSProblem< dim >::getMatrix(), Proto::LSProblem< dim >::getRhs(), Proto::LSProblem< dim >::getUnknowns(), Proto::LSProblem< dim >::m_order, and Proto::LSProblem< dim >::monoMaxMin().
getMatrix()
template<int dim> void Proto::LSProblem< dim >::getMatrix (double ** a_matrix) inline
Referenced by Proto::LSProblem< dim >::getOrderAccuracy().
getRhs()
template<int dim> void Proto::LSProblem< dim >::getRhs (vector< double > & a_rhs) inline
Referenced by Proto::LSProblem< dim >::getOrderAccuracy().
getUnknowns()
template<int dim> void Proto::LSProblem< dim >::getUnknowns (vector< double > & a_unknown) inline
Referenced by Proto::LSProblem< dim >::getOrderAccuracy().
monoMaxMin()
template<int dim> void Proto::LSProblem< dim >::monoMaxMin (double & a_maxVal, double & a_minVal, const IndexTM< int, dim > & a_mono, const IFData< dim > & a_IFData) inline
References Proto::IFData< dim >::m_cellCenterCoord, Proto::IFData< dim >::m_cornerSigns, Proto::IFData< dim >::m_localCoord, and Proto::POW().
Referenced by Proto::LSProblem< dim >::getOrderAccuracy().
computeBounds()
template<int dim> void Proto::LSProblem< dim >::computeBounds (const IndexTM< double, dim > & a_dx, const CutCellMoments< dim > & a_ccm) inline
References Proto::CutCellMoments< dim >::m_EBmoments, Proto::CutCellMoments< dim >::m_IFData, Proto::CutCellMoments< dim >::m_moments, max(), and Proto::IndexTM< T, N >::sum().
Referenced by Proto::LSProblem< dim >::getOrderAccuracy().
getLocMonomialMapDegreeP()
template<int dim> const LocPthMoment& Proto::LSProblem< dim >::getLocMonomialMapDegreeP () const inline
References Proto::LSProblem< dim >::m_locMonoP.
Referenced by Proto::MinimalCCCM< dim >::computeRhs().
getMonomialLocMapDegreeP()
template<int dim> const PthMomentLoc& Proto::LSProblem< dim >::getMonomialLocMapDegreeP () const inline
References Proto::LSProblem< dim >::m_monoLocP.
Referenced by Proto::CutCellMoments< dim >::addBdMoments(), and Proto::MinimalCCCM< dim >::computeMomentsRecursively().
getMonomialLocMapDegreePLess1()
template<int dim> const PthMomentLoc& Proto::LSProblem< dim >::getMonomialLocMapDegreePLess1 () const inline
References Proto::LSProblem< dim >::m_monoLocPLess1.
Referenced by Proto::CutCellMoments< dim >::addBdMoments(), and Proto::MinimalCCCM< dim >::computeMomentsRecursively().
getUnknown()
template<int dim> double Proto::LSProblem< dim >::getUnknown (int loc) inline
References Proto::LSProblem< dim >::m_unknowns.
Referenced by Proto::MinimalCCCM< dim >::computeMomentsRecursively().
getNumberDegP()
template<int dim> int Proto::LSProblem< dim >::getNumberDegP () inline
References Proto::LSProblem< dim >::m_numP.
Referenced by Proto::MinimalCCCM< dim >::computeMomentsRecursively(), and Proto::MinimalCCCM< dim >::computeRhs().
getNumberDegPLess1()
template<int dim> int Proto::LSProblem< dim >::getNumberDegPLess1 () inline
References Proto::LSProblem< dim >::m_numPLess1.
numActiveBounds()
template<int dim> int Proto::LSProblem< dim >::numActiveBounds () const inline
References Proto::LSProblem< dim >::allocArray(), Proto::LSProblem< dim >::differentiate(), Proto::LSProblem< dim >::factorial(), Proto::LSProblem< dim >::fillMap(), Proto::LSProblem< dim >::freeArray(), Proto::LSProblem< dim >::m_numActiveBounds, Proto::LSProblem< dim >::momentBounds(), Proto::LSProblem< dim >::nChooseR(), Proto::LSProblem< dim >::numMonomials(), Proto::LSProblem< dim >::setMatrix(), and Proto::LSProblem< dim >::setRhs().
setRhs()
template<int dim> void Proto::LSProblem< dim >::setRhs (const vector< double > & a_rhs) inline
Referenced by Proto::LSProblem< dim >::numActiveBounds().
setMatrix()
template<int dim> void Proto::LSProblem< dim >::setMatrix () inline
References Proto::LSProblem< dim >::allocArray(), Proto::LSProblem< dim >::differentiate(), LARGEINTVAL, Proto::LSProblem< dim >::m_matrix, Proto::LSProblem< dim >::m_monoLocP, Proto::LSProblem< dim >::m_monoLocPLess1, Proto::LSProblem< dim >::m_normal, Proto::LSProblem< dim >::m_numP, and Proto::LSProblem< dim >::m_numPLess1.
Referenced by Proto::LSProblem< dim >::LSProblem(), and Proto::LSProblem< dim >::numActiveBounds().
momentBounds()
template<int dim> void Proto::LSProblem< dim >::momentBounds (double & a_lobnd, double & a_hibnd, const IvDim & a_mono, const IFData< dim > & a_ifData) inline
References Proto::IFData< dim >::m_cellCenterCoord, Proto::IFData< dim >::m_cornerSigns, Proto::IFData< dim >::m_localCoord, and Proto::POW().
Referenced by Proto::LSProblem< dim >::numActiveBounds().
differentiate()
template<int dim> void Proto::LSProblem< dim >::differentiate (int & a_coeff, IvDim & a_Dmono, int & a_idir, const IvDim & a_mono) inline
References LARGEINTVAL.
Referenced by Proto::LSProblem< dim >::numActiveBounds(), and Proto::LSProblem< dim >::setMatrix().
nChooseR()
template<int dim> int Proto::LSProblem< dim >::nChooseR (int a_n, int a_r) inline
Referenced by Proto::LSProblem< dim >::numActiveBounds().
fillMap()
template<int dim> void Proto::LSProblem< dim >::fillMap (PthMomentLoc & a_monoLoc, LocPthMoment & a_locMono, const int & a_degree) inline
References Proto::generateMultiIndices().
Referenced by Proto::LSProblem< dim >::LSProblem(), and Proto::LSProblem< dim >::numActiveBounds().
numMonomials()
template<int dim> int Proto::LSProblem< dim >::numMonomials (const int & a_monoDegree) inline
References Proto::LSProblem< dim >::factorial(), and LARGEINTVAL.
Referenced by Proto::LSProblem< dim >::LSProblem(), and Proto::LSProblem< dim >::numActiveBounds().
factorial()
template<int dim> int Proto::LSProblem< dim >::factorial (const int & a_n, const int & a_m = 0) inline
Referenced by Proto::LSProblem< dim >::numActiveBounds(), and Proto::LSProblem< dim >::numMonomials().
allocArray()
template<int dim> void Proto::LSProblem< dim >::allocArray (const int & a_rows, const int & a_cols, double **& a_A) inline
Referenced by Proto::LSProblem< dim >::numActiveBounds(), and Proto::LSProblem< dim >::setMatrix().
freeArray()
template<int dim> void Proto::LSProblem< dim >::freeArray (const int & a_rows, const int & a_cols, double **& a_A) inline
Referenced by Proto::LSProblem< dim >::numActiveBounds().
Member Data Documentation
m_order
template<int dim> int Proto::LSProblem< dim >::m_order
Referenced by Proto::LSProblem< dim >::getOrderAccuracy().
m_degreeP
template<int dim> int Proto::LSProblem< dim >::m_degreeP
Referenced by Proto::LSProblem< dim >::getDegree(), and Proto::LSProblem< dim >::LSProblem().
m_numActiveBounds
template<int dim> int Proto::LSProblem< dim >::m_numActiveBounds
Referenced by Proto::LSProblem< dim >::invertNormalEq(), and Proto::LSProblem< dim >::numActiveBounds().
m_useConstraints
template<int dim> bool Proto::LSProblem< dim >::m_useConstraints
m_normal
template<int dim> IndexTM<double,dim> Proto::LSProblem< dim >::m_normal
Referenced by Proto::LSProblem< dim >::setMatrix().
m_monoLocP
template<int dim> PthMomentLoc Proto::LSProblem< dim >::m_monoLocP
Referenced by Proto::LSProblem< dim >::getMonomialLocMapDegreeP(), Proto::LSProblem< dim >::LSProblem(), and Proto::LSProblem< dim >::setMatrix().
m_locMonoP
template<int dim> LocPthMoment Proto::LSProblem< dim >::m_locMonoP
Referenced by Proto::LSProblem< dim >::getLocMonomialMapDegreeP(), and Proto::LSProblem< dim >::LSProblem().
m_numP
template<int dim> int Proto::LSProblem< dim >::m_numP
Referenced by Proto::LSProblem< dim >::getNumberDegP(), Proto::LSProblem< dim >::invertNormalEq(), Proto::LSProblem< dim >::LSProblem(), Proto::LSProblem< dim >::setMatrix(), and Proto::LSProblem< 1 >::setNumMonomials().
m_monoLocPLess1
template<int dim> PthMomentLoc Proto::LSProblem< dim >::m_monoLocPLess1
Referenced by Proto::LSProblem< dim >::getMonomialLocMapDegreePLess1(), Proto::LSProblem< dim >::LSProblem(), and Proto::LSProblem< dim >::setMatrix().
m_locMonoPLess1
template<int dim> LocPthMoment Proto::LSProblem< dim >::m_locMonoPLess1
Referenced by Proto::LSProblem< dim >::LSProblem().
m_numPLess1
template<int dim> int Proto::LSProblem< dim >::m_numPLess1
Referenced by Proto::LSProblem< dim >::getNumberDegPLess1(), Proto::LSProblem< dim >::invertNormalEq(), Proto::LSProblem< dim >::LSProblem(), Proto::LSProblem< dim >::setMatrix(), and Proto::LSProblem< 1 >::setNumMonomials().
m_matrix
template<int dim> double** Proto::LSProblem< dim >::m_matrix
Referenced by Proto::LSProblem< dim >::invertNormalEq(), Proto::LSProblem< dim >::LSProblem(), and Proto::LSProblem< dim >::setMatrix().
m_unknowns
template<int dim> vector<double> Proto::LSProblem< dim >::m_unknowns
Referenced by Proto::LSProblem< dim >::getUnknown(), Proto::LSProblem< dim >::invertNormalEq(), and Proto::LSProblem< dim >::LSProblem().
m_rhs
template<int dim> vector<double> Proto::LSProblem< dim >::m_rhs
Referenced by Proto::LSProblem< dim >::invertNormalEq(), and Proto::LSProblem< dim >::LSProblem().
m_lowerBound
template<int dim> vector<double> Proto::LSProblem< dim >::m_lowerBound
Referenced by Proto::LSProblem< dim >::LSProblem().
m_upperBound
template<int dim> vector<double> Proto::LSProblem< dim >::m_upperBound
Referenced by Proto::LSProblem< dim >::LSProblem().
The documentation for this class was generated from the following files:
Proto_LSProblem.H
Proto_LSProblemImplem.H