Chombo_4: GeometryService< order > Class Template Reference
GeometryService< order > Class Template Reference
#include <Chombo_GeometryService.H>
Public Types
typedef IndexedMoments< DIM, order > IndMomDIM
typedef IndexedMoments< DIM-1, order > IndMomSDMinOne
typedef MomentIterator< DIM, order > MomItDIM
typedef MomentIterator< DIM-1, order > MomItSDMinOne
typedef IrregNode< order > inode
typedef HostIrregData< CELL, IndMomDIM, 1 > VoluData
typedef HostIrregData< BOUNDARY, IndMomDIM, 1 > EBFaData
typedef HostIrregData< XFACE, IndMomSDMinOne, 1 > XFacData
typedef HostIrregData< YFACE, IndMomSDMinOne, 1 > YFacData
typedef HostIrregData< ZFACE, IndMomSDMinOne, 1 > ZFacData
typedef HostIrregData< CELL, IndMomDIM, 1 > EBNormalData
typedef CH4_Data_Choreography::DistributedData< EBGraph > graph_distrib_t
typedef CH4_Data_Choreography::DistributedData< VoluData > volu_distrib_t
typedef CH4_Data_Choreography::DistributedData< EBFaData > ebfa_distrib_t
typedef CH4_Data_Choreography::DistributedData< XFacData > xfac_distrib_t
typedef CH4_Data_Choreography::DistributedData< YFacData > yfac_distrib_t
typedef CH4_Data_Choreography::DistributedData< ZFacData > zfac_distrib_t
typedef CH4_Data_Choreography::DistributedData< EBNormalData > ebnorm_distrib_t
Public Member Functions
GeometryService (const shared_ptr< BaseIF > &a_baseIF, const RealVect &a_origin, const double &a_finestDx, const Box &a_finestDomain, const std::vector< DisjointBoxLayout > &a_grids, const int &a_ghost, bool a_printStuff=false)
GeometryService (const shared_ptr< BaseIF > &a_baseIF, const RealVect &a_origin, const double &a_dx, const Box &a_finestDomain, const DisjointBoxLayout &a_grids, const int &a_ghost)
shared_ptr< graph_distrib_t > getGraphs (const Box &a_domain)
shared_ptr< volu_distrib_t > getVoluData (const Box &a_domain)
void fillKappa (EBHostData< CELL, Real, 1 > &a_kappa, const Box &a_grid, const DataIndex &a_dit, const Box &a_domain) const
fill a data holder in with volume fractions
void fillEBFaceData (EBHostData< CELL, Real, 1 > &a_ebfdata, const Box &a_grid, const DataIndex &a_dit, const Box &a_domain) const
fill a data holder in with eb face data
void fillEBFaceAlpha (EBHostData< CELL, Real, 1 > &a_ebfdata, const Box &a_grid, const DataIndex &a_dit, const Box &a_domain) const
fill a data holder in with eb face area fractions
shared_ptr< ebfa_distrib_t > getEBFaceData (const Box &a_domain)
shared_ptr< xfac_distrib_t > getXFaceData (const Box &a_domain)
shared_ptr< yfac_distrib_t > getYFaceData (const Box &a_domain)
shared_ptr< zfac_distrib_t > getZFaceData (const Box &a_domain)
shared_ptr< ebnorm_distrib_t > getEBNormalData_x (const Box &a_domain)
Get eb moment in the x direction.
shared_ptr< ebnorm_distrib_t > getEBNormalData_y (const Box &a_domain)
Get eb moment in the y direction.
shared_ptr< ebnorm_distrib_t > getEBNormalData_z (const Box &a_domain)
Get eb moment in the z direction.
DisjointBoxLayout getDBL (const Box &a_domain)
shared_ptr< LevelGeometryService< order > > operator[] (const Box &a_domain)
const shared_ptr< LevelGeometryService< order > > operator[] (const Box &a_domain) const
bool hasLevel (const Box &a_domain) const
Static Public Member Functions
static void generateGrids (std::vector< DisjointBoxLayout > &a_grids, const Box &a_domain, int a_maxGridSize=32, int a_maxCoarsen=-1)
Protected Attributes
vector< Box > m_domains
vector< shared_ptr< LevelGeometryService< order > > > m_levels
Private Member Functions
int getLevel (const Box &a_domain) const
GeometryService ()
GeometryService (const GeometryService &a_workshopin)
void operator= (const GeometryService &a_workshopin)
Detailed Description
template<int order>
class GeometryService< order >
makes geometric description from an implicit function.
Member Typedef Documentation
IndMomDIM
template<int order> typedef IndexedMoments<DIM , order> GeometryService< order >::IndMomDIM
IndMomSDMinOne
template<int order> typedef IndexedMoments<DIM-1, order> GeometryService< order >::IndMomSDMinOne
MomItDIM
template<int order> typedef MomentIterator<DIM , order> GeometryService< order >::MomItDIM
MomItSDMinOne
template<int order> typedef MomentIterator<DIM-1, order> GeometryService< order >::MomItSDMinOne
inode
template<int order> typedef IrregNode<order> GeometryService< order >::inode
VoluData
template<int order> typedef HostIrregData<CELL, IndMomDIM, 1> GeometryService< order >::VoluData
EBFaData
template<int order> typedef HostIrregData<BOUNDARY, IndMomDIM, 1> GeometryService< order >::EBFaData
XFacData
template<int order> typedef HostIrregData<XFACE, IndMomSDMinOne, 1> GeometryService< order >::XFacData
YFacData
template<int order> typedef HostIrregData<YFACE, IndMomSDMinOne, 1> GeometryService< order >::YFacData
ZFacData
template<int order> typedef HostIrregData<ZFACE, IndMomSDMinOne, 1> GeometryService< order >::ZFacData
EBNormalData
template<int order> typedef HostIrregData<CELL, IndMomDIM, 1> GeometryService< order >::EBNormalData
graph_distrib_t
template<int order> typedef CH4_Data_Choreography::DistributedData<EBGraph> GeometryService< order >::graph_distrib_t
volu_distrib_t
template<int order> typedef CH4_Data_Choreography::DistributedData<VoluData> GeometryService< order >::volu_distrib_t
ebfa_distrib_t
template<int order> typedef CH4_Data_Choreography::DistributedData<EBFaData> GeometryService< order >::ebfa_distrib_t
xfac_distrib_t
template<int order> typedef CH4_Data_Choreography::DistributedData<XFacData> GeometryService< order >::xfac_distrib_t
yfac_distrib_t
template<int order> typedef CH4_Data_Choreography::DistributedData<YFacData> GeometryService< order >::yfac_distrib_t
zfac_distrib_t
template<int order> typedef CH4_Data_Choreography::DistributedData<ZFacData> GeometryService< order >::zfac_distrib_t
ebnorm_distrib_t
template<int order> typedef CH4_Data_Choreography::DistributedData<EBNormalData> GeometryService< order >::ebnorm_distrib_t
Constructor & Destructor Documentation
GeometryService() [1/4]
template<int order> GeometryService< order >::GeometryService (const shared_ptr< BaseIF > & a_baseIF, const RealVect & a_origin, const double & a_finestDx, const Box & a_finestDomain, const std::vector< DisjointBoxLayout > & a_grids, const int & a_ghost, bool a_printStuff = false) inline
basif : implicit function origin : location of the lower left corner of the domain dx : grid spacing domain : finest domain in the calculation finestGrids: layout of the finest domain ghost : maximum number of ghost cells needed in calculation
References coarsen(), and pout().
GeometryService() [2/4]
template<int order> GeometryService< order >::GeometryService (const shared_ptr< BaseIF > & a_baseIF, const RealVect & a_origin, const double & a_dx, const Box & a_finestDomain, const DisjointBoxLayout & a_grids, const int & a_ghost) inline
single level define. basif : implicit function origin : location of the lower left corner of the domain dx : grid spacing domain : finest domain in the calculation finestGrids: layout of the finest domain ghost : maximum number of ghost cells needed in calculation
GeometryService() [3/4]
template<int order> GeometryService< order >::GeometryService () private
GeometryService() [4/4]
template<int order> GeometryService< order >::GeometryService (const GeometryService< order > & a_workshopin) private
Member Function Documentation
generateGrids()
template<int order> static void GeometryService< order >::generateGrids (std::vector< DisjointBoxLayout > & a_grids, const Box & a_domain, int a_maxGridSize = 32, int a_maxCoarsen = -1) inline static
make vector of grids that cover the domain at various coarsenings This coarsens grids if it can, rebuilds them if it has to for coarser grids maxGridSize: maximum size of boxes on coarser grids maxCoarsen : maximum times the service coarsens (-1 means coarsen down to 2x2)
References coarsen(), Box::coarsenable(), domainSplit(), LoadBalance(), and ParmParse::query().
Referenced by EBCM::Algorithm_Framework< ebcm_order >::makeMergedGeometry().
getGraphs()
template<int order> shared_ptr<graph_distrib_t> GeometryService< order >::getGraphs (const Box & a_domain) inline
getVoluData()
template<int order> shared_ptr<volu_distrib_t > GeometryService< order >::getVoluData (const Box & a_domain) inline
fillKappa()
template<int order> void GeometryService< order >::fillKappa (EBHostData< CELL, Real, 1 > & a_kappa, const Box & a_grid, const DataIndex & a_dit, const Box & a_domain) const inline
fill a data holder in with volume fractions
fillEBFaceData()
template<int order> void GeometryService< order >::fillEBFaceData (EBHostData< CELL, Real, 1 > & a_ebfdata, const Box & a_grid, const DataIndex & a_dit, const Box & a_domain) const inline
fill a data holder in with eb face data
fillEBFaceAlpha()
template<int order> void GeometryService< order >::fillEBFaceAlpha (EBHostData< CELL, Real, 1 > & a_ebfdata, const Box & a_grid, const DataIndex & a_dit, const Box & a_domain) const inline
fill a data holder in with eb face area fractions
getEBFaceData()
template<int order> shared_ptr<ebfa_distrib_t > GeometryService< order >::getEBFaceData (const Box & a_domain) inline
getXFaceData()
template<int order> shared_ptr<xfac_distrib_t > GeometryService< order >::getXFaceData (const Box & a_domain) inline
getYFaceData()
template<int order> shared_ptr<yfac_distrib_t > GeometryService< order >::getYFaceData (const Box & a_domain) inline
getZFaceData()
template<int order> shared_ptr<zfac_distrib_t> GeometryService< order >::getZFaceData (const Box & a_domain) inline
getEBNormalData_x()
template<int order> shared_ptr<ebnorm_distrib_t > GeometryService< order >::getEBNormalData_x (const Box & a_domain) inline
Get eb moment in the x direction.
getEBNormalData_y()
template<int order> shared_ptr<ebnorm_distrib_t > GeometryService< order >::getEBNormalData_y (const Box & a_domain) inline
Get eb moment in the y direction.
getEBNormalData_z()
template<int order> shared_ptr<ebnorm_distrib_t > GeometryService< order >::getEBNormalData_z (const Box & a_domain) inline
Get eb moment in the z direction.
getDBL()
template<int order> DisjointBoxLayout GeometryService< order >::getDBL (const Box & a_domain) inline
operator[]() [1/2]
template<int order> shared_ptr<LevelGeometryService<order> > GeometryService< order >::operator[] (const Box & a_domain) inline
operator[]() [2/2]
template<int order> const shared_ptr<LevelGeometryService<order> > GeometryService< order >::operator[] (const Box & a_domain) const inline
hasLevel()
template<int order> bool GeometryService< order >::hasLevel (const Box & a_domain) const inline
getLevel()
template<int order> int GeometryService< order >::getLevel (const Box & a_domain) const inline private
References MayDay::Error().
operator=()
template<int order> void GeometryService< order >::operator= (const GeometryService< order > & a_workshopin) private
Member Data Documentation
m_domains
template<int order> vector<Box> GeometryService< order >::m_domains protected
m_levels
template<int order> vector<shared_ptr<LevelGeometryService<order> > > GeometryService< order >::m_levels protected
The documentation for this class was generated from the following file:
Chombo_GeometryService.H