Chombo_4: Proto::HostIrregData< cent, data_t, ncomp > Class Template Reference
Proto::HostIrregData< cent, data_t, ncomp > Class Template Reference
#include <Proto_HostIrregData.H>
Public Member Functions
HostIrregData ()
virtual ~HostIrregData ()
int nComp () const
to conform with mpi stuff
HostIrregData (const Box &a_box, bool a_stackAllocation=true)
needed for leveldata
std::size_t size () const
bool defined () const
data_t * dataPtr (unsigned int a_ivar=0)
const data_t * dataPtr (unsigned int a_ivar=0) const
data_t * data ()
const data_t * data () const
size_t index (const EBIndex< cent > &a_vof, const int &a_ivar) const
data_t & operator() (const EBIndex< cent > &a_vof, int a_comp)
const data_t & operator() (const EBIndex< cent > &a_vof, int a_comp) const
unsigned int vecsize () const
sometimes useful for debugging
template<unsigned int srccomp>
void define (HostIrregData< cent, data_t, srccomp > &a_input, unsigned int &a_comp)
template<unsigned int srccomp>
void define (IrregData< cent, data_t, srccomp > &a_input)
Box inputBox () const
shared_ptr< vector< EBIndex< cent > > > getIndicies () const
shared_ptr< data_t > getData () const
void define (const Box &a_box, const EBGraph &a_graph)
bool contains (const EBIndex< cent > &a_index) const
void setVal (data_t val)
bool copyContains (const EBIndex< cent > &a_ind, const Box &a_srcbox) const
vector< EBIndex< cent > > getIndiciesInBox (const Box &a_bx) const
std::size_t charsize (const Box &a_bx, unsigned int a_startcomp, unsigned int a_numcomps, bool a_printStuff=false) const
this DOES include sizeof(T)
void energize (void *a_buf, size_t a_expectedCharSize, bool a_printStuff=false) const
recreates this object into a stream of bytes
HostIrregData (void *a_buf, size_t a_expectedCharSize, bool a_printStuff=false)
creates this object from the aforementioned stream of bytes
void linearOut (void *a_buf, size_t a_expectedCharSize, const Box &a_bx, unsigned int a_startcomp, unsigned int a_numcomps, bool a_printStuff=false) const
void linearIn (void *a_buf, size_t a_expectedCharSize, const Box &a_bx, unsigned int a_startcomp, unsigned int a_numcomps, bool a_printStuff=false)
void copy (const HostIrregData< cent, data_t, ncomp > &a_src, const Box &a_bxFrom, unsigned int a_isrc, const Box &a_bxTo, unsigned int a_idst, unsigned int a_inco, bool a_printStuff=false)
void define (const Box &a_box, const shared_ptr< vector< EBIndex< cent > > > &a_indicies)
Static Public Member Functions
static int preAllocatable ()
static int memTypeAllocation ()
Protected Member Functions
void define (const shared_ptr< vector< EBIndex< cent > > > &a_indexVec)
void fillSetFromVector ()
HostIrregData (const HostIrregData< cent, data_t, ncomp > &a_src)
insert usual reasons here
HostIrregData & operator= (const HostIrregData< cent, data_t, ncomp > &a_src)
Protected Attributes
Box m_inputBox
std::shared_ptr< std::vector< EBIndex< cent > > > m_indexVec
std::shared_ptr< std::set< EBIndex< cent > > > m_indexSet
std::shared_ptr< data_t > m_data
data_t * m_rawPtr
Constructor & Destructor Documentation
HostIrregData() [1/4]
template<CENTERING cent, class data_t, unsigned int ncomp> Proto::HostIrregData< cent, data_t, ncomp >::HostIrregData () inline
~HostIrregData()
template<CENTERING cent, class data_t, unsigned int ncomp> virtual Proto::HostIrregData< cent, data_t, ncomp >::~HostIrregData () inline virtual
HostIrregData() [2/4]
template<CENTERING cent, class data_t, unsigned int ncomp> Proto::HostIrregData< cent, data_t, ncomp >::HostIrregData (const Box & a_box, bool a_stackAllocation = true) inline
needed for leveldata
HostIrregData() [3/4]
template<CENTERING cent, class data_t, unsigned int ncomp> Proto::HostIrregData< cent, data_t, ncomp >::HostIrregData (void * a_buf, size_t a_expectedCharSize, bool a_printStuff = false) inline
creates this object from the aforementioned stream of bytes
References Proto::HostIrregData< cent, data_t, ncomp >::data(), Proto::HostIrregData< cent, data_t, ncomp >::define(), Proto::HostIrregData< cent, data_t, ncomp >::index(), ProtoSer::linearCharBufSize(), ProtoSer::linearInFromCharBuf(), Proto::HostIrregData< cent, data_t, ncomp >::m_inputBox, Proto::HostIrregData< cent, data_t, ncomp >::m_rawPtr, pout(), and Proto::HostIrregData< cent, data_t, ncomp >::vecsize().
HostIrregData() [4/4]
template<CENTERING cent, class data_t, unsigned int ncomp> Proto::HostIrregData< cent, data_t, ncomp >::HostIrregData (const HostIrregData< cent, data_t, ncomp > & a_src) protected
insert usual reasons here
Member Function Documentation
nComp()
template<CENTERING cent, class data_t, unsigned int ncomp> int Proto::HostIrregData< cent, data_t, ncomp >::nComp () const inline
to conform with mpi stuff
size()
template<CENTERING cent, class data_t, unsigned int ncomp> std::size_t Proto::HostIrregData< cent, data_t, ncomp >::size () const inline
References Proto::HostIrregData< cent, data_t, ncomp >::m_indexVec.
Referenced by Proto::HostIrregData< cent, data_t, ncomp >::define(), and Proto::HostIrregData< cent, data_t, ncomp >::index().
defined()
template<CENTERING cent, class data_t, unsigned int ncomp> bool Proto::HostIrregData< cent, data_t, ncomp >::defined () const inline
References Proto::HostIrregData< cent, data_t, ncomp >::m_data.
dataPtr() [1/2]
template<CENTERING cent, class data_t, unsigned int ncomp> data_t* Proto::HostIrregData< cent, data_t, ncomp >::dataPtr (unsigned int a_ivar = 0) inline
References Proto::HostIrregData< cent, data_t, ncomp >::m_indexVec, and Proto::HostIrregData< cent, data_t, ncomp >::m_rawPtr.
Referenced by Proto::HostIrregData< cent, data_t, ncomp >::define().
dataPtr() [2/2]
template<CENTERING cent, class data_t, unsigned int ncomp> const data_t* Proto::HostIrregData< cent, data_t, ncomp >::dataPtr (unsigned int a_ivar = 0) const inline
References Proto::HostIrregData< cent, data_t, ncomp >::m_indexVec, and Proto::HostIrregData< cent, data_t, ncomp >::m_rawPtr.
data() [1/2]
template<CENTERING cent, class data_t, unsigned int ncomp> data_t* Proto::HostIrregData< cent, data_t, ncomp >::data () inline
References Proto::HostIrregData< cent, data_t, ncomp >::m_rawPtr.
Referenced by Proto::HostIrregData< cent, data_t, ncomp >::charsize(), Proto::HostIrregData< cent, data_t, ncomp >::energize(), and Proto::HostIrregData< cent, data_t, ncomp >::HostIrregData().
data() [2/2]
template<CENTERING cent, class data_t, unsigned int ncomp> const data_t* Proto::HostIrregData< cent, data_t, ncomp >::data () const inline
References Proto::HostIrregData< cent, data_t, ncomp >::m_rawPtr.
index()
template<CENTERING cent, class data_t, unsigned int ncomp> size_t Proto::HostIrregData< cent, data_t, ncomp >::index (const EBIndex< cent > & a_vof, const int & a_ivar) const inline
References Proto::HostIrregData< cent, data_t, ncomp >::m_indexVec, and Proto::HostIrregData< cent, data_t, ncomp >::size().
Referenced by Proto::HostIrregData< cent, data_t, ncomp >::HostIrregData(), and Proto::HostIrregData< cent, data_t, ncomp >::operator()().
operator()() [1/2]
template<CENTERING cent, class data_t, unsigned int ncomp> data_t& Proto::HostIrregData< cent, data_t, ncomp >::operator() (const EBIndex< cent > & a_vof, int a_comp) inline
References Proto::HostIrregData< cent, data_t, ncomp >::index(), and Proto::HostIrregData< cent, data_t, ncomp >::m_rawPtr.
operator()() [2/2]
template<CENTERING cent, class data_t, unsigned int ncomp> const data_t& Proto::HostIrregData< cent, data_t, ncomp >::operator() (const EBIndex< cent > & a_vof, int a_comp) const inline
References Proto::HostIrregData< cent, data_t, ncomp >::index(), and Proto::HostIrregData< cent, data_t, ncomp >::m_rawPtr.
vecsize()
template<CENTERING cent, class data_t, unsigned int ncomp> unsigned int Proto::HostIrregData< cent, data_t, ncomp >::vecsize () const inline
sometimes useful for debugging
References Proto::HostIrregData< cent, data_t, ncomp >::m_indexVec.
Referenced by Proto::HostIrregData< cent, data_t, ncomp >::energize(), and Proto::HostIrregData< cent, data_t, ncomp >::HostIrregData().
define() [1/5]
template<CENTERING cent, class data_t, unsigned int ncomp> template<unsigned int srccomp> void Proto::HostIrregData< cent, data_t, ncomp >::define (HostIrregData< cent, data_t, srccomp > & a_input, unsigned int & a_comp) inline
References Proto::HostIrregData< cent, data_t, ncomp >::dataPtr(), Proto::HostIrregData< cent, data_t, ncomp >::getData(), Proto::HostIrregData< cent, data_t, ncomp >::getIndicies(), Proto::HostIrregData< cent, data_t, ncomp >::inputBox(), Proto::HostIrregData< cent, data_t, ncomp >::m_data, Proto::HostIrregData< cent, data_t, ncomp >::m_indexSet, Proto::HostIrregData< cent, data_t, ncomp >::m_indexVec, Proto::HostIrregData< cent, data_t, ncomp >::m_inputBox, and Proto::HostIrregData< cent, data_t, ncomp >::m_rawPtr.
Referenced by Proto::HostIrregData< cent, data_t, ncomp >::define(), and Proto::HostIrregData< cent, data_t, ncomp >::HostIrregData().
define() [2/5]
template<CENTERING cent, class data_t, unsigned int ncomp> template<unsigned int srccomp> void Proto::HostIrregData< cent, data_t, ncomp >::define (IrregData< cent, data_t, srccomp > & a_input) inline
References Proto::IrregData< cent, data_t, ncomp >::dataPtr(), Proto::HostIrregData< cent, data_t, ncomp >::fillSetFromVector(), Proto::IrregData< cent, data_t, ncomp >::getData(), Proto::IrregData< cent, data_t, ncomp >::getIndicies(), Proto::IrregData< cent, data_t, ncomp >::inputBox(), Proto::HostIrregData< cent, data_t, ncomp >::m_data, Proto::HostIrregData< cent, data_t, ncomp >::m_indexVec, Proto::HostIrregData< cent, data_t, ncomp >::m_inputBox, and Proto::HostIrregData< cent, data_t, ncomp >::m_rawPtr.
inputBox()
template<CENTERING cent, class data_t, unsigned int ncomp> Box Proto::HostIrregData< cent, data_t, ncomp >::inputBox () const inline
References Proto::HostIrregData< cent, data_t, ncomp >::m_inputBox.
Referenced by Proto::HostIrregData< cent, data_t, ncomp >::define().
getIndicies()
template<CENTERING cent, class data_t, unsigned int ncomp> shared_ptr<vector< EBIndex<cent> > > Proto::HostIrregData< cent, data_t, ncomp >::getIndicies () const inline
References Proto::HostIrregData< cent, data_t, ncomp >::m_indexVec.
Referenced by Proto::HostIrregData< cent, data_t, ncomp >::define().
getData()
template<CENTERING cent, class data_t, unsigned int ncomp> shared_ptr<data_t> Proto::HostIrregData< cent, data_t, ncomp >::getData () const inline
References Proto::HostIrregData< cent, data_t, ncomp >::m_data.
Referenced by Proto::HostIrregData< cent, data_t, ncomp >::define().
define() [3/5]
template<CENTERING cent, class data_t, unsigned int ncomp> void Proto::HostIrregData< cent, data_t, ncomp >::define (const Box & a_box, const EBGraph & a_graph) inline
References Proto::HostIrregData< cent, data_t, ncomp >::define(), Proto::EBGraph::getDomain(), and Proto::HostIrregData< cent, data_t, ncomp >::m_inputBox.
contains()
template<CENTERING cent, class data_t, unsigned int ncomp> bool Proto::HostIrregData< cent, data_t, ncomp >::contains (const EBIndex< cent > & a_index) const inline
References Proto::HostIrregData< cent, data_t, ncomp >::m_indexSet.
Referenced by Proto::HostIrregData< cent, data_t, ncomp >::copyContains(), and Proto::EBStencilArchive< CELL, CELL, order, double >::getRestrictionStencil().
setVal()
template<CENTERING cent, class data_t, unsigned int ncomp> void Proto::HostIrregData< cent, data_t, ncomp >::setVal (data_t val) inline
References Proto::HostIrregData< cent, data_t, ncomp >::m_indexVec.
copyContains()
template<CENTERING cent, class data_t, unsigned int ncomp> bool Proto::HostIrregData< cent, data_t, ncomp >::copyContains (const EBIndex< cent > & a_ind, const Box & a_srcbox) const inline
References Proto::BOUNDARY, Proto::CELL, Proto::HostIrregData< cent, data_t, ncomp >::contains(), Box::contains(), Proto::EBIndex< cent >::m_pt, Proto::XFACE, Proto::YFACE, and Proto::ZFACE.
Referenced by Proto::HostIrregData< cent, data_t, ncomp >::copy(), and Proto::HostIrregData< cent, data_t, ncomp >::getIndiciesInBox().
getIndiciesInBox()
template<CENTERING cent, class data_t, unsigned int ncomp> vector<EBIndex<cent> > Proto::HostIrregData< cent, data_t, ncomp >::getIndiciesInBox (const Box & a_bx) const inline
References Proto::HostIrregData< cent, data_t, ncomp >::copyContains(), and Proto::HostIrregData< cent, data_t, ncomp >::m_indexVec.
charsize()
template<CENTERING cent, class data_t, unsigned int ncomp> std::size_t Proto::HostIrregData< cent, data_t, ncomp >::charsize (const Box & a_bx, unsigned int a_startcomp, unsigned int a_numcomps, bool a_printStuff = false) const inline
this DOES include sizeof(T)
References Proto::HostIrregData< cent, data_t, ncomp >::data(), ProtoSer::linearCharBufSize(), Proto::HostIrregData< cent, data_t, ncomp >::m_indexVec, Proto::HostIrregData< cent, data_t, ncomp >::m_inputBox, and pout().
energize()
template<CENTERING cent, class data_t, unsigned int ncomp> void Proto::HostIrregData< cent, data_t, ncomp >::energize (void * a_buf, size_t a_expectedCharSize, bool a_printStuff = false) const inline
recreates this object into a stream of bytes
References Proto::HostIrregData< cent, data_t, ncomp >::data(), ProtoSer::linearCharBufSize(), ProtoSer::linearOutToCharBuf(), Proto::HostIrregData< cent, data_t, ncomp >::m_indexVec, Proto::HostIrregData< cent, data_t, ncomp >::m_inputBox, pout(), and Proto::HostIrregData< cent, data_t, ncomp >::vecsize().
Referenced by Proto::HostIrregData< cent, data_t, ncomp >::linearOut().
linearOut()
template<CENTERING cent, class data_t, unsigned int ncomp> void Proto::HostIrregData< cent, data_t, ncomp >::linearOut (void * a_buf, size_t a_expectedCharSize, const Box & a_bx, unsigned int a_startcomp, unsigned int a_numcomps, bool a_printStuff = false) const inline
References Proto::HostIrregData< cent, data_t, ncomp >::energize().
linearIn()
template<CENTERING cent, class data_t, unsigned int ncomp> void Proto::HostIrregData< cent, data_t, ncomp >::linearIn (void * a_buf, size_t a_expectedCharSize, const Box & a_bx, unsigned int a_startcomp, unsigned int a_numcomps, bool a_printStuff = false) inline
References Proto::HostIrregData< cent, data_t, ncomp >::copy().
preAllocatable()
template<CENTERING cent, class data_t, unsigned int ncomp> static int Proto::HostIrregData< cent, data_t, ncomp >::preAllocatable () inline static
memTypeAllocation()
template<CENTERING cent, class data_t, unsigned int ncomp> static int Proto::HostIrregData< cent, data_t, ncomp >::memTypeAllocation () inline static
copy()
template<CENTERING cent, class data_t, unsigned int ncomp> void Proto::HostIrregData< cent, data_t, ncomp >::copy (const HostIrregData< cent, data_t, ncomp > & a_src, const Box & a_bxFrom, unsigned int a_isrc, const Box & a_bxTo, unsigned int a_idst, unsigned int a_inco, bool a_printStuff = false) inline
References Box::contains(), Proto::HostIrregData< cent, data_t, ncomp >::copyContains(), and Proto::HostIrregData< cent, data_t, ncomp >::m_indexVec.
Referenced by Proto::HostIrregData< cent, data_t, ncomp >::linearIn().
define() [4/5]
template<CENTERING cent, class data_t, unsigned int ncomp> void Proto::HostIrregData< cent, data_t, ncomp >::define (const Box & a_box, const shared_ptr< vector< EBIndex< cent > > > & a_indicies) inline
References Proto::HostIrregData< cent, data_t, ncomp >::define(), and Proto::HostIrregData< cent, data_t, ncomp >::m_inputBox.
define() [5/5]
template<CENTERING cent, class data_t, unsigned int ncomp> void Proto::HostIrregData< cent, data_t, ncomp >::define (const shared_ptr< vector< EBIndex< cent > > > & a_indexVec) inline protected
References Proto::HostIrregData< cent, data_t, ncomp >::fillSetFromVector(), Proto::HostIrregData< cent, data_t, ncomp >::m_data, Proto::HostIrregData< cent, data_t, ncomp >::m_indexVec, Proto::HostIrregData< cent, data_t, ncomp >::m_rawPtr, and Proto::HostIrregData< cent, data_t, ncomp >::size().
fillSetFromVector()
template<CENTERING cent, class data_t, unsigned int ncomp> void Proto::HostIrregData< cent, data_t, ncomp >::fillSetFromVector () inline protected
References Proto::HostIrregData< cent, data_t, ncomp >::m_indexSet, and Proto::HostIrregData< cent, data_t, ncomp >::m_indexVec.
Referenced by Proto::HostIrregData< cent, data_t, ncomp >::define().
operator=()
template<CENTERING cent, class data_t, unsigned int ncomp> HostIrregData& Proto::HostIrregData< cent, data_t, ncomp >::operator= (const HostIrregData< cent, data_t, ncomp > & a_src) protected
Member Data Documentation
m_inputBox
template<CENTERING cent, class data_t, unsigned int ncomp> Box Proto::HostIrregData< cent, data_t, ncomp >::m_inputBox protected
Referenced by Proto::HostIrregData< cent, data_t, ncomp >::charsize(), Proto::HostIrregData< cent, data_t, ncomp >::define(), Proto::HostIrregData< cent, data_t, ncomp >::energize(), Proto::HostIrregData< cent, data_t, ncomp >::HostIrregData(), and Proto::HostIrregData< cent, data_t, ncomp >::inputBox().
m_indexVec
template<CENTERING cent, class data_t, unsigned int ncomp> std::shared_ptr<std::vector< EBIndex<cent> > > Proto::HostIrregData< cent, data_t, ncomp >::m_indexVec protected
Referenced by Proto::HostIrregData< cent, data_t, ncomp >::charsize(), Proto::HostIrregData< cent, data_t, ncomp >::copy(), Proto::HostIrregData< cent, data_t, ncomp >::dataPtr(), Proto::HostIrregData< cent, data_t, ncomp >::define(), Proto::HostIrregData< cent, data_t, ncomp >::energize(), Proto::HostIrregData< cent, data_t, ncomp >::fillSetFromVector(), Proto::HostIrregData< cent, data_t, ncomp >::getIndicies(), Proto::HostIrregData< cent, data_t, ncomp >::getIndiciesInBox(), Proto::HostIrregData< cent, data_t, ncomp >::index(), Proto::HostIrregData< cent, data_t, ncomp >::setVal(), Proto::HostIrregData< cent, data_t, ncomp >::size(), and Proto::HostIrregData< cent, data_t, ncomp >::vecsize().
m_indexSet
template<CENTERING cent, class data_t, unsigned int ncomp> std::shared_ptr<std::set< EBIndex<cent> > > Proto::HostIrregData< cent, data_t, ncomp >::m_indexSet protected
Referenced by Proto::HostIrregData< cent, data_t, ncomp >::contains(), Proto::HostIrregData< cent, data_t, ncomp >::define(), and Proto::HostIrregData< cent, data_t, ncomp >::fillSetFromVector().
m_data
template<CENTERING cent, class data_t, unsigned int ncomp> std::shared_ptr<data_t> Proto::HostIrregData< cent, data_t, ncomp >::m_data protected
Referenced by Proto::HostIrregData< cent, data_t, ncomp >::define(), Proto::HostIrregData< cent, data_t, ncomp >::defined(), and Proto::HostIrregData< cent, data_t, ncomp >::getData().
m_rawPtr
template<CENTERING cent, class data_t, unsigned int ncomp> data_t* Proto::HostIrregData< cent, data_t, ncomp >::m_rawPtr protected
Referenced by Proto::HostIrregData< cent, data_t, ncomp >::data(), Proto::HostIrregData< cent, data_t, ncomp >::dataPtr(), Proto::HostIrregData< cent, data_t, ncomp >::define(), Proto::HostIrregData< cent, data_t, ncomp >::HostIrregData(), and Proto::HostIrregData< cent, data_t, ncomp >::operator()().
The documentation for this class was generated from the following file:
Proto_HostIrregData.H