Chombo_4: Vector< T > Class Template Reference
Vector< T > Class Template Reference
one dimensional dynamic array
#include <Vector.H>
Public Member Functions
Vector ()
virtual ~Vector ()
Vector (const Vector< T > &invec)
Vector (Vector< T > &&a_invec) noexcept
Vector (const std::vector< T > &invec)
Vector< T > & operator= (const std::vector< T > &invec)
Vector< T > & operator= (Vector< T > &&a_invec)
Vector< T > & operator= (const Vector< T > &invec)
Vector< T > & assign (const T &inval)
assign a scalar to every element of the vector
Vector (unsigned int isize)
void clear ()
size_t size () const
Vector (unsigned int isize, const T &value)
T & operator[] (unsigned int n)
const T & operator[] (unsigned int n) const
T & front ()
T & back ()
void pop_back ()
const T & back () const
void swap (Vector< T > &other)
void push_back (const T &in)
void push_back (T &&in)
void append (const Vector< T > &invec)
void resize (unsigned int isize)
void reserve (size_t isize)
size_t capacity () const
void resize (unsigned int isize, const T &value)
void sort ()
std::vector< T > & stdVector ()
Returns std::vector under the hood.
const std::vector< T > & constStdVector () const
Private Member Functions
unsigned int initFunc ()
Private Attributes
std::vector< T > v
Detailed Description
template<class T>
class Vector< T >
one dimensional dynamic array
Vector is a resizable one-dimensional array with constant-time random access and range checking. The template type T must have a default constructor, a copy constructor, and an assignment operator.
Constructor & Destructor Documentation
Vector() [1/6]
template<class T> Vector< T >::Vector () inline
Default constructor. Creates a Vector of zero length with null data.
~Vector()
template<class T> virtual Vector< T >::~Vector () inline virtual
Destructor.
References Vector< T >::size().
Vector() [2/6]
template<class T> Vector< T >::Vector (const Vector< T > & invec) inline
Copy constructor.
References Vector< T >::size().
Vector() [3/6]
template<class T> Vector< T >::Vector (Vector< T > && a_invec) inline noexcept
Vector() [4/6]
template<class T> Vector< T >::Vector (const std::vector< T > & invec) inline
conversion constructor
Vector() [5/6]
template<class T> Vector< T >::Vector (unsigned int isize) inline
Constructs a Vector with given number of elements.\
{ Arguments:}\ size (not modified): number of elements of Vector to construct.\ { This:}\ ----—The object is modified-------—
References Vector< T >::resize().
Vector() [6/6]
template<class T> Vector< T >::Vector (unsigned int isize, const T & value) inline
Constructs a Vector with given number of elements and constant value.\
{ Arguments:}\ size (not modified): number of elements of Vector to construct.\ value (not modified): value to set every element to.\ { This:}\ ----—The object is modified-------—
Member Function Documentation
operator=() [1/3]
template<class T> Vector<T>& Vector< T >::operator= (const std::vector< T > & invec) inline
References Vector< T >::size(), and Vector< T >::v.
operator=() [2/3]
template<class T> Vector<T>& Vector< T >::operator= (Vector< T > && a_invec) inline
References Vector< T >::v.
operator=() [3/3]
template<class T> Vector<T>& Vector< T >::operator= (const Vector< T > & invec) inline
References Vector< T >::size(), and Vector< T >::v.
assign()
template<class T> Vector<T>& Vector< T >::assign (const T & inval) inline
assign a scalar to every element of the vector
[NOTE: cant use operator=() for this because it would be ambiguous with the (int) constructor for number T types.]
References Vector< T >::size(), and Vector< T >::v.
clear()
template<class T> void Vector< T >::clear () inline
References Vector< T >::size(), and Vector< T >::v.
size()
template<class T> size_t Vector< T >::size () const inline
size function. returns current size of Vector
References Vector< T >::v.
Referenced by Vector< T >::append(), Vector< T >::assign(), Vector< T >::clear(), Vector< T >::operator=(), Vector< T >::operator[](), Vector< T >::resize(), Vector< T >::Vector(), and Vector< T >::~Vector().
operator[]() [1/2]
template<class T> T& Vector< T >::operator[] (unsigned int n) inline
Returns a modifiable lvalue reference to the value of the given element in this Vector. It is an error if n < 0 or n >= this->size(). \
{ Arguments:}\ n (not modified) index of desired element.\ { Returns:}\ modifiable reference to value in Vector at index n.\
{ This:}\
This object is modified if the returned reference is assigned a new value
References CH_assert, Vector< T >::size(), and Vector< T >::v.
operator[]() [2/2]
template<class T> const T& Vector< T >::operator[] (unsigned int n) const inline
Returns a constant reference to the given element in this Vector.\
{ Arguments:}\ n (not modified) index of desired element.\ { Returns:}\ constant reference to value in Vector at index n.\ { This:}\ This object is not modified.
References CH_assert, Vector< T >::size(), and Vector< T >::v.
front()
template<class T> T& Vector< T >::front () inline
References Vector< T >::v.
back() [1/2]
template<class T> T& Vector< T >::back () inline
References Vector< T >::v.
pop_back()
template<class T> void Vector< T >::pop_back () inline
References Vector< T >::v.
back() [2/2]
template<class T> const T& Vector< T >::back () const inline
References Vector< T >::v.
swap()
template<class T> void Vector< T >::swap (Vector< T > & other) inline
References Vector< T >::v.
push_back() [1/2]
template<class T> void Vector< T >::push_back (const T & in) inline
References Vector< T >::v.
push_back() [2/2]
template<class T> void Vector< T >::push_back (T && in) inline
References Vector< T >::v.
append()
template<class T> void Vector< T >::append (const Vector< T > & invec) inline
Modifies this Vector by appending the elements of the argument Vector. The new Vector will have a size of this->size() + invec.size() (where this Vector is considered before the append is performed). The first element of invec will have index this->size(), the second element will have index this->size()+1, etc.\
{ Arguments:}\ invec (not modified): Vector whose elements to append to this Vector.\ { This:}\ ----—The object is modified-------—
References Vector< T >::size(), and Vector< T >::v.
resize() [1/2]
template<class T> void Vector< T >::resize (unsigned int isize) inline
References Vector< T >::size(), and Vector< T >::v.
Referenced by Vector< T >::Vector().
reserve()
template<class T> void Vector< T >::reserve (size_t isize) inline
References Vector< T >::v.
capacity()
template<class T> size_t Vector< T >::capacity () const inline
References Vector< T >::v.
resize() [2/2]
template<class T> void Vector< T >::resize (unsigned int isize, const T & value) inline
References Vector< T >::size(), and Vector< T >::v.
sort()
template<class T> void Vector< T >::sort () inline
References Vector< T >::v.
stdVector()
template<class T> std::vector<T>& Vector< T >::stdVector () inline
Returns std::vector under the hood.
References Vector< T >::v.
constStdVector()
template<class T> const std::vector<T>& Vector< T >::constStdVector () const inline
References Vector< T >::initFunc(), and Vector< T >::v.
initFunc()
template<class T> unsigned int Vector< T >::initFunc () private
Referenced by Vector< T >::constStdVector(), and operator<<().
Member Data Documentation
v
template<class T> std::vector<T> Vector< T >::v private
Referenced by Vector< T >::append(), Vector< T >::assign(), Vector< T >::back(), Vector< T >::capacity(), Vector< T >::clear(), Vector< T >::constStdVector(), Vector< T >::front(), Vector< T >::operator=(), Vector< T >::operator[](), Vector< T >::pop_back(), Vector< T >::push_back(), Vector< T >::reserve(), Vector< T >::resize(), Vector< T >::size(), Vector< T >::sort(), Vector< T >::stdVector(), and Vector< T >::swap().
The documentation for this class was generated from the following file:
Vector.H