Chombo_4: EBCM::EBCM_Face< cent, order > Class Template Reference
EBCM::EBCM_Face< cent, order > Class Template Reference
#include <Chombo_EBCM_Graph.H>
Public Member Functions
void defineAsRegular (pr_vof a_lo, pr_vof a_hi, double a_dx)
bool operator== (const EBCM_Face &a_input) const
void print () const
bool domainBoundary () const
size_t charsize () const
size_t energize (char *a_outbuf, size_t a_expected_size) const
size_t linearIn (char *a_inbuf, size_t a_expected_size)
Public Attributes
pr_vof m_lo
pr_vof m_hi
IndexedMoments< DIM-1, order > m_facmom
Member Function Documentation
defineAsRegular()
template<CENTERING cent, int order> void EBCM::EBCM_Face< cent, order >::defineAsRegular (pr_vof a_lo, pr_vof a_hi, double a_dx) inline
operator==()
template<CENTERING cent, int order> bool EBCM::EBCM_Face< cent, order >::operator== (const EBCM_Face< cent, order > & a_input) const inline
References EBCM::EBCM_Face< cent, order >::m_hi, and EBCM::EBCM_Face< cent, order >::m_lo.
print()
template<CENTERING cent, int order> void EBCM::EBCM_Face< cent, order >::print () const inline
References pout().
domainBoundary()
template<CENTERING cent, int order> bool EBCM::EBCM_Face< cent, order >::domainBoundary () const inline
References Proto::EBIndex< cent >::m_vofIDMe.
charsize()
template<CENTERING cent, int order> size_t EBCM::EBCM_Face< cent, order >::charsize () const inline
References Proto::EBIndex< cent >::charsize().
energize()
template<CENTERING cent, int order> size_t EBCM::EBCM_Face< cent, order >::energize (char * a_outbuf, size_t a_expected_size) const inline
References Proto::EBIndex< cent >::charsize(), and Proto::EBIndex< cent >::energize().
Referenced by EBCM::EBCM_Volu< order >::linearOut(), and EBCM::EBCM_Graph< order >::linearOut().
linearIn()
template<CENTERING cent, int order> size_t EBCM::EBCM_Face< cent, order >::linearIn (char * a_inbuf, size_t a_expected_size) inline
References Proto::EBIndex< cent >::charsize(), and Proto::EBIndex< cent >::linearIn().
Member Data Documentation
m_lo
template<CENTERING cent, int order> pr_vof EBCM::EBCM_Face< cent, order >::m_lo
Referenced by EBCM::faceSign(), EBCM::Algorithm_Framework< ebcm_order >::neighborhood_t::getFaceDetails(), EBCM::Algorithm_Framework< ebcm_order >::getSystemMatrix(), and EBCM::EBCM_Face< cent, order >::operator==().
m_hi
template<CENTERING cent, int order> pr_vof EBCM::EBCM_Face< cent, order >::m_hi
Referenced by EBCM::faceSign(), EBCM::Algorithm_Framework< ebcm_order >::neighborhood_t::getFaceDetails(), EBCM::Algorithm_Framework< ebcm_order >::getSystemMatrix(), and EBCM::EBCM_Face< cent, order >::operator==().
m_facmom
template<CENTERING cent, int order> IndexedMoments<DIM-1, order> EBCM::EBCM_Face< cent, order >::m_facmom
Referenced by EBCM::Algorithm_Framework< ebcm_order >::neighborhood_t::getFaceDetails().
The documentation for this class was generated from the following file:
Chombo_EBCM_Graph.H