Chombo_4: Proto::EBBoxData< cent, data_t, ncomp > Class Template Reference
Proto::EBBoxData< cent, data_t, ncomp > Class Template Reference
Holder for EB data over a box.
#include <Proto_EBBoxData.H>
Public Member Functions
EBBoxData ()
virtual ~EBBoxData ()
template<unsigned int Csrc>
void copy (const EBBoxData< cent, data_t, Csrc > &a_src, const Box &a_srcBox, unsigned int a_srcComp, const Box &a_destBox, unsigned int a_destComp, unsigned int a_numcomp)
EBBoxData< cent, data_t, ncomp > & operator+= (const EBBoxData< cent, data_t, ncomp > &a_input)
EBBoxData< cent, data_t, ncomp > & operator-= (const EBBoxData< cent, data_t, ncomp > &a_input)
EBBoxData< cent, data_t, ncomp > & operator*= (const EBBoxData< cent, data_t, ncomp > &a_input)
EBBoxData< cent, data_t, ncomp > & operator/= (const EBBoxData< cent, data_t, ncomp > &a_input)
void scale (data_t a_scale)
void incr (const EBBoxData< cent, data_t, ncomp > &a_input, data_t a_scale)
virtual void setVal (data_t a_val)
data_t operator() (const EBIndex< cent > &a_vof, unsigned int a_ivar) const
will not work on device–debugging use only
const data_t * dataPtr (int a_dataType, int a_ivar) const
for AggStencil
data_t * dataPtr (int a_dataType, int a_ivar)
for AggStencil
BoxData< data_t, ncomp > & getRegData ()
needed to apply stencils
const BoxData< data_t, ncomp > & getRegData () const
needed to apply stencils
IrregData< cent, data_t, ncomp > & getIrregData ()
needed to apply stencils
const IrregData< cent, data_t, ncomp > & getIrregData () const
needed to apply stencils
EBBoxData (const Box &a_box, bool a_stackAlloc)
needed for Proto::LevelData. meaningless here becasue we need the graph.
template<unsigned int srccomp>
void define (EBBoxData< cent, data_t, srccomp > &a_input, unsigned int a_comp)
void dataInfo (data_t *&a_dataPtr, size_t &a_datasize, unsigned int a_whichfab) const
for data transfers. datasize does NOT include sizeof(data_t) (to conform with boxdata::size)
Box box () const
input box is cell centered—semantic is somewhat different depending on centering
EBGraph ebgraph () const
Box inputBox () const
EBBoxData (const Box &a_box, const EBGraph &a_graph, bool a_useStack=false)
void define (const Box &a_box, const EBGraph &a_graph, bool a_useStack=false)
EBDataLoc indexInfo (const EBIndex< cent > &a_index, int a_ivar) const
for AggStencil – not really part of the public interface.
virtual std::size_t charsize (const Box &a_bx, unsigned int a_startcomp, unsigned int a_numcomps) const
virtual void linearIn (void *a_buf, const Box &a_bx, unsigned int a_startcomp, unsigned int a_numcomps)
virtual void linearOut (void *a_buf, const Box &a_bx, unsigned int a_startcomp, unsigned int a_numcomps) const
Static Public Member Functions
static int preAllocatable ()
static int memTypeAllocation ()
Static Public Attributes
static const bool s_stackDefault = false
Protected Member Functions
EBBoxData (const EBBoxData< cent, data_t, ncomp > &a_src)
EBBoxData & operator= (const EBBoxData< cent, data_t, ncomp > &a_src)
Protected Attributes
Box m_inputBox
BoxData< data_t, ncomp > m_regData
IrregData< cent, data_t, ncomp > m_irrData
EBGraph m_graph
Detailed Description
template<CENTERING cent, typename data_t, unsigned int ncomp>
class Proto::EBBoxData< cent, data_t, ncomp >
Holder for EB data over a box.
This is the general holder for all EB. if cent == CELL, this is over cells. if cent == BOUNDARY, the data only exists at cut cells if cent == XFACE, YFACE, ZFACE, the data is at coordinate face. All box inputs are assumed to be cll centered
Constructor & Destructor Documentation
EBBoxData() [1/4]
template<CENTERING cent, typename data_t, unsigned int ncomp> Proto::EBBoxData< cent, data_t, ncomp >::EBBoxData () inline
~EBBoxData()
template<CENTERING cent, typename data_t, unsigned int ncomp> virtual Proto::EBBoxData< cent, data_t, ncomp >::~EBBoxData () inline virtual
EBBoxData() [2/4]
template<CENTERING cent, typename data_t, unsigned int ncomp> Proto::EBBoxData< cent, data_t, ncomp >::EBBoxData (const Box & a_box, bool a_stackAlloc) inline
needed for Proto::LevelData. meaningless here becasue we need the graph.
EBBoxData() [3/4]
template<CENTERING cent, typename data_t, unsigned int ncomp> Proto::EBBoxData< cent, data_t, ncomp >::EBBoxData (const Box & a_box, const EBGraph & a_graph, bool a_useStack = false) inline
Input box (a_box) is cell centered. the box is adjusted for centering if it is cent==XFACE YFACE or ZFACE. All irregular data (data at cut cells is held in a sparse holder (IrregData). Regular data is held in a BoxData.
EBBoxData() [4/4]
template<CENTERING cent, typename data_t, unsigned int ncomp> Proto::EBBoxData< cent, data_t, ncomp >::EBBoxData (const EBBoxData< cent, data_t, ncomp > & a_src) protected
Member Function Documentation
copy()
template<CENTERING cent, typename data_t, unsigned int ncomp> template<unsigned int Csrc> void Proto::EBBoxData< cent, data_t, ncomp >::copy (const EBBoxData< cent, data_t, Csrc > & a_src, const Box & a_srcBox, unsigned int a_srcComp, const Box & a_destBox, unsigned int a_destComp, unsigned int a_numcomp) inline
operator+=()
template<CENTERING cent, typename data_t, unsigned int ncomp> EBBoxData<cent, data_t, ncomp>& Proto::EBBoxData< cent, data_t, ncomp >::operator+= (const EBBoxData< cent, data_t, ncomp > & a_input) inline
References Proto::EBBoxData< cent, data_t, ncomp >::m_inputBox, Proto::EBBoxData< cent, data_t, ncomp >::m_irrData, and Proto::EBBoxData< cent, data_t, ncomp >::m_regData.
operator-=()
template<CENTERING cent, typename data_t, unsigned int ncomp> EBBoxData<cent, data_t, ncomp>& Proto::EBBoxData< cent, data_t, ncomp >::operator-= (const EBBoxData< cent, data_t, ncomp > & a_input) inline
References Proto::EBBoxData< cent, data_t, ncomp >::m_inputBox, Proto::EBBoxData< cent, data_t, ncomp >::m_irrData, and Proto::EBBoxData< cent, data_t, ncomp >::m_regData.
operator*=()
template<CENTERING cent, typename data_t, unsigned int ncomp> EBBoxData<cent, data_t, ncomp>& Proto::EBBoxData< cent, data_t, ncomp >::operator*= (const EBBoxData< cent, data_t, ncomp > & a_input) inline
References Proto::EBBoxData< cent, data_t, ncomp >::m_inputBox, Proto::EBBoxData< cent, data_t, ncomp >::m_irrData, and Proto::EBBoxData< cent, data_t, ncomp >::m_regData.
operator/=()
template<CENTERING cent, typename data_t, unsigned int ncomp> EBBoxData<cent, data_t, ncomp>& Proto::EBBoxData< cent, data_t, ncomp >::operator/= (const EBBoxData< cent, data_t, ncomp > & a_input) inline
References Proto::EBBoxData< cent, data_t, ncomp >::m_inputBox, Proto::EBBoxData< cent, data_t, ncomp >::m_irrData, and Proto::EBBoxData< cent, data_t, ncomp >::m_regData.
scale()
template<CENTERING cent, typename data_t, unsigned int ncomp> void Proto::EBBoxData< cent, data_t, ncomp >::scale (data_t a_scale) inline
References Proto::EBBoxData< cent, data_t, ncomp >::setVal().
Referenced by Proto::EBBoxData< cent, data_t, ncomp >::incr().
incr()
template<CENTERING cent, typename data_t, unsigned int ncomp> void Proto::EBBoxData< cent, data_t, ncomp >::incr (const EBBoxData< cent, data_t, ncomp > & a_input, data_t a_scale) inline
References Proto::EBBoxData< cent, data_t, ncomp >::scale(), and Proto::EBBoxData< cent, data_t, ncomp >::setVal().
setVal()
template<CENTERING cent, typename data_t, unsigned int ncomp> virtual void Proto::EBBoxData< cent, data_t, ncomp >::setVal (data_t a_val) inline virtual
Referenced by Proto::EBStencil< order, data_t, srcCenter, dstCenter >::apply(), Proto::EBBoxData< cent, data_t, ncomp >::incr(), and Proto::EBBoxData< cent, data_t, ncomp >::scale().
operator()()
template<CENTERING cent, typename data_t, unsigned int ncomp> data_t Proto::EBBoxData< cent, data_t, ncomp >::operator() (const EBIndex< cent > & a_vof, unsigned int a_ivar) const inline
will not work on device–debugging use only
References Proto::EBDataLoc::m_dataID, and Proto::EBIndex< cent >::m_pt.
dataPtr() [1/2]
template<CENTERING cent, typename data_t, unsigned int ncomp> const data_t* Proto::EBBoxData< cent, data_t, ncomp >::dataPtr (int a_dataType, int a_ivar) const inline
for AggStencil
Referenced by Proto::AggStencil< srcCenter, dstCenter, data_t >::hostApply().
dataPtr() [2/2]
template<CENTERING cent, typename data_t, unsigned int ncomp> data_t* Proto::EBBoxData< cent, data_t, ncomp >::dataPtr (int a_dataType, int a_ivar) inline
for AggStencil
getRegData() [1/2]
template<CENTERING cent, typename data_t, unsigned int ncomp> BoxData<data_t,ncomp>& Proto::EBBoxData< cent, data_t, ncomp >::getRegData () inline
needed to apply stencils
Referenced by Proto::EBStencil< order, data_t, srcCenter, dstCenter >::applyITZ(), Proto::EBHostData< cent, data_t, ncomp >::define(), Proto::EBBoxData< cent, data_t, ncomp >::define(), and Proto::getBoxData().
getRegData() [2/2]
template<CENTERING cent, typename data_t, unsigned int ncomp> const BoxData<data_t,ncomp>& Proto::EBBoxData< cent, data_t, ncomp >::getRegData () const inline
needed to apply stencils
getIrregData() [1/2]
template<CENTERING cent, typename data_t, unsigned int ncomp> IrregData<cent, data_t,ncomp>& Proto::EBBoxData< cent, data_t, ncomp >::getIrregData () inline
needed to apply stencils
Referenced by Proto::EBHostData< cent, data_t, ncomp >::define(), Proto::EBBoxData< cent, data_t, ncomp >::define(), and Proto::getIrregData().
getIrregData() [2/2]
template<CENTERING cent, typename data_t, unsigned int ncomp> const IrregData<cent, data_t, ncomp>& Proto::EBBoxData< cent, data_t, ncomp >::getIrregData () const inline
needed to apply stencils
define() [1/2]
template<CENTERING cent, typename data_t, unsigned int ncomp> template<unsigned int srccomp> void Proto::EBBoxData< cent, data_t, ncomp >::define (EBBoxData< cent, data_t, srccomp > & a_input, unsigned int a_comp) inline
References Proto::EBBoxData< cent, data_t, ncomp >::ebgraph(), Proto::EBBoxData< cent, data_t, ncomp >::getIrregData(), and Proto::EBBoxData< cent, data_t, ncomp >::getRegData().
Referenced by EBEncyclopedia< order, data_t >::applyCellToFace(), ScalarAliasFactory< srcComp, dstComp >::create(), and Proto::EBFluxData< data_t, ncomp >::define().
dataInfo()
template<CENTERING cent, typename data_t, unsigned int ncomp> void Proto::EBBoxData< cent, data_t, ncomp >::dataInfo (data_t *& a_dataPtr, size_t & a_datasize, unsigned int a_whichfab) const inline
for data transfers. datasize does NOT include sizeof(data_t) (to conform with boxdata::size)
Referenced by Proto::EBStencil< order, data_t, srcCenter, dstCenter >::computeDiagonalWeights(), EBLevelBoxData< cent, NUMCOMPS >::copyToDevice(), and EBLevelBoxData< cent, NUMCOMPS >::copyToHost().
box()
template<CENTERING cent, typename data_t, unsigned int ncomp> Box Proto::EBBoxData< cent, data_t, ncomp >::box () const inline
input box is cell centered—semantic is somewhat different depending on centering
Referenced by Proto::dumpArea().
ebgraph()
template<CENTERING cent, typename data_t, unsigned int ncomp> EBGraph Proto::EBBoxData< cent, data_t, ncomp >::ebgraph () const inline
Referenced by Proto::EBStencil< order, data_t, srcCenter, dstCenter >::apply(), EBLevelBoxData< cent, NUMCOMPS >::checkAnswer(), Proto::EBHostData< cent, data_t, ncomp >::define(), Proto::EBBoxData< cent, data_t, ncomp >::define(), Proto::dumpArea(), Proto::maxLocCell(), and Proto::maxLocFace().
inputBox()
template<CENTERING cent, typename data_t, unsigned int ncomp> Box Proto::EBBoxData< cent, data_t, ncomp >::inputBox () const inline
Referenced by Proto::EBStencil< order, data_t, srcCenter, dstCenter >::apply(), Proto::AggStencil< srcCenter, dstCenter, data_t >::apply(), EBLevelBoxData< cent, NUMCOMPS >::checkAnswer(), and Proto::checkBox().
define() [2/2]
template<CENTERING cent, typename data_t, unsigned int ncomp> void Proto::EBBoxData< cent, data_t, ncomp >::define (const Box & a_box, const EBGraph & a_graph, bool a_useStack = false) inline
indexInfo()
template<CENTERING cent, typename data_t, unsigned int ncomp> EBDataLoc Proto::EBBoxData< cent, data_t, ncomp >::indexInfo (const EBIndex< cent > & a_index, int a_ivar) const inline
for AggStencil – not really part of the public interface.
References Proto::EBDataLoc::m_dataID, Proto::EBDataLoc::m_offset, and Proto::EBIndex< cent >::m_pt.
Referenced by Proto::AggStencil< srcCenter, dstCenter, data_t >::AggStencil().
charsize()
template<CENTERING cent, typename data_t, unsigned int ncomp> virtual std::size_t Proto::EBBoxData< cent, data_t, ncomp >::charsize (const Box & a_bx, unsigned int a_startcomp, unsigned int a_numcomps) const inline virtual
linearIn()
template<CENTERING cent, typename data_t, unsigned int ncomp> virtual void Proto::EBBoxData< cent, data_t, ncomp >::linearIn (void * a_buf, const Box & a_bx, unsigned int a_startcomp, unsigned int a_numcomps) inline virtual
linearOut()
template<CENTERING cent, typename data_t, unsigned int ncomp> virtual void Proto::EBBoxData< cent, data_t, ncomp >::linearOut (void * a_buf, const Box & a_bx, unsigned int a_startcomp, unsigned int a_numcomps) const inline virtual
preAllocatable()
template<CENTERING cent, typename data_t, unsigned int ncomp> static int Proto::EBBoxData< cent, data_t, ncomp >::preAllocatable () inline static
memTypeAllocation()
template<CENTERING cent, typename data_t, unsigned int ncomp> static int Proto::EBBoxData< cent, data_t, ncomp >::memTypeAllocation () inline static
operator=()
template<CENTERING cent, typename data_t, unsigned int ncomp> EBBoxData& Proto::EBBoxData< cent, data_t, ncomp >::operator= (const EBBoxData< cent, data_t, ncomp > & a_src) protected
Member Data Documentation
s_stackDefault
template<CENTERING cent, typename data_t, unsigned int ncomp> const bool Proto::EBBoxData< cent, data_t, ncomp >::s_stackDefault = false static
m_inputBox
template<CENTERING cent, typename data_t, unsigned int ncomp> Box Proto::EBBoxData< cent, data_t, ncomp >::m_inputBox protected
Referenced by Proto::EBBoxData< cent, data_t, ncomp >::operator*=(), Proto::EBBoxData< cent, data_t, ncomp >::operator+=(), Proto::EBBoxData< cent, data_t, ncomp >::operator-=(), and Proto::EBBoxData< cent, data_t, ncomp >::operator/=().
m_regData
template<CENTERING cent, typename data_t, unsigned int ncomp> BoxData< data_t, ncomp> Proto::EBBoxData< cent, data_t, ncomp >::m_regData protected
Referenced by Proto::EBBoxData< cent, data_t, ncomp >::operator*=(), Proto::EBBoxData< cent, data_t, ncomp >::operator+=(), Proto::EBBoxData< cent, data_t, ncomp >::operator-=(), and Proto::EBBoxData< cent, data_t, ncomp >::operator/=().
m_irrData
template<CENTERING cent, typename data_t, unsigned int ncomp> IrregData<cent, data_t, ncomp> Proto::EBBoxData< cent, data_t, ncomp >::m_irrData protected
Referenced by Proto::EBBoxData< cent, data_t, ncomp >::operator*=(), Proto::EBBoxData< cent, data_t, ncomp >::operator+=(), Proto::EBBoxData< cent, data_t, ncomp >::operator-=(), and Proto::EBBoxData< cent, data_t, ncomp >::operator/=().
m_graph
template<CENTERING cent, typename data_t, unsigned int ncomp> EBGraph Proto::EBBoxData< cent, data_t, ncomp >::m_graph protected
The documentation for this class was generated from the following file:
Proto_EBBoxData.H