Chombo_4: Proto::MinimalCCCM< dim > Class Template Reference
Proto::MinimalCCCM< dim > Class Template Reference
#include <Proto_MinimalCCCM.H>
Public Types
typedef IndexTM< int, dim > IvDim
typedef IndexTM< double, dim > RvDim
typedef map< IvDim, double > PthMoment
typedef map< IndexTM< int, dim-1 >, double > PthMomentLesserDimension
typedef map< IndexTM< int, 1 >, double > OneDMoments
typedef map< int, IvDim > LocPthMoment
typedef map< IvDim, int > PthMomentLoc
typedef map< Iv2, CutCellMoments< dim-1 > > BdCutCellMoments
Public Member Functions
MinimalCCCM ()
MinimalCCCM (const MinimalCCCM< dim > &a_MinimalCCCM)
MinimalCCCM (const IFData< dim > &a_info)
~MinimalCCCM ()
void computeMoments (const int &a_orderPmax, const int &a_degreePmax)
void computeMomentsRecursively (const int &a_orderPmax, const int &a_degreePmax)
vector< double > computeRhs (LSProblem< dim > &a_lsp, const int &a_order)
void operator= (const MinimalCCCM< dim > &a_MinimalCCCM)
double factorial (const IvDim &a_multiIndex) const
Public Attributes
CutCellMoments< dim > m_cutCellMoments
bool m_boundaryMomentsComputed
Member Typedef Documentation
IvDim
template<int dim> typedef IndexTM<int,dim> Proto::MinimalCCCM< dim >::IvDim
RvDim
template<int dim> typedef IndexTM<double,dim> Proto::MinimalCCCM< dim >::RvDim
PthMoment
template<int dim> typedef map<IvDim,double > Proto::MinimalCCCM< dim >::PthMoment
PthMomentLesserDimension
template<int dim> typedef map<IndexTM<int,dim-1>,double > Proto::MinimalCCCM< dim >::PthMomentLesserDimension
OneDMoments
template<int dim> typedef map<IndexTM<int,1>,double > Proto::MinimalCCCM< dim >::OneDMoments
LocPthMoment
template<int dim> typedef map<int,IvDim> Proto::MinimalCCCM< dim >::LocPthMoment
PthMomentLoc
template<int dim> typedef map<IvDim,int > Proto::MinimalCCCM< dim >::PthMomentLoc
BdCutCellMoments
template<int dim> typedef map<Iv2,CutCellMoments<dim-1> > Proto::MinimalCCCM< dim >::BdCutCellMoments
Constructor & Destructor Documentation
MinimalCCCM() [1/3]
template<int dim> Proto::MinimalCCCM< dim >::MinimalCCCM () inline
MinimalCCCM() [2/3]
template<int dim> Proto::MinimalCCCM< dim >::MinimalCCCM (const MinimalCCCM< dim > & a_MinimalCCCM) inline
MinimalCCCM() [3/3]
template<int dim> Proto::MinimalCCCM< dim >::MinimalCCCM (const IFData< dim > & a_info) inline
References BDID_DIR, BDID_HILO, Proto::MinimalCCCM< dim >::m_cutCellMoments, and Proto::IFData< dim >::m_maxOrder.
~MinimalCCCM()
template<int dim> Proto::MinimalCCCM< dim >::~MinimalCCCM () inline
Member Function Documentation
computeMoments()
template<int dim> void Proto::MinimalCCCM< dim >::computeMoments (const int & a_orderPmax, const int & a_degreePmax) inline
References Proto::MinimalCCCM< dim >::computeMomentsRecursively(), LARGEREALVAL, Proto::MinimalCCCM< dim >::m_boundaryMomentsComputed, and Proto::MinimalCCCM< dim >::m_cutCellMoments.
computeMomentsRecursively()
template<int dim> void Proto::MinimalCCCM< dim >::computeMomentsRecursively (const int & a_orderPmax, const int & a_degreePmax) inline
References Proto::MinimalCCCM< dim >::computeRhs(), Proto::LSProblem< dim >::getMonomialLocMapDegreeP(), Proto::LSProblem< dim >::getMonomialLocMapDegreePLess1(), Proto::LSProblem< dim >::getNumberDegP(), Proto::LSProblem< dim >::getUnknown(), Proto::LSProblem< dim >::invertNormalEq(), Proto::MinimalCCCM< dim >::m_boundaryMomentsComputed, and Proto::MinimalCCCM< dim >::m_cutCellMoments.
Referenced by Proto::MinimalCCCM< dim >::computeMoments().
computeRhs()
template<int dim> vector< double > Proto::MinimalCCCM< dim >::computeRhs (LSProblem< dim > & a_lsp, const int & a_order) inline
References Proto::MinimalCCCM< dim >::factorial(), Proto::generateMultiIndices(), Proto::LSProblem< dim >::getLocMonomialMapDegreeP(), Proto::LSProblem< dim >::getNumberDegP(), Proto::MinimalCCCM< dim >::m_cutCellMoments, and Proto::POW().
Referenced by Proto::MinimalCCCM< dim >::computeMomentsRecursively().
operator=()
template<int dim> void Proto::MinimalCCCM< dim >::operator= (const MinimalCCCM< dim > & a_MinimalCCCM) inline
References Proto::MinimalCCCM< dim >::m_cutCellMoments.
factorial()
template<int dim> double Proto::MinimalCCCM< dim >::factorial (const IvDim & a_multiIndex) const inline
Referenced by Proto::MinimalCCCM< dim >::computeRhs().
Member Data Documentation
m_cutCellMoments
template<int dim> CutCellMoments<dim> Proto::MinimalCCCM< dim >::m_cutCellMoments
Referenced by Proto::MinimalCCCM< dim >::computeMoments(), Proto::MinimalCCCM< 1 >::computeMoments(), Proto::MinimalCCCM< dim >::computeMomentsRecursively(), Proto::MinimalCCCM< 1 >::computeMomentsUsingBinomial(), Proto::MinimalCCCM< dim >::computeRhs(), Proto::MinimalCCCM< dim >::MinimalCCCM(), Proto::MinimalCCCM< dim >::operator=(), Proto::MinimalCCCM< 1 >::operator=(), and Proto::MinimalCCCM< 1 >::simpleComputeMoments().
m_boundaryMomentsComputed
template<int dim> bool Proto::MinimalCCCM< dim >::m_boundaryMomentsComputed
Referenced by Proto::MinimalCCCM< dim >::computeMoments(), and Proto::MinimalCCCM< dim >::computeMomentsRecursively().
The documentation for this class was generated from the following files:
Proto_MinimalCCCM.H
Proto_MinimalCCCMImplem.H