Chombo_4: CopyIterator Class Reference
CopyIterator Class Reference
#include <Chombo_Copier.H>
Public Types
enum local_from_to { LOCAL, FROM, TO }
Public Member Functions
CopyIterator (const Copier &a_copier, local_from_to)
const MotionItem & operator() () const
const MotionItem & operator[] (size_t index) const
void operator++ ()
bool ok () const
void reset ()
size_t size ()
Private Attributes
const std::vector< MotionItem * > * m_motionplanPtr
unsigned int m_current
Member Enumeration Documentation
local_from_to
enum CopyIterator::local_from_to
Enumerator
LOCAL
FROM
TO
Constructor & Destructor Documentation
CopyIterator()
CopyIterator::CopyIterator (const Copier & a_copier, local_from_to type) inline
References MayDay::Error(), FROM, LOCAL, Copier::m_fromMotionPlan, Copier::m_localMotionPlan, m_motionplanPtr, Copier::m_toMotionPlan, and TO.
Member Function Documentation
operator()()
const MotionItem & CopyIterator::operator() () const inline
References CH_assert, m_current, m_motionplanPtr, and size().
operator[]()
const MotionItem & CopyIterator::operator[] (size_t index) const inline
References CH_assert, m_motionplanPtr, and size().
operator++()
void CopyIterator::operator++ () inline
References m_current.
ok()
bool CopyIterator::ok () const inline
References m_current, and m_motionplanPtr.
Referenced by BoxLayoutData< FArrayBox >::allocateBuffers().
reset()
void CopyIterator::reset () inline
References m_current.
size()
size_t CopyIterator::size () inline
Referenced by BoxLayoutData< FArrayBox >::generalCopyTo(), BoxLayoutData< FArrayBox >::makeItSoLocalCopy(), operator()(), and operator[]().
Member Data Documentation
m_motionplanPtr
const std::vector<MotionItem*>* CopyIterator::m_motionplanPtr private
Referenced by CopyIterator(), ok(), operator()(), and operator[]().
m_current
unsigned int CopyIterator::m_current private
Referenced by ok(), operator()(), operator++(), and reset().
The documentation for this class was generated from the following file:
Chombo_Copier.H