Chombo_4: Proto::SimpleSphereIF Class Reference
Proto::SimpleSphereIF Class Reference
Sphere.
#include <Proto_SimpleImplicitFunctions.H>
Public Member Functions
Box getBoundingBox (RealVect a_origin, double a_dx, double a_radius, RealVect a_cent)
virtual bool entireBoxRegular (const Box &a_box, const RealVect &a_origin, const double &a_dx)
return true if the box is entirely in the fluid
virtual bool entireBoxCovered (const Box &a_box, const RealVect &a_origin, const double &a_dx)
return true if the entire box is covered by the ellipsoid
SimpleSphereIF (const RealVect &a_X0, const double &a_R, const bool &a_inside)
virtual ~SimpleSphereIF ()
Destructor.
Public Member Functions inherited from Proto::SimpleEllipsoidIF
SimpleEllipsoidIF (const RealVect &a_ABE, const RealVect &a_X0, const double &a_R, const bool &a_inside)
virtual ~SimpleEllipsoidIF ()
Destructor.
double value (const IndexTM< double, DIM > &a_point) const
virtual double value (const IndexTM< int, DIM > &a_partialDerivative, const IndexTM< double, DIM > &a_point) const
virtual BaseIF * newImplicitFunction () const
factory method
Public Member Functions inherited from Proto::SimpleGeometry
IndexTM< double, DIM > getIndexTM (const RealVect &a_rv)
vector< RealVect > getCornerLocations (const Box &a_box, const RealVect &a_origin, const double &a_dx)
Public Member Functions inherited from Proto::BaseIF
BaseIF ()
Default constructor.
virtual ~BaseIF ()
Default destructor.
virtual bool entireBoxRegular (const Proto::Box &a_box, const RealVect &a_origin, const double &a_dx)
virtual bool entireBoxCovered (const Proto::Box &a_box, const RealVect &a_origin, const double &a_dx)
overwrite if you have a fast way of knowing if a whole region is regular
Private Member Functions
SimpleSphereIF ()
Additional Inherited Members
Protected Attributes inherited from Proto::SimpleEllipsoidIF
RealVect m_ABE
RealVect m_X0
double m_R
bool m_inside
RealVect m_A2
Detailed Description
Sphere.
(x-xo)^2 + (y-y0)^2 + (z-z0)^2 - r^2 = f(x,y,z)
Constructor & Destructor Documentation
SimpleSphereIF() [1/2]
Proto::SimpleSphereIF::SimpleSphereIF (const RealVect & a_X0, const double & a_R, const bool & a_inside) inline
~SimpleSphereIF()
virtual Proto::SimpleSphereIF::~SimpleSphereIF () inline virtual
Destructor.
SimpleSphereIF() [2/2]
Proto::SimpleSphereIF::SimpleSphereIF () private
Member Function Documentation
getBoundingBox()
Box Proto::SimpleSphereIF::getBoundingBox (RealVect a_origin, double a_dx, double a_radius, RealVect a_cent) inline
References grow().
entireBoxRegular()
virtual bool Proto::SimpleSphereIF::entireBoxRegular (const Box & a_box, const RealVect & a_origin, const double & a_dx) inline virtual
return true if the box is entirely in the fluid
References Box::contains().
entireBoxCovered()
virtual bool Proto::SimpleSphereIF::entireBoxCovered (const Box & a_box, const RealVect & a_origin, const double & a_dx) inline virtual
return true if the entire box is covered by the ellipsoid
References Box::contains().
The documentation for this class was generated from the following file:
Proto_SimpleImplicitFunctions.H