Chombo_4: EBCM::HostLevelData< data_t, ncomp, order > Class Template Reference
EBCM::HostLevelData< data_t, ncomp, order > Class Template Reference
Simple structure to hold data on a level in an ebcm context. volume data only.
#include <Chombo_EBCM_HostLevelData.H>
Public Types
typedef Proto::HostBoxData< data_t, ncomp > pr_fab_t
typedef Chombo4::NullConstructorDataFactory< pr_fab_t > null_factory_t
typedef CH4_Data_Choreography::DistributedData< pr_fab_t > mpi_frame_t
typedef EBCM::MetaDataLevel< order > ebcm_meta_t
typedef Chombo4::GeometryService< order > ch_geoserv
typedef Chombo4::DisjointBoxLayout ch_dbl
typedef Chombo4::ProblemDomain ch_probdom
typedef Chombo4::DataIterator ch_dit
typedef Chombo4::IntVect ch_iv
typedef Chombo4::FArrayBox ch_fab
typedef Chombo4::BoxIterator ch_bit
typedef Chombo4::LevelData< ch_fab > ch_ldfab
Public Member Functions
HostLevelData (const shared_ptr< ebcm_meta_t > &a_meta, const int &a_ghost)
void writeToHDF5 (string a_filename) const
void exchange (bool a_printStuff)
Public Attributes
shared_ptr< ebcm_meta_t > m_meta
shared_ptr< mpi_frame_t > m_data
Private Member Functions
HostLevelData ()
Detailed Description
template<typename data_t, int ncomp, int order>
class EBCM::HostLevelData< data_t, ncomp, order >
Simple structure to hold data on a level in an ebcm context. volume data only.
Member Typedef Documentation
pr_fab_t
template<typename data_t, int ncomp, int order> typedef Proto::HostBoxData<data_t, ncomp> EBCM::HostLevelData< data_t, ncomp, order >::pr_fab_t
null_factory_t
template<typename data_t, int ncomp, int order> typedef Chombo4::NullConstructorDataFactory< pr_fab_t> EBCM::HostLevelData< data_t, ncomp, order >::null_factory_t
mpi_frame_t
template<typename data_t, int ncomp, int order> typedef CH4_Data_Choreography::DistributedData< pr_fab_t > EBCM::HostLevelData< data_t, ncomp, order >::mpi_frame_t
ebcm_meta_t
template<typename data_t, int ncomp, int order> typedef EBCM::MetaDataLevel< order > EBCM::HostLevelData< data_t, ncomp, order >::ebcm_meta_t
ch_geoserv
template<typename data_t, int ncomp, int order> typedef Chombo4::GeometryService< order > EBCM::HostLevelData< data_t, ncomp, order >::ch_geoserv
ch_dbl
template<typename data_t, int ncomp, int order> typedef Chombo4::DisjointBoxLayout EBCM::HostLevelData< data_t, ncomp, order >::ch_dbl
ch_probdom
template<typename data_t, int ncomp, int order> typedef Chombo4::ProblemDomain EBCM::HostLevelData< data_t, ncomp, order >::ch_probdom
ch_dit
template<typename data_t, int ncomp, int order> typedef Chombo4::DataIterator EBCM::HostLevelData< data_t, ncomp, order >::ch_dit
ch_iv
template<typename data_t, int ncomp, int order> typedef Chombo4::IntVect EBCM::HostLevelData< data_t, ncomp, order >::ch_iv
ch_fab
template<typename data_t, int ncomp, int order> typedef Chombo4::FArrayBox EBCM::HostLevelData< data_t, ncomp, order >::ch_fab
ch_bit
template<typename data_t, int ncomp, int order> typedef Chombo4::BoxIterator EBCM::HostLevelData< data_t, ncomp, order >::ch_bit
ch_ldfab
template<typename data_t, int ncomp, int order> typedef Chombo4::LevelData<ch_fab> EBCM::HostLevelData< data_t, ncomp, order >::ch_ldfab
Constructor & Destructor Documentation
HostLevelData() [1/2]
template<typename data_t, int ncomp, int order> EBCM::HostLevelData< data_t, ncomp, order >::HostLevelData (const shared_ptr< ebcm_meta_t > & a_meta, const int & a_ghost) inline
References EBCM::HostLevelData< data_t, ncomp, order >::m_data, and EBCM::HostLevelData< data_t, ncomp, order >::m_meta.
HostLevelData() [2/2]
template<typename data_t, int ncomp, int order> EBCM::HostLevelData< data_t, ncomp, order >::HostLevelData () private
Referenced by EBCM::HostLevelData< data_t, ncomp, order >::exchange().
Member Function Documentation
writeToHDF5()
template<typename data_t, int ncomp, int order> void EBCM::HostLevelData< data_t, ncomp, order >::writeToHDF5 (string a_filename) const inline
References ProtoCh::getPoint(), EBCM::HostLevelData< data_t, ncomp, order >::m_meta, and writeLevelname().
exchange()
template<typename data_t, int ncomp, int order> void EBCM::HostLevelData< data_t, ncomp, order >::exchange (bool a_printStuff) inline
References EBCM::HostLevelData< data_t, ncomp, order >::HostLevelData().
Member Data Documentation
m_meta
template<typename data_t, int ncomp, int order> shared_ptr< ebcm_meta_t > EBCM::HostLevelData< data_t, ncomp, order >::m_meta
Referenced by EBCM::HostLevelData< data_t, ncomp, order >::HostLevelData(), and EBCM::HostLevelData< data_t, ncomp, order >::writeToHDF5().
m_data
template<typename data_t, int ncomp, int order> shared_ptr< mpi_frame_t > EBCM::HostLevelData< data_t, ncomp, order >::m_data
Referenced by EBCM::HostLevelData< data_t, ncomp, order >::HostLevelData().
The documentation for this class was generated from the following file:
Chombo_EBCM_HostLevelData.H