Chombo_4: CH4_Data_Choreography::CommunicationMetaData< fabtype_t > Class Template Reference
CH4_Data_Choreography::CommunicationMetaData< fabtype_t > Class Template Reference
class to manage meta data for communication between processors (reduces to a bunch of proc_interactions)
#include <Chombo_CommunicationMetaData.H>
Public Member Functions
CommunicationMetaData (const BoxPattern &a_pattern, vector< fabtype_t *> &a_data, bool a_printStuff=false)
~CommunicationMetaData ()
Because we have malloced, so we must free.
Public Attributes
int m_numSends
int m_numRecvs
vector< shared_ptr< proc_interaction_t > > m_recvPI
vector< shared_ptr< proc_interaction_t > > m_sendPI
Detailed Description
template<class fabtype_t>
class CH4_Data_Choreography::CommunicationMetaData< fabtype_t >
class to manage meta data for communication between processors (reduces to a bunch of proc_interactions)
Constructor & Destructor Documentation
CommunicationMetaData()
template<class fabtype_t> CH4_Data_Choreography::CommunicationMetaData< fabtype_t >::CommunicationMetaData (const BoxPattern & a_pattern, vector< fabtype_t *> & a_data, bool a_printStuff = false) inline
References CH4_SPMD::barrier(), CH_assert, CH_TIME, CH4_Data_Choreography::BoxPattern::m_recvPattern, CH4_Data_Choreography::BoxPattern::m_sendPattern, CH4_SPMD::numProc(), pout(), and CH4_SPMD::procID().
~CommunicationMetaData()
template<class fabtype_t> CH4_Data_Choreography::CommunicationMetaData< fabtype_t >::~CommunicationMetaData () inline
Because we have malloced, so we must free.
Member Data Documentation
m_numSends
template<class fabtype_t> int CH4_Data_Choreography::CommunicationMetaData< fabtype_t >::m_numSends
m_numRecvs
template<class fabtype_t> int CH4_Data_Choreography::CommunicationMetaData< fabtype_t >::m_numRecvs
m_recvPI
template<class fabtype_t> vector<shared_ptr<proc_interaction_t> > CH4_Data_Choreography::CommunicationMetaData< fabtype_t >::m_recvPI
Referenced by CH4_Data_Choreography::DistributedData< EBFluxData< Real, NUMCOMPS > >::communicate().
m_sendPI
template<class fabtype_t> vector<shared_ptr<proc_interaction_t> > CH4_Data_Choreography::CommunicationMetaData< fabtype_t >::m_sendPI
Referenced by CH4_Data_Choreography::DistributedData< EBFluxData< Real, NUMCOMPS > >::communicate().
The documentation for this class was generated from the following file:
Chombo_CommunicationMetaData.H