Chombo_4: Proto::Poisson2ndOrder< facecent, order > Class Template Reference
Proto::Poisson2ndOrder< facecent, order > Class Template Reference
second order Poisson flux
#include <Proto_SecondOrderCell.H>
Public Member Functions
void getFaceCenteredFluxStencil (LocalStencil< CELL, double > &a_facesten, const EBIndex< facecent > &a_face, const EBGraph &a_graph, const HostIrregData< facecent, IndMomSDMinOne, 1 > &a_facedat, string a_dombc, double a_dx) const
virtual ~Poisson2ndOrder ()
Poisson2ndOrder ()
Public Member Functions inherited from Proto::Base2ndOrderFlux< facecent, order >
void getFaceInterpStencil (LocalStencil< cent, double > &a_sten, const EBIndex< cent > &a_face, const EBGraph &a_graph, const HostIrregData< cent, IndMomSDMinOne, 1 > &a_facdata, double a_dx) const
void getCentroidStencil (LocalStencil< CELL, double > &a_sten, const EBIndex< cent > &a_face, const EBGraph &a_graph, const HostIrregData< cent, IndMomSDMinOne, 1 > &a_facdata, string a_dombc, double a_dx) const
Private Types
typedef IndexedMoments< DIM, order > IndMomDIM
typedef IndexedMoments< DIM-1, order > IndMomSDMinOne
typedef MomentIterator< DIM, order > MomItDIM
typedef MomentIterator< DIM-1, order > MomItSDMinOne
typedef HostIrregData< CELL, IndMomDIM, 1 > VoluData
typedef HostIrregData< BOUNDARY, IndMomDIM, 1 > EBFaData
typedef HostIrregData< XFACE, IndMomSDMinOne, 1 > XFacData
typedef HostIrregData< YFACE, IndMomSDMinOne, 1 > YFacData
typedef HostIrregData< ZFACE, IndMomSDMinOne, 1 > ZFacData
Additional Inherited Members
Public Types inherited from Proto::Base2ndOrderFlux< facecent, order >
typedef IndexedMoments< DIM, order > IndMomDIM
typedef IndexedMoments< DIM-1, order > IndMomSDMinOne
typedef MomentIterator< DIM, order > MomItDIM
typedef MomentIterator< DIM-1, order > MomItSDMinOne
Detailed Description
template<CENTERING facecent, int order>
class Proto::Poisson2ndOrder< facecent, order >
second order Poisson flux
Member Typedef Documentation
IndMomDIM
template<CENTERING facecent, int order> typedef IndexedMoments<DIM , order> Proto::Poisson2ndOrder< facecent, order >::IndMomDIM private
IndMomSDMinOne
template<CENTERING facecent, int order> typedef IndexedMoments<DIM-1, order> Proto::Poisson2ndOrder< facecent, order >::IndMomSDMinOne private
MomItDIM
template<CENTERING facecent, int order> typedef MomentIterator<DIM , order> Proto::Poisson2ndOrder< facecent, order >::MomItDIM private
MomItSDMinOne
template<CENTERING facecent, int order> typedef MomentIterator<DIM-1, order> Proto::Poisson2ndOrder< facecent, order >::MomItSDMinOne private
VoluData
template<CENTERING facecent, int order> typedef HostIrregData<CELL , IndMomDIM , 1> Proto::Poisson2ndOrder< facecent, order >::VoluData private
EBFaData
template<CENTERING facecent, int order> typedef HostIrregData<BOUNDARY, IndMomDIM , 1> Proto::Poisson2ndOrder< facecent, order >::EBFaData private
XFacData
template<CENTERING facecent, int order> typedef HostIrregData<XFACE, IndMomSDMinOne, 1> Proto::Poisson2ndOrder< facecent, order >::XFacData private
YFacData
template<CENTERING facecent, int order> typedef HostIrregData<YFACE, IndMomSDMinOne, 1> Proto::Poisson2ndOrder< facecent, order >::YFacData private
ZFacData
template<CENTERING facecent, int order> typedef HostIrregData<ZFACE, IndMomSDMinOne, 1> Proto::Poisson2ndOrder< facecent, order >::ZFacData private
Constructor & Destructor Documentation
~Poisson2ndOrder()
template<CENTERING facecent, int order> virtual Proto::Poisson2ndOrder< facecent, order >::~Poisson2ndOrder () inline virtual
Poisson2ndOrder()
template<CENTERING facecent, int order> Proto::Poisson2ndOrder< facecent, order >::Poisson2ndOrder () inline
Member Function Documentation
getFaceCenteredFluxStencil()
template<CENTERING cent, int order> void Proto::Poisson2ndOrder< cent, order >::getFaceCenteredFluxStencil (LocalStencil< CELL, double > & a_facesten, const EBIndex< cent > & a_face, const EBGraph & a_graph, const HostIrregData< cent, IndMomSDMinOne, 1 > & a_facedat, string a_dombc, double a_dx) const inline virtual
Reimplemented from Proto::Base2ndOrderFlux< facecent, order >.
References Proto::LocalStencil< cent, data_t >::add(), Proto::LocalStencil< cent, data_t >::clear(), Proto::SecondOrderStencil< order >::get2ndOrderDivFStencil(), Proto::EBIndex< cent >::getVoF(), Proto::EBIndex< cent >::m_isBoundary, Proto::EBIndex< cent >::m_vofIDLo, and Proto::EBIndex< cent >::m_vofIDMe.
Referenced by Proto::Base2ndOrderFlux< facecent, order >::getCentroidStencil().
The documentation for this class was generated from the following files:
Proto_SecondOrderCell.H
Proto_SecondOrderCellImplem.H