Chombo_4: Proto::vofMo Class Reference
Proto::vofMo Class Reference
#include <Proto_Moments.H>
Public Member Functions
vofMo ()
void define (const faceMo a_faces[6])
void makeNormal ()
void setNormal (double a_normalVec[3])
void getNormal (double a_normalVec[3]) const
void normalize (double a_normalVec[3])
void getFaces (faceMo a_faces[6]) const
double getBdArea () const
Private Attributes
faceMo m_faces [6]
double m_normalVec [3]
double m_bdArea
Constructor & Destructor Documentation
vofMo()
Proto::vofMo::vofMo () inline
References Proto::edgeMo::define(), and Proto::getFaces().
Member Function Documentation
define()
void Proto::vofMo::define (const faceMo a_faces[6])
References Proto::edgeMo::dontKnow(), Proto::faceMo::dontKnow(), Proto::faceMo::getEdges(), Proto::faceMo::getFaceNormal(), Proto::faceMo::isCovered(), and Proto::faceMo::isRegular().
makeNormal()
void Proto::vofMo::makeNormal ()
References Proto::Moments::momentCalc2D().
setNormal()
void Proto::vofMo::setNormal (double a_normalVec[3])
getNormal()
void Proto::vofMo::getNormal (double a_normalVec[3]) const
Referenced by Proto::Moments::momentCalc3D().
normalize()
void Proto::vofMo::normalize (double a_normalVec[3])
getFaces()
void Proto::vofMo::getFaces (faceMo a_faces[6]) const
References Proto::faceMo::define(), Proto::edgeMo::dontKnow(), and Proto::edgeMo::isRegular().
Referenced by Proto::Moments::momentCalc3D().
getBdArea()
double Proto::vofMo::getBdArea () const
Member Data Documentation
m_faces
faceMo Proto::vofMo::m_faces[6] private
m_normalVec
double Proto::vofMo::m_normalVec[3] private
m_bdArea
double Proto::vofMo::m_bdArea private
The documentation for this class was generated from the following files:
Proto_Moments.H
Proto_MomentsImplem.H