Chombo_4: DisjointBoxLayout Class Reference
DisjointBoxLayout Class Reference
A BoxLayout that has a concept of disjointedness.
#include <Chombo_DisjointBoxLayout.H>
Public Member Functions
const ProblemDomain & physDomain () const
const Box & getDomain () const
virtual void closeNoSort ()
Constructors, destructors, defines
DisjointBoxLayout ()
DisjointBoxLayout (const std::vector< Box > &a_boxes, const std::vector< int > &a_procIDs)
DisjointBoxLayout (const std::vector< Box > &a_boxes, const std::vector< int > &a_procIDs, const ProblemDomain &a_physDomain)
virtual ~DisjointBoxLayout ()
unsigned long long int numPointsThisProc () const
virtual void define (const std::vector< Box > &a_boxes, const std::vector< int > &a_procIDs)
void defineAndLoadBalance (const std::vector< Box > &a_boxes, std::vector< int > *a_procIDs)
void defineAndLoadBalance (const std::vector< Box > &a_boxes, std::vector< int > *a_procIDs, const ProblemDomain &a_physDomain)
virtual void define (const BoxLayout &a_layout)
virtual void define (const BoxLayout &a_layout, const ProblemDomain &a_physDomain)
virtual void define (const std::vector< Box > &a_boxes, const std::vector< int > &a_procIDs, const ProblemDomain &a_physDomain)
virtual void define_pd (const std::vector< Box > &a_boxes, const std::vector< int > &a_procIDs, const ProblemDomain &a_physDomain)
Checks
bool isDisjoint () const
bool checkPeriodic (const ProblemDomain &a_domain) const
bool checkDomains (const DisjointBoxLayout &a_dbl) const
Public Member Functions inherited from BoxLayout
std::vector< Box > boxArray () const
std::vector< int > procIDs () const
unsigned int indexI (const LayoutIndex &) const
const std::vector< Entry > * rawPtr () const
BoxLayout ()
BoxLayout (const std::vector< Box > &a_boxes, const std::vector< int > &a_procIDs)
void transform (BaseTransform &a_transform)
virtual ~BoxLayout ()
BoxLayout & operator= (const BoxLayout &a_rhs)
Box operator[] (const LayoutIndex &it) const
Box operator[] (const LayoutIterator &it) const
Box operator[] (const DataIterator &it) const
Box get (const LayoutIndex &it) const
Box get (const DataIterator &it) const
Box get (const LayoutIterator &it) const
unsigned int procID (const LayoutIndex &a_index) const
bool sameBoxes (const BoxLayout &a_layout) const
Checks whether this layout has the same boxes in the same order as a_layout.
int numBoxes (const int procID) const
Returns the number of boxes assigned to a given procID.
void printBalance () const
long long numCells () const
Return number of cells in all boxes of entire box layout.
unsigned int size () const
Returns the total number of boxes in the BoxLayout.
unsigned int index (const LayoutIndex &index) const
unsigned int lindex (const DataIndex &index) const
bool operator== (const BoxLayout &rhs) const
bool operator< (const BoxLayout &rhs) const
int refCount () const
bool eq (const BoxLayout &rhs) const
bool isClosed () const
bool isSorted () const
bool check (const LayoutIndex &index) const
bool compatible (const BoxLayout &a_rhs) const
DataIterator dataIterator () const
Parallel iterator.
TimedDataIterator timedDataIterator () const
LayoutIterator layoutIterator () const
Iterator that processes through ALL the boxes in a BoxLayout.
void print () const
void p () const
bool coarsenable (int refRatio) const
void growSide (int idir, int length, Side::LoHiSide a_sd)
void surroundingNodes ()
void enclosedCells ()
void coarsen (int a_ref)
void refine (int a_ref)
void grow (int a_growth)
void grow (IntVect a_growth)
void grow (int a_dir, int a_growth)
void shift (const IntVect &a_iv)
void shiftHalf (const IntVect &a_iv)
void adjCellSide (int a_dir, int a_len, Side::LoHiSide a_sd)
void operator &= (const Box &a_box)
void operator &= (const ProblemDomain &a_domain)
void setProcID (const LayoutIndex &a_index, unsigned int a_procID)
void sort ()
Protected Member Functions
void computeNeighbors ()
virtual void closeN (RefCountedPtr< std::vector< std::vector< std::pair< int, LayoutIndex > > > > neighbors)
virtual void closeNO ()
Protected Member Functions inherited from BoxLayout
void buildDataIndex ()
void checkDefine (const std::vector< Box > &a_boxes, const std::vector< int > &procIDs)
Protected Attributes
ProblemDomain m_physDomain
RefCountedPtr< std::vector< std::vector< std::pair< int, LayoutIndex > > > > m_neighbors
Protected Attributes inherited from BoxLayout
RefCountedPtr< std::vector< Entry > > m_boxes
RefCountedPtr< int > m_layout
RefCountedPtr< bool > m_closed
RefCountedPtr< bool > m_sorted
RefCountedPtr< DataIterator > m_dataIterator
RefCountedPtr< std::vector< LayoutIndex > > m_indicies
Friends
class Copier
class NeighborIterator
Neighbor functions
void adjCellLo (DisjointBoxLayout &a_output, const DisjointBoxLayout &a_input, int a_dir, int a_len)
void adjCellHi (DisjointBoxLayout &a_output, const DisjointBoxLayout &a_input, int a_dir, int a_len)
Friends inherited from BoxLayout
Modification functions
void coarsen (DisjointBoxLayout &output, const DisjointBoxLayout &input, int refinement)
void refine (DisjointBoxLayout &output, const DisjointBoxLayout &input, int refinement)
virtual void close ()
void setDomain (const ProblemDomain &a_domain)
virtual void deepCopy (const DisjointBoxLayout &a_source)
virtual void deepCopy (const BoxLayout &a_source)
virtual void deepCopy (const BoxLayout &a_source, const ProblemDomain &a_physDomain)
void degenerate (DisjointBoxLayout &a_to, const SliceSpec &a_ss, bool a_maintainProcAssign=false) const
Detailed Description
A BoxLayout that has a concept of disjointedness.
DisjointBoxLayout is-a BoxLayout that has a concept of disjointedness of the boxes. DisjointBoxLayout is only different from BoxLayout in that it has a method isDisjoint(). DisjointBoxLayouts also have a ProblemDomain member to ensure disjointness in the case of periodic boundary conditions, among other things.
Constructor & Destructor Documentation
DisjointBoxLayout() [1/3]
DisjointBoxLayout::DisjointBoxLayout ()
Construct BoxLayout with no boxes.
Referenced by define_pd(), refine_dbl(), and setDomain().
DisjointBoxLayout() [2/3]
DisjointBoxLayout::DisjointBoxLayout (const std::vector< Box > & a_boxes, const std::vector< int > & a_procIDs)
Construct from a std::vector of Boxes and optionally a std::vector of processor assignments. If the processor assignment std::vector is present, it must be either zero-length or the same length as the Box std::vector. On exit, the DisjointBoxLayout will be closed.
DisjointBoxLayout() [3/3]
DisjointBoxLayout::DisjointBoxLayout (const std::vector< Box > & a_boxes, const std::vector< int > & a_procIDs, const ProblemDomain & a_physDomain)
Construct from a std::vector of Boxes and optionally a std::vector of processor assignments. If the processor assignment std::vector is present, it must be either zero-length or the same length as the Box std::vector. On exit, the DisjointBoxLayout will be closed.
~DisjointBoxLayout()
virtual DisjointBoxLayout::~DisjointBoxLayout () inline virtual
Ref-counted destruction. Once the last reference to the implementation of this class is destroyed, the data members are cleaned up.
References BoxLayout::define(), defineAndLoadBalance(), and numPointsThisProc().
Member Function Documentation
numPointsThisProc()
unsigned long long int DisjointBoxLayout::numPointsThisProc () const
Referenced by ~DisjointBoxLayout().
define() [1/4]
virtual void DisjointBoxLayout::define (const std::vector< Box > & a_boxes, const std::vector< int > & a_procIDs) virtual
Define this DisjointBoxLayout from a std::vector of Boxes. This is a wrapper for a call to BoxLayout::define, required because DisjointBoxLayout::define is overloaded and the compiler will not look into the base class for name resolution.
Reimplemented from BoxLayout.
defineAndLoadBalance() [1/2]
void DisjointBoxLayout::defineAndLoadBalance (const std::vector< Box > & a_boxes, std::vector< int > * a_procIDs)
Like the define() that takes the same two arguments, except this one also initializes a_procIDs if it's not NULL. In that case, the passed-in a_procIDs should point to a std::vector of size 0.
Referenced by ~DisjointBoxLayout().
defineAndLoadBalance() [2/2]
void DisjointBoxLayout::defineAndLoadBalance (const std::vector< Box > & a_boxes, std::vector< int > * a_procIDs, const ProblemDomain & a_physDomain)
Like the define() that takes the same two arguments, except this one also initializes a_procIDs if it's not NULL. In that case, the passed-in a_procIDs should point to a std::vector of size 0.
define() [2/4]
virtual void DisjointBoxLayout::define (const BoxLayout & a_layout) virtual
Shallow define. Only way to promote a BoxLayout. If BoxLayout has been closed, then this method checks isDisjoint and throws an error if not disjoint. If a_layout is disjoint, then this object becomes a closed DisjointBoxLayout object.
define() [3/4]
virtual void DisjointBoxLayout::define (const BoxLayout & a_layout, const ProblemDomain & a_physDomain) virtual
Shallow define. Only way to promote a BoxLayout. If BoxLayout has been closed, then this method checks isDisjoint and throws an error if not disjoint. If a_layout is disjoint, then this object becomes a closed DisjointBoxLayout object. If BoxLayout has been closed, and is sorted, the neighbour iterator is rebuilt (now with knowledge of the problem domain).
define() [4/4]
virtual void DisjointBoxLayout::define (const std::vector< Box > & a_boxes, const std::vector< int > & a_procIDs, const ProblemDomain & a_physDomain) virtual
Define this DisjointBoxLayout from a std::vector of Boxes. This is a wrapper for a call to BoxLayout::define, required because DisjointBoxLayout::define is overloaded and the compiler will not look into the base class for name resolution.
define_pd()
virtual void DisjointBoxLayout::define_pd (const std::vector< Box > & a_boxes, const std::vector< int > & a_procIDs, const ProblemDomain & a_physDomain) inline virtual
Define this DisjointBoxLayout from a std::vector of Boxes. Same as define.
References checkDomains(), checkPeriodic(), BoxLayout::close(), BoxLayout::define(), DisjointBoxLayout(), and isDisjoint().
isDisjoint()
bool DisjointBoxLayout::isDisjoint () const
Returns true if this object contains a disjoint union of Boxes.
The Disjoint testing algorithm assumes that the boxes are CELL-Centered boxes. We can expand the algorithm when someone needs it. bvs
Referenced by define_pd().
checkPeriodic()
bool DisjointBoxLayout::checkPeriodic (const ProblemDomain & a_domain) const
Checks to see that problem domains are compatible. To be compatible:
a_domain and the ProblemDomain in this DisjointBoxLayout must have the same periodicity.
The ProblemDomains must be periodic in the same dimensions.
In all periodic directions, the period must be the same.
There are no checks in non-periodic directions, since DisjointBoxLayouts don't care about physical domains except in the periodic case.
Referenced by define_pd().
checkDomains()
bool DisjointBoxLayout::checkDomains (const DisjointBoxLayout & a_dbl) const
Performs problem domain check when we don't have direct access to a problemDomain.
Returns true if this and a_dbl have compatible ProblemDomains.
Referenced by define_pd().
close()
virtual void DisjointBoxLayout::close () virtual
Mark this DisjointBoxLayout as complete and unchangeable.
Reimplemented from BoxLayout.
setDomain()
void DisjointBoxLayout::setDomain (const ProblemDomain & a_domain) inline
Set ProblemDomain. Useful when using addBox() and trying to use closeNoSort()
References adjCellHi(), adjCellLo(), BoxLayout::coarsen, BoxLayout::deepCopy(), degenerate(), DisjointBoxLayout(), m_physDomain, physDomain(), and BoxLayout::refine().
deepCopy() [1/3]
virtual void DisjointBoxLayout::deepCopy (const DisjointBoxLayout & a_source) virtual
Create new open DisjointBoxLayout with copied data.
Doesn't check for disjointness, since a_source is already guaranteed to be disjoint. Also copies problem domain info.
deepCopy() [2/3]
virtual void DisjointBoxLayout::deepCopy (const BoxLayout & a_source) virtual
Create new open DisjointBoxLayout with copied data.
Checks that the source BoxLayout isDisjoint, throws an error if it is not. Otherwise, same as BoxLayout::deepCopy.
Reimplemented from BoxLayout.
deepCopy() [3/3]
virtual void DisjointBoxLayout::deepCopy (const BoxLayout & a_source, const ProblemDomain & a_physDomain) virtual
Create new open DisjointBoxLayout with copied data.
Checks that the source BoxLayout isDisjoint, throws an error if it is not. Otherwise, same as BoxLayout::deepCopy.
degenerate()
void DisjointBoxLayout::degenerate (DisjointBoxLayout & a_to, const SliceSpec & a_ss, bool a_maintainProcAssign = false) const
Makes a_to a one-cell-thick version of *this – sliced at a_ss.position along the a_ss.direction'th axis. If a_ss.position is outside the range of *this, that's a fatal error. If a_maintainProcAssign = true, maintain processor assignments in the process (even if it breaks load balancing)
Referenced by setDomain().
physDomain()
const ProblemDomain& DisjointBoxLayout::physDomain () const
Referenced by getDomain(), and setDomain().
getDomain()
const Box& DisjointBoxLayout::getDomain () const inline
References BoxLayout::closeNoSort(), ProblemDomain::domainBox(), and physDomain().
closeNoSort()
virtual void DisjointBoxLayout::closeNoSort () virtual
Reimplemented from BoxLayout.
computeNeighbors()
void DisjointBoxLayout::computeNeighbors () protected
closeN()
virtual void DisjointBoxLayout::closeN (RefCountedPtr< std::vector< std::vector< std::pair< int, LayoutIndex > > > > neighbors) protected virtual
closeNO()
virtual void DisjointBoxLayout::closeNO () protected virtual
Friends And Related Function Documentation
Copier
friend class Copier friend
NeighborIterator
friend class NeighborIterator friend
coarsen
void coarsen (DisjointBoxLayout & output, const DisjointBoxLayout & input, int refinement) friend
Coarsen a DisjointBoxLayout:
output must be open
input must be closed
refinement must be a positive non-zero integer
output and input do not share an implementation.
output is first deepCopy'ed from input, then coarsen(refinement) is called on each box of output.
output returns from this function closed.
LayoutIterators and DataIterators from input and output can be used interchangeably.
refine
void refine (DisjointBoxLayout & output, const DisjointBoxLayout & input, int refinement) friend
Refine a DisjointBoxLayout:
output must be open
input must be closed
refinement must be a positive non-zero integer
output and input do not share an implementation.
output is first deepCopy'ed from input, then refine(refinement) is called on each box of output.
output returns from this function closed.
LayoutIterators and DataIterators from input and output can be used interchangeably.
adjCellLo
void adjCellLo (DisjointBoxLayout & a_output, const DisjointBoxLayout & a_input, int a_dir, int a_len) friend
Returns the set of boxes which you get from calling Box::adjCellLo on each box in input. Output must be open, is closed upon exit from this function. A negative length results in the set of boxes of width a_len on the low side of, but inside the original boxes.
adjCellHi
void adjCellHi (DisjointBoxLayout & a_output, const DisjointBoxLayout & a_input, int a_dir, int a_len) friend
Returns the set of boxes which result from calling Box::adjCellHi on each box in input. Output must be open, will be closed upon exiting this function. A negative length results in the set of boxes of width a_len on the low side of, but inside the original boxes.
Member Data Documentation
m_physDomain
ProblemDomain DisjointBoxLayout::m_physDomain protected
Referenced by setDomain().
m_neighbors
RefCountedPtr<std::vector<std::vector<std::pair<int, LayoutIndex> > > > DisjointBoxLayout::m_neighbors protected
The documentation for this class was generated from the following file:
Chombo_DisjointBoxLayout.H