Chombo_4: EBLevelFluxData< NUMCOMPS > Class Template Reference
EBLevelFluxData< NUMCOMPS > Class Template Reference
#include <Chombo_EBLevelFluxData.H>
Public Types
typedef CH4_Data_Choreography::DistributedData< EBFluxData< Real, NUMCOMPS > > devidistrib_t
typedef CH4_Data_Choreography::DistributedData< EBHostFluxData< Real, NUMCOMPS > > hostdistrib_t
typedef GraphConstructorFactory< EBFluxData< Real, NUMCOMPS > > devifactory_t
typedef GraphConstructorFactory< EBHostFluxData< Real, NUMCOMPS > > hostfactory_t
typedef CH4_Data_Choreography::DistributedData< EBGraph > graph_distrib_t
Public Member Functions
EBLevelFluxData ()
EBLevelFluxData (const DisjointBoxLayout &a_dp, const IntVect &a_ghost, shared_ptr< graph_distrib_t > a_graphs)
virtual ~EBLevelFluxData ()
virtual void define (const DisjointBoxLayout &a_dp, const IntVect &a_ghost, shared_ptr< graph_distrib_t > a_graphs)
template<unsigned int srcComp>
void define (EBLevelFluxData< srcComp > &a_input, unsigned int a_comp, shared_ptr< graph_distrib_t > a_graphs)
aliasing define
void setVal (Real a_value)
EBLevelFluxData & operator+= (const EBLevelFluxData &a_input)
EBLevelFluxData & operator-= (const EBLevelFluxData &a_input)
Real maxNorm (int a_icomp) const
void copyTo (EBLevelFluxData< NUMCOMPS > &a_dst, bool a_printStuff=false) const
all the cool kids use this copyTo interface
virtual void exchange (bool a_printStuff=false)
The hip new slick exchange interface. Use this one.
Public Member Functions inherited from CH4_Data_Choreography::DistributedData< EBFluxData< Real, NUMCOMPS > >
DistributedData ()
DistributedData (const Chombo4::DisjointBoxLayout &a_grids, const Chombo4::IntVect &a_ghost, const Chombo4::DataFactory< EBFluxData< Real, NUMCOMPS > > &a_factory, bool a_enableStaticCache=false)
void define (const Chombo4::DisjointBoxLayout &a_grids, const Chombo4::IntVect &a_ghost, const Chombo4::DataFactory< EBFluxData< Real, NUMCOMPS > > &a_factory, bool a_enableStaticCache=false)
datafactory has an ncomps argument that shall be ignored here
Chombo4::DataIterator dataIterator () const
old leveldata functionality that got used a LOT
virtual ~DistributedData ()
EBFluxData< Real, NUMCOMPS > & operator[] (const Chombo4::DataIndex &a_dit)
const EBFluxData< Real, NUMCOMPS > & operator[] (const Chombo4::DataIndex &a_dit) const
void exchange (bool a_printStuff=false)
void copyTo (DistributedData &a_dst, bool a_printStuff=false)
IntVect ghostVect () const
Chombo4::DisjointBoxLayout disjointBoxLayout () const
void printGrids () const
Static Public Member Functions
static void copyToHost (hostdistrib_t &a_hostDat, const devidistrib_t &a_deviDat)
static void copyToHost (EBHostFluxData< Real, NUMCOMPS > &a_hostfab, const EBFluxData< Real, NUMCOMPS > &a_devifab)
static void copyToDevice (devidistrib_t &a_deviDat, const hostdistrib_t &a_hostDat)
static void copyToDevice (const EBHostFluxData< Real, NUMCOMPS > &a_hostfab, EBFluxData< Real, NUMCOMPS > &a_devifab)
Private Attributes
shared_ptr< graph_distrib_t > m_graphs
Member Typedef Documentation
devidistrib_t
template<int NUMCOMPS> typedef CH4_Data_Choreography::DistributedData< EBFluxData<Real, NUMCOMPS> > EBLevelFluxData< NUMCOMPS >::devidistrib_t
hostdistrib_t
template<int NUMCOMPS> typedef CH4_Data_Choreography::DistributedData<EBHostFluxData<Real, NUMCOMPS> > EBLevelFluxData< NUMCOMPS >::hostdistrib_t
devifactory_t
template<int NUMCOMPS> typedef GraphConstructorFactory< EBFluxData<Real, NUMCOMPS> > EBLevelFluxData< NUMCOMPS >::devifactory_t
hostfactory_t
template<int NUMCOMPS> typedef GraphConstructorFactory<EBHostFluxData<Real, NUMCOMPS> > EBLevelFluxData< NUMCOMPS >::hostfactory_t
graph_distrib_t
template<int NUMCOMPS> typedef CH4_Data_Choreography::DistributedData<EBGraph> EBLevelFluxData< NUMCOMPS >::graph_distrib_t
Constructor & Destructor Documentation
EBLevelFluxData() [1/2]
template<int NUMCOMPS> EBLevelFluxData< NUMCOMPS >::EBLevelFluxData () inline
EBLevelFluxData() [2/2]
template<int NUMCOMPS> EBLevelFluxData< NUMCOMPS >::EBLevelFluxData (const DisjointBoxLayout & a_dp, const IntVect & a_ghost, shared_ptr< graph_distrib_t > a_graphs) inline
~EBLevelFluxData()
template<int NUMCOMPS> virtual EBLevelFluxData< NUMCOMPS >::~EBLevelFluxData () inline virtual
Member Function Documentation
define() [1/2]
template<int NUMCOMPS> virtual void EBLevelFluxData< NUMCOMPS >::define (const DisjointBoxLayout & a_dp, const IntVect & a_ghost, shared_ptr< graph_distrib_t > a_graphs) inline virtual
define() [2/2]
template<int NUMCOMPS> template<unsigned int srcComp> void EBLevelFluxData< NUMCOMPS >::define (EBLevelFluxData< srcComp > & a_input, unsigned int a_comp, shared_ptr< graph_distrib_t > a_graphs) inline
aliasing define
References CH4_Data_Choreography::DistributedData< EBFluxData< Real, NUMCOMPS > >::disjointBoxLayout(), and CH4_Data_Choreography::DistributedData< EBFluxData< Real, NUMCOMPS > >::ghostVect().
setVal()
template<int NUMCOMPS> void EBLevelFluxData< NUMCOMPS >::setVal (Real a_value) inline
operator+=()
template<int NUMCOMPS> EBLevelFluxData& EBLevelFluxData< NUMCOMPS >::operator+= (const EBLevelFluxData< NUMCOMPS > & a_input) inline
operator-=()
template<int NUMCOMPS> EBLevelFluxData& EBLevelFluxData< NUMCOMPS >::operator-= (const EBLevelFluxData< NUMCOMPS > & a_input) inline
maxNorm()
template<int NUMCOMPS> Real EBLevelFluxData< NUMCOMPS >::maxNorm (int a_icomp) const inline
References CH_TIME, MayDay::Error(), and MPI_CH_REAL.
copyTo()
template<int NUMCOMPS> void EBLevelFluxData< NUMCOMPS >::copyTo (EBLevelFluxData< NUMCOMPS > & a_dst, bool a_printStuff = false) const inline
all the cool kids use this copyTo interface
copy over box intersections
References CH4_Data_Choreography::DistributedData< fabtype_t >::copyTo(), CH4_Data_Choreography::DistributedData< EBFluxData< Real, NUMCOMPS > >::disjointBoxLayout(), CH4_Data_Choreography::DistributedData< EBFluxData< Real, NUMCOMPS > >::ghostVect(), and EBLevelFluxData< NUMCOMPS >::m_graphs.
exchange()
template<int NUMCOMPS> virtual void EBLevelFluxData< NUMCOMPS >::exchange (bool a_printStuff = false) inline virtual
The hip new slick exchange interface. Use this one.
References CH4_Data_Choreography::DistributedData< fabtype_t >::exchange(), and pout().
copyToHost() [1/2]
template<int NUMCOMPS> static void EBLevelFluxData< NUMCOMPS >::copyToHost (hostdistrib_t & a_hostDat, const devidistrib_t & a_deviDat) inline static
References CH4_Data_Choreography::DistributedData< fabtype_t >::dataIterator().
copyToHost() [2/2]
template<int NUMCOMPS> static void EBLevelFluxData< NUMCOMPS >::copyToHost (EBHostFluxData< Real, NUMCOMPS > & a_hostfab, const EBFluxData< Real, NUMCOMPS > & a_devifab) inline static
References Proto::EBHostFluxData< data_t, ncomp >::dataInfo(), and Proto::EBFluxData< data_t, ncomp >::dataInfo().
copyToDevice() [1/2]
template<int NUMCOMPS> static void EBLevelFluxData< NUMCOMPS >::copyToDevice (devidistrib_t & a_deviDat, const hostdistrib_t & a_hostDat) inline static
References CH4_Data_Choreography::DistributedData< fabtype_t >::dataIterator().
copyToDevice() [2/2]
template<int NUMCOMPS> static void EBLevelFluxData< NUMCOMPS >::copyToDevice (const EBHostFluxData< Real, NUMCOMPS > & a_hostfab, EBFluxData< Real, NUMCOMPS > & a_devifab) inline static
References Proto::EBHostFluxData< data_t, ncomp >::dataInfo(), and Proto::EBFluxData< data_t, ncomp >::dataInfo().
Member Data Documentation
m_graphs
template<int NUMCOMPS> shared_ptr<graph_distrib_t> EBLevelFluxData< NUMCOMPS >::m_graphs private
Referenced by EBLevelFluxData< NUMCOMPS >::copyTo().
The documentation for this class was generated from the following file:
Chombo_EBLevelFluxData.H