Chombo_4: Proto::LocalStencil< cent, data_t > Class Template Reference
Proto::LocalStencil< cent, data_t > Class Template Reference
replacement for Chombo's vofstencil and facestencil
#include <Proto_AggStencil.H>
Classes
struct entry_t
Public Member Functions
data_t sum () const
void setBetaWeight (data_t a_value)
LocalStencil ()
~LocalStencil ()
void clear ()
int size () const
void add (const entry_t &a_entry)
this api should be stable
void add (const EBIndex< cent > a_vof, const data_t &a_weight)
this might change (if a variable number argument is added, for example)
LocalStencil< cent, data_t > & operator+= (const LocalStencil< cent, data_t > &a_input)
add full stencil
bool getValueAtVoF (data_t &a_value, const EBIndex< cent > a_vof)
void operator*= (const data_t &a_scaling)
scaling operator
void print () const
void printSum () const
Public Attributes
vector< entry_t > m_entries
data_t m_betaWeight
data_t m_ebbcWeight
bool m_betaWeightSet
Detailed Description
template<CENTERING cent, typename data_t>
class Proto::LocalStencil< cent, data_t >
replacement for Chombo's vofstencil and facestencil
Constructor & Destructor Documentation
LocalStencil()
template<CENTERING cent, typename data_t> Proto::LocalStencil< cent, data_t >::LocalStencil () inline
~LocalStencil()
template<CENTERING cent, typename data_t> Proto::LocalStencil< cent, data_t >::~LocalStencil () inline
Member Function Documentation
sum()
template<CENTERING cent, typename data_t> data_t Proto::LocalStencil< cent, data_t >::sum () const inline
setBetaWeight()
template<CENTERING cent, typename data_t> void Proto::LocalStencil< cent, data_t >::setBetaWeight (data_t a_value) inline
Referenced by Proto::SecondOrderStencil< order >::get2ndOrderDivFStencil(), and Proto::EBStencilArchive< CELL, CELL, order, double >::getRegularPoissonBoundaryStencil().
clear()
template<CENTERING cent, typename data_t> void Proto::LocalStencil< cent, data_t >::clear () inline
Referenced by Proto::SecondOrderStencil< order >::get2ndOrderDivFStencil(), Proto::Base2ndOrderFlux< facecent, order >::getCentroidStencil(), Proto::DirichletEBFlux< order >::getEBFluxStencil(), Proto::Poisson2ndOrder< facecent, order >::getFaceCenteredFluxStencil(), Proto::Base2ndOrderFlux< facecent, order >::getFaceInterpStencil(), and Proto::EBStencilArchive< CELL, CELL, order, double >::getRegularPoissonBoundaryStencil().
size()
template<CENTERING cent, typename data_t> int Proto::LocalStencil< cent, data_t >::size () const inline
Referenced by Proto::AggStencil< srcCenter, dstCenter, data_t >::AggStencil(), Proto::Base2ndOrderFlux< facecent, order >::getCentroidStencil(), Proto::EBStencilArchive< CELL, CELL, order, double >::getRedistributionStencil(), and Proto::LocalStencil< cent, data_t >::operator+=().
add() [1/2]
template<CENTERING cent, typename data_t> void Proto::LocalStencil< cent, data_t >::add (const entry_t & a_entry) inline
this api should be stable
References Proto::LocalStencil< cent, data_t >::entry_t::m_vof, and Proto::LocalStencil< cent, data_t >::entry_t::m_weight.
Referenced by Proto::Base2ndOrderFlux< facecent, order >::getCentroidStencil(), Proto::EBStencilArchive< fcent, fcent, order, double >::getDomainExtrapolationStencil(), Proto::DirichletEBFlux< order >::getEBFluxStencil(), Proto::Poisson2ndOrder< facecent, order >::getFaceCenteredFluxStencil(), Proto::Base2ndOrderFlux< facecent, order >::getFaceInterpStencil(), Proto::EBStencilArchive< CELL, CELL, order, double >::getRedistributionStencil(), and Proto::EBStencilArchive< CELL, CELL, order, double >::getRegularPoissonBoundaryStencil().
add() [2/2]
template<CENTERING cent, typename data_t> void Proto::LocalStencil< cent, data_t >::add (const EBIndex< cent > a_vof, const data_t & a_weight) inline
this might change (if a variable number argument is added, for example)
operator+=()
template<CENTERING cent, typename data_t> LocalStencil<cent, data_t>& Proto::LocalStencil< cent, data_t >::operator+= (const LocalStencil< cent, data_t > & a_input) inline
add full stencil
References Proto::LocalStencil< cent, data_t >::m_entries, and Proto::LocalStencil< cent, data_t >::size().
getValueAtVoF()
template<CENTERING cent, typename data_t> bool Proto::LocalStencil< cent, data_t >::getValueAtVoF (data_t & a_value, const EBIndex< cent > a_vof) inline
Referenced by Proto::SecondOrderStencil< order >::get2ndOrderDivFStencil().
operator*=()
template<CENTERING cent, typename data_t> void Proto::LocalStencil< cent, data_t >::operator*= (const data_t & a_scaling) inline
scaling operator
print()
template<CENTERING cent, typename data_t> void Proto::LocalStencil< cent, data_t >::print () const inline
References pout().
printSum()
template<CENTERING cent, typename data_t> void Proto::LocalStencil< cent, data_t >::printSum () const inline
References pout().
Member Data Documentation
m_entries
template<CENTERING cent, typename data_t> vector<entry_t> Proto::LocalStencil< cent, data_t >::m_entries
Referenced by Proto::AggStencil< srcCenter, dstCenter, data_t >::AggStencil(), Proto::Base2ndOrderFlux< facecent, order >::getCentroidStencil(), Proto::EBStencilArchive< CELL, CELL, order, double >::getRedistributionStencil(), and Proto::LocalStencil< cent, data_t >::operator+=().
m_betaWeight
template<CENTERING cent, typename data_t> data_t Proto::LocalStencil< cent, data_t >::m_betaWeight
Referenced by Proto::EBStencil< order, data_t, srcCenter, dstCenter >::computeDiagonalWeights().
m_ebbcWeight
template<CENTERING cent, typename data_t> data_t Proto::LocalStencil< cent, data_t >::m_ebbcWeight
m_betaWeightSet
template<CENTERING cent, typename data_t> bool Proto::LocalStencil< cent, data_t >::m_betaWeightSet
Referenced by Proto::EBStencil< order, data_t, srcCenter, dstCenter >::computeDiagonalWeights().
The documentation for this class was generated from the following file:
Proto_AggStencil.H