Chombo_4: Proto::EBStencil< order, data_t, srcCenter, dstCenter > Class Template Reference
Proto::EBStencil< order, data_t, srcCenter, dstCenter > Class Template Reference
class to encapsulate evaluating a stencil for an embedded boundary calculation
#include <Proto_EBStencil.H>
Public Types
typedef EBStencilArchive< srcCenter, dstCenter, order, data_t > archive_t
typedef EBStencilHO< srcCenter, dstCenter, order, data_t > ho_t
typedef IndexedMoments< DIM, order > IndMomDIM
typedef IndexedMoments< DIM-1, order > IndMomSDMinOne
typedef MomentIterator< DIM, order > MomItDIM
typedef MomentIterator< DIM-1, order > MomItSDMinOne
typedef HostIrregData< CELL, IndMomDIM, 1 > VoluData
typedef HostIrregData< BOUNDARY, IndMomDIM, 1 > EBFaData
typedef HostIrregData< XFACE, IndMomSDMinOne, 1 > XFacData
typedef HostIrregData< YFACE, IndMomSDMinOne, 1 > YFacData
typedef HostIrregData< ZFACE, IndMomSDMinOne, 1 > ZFacData
typedef HostIrregData< CELL, IndMomDIM, 1 > EBNorData
Public Member Functions
EBStencil (const vector< EBIndex< dstCenter > > &a_dstVoFs, const vector< LocalStencil< srcCenter, data_t > > &a_stencil, const EBGraph &a_srcGraph, const EBGraph &a_dstGraph, const Box &a_srcValid, const Box &a_dstValid, const Box &a_srcDomain, const Box &a_dstDomain, const Point &a_srcGhost, const Point &a_dstGhost, bool a_needDiagonalWeights)
Constructor for algorithm developers.
EBStencil (string a_stencilName, string a_domainBCName[2 *DIM], string a_ebbcName, const Box &a_srcValid, const Box &a_dstValid, const Box &a_srcDomain, const Box &a_dstDomain, const Point &a_srcGhost, const Point &a_dstGhost, const EBGraph &a_srcGraph, const EBGraph &a_dstGraph, const VoluData &a_voludata, const EBFaData &a_ebfadata, const XFacData &a_xfacdata, const YFacData &a_yfacdata, const ZFacData &a_zfacdata, double a_dx, bool a_periodiconly, bool a_needDiagonalWeights, Point a_dstGrown)
Constructor for named, archived stencils.
EBStencil (string a_stencilName, string a_domainBCName[2 *DIM], string a_ebbcName, const Box &a_srcValid, const Box &a_dstValid, const Box &a_srcDomain, const Box &a_dstDomain, const Point &a_srcGhost, const Point &a_dstGhost, const EBGraph &a_srcGraph, const EBGraph &a_dstGraph, const VoluData &a_voludata, const EBFaData &a_ebfadata, const XFacData &a_xfacdata, const YFacData &a_yfacdata, const ZFacData &a_zfacdata, const EBNorData &a_ebnorxdata, const EBNorData &a_ebnorydata, const EBNorData &a_ebnorzdata, double a_dx, bool periodic_domain_bcs_only, bool a_needDiagonalWeights=false, Point a_growDst=Point::Zeros())
internal constructor
~EBStencil ()
void apply (EBBoxData< dstCenter, data_t, 1 > &a_dst, const EBBoxData< srcCenter, data_t, 1 > &a_src, bool a_initToZero=true, double a_scale=1.0, bool a_printStuff=false) const
void applyITZ (EBBoxData< dstCenter, data_t, 1 > &a_dst, const EBBoxData< srcCenter, data_t, 1 > &a_src, double a_scale=1.0, bool a_printStuff=false) const
shared_ptr< EBBoxData< dstCenter, data_t, 1 > > getDiagonalWeights () const
get the diagonal weights of the stencil
Protected Member Functions
void computeDiagonalWeights (const vector< EBIndex< dstCenter > > &a_dstVoFs, const vector< LocalStencil< srcCenter, data_t > > &a_stencil, const EBGraph &a_graph, const Box &a_validBox, const Point &a_dstGrown)
Protected Attributes
bool m_hasDomainBCs
bool m_bcsOnly
bool m_irregOnly
Stencil< double > m_regStencilInterior
these
vector< Stencil< double > > m_regStencilBCS [2 *DIM]
vector< Box > m_BCApplyBoxes [2 *DIM]
bool m_periodic_domain_bcs_only
Box m_regApplyBox
shared_ptr< AggStencil< srcCenter, dstCenter, data_t > > m_irregStencil
shared_ptr< EBBoxData< dstCenter, data_t, 1 > > m_diagonalWeights
Private Member Functions
EBStencil ()
EBStencil (const EBStencil< order, data_t, srcCenter, dstCenter > &a_inp)
void operator= (const EBStencil< order, data_t, srcCenter, dstCenter > &a_inp)
Detailed Description
template<int order, typename data_t, CENTERING srcCenter, CENTERING dstCenter>
class Proto::EBStencil< order, data_t, srcCenter, dstCenter >
class to encapsulate evaluating a stencil for an embedded boundary calculation
This is Proto::Stencil generalized to embedded boundaries. One does not generate these directly, you get it out of your EBDictionary once you have registered it. The only part of this API that the user should use are EBStencil::apply and EBStencil::getDiagonalWeights
Member Typedef Documentation
archive_t
template<int order, typename data_t, CENTERING srcCenter, CENTERING dstCenter> typedef EBStencilArchive<srcCenter, dstCenter, order, data_t> Proto::EBStencil< order, data_t, srcCenter, dstCenter >::archive_t
ho_t
template<int order, typename data_t, CENTERING srcCenter, CENTERING dstCenter> typedef EBStencilHO<srcCenter, dstCenter, order, data_t> Proto::EBStencil< order, data_t, srcCenter, dstCenter >::ho_t
IndMomDIM
template<int order, typename data_t, CENTERING srcCenter, CENTERING dstCenter> typedef IndexedMoments<DIM , order> Proto::EBStencil< order, data_t, srcCenter, dstCenter >::IndMomDIM
IndMomSDMinOne
template<int order, typename data_t, CENTERING srcCenter, CENTERING dstCenter> typedef IndexedMoments<DIM-1, order> Proto::EBStencil< order, data_t, srcCenter, dstCenter >::IndMomSDMinOne
MomItDIM
template<int order, typename data_t, CENTERING srcCenter, CENTERING dstCenter> typedef MomentIterator<DIM , order> Proto::EBStencil< order, data_t, srcCenter, dstCenter >::MomItDIM
MomItSDMinOne
template<int order, typename data_t, CENTERING srcCenter, CENTERING dstCenter> typedef MomentIterator<DIM-1, order> Proto::EBStencil< order, data_t, srcCenter, dstCenter >::MomItSDMinOne
VoluData
template<int order, typename data_t, CENTERING srcCenter, CENTERING dstCenter> typedef HostIrregData<CELL , IndMomDIM , 1> Proto::EBStencil< order, data_t, srcCenter, dstCenter >::VoluData
EBFaData
template<int order, typename data_t, CENTERING srcCenter, CENTERING dstCenter> typedef HostIrregData<BOUNDARY, IndMomDIM , 1> Proto::EBStencil< order, data_t, srcCenter, dstCenter >::EBFaData
XFacData
template<int order, typename data_t, CENTERING srcCenter, CENTERING dstCenter> typedef HostIrregData<XFACE, IndMomSDMinOne, 1> Proto::EBStencil< order, data_t, srcCenter, dstCenter >::XFacData
YFacData
template<int order, typename data_t, CENTERING srcCenter, CENTERING dstCenter> typedef HostIrregData<YFACE, IndMomSDMinOne, 1> Proto::EBStencil< order, data_t, srcCenter, dstCenter >::YFacData
ZFacData
template<int order, typename data_t, CENTERING srcCenter, CENTERING dstCenter> typedef HostIrregData<ZFACE, IndMomSDMinOne, 1> Proto::EBStencil< order, data_t, srcCenter, dstCenter >::ZFacData
EBNorData
template<int order, typename data_t, CENTERING srcCenter, CENTERING dstCenter> typedef HostIrregData<CELL , IndMomDIM , 1> Proto::EBStencil< order, data_t, srcCenter, dstCenter >::EBNorData
Constructor & Destructor Documentation
EBStencil() [1/5]
template<int order, typename data_t , CENTERING srcCenter, CENTERING dstCenter> Proto::EBStencil< order, data_t, srcCenter, dstCenter >::EBStencil (const vector< EBIndex< dstCenter > > & a_dstVoFs, const vector< LocalStencil< srcCenter, data_t > > & a_stencil, const EBGraph & a_srcGraph, const EBGraph & a_dstGraph, const Box & a_srcValid, const Box & a_dstValid, const Box & a_srcDomain, const Box & a_dstDomain, const Point & a_srcGhost, const Point & a_dstGhost, bool a_needDiagonalWeights)
Constructor for algorithm developers.
If you are designing a stencil and want it executed via EBStencil, use this constructor. Users wishing to just used named, existing stencils should use the other constructor. In both cases, the user really should get her EBStencil through EBDictionary::registerStencil (which calls this constructor or the other constructor if needed). EBDictionary maintains a cache of registered stencils so they never have to be defined twice.
Only the AggStencil bit will be executed so you have to create a stencil for every point in the box (not just the cut cells)
regular stencil gets applied in the interior of the domain. The aggstencil overwrites it near the EB. The domainBC stencils fill ghost cells outside the domain. The vector length needs to be the same as the one-sided span of the stencil.
References Proto::EBStencil< order, data_t, srcCenter, dstCenter >::EBStencil().
EBStencil() [2/5]
template<int order, typename data_t , CENTERING srcCenter, CENTERING dstCenter> Proto::EBStencil< order, data_t, srcCenter, dstCenter >::EBStencil (string a_stencilName, string a_domainBCName[2 *DIM], string a_ebbcName, const Box & a_srcValid, const Box & a_dstValid, const Box & a_srcDomain, const Box & a_dstDomain, const Point & a_srcGhost, const Point & a_dstGhost, const EBGraph & a_srcGraph, const EBGraph & a_dstGraph, const VoluData & a_voludata, const EBFaData & a_ebfadata, const XFacData & a_xfacdata, const YFacData & a_yfacdata, const ZFacData & a_zfacdata, double a_dx, bool a_periodiconly, bool a_needDiagonalWeights, Point a_dstGrown)
Constructor for named, archived stencils.
Users wishing to just used named, existing stencils should use this constructor. This just asks the EBStencilArchive for the stencil, so if the stencil is not there, it will be a run time error. If you are designing a stencil and want it executed via EBStencil, use the other constructor so you can actually just specify what it is. In both cases, the user really should get her EBStencil through EBDictionary::registerStencil (which calls this constructor or the other constructor if needed). EBDictionary maintains a cache of registered stencils so they never have to be defined twice.
References Proto::EBStencil< order, data_t, srcCenter, dstCenter >::computeDiagonalWeights().
EBStencil() [3/5]
template<int order, typename data_t, CENTERING srcCenter, CENTERING dstCenter> Proto::EBStencil< order, data_t, srcCenter, dstCenter >::EBStencil (string a_stencilName, string a_domainBCName[2 *DIM], string a_ebbcName, const Box & a_srcValid, const Box & a_dstValid, const Box & a_srcDomain, const Box & a_dstDomain, const Point & a_srcGhost, const Point & a_dstGhost, const EBGraph & a_srcGraph, const EBGraph & a_dstGraph, const VoluData & a_voludata, const EBFaData & a_ebfadata, const XFacData & a_xfacdata, const YFacData & a_yfacdata, const ZFacData & a_zfacdata, const EBNorData & a_ebnorxdata, const EBNorData & a_ebnorydata, const EBNorData & a_ebnorzdata, double a_dx, bool periodic_domain_bcs_only, bool a_needDiagonalWeights = false, Point a_growDst = Point::Zeros())
internal constructor
This constructor is specifically for Weighted Least Squares stencils
~EBStencil()
template<int order, typename data_t, CENTERING srcCenter, CENTERING dstCenter> Proto::EBStencil< order, data_t, srcCenter, dstCenter >::~EBStencil () inline
References Proto::EBStencil< order, data_t, srcCenter, dstCenter >::apply(), and Proto::EBStencil< order, data_t, srcCenter, dstCenter >::applyITZ().
EBStencil() [4/5]
template<int order, typename data_t, CENTERING srcCenter, CENTERING dstCenter> Proto::EBStencil< order, data_t, srcCenter, dstCenter >::EBStencil () private
Referenced by Proto::EBStencil< order, data_t, srcCenter, dstCenter >::EBStencil().
EBStencil() [5/5]
template<int order, typename data_t, CENTERING srcCenter, CENTERING dstCenter> Proto::EBStencil< order, data_t, srcCenter, dstCenter >::EBStencil (const EBStencil< order, data_t, srcCenter, dstCenter > & a_inp) private
Member Function Documentation
apply()
template<int order, typename data_t , CENTERING srcCenter, CENTERING dstCenter> void Proto::EBStencil< order, data_t, srcCenter, dstCenter >::apply (EBBoxData< dstCenter, data_t, 1 > & a_dst, const EBBoxData< srcCenter, data_t, 1 > & a_src, bool a_initToZero = true, double a_scale = 1.0, bool a_printStuff = false) const inline
regular stencil gets applied in the interior of the domain. The aggstencil overwrites it near the EB. The domainBC stencils fill ghost cells outside the domain. The vector length needs to be the same as the one-sided span of the stencil.
Boundary conditions are applied if m_hasDomainBCs has been set to zero. See how complicated this is? Use EBDictionary.
References Proto::EBBoxData< cent, data_t, ncomp >::ebgraph(), Proto::EBBoxData< cent, data_t, ncomp >::inputBox(), and Proto::EBBoxData< cent, data_t, ncomp >::setVal().
Referenced by Proto::EBStencil< order, data_t, srcCenter, dstCenter >::applyITZ(), and Proto::EBStencil< order, data_t, srcCenter, dstCenter >::~EBStencil().
applyITZ()
template<int order, typename data_t , CENTERING srcCenter, CENTERING dstCenter> void Proto::EBStencil< order, data_t, srcCenter, dstCenter >::applyITZ (EBBoxData< dstCenter, data_t, 1 > & a_dst, const EBBoxData< srcCenter, data_t, 1 > & a_src, double a_scale = 1.0, bool a_printStuff = false) const inline
References Proto::EBStencil< order, data_t, srcCenter, dstCenter >::apply(), Proto::dumpArea(), and Proto::EBBoxData< cent, data_t, ncomp >::getRegData().
Referenced by Proto::EBStencil< order, data_t, srcCenter, dstCenter >::computeDiagonalWeights(), and Proto::EBStencil< order, data_t, srcCenter, dstCenter >::~EBStencil().
getDiagonalWeights()
template<int order, typename data_t, CENTERING srcCenter, CENTERING dstCenter> shared_ptr<EBBoxData<dstCenter, data_t, 1> > Proto::EBStencil< order, data_t, srcCenter, dstCenter >::getDiagonalWeights () const inline
get the diagonal weights of the stencil
can only be used if it was asked for at construction. Useful for relaxation methods.
References Proto::EBStencil< order, data_t, srcCenter, dstCenter >::computeDiagonalWeights(), and Proto::EBStencil< order, data_t, srcCenter, dstCenter >::m_diagonalWeights.
computeDiagonalWeights()
template<int order, typename data_t , CENTERING srcCenter, CENTERING dstCenter> void Proto::EBStencil< order, data_t, srcCenter, dstCenter >::computeDiagonalWeights (const vector< EBIndex< dstCenter > > & a_dstVoFs, const vector< LocalStencil< srcCenter, data_t > > & a_stencil, const EBGraph & a_graph, const Box & a_validBox, const Point & a_dstGrown) protected
References Proto::EBStencil< order, data_t, srcCenter, dstCenter >::applyITZ(), Proto::EBHostData< cent, data_t, ncomp >::dataInfo(), Proto::EBBoxData< cent, data_t, ncomp >::dataInfo(), Box::grow(), Proto::LocalStencil< cent, data_t >::m_betaWeight, Proto::LocalStencil< cent, data_t >::m_betaWeightSet, and Proto::EBHostData< cent, data_t, ncomp >::setVal().
Referenced by Proto::EBStencil< order, data_t, srcCenter, dstCenter >::EBStencil(), and Proto::EBStencil< order, data_t, srcCenter, dstCenter >::getDiagonalWeights().
operator=()
template<int order, typename data_t, CENTERING srcCenter, CENTERING dstCenter> void Proto::EBStencil< order, data_t, srcCenter, dstCenter >::operator= (const EBStencil< order, data_t, srcCenter, dstCenter > & a_inp) private
Member Data Documentation
m_hasDomainBCs
template<int order, typename data_t, CENTERING srcCenter, CENTERING dstCenter> bool Proto::EBStencil< order, data_t, srcCenter, dstCenter >::m_hasDomainBCs protected
m_bcsOnly
template<int order, typename data_t, CENTERING srcCenter, CENTERING dstCenter> bool Proto::EBStencil< order, data_t, srcCenter, dstCenter >::m_bcsOnly protected
m_irregOnly
template<int order, typename data_t, CENTERING srcCenter, CENTERING dstCenter> bool Proto::EBStencil< order, data_t, srcCenter, dstCenter >::m_irregOnly protected
m_regStencilInterior
template<int order, typename data_t, CENTERING srcCenter, CENTERING dstCenter> Stencil<double> Proto::EBStencil< order, data_t, srcCenter, dstCenter >::m_regStencilInterior protected
these
m_regStencilBCS
template<int order, typename data_t, CENTERING srcCenter, CENTERING dstCenter> vector<Stencil<double> > Proto::EBStencil< order, data_t, srcCenter, dstCenter >::m_regStencilBCS[2 *DIM] protected
m_BCApplyBoxes
template<int order, typename data_t, CENTERING srcCenter, CENTERING dstCenter> vector<Box> Proto::EBStencil< order, data_t, srcCenter, dstCenter >::m_BCApplyBoxes[2 *DIM] protected
m_periodic_domain_bcs_only
template<int order, typename data_t, CENTERING srcCenter, CENTERING dstCenter> bool Proto::EBStencil< order, data_t, srcCenter, dstCenter >::m_periodic_domain_bcs_only protected
m_regApplyBox
template<int order, typename data_t, CENTERING srcCenter, CENTERING dstCenter> Box Proto::EBStencil< order, data_t, srcCenter, dstCenter >::m_regApplyBox protected
m_irregStencil
template<int order, typename data_t, CENTERING srcCenter, CENTERING dstCenter> shared_ptr< AggStencil<srcCenter, dstCenter, data_t> > Proto::EBStencil< order, data_t, srcCenter, dstCenter >::m_irregStencil protected
m_diagonalWeights
template<int order, typename data_t, CENTERING srcCenter, CENTERING dstCenter> shared_ptr< EBBoxData<dstCenter, data_t, 1> > Proto::EBStencil< order, data_t, srcCenter, dstCenter >::m_diagonalWeights protected
Referenced by Proto::EBStencil< order, data_t, srcCenter, dstCenter >::getDiagonalWeights().
The documentation for this class was generated from the following files:
Proto_EBStencil.H
Proto_EBStencilImplem.H