Chombo_4: EBLevelBoxData< cent, NUMCOMPS > Class Template Reference
EBLevelBoxData< cent, NUMCOMPS > Class Template Reference
#include <Chombo_EBLevelBoxData.H>
Public Types
typedef CH4_Data_Choreography::DistributedData< EBBoxData< cent, Real, NUMCOMPS > > devi_distrib_t
typedef CH4_Data_Choreography::DistributedData< EBHostData< cent, Real, NUMCOMPS > > host_distrib_t
typedef CH4_Data_Choreography::DistributedData< EBGraph > graph_distrib_t
typedef GraphConstructorFactory< EBBoxData< cent, Real, NUMCOMPS > > devifactory_t
typedef GraphConstructorFactory< EBHostData< cent, Real, NUMCOMPS > > hostfactory_t
typedef DeviToHostAliasFactory< cent, Real, NUMCOMPS > devi_to_host_alias_factory_t
Public Member Functions
EBLevelBoxData ()
EBLevelBoxData (const DisjointBoxLayout &a_dp, const IntVect &a_ghost, shared_ptr< graph_distrib_t > a_graphs)
virtual ~EBLevelBoxData ()
virtual void define (const DisjointBoxLayout &a_dp, const IntVect &a_ghost, shared_ptr< graph_distrib_t > a_graphs)
template<unsigned int srcComp>
void define (EBLevelBoxData< cent, srcComp > &a_input, unsigned int a_comp, shared_ptr< graph_distrib_t > a_graphs)
EBLevelBoxData & operator+= (const EBLevelBoxData &a_input)
EBLevelBoxData & operator-= (const EBLevelBoxData &a_input)
EBLevelBoxData & operator*= (const EBLevelBoxData &a_input)
EBLevelBoxData & operator/= (const EBLevelBoxData &a_input)
void checkIfPeriodic (const DisjointBoxLayout &a_dp) const
void setVal (Real a_value)
void scale (Real a_value)
void incr (const EBLevelBoxData &a_input, Real a_value)
void copyTo (EBLevelBoxData< cent, NUMCOMPS > &a_dst, bool a_printStuff=false) const
the real copyTo interface. accept no imitations
void copyToCPUOnly (EBLevelBoxData< cent, NUMCOMPS > &a_dst, bool a_printStuff=false) const
void copyToWithGPU (EBLevelBoxData< cent, NUMCOMPS > &a_dst, bool a_printStuff=false) const
virtual void exchange (bool a_printStuff=false)
the new, sleeker exchange interface that all the kids are talking about
virtual void exchangeCPUOnly (bool a_printStuff=false)
exchange when the GPU is a lie
virtual void exchangeWithGPU (bool a_printStuff=false)
the new, sleeker exchange interface that all the kids are talking about
Real maxNorm (int a_icomp) const
deprecated interface
Real maxNorm (EBIndex< CELL > &a_vofMaxThisProc, int a_icomp) const
The new maxnorm interface all the cool kids are using.
std::array< Real, 3 > maxNormSplit (int a_icomp) const
template<int order>
std::array< Real, 3 > pNormSplit (int a_icomp, Real a_p, shared_ptr< GeometryService< order > > a_geoserv, bool a_volWeighted=false) const
Real max (int a_icomp) const
Real min (int a_icomp) const
Real sum (int a_icomp) const
for dot products
void writeToFileHDF5 (const string &a_filename, Real a_coveredval) const
void writeToCheckPoint (HDF5Handle &a_handle, string a_varname) const
void readFromCheckPoint (HDF5Handle &a_handle, string a_varname)
void dumpFile (int fileNumber, Real coveredValue) const
void dumpFile (std::string fileName, Real coveredValue) const
shared_ptr< graph_distrib_t > getGraphs ()
Public Member Functions inherited from CH4_Data_Choreography::DistributedData< EBBoxData< cent, Real, NUMCOMPS > >
DistributedData ()
DistributedData (const Chombo4::DisjointBoxLayout &a_grids, const Chombo4::IntVect &a_ghost, const Chombo4::DataFactory< EBBoxData< cent, Real, NUMCOMPS > > &a_factory, bool a_enableStaticCache=false)
void define (const Chombo4::DisjointBoxLayout &a_grids, const Chombo4::IntVect &a_ghost, const Chombo4::DataFactory< EBBoxData< cent, Real, NUMCOMPS > > &a_factory, bool a_enableStaticCache=false)
datafactory has an ncomps argument that shall be ignored here
Chombo4::DataIterator dataIterator () const
old leveldata functionality that got used a LOT
virtual ~DistributedData ()
EBBoxData< cent, Real, NUMCOMPS > & operator[] (const Chombo4::DataIndex &a_dit)
const EBBoxData< cent, Real, NUMCOMPS > & operator[] (const Chombo4::DataIndex &a_dit) const
void exchange (bool a_printStuff=false)
void copyTo (DistributedData &a_dst, bool a_printStuff=false)
IntVect ghostVect () const
Chombo4::DisjointBoxLayout disjointBoxLayout () const
void printGrids () const
Static Public Member Functions
static void copyHostToFAB (LevelData< FArrayBox > &a_fabxDat, const host_distrib_t &a_hostDat, const Real &a_coveredval)
This is for plotfiles only as multivalued stuff will be lost.
static void copyToHost (host_distrib_t &a_hostDat, const devi_distrib_t &a_deviDat)
this is for mpi stuff
static void copyToHost (EBHostData< cent, Real, NUMCOMPS > &hostfab, const EBBoxData< cent, Real, NUMCOMPS > &devifab)
static void copyToDevice (devi_distrib_t &a_deviDat, const host_distrib_t &a_hostDat)
static void copyToDevice (EBBoxData< cent, Real, NUMCOMPS > &devifab, const EBHostData< cent, Real, NUMCOMPS > &hostfab)
template<int order>
static shared_ptr< graph_distrib_t > getGraphOnOneBox (const Box &a_domain, IntVect a_ghost, shared_ptr< GeometryService< order > > a_geoserv)
Only for debugging. This will not scale.
template<int order>
static shared_ptr< EBLevelBoxData< CELL, 1 > > getOneBoxCopyOfData (const EBLevelBoxData< CELL, 1 > &a_input, shared_ptr< GeometryService< order > > a_geoserv)
Only for debugging. This will not scale.
static int checkAnswer (const EBBoxData< cent, Real, NUMCOMPS > &a_calculatedAns, const EBBoxData< cent, Real, NUMCOMPS > &a_referenceAns, const Bx &a_grid, unsigned int a_icomp, Real a_tol)
for tests
template<int order>
static shared_ptr< EBLevelBoxData< CELL, 1 > > getDataOnRefinedCoarseLayout (const DisjointBoxLayout &a_dblCoar, const IntVect &a_ghost, shared_ptr< GeometryService< order > > a_geoserv)
useful for multigrid, AMR
template<int order>
static shared_ptr< graph_distrib_t > getGraphOnRefinedCoarseLayout (const DisjointBoxLayout &a_dblCoar, const IntVect &a_ghost, shared_ptr< GeometryService< order > > a_geoserv)
meta data for the above
Private Attributes
shared_ptr< graph_distrib_t > m_graphs
Member Typedef Documentation
devi_distrib_t
template<CENTERING cent, int NUMCOMPS> typedef CH4_Data_Choreography::DistributedData<EBBoxData< cent, Real, NUMCOMPS> > EBLevelBoxData< cent, NUMCOMPS >::devi_distrib_t
host_distrib_t
template<CENTERING cent, int NUMCOMPS> typedef CH4_Data_Choreography::DistributedData<EBHostData<cent, Real, NUMCOMPS> > EBLevelBoxData< cent, NUMCOMPS >::host_distrib_t
graph_distrib_t
template<CENTERING cent, int NUMCOMPS> typedef CH4_Data_Choreography::DistributedData<EBGraph> EBLevelBoxData< cent, NUMCOMPS >::graph_distrib_t
devifactory_t
template<CENTERING cent, int NUMCOMPS> typedef GraphConstructorFactory< EBBoxData<cent, Real, NUMCOMPS> > EBLevelBoxData< cent, NUMCOMPS >::devifactory_t
hostfactory_t
template<CENTERING cent, int NUMCOMPS> typedef GraphConstructorFactory<EBHostData<cent, Real, NUMCOMPS> > EBLevelBoxData< cent, NUMCOMPS >::hostfactory_t
devi_to_host_alias_factory_t
template<CENTERING cent, int NUMCOMPS> typedef DeviToHostAliasFactory<cent, Real, NUMCOMPS> EBLevelBoxData< cent, NUMCOMPS >::devi_to_host_alias_factory_t
Constructor & Destructor Documentation
EBLevelBoxData() [1/2]
template<CENTERING cent, int NUMCOMPS> EBLevelBoxData< cent, NUMCOMPS >::EBLevelBoxData () inline
EBLevelBoxData() [2/2]
template<CENTERING cent, int NUMCOMPS> EBLevelBoxData< cent, NUMCOMPS >::EBLevelBoxData (const DisjointBoxLayout & a_dp, const IntVect & a_ghost, shared_ptr< graph_distrib_t > a_graphs) inline
~EBLevelBoxData()
template<CENTERING cent, int NUMCOMPS> virtual EBLevelBoxData< cent, NUMCOMPS >::~EBLevelBoxData () inline virtual
Member Function Documentation
define() [1/2]
template<CENTERING cent, int NUMCOMPS> virtual void EBLevelBoxData< cent, NUMCOMPS >::define (const DisjointBoxLayout & a_dp, const IntVect & a_ghost, shared_ptr< graph_distrib_t > a_graphs) inline virtual
define() [2/2]
template<CENTERING cent, int NUMCOMPS> template<unsigned int srcComp> void EBLevelBoxData< cent, NUMCOMPS >::define (EBLevelBoxData< cent, srcComp > & a_input, unsigned int a_comp, shared_ptr< graph_distrib_t > a_graphs) inline
References CH4_Data_Choreography::DistributedData< EBBoxData< cent, Real, NUMCOMPS > >::disjointBoxLayout(), and CH4_Data_Choreography::DistributedData< EBBoxData< cent, Real, NUMCOMPS > >::ghostVect().
operator+=()
template<CENTERING cent, int NUMCOMPS> EBLevelBoxData& EBLevelBoxData< cent, NUMCOMPS >::operator+= (const EBLevelBoxData< cent, NUMCOMPS > & a_input) inline
operator-=()
template<CENTERING cent, int NUMCOMPS> EBLevelBoxData& EBLevelBoxData< cent, NUMCOMPS >::operator-= (const EBLevelBoxData< cent, NUMCOMPS > & a_input) inline
operator*=()
template<CENTERING cent, int NUMCOMPS> EBLevelBoxData& EBLevelBoxData< cent, NUMCOMPS >::operator*= (const EBLevelBoxData< cent, NUMCOMPS > & a_input) inline
operator/=()
template<CENTERING cent, int NUMCOMPS> EBLevelBoxData& EBLevelBoxData< cent, NUMCOMPS >::operator/= (const EBLevelBoxData< cent, NUMCOMPS > & a_input) inline
checkIfPeriodic()
template<CENTERING cent, int NUMCOMPS> void EBLevelBoxData< cent, NUMCOMPS >::checkIfPeriodic (const DisjointBoxLayout & a_dp) const inline
References MayDay::Error().
setVal()
template<CENTERING cent, int NUMCOMPS> void EBLevelBoxData< cent, NUMCOMPS >::setVal (Real a_value) inline
scale()
template<CENTERING cent, int NUMCOMPS> void EBLevelBoxData< cent, NUMCOMPS >::scale (Real a_value) inline
incr()
template<CENTERING cent, int NUMCOMPS> void EBLevelBoxData< cent, NUMCOMPS >::incr (const EBLevelBoxData< cent, NUMCOMPS > & a_input, Real a_value) inline
copyTo()
template<CENTERING cent, int NUMCOMPS> void EBLevelBoxData< cent, NUMCOMPS >::copyTo (EBLevelBoxData< cent, NUMCOMPS > & a_dst, bool a_printStuff = false) const inline
the real copyTo interface. accept no imitations
copy to a_dst over box intersections.
References CH_TIME.
Referenced by EBLevelBoxData< cent, NUMCOMPS >::getOneBoxCopyOfData().
copyToCPUOnly()
template<CENTERING cent, int NUMCOMPS> void EBLevelBoxData< cent, NUMCOMPS >::copyToCPUOnly (EBLevelBoxData< cent, NUMCOMPS > & a_dst, bool a_printStuff = false) const inline
References CH_TIME, CH4_Data_Choreography::DistributedData< fabtype_t >::copyTo(), CH4_Data_Choreography::DistributedData< EBBoxData< cent, Real, NUMCOMPS > >::disjointBoxLayout(), CH4_Data_Choreography::DistributedData< EBBoxData< cent, Real, NUMCOMPS > >::ghostVect(), and pout().
copyToWithGPU()
template<CENTERING cent, int NUMCOMPS> void EBLevelBoxData< cent, NUMCOMPS >::copyToWithGPU (EBLevelBoxData< cent, NUMCOMPS > & a_dst, bool a_printStuff = false) const inline
References CH_TIME, CH4_Data_Choreography::DistributedData< fabtype_t >::copyTo(), CH4_Data_Choreography::DistributedData< EBBoxData< cent, Real, NUMCOMPS > >::disjointBoxLayout(), CH4_Data_Choreography::DistributedData< EBBoxData< cent, Real, NUMCOMPS > >::ghostVect(), EBLevelBoxData< cent, NUMCOMPS >::m_graphs, and pout().
exchange()
template<CENTERING cent, int NUMCOMPS> virtual void EBLevelBoxData< cent, NUMCOMPS >::exchange (bool a_printStuff = false) inline virtual
the new, sleeker exchange interface that all the kids are talking about
References CH_TIME.
exchangeCPUOnly()
template<CENTERING cent, int NUMCOMPS> virtual void EBLevelBoxData< cent, NUMCOMPS >::exchangeCPUOnly (bool a_printStuff = false) inline virtual
exchange when the GPU is a lie
References CH_TIME, and CH4_Data_Choreography::DistributedData< fabtype_t >::exchange().
exchangeWithGPU()
template<CENTERING cent, int NUMCOMPS> virtual void EBLevelBoxData< cent, NUMCOMPS >::exchangeWithGPU (bool a_printStuff = false) inline virtual
the new, sleeker exchange interface that all the kids are talking about
References CH4_SPMD::barrier(), CH_TIME, CH4_Data_Choreography::DistributedData< fabtype_t >::exchange(), and pout().
maxNorm() [1/2]
template<CENTERING cent, int NUMCOMPS> Real EBLevelBoxData< cent, NUMCOMPS >::maxNorm (int a_icomp) const inline
deprecated interface
maxNorm() [2/2]
template<CENTERING cent, int NUMCOMPS> Real EBLevelBoxData< cent, NUMCOMPS >::maxNorm (EBIndex< CELL > & a_vofMaxThisProc, int a_icomp) const inline
The new maxnorm interface all the cool kids are using.
References CH_TIME, MayDay::Error(), max(), Proto::maxNormCell(), and MPI_CH_REAL.
maxNormSplit()
template<CENTERING cent, int NUMCOMPS> std::array<Real, 3> EBLevelBoxData< cent, NUMCOMPS >::maxNormSplit (int a_icomp) const inline
The L_inf norm split by EB and regular cells a_volWeighted=false means weighted by number of cells, true is by volume of cells always normalized (not dx aware) Returns array with the norms of [all, EB, regular]
References CH_TIME, MayDay::Error(), max(), and MPI_CH_REAL.
pNormSplit()
template<CENTERING cent, int NUMCOMPS> template<int order> std::array<Real, 3> EBLevelBoxData< cent, NUMCOMPS >::pNormSplit (int a_icomp, Real a_p, shared_ptr< GeometryService< order > > a_geoserv, bool a_volWeighted = false) const inline
The L_p norm split by regular and EB cells a_volWeighted=false means weighted by number of cells, true is by volume of cells always normalized (not dx aware) Returns array with the norms of [all, EB, regular]
References CH_TIME, MayDay::Error(), MPI_CH_REAL, and norm().
max()
template<CENTERING cent, int NUMCOMPS> Real EBLevelBoxData< cent, NUMCOMPS >::max (int a_icomp) const inline
References CH_TIME, MayDay::Error(), max(), Proto::maxCell(), and MPI_CH_REAL.
min()
template<CENTERING cent, int NUMCOMPS> Real EBLevelBoxData< cent, NUMCOMPS >::min (int a_icomp) const inline
References CH_TIME, MayDay::Error(), max(), Proto::minCell(), and MPI_CH_REAL.
sum()
template<CENTERING cent, int NUMCOMPS> Real EBLevelBoxData< cent, NUMCOMPS >::sum (int a_icomp) const inline
for dot products
References CH_TIME, MayDay::Error(), ProtoCh::getPoint(), Proto::EBGraph::getVoFs(), MPI_CH_REAL, and BoxIterator::ok().
writeToFileHDF5()
template<CENTERING cent, int NUMCOMPS> void EBLevelBoxData< cent, NUMCOMPS >::writeToFileHDF5 (const string & a_filename, Real a_coveredval) const inline
References writeLevelname().
writeToCheckPoint()
template<CENTERING cent, int NUMCOMPS> void EBLevelBoxData< cent, NUMCOMPS >::writeToCheckPoint (HDF5Handle & a_handle, string a_varname) const inline
References write().
readFromCheckPoint()
template<CENTERING cent, int NUMCOMPS> void EBLevelBoxData< cent, NUMCOMPS >::readFromCheckPoint (HDF5Handle & a_handle, string a_varname) inline
References read().
dumpFile() [1/2]
template<CENTERING cent, int NUMCOMPS> void EBLevelBoxData< cent, NUMCOMPS >::dumpFile (int fileNumber, Real coveredValue) const inline
dumpFile() [2/2]
template<CENTERING cent, int NUMCOMPS> void EBLevelBoxData< cent, NUMCOMPS >::dumpFile (std::string fileName, Real coveredValue) const inline
copyHostToFAB()
template<CENTERING cent, int NUMCOMPS> static void EBLevelBoxData< cent, NUMCOMPS >::copyHostToFAB (LevelData< FArrayBox > & a_fabxDat, const host_distrib_t & a_hostDat, const Real & a_coveredval) inline static
This is for plotfiles only as multivalued stuff will be lost.
References CH4_Data_Choreography::DistributedData< fabtype_t >::dataIterator(), LevelData< T >::disjointBoxLayout(), ProtoCh::getIntVect(), Proto::EBGraph::isCovered(), Proto::EBIndex< cent >::m_isBoundary, Proto::EBIndex< cent >::m_pt, Proto::EBIndex< cent >::m_vofIDLo, Proto::EBIndex< cent >::m_vofIDMe, and Proto::PointSetIterator::ok().
copyToHost() [1/2]
template<CENTERING cent, int NUMCOMPS> static void EBLevelBoxData< cent, NUMCOMPS >::copyToHost (host_distrib_t & a_hostDat, const devi_distrib_t & a_deviDat) inline static
this is for mpi stuff
References CH_TIME, Proto::EBHostData< cent, data_t, ncomp >::dataInfo(), Proto::EBBoxData< cent, data_t, ncomp >::dataInfo(), and CH4_Data_Choreography::DistributedData< fabtype_t >::dataIterator().
Referenced by writeEBLevelHDF5().
copyToHost() [2/2]
template<CENTERING cent, int NUMCOMPS> static void EBLevelBoxData< cent, NUMCOMPS >::copyToHost (EBHostData< cent, Real, NUMCOMPS > & hostfab, const EBBoxData< cent, Real, NUMCOMPS > & devifab) inline static
References Proto::EBHostData< cent, data_t, ncomp >::dataInfo(), and Proto::EBBoxData< cent, data_t, ncomp >::dataInfo().
copyToDevice() [1/2]
template<CENTERING cent, int NUMCOMPS> static void EBLevelBoxData< cent, NUMCOMPS >::copyToDevice (devi_distrib_t & a_deviDat, const host_distrib_t & a_hostDat) inline static
References CH_TIME, and CH4_Data_Choreography::DistributedData< fabtype_t >::dataIterator().
copyToDevice() [2/2]
template<CENTERING cent, int NUMCOMPS> static void EBLevelBoxData< cent, NUMCOMPS >::copyToDevice (EBBoxData< cent, Real, NUMCOMPS > & devifab, const EBHostData< cent, Real, NUMCOMPS > & hostfab) inline static
References Proto::EBHostData< cent, data_t, ncomp >::dataInfo(), Proto::EBBoxData< cent, data_t, ncomp >::dataInfo(), and MayDay::Error().
getGraphOnOneBox()
template<CENTERING cent, int NUMCOMPS> template<int order> static shared_ptr<graph_distrib_t> EBLevelBoxData< cent, NUMCOMPS >::getGraphOnOneBox (const Box & a_domain, IntVect a_ghost, shared_ptr< GeometryService< order > > a_geoserv) inline static
Only for debugging. This will not scale.
getOneBoxCopyOfData()
template<CENTERING cent, int NUMCOMPS> template<int order> static shared_ptr<EBLevelBoxData<CELL, 1> > EBLevelBoxData< cent, NUMCOMPS >::getOneBoxCopyOfData (const EBLevelBoxData< CELL, 1 > & a_input, shared_ptr< GeometryService< order > > a_geoserv) inline static
Only for debugging. This will not scale.
References EBLevelBoxData< cent, NUMCOMPS >::copyTo(), CH4_Data_Choreography::DistributedData< EBBoxData< cent, Real, NUMCOMPS > >::disjointBoxLayout(), and CH4_Data_Choreography::DistributedData< EBBoxData< cent, Real, NUMCOMPS > >::ghostVect().
checkAnswer()
template<CENTERING cent, int NUMCOMPS> static int EBLevelBoxData< cent, NUMCOMPS >::checkAnswer (const EBBoxData< cent, Real, NUMCOMPS > & a_calculatedAns, const EBBoxData< cent, Real, NUMCOMPS > & a_referenceAns, const Bx & a_grid, unsigned int a_icomp, Real a_tol) inline static
for tests
References CH_assert, Proto::EBBoxData< cent, data_t, ncomp >::ebgraph(), Proto::EBBoxData< cent, data_t, ncomp >::inputBox(), and Proto::maxNormCell().
getGraphs()
template<CENTERING cent, int NUMCOMPS> shared_ptr<graph_distrib_t > EBLevelBoxData< cent, NUMCOMPS >::getGraphs () inline
getDataOnRefinedCoarseLayout()
template<CENTERING cent, int NUMCOMPS> template<int order> static shared_ptr<EBLevelBoxData<CELL, 1> > EBLevelBoxData< cent, NUMCOMPS >::getDataOnRefinedCoarseLayout (const DisjointBoxLayout & a_dblCoar, const IntVect & a_ghost, shared_ptr< GeometryService< order > > a_geoserv) inline static
useful for multigrid, AMR
getGraphOnRefinedCoarseLayout()
template<CENTERING cent, int NUMCOMPS> template<int order> static shared_ptr<graph_distrib_t> EBLevelBoxData< cent, NUMCOMPS >::getGraphOnRefinedCoarseLayout (const DisjointBoxLayout & a_dblCoar, const IntVect & a_ghost, shared_ptr< GeometryService< order > > a_geoserv) inline static
meta data for the above
References grow(), and refine().
Member Data Documentation
m_graphs
template<CENTERING cent, int NUMCOMPS> shared_ptr<graph_distrib_t> EBLevelBoxData< cent, NUMCOMPS >::m_graphs private
Referenced by EBLevelBoxData< cent, NUMCOMPS >::copyToWithGPU().
The documentation for this class was generated from the following file:
Chombo_EBLevelBoxData.H