Chombo_4: Proto::IndexTM< T, N > Class Template Reference
Proto::IndexTM< T, N > Class Template Reference
#include <Proto_IndexTM.H>
Public Member Functions
T max () const
T min () const
template<typename OP >
bool operatorCompare (const IndexTM< T, N > &a_p, const OP &a_op) const
template<typename OP >
IndexTM< T, N > & operatorOpEquals (const IndexTM< T, N > &a_p, const OP &a_op)
template<typename OP >
IndexTM< T, N > & operatorOpEquals (const T &a_p, const OP &a_op)
IndexTM & reciprocal ()
int minDir (bool a_doAbs) const
int maxDir (bool a_doAbs) const
T integer_factorial (int n) const
T factorial () const
Constructors and Accessors
See derived class IndexTM for more constructors.
IndexTM ()
~IndexTM ()
IndexTM (T a_i)
IndexTM (T a_i, T a_j)
IndexTM (T a_i, T a_j, T a_k)
IndexTM (T a_i, T a_j, T a_k, T a_l)
IndexTM (T a_i, T a_j, T a_k, T a_l, T a_m)
IndexTM (T a_i, T a_j, T a_k, T a_l, T a_m, T a_n)
IndexTM (const T *a_a)
IndexTM (const IndexTM &a_rhs)
IndexTM copy () const
IndexTM & operator= (const IndexTM &a_rhs)
T & operator[] (int a_i)
T operator[] (int a_i) const
void setVal (int a_i, T a_val)
void setAll (T a_val)
Data pointer functions
const T * getVect () const
const T * dataPtr () const
T * dataPtr ()
Comparison Operators
bool operator== (const IndexTM &a_p) const
bool operator!= (const IndexTM &a_p) const
bool lexLT (const IndexTM &a_s) const
bool operator< (const IndexTM &a_s) const
bool componentwiseLE (const IndexTM &a_s)
bool lexGT (const IndexTM &a_s) const
Unary operators
IndexTM operator+ () const
IndexTM operator- () const
T dotProduct (const IndexTM &a_rhs) const
T sum () const
T product () const
Other arithmetic operators
IndexTM & min (const IndexTM &a_p)
IndexTM & max (const IndexTM &a_p)
IndexTM & scale (T a_s)
IndexTM & reflect (T a_refIx, int a_idir)
IndexTM & shift (int a_coord, T a_s)
IndexTM & shift (const IndexTM &a_iv)
IndexTM & diagShift (T a_s)
IndexTM & coarsen (const IndexTM &a_p)
IndexTM & coarsen (T a_p)
I/O Functions
void p () const
Public Member Functions inherited from Proto::GenericArithmeticable< T, IndexTM< T, N > >
virtual ~GenericArithmeticable ()
GenericArithmeticable (IndexTM< T, N > *s)
bool operator< (const IndexTM< T, N > &) const
bool operator> (const IndexTM< T, N > &) const
bool operator<= (const IndexTM< T, N > &) const
bool operator>= (const IndexTM< T, N > &) const
IndexTM< T, N > & operator+= (const IndexTM< T, N > &)
IndexTM< T, N > & operator+= (const T &)
IndexTM< T, N > & operator-= (const IndexTM< T, N > &)
IndexTM< T, N > & operator-= (const T &)
IndexTM< T, N > & operator*= (const IndexTM< T, N > &)
IndexTM< T, N > & operator*= (const T &)
IndexTM< T, N > & operator/= (const IndexTM< T, N > &)
IndexTM< T, N > & operator/= (const T &)
Static Public Member Functions
static IndexTM< T, N > BASISV (int idir)
Protected Member Functions
IndexTM (const char *)
Protected Attributes
T m_vect [N]
Constants
static const IndexTM Zero
static const IndexTM Unit
static int InitStatics ()
void linearIn (const void *a_inBuf)
void linearOut (void *a_outBuf) const
Additional Inherited Members
Public Types inherited from Proto::GenericArithmeticable< T, IndexTM< T, N > >
typedef T scalar_type
typedef IndexTM< T, N > self_type
Constructor & Destructor Documentation
IndexTM() [1/10]
template<typename T, int N = DIM> Proto::IndexTM< T, N >::IndexTM () inline
Construct an IndexTM whose components are uninitialized.
Referenced by Proto::IndexTM< double, N >::factorial(), and Proto::IndexTM< double, N >::~IndexTM().
~IndexTM()
template<typename T, int N = DIM> Proto::IndexTM< T, N >::~IndexTM () inline
Destructor.
IndexTM() [2/10]
template<typename T, int N> IndexTM< T, N >::IndexTM (T a_i) explicit
IndexTM() [3/10]
template<typename T, int N> IndexTM< T, N >::IndexTM (T a_i, T a_j)
IndexTM() [4/10]
template<typename T, int N> IndexTM< T, N >::IndexTM (T a_i, T a_j, T a_k)
IndexTM() [5/10]
template<typename T, int N> IndexTM< T, N >::IndexTM (T a_i, T a_j, T a_k, T a_l)
IndexTM() [6/10]
template<typename T, int N> IndexTM< T, N >::IndexTM (T a_i, T a_j, T a_k, T a_l, T a_m)
IndexTM() [7/10]
template<typename T, int N> IndexTM< T, N >::IndexTM (T a_i, T a_j, T a_k, T a_l, T a_m, T a_n)
IndexTM() [8/10]
template<typename T, int N> IndexTM< T, N >::IndexTM (const T * a_a) inline explicit
Construct an IndexTM setting the coordinates to the corresponding values in the integer array a_a.
IndexTM() [9/10]
template<typename T, int N> IndexTM< T, N >::IndexTM (const IndexTM< T, N > & a_rhs) inline
The copy constructor.
IndexTM() [10/10]
template<typename T, int N> IndexTM< T, N >::IndexTM (const char * a_reference) inline protected
Member Function Documentation
BASISV()
template<typename T, int N = DIM> static IndexTM<T, N> Proto::IndexTM< T, N >::BASISV (int idir) inline static
max() [1/2]
template<typename T, int N = DIM> T Proto::IndexTM< T, N >::max () const inline
Referenced by Proto::IndexTM< double, N >::componentwiseLE(), and Proto::max().
min() [1/2]
template<typename T, int N = DIM> T Proto::IndexTM< T, N >::min () const inline
Referenced by Proto::IndexTM< double, N >::componentwiseLE(), and Proto::min().
copy()
template<typename T, int N = DIM> IndexTM Proto::IndexTM< T, N >::copy () const inline
operator=()
template<typename T , int N> IndexTM< T, N > & IndexTM< T, N >::operator= (const IndexTM< T, N > & a_rhs) inline
The assignment operator.
Referenced by Proto::IndexTM< double, N >::copy().
operator[]() [1/2]
template<typename T , int N> T & IndexTM< T, N >::operator[] (int a_i) inline
Returns a modifiable lvalue reference to the i'th coordinate of the IndexTM.
Referenced by Proto::IndexTM< double, N >::copy().
operator[]() [2/2]
template<typename T , int N> T IndexTM< T, N >::operator[] (int a_i) const inline
Returns the i'th coordinate of the IndexTM.
setVal()
template<typename T, int N> void IndexTM< T, N >::setVal (int a_i, T a_val) inline
Set i'th coordinate of IndexTM to val.
Referenced by Proto::IndexTM< double, N >::copy().
setAll()
template<typename T, int N> void IndexTM< T, N >::setAll (T a_val) inline
set all values to val
Referenced by Proto::checkMoments(), Proto::IndexTM< double, N >::copy(), Proto::PlaneIF::entireBoxCovered(), and Proto::PlaneIF::entireBoxRegular().
getVect()
template<typename T , int N> const T * IndexTM< T, N >::getVect () const inline
Returns a const pointer to an array of coordinates of the IndexTM. Useful for arguments to FORTRAN calls.
Referenced by Proto::IndexTM< double, N >::copy().
dataPtr() [1/2]
template<typename T , int N> const T * IndexTM< T, N >::dataPtr () const inline
Only for sending to Fortran
Referenced by Proto::BASISV_TM(), and Proto::IndexTM< double, N >::copy().
dataPtr() [2/2]
template<typename T , int N> T * IndexTM< T, N >::dataPtr () inline
Only for sending to Fortran
operator==()
template<typename T , int N> bool IndexTM< T, N >::operator== (const IndexTM< T, N > & a_p) const inline
Returns true if this IndexTM is equivalent to argument IndexTM. All comparisons between analogous components must be satisfied.
Referenced by Proto::IndexTM< double, N >::copy().
operator!=()
template<typename T , int N> bool IndexTM< T, N >::operator!= (const IndexTM< T, N > & a_p) const inline
Returns true if this IndexTM is different from argument IndexTM. All comparisons between analogous components must be satisfied.
Referenced by Proto::IndexTM< double, N >::copy().
lexLT()
template<typename T , int N> bool IndexTM< T, N >::lexLT (const IndexTM< T, N > & a_s) const inline
Returns true if this IndexTM is lexically less than the argument. An IndexTM MUST BE either lexically less than, lexically greater than, or equal to another IndexTM.
iv1 is lexically less than iv2 if:
in 2-D:
(iv1[0] < iv2[0]) || ((iv1[0] == iv2[0]) && (iv1[1] < iv2[1]));
in 3-D:
(iv1[0] < iv2[0]) || (iv1[0]==iv2[0] && ((iv1[1] < iv2[1] || ((iv1[1] == iv2[1]) && (iv1[2] < iv2[2])))));
Referenced by Proto::IndexTM< double, N >::copy(), and Proto::IndexTM< double, N >::operator<().
operator<()
template<typename T, int N = DIM> bool Proto::IndexTM< T, N >::operator< (const IndexTM< T, N > & a_s) const inline
Returns true if this IndexTM is lexically less than the argument. An IndexTM MUST BE either lexically less than, lexically greater than, or equal to another IndexTM.
iv1 is lexically less than iv2 if:
in 2-D:
(iv1[0] < iv2[0]) || ((iv1[0] == iv2[0]) && (iv1[1] < iv2[1]));
in 3-D:
(iv1[0] < iv2[0]) || (iv1[0]==iv2[0] && ((iv1[1] < iv2[1] || ((iv1[1] == iv2[1]) && (iv1[2] < iv2[2])))));
componentwiseLE()
template<typename T, int N = DIM> bool Proto::IndexTM< T, N >::componentwiseLE (const IndexTM< T, N > & a_s) inline
Does operator <= the same way that intvect does it Intvect code looks like this: return D_TERM6(vect[0] >= p[0], && vect[1] >= p[1], && vect[2] >= p[2], && vect[3] >= p[3], && vect[4] >= p[4], && vect[5] >= p[5]);
Referenced by Proto::IndexedMoments< DIM-1, order >::shift().
lexGT()
template<typename T , int N> bool IndexTM< T, N >::lexGT (const IndexTM< T, N > & a_s) const inline
Returns true if this IndexTM is lexically greater than the argument. An IndexTM MUST BE either lexically less than, lexically greater than, or equal to another IndexTM.
iv1 is lexically less than iv2 if:
in 2-D:
(iv1[0] > iv2[0]) || ((iv1[0] == iv2[0]) && (iv1[1] > iv2[1]));
in 3-D:
(iv1[0] > iv2[0]) || (iv1[0]==iv2[0] && ((iv1[1] > iv2[1] || ((iv1[1] == iv2[1]) && (iv1[2] > iv2[2])))));
Referenced by Proto::IndexTM< double, N >::componentwiseLE().
operator+()
template<typename T , int N> IndexTM< T, N > IndexTM< T, N >::operator+ () const inline
Unary plus – for completeness.
Referenced by Proto::IndexTM< double, N >::componentwiseLE().
operator-()
template<typename T , int N> IndexTM< T, N > IndexTM< T, N >::operator- () const inline
Unary minus – negates all components of this IndexTM.
Referenced by Proto::IndexTM< double, N >::componentwiseLE().
dotProduct()
template<typename T , int N> T IndexTM< T, N >::dotProduct (const IndexTM< T, N > & a_rhs) const inline
Referenced by Proto::IndexTM< double, N >::componentwiseLE().
sum()
template<typename T , int N> T IndexTM< T, N >::sum () const inline
Sum of all components of this IndexTM.
Referenced by Proto::NormalDerivativeNew< dim >::calculateAll(), Proto::checkMoments(), Proto::IndexTM< double, N >::componentwiseLE(), Proto::LSProblem< dim >::computeBounds(), UniformSolution::getDerivative(), SineSphereEF::getDerivative(), MonomialEF::getDerivative(), GaussianBlob::getDerivative(), ExponentialProduct::getDerivative(), Proto::IndexedMoments< DIM-1, order >::indexOf(), BaseExactSolution::operator()(), Proto::IndexedMoments< DIM-1, order >::setMultiIndicies(), Proto::IndexedMoments< DIM-1, order >::setRegular(), Proto::IndexedMoments< DIM-1, order >::setToTruncatedMultiply(), Proto::SimpleCylinderIF::value(), Proto::SimpleEllipsoidIF::value(), Proto::AllRegularIF::value(), Proto::PlaneIF::value(), Proto::SimpleSinProductIF::value(), and Proto::SimpleCosSurfIF::value().
product()
template<typename T , int N> T IndexTM< T, N >::product () const inline
Product of all components of this IndexTM.
Referenced by Proto::IndexTM< double, N >::componentwiseLE().
operatorCompare()
template<typename T, int N> template<typename OP > bool IndexTM< T, N >::operatorCompare (const IndexTM< T, N > & a_p, const OP & a_op) const
Used by GenericArithmeticable to implement all pointwise arithmetic and comparison functions.
Referenced by Proto::IndexTM< double, N >::componentwiseLE().
operatorOpEquals() [1/2]
template<typename T, int N> template<typename OP > IndexTM< T, N > & IndexTM< T, N >::operatorOpEquals (const IndexTM< T, N > & a_p, const OP & a_op) inline
Referenced by Proto::IndexTM< double, N >::componentwiseLE().
operatorOpEquals() [2/2]
template<typename T, int N> template<typename OP > IndexTM< T, N > & IndexTM< T, N >::operatorOpEquals (const T & a_p, const OP & a_op) inline
reciprocal()
template<typename T , int N> IndexTM< T, N > & IndexTM< T, N >::reciprocal () inline
Modifies this IndexTM by division of each component into T(1).
Referenced by Proto::IndexTM< double, N >::componentwiseLE().
minDir()
template<typename T , int N> int IndexTM< T, N >::minDir (bool a_doAbs) const inline
Component with the minimum value of this Index(returns 0 if they are all the same). a_doAbs : if true then take the absolute value before comparing
Referenced by Proto::IndexTM< double, N >::componentwiseLE().
maxDir()
template<typename T , int N> int IndexTM< T, N >::maxDir (bool a_doAbs) const inline
Component with the maximum value of this Index (returns 0 if they are all the same). a_doAbs : if true then take the absolute value before comparing.
Referenced by Proto::IndexTM< double, N >::componentwiseLE().
min() [2/2]
template<typename T , int N> IndexTM< T, N > & IndexTM< T, N >::min (const IndexTM< T, N > & a_p) inline
Modifies this IndexTM by taking component-wise min with IndexTM argument.
max() [2/2]
template<typename T , int N> IndexTM< T, N > & IndexTM< T, N >::max (const IndexTM< T, N > & a_p) inline
Modifies this IndexTM by taking component-wise max with IndexTM argument.
scale()
template<typename T, int N> IndexTM< T, N > & IndexTM< T, N >::scale (T a_s) inline
Modifies this IndexTM by multiplying each component by a scalar.
Referenced by Proto::IndexTM< double, N >::componentwiseLE().
reflect()
template<typename T, int N> IndexTM< T, N > & IndexTM< T, N >::reflect (T a_refIx, int a_idir) inline
Modifies IndexTM by reflecting it in the plane defined by the index ref_ix and with normal in the direction of idir. Directions are based at zero.
Referenced by Proto::IndexTM< double, N >::componentwiseLE(), and Proto::reflect().
shift() [1/2]
template<typename T, int N> IndexTM< T, N > & IndexTM< T, N >::shift (int a_coord, T a_s) inline
Modifies this IndexTM by adding s to component in given coordinate direction.
Referenced by Proto::IndexTM< double, N >::componentwiseLE().
shift() [2/2]
template<typename T, int N> IndexTM< T, N > & IndexTM< T, N >::shift (const IndexTM< T, N > & a_iv) inline
Modifies this IndexTM by component-wise addition with IndexTM argument.
diagShift()
template<typename T, int N> IndexTM< T, N > & IndexTM< T, N >::diagShift (T a_s) inline
Modifies this IndexTM by adding a scalar s to each component.
Referenced by Proto::IndexTM< double, N >::componentwiseLE().
coarsen() [1/2]
template<typename T , int N> IndexTM< T, N > & IndexTM< T, N >::coarsen (const IndexTM< T, N > & a_p) inline
Modify IndexTM by component-wise integer projection.
Referenced by Proto::coarsen(), and Proto::IndexTM< double, N >::componentwiseLE().
coarsen() [2/2]
template<typename T, int N> IndexTM< T, N > & IndexTM< T, N >::coarsen (T a_p) inline
Modify IndexTM by component-wise integer projection.
p()
template<typename T, int N = DIM> void Proto::IndexTM< T, N >::p () const
Print an IndexTM to the pout().
Referenced by Proto::IndexTM< double, N >::componentwiseLE().
InitStatics()
template<typename T, int N = DIM> static int Proto::IndexTM< T, N >::InitStatics () static
Initializes Zero and Unit.
linearIn()
template<typename T , int N> void IndexTM< T, N >::linearIn (const void * a_inBuf)
Low-level data copy.
linearOut()
template<typename T , int N> void IndexTM< T, N >::linearOut (void * a_outBuf) const
integer_factorial()
template<typename T, int N = DIM> T Proto::IndexTM< T, N >::integer_factorial (int n) const inline
Referenced by Proto::IndexTM< double, N >::factorial(), and Proto::IndexTM< double, N >::integer_factorial().
factorial()
template<typename T, int N = DIM> T Proto::IndexTM< T, N >::factorial () const inline
Referenced by BaseExactSolution::operator()().
Member Data Documentation
Zero
template<typename T, int N = DIM> const IndexTM< T, N > IndexTM< T, N >::Zero static
This is an IndexTM all of whose components are equal to zero.
Referenced by Proto::NormalDerivativeNew< dim >::addLDeriv(), Proto::NormalDerivativeNew< dim >::addNDeriv(), Proto::IndexTM< double, N >::BASISV(), LevelGeometryService< order >::fillGraph(), PseudoGaussian::getPhiPoint(), RotatingSphere::getPhiPoint(), StokesLiquidDrop::getPhiPoint(), Proto::CutCellMoments< dim >::getVol(), Proto::NormalDerivativeNew< dim >::nChoosek(), Proto::Normalizor< order >::normalizedBndryMoments(), Proto::Normalizor< order >::normalizedFaceMoments(), Proto::Normalizor< order >::normalizedVoluMoments(), BaseExactSolution::operator()(), and EBCM::Algorithm_Framework< ebcm_order >::shiftMomentAndFillRow().
Unit
template<typename T, int N = DIM> const IndexTM< T, N > IndexTM< T, N >::Unit static
This is an IndexTM all of whose components are equal to one.
m_vect
template<typename T, int N = DIM> T Proto::IndexTM< T, N >::m_vect[N] protected
The individual components of this IndexTM.
Referenced by Proto::IndexTM< double, N >::coarsen(), Proto::IndexTM< double, N >::dotProduct(), Proto::IndexTM< double, N >::factorial(), Proto::IndexTM< double, N >::IndexTM(), Proto::IndexTM< double, N >::lexGT(), Proto::IndexTM< double, N >::lexLT(), Proto::IndexTM< double, N >::max(), Proto::IndexTM< double, N >::min(), Proto::IndexTM< double, N >::operator-(), Proto::IndexTM< double, N >::operator=(), Proto::IndexTM< double, N >::operator==(), Proto::IndexTM< double, N >::operatorCompare(), and Proto::IndexTM< double, N >::operatorOpEquals().
The documentation for this class was generated from the following files:
Proto_IndexTM.H
Proto_IndexTMImplem.H