Chombo_4: Proto::EBCrossStencilArchive< srcCenter, dstCenter, order > Class Template Reference
Proto::EBCrossStencilArchive< srcCenter, dstCenter, order > Class Template Reference
end face to cell
#include <Proto_EBStencilArchiveImplem.H>
Public Types
typedef IndexedMoments< DIM, order > IndMomDIM
typedef IndexedMoments< DIM-1, order > IndMomSDMinOne
typedef MomentIterator< DIM, order > MomItDIM
typedef MomentIterator< DIM-1, order > MomItSDMinOne
typedef HostIrregData< CELL, IndMomDIM, 1 > VoluData
typedef HostIrregData< BOUNDARY, IndMomDIM, 1 > EBFaData
typedef HostIrregData< XFACE, IndMomSDMinOne, 1 > XFacData
typedef HostIrregData< YFACE, IndMomSDMinOne, 1 > YFacData
typedef HostIrregData< ZFACE, IndMomSDMinOne, 1 > ZFacData
Static Public Member Functions
static bool getStencil (vector< EBIndex< dstCenter > > &a_dstFaces, vector< LocalStencil< srcCenter, double > > &a_stencil, Stencil< double > &a_regStencilInterior, vector< Stencil< double > > a_regStencilBCS[2 *DIM], vector< Box > a_BCApplyBoxes[2 *DIM], Box &a_regApplyBox, bool &a_bcOnly, bool &a_irregOnly, string a_stencilName, string a_domainBCName[2 *DIM], string a_ebbcName, const Box &a_srcValid, const Box &a_dstValid, const Box &a_srcDomain, const Box &a_dstDomain, const Point &a_srcGhost, const Point &a_dstGhost, const EBGraph &a_srcGraph, const EBGraph &a_dstGraph, const VoluData &a_voludata, const EBFaData &a_ebfadata, const XFacData &a_xfacdata, const YFacData &a_yfacdata, const ZFacData &a_zfacdata, double a_dx, bool a_periodiconly, Point a_dstGrown, unsigned int a_srcDir, unsigned int a_dstDir)
Detailed Description
template<CENTERING srcCenter, CENTERING dstCenter, int order>
class Proto::EBCrossStencilArchive< srcCenter, dstCenter, order >
end face to cell
Member Typedef Documentation
IndMomDIM
template<CENTERING srcCenter, CENTERING dstCenter, int order> typedef IndexedMoments<DIM , order> Proto::EBCrossStencilArchive< srcCenter, dstCenter, order >::IndMomDIM
IndMomSDMinOne
template<CENTERING srcCenter, CENTERING dstCenter, int order> typedef IndexedMoments<DIM-1, order> Proto::EBCrossStencilArchive< srcCenter, dstCenter, order >::IndMomSDMinOne
MomItDIM
template<CENTERING srcCenter, CENTERING dstCenter, int order> typedef MomentIterator<DIM , order> Proto::EBCrossStencilArchive< srcCenter, dstCenter, order >::MomItDIM
MomItSDMinOne
template<CENTERING srcCenter, CENTERING dstCenter, int order> typedef MomentIterator<DIM-1, order> Proto::EBCrossStencilArchive< srcCenter, dstCenter, order >::MomItSDMinOne
VoluData
template<CENTERING srcCenter, CENTERING dstCenter, int order> typedef HostIrregData<CELL, IndMomDIM , 1> Proto::EBCrossStencilArchive< srcCenter, dstCenter, order >::VoluData
EBFaData
template<CENTERING srcCenter, CENTERING dstCenter, int order> typedef HostIrregData<BOUNDARY, IndMomDIM , 1> Proto::EBCrossStencilArchive< srcCenter, dstCenter, order >::EBFaData
XFacData
template<CENTERING srcCenter, CENTERING dstCenter, int order> typedef HostIrregData<XFACE, IndMomSDMinOne, 1> Proto::EBCrossStencilArchive< srcCenter, dstCenter, order >::XFacData
YFacData
template<CENTERING srcCenter, CENTERING dstCenter, int order> typedef HostIrregData<YFACE, IndMomSDMinOne, 1> Proto::EBCrossStencilArchive< srcCenter, dstCenter, order >::YFacData
ZFacData
template<CENTERING srcCenter, CENTERING dstCenter, int order> typedef HostIrregData<ZFACE, IndMomSDMinOne, 1> Proto::EBCrossStencilArchive< srcCenter, dstCenter, order >::ZFacData
Member Function Documentation
getStencil()
template<CENTERING srcCenter, CENTERING dstCenter, int order> static bool Proto::EBCrossStencilArchive< srcCenter, dstCenter, order >::getStencil (vector< EBIndex< dstCenter > > & a_dstFaces, vector< LocalStencil< srcCenter, double > > & a_stencil, Stencil< double > & a_regStencilInterior, vector< Stencil< double > > a_regStencilBCS[2 *DIM], vector< Box > a_BCApplyBoxes[2 *DIM], Box & a_regApplyBox, bool & a_bcOnly, bool & a_irregOnly, string a_stencilName, string a_domainBCName[2 *DIM], string a_ebbcName, const Box & a_srcValid, const Box & a_dstValid, const Box & a_srcDomain, const Box & a_dstDomain, const Point & a_srcGhost, const Point & a_dstGhost, const EBGraph & a_srcGraph, const EBGraph & a_dstGraph, const VoluData & a_voludata, const EBFaData & a_ebfadata, const XFacData & a_xfacdata, const YFacData & a_yfacdata, const ZFacData & a_zfacdata, double a_dx, bool a_periodiconly, Point a_dstGrown, unsigned int a_srcDir, unsigned int a_dstDir) inline static
References Proto::EBGraph::getDomain(), Proto::EBStencilArchive< srcCenter, dstCenter, order, data_t >::getStencil(), Proto::EBIndex< cent >::getVoF(), and Proto::EBIndex< cent >::m_pt.
Referenced by Proto::EBStencilArchive< YFACE, XFACE, order, double >::getStencil(), Proto::EBStencilArchive< XFACE, YFACE, order, double >::getStencil(), Proto::EBStencilArchive< XFACE, ZFACE, order, double >::getStencil(), Proto::EBStencilArchive< YFACE, ZFACE, order, double >::getStencil(), Proto::EBStencilArchive< ZFACE, XFACE, order, double >::getStencil(), and Proto::EBStencilArchive< ZFACE, YFACE, order, double >::getStencil().
The documentation for this class was generated from the following file:
Proto_EBStencilArchiveImplem.H