Chombo_4: Proto::Moments Class Reference
Proto::Moments Class Reference
#include <Proto_Moments.H>
Public Member Functions
Moments ()
vector< double > momentCalc3D (const int &a_order, vofMo &a_vof)
vector< double > momentCalc2D (const int &a_order, const faceMo &a_face)
void listOfMoments (const int &a_order, vector< Point > &a_exponents)
void makeMatrix (const vector< Point > &a_list, const vector< Point > &a_listPlus, const vector< double > &a_normalVec, double **a_A, const int &a_faceNormal=999)
Constructor & Destructor Documentation
Moments()
Proto::Moments::Moments ()
Member Function Documentation
momentCalc3D()
vector< double > Proto::Moments::momentCalc3D (const int & a_order, vofMo & a_vof)
References A, Proto::LSquares::allocArray(), Proto::LSquares::freeArray(), Proto::vofMo::getFaces(), Proto::vofMo::getNormal(), Proto::faceMo::isCovered(), and Proto::LSquares::LeastSquares().
momentCalc2D()
vector< double > Proto::Moments::momentCalc2D (const int & a_order, const faceMo & a_face)
References A, Proto::LSquares::allocArray(), Proto::LSquares::freeArray(), Proto::faceMo::getEdges(), Proto::faceMo::getFaceNormal(), Proto::faceMo::getNormal(), Proto::LSquares::LeastSquares(), and Proto::edgeMo::moment().
Referenced by Proto::vofMo::makeNormal().
listOfMoments()
void Proto::Moments::listOfMoments (const int & a_order, vector< Point > & a_exponents)
makeMatrix()
void Proto::Moments::makeMatrix (const vector< Point > & a_list, const vector< Point > & a_listPlus, const vector< double > & a_normalVec, double ** a_A, const int & a_faceNormal = 999)
The documentation for this class was generated from the following files:
Proto_Moments.H
Proto_MomentsImplem.H