Chombo_4: Proto::RealVect Class Reference
Proto::RealVect Class Reference
A double vector in DIM-dimensional space.
#include <Proto_RealVect.H>
Public Types
typedef Chombo4::IntVect ch_iv
Public Member Functions
Constructors and Accessors
RealVect ()
RealVect operator* (const double &a_scale) const
RealVect (const RealVect &rhs)
RealVect (const IndexTM< double, DIM > &a_tm)
RealVect (const Point &iv)
RealVect (const double &iv)
RealVect & operator= (const RealVect &rhs)
double & operator[] (int i)
const double & operator[] (int i) const
Arithmetic Operators
RealVect & operator+= (double s)
RealVect operator+ (double s) const
RealVect & operator+= (const RealVect &p)
RealVect & operator-= (double s)
RealVect & operator-= (const RealVect &p)
RealVect operator- (double s) const
RealVect & operator*= (double s)
RealVect operator* (double s)
double dotProduct (const RealVect &a_rhs) const
RealVect operator* (double s) const
RealVect & operator/= (double s)
RealVect operator/ (double s) const
RealVect operator+ () const
RealVect operator- () const
double sum () const
double vectorLength () const
double radSquared () const
int minDir (const bool &a_doAbs) const
void setToCCLocation (const ch_iv &a_iv, const Real &a_dx)
set to location of a cell center
int maxDir (const bool &a_doAbs) const
Static Public Member Functions
Constants
static RealVect Zero ()
static RealVect Unit ()
Public Attributes
double vect [DIM]
Detailed Description
A double vector in DIM-dimensional space.
The class RealVect is an implementation of a double vector in a DIM-dimensional space. RealVect values are accessed using the operator[] function, as for a normal C++ array. In addition, the basic arithmetic operators have been overloaded to implement scaling and translation operations.
Member Typedef Documentation
ch_iv
typedef Chombo4::IntVect Proto::RealVect::ch_iv
Constructor & Destructor Documentation
RealVect() [1/5]
Proto::RealVect::RealVect () inline
Construct a RealVect whose components are zero.
References vect.
Referenced by operator+().
RealVect() [2/5]
Proto::RealVect::RealVect (const RealVect & rhs) inline
The copy constructor.
References vect.
RealVect() [3/5]
Proto::RealVect::RealVect (const IndexTM< double, DIM > & a_tm) inline
Construct a RealVect from an IndexTM<double,DIM>.
References vect.
RealVect() [4/5]
Proto::RealVect::RealVect (const Point & iv) inline
Construct a RealVect from an Point by coercing each component from int to double.
References vect.
RealVect() [5/5]
Proto::RealVect::RealVect (const double & iv) inline
References vect.
Member Function Documentation
operator*() [1/3]
RealVect Proto::RealVect::operator* (const double & a_scale) const inline
operator=()
RealVect& Proto::RealVect::operator= (const RealVect & rhs) inline
The assignment operator.
References vect.
operator[]() [1/2]
double& Proto::RealVect::operator[] (int i) inline
Returns a modifiable lvalue reference to the i'th coordinate of the RealVect.
References vect.
operator[]() [2/2]
const double& Proto::RealVect::operator[] (int i) const inline
Returns the i'th coordinate of the RealVect.
References vect.
operator+=() [1/2]
RealVect& Proto::RealVect::operator+= (double s) inline
Modifies this RealVect by addition of a scalar to each component.
References vect.
operator+() [1/2]
RealVect Proto::RealVect::operator+ (double s) const inline
Returns a RealVect that is this RealVect with a scalar s added to each component.
References vect.
operator+=() [2/2]
RealVect& Proto::RealVect::operator+= (const RealVect & p) inline
Modifies this RealVect by component-wise addition by argument.
References vect.
operator-=() [1/2]
RealVect& Proto::RealVect::operator-= (double s) inline
Modifies this RealVect by subtraction of a scalar from each component.
References vect.
operator-=() [2/2]
RealVect& Proto::RealVect::operator-= (const RealVect & p) inline
Modifies this RealVect by component-wise subtraction by argument.
References vect.
operator-() [1/2]
RealVect Proto::RealVect::operator- (double s) const inline
Returns a RealVect that is this RealVect with a scalar s subtracted from each component.
References vect.
operator*=()
RealVect& Proto::RealVect::operator*= (double s) inline
Modifies this RealVect by multiplying each component by a scalar.
References vect.
operator*() [2/3]
RealVect Proto::RealVect::operator* (double s) inline
References vect.
dotProduct()
double Proto::RealVect::dotProduct (const RealVect & a_rhs) const inline
References vect.
operator*() [3/3]
RealVect Proto::RealVect::operator* (double s) const inline
Returns a RealVect that is this RealVect with each component multiplied by a scalar.
References vect.
operator/=()
RealVect& Proto::RealVect::operator/= (double s) inline
Modifies this RealVect by dividing each component by a scalar.
References vect.
operator/()
RealVect Proto::RealVect::operator/ (double s) const inline
Returns a RealVect that is this RealVect with each component divided by a scalar.
References vect.
operator+() [2/2]
RealVect Proto::RealVect::operator+ () const inline
Unary plus – for completeness.
References RealVect().
operator-() [2/2]
RealVect Proto::RealVect::operator- () const inline
Unary minus – negates all components of this RealVect.
sum()
double Proto::RealVect::sum () const inline
Sum of all components of this RealVect.
References vect.
vectorLength()
double Proto::RealVect::vectorLength () const inline
sqrt(sum squares)
References radSquared().
Referenced by RotatingSphere::getDerivative().
radSquared()
double Proto::RealVect::radSquared () const inline
sum squares–no square root
References vect.
Referenced by vectorLength().
minDir()
int Proto::RealVect::minDir (const bool & a_doAbs) const inline
Component with the minimum value of this RealVect (returns 0 if they are all the same). a_doAbs : if true then take the absolute value before comparing
References vect.
setToCCLocation()
void Proto::RealVect::setToCCLocation (const ch_iv & a_iv, const Real & a_dx) inline
set to location of a cell center
Referenced by EBCM::Algorithm_Framework< ebcm_order >::neighborhood_t::neighborhood_t().
maxDir()
int Proto::RealVect::maxDir (const bool & a_doAbs) const inline
Component with the maximum value of this RealVect (returns 0 if they are all the same). a_doAbs : if true then take the absolute value before comparing
References vect.
Zero()
static RealVect Proto::RealVect::Zero () inline static
This is a RealVect all of whose components are equal to zero.
Referenced by Proto::BASISREALV(), Proto::DirichletEBFlux< order >::calculateWeightingMatrix(), Proto::DirichletEBFlux< order >::getEBFluxStencil(), EBCM::Algorithm_Framework< ebcm_order >::makeMergedGeometry(), Proto::Normalizor< order >::normalizedBndryMoments(), Proto::Normalizor< order >::normalizedFaceMoments(), and Proto::Normalizor< order >::normalizedVoluMoments().
Unit()
static RealVect Proto::RealVect::Unit () inline static
This is a RealVect all of whose components are equal to one.
Referenced by Proto::Normalizor< order >::faceCenter().
Member Data Documentation
vect
double Proto::RealVect::vect[DIM]
The individual components of this RealVect.
Referenced by dotProduct(), maxDir(), minDir(), operator*(), operator*=(), operator+(), operator+=(), operator-(), operator-=(), operator/(), operator/=(), operator=(), operator[](), radSquared(), RealVect(), and sum().
The documentation for this class was generated from the following file:
Proto_RealVect.H