Chombo_4: SmoothAbsoluteValue Class Reference
SmoothAbsoluteValue Class Reference
#include <Chombo_SmoothAbsoluteValue.H>
Public Member Functions
SmoothAbsoluteValue (const Proto::BaseIF *a_f, const Proto::BaseIF *a_g, const Real &a_delta)
virtual ~SmoothAbsoluteValue ()
virtual Real smoothAbsFMinusG (const Proto::IndexTM< int, DIM > &a_deriv, const Proto::IndexTM< double, DIM > &a_point) const
void getWCase (int &a_case, Real &a_wval, const Proto::IndexTM< double, DIM > &a_point) const
Static Public Member Functions
static Real POW (Real a_x, int a_p)
Protected Member Functions
virtual Real valueAem (const Proto::IndexTM< double, DIM > &a_point) const
virtual Real firstDerivAem (const Proto::IndexTM< int, DIM > &a_deriv, const Proto::IndexTM< double, DIM > &a_point) const
virtual Real secondDerivAem (const Proto::IndexTM< int, DIM > &a_deriv, const Proto::IndexTM< double, DIM > &a_point) const
virtual Real thirdDerivAem (const Proto::IndexTM< int, DIM > &a_deriv, const Proto::IndexTM< double, DIM > &a_point) const
virtual Real fourthDerivAem (const Proto::IndexTM< int, DIM > &a_deriv, const Proto::IndexTM< double, DIM > &a_point) const
bool isBogus (const Real &a_number) const
just checks nan
Protected Attributes
const Proto::BaseIF * m_f
const Proto::BaseIF * m_g
Real m_d
Real m_pi
Private Member Functions
SmoothAbsoluteValue ()
SmoothAbsoluteValue (const SmoothAbsoluteValue &a_inputIF)
void operator= (const SmoothAbsoluteValue &a_inputIF)
Detailed Description
Functions to take a smooth absolute value of the difference between two functions A_e(a,b) = |a-b|
max(f, g) = (a + b + |a - b|)/2 We need to make abs(a-b) smooth.
We take the convolution of the absolute value with cos^4(pi w/(2 delta))
Constructor & Destructor Documentation
SmoothAbsoluteValue() [1/3]
SmoothAbsoluteValue::SmoothAbsoluteValue (const Proto::BaseIF * a_f, const Proto::BaseIF * a_g, const Real & a_delta) inline
References m_d, m_f, m_g, and m_pi.
~SmoothAbsoluteValue()
virtual SmoothAbsoluteValue::~SmoothAbsoluteValue () inline virtual
References getWCase(), and smoothAbsFMinusG().
SmoothAbsoluteValue() [2/3]
SmoothAbsoluteValue::SmoothAbsoluteValue () private
SmoothAbsoluteValue() [3/3]
SmoothAbsoluteValue::SmoothAbsoluteValue (const SmoothAbsoluteValue & a_inputIF) private
Member Function Documentation
smoothAbsFMinusG()
virtual Real SmoothAbsoluteValue::smoothAbsFMinusG (const Proto::IndexTM< int, DIM > & a_deriv, const Proto::IndexTM< double, DIM > & a_point) const virtual
Referenced by ~SmoothAbsoluteValue().
getWCase()
void SmoothAbsoluteValue::getWCase (int & a_case, Real & a_wval, const Proto::IndexTM< double, DIM > & a_point) const
returns -1 if w < -delta, 1 if w > delta, 0 otherwise reduces to regular |f-g| unless case == 0
Referenced by ~SmoothAbsoluteValue().
POW()
static Real SmoothAbsoluteValue::POW (Real a_x, int a_p) inline static
References firstDerivAem(), fourthDerivAem(), ipow(), isBogus(), secondDerivAem(), thirdDerivAem(), and valueAem().
valueAem()
virtual Real SmoothAbsoluteValue::valueAem (const Proto::IndexTM< double, DIM > & a_point) const protected virtual
Here is the logic of this stuff. We have three cases that reduce to two cases. w = f(x) - g(x) case 1: (w > delta): -— whole integral is above zero answer = abs(w) case -1: (w < - delta): -— whole integral is below zero answer = abs(w) case 0: (-delta <= w <= delta) — have to split integral into above and below answer = functionAem();
Referenced by POW().
firstDerivAem()
virtual Real SmoothAbsoluteValue::firstDerivAem (const Proto::IndexTM< int, DIM > & a_deriv, const Proto::IndexTM< double, DIM > & a_point) const protected virtual
Referenced by POW().
secondDerivAem()
virtual Real SmoothAbsoluteValue::secondDerivAem (const Proto::IndexTM< int, DIM > & a_deriv, const Proto::IndexTM< double, DIM > & a_point) const protected virtual
Referenced by POW().
thirdDerivAem()
virtual Real SmoothAbsoluteValue::thirdDerivAem (const Proto::IndexTM< int, DIM > & a_deriv, const Proto::IndexTM< double, DIM > & a_point) const protected virtual
Referenced by POW().
fourthDerivAem()
virtual Real SmoothAbsoluteValue::fourthDerivAem (const Proto::IndexTM< int, DIM > & a_deriv, const Proto::IndexTM< double, DIM > & a_point) const protected virtual
Referenced by POW().
isBogus()
bool SmoothAbsoluteValue::isBogus (const Real & a_number) const protected
just checks nan
Referenced by POW().
operator=()
void SmoothAbsoluteValue::operator= (const SmoothAbsoluteValue & a_inputIF) private
Member Data Documentation
m_f
const Proto::BaseIF* SmoothAbsoluteValue::m_f protected
Referenced by SmoothAbsoluteValue().
m_g
const Proto::BaseIF* SmoothAbsoluteValue::m_g protected
Referenced by SmoothAbsoluteValue().
m_d
Real SmoothAbsoluteValue::m_d protected
Referenced by SmoothAbsoluteValue().
m_pi
Real SmoothAbsoluteValue::m_pi protected
Referenced by SmoothAbsoluteValue().
The documentation for this class was generated from the following file:
Chombo_SmoothAbsoluteValue.H