Chombo_4: Proto::Normalizor< order > Class Template Reference
Proto::Normalizor< order > Class Template Reference
This class is used to provide nomalized moments (removes dependence on grid spacing)
#include <Proto_Normalizor.H>
Public Types
typedef IndexTM< int, DIM > IvDIM
typedef IndexTM< int, DIM-1 > IvSDMinOne
typedef IndexedMoments< DIM, order > IndMomDIM
typedef IndexedMoments< DIM-1, order > IndMomSDMinOne
typedef MomentIterator< DIM, order > MomItDIM
typedef MomentIterator< DIM-1, order > MomItSDMinOne
typedef HostIrregData< CELL, IndMomDIM, 1 > VoluData
typedef HostIrregData< BOUNDARY, IndMomDIM, 1 > EBFaData
typedef HostIrregData< XFACE, IndMomSDMinOne, 1 > XFacData
typedef HostIrregData< YFACE, IndMomSDMinOne, 1 > YFacData
typedef HostIrregData< ZFACE, IndMomSDMinOne, 1 > ZFacData
Static Public Member Functions
template<CENTERING cent>
static void normalizedFaceMoments (double &a_areaFrac, RealVect &a_centroid, const HostIrregData< cent, IndexedMoments< DIM-1, order >, 1 > &a_facedat, const EBIndex< cent > &a_face, const EBGraph &a_graph, double a_dx)
template<CENTERING cent>
static void normalizedFaceMoments (double &a_areaFrac, RealVect &a_centroid, const HostIrregData< XFACE, IndexedMoments< DIM-1, order >, 1 > &a_xfacedat, const HostIrregData< YFACE, IndexedMoments< DIM-1, order >, 1 > &a_yfacedat, const HostIrregData< ZFACE, IndexedMoments< DIM-1, order >, 1 > &a_zfacedat, const EBIndex< cent > &a_face, const EBGraph &a_graph, double a_dx, int a_idir)
static void normalizedVoluMoments (double &a_volFrac, RealVect &a_centroid, const HostIrregData< CELL, IndexedMoments< DIM, order >, 1 > &a_celldat, const EBIndex< CELL > &a_vof, const EBGraph &a_graph, double a_dx)
static void normalizedBndryMoments (double &a_areaFrac, RealVect &a_centroid, const EBFaData &a_ebfadat, const EBIndex< BOUNDARY > &a_vof, const EBGraph &a_graph, double a_dx)
static double sumArea (const VoluData &a_voludata, const EBFaData &a_ebfadata, const XFacData &a_xfacdata, const YFacData &a_yfacdata, const ZFacData &a_zfacdata, const EBGraph &a_graph, const EBIndex< CELL > &a_vof, const int &a_idir, const Side::LoHiSide &a_sd, const double &a_dx)
template<typename data_t >
static void getNormalAndBoundaryArea (double &a_bndryArea, RealVect &a_normal, const VoluData &a_voludata, const EBFaData &a_ebfadata, const XFacData &a_xfacdata, const YFacData &a_yfacdata, const ZFacData &a_zfacdata, const EBIndex< CELL > &a_vof, const EBGraph &a_graph, data_t a_dx)
static void normalizeFaceMoment (IndexedMoments< DIM-1, order > &a_faceMoment, const Real a_dx)
static void normalizeFaceMoment (IndexedMoments< DIM, order > &a_faceMoment, const Real a_dx)
static void normalizeVolumeMoment (IndexedMoments< DIM, order > &a_volMoment, const Real a_dx)
template<CENTERING cent>
static RealVect faceCenter (EBIndex< cent > a_face, const Real a_dx)
Detailed Description
template<int order>
class Proto::Normalizor< order >
This class is used to provide nomalized moments (removes dependence on grid spacing)
Member Typedef Documentation
IvDIM
template<int order> typedef IndexTM<int , DIM> Proto::Normalizor< order >::IvDIM
IvSDMinOne
template<int order> typedef IndexTM<int , DIM-1> Proto::Normalizor< order >::IvSDMinOne
IndMomDIM
template<int order> typedef IndexedMoments<DIM , order> Proto::Normalizor< order >::IndMomDIM
IndMomSDMinOne
template<int order> typedef IndexedMoments<DIM-1, order> Proto::Normalizor< order >::IndMomSDMinOne
MomItDIM
template<int order> typedef MomentIterator<DIM , order> Proto::Normalizor< order >::MomItDIM
MomItSDMinOne
template<int order> typedef MomentIterator<DIM-1, order> Proto::Normalizor< order >::MomItSDMinOne
VoluData
template<int order> typedef HostIrregData<CELL , IndMomDIM , 1> Proto::Normalizor< order >::VoluData
EBFaData
template<int order> typedef HostIrregData<BOUNDARY, IndMomDIM , 1> Proto::Normalizor< order >::EBFaData
XFacData
template<int order> typedef HostIrregData<XFACE, IndMomSDMinOne, 1> Proto::Normalizor< order >::XFacData
YFacData
template<int order> typedef HostIrregData<YFACE, IndMomSDMinOne, 1> Proto::Normalizor< order >::YFacData
ZFacData
template<int order> typedef HostIrregData<ZFACE, IndMomSDMinOne, 1> Proto::Normalizor< order >::ZFacData
Member Function Documentation
normalizedFaceMoments() [1/2]
template<int order> template<CENTERING cent> static void Proto::Normalizor< order >::normalizedFaceMoments (double & a_areaFrac, RealVect & a_centroid, const HostIrregData< cent, IndexedMoments< DIM-1, order >, 1 > & a_facedat, const EBIndex< cent > & a_face, const EBGraph & a_graph, double a_dx) inline static
References Proto::BASISV_TM(), Proto::EBIndex< cent >::direction(), Proto::EBGraph::isFaceCovered(), Proto::EBGraph::isFaceRegular(), Proto::IndexTM< T, N >::Zero, and Proto::RealVect::Zero().
Referenced by Proto::SecondOrderStencil< order >::get2ndOrderDivFStencil(), Proto::EBStencilArchive< fcent, CELL, order, double >::getDivergenceStencil(), Proto::Base2ndOrderFlux< facecent, order >::getFaceInterpStencil(), and Proto::Normalizor< order >::normalizedFaceMoments().
normalizedFaceMoments() [2/2]
template<int order> template<CENTERING cent> static void Proto::Normalizor< order >::normalizedFaceMoments (double & a_areaFrac, RealVect & a_centroid, const HostIrregData< XFACE, IndexedMoments< DIM-1, order >, 1 > & a_xfacedat, const HostIrregData< YFACE, IndexedMoments< DIM-1, order >, 1 > & a_yfacedat, const HostIrregData< ZFACE, IndexedMoments< DIM-1, order >, 1 > & a_zfacedat, const EBIndex< cent > & a_face, const EBGraph & a_graph, double a_dx, int a_idir) inline static
References Proto::EBIndex< cent >::m_isBoundary, Proto::EBIndex< cent >::m_pt, Proto::EBIndex< cent >::m_vofIDLo, Proto::EBIndex< cent >::m_vofIDMe, and Proto::Normalizor< order >::normalizedFaceMoments().
normalizedVoluMoments()
template<int order> static void Proto::Normalizor< order >::normalizedVoluMoments (double & a_volFrac, RealVect & a_centroid, const HostIrregData< CELL, IndexedMoments< DIM, order >, 1 > & a_celldat, const EBIndex< CELL > & a_vof, const EBGraph & a_graph, double a_dx) inline static
References Proto::EBGraph::isCovered(), Proto::EBGraph::isRegular(), Proto::EBIndex< cent >::m_pt, Proto::IndexTM< T, N >::Zero, and Proto::RealVect::Zero().
Referenced by Proto::EBStencilArchive< fcent, CELL, order, double >::getDivergenceStencil(), Proto::EBStencilArchive< CELL, CELL, order, double >::getNormalizationStencil(), Proto::EBStencilArchive< CELL, CELL, order, double >::getRedistributionStencil(), and Proto::EBStencilArchive< CELL, CELL, order, double >::getRestrictionStencil().
normalizedBndryMoments()
template<int order> static void Proto::Normalizor< order >::normalizedBndryMoments (double & a_areaFrac, RealVect & a_centroid, const EBFaData & a_ebfadat, const EBIndex< BOUNDARY > & a_vof, const EBGraph & a_graph, double a_dx) inline static
References Proto::EBGraph::isCovered(), Proto::EBGraph::isRegular(), Proto::EBIndex< cent >::m_pt, Proto::IndexTM< T, N >::Zero, and Proto::RealVect::Zero().
Referenced by Proto::SecondOrderStencil< order >::get2ndOrderDivFStencil(), and Proto::DirichletEBFlux< order >::getEBFluxStencil().
sumArea()
template<int order> static double Proto::Normalizor< order >::sumArea (const VoluData & a_voludata, const EBFaData & a_ebfadata, const XFacData & a_xfacdata, const YFacData & a_yfacdata, const ZFacData & a_zfacdata, const EBGraph & a_graph, const EBIndex< CELL > & a_vof, const int & a_idir, const Side::LoHiSide & a_sd, const double & a_dx) inline static
References Proto::EBGraph::getXFaces(), Proto::EBGraph::getYFaces(), Proto::EBGraph::isCovered(), Proto::EBGraph::isRegular(), and Proto::EBIndex< cent >::m_pt.
Referenced by Proto::Normalizor< order >::getNormalAndBoundaryArea().
getNormalAndBoundaryArea()
template<int order> template<typename data_t > static void Proto::Normalizor< order >::getNormalAndBoundaryArea (double & a_bndryArea, RealVect & a_normal, const VoluData & a_voludata, const EBFaData & a_ebfadata, const XFacData & a_xfacdata, const YFacData & a_yfacdata, const ZFacData & a_zfacdata, const EBIndex< CELL > & a_vof, const EBGraph & a_graph, data_t a_dx) inline static
References Proto::BASISREALV(), Proto::EBGraph::isIrregular(), Proto::EBIndex< cent >::m_pt, and Proto::Normalizor< order >::sumArea().
Referenced by Proto::SecondOrderStencil< order >::get2ndOrderDivFStencil(), Proto::EBStencilArchive< fcent, CELL, order, double >::getDivergenceStencil(), Proto::DirichletEBFlux< order >::getEBFluxStencil(), and Proto::EBStencilArchive< BOUNDARY, CELL, order, double >::getStencil().
normalizeFaceMoment() [1/2]
template<int order> static void Proto::Normalizor< order >::normalizeFaceMoment (IndexedMoments< DIM-1, order > & a_faceMoment, const Real a_dx) inline static
References Proto::getRegularArea(), Proto::MomentIterator< D, P >::ok(), and Proto::POW().
normalizeFaceMoment() [2/2]
template<int order> static void Proto::Normalizor< order >::normalizeFaceMoment (IndexedMoments< DIM, order > & a_faceMoment, const Real a_dx) inline static
References Proto::getRegularArea(), Proto::MomentIterator< D, P >::ok(), and Proto::POW().
normalizeVolumeMoment()
template<int order> static void Proto::Normalizor< order >::normalizeVolumeMoment (IndexedMoments< DIM, order > & a_volMoment, const Real a_dx) inline static
References Proto::getRegularVolume(), Proto::MomentIterator< D, P >::ok(), and Proto::POW().
faceCenter()
template<int order> template<CENTERING cent> static RealVect Proto::Normalizor< order >::faceCenter (EBIndex< cent > a_face, const Real a_dx) inline static
References Proto::EBIndex< cent >::m_pt, Proto::RealVect::Unit(), Proto::XFACE, Proto::YFACE, and Proto::ZFACE.
The documentation for this class was generated from the following file:
Proto_Normalizor.H