Chombo_4: BoxLayoutData< T > Class Template Reference
BoxLayoutData< T > Class Template Reference
Data on a BoxLayout.
#include <Chombo_BoxLayoutData.H>
Public Member Functions
BoxLayoutData ()
virtual ~BoxLayoutData ()
BoxLayoutData (const BoxLayout &boxes, int comps, const DataFactory< T > &factory=DefaultDataFactory< T >())
virtual void define (const BoxLayout &boxes, int comps, const DataFactory< T > &factory=DefaultDataFactory< T >())
virtual void define (const BoxLayoutData< T > &da, const DataFactory< T > &factory=DefaultDataFactory< T >())
virtual void define (const BoxLayoutData< T > &da, const Interval &comps, const DataFactory< T > &factory=DefaultDataFactory< T >())
virtual void define (const BoxLayout &boxes)
overridden and throws an error.
int nComp () const
Interval interval () const
void generalCopyTo (const BoxLayout &a_destGrids, LayoutData< std::vector< RefCountedPtr< T > > > &a_dest, const Interval &a_interval, const ProblemDomain &a_domain, const DataFactory< T > &factory=DefaultDataFactory< T >()) const
General data copying operation.
void generalCopyTo (const BoxLayout &a_destGrids, LayoutData< std::vector< RefCountedPtr< T > > > &a_dest, const Interval &a_interval, const ProblemDomain &a_domain, const Copier &a_copier, const DataFactory< T > &factory=DefaultDataFactory< T >()) const
void addTo (const Interval &a_srcComps, BoxLayoutData< T > &a_dest, const Interval &a_destComps, const ProblemDomain &a_domain) const
void addTo (const Interval &a_srcComps, BoxLayoutData< T > &a_dest, const Interval &a_destComps, const ProblemDomain &a_domain, const Copier &a_copier) const
void addToBegin (const Interval &a_srcComps, BoxLayoutData< T > &a_dest, const Interval &a_destComps, const Copier &a_copier) const
void addToEnd (const Interval &a_destComps)
you call this on the destination BoxLayoutData, not the source.
virtual void apply (void(*a_Function)(const Box &box, int comps, T &t))
virtual bool isDefined () const
virtual void clear ()
Public Member Functions inherited from LayoutData< T >
LayoutData ()
LayoutData (const BoxLayout &a_dp)
virtual ~LayoutData ()
DataIterator dataIterator () const
TimedDataIterator timedDataIterator () const
const T & operator[] (const DataIndex &a_index) const
const accessor function
const T & operator[] (const DataIterator &a_iterator) const
const accessor function
T & operator[] (const DataIndex &a_index)
non-const accessor function
T & operator[] (const DataIterator &a_iterator)
non-const accessor function
Box box (const DataIndex &a_index) const
Box box (const DataIterator &a_iterator) const
const BoxLayout & boxLayout () const
Protected Member Functions
void setVector (const BoxLayoutData< T > &da, const Interval &srcComps, const Interval &destComps)
void allocateGhostVector (const DataFactory< T > &factory, const IntVect &ghost=IntVect::Zero)
void makeItSo (const Interval &a_srcComps, const BoxLayoutData< T > &a_src, BoxLayoutData< T > &a_dest, const Interval &a_destComps, const Copier &a_copier, const LDOperator< T > &a_op=LDOperator< T >(), bool a_printStuff=false) const
void makeItSoBegin (const Interval &a_srcComps, const BoxLayoutData< T > &a_src, BoxLayoutData< T > &a_dest, const Interval &a_destComps, const Copier &a_copier, const LDOperator< T > &a_op=LDOperator< T >(), bool a_printStuff=false) const
void makeItSoLocalCopy (const Interval &a_srcComps, const BoxLayoutData< T > &a_src, BoxLayoutData< T > &a_dest, const Interval &a_destComps, const Copier &a_copier, const LDOperator< T > &a_op=LDOperator< T >(), bool a_printStuff=false) const
void makeItSoEnd (const Interval &a_destComps, const LDOperator< T > &a_op=LDOperator< T >(), bool a_printStuff=false)
void completePendingSends () const
void allocateBuffers (const BoxLayoutData< T > &a_src, const Interval &a_srcComps, const BoxLayoutData< T > &a_dest, const Interval &a_destComps, const Copier &a_copier, const LDOperator< T > &a_op, bool a_printStuff=false) const
void writeSendDataFromMeIntoBuffers (const BoxLayoutData< T > &a_src, const Interval &a_srcComps, const LDOperator< T > &a_op) const
void postSendsFromMe () const
void postReceivesToMe () const
void unpackReceivesToMe (const Interval &a_destComps, const LDOperator< T > &a_op)
void unpackReceivesToMe_append (LayoutData< std::vector< RefCountedPtr< T > > > &a_dest, const Interval &a_destComps, int ncomp, const DataFactory< T > &factory, const LDOperator< T > &a_op)
Protected Attributes
int m_comps
bool m_isdefined
Parallel messaging members
CopierBuffer * m_buff
Protected Attributes inherited from LayoutData< T >
BoxLayout m_boxLayout
std::vector< T * > m_vector
bool m_callDelete
Friends
class LevelData< T >
Detailed Description
template<class T>
class BoxLayoutData< T >
Data on a BoxLayout.
A collection of Box-oriented objects. The arrangement of Boxes is given by the underlying BoxLayout object. BoxLayoutData attempt to prevent users from manipulating the template class T to become out of sync with the boxes in the BoxLayout. Caveat emptor.
All access to the data in a BoxLayoutData is forced to be data-parallel, by use of the DataIterator.
class T must provide the following methods:
 T()
 T(const Box& box, int comps)
 define(const Box& box, int comps)
 void copy(const Box& Rfrom, const Interval& Cd, const Box& Rto, const T& source, const Interval Cs)
Cs and Cd must have same length, but can be displaced;
Rfrom and Rto must be the same size, but can be translated.
 static int preAllocatable()
returns 0 if the size(...) function is strictly a function of Box and
Interval, and does not depend on the current state of the T object.
return 1 if size(..) is symmetric, in that sender and receiver T object
can size their message buffers, but a static object cannot.
returns 2 if the object is truly dynamic.  the message size is subject to
unique object data.
 int size(const Box& R, const Interval& comps)
 void linearOut(void* buf, const Box& R, const Interval& comps)
writes the T object into the byte stream buf, already allocated.
 void linearIn(void* buf, const Box& R, const Interval& comps)
reads in the T object from the byte stream buf.
In sequential codes, many of these functions will not be called, but in the general parallel case, they all will be.
Constructor & Destructor Documentation
BoxLayoutData() [1/2]
template<class T > BoxLayoutData< T >::BoxLayoutData () inline
~BoxLayoutData()
template<class T > BoxLayoutData< T >::~BoxLayoutData () virtual
BoxLayoutData() [2/2]
template<class T> BoxLayoutData< T >::BoxLayoutData (const BoxLayout & boxes, int comps, const DataFactory< T > & factory = DefaultDataFactory<T>()) inline
Member Function Documentation
define() [1/4]
template<class T> void BoxLayoutData< T >::define (const BoxLayout & boxes, int comps, const DataFactory< T > & factory = DefaultDataFactory<T>()) inline virtual
Reimplemented in LevelData< T >, LevelData< BoxData< Real, NUMCOMPS > >, and LevelData< FArrayBox >.
Referenced by AliasDataFactory< T >::AliasDataFactory(), and read().
define() [2/4]
template<class T> void BoxLayoutData< T >::define (const BoxLayoutData< T > & da, const DataFactory< T > & factory = DefaultDataFactory<T>()) inline virtual
Reimplemented in LevelData< T >, LevelData< BoxData< Real, NUMCOMPS > >, and LevelData< FArrayBox >.
define() [3/4]
template<class T> void BoxLayoutData< T >::define (const BoxLayoutData< T > & da, const Interval & comps, const DataFactory< T > & factory = DefaultDataFactory<T>()) inline virtual
Define this BoxLayoutData to be the subset of the data in da defined by the Interval comps.
Reimplemented in LevelData< T >, LevelData< BoxData< Real, NUMCOMPS > >, and LevelData< FArrayBox >.
define() [4/4]
template<class T> void BoxLayoutData< T >::define (const BoxLayout & boxes) inline virtual
overridden and throws an error.
Reimplemented from LayoutData< T >.
Reimplemented in LevelData< T >, LevelData< BoxData< Real, NUMCOMPS > >, and LevelData< FArrayBox >.
nComp()
template<class T> int BoxLayoutData< T >::nComp () const inline
Referenced by LevelData< FArrayBox >::copyTo(), BoxLayoutData< FArrayBox >::define(), LevelData< FArrayBox >::degenerate(), LevelData< FArrayBox >::degenerateLocalOnly(), LevelData< FArrayBox >::localCopyTo(), and WriteMultiData< T >::writeData().
interval()
template<class T> Interval BoxLayoutData< T >::interval () const inline
Referenced by LevelData< FArrayBox >::copyTo(), AliasDataFactory< T >::define(), LevelData< FArrayBox >::exchange(), LevelData< FArrayBox >::exchangeBegin(), LevelData< FArrayBox >::exchangeEnd(), LevelData< FArrayBox >::exchangeNoOverlap(), LevelData< FArrayBox >::LevelData(), LevelData< FArrayBox >::localCopyTo(), write(), and WriteMultiData< T >::writeData().
generalCopyTo() [1/2]
template<class T> void BoxLayoutData< T >::generalCopyTo (const BoxLayout & a_destGrids, LayoutData< std::vector< RefCountedPtr< T > > > & a_dest, const Interval & a_interval, const ProblemDomain & a_domain, const DataFactory< T > & factory = DefaultDataFactory<T>()) const
General data copying operation.
Parameters
a_destGrids BoxLayout for the destination data holder
a_dest return argument. upon completion contains a std::vector of T objects for each Box in a_destGrids that overlaps this->boxLayout()
a_interval range of components to source
a_domain ProblemDomain that this grid and a_destGrids reside on.
factory optional data factory for template classes that have non-trivial construction
Referenced by BoxLayoutData< FArrayBox >::generalCopyTo().
generalCopyTo() [2/2]
template<class T> void BoxLayoutData< T >::generalCopyTo (const BoxLayout & a_destGrids, LayoutData< std::vector< RefCountedPtr< T > > > & a_dest, const Interval & a_interval, const ProblemDomain & a_domain, const Copier & a_copier, const DataFactory< T > & factory = DefaultDataFactory<T>()) const
addTo() [1/2]
template<class T> void BoxLayoutData< T >::addTo (const Interval & a_srcComps, BoxLayoutData< T > & a_dest, const Interval & a_destComps, const ProblemDomain & a_domain) const
Special version of generalCopyTo that performs increment-on-intersection of the destination instead of replacement
Referenced by BoxLayoutData< FArrayBox >::addTo().
addTo() [2/2]
template<class T> void BoxLayoutData< T >::addTo (const Interval & a_srcComps, BoxLayoutData< T > & a_dest, const Interval & a_destComps, const ProblemDomain & a_domain, const Copier & a_copier) const
Special version of generalCopyTo that performs increment-on-intersection of the destination instead of replacement. This version lets the user send in a pre-built Copier.
addToBegin()
template<class T> void BoxLayoutData< T >::addToBegin (const Interval & a_srcComps, BoxLayoutData< T > & a_dest, const Interval & a_destComps, const Copier & a_copier) const
Special version of generalCopyTo that performs increment-on-intersection of the destination instead of replacement. This version of addTo allows for split-phase communication, where you call addToBegin on the source, then addToEnd on the destination. This version requires the user to use a prebuilt Copier and ensure it's lifetime lives past the call to addToEnd (I have my buffers in the Copier)
Referenced by BoxLayoutData< FArrayBox >::addTo().
addToEnd()
template<class T > void BoxLayoutData< T >::addToEnd (const Interval & a_destComps)
you call this on the destination BoxLayoutData, not the source.
Referenced by BoxLayoutData< FArrayBox >::addTo().
apply()
template<class T> void BoxLayoutData< T >::apply (void(*)(const Box &box, int comps, T &t) a_Function) inline virtual
isDefined()
template<class T > bool BoxLayoutData< T >::isDefined () const inline virtual
clear()
template<class T > void BoxLayoutData< T >::clear () inline virtual
setVector()
template<class T> void BoxLayoutData< T >::setVector (const BoxLayoutData< T > & da, const Interval & srcComps, const Interval & destComps) inline protected
Referenced by LevelData< FArrayBox >::define(), and BoxLayoutData< FArrayBox >::define().
allocateGhostVector()
template<class T> void BoxLayoutData< T >::allocateGhostVector (const DataFactory< T > & factory, const IntVect & ghost = IntVect::Zero) inline protected
Referenced by BoxLayoutData< FArrayBox >::BoxLayoutData(), LevelData< FArrayBox >::define(), BoxLayoutData< FArrayBox >::define(), and LevelData< FArrayBox >::LevelData().
makeItSo()
template<class T> void BoxLayoutData< T >::makeItSo (const Interval & a_srcComps, const BoxLayoutData< T > & a_src, BoxLayoutData< T > & a_dest, const Interval & a_destComps, const Copier & a_copier, const LDOperator< T > & a_op = LDOperator<T>(), bool a_printStuff = false) const protected
Referenced by LevelData< FArrayBox >::copyTo(), AliasDataFactory< T >::create(), and LevelData< FArrayBox >::exchange().
makeItSoBegin()
template<class T> void BoxLayoutData< T >::makeItSoBegin (const Interval & a_srcComps, const BoxLayoutData< T > & a_src, BoxLayoutData< T > & a_dest, const Interval & a_destComps, const Copier & a_copier, const LDOperator< T > & a_op = LDOperator<T>(), bool a_printStuff = false) const protected
Referenced by BoxLayoutData< FArrayBox >::addToBegin(), LevelData< FArrayBox >::exchangeBegin(), LevelData< FArrayBox >::exchangeNoOverlap(), and BoxLayoutData< FArrayBox >::makeItSo().
makeItSoLocalCopy()
template<class T> void BoxLayoutData< T >::makeItSoLocalCopy (const Interval & a_srcComps, const BoxLayoutData< T > & a_src, BoxLayoutData< T > & a_dest, const Interval & a_destComps, const Copier & a_copier, const LDOperator< T > & a_op = LDOperator<T>(), bool a_printStuff = false) const protected
Referenced by BoxLayoutData< FArrayBox >::addToBegin(), LevelData< FArrayBox >::exchangeBegin(), LevelData< FArrayBox >::exchangeNoOverlap(), BoxLayoutData< FArrayBox >::makeItSo(), and BoxLayoutData< FArrayBox >::makeItSoBegin().
makeItSoEnd()
template<class T> void BoxLayoutData< T >::makeItSoEnd (const Interval & a_destComps, const LDOperator< T > & a_op = LDOperator<T>(), bool a_printStuff = false) protected
Referenced by BoxLayoutData< FArrayBox >::addToEnd(), LevelData< FArrayBox >::exchangeEnd(), LevelData< FArrayBox >::exchangeNoOverlap(), BoxLayoutData< FArrayBox >::makeItSo(), and BoxLayoutData< FArrayBox >::makeItSoLocalCopy().
completePendingSends()
template<class T > void BoxLayoutData< T >::completePendingSends () const protected
Referenced by BoxLayoutData< FArrayBox >::generalCopyTo(), and BoxLayoutData< FArrayBox >::makeItSoEnd().
allocateBuffers()
template<class T> void BoxLayoutData< T >::allocateBuffers (const BoxLayoutData< T > & a_src, const Interval & a_srcComps, const BoxLayoutData< T > & a_dest, const Interval & a_destComps, const Copier & a_copier, const LDOperator< T > & a_op, bool a_printStuff = false) const protected
Referenced by BoxLayoutData< FArrayBox >::generalCopyTo(), and BoxLayoutData< FArrayBox >::makeItSoBegin().
writeSendDataFromMeIntoBuffers()
template<class T> void BoxLayoutData< T >::writeSendDataFromMeIntoBuffers (const BoxLayoutData< T > & a_src, const Interval & a_srcComps, const LDOperator< T > & a_op) const protected
Referenced by BoxLayoutData< FArrayBox >::generalCopyTo(), and BoxLayoutData< FArrayBox >::makeItSoBegin().
postSendsFromMe()
template<class T > void BoxLayoutData< T >::postSendsFromMe () const protected
Referenced by BoxLayoutData< FArrayBox >::generalCopyTo(), and BoxLayoutData< FArrayBox >::makeItSoBegin().
postReceivesToMe()
template<class T > void BoxLayoutData< T >::postReceivesToMe () const protected
Referenced by BoxLayoutData< FArrayBox >::generalCopyTo(), and BoxLayoutData< FArrayBox >::makeItSoBegin().
unpackReceivesToMe()
template<class T> void BoxLayoutData< T >::unpackReceivesToMe (const Interval & a_destComps, const LDOperator< T > & a_op) protected
Referenced by BoxLayoutData< FArrayBox >::makeItSoEnd(), and BoxLayoutData< FArrayBox >::postReceivesToMe().
unpackReceivesToMe_append()
template<class T> void BoxLayoutData< T >::unpackReceivesToMe_append (LayoutData< std::vector< RefCountedPtr< T > > > & a_dest, const Interval & a_destComps, int ncomp, const DataFactory< T > & factory, const LDOperator< T > & a_op) protected
Referenced by BoxLayoutData< FArrayBox >::generalCopyTo().
Friends And Related Function Documentation
LevelData< T >
template<class T> friend class LevelData< T > friend
Member Data Documentation
m_comps
template<class T> int BoxLayoutData< T >::m_comps protected
Referenced by BoxLayoutData< FArrayBox >::allocateGhostVector(), LevelData< FArrayBox >::apply(), BoxLayoutData< FArrayBox >::apply(), LevelData< FArrayBox >::define(), BoxLayoutData< FArrayBox >::define(), and LevelData< FArrayBox >::LevelData().
m_isdefined
template<class T> bool BoxLayoutData< T >::m_isdefined protected
Referenced by BoxLayoutData< FArrayBox >::BoxLayoutData(), BoxLayoutData< FArrayBox >::clear(), LevelData< FArrayBox >::define(), BoxLayoutData< FArrayBox >::define(), LevelData< FArrayBox >::disjointBoxLayout(), LevelData< FArrayBox >::getBoxes(), BoxLayoutData< FArrayBox >::isDefined(), and LevelData< FArrayBox >::LevelData().
m_buff
template<class T> CopierBuffer* BoxLayoutData< T >::m_buff mutable protected
Referenced by BoxLayoutData< FArrayBox >::allocateBuffers(), BoxLayoutData< FArrayBox >::completePendingSends(), BoxLayoutData< FArrayBox >::generalCopyTo(), BoxLayoutData< FArrayBox >::makeItSoBegin(), BoxLayoutData< FArrayBox >::postReceivesToMe(), BoxLayoutData< FArrayBox >::postSendsFromMe(), BoxLayoutData< FArrayBox >::unpackReceivesToMe(), BoxLayoutData< FArrayBox >::unpackReceivesToMe_append(), and BoxLayoutData< FArrayBox >::writeSendDataFromMeIntoBuffers().
The documentation for this class was generated from the following files:
Chombo_BoxLayoutData.H
Chombo_BoxLayoutDataI.H