Chombo_4: EBCM::IrregFace< order > Class Template Reference
EBCM::IrregFace< order > Class Template Reference
#include <Chombo_EBCM_Graph.H>
Public Member Functions
IndexedMoments< DIM, order > getNormalMoment (const int a_dir) const
void defineAsRegular (pr_vof a_vof)
void print () const
size_t charsize () const
void energize (char *a_outbuf, size_t a_expected_size) const
void linearIn (char *a_inbuf, size_t a_expected_size)
Public Attributes
pr_pt m_pt
IndexedMoments< DIM, order > m_ebfmom
IndexedMoments< DIM, order > m_norm_mom_x
IndexedMoments< DIM, order > m_norm_mom_y
IndexedMoments< DIM, order > m_norm_mom_z
Member Function Documentation
getNormalMoment()
template<int order> IndexedMoments<DIM, order> EBCM::IrregFace< order >::getNormalMoment (const int a_dir) const inline
References pout().
Referenced by EBCM::Algorithm_Framework< ebcm_order >::fillNeumannEBBCRow().
defineAsRegular()
template<int order> void EBCM::IrregFace< order >::defineAsRegular (pr_vof a_vof) inline
References Proto::EBIndex< cent >::m_pt.
print()
template<int order> void EBCM::IrregFace< order >::print () const inline
References pout().
charsize()
template<int order> size_t EBCM::IrregFace< order >::charsize () const inline
energize()
template<int order> void EBCM::IrregFace< order >::energize (char * a_outbuf, size_t a_expected_size) const inline
linearIn()
template<int order> void EBCM::IrregFace< order >::linearIn (char * a_inbuf, size_t a_expected_size) inline
Member Data Documentation
m_pt
template<int order> pr_pt EBCM::IrregFace< order >::m_pt
Referenced by EBCM::Algorithm_Framework< ebcm_order >::getEBSystemMatrix().
m_ebfmom
template<int order> IndexedMoments<DIM, order> EBCM::IrregFace< order >::m_ebfmom
Referenced by EBCM::Algorithm_Framework< ebcm_order >::fillDirichletEBBCRow().
m_norm_mom_x
template<int order> IndexedMoments<DIM, order> EBCM::IrregFace< order >::m_norm_mom_x
m_norm_mom_y
template<int order> IndexedMoments<DIM, order> EBCM::IrregFace< order >::m_norm_mom_y
m_norm_mom_z
template<int order> IndexedMoments<DIM, order> EBCM::IrregFace< order >::m_norm_mom_z
The documentation for this class was generated from the following file:
Chombo_EBCM_Graph.H