Chombo_4: LDOperator< T > Class Template Reference
LDOperator< T > Class Template Reference
#include <Chombo_BoxLayoutData.H>
Public Member Functions
virtual ~LDOperator ()
virtual int size (const T &arg, const Box &b, const Interval &comps) const
virtual void linearOut (const T &arg, void *buf, const Box &R, const Interval &comps) const
virtual void linearIn (T &arg, void *buf, const Box &R, const Interval &comps) const
virtual void op (T &dest, const Box &RegionFrom, const Interval &Cdest, const Box &RegionTo, const T &src, const Interval &Csrc) const
Constructor & Destructor Documentation
~LDOperator()
template<class T> virtual LDOperator< T >::~LDOperator () inline virtual
Member Function Documentation
size()
template<class T> virtual int LDOperator< T >::size (const T & arg, const Box & b, const Interval & comps) const inline virtual
References Interval::begin(), and Interval::size().
Referenced by BoxLayoutData< FArrayBox >::allocateBuffers().
linearOut()
template<class T> virtual void LDOperator< T >::linearOut (const T & arg, void * buf, const Box & R, const Interval & comps) const inline virtual
References Interval::begin(), and Interval::size().
Referenced by BoxLayoutData< FArrayBox >::writeSendDataFromMeIntoBuffers().
linearIn()
template<class T> virtual void LDOperator< T >::linearIn (T & arg, void * buf, const Box & R, const Interval & comps) const inline virtual
Reimplemented in LDaddOp< T >.
References Interval::begin(), and Interval::size().
Referenced by BoxLayoutData< FArrayBox >::unpackReceivesToMe(), and BoxLayoutData< FArrayBox >::unpackReceivesToMe_append().
op()
template<class T> virtual void LDOperator< T >::op (T & dest, const Box & RegionFrom, const Interval & Cdest, const Box & RegionTo, const T & src, const Interval & Csrc) const inline virtual
Reimplemented in LDaddOp< T >.
References MayDay::Abort(), Interval::begin(), CH4_SPMD::linearIn(), LinearizationTest, CH4_SPMD::linearOut(), and Interval::size().
Referenced by BoxLayoutData< FArrayBox >::generalCopyTo(), and BoxLayoutData< FArrayBox >::makeItSoLocalCopy().
The documentation for this class was generated from the following file:
Chombo_BoxLayoutData.H