Chombo_4: Proto::IFSlicer< dim > Class Template Reference
Proto::IFSlicer< dim > Class Template Reference
#include <Proto_IFSlicer.H>
Public Member Functions
IFSlicer ()
null constructor
IFSlicer (const IFSlicer< dim > &a_IFSlicer)
copy constructor
IFSlicer (const shared_ptr< IFSlicer< dim+1 > > &a_slicer, const int &a_fixedComp, const double &a_fixedValue)
makes a reduced IFSlicer
void setParams (const shared_ptr< IFSlicer< dim+1 > > &a_slicer, const int &a_fixedComp, const double &a_fixedValue)
virtual ~IFSlicer ()
destructor
virtual double value (const IndexTM< int, dim > &a_partialDerivative, const IndexTM< double, dim > &a_point) const
Return the partial derivative evaluated at a_point.
Protected Attributes
shared_ptr< IFSlicer< dim+1 > > m_IFSlicer
int m_fixedComp
double m_fixedValue
Private Member Functions
IFSlicer< dim > & operator= (const IFSlicer< dim > &)
Constructor & Destructor Documentation
IFSlicer() [1/3]
template<int dim> Proto::IFSlicer< dim >::IFSlicer () inline
null constructor
null constructor
References LARGEINTVAL, and LARGEREALVAL.
Referenced by Proto::IFSlicer< dim >::IFSlicer().
IFSlicer() [2/3]
template<int dim> Proto::IFSlicer< dim >::IFSlicer (const IFSlicer< dim > & a_IFSlicer) inline
copy constructor
copy constructor
References Proto::IFSlicer< dim >::IFSlicer(), Proto::IFSlicer< dim >::m_fixedComp, Proto::IFSlicer< dim >::m_fixedValue, and Proto::IFSlicer< dim >::m_IFSlicer.
IFSlicer() [3/3]
template<int dim> Proto::IFSlicer< dim >::IFSlicer (const shared_ptr< IFSlicer< dim+1 > > & a_slicer, const int & a_fixedComp, const double & a_fixedValue) inline
makes a reduced IFSlicer
makes a reduced IFSlicer
References Proto::IFSlicer< dim >::setParams().
~IFSlicer()
template<int dim> Proto::IFSlicer< dim >::~IFSlicer () inline virtual
destructor
destructor
Member Function Documentation
setParams()
template<int dim> void Proto::IFSlicer< dim >::setParams (const shared_ptr< IFSlicer< dim+1 > > & a_slicer, const int & a_fixedComp, const double & a_fixedValue) inline
Referenced by Proto::IFSlicer< dim >::IFSlicer().
value()
template<int dim> double Proto::IFSlicer< dim >::value (const IndexTM< int, dim > & a_partialDerivative, const IndexTM< double, dim > & a_point) const inline virtual
Return the partial derivative evaluated at a_point.
Represent the partial derivative as a list of integers. Return the partial derivative evaluated at a_point.
References LARGEREALVAL.
Referenced by Proto::NormalDerivativeNew< dim >::calculatePhiDerivs().
operator=()
template<int dim> IFSlicer<dim>& Proto::IFSlicer< dim >::operator= (const IFSlicer< dim > &) private
Member Data Documentation
m_IFSlicer
template<int dim> shared_ptr<IFSlicer<dim + 1> > Proto::IFSlicer< dim >::m_IFSlicer protected
Referenced by Proto::IFSlicer< dim >::IFSlicer().
m_fixedComp
template<int dim> int Proto::IFSlicer< dim >::m_fixedComp protected
Referenced by Proto::IFSlicer< dim >::IFSlicer().
m_fixedValue
template<int dim> double Proto::IFSlicer< dim >::m_fixedValue protected
Referenced by Proto::IFSlicer< dim >::IFSlicer().
The documentation for this class was generated from the following files:
Proto_IFSlicer.H
Proto_IFSlicerImplem.H