Chombo_4: FArrayBox Class Reference
FArrayBox Class Reference
#include <Chombo_FArrayBox.H>
Public Member Functions
FArrayBox ()
FArrayBox (const Box &a_box, int a_ncomp, Real *a_alias)
FArrayBox (const Box &a_box, int a_ncomp)
FArrayBox (const Interval &a_comps, FArrayBox &a_original)
virtual void define (const Box &a_box, int a_ncomp, Real *a_alias=NULL)
virtual ~FArrayBox ()
virtual void define (const Interval &a_comps, FArrayBox &a_original)
virtual void define (const Interval &a_comps, BaseFab< Real > &a_original)
virtual void resize (const Box &a_box, int a_comps, Real *a_alias=NULL)
FArrayBox (FArrayBox &&a_in)=default
FArrayBox & operator= (FArrayBox &&a_in)=default
Public Member Functions inherited from BaseFab< Real >
virtual long offset (const IntVect &a_iv, const int &a_ivar) const
{ constructors, destructor and defines}
BaseFab ()
BaseFab (const Box &a_bx, int a_n, Real *a_alias=NULL)
BaseFab (const Interval &a_comps, BaseFab< Real > &a_original)
BaseFab (BaseFab< Real > &&a_in) noexcept
move constructor
virtual ~BaseFab ()
void resize (const Box &a_b, int a_n=1, Real *a_alias=NULL)
void define ()
void clear ()
int nComp () const
{ accessors}
const Box & box () const
IntVect size () const
virtual size_t size (const Box &a_box, const Interval &a_comps) const
{ linearization functions}
const IntVect & smallEnd () const
const IntVect & bigEnd () const
Interval interval () const
BaseFab< Real > & operator= (BaseFab< Real > &&) noexcept
move assignment
Real & operator() (const IntVect &a_p, int a_N)
Real & operator() (const IntVect &a_p)
const Real & operator() (const IntVect &p, int N) const
const Real & operator() (const IntVect &p) const
void getVal (Real *a_data, const IntVect &a_pos, int a_N, int a_numcomp) const
void getVal (Real *a_data, const IntVect &a_pos) const
const int * loVect () const
{ Fortran interface functions}
const int * hiVect () const
const int * nCompPtr () const
Real * dataPtr (int a_n=0)
const Real * dataPtr (int a_n=0) const
bool contains (const BaseFab< Real > &a_fab) const
{ comparison functions}
bool contains (const Box &a_bx) const
void setVal (Real a_x, const Box &a_bx, int a_nstart, int a_numcomp)
{ data modification functions}
void setVal (Real a_x, const Box &a_bx, int a_n)
void setVal (Real a_x, int a_n)
void setVal (Real a_x)
BaseFab< Real > & copy (const BaseFab< Real > &a_src, const Box &a_srcbox, int a_srccomp, const Box &a_destbox, int a_destcomp, int a_numcomp)
BaseFab< Real > & copy (const BaseFab< Real > &a_src, const ::Proto::Box &a_srcbox, int a_srccomp, const ::Proto::Box &a_dstbox, int a_dstcomp, int a_numcomp)
BaseFab< Real > & copy (const BaseFab< Real > &a_src, int a_srccomp, int a_destcomp, int a_numcomp=1)
BaseFab< Real > & copy (const BaseFab< Real > &a_src, const Box &a_destbox)
BaseFab< Real > & copy (const BaseFab< Real > &a_src)
void copy (const Box &a_RegionFrom, const Interval &a_Cdest, const Box &a_RegionTo, const BaseFab< Real > &a_src, const Interval &a_Csrc)
BaseFab< Real > & shift (const IntVect &a_v)
{ domain modification functions}
BaseFab< Real > & shift (int a_idir, int a_ncells)
BaseFab< Real > & shiftHalf (int a_dir, int a_numHalfs)
BaseFab< Real > & shiftHalf (const IntVect &a_v)
virtual size_t charsize (const ::Proto::Box &a_bx, unsigned int a_startcomp, unsigned int a_numcomps) const
this DOES include sizeof(T)
virtual void linearOut (void *a_buf, const Box &a_R, const Interval &a_comps) const
virtual void linearOut (void *a_buf, const ::Proto::Box &a_bx, unsigned int a_startcomp, unsigned int a_numcomps) const
void linearOut (void *a_buf) const
These functions are required for broadcast & gather.
virtual void * linearOut2 (void *a_buf, const Box &a_R, const Interval &a_comps) const
Same as linearOut, but returns the current location in the buffer.
virtual void linearIn (void *a_buf, const Box &a_R, const Interval &a_comps)
virtual void linearIn (void *a_buf, const ::Proto::Box &a_bx, unsigned int a_startcomp, unsigned int a_numcomps)
void linearIn (const void *const a_buf)
virtual void * linearIn2 (void *a_buf, const Box &a_R, const Interval &a_comps)
int linearSize (void) const
void degenerate (BaseFab< Real > &a_slice, const SliceSpec &a_sliceSpec) const
bool isAliased () const
int test ()
Protected Member Functions
virtual void performCopy (const BaseFab< Real > &a_src, const Box &a_srcbox, int a_srccomp, const Box &a_destbox, int a_destcomp, int a_numcomp)
Protected Member Functions inherited from BaseFab< Real >
void define ()
void undefine ()
void undefine ()
void performSetVal (Real a_x, const Box &a_bx, int a_nstart, int a_numcomp)
Additional Inherited Members
Static Public Member Functions inherited from BaseFab< Real >
static int preAllocatable ()
static int memTypeAllocation ()
static int test ()
regression test
static int testBoxAndComp ()
regression test
Static Protected Member Functions inherited from BaseFab< Real >
static std::string name ()
Protected Attributes inherited from BaseFab< Real >
Box m_domain
int m_nvar
long m_numpts
long m_truesize
Real *__restrict m_dptr
bool m_aliased
Detailed Description
Fortran Array Boxes (generally called FABs) are objects constructed to interface with arrays in Fortran. Useful operations can be performed upon FABs in C++, and they provide a convenient interface to Fortran when it is necessary to retreat into that language for doing arithmetic operations when performance matters.
FArrayBox is derived from BaseFab<Real>. FArrayBox adds additional useful capabilities which make sense for Real types, such as I/O and L**p norms.
The C pre-processor macro `CH_SPACEDIM' must be defined to use this class. The internal precision of FArrayBox objects is set by defining either `CH_USE_FLOAT' or `CH_USE_DOUBLE'
This class does NOT provide a copy constructor or assignment operator.
Constructor & Destructor Documentation
FArrayBox() [1/5]
FArrayBox::FArrayBox ()
Constructs an invalid FArrayBox with no memory.
Referenced by resize().
FArrayBox() [2/5]
FArrayBox::FArrayBox (const Box & a_box, int a_ncomp, Real * a_alias)
Constructs an initial FArrayBox with the data space allocated but not inititialized. a_ncomp is the number of components (variables) at each data point in the Box.
FArrayBox() [3/5]
FArrayBox::FArrayBox (const Box & a_box, int a_ncomp)
FArrayBox() [4/5]
FArrayBox::FArrayBox (const Interval & a_comps, FArrayBox & a_original) inline
Construct an aliaed FArrayBox. See BaseFab class for details.
~FArrayBox()
virtual FArrayBox::~FArrayBox () virtual
The (virtual) destructor.
Referenced by define().
FArrayBox() [5/5]
FArrayBox::FArrayBox (FArrayBox && a_in) default
Member Function Documentation
define() [1/3]
virtual void FArrayBox::define (const Box & a_box, int a_ncomp, Real * a_alias = NULL) inline virtual
Defines FArrayBox with the data space allocated but not inititialized. a_ncomp is the number of components (variables) at each data point in the Box.
Reimplemented from BaseFab< Real >.
References BaseFab< T >::define(), and ~FArrayBox().
define() [2/3]
virtual void FArrayBox::define (const Interval & a_comps, FArrayBox & a_original) inline virtual
Constructs an 'aliased' BaseFab of the requested interval of the argument BaseFab. This BaseFab does not allocate any memory, but sets its data pointer into the memory pointed to by the argument BaseFab. It is the users responsiblity to ensure this aliased BaseFab is not used after the original BaseFab has deleted its data ptr (resize, define(..) called, or destruction, etc.).
This aliased BaseFab will also generate side effects (modifying the values of data in one will modify the other's data).
This aliased BaseFab will have a_comps.size() components, starting at zero.
References BaseFab< T >::define().
define() [3/3]
virtual void FArrayBox::define (const Interval & a_comps, BaseFab< Real > & a_original) inline virtual
This is here only to make the Intel compiler stop warning about partial override.
Reimplemented from BaseFab< Real >.
References BaseFab< T >::define().
resize()
virtual void FArrayBox::resize (const Box & a_box, int a_comps, Real * a_alias = NULL) inline virtual
override resize. I'm going to try and get rid of this function in the future (bvs)
References FArrayBox(), operator=(), performCopy(), and BaseFab< T >::resize().
operator=()
FArrayBox& FArrayBox::operator= (FArrayBox && a_in) default
Referenced by resize().
performCopy()
virtual void FArrayBox::performCopy (const BaseFab< Real > & a_src, const Box & a_srcbox, int a_srccomp, const Box & a_destbox, int a_destcomp, int a_numcomp) protected virtual
Reimplemented from BaseFab< Real >.
Referenced by resize().
The documentation for this class was generated from the following file:
Chombo_FArrayBox.H