Chombo_4: EBCM::EBCM_Graph< order > Class Template Reference
EBCM::EBCM_Graph< order > Class Template Reference
#include <Chombo_EBCM_Graph.H>
Public Types
typedef Chombo4::GeometryService< order > ch_geoserv
Speaking of which,.
typedef EBCM_Volu< order > ebcm_volu
Public Member Functions
EBCM_Graph ()
void define (const shared_ptr< ch_geoserv > &a_geoserv, const ch_box &a_domain, const ch_datind &a_dit, const double &a_dx, int a_ghost, bool a_mergeSmallCells, bool a_printStuff)
bool isRegular (pr_pt a_pt) const
bool isCovered (pr_pt a_pt) const
bool hasIrregular () const
void energize (char *a_buf, size_t a_expected_size, bool a_printStuff=false) const
serialization routines
std::size_t charsize (const ch_box &a_bx, unsigned int a_startcomp, unsigned int a_numcomps, bool a_printStuff=false) const
Returns the size of the byte stream.
int nComp () const
blame it all on MPI
EBCM_Graph (void *a_buf, size_t a_expectedSize, bool a_printStuff=false)
void copy (const EBCM_Graph &a_src, const ch_box &a_srcBox, unsigned int a_srcComp, const ch_box &a_destBox, unsigned int a_destComp, unsigned int a_numcomp)
void linearIn (char *a_buf, size_t a_expectedSize, const ch_box &a_bx, unsigned int a_startcomp, unsigned int a_numcomps, bool a_printStuff=false)
this is for MPI communication
void linearOut (char *a_buf, size_t a_expectedSize, const ch_box &a_bx, unsigned int a_startcomp, unsigned int a_numcomps, bool a_printStuff=false) const
this is for MPI communication
void copy (const EBCM_Graph &a_src, const ch_box &a_region)
for exchange. checks over box and adds volumes as needed from source.
void unsparsify ()
ebcm_volu getVolumeCoveringPoint (const pr_pt &a_pt) const
Static Public Member Functions
static int unpackEBDescription (shared_ptr< set< pr_vof > > &a_soluVolumes, const pr_ebgrap &a_graph)
static void getShifts (IndexTM< double, DIM > &a_shiftOne, IndexTM< double, DIM > &a_shiftTwo, const ebcm_volu &a_volMer, const ebcm_volu &a_volOne, const ebcm_volu &a_volTwo)
code that fills EBCM_Volu objects
static void shiftAndMergeVolumeData (ebcm_volu &a_volMer, const ebcm_volu &a_volOne, const ebcm_volu &a_volTwo)
static void shiftAndMergeIrregData (ebcm_volu &a_volMer, const ebcm_volu &a_volOne, const ebcm_volu &a_volTwo)
template<CENTERING cent>
static void addAllOfFirstNotInSecondToThird (vector< EBCM_Face< cent, order > > &a_merged, const vector< EBCM_Face< cent, order > > &a_vecOne, const vector< EBCM_Face< cent, order > > &a_vecTwo)
template<CENTERING cent>
static void consolidateFaces (vector< EBCM_Face< cent, order > > &a_merged, const vector< EBCM_Face< cent, order > > &a_vecOne, const vector< EBCM_Face< cent, order > > &a_vecTwo, bool a_printStuff)
static void consolidateFacesAllDirections (ebcm_volu &a_volMer, const ebcm_volu &a_volOne, const ebcm_volu &a_volTwo, bool a_printStuff)
Consolidate in each direction static inline void.
static int mergeTwoVolumesIntoThird (ebcm_volu &a_volMer, const ebcm_volu &a_volOne, const ebcm_volu &a_volTwo, double a_dx, bool a_printStuff)
make EBCM_Volu volMer that has eaten both volOne and volTwo
static bool volumesConnected (const ebcm_volu &a_volOne, const ebcm_volu &a_volTwo)
static ebcm_volu mergeManyIntoOne (const vector< ebcm_volu > &a_many, double a_dx, bool a_printStuff)
static ebcm_volu getRefinedCoarseVolume (vector< pr_vof > &a_vofsEaten, const pr_vof &a_startvof, const shared_ptr< ch_geoserv > &a_geoserv, const ch_box &a_domain, const ch_datind &a_dit, const double &a_dx, const shared_ptr< set< pr_vof > > &a_vofsLeft, const pr_ebgrap &a_graph, bool a_printStuff)
static ebcm_volu createEBCM_Volume (vector< pr_vof > &a_vofsEaten, const pr_vof &a_startvof, const shared_ptr< ch_geoserv > &a_geoserv, const ch_box &a_domain, const ch_datind &a_dit, const double &a_dx, const shared_ptr< set< pr_vof > > &a_vofsLeft, const pr_ebgrap &a_graph, bool a_mergeSmallCells, bool a_printStuff)
static bool getRegularNeighborPoint (pr_pt &a_regpt, const ebcm_volu &a_smallvol, const pr_hbd_int &a_map)
static void fixVolumeEntriesInMap (shared_ptr< pr_hbd_int > &a_map, const shared_ptr< vector< ebcm_volu > > &a_volumes)
put indicies of volumes in correct places in map
static void mergeSmallVolumesWithNeighbors (shared_ptr< vector< ebcm_volu > > &a_volumes, shared_ptr< pr_hbd_int > &a_map, shared_ptr< vector< ebcm_volu > > &a_tooSmall, const shared_ptr< ch_geoserv > &a_geoserv, const ch_box &a_domain, const ch_datind &a_dit, const double &a_dx, const shared_ptr< set< pr_vof > > &a_vofsLeft, const pr_ebgrap &a_graph, bool a_printStuff)
static int makeTheBlobs (shared_ptr< vector< ebcm_volu > > &a_volumes, shared_ptr< pr_hbd_int > &a_map, shared_ptr< set< pr_vof > > &a_inputVoFs, const shared_ptr< ch_geoserv > &a_geoserv, const ch_box &a_domain, const ch_datind &a_dit, const double &a_dx, const pr_ebgrap &a_graph, bool a_mergeSmallCells, bool a_printStuff)
Public Attributes
bool m_defined
Class Data.
bool m_allRegular
bool m_allCovered
double m_dx
ch_box m_domain
ch_box m_grid
shared_ptr< vector< ebcm_volu > > m_volumes
Irregular volume information.
shared_ptr< HostBoxData< int, 1 > > m_map
Detailed Description
template<int order>
class EBCM::EBCM_Graph< order >
Class holds a optionally-merged sparse embedded boundary description.
Member Typedef Documentation
ch_geoserv
template<int order> typedef Chombo4::GeometryService<order> EBCM::EBCM_Graph< order >::ch_geoserv
Speaking of which,.
First a bunch of static functions that will probably be useful in other contexts They are not standalone because I want to use templated typedefs in declarations.
ebcm_volu
template<int order> typedef EBCM_Volu<order> EBCM::EBCM_Graph< order >::ebcm_volu
Constructor & Destructor Documentation
EBCM_Graph() [1/2]
template<int order> EBCM::EBCM_Graph< order >::EBCM_Graph () inline
EBCM_Graph() [2/2]
template<int order> EBCM::EBCM_Graph< order >::EBCM_Graph (void * a_buf, size_t a_expectedSize, bool a_printStuff = false) inline
Defines this object from a byte stream. This has to be symmetric with the energize function. If I could figure out how to force this, I would.
Irregular volume information. The stuff below are only defined if hasIrregular is true (which means allRegular and allCovered are false). or m_allCovered are true. shared_ptr< vector<ebcm_volu > > m_volumes; shared_ptr< HostBoxData<int, 1> > m_map;
The function isIrregular ought to work because we have set m_allRegular and m_allCovered. Do not move this section of code to before that is true.
References EBCM::vector_linearIn().
Member Function Documentation
unpackEBDescription()
template<int order> static int EBCM::EBCM_Graph< order >::unpackEBDescription (shared_ptr< set< pr_vof > > & a_soluVolumes, const pr_ebgrap & a_graph) inline static
unpacks EB description into a fully unstructured set of volumes return value is me anticipating the need for an error code
References Proto::EBIndex< cent >::defineAsRegular(), Proto::EBGraph::getVoFs(), Proto::EBGraph::isCovered(), Proto::EBGraph::isRegular(), and Proto::EBGraph::validBox().
getShifts()
template<int order> static void EBCM::EBCM_Graph< order >::getShifts (IndexTM< double, DIM > & a_shiftOne, IndexTM< double, DIM > & a_shiftTwo, const ebcm_volu & a_volMer, const ebcm_volu & a_volOne, const ebcm_volu & a_volTwo) inline static
code that fills EBCM_Volu objects
Face objects contain moment informaiton Data that needs to be filled:
vector<ebcm_xface > m_xfaceslo; vector<EBCM_Face<YFACE> > m_yfaceslo; vector<EBCM_Face<ZFACE> > m_zfaceslo; vector<ebcm_xface > m_xfaceshi; vector<EBCM_Face<YFACE> > m_yfaceshi; vector<EBCM_Face<ZFACE> > m_zfaceshi; vector<IrregFace<order> > m_ifaces;
only true if it started as a regular cell and never got merged bool m_regular;
centroid location in global space (not relative to cell center) RealVect m_centroid; double m_kappa; //volume fraction IndexedMoments<DIM, order> m_volmom;
used as a unique identifier. Also volume moments are centered around this cell center. Hence dx. Point m_pt; double m_dx vector<Point> m_cells; //all cells marked for this entry. get how far to shift moments when merging two volumes
References EBCM::EBCM_Volu< order >::m_dx, and EBCM::EBCM_Volu< order >::m_pt.
shiftAndMergeVolumeData()
template<int order> static void EBCM::EBCM_Graph< order >::shiftAndMergeVolumeData (ebcm_volu & a_volMer, const ebcm_volu & a_volOne, const ebcm_volu & a_volTwo) inline static
References EBCM::EBCM_Volu< order >::m_volmom, and Proto::IndexedMoments< Dim, P >::shift().
shiftAndMergeIrregData()
template<int order> static void EBCM::EBCM_Graph< order >::shiftAndMergeIrregData (ebcm_volu & a_volMer, const ebcm_volu & a_volOne, const ebcm_volu & a_volTwo) inline static
This does the same thing as mergeFaces (just slap the two vectors together into the third). The moments are all wrong, though, and need to be shifted
References EBCM::EBCM_Volu< order >::m_ifaces.
addAllOfFirstNotInSecondToThird()
template<int order> template<CENTERING cent> static void EBCM::EBCM_Graph< order >::addAllOfFirstNotInSecondToThird (vector< EBCM_Face< cent, order > > & a_merged, const vector< EBCM_Face< cent, order > > & a_vecOne, const vector< EBCM_Face< cent, order > > & a_vecTwo) inline static
consolidateFaces()
template<int order> template<CENTERING cent> static void EBCM::EBCM_Graph< order >::consolidateFaces (vector< EBCM_Face< cent, order > > & a_merged, const vector< EBCM_Face< cent, order > > & a_vecOne, const vector< EBCM_Face< cent, order > > & a_vecTwo, bool a_printStuff) inline static
makes the face centered structures of merged volume volMer from face structures in volOne and volTwo. If we detect matching faces, that is the line over which we are merging and those faces go away. All other faces get thrown into the mix.
References pout().
consolidateFacesAllDirections()
template<int order> static void EBCM::EBCM_Graph< order >::consolidateFacesAllDirections (ebcm_volu & a_volMer, const ebcm_volu & a_volOne, const ebcm_volu & a_volTwo, bool a_printStuff) inline static
Consolidate in each direction static inline void.
References EBCM::EBCM_Volu< order >::m_xfaces, EBCM::EBCM_Volu< order >::m_yfaces, and EBCM::EBCM_Volu< order >::m_zfaces.
mergeTwoVolumesIntoThird()
template<int order> static int EBCM::EBCM_Graph< order >::mergeTwoVolumesIntoThird (ebcm_volu & a_volMer, const ebcm_volu & a_volOne, const ebcm_volu & a_volTwo, double a_dx, bool a_printStuff) inline static
make EBCM_Volu volMer that has eaten both volOne and volTwo
References EBCM::EBCM_Volu< order >::defineDerivedMeasures(), EBCM::EBCM_Volu< order >::m_cells, EBCM::EBCM_Volu< order >::m_pt, and EBCM::EBCM_Volu< order >::m_regular.
volumesConnected()
template<int order> static bool EBCM::EBCM_Graph< order >::volumesConnected (const ebcm_volu & a_volOne, const ebcm_volu & a_volTwo) inline static
References EBCM::EBCM_Volu< order >::connected().
mergeManyIntoOne()
template<int order> static ebcm_volu EBCM::EBCM_Graph< order >::mergeManyIntoOne (const vector< ebcm_volu > & a_many, double a_dx, bool a_printStuff) inline static
Recursive function that merges a vector of volumes into a single volume. Fails with MayDay::Error if the vector is not has disconnected components.
References MayDay::Error().
getRefinedCoarseVolume()
template<int order> static ebcm_volu EBCM::EBCM_Graph< order >::getRefinedCoarseVolume (vector< pr_vof > & a_vofsEaten, const pr_vof & a_startvof, const shared_ptr< ch_geoserv > & a_geoserv, const ch_box & a_domain, const ch_datind & a_dit, const double & a_dx, const shared_ptr< set< pr_vof > > & a_vofsLeft, const pr_ebgrap & a_graph, bool a_printStuff) inline static
This coarsens, then refines the input cell to get a 2x2x2 (at least in cells, some may be covered cells) region merge it all together. This algorithm should be independent of box division decisions because of the blocking factor thing. Absolutely not guaranteed to get kappa >= 1. –dtg
References Proto::EBGraph::getRegion(), Proto::EBGraph::getVoFs(), Proto::EBGraph::isCovered(), Proto::EBGraph::isRegular(), Proto::EBIndex< cent >::m_pt, and pout().
createEBCM_Volume()
template<int order> static ebcm_volu EBCM::EBCM_Graph< order >::createEBCM_Volume (vector< pr_vof > & a_vofsEaten, const pr_vof & a_startvof, const shared_ptr< ch_geoserv > & a_geoserv, const ch_box & a_domain, const ch_datind & a_dit, const double & a_dx, const shared_ptr< set< pr_vof > > & a_vofsLeft, const pr_ebgrap & a_graph, bool a_mergeSmallCells, bool a_printStuff) inline static
Creates volume from EB description. If merger is necessary and called for, it calls for merger. VoFsLeft gets modified by calling function.
References EBCM::EBCM_Volu< order >::defineAsIrregular(), EBCM::EBCM_Volu< order >::defineAsRegular(), Proto::EBGraph::isCovered(), Proto::EBGraph::isRegular(), EBCM::EBCM_Volu< order >::m_kappa, and Proto::EBIndex< cent >::m_pt.
getRegularNeighborPoint()
template<int order> static bool EBCM::EBCM_Graph< order >::getRegularNeighborPoint (pr_pt & a_regpt, const ebcm_volu & a_smallvol, const pr_hbd_int & a_map) inline static
References Proto::HostBoxData< data_t, ncomp >::box(), and EBCM::EBCM_Volu< order >::m_pt.
fixVolumeEntriesInMap()
template<int order> static void EBCM::EBCM_Graph< order >::fixVolumeEntriesInMap (shared_ptr< pr_hbd_int > & a_map, const shared_ptr< vector< ebcm_volu > > & a_volumes) inline static
put indicies of volumes in correct places in map
mergeSmallVolumesWithNeighbors()
template<int order> static void EBCM::EBCM_Graph< order >::mergeSmallVolumesWithNeighbors (shared_ptr< vector< ebcm_volu > > & a_volumes, shared_ptr< pr_hbd_int > & a_map, shared_ptr< vector< ebcm_volu > > & a_tooSmall, const shared_ptr< ch_geoserv > & a_geoserv, const ch_box & a_domain, const ch_datind & a_dit, const double & a_dx, const shared_ptr< set< pr_vof > > & a_vofsLeft, const pr_ebgrap & a_graph, bool a_printStuff) inline static
Modifies a_volumes in place by merging all of the entries in a_tooSmall to their neighbors found in a_volumes. a_volumes should not change in size but some of its entries will get fatter.
Remember which members of inputVols get used in merger so we do not double add them to a_volumes
Add into a_volumes any inputs that were not used in merging. The merged ones are already in a_volumes.
References EBCM::EBCM_Volu< order >::defineAsRegular(), MayDay::Error(), EBCM::EBCM_Volu< order >::m_cells, and pout().
makeTheBlobs()
template<int order> static int EBCM::EBCM_Graph< order >::makeTheBlobs (shared_ptr< vector< ebcm_volu > > & a_volumes, shared_ptr< pr_hbd_int > & a_map, shared_ptr< set< pr_vof > > & a_inputVoFs, const shared_ptr< ch_geoserv > & a_geoserv, const ch_box & a_domain, const ch_datind & a_dit, const double & a_dx, const pr_ebgrap & a_graph, bool a_mergeSmallCells, bool a_printStuff) inline static
Translate all this mixed stuff into sparse representation that we actually store
two pass merger algorithm. merge on coarsened cell then try to find neighbors
References Proto::EBGraph::getRegion(), Proto::EBGraph::isIrregular(), Proto::EBGraph::isRegular(), EBCM::EBCM_Volu< order >::m_kappa, min(), and pout().
define()
template<int order> void EBCM::EBCM_Graph< order >::define (const shared_ptr< ch_geoserv > & a_geoserv, const ch_box & a_domain, const ch_datind & a_dit, const double & a_dx, int a_ghost, bool a_mergeSmallCells, bool a_printStuff) inline
take all EB stuff and make it into an irregular grid without prejudice about regular or irregular
isRegular()
template<int order> bool EBCM::EBCM_Graph< order >::isRegular (pr_pt a_pt) const inline
Referenced by EBCM::EBCM_Graph< order >::copy(), and EBCM::SubVolumeVector< order >::SubVolumeVector().
isCovered()
template<int order> bool EBCM::EBCM_Graph< order >::isCovered (pr_pt a_pt) const inline
Referenced by EBCM::EBCM_Graph< order >::copy().
hasIrregular()
template<int order> bool EBCM::EBCM_Graph< order >::hasIrregular () const inline
Referenced by EBCM::SubVolumeVector< order >::SubVolumeVector().
energize()
template<int order> void EBCM::EBCM_Graph< order >::energize (char * a_buf, size_t a_expected_size, bool a_printStuff = false) const inline
serialization routines
Fills byte stream from with all the data from this object.
Irregular volume information. The stuff below are only defined if hasIrregular is true (which means allRegular and allCovered are false). or m_allCovered are true. shared_ptr< vector<ebcm_volu > > m_volumes; shared_ptr< HostBoxData<int, 1> > m_map;
References EBCM::vector_charsize(), and EBCM::vector_energize().
charsize()
template<int order> std::size_t EBCM::EBCM_Graph< order >::charsize (const ch_box & a_bx, unsigned int a_startcomp, unsigned int a_numcomps, bool a_printStuff = false) const inline
Returns the size of the byte stream.
Irregular volume information. The stuff below are only defined if hasIrregular is true (which means allRegular and allCovered are false). or m_allCovered are true. shared_ptr< vector<ebcm_volu > > m_volumes; shared_ptr< HostBoxData<int, 1> > m_map;
References ProtoSer::linearCharBufSize(), and EBCM::vector_charsize().
nComp()
template<int order> int EBCM::EBCM_Graph< order >::nComp () const inline
blame it all on MPI
copy() [1/2]
template<int order> void EBCM::EBCM_Graph< order >::copy (const EBCM_Graph< order > & a_src, const ch_box & a_srcBox, unsigned int a_srcComp, const ch_box & a_destBox, unsigned int a_destComp, unsigned int a_numcomp) inline
linearIn()
template<int order> void EBCM::EBCM_Graph< order >::linearIn (char * a_buf, size_t a_expectedSize, const ch_box & a_bx, unsigned int a_startcomp, unsigned int a_numcomps, bool a_printStuff = false) inline
this is for MPI communication
References pout().
linearOut()
template<int order> void EBCM::EBCM_Graph< order >::linearOut (char * a_buf, size_t a_expectedSize, const ch_box & a_bx, unsigned int a_startcomp, unsigned int a_numcomps, bool a_printStuff = false) const inline
this is for MPI communication
References EBCM::EBCM_Face< cent, order >::energize().
copy() [2/2]
template<int order> void EBCM::EBCM_Graph< order >::copy (const EBCM_Graph< order > & a_src, const ch_box & a_region) inline
for exchange. checks over box and adds volumes as needed from source.
end debug
References EBCM::EBCM_Graph< order >::getVolumeCoveringPoint(), EBCM::EBCM_Graph< order >::isCovered(), EBCM::EBCM_Graph< order >::isRegular(), EBCM::EBCM_Graph< order >::m_allCovered, EBCM::EBCM_Graph< order >::m_allRegular, EBCM::EBCM_Volu< order >::m_cells, EBCM::EBCM_Graph< order >::m_defined, and pout().
unsparsify()
template<int order> void EBCM::EBCM_Graph< order >::unsparsify () inline
The function unsparsify recasts this object as a fully mature graph so we can add irregular cells when filling in ghost cell informaiton. This happens in the copy function just as it does in standard EB.
getVolumeCoveringPoint()
template<int order> ebcm_volu EBCM::EBCM_Graph< order >::getVolumeCoveringPoint (const pr_pt & a_pt) const inline
References EBCM::EBCM_Volu< order >::defineAsRegular().
Referenced by EBCM::EBCM_Graph< order >::copy(), and EBCM::PETSc_Framework< ebcm_order >::HelmholtzOp::getLocalStencil().
Member Data Documentation
m_defined
template<int order> bool EBCM::EBCM_Graph< order >::m_defined
Class Data.
I am not bothering with fancy accessor functions. Member data is left in the clear. Use it wisely. Remember the map and the vector are not defined if allRegular or allCovered are true. This should save a ton of memory where there is not much EB. Assignment ought to work but it will be shallow (std::shared_ptr semantics).Whether define function has been called on this object. If m_defined == false, everything else is not defined.
Referenced by EBCM::EBCM_Graph< order >::copy().
m_allRegular
template<int order> bool EBCM::EBCM_Graph< order >::m_allRegular
Referenced by EBCM::EBCM_Graph< order >::copy().
m_allCovered
template<int order> bool EBCM::EBCM_Graph< order >::m_allCovered
Referenced by EBCM::EBCM_Graph< order >::copy().
m_dx
template<int order> double EBCM::EBCM_Graph< order >::m_dx
Referenced by EBCM::Algorithm_Framework< ebcm_order >::neighborhood_t::getBoundaryDerived(), EBCM::Algorithm_Framework< ebcm_order >::neighborhood_t::getFaceInfo(), EBCM::Algorithm_Framework< ebcm_order >::neighborhood_t::neighborhood_t(), and EBCM::SubVolumeVector< order >::SubVolumeVector().
m_domain
template<int order> ch_box EBCM::EBCM_Graph< order >::m_domain
Referenced by EBCM::Algorithm_Framework< ebcm_order >::neighborhood_t::neighborhood_t().
m_grid
template<int order> ch_box EBCM::EBCM_Graph< order >::m_grid
m_volumes
template<int order> shared_ptr< vector<ebcm_volu > > EBCM::EBCM_Graph< order >::m_volumes
Irregular volume information.
We do not store unmerged regular cell volumes. The stuff below is not defined if(m_allRegular or m_allCovered are true (if(m_allRegular || m_allCovered)).This is the meta data and moment information.
Referenced by EBCM::Algorithm_Framework< ebcm_order >::neighborhood_t::getFaceInfo(), and EBCM::SubVolumeVector< order >::SubVolumeVector().
m_map
template<int order> shared_ptr< HostBoxData<int, 1> > EBCM::EBCM_Graph< order >::m_map
The documentation for this class was generated from the following file:
Chombo_EBCM_Graph.H