Chombo_4: Proto::EBHostData< cent, data_t, ncomp > Class Template Reference
Proto::EBHostData< cent, data_t, ncomp > Class Template Reference
Holder for EB data over a box.
#include <Proto_EBHostData.H>
Public Member Functions
EBHostData ()
int nComp () const
virtual ~EBHostData ()
EBDataLoc indexInfo (const EBIndex< cent > &a_index, int a_ivar) const
data_t & operator() (const EBIndex< cent > &a_vof, unsigned int a_ivar)
const data_t & operator() (const EBIndex< cent > &a_vof, unsigned int a_ivar) const
EBHostData (const Box &a_box, bool a_stackAlloc)
needed for Proto::LevelData. meaningless here becasue we need the graph.
template<unsigned int srccomp>
void define (EBHostData< cent, data_t, srccomp > &a_input, unsigned int a_comp)
EBHostData (EBBoxData< cent, data_t, ncomp > &a_input)
void define (EBBoxData< cent, data_t, ncomp > &a_input)
void dataInfo (data_t *&a_dataPtr, size_t &a_datasize, unsigned int a_whichfab) const
for aggstencil mostly. datasize does NOT include sizeof(data_t) (to conform with boxdata::size)
Box box () const
input box is cell centered—semantic is somewhat different depending on centering
EBGraph ebgraph () const
Box inputBox () const
EBHostData (const Box &a_box, const EBGraph &a_graph, bool a_useStack=false)
void define (const Box &a_box, const EBGraph &a_graph, bool a_useStack=false)
HostBoxData< data_t, ncomp > & getRegData ()
HostIrregData< cent, data_t, ncomp > & getIrrData ()
void setVal (data_t val)
void copy (const EBHostData< cent, data_t, ncomp > &a_src, const Box &a_bxFrom, unsigned int isrc, const Box &a_bxTo, unsigned int idst, unsigned int inco)
virtual std::size_t charsize (const Box &a_bx, unsigned int a_startcomp, unsigned int a_numcomps, bool a_printStuff=false) const
this DOES include sizeof(T)
virtual void linearIn (void *a_buf, const size_t a_expectedCharSize, const Box &a_bx, unsigned int a_startcomp, unsigned int a_numcomps, bool a_printStuff=false)
virtual void linearOut (void *a_buf, const size_t a_expectedCharSize, const Box &a_bx, unsigned int a_startcomp, unsigned int a_numcomps, bool a_printStuff=false) const
Static Public Member Functions
static int preAllocatable ()
static int memTypeAllocation ()
Static Public Attributes
static const bool s_stackDefault = false
Protected Member Functions
EBHostData (const EBHostData< cent, data_t, ncomp > &a_src)
EBHostData & operator= (const EBHostData< cent, data_t, ncomp > &a_src)
Protected Attributes
Box m_inputBox
HostBoxData< data_t, ncomp > m_regData
HostIrregData< cent, data_t, ncomp > m_irrData
EBGraph m_graph
Detailed Description
template<CENTERING cent, typename data_t, unsigned int ncomp>
class Proto::EBHostData< cent, data_t, ncomp >
Holder for EB data over a box.
This is the general holder for all EB. if cent == CELL, this is over cells. if cent == BOUNDARY, the data only exists at cut cells if cent == XFACE, YFACE, ZFACE, the data is at coordinate face. All box inputs are assumed to be cll centered
Constructor & Destructor Documentation
EBHostData() [1/5]
template<CENTERING cent, typename data_t, unsigned int ncomp> Proto::EBHostData< cent, data_t, ncomp >::EBHostData () inline
Referenced by Proto::EBHostData< cent, data_t, ncomp >::memTypeAllocation().
~EBHostData()
template<CENTERING cent, typename data_t, unsigned int ncomp> virtual Proto::EBHostData< cent, data_t, ncomp >::~EBHostData () inline virtual
EBHostData() [2/5]
template<CENTERING cent, typename data_t, unsigned int ncomp> Proto::EBHostData< cent, data_t, ncomp >::EBHostData (const Box & a_box, bool a_stackAlloc) inline
needed for Proto::LevelData. meaningless here becasue we need the graph.
EBHostData() [3/5]
template<CENTERING cent, typename data_t, unsigned int ncomp> Proto::EBHostData< cent, data_t, ncomp >::EBHostData (EBBoxData< cent, data_t, ncomp > & a_input) inline
References Proto::EBHostData< cent, data_t, ncomp >::define().
EBHostData() [4/5]
template<CENTERING cent, typename data_t, unsigned int ncomp> Proto::EBHostData< cent, data_t, ncomp >::EBHostData (const Box & a_box, const EBGraph & a_graph, bool a_useStack = false) inline
Input box (a_box) is cell centered. the box is adjusted for centering if it is cent==XFACE YFACE or ZFACE. All irregular data (data at cut cells is held in a sparse holder (IrregData). Regular data is held in a BoxData.
References Proto::EBHostData< cent, data_t, ncomp >::define().
EBHostData() [5/5]
template<CENTERING cent, typename data_t, unsigned int ncomp> Proto::EBHostData< cent, data_t, ncomp >::EBHostData (const EBHostData< cent, data_t, ncomp > & a_src) protected
Member Function Documentation
nComp()
template<CENTERING cent, typename data_t, unsigned int ncomp> int Proto::EBHostData< cent, data_t, ncomp >::nComp () const inline
indexInfo()
template<CENTERING cent, typename data_t, unsigned int ncomp> EBDataLoc Proto::EBHostData< cent, data_t, ncomp >::indexInfo (const EBIndex< cent > & a_index, int a_ivar) const inline
References Proto::EBDataLoc::m_dataID, Proto::EBHostData< cent, data_t, ncomp >::m_irrData, Proto::EBDataLoc::m_offset, Proto::EBIndex< cent >::m_pt, and Proto::EBHostData< cent, data_t, ncomp >::m_regData.
Referenced by Proto::EBHostData< cent, data_t, ncomp >::operator()().
operator()() [1/2]
template<CENTERING cent, typename data_t, unsigned int ncomp> data_t& Proto::EBHostData< cent, data_t, ncomp >::operator() (const EBIndex< cent > & a_vof, unsigned int a_ivar) inline
References Proto::EBHostData< cent, data_t, ncomp >::indexInfo(), Proto::EBDataLoc::m_dataID, Proto::EBHostData< cent, data_t, ncomp >::m_irrData, Proto::EBIndex< cent >::m_pt, and Proto::EBHostData< cent, data_t, ncomp >::m_regData.
operator()() [2/2]
template<CENTERING cent, typename data_t, unsigned int ncomp> const data_t& Proto::EBHostData< cent, data_t, ncomp >::operator() (const EBIndex< cent > & a_vof, unsigned int a_ivar) const inline
References Proto::EBHostData< cent, data_t, ncomp >::indexInfo(), Proto::EBDataLoc::m_dataID, Proto::EBHostData< cent, data_t, ncomp >::m_irrData, Proto::EBIndex< cent >::m_pt, and Proto::EBHostData< cent, data_t, ncomp >::m_regData.
define() [1/3]
template<CENTERING cent, typename data_t, unsigned int ncomp> template<unsigned int srccomp> void Proto::EBHostData< cent, data_t, ncomp >::define (EBHostData< cent, data_t, srccomp > & a_input, unsigned int a_comp) inline
References Proto::EBHostData< cent, data_t, ncomp >::ebgraph(), Proto::EBHostData< cent, data_t, ncomp >::getRegData(), Proto::EBHostData< cent, data_t, ncomp >::m_graph, Proto::EBHostData< cent, data_t, ncomp >::m_inputBox, Proto::EBHostData< cent, data_t, ncomp >::m_irrData, and Proto::EBHostData< cent, data_t, ncomp >::m_regData.
Referenced by Proto::EBHostData< cent, data_t, ncomp >::EBHostData().
define() [2/3]
template<CENTERING cent, typename data_t, unsigned int ncomp> void Proto::EBHostData< cent, data_t, ncomp >::define (EBBoxData< cent, data_t, ncomp > & a_input) inline
References Proto::EBBoxData< cent, data_t, ncomp >::ebgraph(), Proto::EBBoxData< cent, data_t, ncomp >::getIrregData(), Proto::EBBoxData< cent, data_t, ncomp >::getRegData(), Proto::EBHostData< cent, data_t, ncomp >::m_graph, Proto::EBHostData< cent, data_t, ncomp >::m_inputBox, Proto::EBHostData< cent, data_t, ncomp >::m_irrData, and Proto::EBHostData< cent, data_t, ncomp >::m_regData.
dataInfo()
template<CENTERING cent, typename data_t, unsigned int ncomp> void Proto::EBHostData< cent, data_t, ncomp >::dataInfo (data_t *& a_dataPtr, size_t & a_datasize, unsigned int a_whichfab) const inline
for aggstencil mostly. datasize does NOT include sizeof(data_t) (to conform with boxdata::size)
References Proto::EBHostData< cent, data_t, ncomp >::m_irrData, and Proto::EBHostData< cent, data_t, ncomp >::m_regData.
Referenced by Proto::EBStencil< order, data_t, srcCenter, dstCenter >::computeDiagonalWeights(), EBLevelBoxData< cent, NUMCOMPS >::copyToDevice(), and EBLevelBoxData< cent, NUMCOMPS >::copyToHost().
box()
template<CENTERING cent, typename data_t, unsigned int ncomp> Box Proto::EBHostData< cent, data_t, ncomp >::box () const inline
input box is cell centered—semantic is somewhat different depending on centering
References Proto::EBHostData< cent, data_t, ncomp >::m_regData.
ebgraph()
template<CENTERING cent, typename data_t, unsigned int ncomp> EBGraph Proto::EBHostData< cent, data_t, ncomp >::ebgraph () const inline
References Proto::EBHostData< cent, data_t, ncomp >::m_graph.
Referenced by Proto::EBHostData< cent, data_t, ncomp >::define(), Proto::maxCell(), Proto::maxNormCell(), Proto::maxNormFace(), and Proto::minCell().
inputBox()
template<CENTERING cent, typename data_t, unsigned int ncomp> Box Proto::EBHostData< cent, data_t, ncomp >::inputBox () const inline
References Proto::EBHostData< cent, data_t, ncomp >::m_inputBox.
define() [3/3]
template<CENTERING cent, typename data_t, unsigned int ncomp> void Proto::EBHostData< cent, data_t, ncomp >::define (const Box & a_box, const EBGraph & a_graph, bool a_useStack = false) inline
References Proto::EBHostData< cent, data_t, ncomp >::m_graph, Proto::EBHostData< cent, data_t, ncomp >::m_inputBox, Proto::EBHostData< cent, data_t, ncomp >::m_irrData, and Proto::EBHostData< cent, data_t, ncomp >::m_regData.
getRegData()
template<CENTERING cent, typename data_t, unsigned int ncomp> HostBoxData<data_t, ncomp>& Proto::EBHostData< cent, data_t, ncomp >::getRegData () inline
References Proto::EBHostData< cent, data_t, ncomp >::m_regData.
Referenced by Proto::EBHostData< cent, data_t, ncomp >::define(), LevelGeometryService< order >::fillEBFaceAlpha(), fillFaceAlpha(), and LevelGeometryService< order >::fillKappa().
getIrrData()
template<CENTERING cent, typename data_t, unsigned int ncomp> HostIrregData<cent, data_t, ncomp>& Proto::EBHostData< cent, data_t, ncomp >::getIrrData () inline
References Proto::EBHostData< cent, data_t, ncomp >::m_irrData.
Referenced by LevelGeometryService< order >::fillEBFaceAlpha(), fillFaceAlpha(), and LevelGeometryService< order >::fillKappa().
setVal()
template<CENTERING cent, typename data_t, unsigned int ncomp> void Proto::EBHostData< cent, data_t, ncomp >::setVal (data_t val) inline
References Proto::EBHostData< cent, data_t, ncomp >::m_irrData, and Proto::EBHostData< cent, data_t, ncomp >::m_regData.
Referenced by Proto::EBStencil< order, data_t, srcCenter, dstCenter >::computeDiagonalWeights().
copy()
template<CENTERING cent, typename data_t, unsigned int ncomp> void Proto::EBHostData< cent, data_t, ncomp >::copy (const EBHostData< cent, data_t, ncomp > & a_src, const Box & a_bxFrom, unsigned int isrc, const Box & a_bxTo, unsigned int idst, unsigned int inco) inline
References Proto::EBHostData< cent, data_t, ncomp >::m_irrData, and Proto::EBHostData< cent, data_t, ncomp >::m_regData.
charsize()
template<CENTERING cent, typename data_t, unsigned int ncomp> virtual std::size_t Proto::EBHostData< cent, data_t, ncomp >::charsize (const Box & a_bx, unsigned int a_startcomp, unsigned int a_numcomps, bool a_printStuff = false) const inline virtual
this DOES include sizeof(T)
References Proto::EBHostData< cent, data_t, ncomp >::m_irrData, and Proto::EBHostData< cent, data_t, ncomp >::m_regData.
linearIn()
template<CENTERING cent, typename data_t, unsigned int ncomp> virtual void Proto::EBHostData< cent, data_t, ncomp >::linearIn (void * a_buf, const size_t a_expectedCharSize, const Box & a_bx, unsigned int a_startcomp, unsigned int a_numcomps, bool a_printStuff = false) inline virtual
References Proto::EBHostData< cent, data_t, ncomp >::m_irrData, Proto::EBHostData< cent, data_t, ncomp >::m_regData, and pout().
linearOut()
template<CENTERING cent, typename data_t, unsigned int ncomp> virtual void Proto::EBHostData< cent, data_t, ncomp >::linearOut (void * a_buf, const size_t a_expectedCharSize, const Box & a_bx, unsigned int a_startcomp, unsigned int a_numcomps, bool a_printStuff = false) const inline virtual
References Proto::EBHostData< cent, data_t, ncomp >::m_irrData, Proto::EBHostData< cent, data_t, ncomp >::m_regData, and pout().
preAllocatable()
template<CENTERING cent, typename data_t, unsigned int ncomp> static int Proto::EBHostData< cent, data_t, ncomp >::preAllocatable () inline static
memTypeAllocation()
template<CENTERING cent, typename data_t, unsigned int ncomp> static int Proto::EBHostData< cent, data_t, ncomp >::memTypeAllocation () inline static
References Proto::EBHostData< cent, data_t, ncomp >::EBHostData(), and Proto::EBHostData< cent, data_t, ncomp >::operator=().
operator=()
template<CENTERING cent, typename data_t, unsigned int ncomp> EBHostData& Proto::EBHostData< cent, data_t, ncomp >::operator= (const EBHostData< cent, data_t, ncomp > & a_src) protected
Referenced by Proto::EBHostData< cent, data_t, ncomp >::memTypeAllocation().
Member Data Documentation
s_stackDefault
template<CENTERING cent, typename data_t, unsigned int ncomp> const bool Proto::EBHostData< cent, data_t, ncomp >::s_stackDefault = false static
m_inputBox
template<CENTERING cent, typename data_t, unsigned int ncomp> Box Proto::EBHostData< cent, data_t, ncomp >::m_inputBox protected
Referenced by Proto::EBHostData< cent, data_t, ncomp >::define(), and Proto::EBHostData< cent, data_t, ncomp >::inputBox().
m_regData
template<CENTERING cent, typename data_t, unsigned int ncomp> HostBoxData< data_t, ncomp> Proto::EBHostData< cent, data_t, ncomp >::m_regData protected
Referenced by Proto::EBHostData< cent, data_t, ncomp >::box(), Proto::EBHostData< cent, data_t, ncomp >::charsize(), Proto::EBHostData< cent, data_t, ncomp >::copy(), Proto::EBHostData< cent, data_t, ncomp >::dataInfo(), Proto::EBHostData< cent, data_t, ncomp >::define(), Proto::EBHostData< cent, data_t, ncomp >::getRegData(), Proto::EBHostData< cent, data_t, ncomp >::indexInfo(), Proto::EBHostData< cent, data_t, ncomp >::linearIn(), Proto::EBHostData< cent, data_t, ncomp >::linearOut(), Proto::EBHostData< cent, data_t, ncomp >::operator()(), and Proto::EBHostData< cent, data_t, ncomp >::setVal().
m_irrData
template<CENTERING cent, typename data_t, unsigned int ncomp> HostIrregData<cent, data_t, ncomp> Proto::EBHostData< cent, data_t, ncomp >::m_irrData protected
Referenced by Proto::EBHostData< cent, data_t, ncomp >::charsize(), Proto::EBHostData< cent, data_t, ncomp >::copy(), Proto::EBHostData< cent, data_t, ncomp >::dataInfo(), Proto::EBHostData< cent, data_t, ncomp >::define(), Proto::EBHostData< cent, data_t, ncomp >::getIrrData(), Proto::EBHostData< cent, data_t, ncomp >::indexInfo(), Proto::EBHostData< cent, data_t, ncomp >::linearIn(), Proto::EBHostData< cent, data_t, ncomp >::linearOut(), Proto::EBHostData< cent, data_t, ncomp >::operator()(), and Proto::EBHostData< cent, data_t, ncomp >::setVal().
m_graph
template<CENTERING cent, typename data_t, unsigned int ncomp> EBGraph Proto::EBHostData< cent, data_t, ncomp >::m_graph protected
Referenced by Proto::EBHostData< cent, data_t, ncomp >::define(), and Proto::EBHostData< cent, data_t, ncomp >::ebgraph().
The documentation for this class was generated from the following file:
Proto_EBHostData.H