Chombo_4: EBDictionary< order, data_t, srcCenter, dstCenter > Class Template Reference
EBDictionary< order, data_t, srcCenter, dstCenter > Class Template Reference
#include <Chombo_EBDictionary.H>
Classes
struct stencilKey
Public Types
typedef EBStencil< order, data_t, srcCenter, dstCenter > ebstencil_t
typedef IndexedMoments< DIM, order > IndMomDIM
typedef IndexedMoments< DIM-1, order > IndMomSDMinOne
typedef MomentIterator< DIM, order > MomItDIM
typedef MomentIterator< DIM-1, order > MomItSDMinOne
typedef IrregNode< order > inode
typedef HostIrregData< CELL, IndMomDIM, 1 > VoluData
typedef HostIrregData< BOUNDARY, IndMomDIM, 1 > EBFaData
typedef HostIrregData< XFACE, IndMomSDMinOne, 1 > XFacData
typedef HostIrregData< YFACE, IndMomSDMinOne, 1 > YFacData
typedef HostIrregData< ZFACE, IndMomSDMinOne, 1 > ZFacData
typedef HostIrregData< CELL, IndMomDIM, 1 > EBNorData
Public Member Functions
EBDictionary (const shared_ptr< GeometryService< order > > &a_geoserv, const DisjointBoxLayout &a_grids, const Box &a_domain, data_t a_dxPoint, Point a_ghost)
EBDictionary (const shared_ptr< GeometryService< order > > &a_geoserv, const vector< DisjointBoxLayout > &a_grids, const vector< Box > &a_domain, const vector< data_t > &a_dx, Point a_ghost)
maybe we need an amr structure.
int getIndex (const Box &a_dstDomain)
void registerStencil (string a_stencilName, string a_domainBCName[2 *DIM], string a_ebbcName, Box a_srcDomain, Box a_dstDomain, bool needDiagonalWeights=false, Point a_destGrow=Point::Zeros())
register stencil version for existing archived stencils.
void registerStencil (string a_stencilName, string a_ebbcName, const vector< EBIndex< dstCenter > > &a_dstVoFs, const vector< LocalStencil< srcCenter, data_t > > &a_stencil, const Proto::Box &a_srcValid, const Proto::Box &a_dstValid, const Proto::Box &a_srcDomain, const Proto::Box &a_dstDomain, const Point &a_srcGhost, const Point &a_dstGhost, bool a_needDiagonalWeights, unsigned int a_ibox)
register stencil version for algorithm developers
void registerStencilWLS (string a_stencilName, string a_domainBCName[2 *DIM], string a_ebbcName, Box a_srcDomain, Box a_dstDomain, bool needDiagonalWeights=false, Point a_destGrow=Point::Zeros())
void registerStencilWLS (string a_stencilName, string a_domainBCName, string a_ebbcName, Box a_srcDomain, Box a_dstDomain, bool a_needDiagonalWeights=false, Point a_destGrow=Point::Zeros())
void registerStencil (string a_stencilName, string a_domainBCName, string a_ebbcName, Box a_srcDomain, Box a_dstDomain, bool a_needDiagonalWeights=false, Point a_destGrow=Point::Zeros())
shared_ptr< ebstencil_t > getEBStencil (const string &a_stencilName, const string &a_ebbcName, const Box &a_srcDomain, const Box &a_dstDomain, const int &a_boxid)
get the stencil for a particular box at a particular level of refinement
int numLevels () const
void close ()
after this is done, you cannot register any more stencils. This will delete the moment information.
Protected Attributes
vector< vector< map< stencilKey, shared_ptr< ebstencil_t > > > > m_registeredStencils
one per box in the grid
shared_ptr< GeometryService< order > > m_geoserv
Point m_srcGhost
Point m_dstGhost
bool m_isClosed
vector< DisjointBoxLayout > m_grids
vector< Box > m_domain
vector< data_t > m_dx
Private Member Functions
EBDictionary ()
EBDictionary (const EBDictionary< order, data_t, srcCenter, dstCenter > &a_inp)
void operator= (const EBDictionary< order, data_t, srcCenter, dstCenter > &a_inp)
Detailed Description
template<int order, typename data_t, CENTERING srcCenter, CENTERING dstCenter>
class EBDictionary< order, data_t, srcCenter, dstCenter >
makes geometric description from an implicit function.
Member Typedef Documentation
ebstencil_t
template<int order, typename data_t, CENTERING srcCenter, CENTERING dstCenter> typedef EBStencil<order, data_t, srcCenter, dstCenter> EBDictionary< order, data_t, srcCenter, dstCenter >::ebstencil_t
IndMomDIM
template<int order, typename data_t, CENTERING srcCenter, CENTERING dstCenter> typedef IndexedMoments<DIM , order> EBDictionary< order, data_t, srcCenter, dstCenter >::IndMomDIM
IndMomSDMinOne
template<int order, typename data_t, CENTERING srcCenter, CENTERING dstCenter> typedef IndexedMoments<DIM-1, order> EBDictionary< order, data_t, srcCenter, dstCenter >::IndMomSDMinOne
MomItDIM
template<int order, typename data_t, CENTERING srcCenter, CENTERING dstCenter> typedef MomentIterator<DIM , order> EBDictionary< order, data_t, srcCenter, dstCenter >::MomItDIM
MomItSDMinOne
template<int order, typename data_t, CENTERING srcCenter, CENTERING dstCenter> typedef MomentIterator<DIM-1, order> EBDictionary< order, data_t, srcCenter, dstCenter >::MomItSDMinOne
inode
template<int order, typename data_t, CENTERING srcCenter, CENTERING dstCenter> typedef IrregNode<order> EBDictionary< order, data_t, srcCenter, dstCenter >::inode
VoluData
template<int order, typename data_t, CENTERING srcCenter, CENTERING dstCenter> typedef HostIrregData<CELL, IndMomDIM , 1> EBDictionary< order, data_t, srcCenter, dstCenter >::VoluData
EBFaData
template<int order, typename data_t, CENTERING srcCenter, CENTERING dstCenter> typedef HostIrregData<BOUNDARY, IndMomDIM , 1> EBDictionary< order, data_t, srcCenter, dstCenter >::EBFaData
XFacData
template<int order, typename data_t, CENTERING srcCenter, CENTERING dstCenter> typedef HostIrregData<XFACE, IndMomSDMinOne, 1> EBDictionary< order, data_t, srcCenter, dstCenter >::XFacData
YFacData
template<int order, typename data_t, CENTERING srcCenter, CENTERING dstCenter> typedef HostIrregData<YFACE, IndMomSDMinOne, 1> EBDictionary< order, data_t, srcCenter, dstCenter >::YFacData
ZFacData
template<int order, typename data_t, CENTERING srcCenter, CENTERING dstCenter> typedef HostIrregData<ZFACE, IndMomSDMinOne, 1> EBDictionary< order, data_t, srcCenter, dstCenter >::ZFacData
EBNorData
template<int order, typename data_t, CENTERING srcCenter, CENTERING dstCenter> typedef HostIrregData<CELL , IndMomDIM , 1> EBDictionary< order, data_t, srcCenter, dstCenter >::EBNorData
Constructor & Destructor Documentation
EBDictionary() [1/4]
template<int order, typename data_t , CENTERING srcCenter, CENTERING dstCenter> EBDictionary< order, data_t, srcCenter, dstCenter >::EBDictionary (const shared_ptr< GeometryService< order > > & a_geoserv, const DisjointBoxLayout & a_grids, const Box & a_domain, data_t a_dx, Point a_ghost)
This interface is for a single level a_ghost is the number of ghost cells your data will hold. It must be at least as big as the stencil span in each direction..
a_ghost is the number of ghost cells your data will hold. It must be at least as big as the stencil span in each direction..
References EBDictionary< order, data_t, srcCenter, dstCenter >::EBDictionary(), and DataIterator::size().
EBDictionary() [2/4]
template<int order, typename data_t , CENTERING srcCenter, CENTERING dstCenter> EBDictionary< order, data_t, srcCenter, dstCenter >::EBDictionary (const shared_ptr< GeometryService< order > > & a_geoserv, const vector< DisjointBoxLayout > & a_grids, const vector< Box > & a_domain, const vector< data_t > & a_dx, Point a_ghost)
maybe we need an amr structure.
References EBDictionary< order, data_t, srcCenter, dstCenter >::registerStencilWLS(), and DataIterator::size().
EBDictionary() [3/4]
template<int order, typename data_t, CENTERING srcCenter, CENTERING dstCenter> EBDictionary< order, data_t, srcCenter, dstCenter >::EBDictionary () private
Referenced by EBDictionary< order, data_t, srcCenter, dstCenter >::EBDictionary().
EBDictionary() [4/4]
template<int order, typename data_t, CENTERING srcCenter, CENTERING dstCenter> EBDictionary< order, data_t, srcCenter, dstCenter >::EBDictionary (const EBDictionary< order, data_t, srcCenter, dstCenter > & a_inp) private
Member Function Documentation
getIndex()
template<int order, typename data_t, CENTERING srcCenter, CENTERING dstCenter> int EBDictionary< order, data_t, srcCenter, dstCenter >::getIndex (const Box & a_dstDomain) inline
References MayDay::Error().
registerStencil() [1/3]
template<int order, typename data_t , CENTERING srcCenter, CENTERING dstCenter> void EBDictionary< order, data_t, srcCenter, dstCenter >::registerStencil (string a_stencilName, string a_domainBCName[2 *DIM], string a_ebbcName, Box a_srcDomain, Box a_dstDomain, bool needDiagonalWeights = false, Point a_destGrow = Point::Zeros()) inline
register stencil version for existing archived stencils.
diagonal weights are for relaxation–expensive to compute so leave them out if you do not need them dest grow is how many cells to grow valid box for destination.
This is the registerStencil a user ought to use if she wants a known, named, and archived stencil. All the existing stencils have a corresponding entry in StencilNames. If the stencil name does not exist in the EBStencilArchive, that is a run time error.
References EBDictionary< order, data_t, srcCenter, dstCenter >::getEBStencil(), EBDictionary< order, data_t, srcCenter, dstCenter >::stencilKey::m_ebbcName, EBDictionary< order, data_t, srcCenter, dstCenter >::stencilKey::m_stencilName, and DataIterator::size().
Referenced by EBDictionary< order, data_t, srcCenter, dstCenter >::registerStencil(), and EBDictionary< order, data_t, srcCenter, dstCenter >::registerStencilWLS().
registerStencil() [2/3]
template<int order, typename data_t, CENTERING srcCenter, CENTERING dstCenter> void EBDictionary< order, data_t, srcCenter, dstCenter >::registerStencil (string a_stencilName, string a_ebbcName, const vector< EBIndex< dstCenter > > & a_dstVoFs, const vector< LocalStencil< srcCenter, data_t > > & a_stencil, const Proto::Box & a_srcValid, const Proto::Box & a_dstValid, const Proto::Box & a_srcDomain, const Proto::Box & a_dstDomain, const Point & a_srcGhost, const Point & a_dstGhost, bool a_needDiagonalWeights, unsigned int a_ibox) inline
register stencil version for algorithm developers
If you know what stencil you want and you just want to use EBStencil to execute the stencil, use this registerStencil option. Only the AggStencil bit will be executed so there has to be an entry corresponding to every cell for which you want to have an answer. You have to call this for every box as well.
References ProtoCh::getBox(), EBDictionary< order, data_t, srcCenter, dstCenter >::stencilKey::m_ebbcName, EBDictionary< order, data_t, srcCenter, dstCenter >::stencilKey::m_stencilName, and EBDictionary< order, data_t, srcCenter, dstCenter >::registerStencil().
registerStencilWLS() [1/2]
template<int order, typename data_t , CENTERING srcCenter, CENTERING dstCenter> void EBDictionary< order, data_t, srcCenter, dstCenter >::registerStencilWLS (string a_stencilName, string a_domainBCName[2 *DIM], string a_ebbcName, Box a_srcDomain, Box a_dstDomain, bool needDiagonalWeights = false, Point a_destGrow = Point::Zeros()) inline
References EBDictionary< order, data_t, srcCenter, dstCenter >::registerStencil().
Referenced by EBDictionary< order, data_t, srcCenter, dstCenter >::EBDictionary().
registerStencilWLS() [2/2]
template<int order, typename data_t, CENTERING srcCenter, CENTERING dstCenter> void EBDictionary< order, data_t, srcCenter, dstCenter >::registerStencilWLS (string a_stencilName, string a_domainBCName, string a_ebbcName, Box a_srcDomain, Box a_dstDomain, bool a_needDiagonalWeights = false, Point a_destGrow = Point::Zeros()) inline
registerStencil() [3/3]
template<int order, typename data_t, CENTERING srcCenter, CENTERING dstCenter> void EBDictionary< order, data_t, srcCenter, dstCenter >::registerStencil (string a_stencilName, string a_domainBCName, string a_ebbcName, Box a_srcDomain, Box a_dstDomain, bool a_needDiagonalWeights = false, Point a_destGrow = Point::Zeros()) inline
getEBStencil()
template<int order, typename data_t , CENTERING srcCenter, CENTERING dstCenter> shared_ptr< EBStencil< order, data_t, srcCenter, dstCenter > > EBDictionary< order, data_t, srcCenter, dstCenter >::getEBStencil (const string & a_stencilName, const string & a_ebbcName, const Box & a_srcDomain, const Box & a_dstDomain, const int & a_boxid) inline
get the stencil for a particular box at a particular level of refinement
References EBDictionary< order, data_t, srcCenter, dstCenter >::stencilKey::m_ebbcName, and EBDictionary< order, data_t, srcCenter, dstCenter >::stencilKey::m_stencilName.
Referenced by EBDictionary< order, data_t, srcCenter, dstCenter >::registerStencil().
numLevels()
template<int order, typename data_t, CENTERING srcCenter, CENTERING dstCenter> int EBDictionary< order, data_t, srcCenter, dstCenter >::numLevels () const inline
close()
template<int order, typename data_t, CENTERING srcCenter, CENTERING dstCenter> void EBDictionary< order, data_t, srcCenter, dstCenter >::close () inline
after this is done, you cannot register any more stencils. This will delete the moment information.
operator=()
template<int order, typename data_t, CENTERING srcCenter, CENTERING dstCenter> void EBDictionary< order, data_t, srcCenter, dstCenter >::operator= (const EBDictionary< order, data_t, srcCenter, dstCenter > & a_inp) private
Member Data Documentation
m_registeredStencils
template<int order, typename data_t, CENTERING srcCenter, CENTERING dstCenter> vector< vector< map< stencilKey, shared_ptr< ebstencil_t> > > > EBDictionary< order, data_t, srcCenter, dstCenter >::m_registeredStencils protected
one per box in the grid
m_geoserv
template<int order, typename data_t, CENTERING srcCenter, CENTERING dstCenter> shared_ptr<GeometryService<order> > EBDictionary< order, data_t, srcCenter, dstCenter >::m_geoserv protected
m_srcGhost
template<int order, typename data_t, CENTERING srcCenter, CENTERING dstCenter> Point EBDictionary< order, data_t, srcCenter, dstCenter >::m_srcGhost protected
m_dstGhost
template<int order, typename data_t, CENTERING srcCenter, CENTERING dstCenter> Point EBDictionary< order, data_t, srcCenter, dstCenter >::m_dstGhost protected
m_isClosed
template<int order, typename data_t, CENTERING srcCenter, CENTERING dstCenter> bool EBDictionary< order, data_t, srcCenter, dstCenter >::m_isClosed protected
m_grids
template<int order, typename data_t, CENTERING srcCenter, CENTERING dstCenter> vector<DisjointBoxLayout> EBDictionary< order, data_t, srcCenter, dstCenter >::m_grids protected
m_domain
template<int order, typename data_t, CENTERING srcCenter, CENTERING dstCenter> vector<Box> EBDictionary< order, data_t, srcCenter, dstCenter >::m_domain protected
m_dx
template<int order, typename data_t, CENTERING srcCenter, CENTERING dstCenter> vector<data_t> EBDictionary< order, data_t, srcCenter, dstCenter >::m_dx protected
The documentation for this class was generated from the following files:
Chombo_EBDictionary.H
Chombo_EBDictionaryImplem.H