Chombo_4: Proto::SecondOrderStencil< order > Class Template Reference
Proto::SecondOrderStencil< order > Class Template Reference
some basic infrastructure to support the second order stuff
#include <Proto_SecondOrderCell.H>
Public Member Functions
virtual ~SecondOrderStencil ()
SecondOrderStencil ()
Static Public Member Functions
static void get2ndOrderDivFStencil (LocalStencil< CELL, double > &a_vofStencil, const EBIndex< CELL > &a_vof, const EBGraph &a_graph, const VoluData &a_voludata, const EBFaData &a_ebfadata, const XFacData &a_xfacdata, const YFacData &a_yfacdata, const ZFacData &a_zfacdata, const Base2ndOrderFlux< XFACE, order > &a_xfaceflux, const Base2ndOrderFlux< YFACE, order > &a_yfaceflux, const Base2ndOrderFlux< ZFACE, order > &a_zfaceflux, string a_dombc[2 *DIM], string a_ebbcName, double a_dx)
static void getDomainBCs (vector< Stencil< double > > a_regStencilBC[2 *DIM], vector< Box > a_BCApplyBoxes[2 *DIM], string a_domainBCName[2 *DIM], const Box &a_validBox, const Box &a_domain, const Point &a_srcGhost)
Private Types
typedef IndexedMoments< DIM, order > IndMomDIM
typedef IndexedMoments< DIM-1, order > IndMomSDMinOne
typedef MomentIterator< DIM, order > MomItDIM
typedef MomentIterator< DIM-1, order > MomItSDMinOne
typedef HostIrregData< CELL, IndMomDIM, 1 > VoluData
typedef HostIrregData< BOUNDARY, IndMomDIM, 1 > EBFaData
typedef HostIrregData< XFACE, IndMomSDMinOne, 1 > XFacData
typedef HostIrregData< YFACE, IndMomSDMinOne, 1 > YFacData
typedef HostIrregData< ZFACE, IndMomSDMinOne, 1 > ZFacData
Detailed Description
template<int order>
class Proto::SecondOrderStencil< order >
some basic infrastructure to support the second order stuff
Member Typedef Documentation
IndMomDIM
template<int order> typedef IndexedMoments<DIM , order> Proto::SecondOrderStencil< order >::IndMomDIM private
IndMomSDMinOne
template<int order> typedef IndexedMoments<DIM-1, order> Proto::SecondOrderStencil< order >::IndMomSDMinOne private
MomItDIM
template<int order> typedef MomentIterator<DIM , order> Proto::SecondOrderStencil< order >::MomItDIM private
MomItSDMinOne
template<int order> typedef MomentIterator<DIM-1, order> Proto::SecondOrderStencil< order >::MomItSDMinOne private
VoluData
template<int order> typedef HostIrregData<CELL , IndMomDIM , 1> Proto::SecondOrderStencil< order >::VoluData private
EBFaData
template<int order> typedef HostIrregData<BOUNDARY, IndMomDIM , 1> Proto::SecondOrderStencil< order >::EBFaData private
XFacData
template<int order> typedef HostIrregData<XFACE, IndMomSDMinOne, 1> Proto::SecondOrderStencil< order >::XFacData private
YFacData
template<int order> typedef HostIrregData<YFACE, IndMomSDMinOne, 1> Proto::SecondOrderStencil< order >::YFacData private
ZFacData
template<int order> typedef HostIrregData<ZFACE, IndMomSDMinOne, 1> Proto::SecondOrderStencil< order >::ZFacData private
Constructor & Destructor Documentation
~SecondOrderStencil()
template<int order> virtual Proto::SecondOrderStencil< order >::~SecondOrderStencil () inline virtual
SecondOrderStencil()
template<int order> Proto::SecondOrderStencil< order >::SecondOrderStencil () inline
Member Function Documentation
get2ndOrderDivFStencil()
template<int order> void Proto::SecondOrderStencil< order >::get2ndOrderDivFStencil (LocalStencil< CELL, double > & a_vofStencil, const EBIndex< CELL > & a_vof, const EBGraph & a_graph, const VoluData & a_voludata, const EBFaData & a_ebfadata, const XFacData & a_xfacdata, const YFacData & a_yfacdata, const ZFacData & a_zfacdata, const Base2ndOrderFlux< XFACE, order > & a_xfaceflux, const Base2ndOrderFlux< YFACE, order > & a_yfaceflux, const Base2ndOrderFlux< ZFACE, order > & a_zfaceflux, string a_dombc[2 *DIM], string a_ebbcName, double a_dx) inline static
References Proto::DirichletEBFlux< order >::calculateWeightingMatrix(), Proto::LocalStencil< cent, data_t >::clear(), Proto::ebp_index(), Proto::Base2ndOrderFlux< cent, order >::getCentroidStencil(), Proto::EBIndex< cent >::getCutFace(), Proto::NeumannEBFlux< order >::getEBFluxStencil(), Proto::DirichletEBFlux< order >::getEBFluxStencil(), Proto::Normalizor< order >::getNormalAndBoundaryArea(), Proto::LocalStencil< cent, data_t >::getValueAtVoF(), Proto::EBGraph::getXFaces(), Proto::EBGraph::getYFaces(), Proto::Normalizor< order >::normalizedBndryMoments(), Proto::Normalizor< order >::normalizedFaceMoments(), and Proto::LocalStencil< cent, data_t >::setBetaWeight().
Referenced by Proto::Poisson2ndOrder< facecent, order >::getFaceCenteredFluxStencil(), and Proto::EBStencilArchive< CELL, CELL, order, double >::getSecondOrderPoissonStencil().
getDomainBCs()
template<int order> void Proto::SecondOrderStencil< order >::getDomainBCs (vector< Stencil< double > > a_regStencilBC[2 *DIM], vector< Box > a_BCApplyBoxes[2 *DIM], string a_domainBCName[2 *DIM], const Box & a_validBox, const Box & a_domain, const Point & a_srcGhost) inline static
References Proto::ebp_index(), Proto::getStenSign(), Box::grow(), and Box::shift().
Referenced by Proto::EBStencilArchive< CELL, fcent, order, double >::getCellToFaceAveStencil(), Proto::EBStencilArchive< CELL, CELL, order, double >::getDomainBCStencil(), Proto::EBStencilArchive< CELL, fcent, order, double >::getMACGradientStencil(), Proto::EBStencilArchive< CELL, CELL, order, double >::getSlopeStencil(), and Proto::getStenSign().
The documentation for this class was generated from the following files:
Proto_SecondOrderCell.H
Proto_SecondOrderCellImplem.H