Chombo_4: LayoutIterator Class Reference
LayoutIterator Class Reference
An Iterator based on a BoxLayout object.
#include <Chombo_LayoutIterator.H>
Public Member Functions
LayoutIterator ()
a null constructed LayoutIterator will return false on ok()
virtual ~LayoutIterator ()
const LayoutIndex & operator() () const
return the index that this iterator is at
LayoutIndex i () const
return a copy of the index that this iterator is at
virtual void operator++ ()
move the iterator to the next Box in the layout
void incr ()
move the iterator to the next Box in the layout
virtual bool ok () const
return true if this iterator is still in its Layout
void begin ()
initialize this iterator to the first Box in its Layout
void reset ()
same as begin()
void end ()
move this iterator to after the last Box in the layout
const LayoutIndex & operator[] (int ivec) const
LayoutIndex & operator[] (int ivec)
Protected Member Functions
LayoutIterator (const BoxLayout &a_boxlayout, const int *a_layoutID)
Protected Attributes
BoxLayout m_layout
RefCountedPtr< std::vector< LayoutIndex > > m_indicies
unsigned int m_current
Friends
class BoxLayout
class DisjointBoxLayout
class TimedDataIterator
Detailed Description
An Iterator based on a BoxLayout object.
An Iterator based on a BoxLayout object. It does not support a dereferencing operation(1), since it is intended to work with all of BoxLayouts, DisjointBoxLayouts, BoxLayoutDatas LevelData's, and any object that is built on top of a BoxLayout object. LayoutIterator accesses the data in a BoxLayout-based object in a NON-data-parallel manner (i.e. every processor iterates through all the Boxes in the BoxLayout). This differs from the DataIterator class.
BoxLayout-based objects can act as the Factory for the LayoutIterator.
(1) STL-speak. not critical for comprehension, but can help people familiar with STL iterators and expecting similar behaviour.
Constructor & Destructor Documentation
LayoutIterator() [1/2]
LayoutIterator::LayoutIterator () inline
a null constructed LayoutIterator will return false on ok()
~LayoutIterator()
virtual LayoutIterator::~LayoutIterator () inline virtual
References operator()().
LayoutIterator() [2/2]
LayoutIterator::LayoutIterator (const BoxLayout & a_boxlayout, const int * a_layoutID) protected
Member Function Documentation
operator()()
const LayoutIndex & LayoutIterator::operator() () const inline
return the index that this iterator is at
References CH_assert, m_current, m_indicies, and ok().
Referenced by i(), DataIterator::i(), DataIterator::operator()(), and ~LayoutIterator().
i()
LayoutIndex LayoutIterator::i () const inline
return a copy of the index that this iterator is at
References operator()(), and operator++().
operator++()
void LayoutIterator::operator++ () inline virtual
move the iterator to the next Box in the layout
References m_current.
Referenced by i().
incr()
void LayoutIterator::incr () inline
move the iterator to the next Box in the layout
References begin(), end(), ok(), and reset().
ok()
bool LayoutIterator::ok () const inline virtual
return true if this iterator is still in its Layout
References m_current, m_layout, and BoxLayout::size().
Referenced by CH4_Data_Choreography::BoxPattern::BoxPattern(), getOffsets(), incr(), and operator()().
begin()
void LayoutIterator::begin () inline
initialize this iterator to the first Box in its Layout
References m_current.
Referenced by CH4_Data_Choreography::BoxPattern::BoxPattern(), and incr().
reset()
void LayoutIterator::reset ()
same as begin()
Referenced by incr().
end()
void LayoutIterator::end ()
move this iterator to after the last Box in the layout
The iterator will be !ok() afterwards.
Referenced by incr().
operator[]() [1/2]
const LayoutIndex& LayoutIterator::operator[] (int ivec) const inline
References m_indicies.
operator[]() [2/2]
LayoutIndex& LayoutIterator::operator[] (int ivec) inline
References m_indicies.
Friends And Related Function Documentation
BoxLayout
friend class BoxLayout friend
DisjointBoxLayout
friend class DisjointBoxLayout friend
TimedDataIterator
friend class TimedDataIterator friend
Member Data Documentation
m_layout
BoxLayout LayoutIterator::m_layout protected
Referenced by DataIterator::getBoxes(), DataIterator::getPeak(), DataIterator::getTime(), ok(), BoxLayout::operator<(), BoxLayout::operator==(), and DataIterator::size().
m_indicies
RefCountedPtr<std::vector<LayoutIndex> > LayoutIterator::m_indicies protected
Referenced by operator()(), and operator[]().
m_current
unsigned int LayoutIterator::m_current protected
Referenced by begin(), ok(), operator()(), and operator++().
The documentation for this class was generated from the following file:
Chombo_LayoutIterator.H