Chombo_4: CH4_Data_Choreography::DistributedData< fabtype_t > Class Template Reference
CH4_Data_Choreography::DistributedData< fabtype_t > Class Template Reference
#include <Chombo_DistributedData.H>
Public Member Functions
DistributedData ()
DistributedData (const Chombo4::DisjointBoxLayout &a_grids, const Chombo4::IntVect &a_ghost, const Chombo4::DataFactory< fabtype_t > &a_factory, bool a_enableStaticCache=false)
void define (const Chombo4::DisjointBoxLayout &a_grids, const Chombo4::IntVect &a_ghost, const Chombo4::DataFactory< fabtype_t > &a_factory, bool a_enableStaticCache=false)
datafactory has an ncomps argument that shall be ignored here
Chombo4::DataIterator dataIterator () const
old leveldata functionality that got used a LOT
virtual ~DistributedData ()
fabtype_t & operator[] (const Chombo4::DataIndex &a_dit)
const fabtype_t & operator[] (const Chombo4::DataIndex &a_dit) const
void exchange (bool a_printStuff=false)
void copyTo (DistributedData &a_dst, bool a_printStuff=false)
IntVect ghostVect () const
Chombo4::DisjointBoxLayout disjointBoxLayout () const
void printGrids () const
Private Member Functions
DistributedData (const DistributedData &a_input)
void operator= (const DistributedData &a_input)
Static Private Member Functions
static void communicate (DistributedData &a_dst, BoxPattern &a_pattern, CommunicationMetaData< fabtype_t > &a_metadataco, DistributedData &a_src, bool a_printStuff, bool a_graphConstructed)
static void doLocalCopiesWithSerialization (DistributedData &a_dst, const DistributedData &a_src, const BoxPattern &a_pattern, bool a_printStuff=false)
static void doLocalCopies (DistributedData &a_dst, const DistributedData &a_src, const BoxPattern &a_pattern, bool a_printStuff=false)
static void doLocalCopiesWithCopy (DistributedData &a_dst, const DistributedData &a_src, const BoxPattern &a_pattern, bool a_printStuff=false)
static MetaDataCache< fabtype_t > & getMetaDataCache ()
Private Attributes
int m_procID
vector< fabtype_t * > m_data
actual data
IntVect m_ghost
Chombo4::DisjointBoxLayout m_grids
bool m_isDefined
bool m_enableStaticCache
bool m_graphConstructed
Detailed Description
template<class fabtype_t>
class CH4_Data_Choreography::DistributedData< fabtype_t >
Data over a union of rectangles. CopyTo only copies to valid data (no ghost). Exchange does the usual thing (copy from valid data in neighboring cells to overlapping ghost cells). Periodic boundary conditions are not supported. All communication is two phase so exchange and copyTo can involve as many as 4*N^2 messages where N is the number of processors. At each stage, communication between two processors is agreggated into one message.
Constructor & Destructor Documentation
DistributedData() [1/3]
template<class fabtype_t> CH4_Data_Choreography::DistributedData< fabtype_t >::DistributedData () inline
Strong construction brings simplicity. I like simplicity. Sometimes I have to use weak construction, anyway to conform to old APIs. Let this be a lesson to you.
DistributedData() [2/3]
template<class fabtype_t> CH4_Data_Choreography::DistributedData< fabtype_t >::DistributedData (const Chombo4::DisjointBoxLayout & a_grids, const Chombo4::IntVect & a_ghost, const Chombo4::DataFactory< fabtype_t > & a_factory, bool a_enableStaticCache = false) inline
DataFactory has an ncomps argument that shall be ignored here. It is a historical artifact that future generations will find fascinating.
~DistributedData()
template<class fabtype_t> virtual CH4_Data_Choreography::DistributedData< fabtype_t >::~DistributedData () inline virtual
DistributedData() [3/3]
template<class fabtype_t> CH4_Data_Choreography::DistributedData< fabtype_t >::DistributedData (const DistributedData< fabtype_t > & a_input) private
Member Function Documentation
define()
template<class fabtype_t> void CH4_Data_Choreography::DistributedData< fabtype_t >::define (const Chombo4::DisjointBoxLayout & a_grids, const Chombo4::IntVect & a_ghost, const Chombo4::DataFactory< fabtype_t > & a_factory, bool a_enableStaticCache = false) inline
datafactory has an ncomps argument that shall be ignored here
dataIterator()
template<class fabtype_t> Chombo4::DataIterator CH4_Data_Choreography::DistributedData< fabtype_t >::dataIterator () const inline
old leveldata functionality that got used a LOT
Referenced by EBLevelBoxData< cent, NUMCOMPS >::copyHostToFAB(), EBLevelFluxData< NUMCOMPS >::copyToDevice(), EBLevelBoxData< cent, NUMCOMPS >::copyToDevice(), EBLevelFluxData< NUMCOMPS >::copyToHost(), and EBLevelBoxData< cent, NUMCOMPS >::copyToHost().
operator[]() [1/2]
template<class fabtype_t> fabtype_t& CH4_Data_Choreography::DistributedData< fabtype_t >::operator[] (const Chombo4::DataIndex & a_dit) inline
operator[]() [2/2]
template<class fabtype_t> const fabtype_t& CH4_Data_Choreography::DistributedData< fabtype_t >::operator[] (const Chombo4::DataIndex & a_dit) const inline
exchange()
template<class fabtype_t> void CH4_Data_Choreography::DistributedData< fabtype_t >::exchange (bool a_printStuff = false) inline
Referenced by EBLevelFluxData< NUMCOMPS >::exchange(), EBLevelBoxData< cent, NUMCOMPS >::exchangeCPUOnly(), and EBLevelBoxData< cent, NUMCOMPS >::exchangeWithGPU().
copyTo()
template<class fabtype_t> void CH4_Data_Choreography::DistributedData< fabtype_t >::copyTo (DistributedData< fabtype_t > & a_dst, bool a_printStuff = false) inline
Referenced by EBLevelFluxData< NUMCOMPS >::copyTo(), EBLevelBoxData< cent, NUMCOMPS >::copyToCPUOnly(), and EBLevelBoxData< cent, NUMCOMPS >::copyToWithGPU().
ghostVect()
template<class fabtype_t> IntVect CH4_Data_Choreography::DistributedData< fabtype_t >::ghostVect () const inline
disjointBoxLayout()
template<class fabtype_t> Chombo4::DisjointBoxLayout CH4_Data_Choreography::DistributedData< fabtype_t >::disjointBoxLayout () const inline
printGrids()
template<class fabtype_t> void CH4_Data_Choreography::DistributedData< fabtype_t >::printGrids () const inline
communicate()
template<class fabtype_t> static void CH4_Data_Choreography::DistributedData< fabtype_t >::communicate (DistributedData< fabtype_t > & a_dst, BoxPattern & a_pattern, CommunicationMetaData< fabtype_t > & a_metadataco, DistributedData< fabtype_t > & a_src, bool a_printStuff, bool a_graphConstructed) inline static private
doLocalCopiesWithSerialization()
template<class fabtype_t> static void CH4_Data_Choreography::DistributedData< fabtype_t >::doLocalCopiesWithSerialization (DistributedData< fabtype_t > & a_dst, const DistributedData< fabtype_t > & a_src, const BoxPattern & a_pattern, bool a_printStuff = false) inline static private
doLocalCopies()
template<class fabtype_t> static void CH4_Data_Choreography::DistributedData< fabtype_t >::doLocalCopies (DistributedData< fabtype_t > & a_dst, const DistributedData< fabtype_t > & a_src, const BoxPattern & a_pattern, bool a_printStuff = false) inline static private
doLocalCopiesWithCopy()
template<class fabtype_t> static void CH4_Data_Choreography::DistributedData< fabtype_t >::doLocalCopiesWithCopy (DistributedData< fabtype_t > & a_dst, const DistributedData< fabtype_t > & a_src, const BoxPattern & a_pattern, bool a_printStuff = false) inline static private
getMetaDataCache()
template<class fabtype_t> static MetaDataCache<fabtype_t>& CH4_Data_Choreography::DistributedData< fabtype_t >::getMetaDataCache () inline static private
operator=()
template<class fabtype_t> void CH4_Data_Choreography::DistributedData< fabtype_t >::operator= (const DistributedData< fabtype_t > & a_input) private
Member Data Documentation
m_procID
template<class fabtype_t> int CH4_Data_Choreography::DistributedData< fabtype_t >::m_procID private
m_data
template<class fabtype_t> vector<fabtype_t*> CH4_Data_Choreography::DistributedData< fabtype_t >::m_data private
actual data
Referenced by CH4_Data_Choreography::DistributedData< EBFluxData< Real, NUMCOMPS > >::communicate().
m_ghost
template<class fabtype_t> IntVect CH4_Data_Choreography::DistributedData< fabtype_t >::m_ghost private
m_grids
template<class fabtype_t> Chombo4::DisjointBoxLayout CH4_Data_Choreography::DistributedData< fabtype_t >::m_grids private
Referenced by CH4_Data_Choreography::DistributedData< EBFluxData< Real, NUMCOMPS > >::copyTo().
m_isDefined
template<class fabtype_t> bool CH4_Data_Choreography::DistributedData< fabtype_t >::m_isDefined private
m_enableStaticCache
template<class fabtype_t> bool CH4_Data_Choreography::DistributedData< fabtype_t >::m_enableStaticCache private
m_graphConstructed
template<class fabtype_t> bool CH4_Data_Choreography::DistributedData< fabtype_t >::m_graphConstructed private
The documentation for this class was generated from the following file:
Chombo_DistributedData.H