Chombo_4: LDaddOp< T > Class Template Reference
LDaddOp< T > Class Template Reference
#include <Chombo_BoxLayoutDataI.H>
Public Member Functions
virtual void op (T &dest, const Box &RegionFrom, const Interval &Cdest, const Box &RegionTo, const T &src, const Interval &Csrc) const
virtual void linearIn (T &arg, void *buf, const Box &R, const Interval &comps) const
Public Member Functions inherited from LDOperator< T >
virtual ~LDOperator ()
virtual int size (const T &arg, const Box &b, const Interval &comps) const
virtual void linearOut (const T &arg, void *buf, const Box &R, const Interval &comps) const
Member Function Documentation
op()
template<class T> virtual void LDaddOp< T >::op (T & dest, const Box & RegionFrom, const Interval & Cdest, const Box & RegionTo, const T & src, const Interval & Csrc) const inline virtual
Reimplemented from LDOperator< T >.
References Interval::begin(), and Interval::size().
linearIn()
template<class T> virtual void LDaddOp< T >::linearIn (T & arg, void * buf, const Box & R, const Interval & comps) const inline virtual
Reimplemented from LDOperator< T >.
References MayDay::Error().
The documentation for this class was generated from the following file:
Chombo_BoxLayoutDataI.H