Chombo_4: EBCM::PETSc_Framework< ebcm_order >::Base_PETSc_Op Class Reference
EBCM::PETSc_Framework< ebcm_order >::Base_PETSc_Op Class Reference abstract
#include <Chombo_EBCM_PETSc_Framework.H>
Public Member Functions
virtual ~Base_PETSc_Op ()
Base_PETSc_Op (const shared_ptr< ebcm_meta > &a_meta_ptr, const int &a_ghost, bool a_print=false)
virtual shared_ptr< local_stencil_t > getLocalStencil (const pr_pt &a_pt, const ebcm_graph &a_graph, bool a_print=false)=0
this gets done by the derived class
Public Attributes
shared_ptr< petsc_mat > m_mat_ptr
shared_ptr< ebcm_data > m_row_map_ptr
shared_ptr< ebcm_meta > m_meta_ptr
int m_ghost
std::vector< int > m_numPtsPerBox
int m_numPtsThisProc
int m_numPtsAllProcs
int m_startPtThisProc
Protected Member Functions
PetscInt createMatrixRowMap (bool a_print=false)
makes m_row_map_ptr (operator uses this to map between volumes and petsc matrix rows)
PetscInt createOperatorPetscMatrix (bool a_print=false)
makes m_mat_ptr (operator uses this to map between volumes and petsc matrix rows)
PetscInt formMatrix (bool a_print=false)
sets the actual values in *m_mat_ptr
Private Member Functions
Base_PETSc_Op ()
banning weak construction but assignment and copy constructors should work fine.
Detailed Description
template<int ebcm_order>
class EBCM::PETSc_Framework< ebcm_order >::Base_PETSc_Op
This is a wrapper around PETSc's ::Mat object. The specfics of the stencil are computed in the derived class. All data is public because this design is cleaner than hiding behind access functions.
Constructor & Destructor Documentation
~Base_PETSc_Op()
template<int ebcm_order> virtual EBCM::PETSc_Framework< ebcm_order >::Base_PETSc_Op::~Base_PETSc_Op () inline virtual
Base_PETSc_Op() [1/2]
template<int ebcm_order> EBCM::PETSc_Framework< ebcm_order >::Base_PETSc_Op::Base_PETSc_Op (const shared_ptr< ebcm_meta > & a_meta_ptr, const int & a_ghost, bool a_print = false) inline
this would be convenient to keep around but it must be temporary as it contains all kinds of moment data that will no longer be necessary once the matrix is defined.
References CH_TIME, and pout().
Base_PETSc_Op() [2/2]
template<int ebcm_order> EBCM::PETSc_Framework< ebcm_order >::Base_PETSc_Op::Base_PETSc_Op () private
banning weak construction but assignment and copy constructors should work fine.
Member Function Documentation
getLocalStencil()
template<int ebcm_order> virtual shared_ptr<local_stencil_t> EBCM::PETSc_Framework< ebcm_order >::Base_PETSc_Op::getLocalStencil (const pr_pt & a_pt, const ebcm_graph & a_graph, bool a_print = false) pure virtual
this gets done by the derived class
Implemented in EBCM::PETSc_Framework< ebcm_order >::HelmholtzOp, and EBCM::PETSc_Framework< ebcm_order >::DummyDerivedOp.
createMatrixRowMap()
template<int ebcm_order> PetscInt EBCM::PETSc_Framework< ebcm_order >::Base_PETSc_Op::createMatrixRowMap (bool a_print = false) inline protected
makes m_row_map_ptr (operator uses this to map between volumes and petsc matrix rows)
References CH4_SPMD::numProc(), pout(), and CH4_SPMD::procID().
createOperatorPetscMatrix()
template<int ebcm_order> PetscInt EBCM::PETSc_Framework< ebcm_order >::Base_PETSc_Op::createOperatorPetscMatrix (bool a_print = false) inline protected
makes m_mat_ptr (operator uses this to map between volumes and petsc matrix rows)
References CH_TIME.
formMatrix()
template<int ebcm_order> PetscInt EBCM::PETSc_Framework< ebcm_order >::Base_PETSc_Op::formMatrix (bool a_print = false) inline protected
sets the actual values in *m_mat_ptr
This is PETSc for (*m_mat)(irow, icol) = weight;
References CH_TIME.
Member Data Documentation
m_mat_ptr
template<int ebcm_order> shared_ptr<petsc_mat> EBCM::PETSc_Framework< ebcm_order >::Base_PETSc_Op::m_mat_ptr
m_row_map_ptr
template<int ebcm_order> shared_ptr<ebcm_data> EBCM::PETSc_Framework< ebcm_order >::Base_PETSc_Op::m_row_map_ptr
m_meta_ptr
template<int ebcm_order> shared_ptr<ebcm_meta> EBCM::PETSc_Framework< ebcm_order >::Base_PETSc_Op::m_meta_ptr
m_ghost
template<int ebcm_order> int EBCM::PETSc_Framework< ebcm_order >::Base_PETSc_Op::m_ghost
m_numPtsPerBox
template<int ebcm_order> std::vector<int> EBCM::PETSc_Framework< ebcm_order >::Base_PETSc_Op::m_numPtsPerBox
m_numPtsThisProc
template<int ebcm_order> int EBCM::PETSc_Framework< ebcm_order >::Base_PETSc_Op::m_numPtsThisProc
m_numPtsAllProcs
template<int ebcm_order> int EBCM::PETSc_Framework< ebcm_order >::Base_PETSc_Op::m_numPtsAllProcs
m_startPtThisProc
template<int ebcm_order> int EBCM::PETSc_Framework< ebcm_order >::Base_PETSc_Op::m_startPtThisProc
The documentation for this class was generated from the following file:
Chombo_EBCM_PETSc_Framework.H