Chombo_4: Proto::EBStencilArchive< CELL, CELL, order, double > Class Template Reference
Proto::EBStencilArchive< CELL, CELL, order, double > Class Template Reference
#include <Proto_EBStencilArchive.H>
Public Types
typedef IndexedMoments< DIM, order > IndMomDIM
typedef IndexedMoments< DIM-1, order > IndMomSDMinOne
typedef MomentIterator< DIM, order > MomItDIM
typedef MomentIterator< DIM-1, order > MomItSDMinOne
typedef HostIrregData< CELL, IndMomDIM, 1 > VoluData
typedef HostIrregData< BOUNDARY, IndMomDIM, 1 > EBFaData
typedef HostIrregData< XFACE, IndMomSDMinOne, 1 > XFacData
typedef HostIrregData< YFACE, IndMomSDMinOne, 1 > YFacData
typedef HostIrregData< ZFACE, IndMomSDMinOne, 1 > ZFacData
typedef HostIrregData< CELL, IndMomDIM, 1 > EBNormalData
Public Member Functions
EBStencilArchive ()
~EBStencilArchive ()
Static Public Member Functions
static Point getColor (unsigned long icolor)
for prolongation and multicolor relaxation
static bool getStencil (vector< EBIndex< CELL > > &a_dstVoFs, vector< LocalStencil< CELL, double > > &a_stencil, Stencil< double > &a_regStencilInterior, vector< Stencil< double > > a_regStencilBCS[2 *DIM], vector< Box > a_BCApplyBoxes[2 *DIM], Box &a_regApplyBox, bool &a_bcOnly, bool &a_irregOnly, string a_stencilName, string a_domainBCName[2 *DIM], string a_ebbcName, const Box &a_srcValid, const Box &a_dstValid, const Box &a_srcDomain, const Box &a_dstDomain, const Point &a_srcGhost, const Point &a_dstGhost, const EBGraph &a_srcGraph, const EBGraph &a_dstGraph, const VoluData &a_voludata, const EBFaData &a_ebfadata, const XFacData &a_xfacdata, const YFacData &a_yfacdata, const ZFacData &a_zfacdata, double a_dx, bool a_periodiconly, Point a_dstGrown)
returns true if there are domain boundary conditions
static bool getDomainBCStencil (vector< Stencil< double > > a_regStencilBC[2 *DIM], vector< Box > a_BCApplyBoxes[2 *DIM], bool a_bcOnly, string a_domainBCName[2 *DIM], const Box &a_validBox, const Box &a_domain, const Point &a_srcGhost)
static bool getNormalizationStencil (vector< EBIndex< CELL > > &a_dstVoFs, vector< LocalStencil< CELL, double > > &a_stencil, Stencil< double > &a_regStencil, Box &a_regApplyBox, const Box &a_validBox, const Box &a_domain, const Point &a_srcGhost, const Point &a_dstGhost, const EBGraph &a_graph, const VoluData &a_voludata, unsigned long &a_radius, double a_dx)
stencil to do noramlize by volume fraction
static bool getSecondOrderPoissonStencil (vector< EBIndex< CELL > > &a_dstVoFs, vector< LocalStencil< CELL, double > > &a_stencil, Stencil< double > &a_regStencilInterior, vector< Stencil< double > > a_regStencilBC[2 *DIM], vector< Box > a_BCApplyBoxes[2 *DIM], Box &a_regApplyBox, string a_stencilName, string a_domainBCName[2 *DIM], string a_ebbcName, const Box &a_validBox, const Box &a_domain, const Point &a_srcGhost, const Point &a_dstGhost, const EBGraph &a_graph, const VoluData &a_voludata, const EBFaData &a_ebfadata, const XFacData &a_xfacdata, const YFacData &a_yfacdata, const ZFacData &a_zfacdata, double a_dx, bool a_periodiconly, bool a_forceAllNeumann)
Second order Poisson operator (interpolation to face centroids and all that)
static void getRegularPoissonBoundaryStencil (LocalStencil< CELL, double > &a_stencil, EBIndex< CELL > &a_startvof, const Box &a_domain, double a_dx, string a_dombc[2 *DIM])
static bool getRestrictionStencil (vector< EBIndex< CELL > > &a_dstVoFs, vector< LocalStencil< CELL, double > > &a_stencil, Stencil< double > &a_regStencilInterior, Box &a_regApplyBox, const Box &a_srcValid, const Box &a_dstValid, const Point &a_srcGhost, const Point &a_dstGhost, const EBGraph &a_srcGraph, const EBGraph &a_dstGraph, const VoluData &a_voludata, double a_dx, bool a_volumeWeighed)
Restriction.
static bool getRedistributionStencil (vector< EBIndex< CELL > > &a_dstVoFs, vector< LocalStencil< CELL, double > > &a_stencil, Stencil< double > &a_regStencil, Box &a_regApplyBox, const Box &a_validBox, const Box &a_domain, const Point &a_srcGhost, const Point &a_dstGhost, const EBGraph &a_graph, const VoluData &a_voludata, int a_redistRad, double a_dx)
Restriction.
static bool getSlopeStencil (vector< EBIndex< CELL > > &a_dstVoFs, vector< LocalStencil< CELL, double > > &a_stencil, Stencil< double > &a_regStencil, vector< Stencil< double > > a_regStencilBC[2 *DIM], vector< Box > a_BCApplyBoxes[2 *DIM], Box &a_regApplyBox, string a_domainBCName[2 *DIM], const Box &a_validBox, const Box &a_domain, const Point &a_srcGhost, const Point &a_dstGhost, const EBGraph &a_graph, const VoluData &a_voludata, const Point &a_dstGrown, unsigned int a_slopeDir, Side::LoHiSide a_slopeSign)
slopes
static bool getProlongationStencil (vector< EBIndex< CELL > > &a_dstVoFs, vector< LocalStencil< CELL, double > > &a_stencil, Stencil< double > &a_regStencilInterior, Box &a_regApplyBox, const Box &a_srcValid, const Box &a_dstValid, const Point &a_srcGhost, const Point &a_dstGhost, const EBGraph &a_srcGraph, const EBGraph &a_dstGraph, unsigned long a_icolor)
Prolongation.
static void getIrregLocations (vector< EBIndex< CELL > > &a_dstVoFs, const Stencil< double > &a_regStencil, const Box &a_boundingBox, const EBGraph &a_dstGraph)
Member Typedef Documentation
IndMomDIM
template<int order> typedef IndexedMoments<DIM , order> Proto::EBStencilArchive< CELL, CELL, order, double >::IndMomDIM
IndMomSDMinOne
template<int order> typedef IndexedMoments<DIM-1, order> Proto::EBStencilArchive< CELL, CELL, order, double >::IndMomSDMinOne
MomItDIM
template<int order> typedef MomentIterator<DIM , order> Proto::EBStencilArchive< CELL, CELL, order, double >::MomItDIM
MomItSDMinOne
template<int order> typedef MomentIterator<DIM-1, order> Proto::EBStencilArchive< CELL, CELL, order, double >::MomItSDMinOne
VoluData
template<int order> typedef HostIrregData<CELL, IndMomDIM , 1> Proto::EBStencilArchive< CELL, CELL, order, double >::VoluData
EBFaData
template<int order> typedef HostIrregData<BOUNDARY, IndMomDIM , 1> Proto::EBStencilArchive< CELL, CELL, order, double >::EBFaData
XFacData
template<int order> typedef HostIrregData<XFACE, IndMomSDMinOne, 1> Proto::EBStencilArchive< CELL, CELL, order, double >::XFacData
YFacData
template<int order> typedef HostIrregData<YFACE, IndMomSDMinOne, 1> Proto::EBStencilArchive< CELL, CELL, order, double >::YFacData
ZFacData
template<int order> typedef HostIrregData<ZFACE, IndMomSDMinOne, 1> Proto::EBStencilArchive< CELL, CELL, order, double >::ZFacData
EBNormalData
template<int order> typedef HostIrregData<CELL, IndMomDIM , 1> Proto::EBStencilArchive< CELL, CELL, order, double >::EBNormalData
Constructor & Destructor Documentation
EBStencilArchive()
template<int order> Proto::EBStencilArchive< CELL, CELL, order, double >::EBStencilArchive () inline
~EBStencilArchive()
template<int order> Proto::EBStencilArchive< CELL, CELL, order, double >::~EBStencilArchive () inline
Member Function Documentation
getColor()
template<int order> static Point Proto::EBStencilArchive< CELL, CELL, order, double >::getColor (unsigned long icolor) inline static
for prolongation and multicolor relaxation
References Proto::EBStencilArchive< srcCenter, dstCenter, order, data_t >::getStencil().
getStencil()
template<int order> bool Proto::EBStencilArchive< CELL, CELL, order, double >::getStencil (vector< EBIndex< CELL > > & a_dstVoFs, vector< LocalStencil< CELL, double > > & a_stencil, Stencil< double > & a_regStencil, vector< Stencil< double > > a_regStencilBCS[2 *DIM], vector< Box > a_BCApplyBoxes[2 *DIM], Box & a_regApplyBox, bool & a_bcOnly, bool & a_irregOnly, string a_stencilName, string a_domainBCName[2 *DIM], string a_ebbcName, const Box & a_srcValid, const Box & a_dstValid, const Box & a_srcDomain, const Box & a_dstDomain, const Point & a_srcGhost, const Point & a_dstGhost, const EBGraph & a_srcGraph, const EBGraph & a_dstGraph, const VoluData & a_voludata, const EBFaData & a_ebfadata, const XFacData & a_xfacdata, const YFacData & a_yfacdata, const ZFacData & a_zfacdata, double a_dx, bool a_periodiconly, Point a_dstGrown) inline static
returns true if there are domain boundary conditions
this deep down in the bowels, everything is a template specialization returns whether there are domain boundary conditions
getDomainBCStencil()
template<int order> bool Proto::EBStencilArchive< CELL, CELL, order, double >::getDomainBCStencil (vector< Stencil< double > > a_regStencilBC[2 *DIM], vector< Box > a_BCApplyBoxes[2 *DIM], bool a_bcOnly, string a_domainBCName[2 *DIM], const Box & a_validBox, const Box & a_domain, const Point & a_srcGhost) inline static
References Proto::SecondOrderStencil< order >::getDomainBCs().
getNormalizationStencil()
template<int order> bool Proto::EBStencilArchive< CELL, CELL, order, double >::getNormalizationStencil (vector< EBIndex< CELL > > & a_dstVoFs, vector< LocalStencil< CELL, double > > & a_stencil, Stencil< double > & a_regStencil, Box & a_regApplyBox, const Box & a_validBox, const Box & a_domain, const Point & a_srcGhost, const Point & a_dstGhost, const EBGraph & a_graph, const VoluData & a_voludata, unsigned long & a_radius, double a_dx) inline static
stencil to do noramlize by volume fraction
References Proto::EBGraph::getDomain(), Proto::EBGraph::getIrregVoFs(), Proto::EBGraph::getVoFs(), Box::grow(), and Proto::Normalizor< order >::normalizedVoluMoments().
getSecondOrderPoissonStencil()
template<int order> bool Proto::EBStencilArchive< CELL, CELL, order, double >::getSecondOrderPoissonStencil (vector< EBIndex< CELL > > & a_dstVoFs, vector< LocalStencil< CELL, double > > & a_stencil, Stencil< double > & a_regStencilInterior, vector< Stencil< double > > a_regStencilBC[2 *DIM], vector< Box > a_BCApplyBoxes[2 *DIM], Box & a_regApplyBox, string a_stencilName, string a_domainBCName[2 *DIM], string a_ebbcName, const Box & a_validBox, const Box & a_domain, const Point & a_srcGhost, const Point & a_dstGhost, const EBGraph & a_graph, const VoluData & a_voludata, const EBFaData & a_ebfadata, const XFacData & a_xfacdata, const YFacData & a_yfacdata, const ZFacData & a_zfacdata, double a_dx, bool a_periodiconly, bool a_forceAllNeumann) inline static
Second order Poisson operator (interpolation to face centroids and all that)
this deep down in the bowels, everything is a template specialization
add to the irregular set all regular volumes that are adjacent to the domain boundary and create their stencils
References Box::contains(), Proto::EBIndex< cent >::defineAsRegular(), Proto::SecondOrderStencil< order >::get2ndOrderDivFStencil(), Proto::EBGraph::getAllVoFs(), Box::grow(), and Proto::EBGraph::isRegular().
getRegularPoissonBoundaryStencil()
template<int order> void Proto::EBStencilArchive< CELL, CELL, order, double >::getRegularPoissonBoundaryStencil (LocalStencil< CELL, double > & a_stencil, EBIndex< CELL > & a_startvof, const Box & a_domain, double a_dx, string a_dombc[2 *DIM]) inline static
References Proto::LocalStencil< cent, data_t >::add(), Proto::LocalStencil< cent, data_t >::clear(), Box::contains(), Proto::EBIndex< cent >::defineAsRegular(), Proto::ebp_index(), Proto::EBStencilArchive< srcCenter, dstCenter, order, data_t >::getStencil(), Proto::EBIndex< cent >::m_pt, and Proto::LocalStencil< cent, data_t >::setBetaWeight().
getRestrictionStencil()
template<int order> bool Proto::EBStencilArchive< CELL, CELL, order, double >::getRestrictionStencil (vector< EBIndex< CELL > > & a_dstVoFs, vector< LocalStencil< CELL, double > > & a_stencil, Stencil< double > & a_regStencilInterior, Box & a_regApplyBox, const Box & a_srcValid, const Box & a_dstValid, const Point & a_srcGhost, const Point & a_dstGhost, const EBGraph & a_srcGraph, const EBGraph & a_dstGraph, const VoluData & a_voludata, double a_dx, bool a_volumeWeighed) inline static
Restriction.
This produces phi_coarse = Averate(phi_fine). If kappa weighting is true, this does volume weighted averaging. If kappa weighting is false, this does straight averaging assuming that the inputs are already weighted with the volume fraction (as one does with multigrid). The source objects are on the finer level, the destination are on the coarser level. Refinement ratio of 2 is assumed. Moment data should be on the finer level. Should be used with incrementonly = false; The valid box should be on the coarse level Returns false (no bcs needed here) Dx is on the fine level
References Proto::HostIrregData< cent, data_t, ncomp >::contains(), Proto::EBGraph::getIrregVoFs(), Proto::EBGraph::isCovered(), Proto::Normalizor< order >::normalizedVoluMoments(), and Proto::EBGraph::refine().
getRedistributionStencil()
template<int order> bool Proto::EBStencilArchive< CELL, CELL, order, double >::getRedistributionStencil (vector< EBIndex< CELL > > & a_dstVoFs, vector< LocalStencil< CELL, double > > & a_stencil, Stencil< double > & a_regStencil, Box & a_regApplyBox, const Box & a_validBox, const Box & a_domain, const Point & a_srcGhost, const Point & a_dstGhost, const EBGraph & a_graph, const VoluData & a_voludata, int a_redistRad, double a_dx) inline static
Restriction.
This produces phi_coarse = Averate(phi_fine). If kappa weighting is true, this does volume weighted averaging. If kappa weighting is false, this does straight averaging assuming that the inputs are already weighted with the volume fraction (as one does with multigrid). The source objects are on the finer level, the destination are on the coarser level. Refinement ratio of 2 is assumed. Moment data should be on the finer level. Should be used with incrementonly = false; The valid box should be on the coarse level Returns false (no bcs needed here) Dx is on the fine level
References Proto::LocalStencil< cent, data_t >::add(), Box::contains(), Proto::EBGraph::getAllVoFsWithinRadius(), Proto::EBGraph::getIrregVoFs(), Box::grow(), Proto::LocalStencil< cent, data_t >::m_entries, Proto::EBIndex< cent >::m_pt, Proto::Normalizor< order >::normalizedVoluMoments(), and Proto::LocalStencil< cent, data_t >::size().
getSlopeStencil()
template<int order> bool Proto::EBStencilArchive< CELL, CELL, order, double >::getSlopeStencil (vector< EBIndex< CELL > > & a_dstVoFs, vector< LocalStencil< CELL, double > > & a_stencil, Stencil< double > & a_regStencil, vector< Stencil< double > > a_regStencilBC[2 *DIM], vector< Box > a_BCApplyBoxes[2 *DIM], Box & a_regApplyBox, string a_domainBCName[2 *DIM], const Box & a_validBox, const Box & a_domain, const Point & a_srcGhost, const Point & a_dstGhost, const EBGraph & a_graph, const VoluData & a_voludata, const Point & a_dstGrown, unsigned int a_slopeDir, Side::LoHiSide a_slopeSign) inline static
slopes
This produces low sided (phi_i - phi_i-1) or high sided (phi_i+1 - phi_i) depending on whether slopeSign is Lo or Hi
References Proto::EBGraph::getDomain(), Proto::SecondOrderStencil< order >::getDomainBCs(), Proto::EBGraph::getNeighborVoFs(), and Box::grow().
getProlongationStencil()
template<int order> bool Proto::EBStencilArchive< CELL, CELL, order, double >::getProlongationStencil (vector< EBIndex< CELL > > & a_dstVoFs, vector< LocalStencil< CELL, double > > & a_stencil, Stencil< double > & a_regStencilInterior, Box & a_regApplyBox, const Box & a_srcValid, const Box & a_dstValid, const Point & a_srcGhost, const Point & a_dstGhost, const EBGraph & a_srcGraph, const EBGraph & a_dstGraph, unsigned long a_icolor) inline static
Prolongation.
This produces phi_fine = piecewise_constant(phi_coar). Mostly used in multigrid. The color says which fine cell color (in the multicolored Gauss Seidel sense) will be changed. Should be used with incrementonly = true; The source objects are on the coarser level, the destination are on the finer level. Refinement ratio of 2 is assumed. Moment data is not used. The valid box should be on the fine level Returns false (no bcs needed here)
References Proto::EBGraph::coarsen(), Proto::EBGraph::getIrregVoFs(), Proto::EBIndex< cent >::m_pt, and Proto::EBGraph::refine().
getIrregLocations()
template<int order> void Proto::EBStencilArchive< CELL, CELL, order, double >::getIrregLocations (vector< EBIndex< CELL > > & a_dstVoFs, const Stencil< double > & a_regStencil, const Box & a_boundingBox, const EBGraph & a_dstGraph) inline static
References Proto::EBGraph::getDomain(), Proto::EBGraph::getIrregCells(), Proto::EBGraph::getVoFs(), Proto::PointSet::grow(), grow(), max(), and Proto::PointSetIterator::ok().
The documentation for this class was generated from the following files:
Proto_EBStencilArchive.H
Proto_EBStencilArchiveImplem.H