Chombo_4: EBLinearOutFused< cent, data_t, ncomp > Class Template Reference
EBLinearOutFused< cent, data_t, ncomp > Class Template Reference
#include <Proto_fusedLinear.H>
Public Attributes
unsigned int m_numberOfIteration = 0
bool isAllocated = false
unsigned int * m_end = nullptr
EBIndex< cent > ** m_indiciesSrc = nullptr
unsigned int * m_indiciesSizeSrc = nullptr
const data_t ** m_src = nullptr
void ** m_dst = nullptr
Private Member Functions
EBLinearOutFused ()
void allocate (unsigned int a_numberOfIteration)
template<typename T >
void fillparams (Chombo4::CopierBuffer *a_buffer, T &a_src, unsigned int a_srcComps_begin, unsigned int a_srcComps_size)
void fillparam (unsigned int a_it, void *a_dst, IrregData< cent, data_t, ncomp > &a_src)
void fillOne (unsigned int it, unsigned int end, EBIndex< cent > *indiciesSrc, unsigned int indiciesSizeSrc, const data_t *src, void *dst)
void launch ()
Constructor & Destructor Documentation
EBLinearOutFused()
template<CENTERING cent, class data_t , unsigned int ncomp> EBLinearOutFused< cent, data_t, ncomp >::EBLinearOutFused () inline private
Member Function Documentation
allocate()
template<CENTERING cent, class data_t , unsigned int ncomp> void EBLinearOutFused< cent, data_t, ncomp >::allocate (unsigned int a_numberOfIteration) inline private
References EBBoxDataIndexerFused< cent, data_t, ncomp >::m_dst, EBBoxDataIndexerFused< cent, data_t, ncomp >::m_end, EBBoxDataIndexerFused< cent, data_t, ncomp >::m_indiciesSizeSrc, EBBoxDataIndexerFused< cent, data_t, ncomp >::m_indiciesSrc, EBBoxDataIndexerFused< cent, data_t, ncomp >::m_numberOfIteration, and EBBoxDataIndexerFused< cent, data_t, ncomp >::m_src.
fillparams()
template<CENTERING cent, class data_t , unsigned int ncomp> template<typename T > void EBLinearOutFused< cent, data_t, ncomp >::fillparams (Chombo4::CopierBuffer * a_buffer, T & a_src, unsigned int a_srcComps_begin, unsigned int a_srcComps_size) inline private
References EBBoxDataIndexerFused< cent, data_t, ncomp >::fillparam().
fillparam()
template<CENTERING cent, class data_t , unsigned int ncomp> void EBLinearOutFused< cent, data_t, ncomp >::fillparam (unsigned int a_it, void * a_dst, IrregData< cent, data_t, ncomp > & a_src) inline private
References EBBoxDataIndexerFused< cent, data_t, ncomp >::fillone().
fillOne()
template<CENTERING cent, class data_t , unsigned int ncomp> void EBLinearOutFused< cent, data_t, ncomp >::fillOne (unsigned int it, unsigned int end, EBIndex< cent > * indiciesSrc, unsigned int indiciesSizeSrc, const data_t * src, void * dst) inline private
References EBBoxDataIndexerFused< cent, data_t, ncomp >::m_dst, EBBoxDataIndexerFused< cent, data_t, ncomp >::m_end, EBBoxDataIndexerFused< cent, data_t, ncomp >::m_indiciesSizeSrc, EBBoxDataIndexerFused< cent, data_t, ncomp >::m_indiciesSrc, and EBBoxDataIndexerFused< cent, data_t, ncomp >::m_src.
launch()
template<CENTERING cent, class data_t , unsigned int ncomp> void EBLinearOutFused< cent, data_t, ncomp >::launch () inline private
References kernel_eblinearout(), EBBoxDataIndexerFused< cent, data_t, ncomp >::m_dst, EBBoxDataIndexerFused< cent, data_t, ncomp >::m_end, EBBoxDataIndexerFused< cent, data_t, ncomp >::m_indiciesSizeSrc, EBBoxDataIndexerFused< cent, data_t, ncomp >::m_indiciesSrc, EBBoxDataIndexerFused< cent, data_t, ncomp >::m_numberOfIteration, and EBBoxDataIndexerFused< cent, data_t, ncomp >::m_src.
Member Data Documentation
m_numberOfIteration
template<CENTERING cent, class data_t , unsigned int ncomp> unsigned int EBLinearOutFused< cent, data_t, ncomp >::m_numberOfIteration = 0
isAllocated
template<CENTERING cent, class data_t , unsigned int ncomp> bool EBLinearOutFused< cent, data_t, ncomp >::isAllocated = false
m_end
template<CENTERING cent, class data_t , unsigned int ncomp> unsigned int* EBLinearOutFused< cent, data_t, ncomp >::m_end = nullptr
m_indiciesSrc
template<CENTERING cent, class data_t , unsigned int ncomp> EBIndex<cent>** EBLinearOutFused< cent, data_t, ncomp >::m_indiciesSrc = nullptr
m_indiciesSizeSrc
template<CENTERING cent, class data_t , unsigned int ncomp> unsigned int* EBLinearOutFused< cent, data_t, ncomp >::m_indiciesSizeSrc = nullptr
m_src
template<CENTERING cent, class data_t , unsigned int ncomp> const data_t** EBLinearOutFused< cent, data_t, ncomp >::m_src = nullptr
m_dst
template<CENTERING cent, class data_t , unsigned int ncomp> void** EBLinearOutFused< cent, data_t, ncomp >::m_dst = nullptr
The documentation for this class was generated from the following file:
Proto_fusedLinear.H