Chombo_4: IntVect Class Reference
IntVect Class Reference
An integer vector in SpaceDim-dimensional space.
#include <Chombo_IntVect.H>
Public Member Functions
uint64_t hash (const IntVect &origin, const IntVect &blockingFactor) const
IntVect (Proto::Point a_pt)
operator Proto::Point () const
uint64_t hash (const IntVect &origin, const IntVect &blockingFactor) const
Constructors and Accessors
IntVect ()
IntVect (const std::vector< int > &vi)
IntVect (D_DECL6(int i, int j, int k, int l, int m, int n))
IntVect (const int *a)
IntVect copy () const
int & operator[] (int i)
int operator[] (int i) const
void setVal (int i, int val)
IntVect ()
IntVect (const Vector< int > &vi)
IntVect (D_DECL6(int i, int j, int k, int l, int m, int n))
IntVect (const int *a)
IntVect (const IndexTM< int, CH_SPACEDIM > &a_tm)
IntVect copy () const
int & operator[] (int i)
int operator[] (int i) const
void setVal (int i, int val)
Data pointer functions
const int * getVect () const
const int * dataPtr () const
int * dataPtr ()
const int * getVect () const
const int * dataPtr () const
int * dataPtr ()
Comparison Operators
bool operator== (const IntVect &p) const
bool operator!= (const IntVect &p) const
bool operator< (const IntVect &p) const
bool operator<= (const IntVect &p) const
bool operator> (const IntVect &p) const
bool operator>= (const IntVect &p) const
bool lexLT (const IntVect &s) const
bool lexGT (const IntVect &s) const
bool operator== (const IntVect &p) const
bool operator!= (const IntVect &p) const
bool operator< (const IntVect &p) const
bool operator<= (const IntVect &p) const
bool operator> (const IntVect &p) const
bool operator>= (const IntVect &p) const
bool lexLT (const IntVect &s) const
bool lexGT (const IntVect &s) const
Unary operators
IntVect operator+ () const
IntVect operator- () const
int sum () const
int product () const
IntVect operator+ () const
IntVect operator- () const
int sum () const
int product () const
Division operators
IntVect & operator/= (int s)
IntVect & operator/= (const IntVect &p)
IntVect operator/ (const IntVect &p) const
IntVect operator/ (int s) const
IntVect & operator/= (int s)
IntVect & operator/= (const IntVect &p)
IntVect operator/ (const IntVect &p) const
IntVect operator/ (int s) const
Static Public Attributes
static size_t io_offset
Protected Attributes
int vect [CH_SPACEDIM]
Static Protected Attributes
static const size_t IntVectSize
static const uint32_t morton256_x [256]
static const uint32_t morton256_y [256]
static const uint32_t morton256_z [256]
Friends
class Box
class HDF5Handle
class VolIndex
class FaceIndex
class BLfacade::IntVect
Addition operators
IntVect operator+ (int s, const IntVect &p)
IntVect operator+ (int s, const IntVect &p)
IntVect & operator+= (int s)
IntVect & operator+= (const IntVect &p)
IntVect operator+ (const IntVect &p) const
IntVect operator+ (int s) const
IntVect & operator+= (int s)
IntVect & operator+= (const IntVect &p)
IntVect operator+ (const IntVect &p) const
IntVect operator+ (int s) const
Subtraction operators
IntVect operator- (int s, const IntVect &p)
IntVect operator- (int s, const IntVect &p)
IntVect & operator-= (int s)
IntVect & operator-= (const IntVect &p)
IntVect operator- (const IntVect &p) const
IntVect operator- (int s) const
IntVect & operator-= (int s)
IntVect & operator-= (const IntVect &p)
IntVect operator- (const IntVect &p) const
IntVect operator- (int s) const
Multiplication operators
IntVect operator* (int s, const IntVect &p)
IntVect operator* (int s, const IntVect &p)
IntVect & operator*= (int s)
IntVect & operator*= (const IntVect &p)
IntVect operator* (const IntVect &p) const
IntVect operator* (int s) const
IntVect & operator*= (int s)
IntVect & operator*= (const IntVect &p)
IntVect operator* (const IntVect &p) const
IntVect operator* (int s) const
Other arithmetic operators
IntVect min (const IntVect &p1, const IntVect &p2)
IntVect max (const IntVect &p1, const IntVect &p2)
IntVect scale (const IntVect &p, int s)
const IntVect absolute (const IntVect &p)
Returns the componentwise absolute value of the given IntVect.
IntVect reflect (const IntVect &a, int ref_ix, int idir)
IntVect diagShift (const IntVect &p, int s)
IntVect coarsen (const IntVect &p, int s)
IntVect coarsen (const IntVect &p1, const IntVect &p2)
IntVect min (const IntVect &p1, const IntVect &p2)
IntVect max (const IntVect &p1, const IntVect &p2)
IntVect scale (const IntVect &p, int s)
const IntVect absolute (const IntVect &p)
Returns the componentwise absolute value of the given IntVect.
IntVect reflect (const IntVect &a, int ref_ix, int idir)
IntVect diagShift (const IntVect &p, int s)
IntVect coarsen (const IntVect &p, int s)
IntVect coarsen (const IntVect &p1, const IntVect &p2)
IntVect & min (const IntVect &p)
IntVect & max (const IntVect &p)
int max () const
return the maximum value in the intvect
int min () const
return the minimum value in the intvect
IntVect & scale (int s)
IntVect & reflect (int ref_ix, int idir)
IntVect & shift (int coord, int s)
IntVect & shift (const IntVect &iv)
IntVect & diagShift (int s)
IntVect & coarsen (const IntVect &p)
IntVect & coarsen (int p)
IntVect & min (const IntVect &p)
IntVect & max (const IntVect &p)
int max () const
return the maximum value in the intvect
int min () const
return the minimum value in the intvect
IntVect & scale (int s)
IntVect & reflect (int ref_ix, int idir)
IntVect & shift (int coord, int s)
IntVect & shift (const IntVect &iv)
IntVect & diagShift (int s)
IntVect & coarsen (const IntVect &p)
IntVect & coarsen (int p)
I/O Functions
std::ostream & operator<< (std::ostream &os, const IntVect &iv)
std::istream & operator>> (std::istream &os, IntVect &iv)
std::ostream & operator<< (std::ostream &os, const IntVect &iv)
std::istream & operator>> (std::istream &os, IntVect &iv)
void printOn (std::ostream &os) const
void p () const
void dumpOn (std::ostream &os) const
void printOn (std::ostream &os) const
void p () const
void dumpOn (std::ostream &os) const
Constants
static const IntVect Zero
static const IntVect Unit
IntVect BASISV (int dir)
IntVect BASISV (int dir)
static int InitStatics ()
Detailed Description
An integer vector in SpaceDim-dimensional space.
An integer Vector in SpaceDim-dimensional space.
The class IntVect is an implementation of an integer vector in a SpaceDim-dimensional space. It represents a point in a discrete space. IntVect values are accessed using the operator[] function, as for a normal C++ array. In addition, the basic arithmetic operators have been overloaded to implement scaling and translation operations.
Constructor & Destructor Documentation
IntVect() [1/10]
IntVect::IntVect () inline
Construct an IntVect whose components are uninitialized.
IntVect() [2/10]
IntVect::IntVect (const std::vector< int > & vi) inline explicit
IntVect() [3/10]
IntVect::IntVect (D_DECL6(int i, int j, int k, int l, int m, int n)) inline explicit
Destructor. Let the compiler build the default destructor (bvs) Construct an IntVect given the specific values for its coordinates. D_DECL6 is a macro that sets the constructor to take CH_SPACEDIM arguments.
IntVect() [4/10]
IntVect::IntVect (const int * a) inline explicit
Construct an IntVect setting the coordinates to the corresponding values in the integer array a.
IntVect() [5/10]
IntVect::IntVect (Proto::Point a_pt) inline
IntVect() [6/10]
IntVect::IntVect () inline
Construct an IntVect whose components are uninitialized.
IntVect() [7/10]
IntVect::IntVect (const Vector< int > & vi) inline explicit
IntVect() [8/10]
IntVect::IntVect (D_DECL6(int i, int j, int k, int l, int m, int n)) explicit
Destructor. Let the compiler build the default destructor (bvs) Construct an IntVect given the specific values for its coordinates. D_DECL6 is a macro that sets the constructor to take CH_SPACEDIM arguments.
IntVect() [9/10]
IntVect::IntVect (const int * a) explicit
Construct an IntVect setting the coordinates to the corresponding values in the integer array a.
IntVect() [10/10]
IntVect::IntVect (const IndexTM< int, CH_SPACEDIM > & a_tm)
The copy constructor. let compiler build default copy constructor (bvs)
Member Function Documentation
copy() [1/2]
IntVect IntVect::copy () const inline
The copy constructor. let compiler build default copy constructor (bvs)
References max(), min(), operator*(), operator+(), operator-(), and operator/().
operator[]() [1/4]
int & IntVect::operator[] (int i) inline
The assignment operator. Let compiler build default assign operator Returns a modifiable lvalue reference to the i'th coordinate of the IntVect.
References CH_assert, and SpaceDim.
operator[]() [2/4]
int IntVect::operator[] (int i) const inline
Returns the i'th coordinate of the IntVect.
References CH_assert, and SpaceDim.
setVal() [1/2]
void IntVect::setVal (int i, int val) inline
Set i'th coordinate of IntVect to val.
References CH_assert, and SpaceDim.
getVect() [1/2]
const int * IntVect::getVect () const inline
Returns a const pointer to an array of coordinates of the IntVect. Useful for arguments to FORTRAN calls.
dataPtr() [1/4]
const int * IntVect::dataPtr () const inline
Only for sending to Fortran
dataPtr() [2/4]
int * IntVect::dataPtr () inline
Only for sending to Fortran
operator==() [1/2]
bool IntVect::operator== (const IntVect & p) const inline
Returns true if this IntVect is equivalent to argument IntVect. All comparisons between analogous components must be satisfied.
operator!=() [1/2]
bool IntVect::operator!= (const IntVect & p) const inline
Returns true if this IntVect is different from argument IntVect. All comparisons between analogous components must be satisfied.
operator<() [1/2]
bool IntVect::operator< (const IntVect & p) const inline
Returns true if this IntVect is less than argument IntVect. All comparisons between analogous components must be satisfied. Note that, since the comparison is component-wise, it is possible for an IntVect to be neither greater than, less than, nor equal to another.
operator<=() [1/2]
bool IntVect::operator<= (const IntVect & p) const inline
Returns true if this IntVect is less than or equal to argument IntVect. All comparisons between analogous components must be satisfied. Note that, since the comparison is component-wise, it is possible for an IntVect to be neither greater than or equal to, less than or equal to, nor equal to another.
operator>() [1/2]
bool IntVect::operator> (const IntVect & p) const inline
Returns true if this IntVect is greater than argument IntVect. All comparisons between analogous components must be satisfied. Note that, since the comparison is component-wise, it is possible for an IntVect to be neither greater than, less than, nor equal to another.
operator>=() [1/2]
bool IntVect::operator>= (const IntVect & p) const inline
Returns true if this IntVect is greater than or equal to argument IntVect. All comparisons between analogous components must be satisfied. Note that, since the comparison is component-wise, it is possible for an IntVect to be neither greater than or equal to, less than or equal to, nor equal to another.
lexLT() [1/2]
bool IntVect::lexLT (const IntVect & s) const inline
Returns true if this IntVect is lexically less than the argument. An IntVect MUST BE either lexically less than, lexically greater than, or equal to another IntVect.
iv1 is lexically less than iv2 if:
in 2-D:
(iv1[0] < iv2[0]) || ((iv1[0] == iv2[0]) && (iv1[1] < iv2[1]));
in 3-D:
(iv1[0] < iv2[0]) || (iv1[0]==iv2[0] && ((iv1[1] < iv2[1] || ((iv1[1] == iv2[1]) && (iv1[2] < iv2[2])))));
Referenced by std::less< IntVect >::operator()().
lexGT() [1/2]
bool IntVect::lexGT (const IntVect & s) const inline
Returns true if this IntVect is lexically greater than the argument. An IntVect MUST BE either lexically less than, lexically greater than, or equal to another IntVect.
iv1 is lexically less than iv2 if:
in 2-D:
(iv1[0] > iv2[0]) || ((iv1[0] == iv2[0]) && (iv1[1] > iv2[1]));
in 3-D:
(iv1[0] > iv2[0]) || (iv1[0]==iv2[0] && ((iv1[1] > iv2[1] || ((iv1[1] == iv2[1]) && (iv1[2] > iv2[2])))));
operator+() [1/6]
IntVect IntVect::operator+ () const inline
Unary plus – for completeness.
operator-() [1/6]
IntVect IntVect::operator- () const inline
Unary minus – negates all components of this IntVect.
sum() [1/2]
int IntVect::sum () const inline
Sum of all components of this IntVect.
product() [1/2]
int IntVect::product () const inline
Product of all components of this IntVect.
operator+=() [1/4]
IntVect & IntVect::operator+= (int s) inline
Modifies this IntVect by addition of a scalar to each component.
operator+=() [2/4]
IntVect & IntVect::operator+= (const IntVect & p) inline
Modifies this IntVect by component-wise addition with argument.
operator+() [2/6]
IntVect IntVect::operator+ (const IntVect & p) const inline
Returns component-wise sum of this IntVect and argument.
operator+() [3/6]
IntVect IntVect::operator+ (int s) const inline
Return an IntVect that is this IntVect with a scalar added to each component.
operator-=() [1/4]
IntVect & IntVect::operator-= (int s) inline
Modifies this IntVect by subtraction of a scalar from each component.
operator-=() [2/4]
IntVect & IntVect::operator-= (const IntVect & p) inline
Modifies this IntVect by component-wise subtraction by argument.
operator-() [2/6]
IntVect IntVect::operator- (const IntVect & p) const inline
Returns an IntVect that is this IntVect with p subtracted from it component-wise.
operator-() [3/6]
IntVect IntVect::operator- (int s) const inline
Returns an IntVect that is this IntVect with a scalar s subtracted from each component.
operator*=() [1/4]
IntVect & IntVect::operator*= (int s) inline
Modifies this IntVect by multiplication of each component by a scalar.
operator*=() [2/4]
IntVect & IntVect::operator*= (const IntVect & p) inline
Modifies this IntVect by component-wise multiplication by argument.
operator*() [1/4]
IntVect IntVect::operator* (const IntVect & p) const inline
Returns component-wise product of this IntVect with argument.
operator*() [2/4]
IntVect IntVect::operator* (int s) const inline
Returns an IntVect that is this IntVect with each component multiplied by a scalar.
operator/=() [1/4]
IntVect & IntVect::operator/= (int s) inline
Modifies this IntVect by division of each component by a scalar.
operator/=() [2/4]
IntVect & IntVect::operator/= (const IntVect & p) inline
Modifies this IntVect by component-wise division by IntVect argument.
operator/() [1/4]
IntVect IntVect::operator/ (const IntVect & p) const inline
Returns component-wise quotient of this IntVect by argument.
operator/() [2/4]
IntVect IntVect::operator/ (int s) const inline
Returns an IntVect that is this IntVect with each component divided by a scalar.
min() [1/4]
IntVect & IntVect::min (const IntVect & p) inline
Modifies this IntVect by taking component-wise min with IntVect argument.
References min(), and vect.
Referenced by min(), and write().
max() [1/4]
IntVect & IntVect::max (const IntVect & p) inline
Modifies this IntVect by taking component-wise max with IntVect argument.
References max(), and vect.
Referenced by max().
max() [2/4]
int IntVect::max () const inline
return the maximum value in the intvect
References max(), and SpaceDim.
min() [2/4]
int IntVect::min () const inline
return the minimum value in the intvect
References absolute(), BASISV(), coarsen(), diagShift(), max(), min(), operator<<(), operator>>(), reflect(), scale(), and SpaceDim.
scale() [1/2]
IntVect & IntVect::scale (int s) inline
Modifies this IntVect by multiplying each component by a scalar.
reflect() [1/2]
IntVect & IntVect::reflect (int ref_ix, int idir) inline
Modifies IntVect by reflecting it in the plane defined by the index ref_ix and with normal in the direction of idir. Directions are based at zero.
References CH_assert, and SpaceDim.
shift() [1/4]
IntVect & IntVect::shift (int coord, int s) inline
Modifies this IntVect by adding s to component in given coordinate direction.
References CH_assert, and SpaceDim.
shift() [2/4]
IntVect & IntVect::shift (const IntVect & iv) inline
Modifies this IntVect by component-wise addition with IntVect argument.
diagShift() [1/2]
IntVect & IntVect::diagShift (int s) inline
Modifies this IntVect by adding a scalar s to each component.
coarsen() [1/4]
IntVect & IntVect::coarsen (const IntVect & p) inline
Modify IntVect by component-wise integer projection.
References CH_assert, SpaceDim, vect, and Zero.
Referenced by coarsen().
coarsen() [2/4]
IntVect & IntVect::coarsen (int p) inline
Modify IntVect by component-wise integer projection.
References CH_assert, and SpaceDim.
printOn() [1/2]
void IntVect::printOn (std::ostream & os) const
Print an IntVect to the ostream.
p() [1/2]
void IntVect::p () const
Print an IntVect to the pout().
dumpOn() [1/2]
void IntVect::dumpOn (std::ostream & os) const
Print an IntVect to the ostream a bit more verbosely.
hash() [1/2]
uint64_t IntVect::hash (const IntVect & origin, const IntVect & blockingFactor) const inline
References CH_SPACEDIM.
Referenced by coarsen().
operator Proto::Point()
IntVect::operator Proto::Point () const inline
copy() [2/2]
IntVect IntVect::copy () const inline
References max(), min(), operator*(), operator+(), operator-(), and operator/().
operator[]() [3/4]
int& IntVect::operator[] (int i) inline
The assignment operator. Let compiler build default assign operator Returns a modifiable lvalue reference to the i'th coordinate of the IntVect.
operator[]() [4/4]
int IntVect::operator[] (int i) const inline
Returns the i'th coordinate of the IntVect.
setVal() [2/2]
void IntVect::setVal (int i, int val)
Set i'th coordinate of IntVect to val.
getVect() [2/2]
const int* IntVect::getVect () const
Returns a const pointer to an array of coordinates of the IntVect. Useful for arguments to FORTRAN calls.
dataPtr() [3/4]
const int* IntVect::dataPtr () const
Only for sending to Fortran
dataPtr() [4/4]
int* IntVect::dataPtr ()
Only for sending to Fortran
operator==() [2/2]
bool IntVect::operator== (const IntVect & p) const
Returns true if this IntVect is equivalent to argument IntVect. All comparisons between analogous components must be satisfied.
operator!=() [2/2]
bool IntVect::operator!= (const IntVect & p) const
Returns true if this IntVect is different from argument IntVect. All comparisons between analogous components must be satisfied.
operator<() [2/2]
bool IntVect::operator< (const IntVect & p) const
Returns true if this IntVect is less than argument IntVect. All comparisons between analogous components must be satisfied. Note that, since the comparison is component-wise, it is possible for an IntVect to be neither greater than, less than, nor equal to another.
operator<=() [2/2]
bool IntVect::operator<= (const IntVect & p) const
Returns true if this IntVect is less than or equal to argument IntVect. All comparisons between analogous components must be satisfied. Note that, since the comparison is component-wise, it is possible for an IntVect to be neither greater than or equal to, less than or equal to, nor equal to another.
operator>() [2/2]
bool IntVect::operator> (const IntVect & p) const
Returns true if this IntVect is greater than argument IntVect. All comparisons between analogous components must be satisfied. Note that, since the comparison is component-wise, it is possible for an IntVect to be neither greater than, less than, nor equal to another.
operator>=() [2/2]
bool IntVect::operator>= (const IntVect & p) const
Returns true if this IntVect is greater than or equal to argument IntVect. All comparisons between analogous components must be satisfied. Note that, since the comparison is component-wise, it is possible for an IntVect to be neither greater than or equal to, less than or equal to, nor equal to another.
lexLT() [2/2]
bool IntVect::lexLT (const IntVect & s) const
Returns true if this IntVect is lexically less than the argument. An IntVect MUST BE either lexically less than, lexically greater than, or equal to another IntVect.
iv1 is lexically less than iv2 if:
in 2-D:
(iv1[0] < iv2[0]) || ((iv1[0] == iv2[0]) && (iv1[1] < iv2[1]));
in 3-D:
(iv1[0] < iv2[0]) || (iv1[0]==iv2[0] && ((iv1[1] < iv2[1] || ((iv1[1] == iv2[1]) && (iv1[2] < iv2[2])))));
lexGT() [2/2]
bool IntVect::lexGT (const IntVect & s) const
Returns true if this IntVect is lexically greater than the argument. An IntVect MUST BE either lexically less than, lexically greater than, or equal to another IntVect.
iv1 is lexically less than iv2 if:
in 2-D:
(iv1[0] > iv2[0]) || ((iv1[0] == iv2[0]) && (iv1[1] > iv2[1]));
in 3-D:
(iv1[0] > iv2[0]) || (iv1[0]==iv2[0] && ((iv1[1] > iv2[1] || ((iv1[1] == iv2[1]) && (iv1[2] > iv2[2])))));
operator+() [4/6]
IntVect IntVect::operator+ () const
Unary plus – for completeness.
operator-() [4/6]
IntVect IntVect::operator- () const
Unary minus – negates all components of this IntVect.
sum() [2/2]
int IntVect::sum () const
Sum of all components of this IntVect.
product() [2/2]
int IntVect::product () const
Product of all components of this IntVect.
operator+=() [3/4]
IntVect& IntVect::operator+= (int s)
Modifies this IntVect by addition of a scalar to each component.
operator+=() [4/4]
IntVect& IntVect::operator+= (const IntVect & p)
Modifies this IntVect by component-wise addition with argument.
operator+() [5/6]
IntVect IntVect::operator+ (const IntVect & p) const
Returns component-wise sum of this IntVect and argument.
operator+() [6/6]
IntVect IntVect::operator+ (int s) const
Return an IntVect that is this IntVect with a scalar added to each component.
operator-=() [3/4]
IntVect& IntVect::operator-= (int s)
Modifies this IntVect by subtraction of a scalar from each component.
operator-=() [4/4]
IntVect& IntVect::operator-= (const IntVect & p)
Modifies this IntVect by component-wise subtraction by argument.
operator-() [5/6]
IntVect IntVect::operator- (const IntVect & p) const
Returns an IntVect that is this IntVect with p subtracted from it component-wise.
operator-() [6/6]
IntVect IntVect::operator- (int s) const
Returns an IntVect that is this IntVect with a scalar s subtracted from each component.
operator*=() [3/4]
IntVect& IntVect::operator*= (int s)
Modifies this IntVect by multiplication of each component by a scalar.
operator*=() [4/4]
IntVect& IntVect::operator*= (const IntVect & p)
Modifies this IntVect by component-wise multiplication by argument.
operator*() [3/4]
IntVect IntVect::operator* (const IntVect & p) const
Returns component-wise product of this IntVect with argument.
operator*() [4/4]
IntVect IntVect::operator* (int s) const
Returns an IntVect that is this IntVect with each component multiplied by a scalar.
operator/=() [3/4]
IntVect& IntVect::operator/= (int s)
Modifies this IntVect by division of each component by a scalar.
operator/=() [4/4]
IntVect& IntVect::operator/= (const IntVect & p)
Modifies this IntVect by component-wise division by IntVect argument.
operator/() [3/4]
IntVect IntVect::operator/ (const IntVect & p) const
Returns component-wise quotient of this IntVect by argument.
operator/() [4/4]
IntVect IntVect::operator/ (int s) const
Returns an IntVect that is this IntVect with each component divided by a scalar.
min() [3/4]
IntVect& IntVect::min (const IntVect & p)
Modifies this IntVect by taking component-wise min with IntVect argument.
max() [3/4]
IntVect& IntVect::max (const IntVect & p)
Modifies this IntVect by taking component-wise max with IntVect argument.
max() [4/4]
int IntVect::max () const inline
return the maximum value in the intvect
References Max(), and SpaceDim.
min() [4/4]
int IntVect::min () const inline
return the minimum value in the intvect
References absolute(), BASISV(), CH_SPACEDIM, coarsen(), diagShift(), linearIn(), linearOut(), linearSize(), max(), Min(), operator<<(), operator>>(), reflect(), scale(), and SpaceDim.
scale() [2/2]
IntVect& IntVect::scale (int s)
Modifies this IntVect by multiplying each component by a scalar.
reflect() [2/2]
IntVect& IntVect::reflect (int ref_ix, int idir)
Modifies IntVect by reflecting it in the plane defined by the index ref_ix and with normal in the direction of idir. Directions are based at zero.
shift() [3/4]
IntVect& IntVect::shift (int coord, int s)
Modifies this IntVect by adding s to component in given coordinate direction.
shift() [4/4]
IntVect& IntVect::shift (const IntVect & iv)
Modifies this IntVect by component-wise addition with IntVect argument.
diagShift() [2/2]
IntVect& IntVect::diagShift (int s)
Modifies this IntVect by adding a scalar s to each component.
coarsen() [3/4]
IntVect& IntVect::coarsen (const IntVect & p)
Modify IntVect by component-wise integer projection.
coarsen() [4/4]
IntVect& IntVect::coarsen (int p)
Modify IntVect by component-wise integer projection.
printOn() [2/2]
void IntVect::printOn (std::ostream & os) const
Print an IntVect to the ostream.
p() [2/2]
void IntVect::p () const
Print an IntVect to the pout().
dumpOn() [2/2]
void IntVect::dumpOn (std::ostream & os) const
Print an IntVect to the ostream a bit more verbosely.
InitStatics()
static int IntVect::InitStatics () static
Initializes Zero and Unit.
hash() [2/2]
uint64_t IntVect::hash (const IntVect & origin, const IntVect & blockingFactor) const inline
Friends And Related Function Documentation
Box
Box friend
HDF5Handle
HDF5Handle friend
VolIndex
VolIndex friend
FaceIndex
FaceIndex friend
BLfacade::IntVect
BLfacade::IntVect friend
operator+ [1/2]
IntVect operator+ (int s, const IntVect & p) friend
Returns an IntVect that is an IntVect p with a scalar s added to each component.
operator- [1/2]
IntVect operator- (int s, const IntVect & p) friend
Returns s - p.
operator* [1/2]
IntVect operator* (int s, const IntVect & p) friend
Returns an IntVect that is an IntVect p with each component multiplied by a scalar s.
min [1/2]
IntVect min (const IntVect & p1, const IntVect & p2) friend
Returns the IntVect that is the component-wise minimum of two argument IntVects.
max [1/2]
IntVect max (const IntVect & p1, const IntVect & p2) friend
Returns the IntVect that is the component-wise maximum of two argument IntVects.
scale [1/2]
IntVect scale (const IntVect & p, int s) friend
Returns an IntVect obtained by multiplying each of the components of the given IntVect by a scalar.
absolute [1/2]
const IntVect absolute (const IntVect & p) friend
Returns the componentwise absolute value of the given IntVect.
reflect [1/2]
IntVect reflect (const IntVect & a, int ref_ix, int idir) friend
Returns an IntVect that is the reflection of the given IntVect in the plane which passes through ref_ix and normal to the coordinate direction idir.
diagShift [1/2]
IntVect diagShift (const IntVect & p, int s) friend
Returns IntVect obtained by adding a scalar to each of the components of the given IntVect.
coarsen [1/4]
IntVect coarsen (const IntVect & p, int s) friend
Returns an IntVect that is the component-wise integer projection of p by s.
coarsen [2/4]
IntVect coarsen (const IntVect & p1, const IntVect & p2) friend
Returns an IntVect which is the component-wise integer projection of IntVect p1 by IntVect p2.
operator<< [1/2]
std::ostream& operator<< (std::ostream & os, const IntVect & iv) friend
Print the IntVect to given output stream in ASCII.
operator>> [1/2]
std::istream& operator>> (std::istream & os, IntVect & iv) friend
Read next IntVect from given input stream.
BASISV [1/2]
IntVect BASISV (int dir) friend
Returns a basis vector in the given coordinate direction.
In 3-D: BASISV(0) == (1,0,0); BASISV(1) == (0,1,0); BASISV(2) == (0,0,1).
In 2-D: BASISV(0) == (1,0); BASISV(1) == (0,1).
Note that the coordinate directions are based at zero.
operator+ [2/2]
IntVect operator+ (int s, const IntVect & p) friend
Returns an IntVect that is an IntVect p with a scalar s added to each component.
operator- [2/2]
IntVect operator- (int s, const IntVect & p) friend
Returns s - p.
operator* [2/2]
IntVect operator* (int s, const IntVect & p) friend
Returns an IntVect that is an IntVect p with each component multiplied by a scalar s.
min [2/2]
IntVect min (const IntVect & p1, const IntVect & p2) friend
Returns the IntVect that is the component-wise minimum of two argument IntVects.
max [2/2]
IntVect max (const IntVect & p1, const IntVect & p2) friend
Returns the IntVect that is the component-wise maximum of two argument IntVects.
scale [2/2]
IntVect scale (const IntVect & p, int s) friend
Returns an IntVect obtained by multiplying each of the components of the given IntVect by a scalar.
absolute [2/2]
const IntVect absolute (const IntVect & p) friend
Returns the componentwise absolute value of the given IntVect.
reflect [2/2]
IntVect reflect (const IntVect & a, int ref_ix, int idir) friend
Returns an IntVect that is the reflection of the given IntVect in the plane which passes through ref_ix and normal to the coordinate direction idir.
diagShift [2/2]
IntVect diagShift (const IntVect & p, int s) friend
Returns IntVect obtained by adding a scalar to each of the components of the given IntVect.
coarsen [3/4]
IntVect coarsen (const IntVect & p, int s) friend
Returns an IntVect that is the component-wise integer projection of p by s.
coarsen [4/4]
IntVect coarsen (const IntVect & p1, const IntVect & p2) friend
Returns an IntVect which is the component-wise integer projection of IntVect p1 by IntVect p2.
operator<< [2/2]
std::ostream& operator<< (std::ostream & os, const IntVect & iv) friend
Print the IntVect to given output stream in ASCII.
operator>> [2/2]
std::istream& operator>> (std::istream & os, IntVect & iv) friend
Read next IntVect from given input stream.
BASISV [2/2]
IntVect BASISV (int dir) friend
Returns a basis vector in the given coordinate direction.
In 3-D: BASISV(0) == (1,0,0); BASISV(1) == (0,1,0); BASISV(2) == (0,0,1).
In 2-D: BASISV(0) == (1,0); BASISV(1) == (0,1).
Note that the coordinate directions are based at zero.
Member Data Documentation
Zero
static const IntVect IntVect::Zero static
This is an IntVect all of whose components are equal to zero.
Referenced by BoxLayoutData< FArrayBox >::addTo(), BASISV(), BoxIterator::BoxIterator(), coarsen(), coarsen(), Box::convert(), Copier::Copier(), LevelData< FArrayBox >::copyTo(), LevelData< FArrayBox >::define(), LevelBoxData< NUMCOMPS >::define(), LevelData< FArrayBox >::exchange(), BoxLayoutData< FArrayBox >::generalCopyTo(), ImageIterator::ok(), EBCM::MetaDataLevel< order >::outputGraphMapAsHDF5(), read(), BaseFab< Real >::testBoxAndComp(), and writeEBLevelHDF5().
Unit
static const IntVect IntVect::Unit static
This is an IntVect all of whose components are equal to one.
Referenced by BoxIterator::BoxIterator(), Box::convert(), LevelGeometryService< order >::LevelGeometryService(), readLevel(), and BaseFab< Real >::testBoxAndComp().
io_offset
static size_t IntVect::io_offset static
Initializes Zero and Unit.
vect
int IntVect::vect protected
The individual components of this IntVect.
Referenced by BASISV(), coarsen(), coarsen(), Box::index(), max(), min(), and reflect().
IntVectSize
static const size_t IntVect::IntVectSize static protected
Number of bytes of storage used by this IntVect.
morton256_x
static const uint32_t IntVect::morton256_x static protected
morton256_y
static const uint32_t IntVect::morton256_y static protected
morton256_z
static const uint32_t IntVect::morton256_z static protected
The documentation for this class was generated from the following files:
Chombo_IntVect.H
IntVect.H