Chombo_4: Proto::EBGraph Class Reference
Proto::EBGraph Class Reference
Geometric description within a box.
#include <Proto_EBGraph.H>
Classes
struct localData
Public Types
enum TAG { AllRegular = 0, AllCovered, HasIrregular }
Public Member Functions
EBGraph ()
int nComp () const
not meaningful in this context. used by the mpi code
template<CENTERING cent>
bool isFaceRegular (const EBIndex< cent > &a_face) const
template<CENTERING cent>
bool isFaceCovered (const EBIndex< cent > &a_face) const
EBGraph (const Box &a_box, bool a_stackAlloc)
needed for Proto::LevelData. meaningless here becasue we need the graph.
vector< EBIndex< CELL > > getVoFsThatCoarsenTo (const EBIndex< CELL > &a_coarVoF) const
given vof on a coarser level, get vofs on THIS level it was coarsened from
void copy (const EBGraph &a_dsrc, const Box &a_srcBox, unsigned int a_srcComp, const Box &a_destBox, unsigned int a_destComp, unsigned int a_numcomp)
virtual ~EBGraph ()
template<CENTERING cent>
bool getAdjacentFace (EBIndex< cent > &a_adjFace, const EBIndex< cent > &a_startFace, int a_tanDir, Side::LoHiSide a_side) const
returns false if no such unique face exists (multivalued, outside of the domain, whatever)
vector< EBIndex< CELL > > getVoFs (const Point &a_iv) const
vector< EBIndex< CELL > > getAllVoFsWithinRadius (const Point &a_iv, unsigned int a_radius) const
bool isAllRegular () const
bool hasIrregular () const
bool isAllCovered () const
bool isIrregular (const Point &a_iv) const
bool isCovered (const Box &a_box) const
bool isRegular (const Box &a_box) const
bool isRegular (const Point &a_iv) const
bool isCovered (const Point &a_iv) const
bool isConnected (const EBIndex< CELL > &a_vof1, const EBIndex< CELL > &a_vof2) const
vector< EBIndex< XFACE > > getXFaces (const EBIndex< CELL > &a_vof, const Side::LoHiSide &a_sd) const
vector< EBIndex< YFACE > > getYFaces (const EBIndex< CELL > &a_vof, const Side::LoHiSide &a_sd) const
vector< EBIndex< CELL > > getNeighborVoFs (const EBIndex< CELL > &a_vof, const unsigned int &a_dir, const Side::LoHiSide &a_sd) const
void defineFromPrimitives (const Box &a_validBox, const HostBoxData< int > &a_regIrregCovered, const vector< IrregGraph > &a_irregGraph, const Box &a_validRegion, const Box &a_domain, bool singleValuedOnly=true)
void defineAsAllRegular (const Box &a_validBox, const Box &a_region, const Box &a_domain)
void defineAsAllCovered (const Box &a_validBox, const Box &a_region, const Box &a_domain)
const Box & getRegion () const
const Box & validBox () const
const Box & box () const
const Box & getDomain () const
bool isDefined () const
PointSet getIrregCells (const Box &a_box) const
vector< EBIndex< CELL > > getIrregVoFs (const Box &a_box) const
vector< set< EBIndex< CELL > > > getVoFSets (const Box &a_region) const
used in coarsening–get collections of connected vofs
bool hasBoundaryFaces (const EBIndex< CELL > &a_vof, int a_idir, Side::LoHiSide a_sd)
vector< EBIndex< BOUNDARY > > getCutFaces (const Point &a_pt) const
vector< EBIndex< BOUNDARY > > getCutFaces (const Box &a_box) const
get the cut faces (basically the same as above
vector< EBIndex< CELL > > getAllVoFs (const Box &a_box) const
template<CENTERING cent>
vector< EBIndex< cent > > refine (const EBIndex< cent > &a_ind, const EBGraph &a_finer) const
for faces
template<CENTERING cent>
EBIndex< cent > coarsen (const EBIndex< cent > &a_cent) const
vector< EBIndex< CELL > > refine (const EBIndex< CELL > &a_vof) const
void coarsenVoFs (const Box &a_validBox, EBGraph &a_fineEBGraph, const Box &a_vofRegionCoar)
void coarsenFaces (const EBGraph &a_fineEBGraph, const Box &a_faceRegionCoar)
vector< int > coarsenFaces (const EBGraph &a_fineEBGraph, const Box &a_regionCoar, const EBIndex< CELL > &a_vofCoar, const int &a_idir, const Side::LoHiSide &a_sd)
bool hasBoundaryFaces (const EBIndex< CELL > &a_vof, int a_idir, Side::LoHiSide a_sd) const
EBGraph (const Box &a_grid)
needed for leveldata
EBGraph (void *a_buf, size_t a_expectedSize, bool a_printStuff=false)
void energize (void *a_buf, size_t a_expected_size, bool a_printStuff=false) const
virtual std::size_t charsize (const Box &a_bx, unsigned int a_startcomp, unsigned int a_numcomps, bool a_printStuff=false) const
Chombo leveldata serialization routines.
virtual void linearIn (void *a_buf, size_t a_expectedSize, const Box &a_bx, unsigned int a_startcomp, unsigned int a_numcomps, bool a_printStuff=false)
virtual void linearOut (void *a_buf, size_t a_expectedSize, const Box &a_bx, unsigned int a_startcomp, unsigned int a_numcomps, bool a_printStuff=false) const
template<>
vector< EBIndex< BOUNDARY > > refine (const EBIndex< BOUNDARY > &a_ind, const EBGraph &a_finer) const
template<>
vector< EBIndex< CELL > > refine (const EBIndex< CELL > &a_ind, const EBGraph &a_finer) const
Static Public Member Functions
static int preAllocatable ()
static int memTypeAllocation ()
Private Member Functions
void defineAsFullIrregular (const Box &a_validBox, const Box &a_region, const Box &a_domain)
void defineAsEmptyIrregular (const Box &a_validBox, const Box &a_region, const Box &a_domain)
Private Attributes
TAG m_tag
Box m_region
box over which this graph is defined
Box m_validBox
Box m_domain
computational domain at this level of refinement
bool m_isDefined
shared_ptr< localData > m_internals
Detailed Description
Geometric description within a box.
EBGraph represents the geometric information of the domain at a given refinement within the boundaries of a particular box.
Member Enumeration Documentation
TAG
enum Proto::EBGraph::TAG
The EBGraph can be all regular or all covered or contain irregular cells.
Enumerator
AllRegular
AllCovered
HasIrregular
Constructor & Destructor Documentation
EBGraph() [1/4]
Proto::EBGraph::EBGraph () inline
Makes an EBGraph whose contents are undefined.
Referenced by energize().
EBGraph() [2/4]
Proto::EBGraph::EBGraph (const Box & a_box, bool a_stackAlloc) inline
needed for Proto::LevelData. meaningless here becasue we need the graph.
~EBGraph()
virtual Proto::EBGraph::~EBGraph () inline virtual
EBGraph() [3/4]
Proto::EBGraph::EBGraph (const Box & a_grid) inline
needed for leveldata
References Proto::EBIndex< cent >::charsize(), Proto::EBIndex< cent >::energize(), Proto::EBIndex< cent >::linearIn(), and Proto::EBIndex< cent >::linearOut().
EBGraph() [4/4]
Proto::EBGraph::EBGraph (void * a_buf, size_t a_expectedSize, bool a_printStuff = false) inline
References AllCovered, AllRegular, HasIrregular, ProtoSer::linearCharBufSize(), linearIn(), ProtoSer::linearInFromCharBuf(), m_domain, m_internals, m_isDefined, m_region, m_tag, m_validBox, and pout().
Member Function Documentation
nComp()
int Proto::EBGraph::nComp () const inline
not meaningful in this context. used by the mpi code
isFaceRegular()
template<CENTERING cent> bool Proto::EBGraph::isFaceRegular (const EBIndex< cent > & a_face) const inline
References Box::contains(), Proto::EBIndex< cent >::getVoF(), isFaceCovered(), isRegular(), m_domain, and Proto::EBIndex< cent >::m_pt.
Referenced by isRegular(), and Proto::Normalizor< order >::normalizedFaceMoments().
isFaceCovered()
template<CENTERING cent> bool Proto::EBGraph::isFaceCovered (const EBIndex< cent > & a_face) const inline
References Box::contains(), Proto::EBIndex< cent >::getVoF(), isCovered(), m_domain, and Proto::EBIndex< cent >::m_pt.
Referenced by isFaceRegular(), and Proto::Normalizor< order >::normalizedFaceMoments().
getVoFsThatCoarsenTo()
vector<EBIndex<CELL> > Proto::EBGraph::getVoFsThatCoarsenTo (const EBIndex< CELL > & a_coarVoF) const inline
given vof on a coarser level, get vofs on THIS level it was coarsened from
This is useful when you only have the graph on the finer level but need to refine the coarser vof. Trust me, it comes up.
References Proto::coarsen(), Proto::EBIndex< cent >::m_pt, and Box::refine().
preAllocatable()
static int Proto::EBGraph::preAllocatable () inline static
memTypeAllocation()
static int Proto::EBGraph::memTypeAllocation () inline static
copy()
void Proto::EBGraph::copy (const EBGraph & a_dsrc, const Box & a_srcBox, unsigned int a_srcComp, const Box & a_destBox, unsigned int a_destComp, unsigned int a_numcomp) inline
References charsize(), Box::contains(), defineAsAllCovered(), defineAsAllRegular(), Proto::CellNode::defineAsCovered(), defineAsEmptyIrregular(), defineAsFullIrregular(), Proto::CellNode::defineAsRegular(), hasIrregular(), isAllCovered(), isAllRegular(), isCovered(), isDefined(), isRegular(), m_domain, m_internals, m_region, m_validBox, and Proto::HostBoxData< data_t, ncomp >::setVal().
Referenced by linearIn().
getAdjacentFace()
template<CENTERING cent> bool Proto::EBGraph::getAdjacentFace (EBIndex< cent > & a_adjFace, const EBIndex< cent > & a_startFace, int a_tanDir, Side::LoHiSide a_side) const inline
returns false if no such unique face exists (multivalued, outside of the domain, whatever)
tandir should be shomething different from face.direction
References Box::contains(), Proto::EBIndex< cent >::direction(), Proto::EBIndex< cent >::getVoF(), getXFaces(), getYFaces(), isConnected(), m_domain, Proto::EBIndex< cent >::m_pt, and Proto::CellNode::setFaceStuff().
Referenced by coarsen(), and Proto::Base2ndOrderFlux< facecent, order >::getFaceInterpStencil().
getVoFs()
vector< EBIndex< CELL > > Proto::EBGraph::getVoFs (const Point & a_iv) const inline
Return the VoFs in the cell.
References AllCovered, AllRegular, Box::contains(), Proto::CellNode::getVoFs(), HasIrregular, isDefined(), m_internals, m_region, and m_tag.
Referenced by coarsenFaces(), LevelGeometryService< order >::fillEBFaceAlpha(), LevelGeometryService< order >::fillKappa(), Proto::getAllFaces(), Proto::EBStencilArchive< fcent, fcent, order, double >::getDomainExtrapolationStencil(), Proto::getIrregFaces(), Proto::EBStencilArchive< fcent, CELL, order, double >::getIrregLocations(), Proto::EBStencilArchive< CELL, CELL, order, double >::getIrregLocations(), Proto::EBStencilArchive< CELL, CELL, order, double >::getNormalizationStencil(), EBCM::EBCM_Graph< order >::getRefinedCoarseVolume(), getVoFSets(), Proto::maxLocCell(), Proto::maxLocFace(), EBLevelBoxData< cent, NUMCOMPS >::sum(), and EBCM::EBCM_Graph< order >::unpackEBDescription().
getAllVoFsWithinRadius()
vector< EBIndex<CELL> > Proto::EBGraph::getAllVoFsWithinRadius (const Point & a_iv, unsigned int a_radius) const inline
References Box::grow().
Referenced by Proto::DirichletEBFlux< order >::getEBFluxStencil(), and Proto::EBStencilArchive< CELL, CELL, order, double >::getRedistributionStencil().
isAllRegular()
bool Proto::EBGraph::isAllRegular () const inline
Return true if every cell in the EBGraph is a regular cell.
Referenced by copy().
hasIrregular()
bool Proto::EBGraph::hasIrregular () const inline
Return true neither all regular nor all covered
Referenced by copy().
isAllCovered()
bool Proto::EBGraph::isAllCovered () const inline
Return true if every cell in the EBGraph is a covered cell.
Referenced by copy().
isIrregular()
bool Proto::EBGraph::isIrregular (const Point & a_iv) const inline
Return true if a_iv is an irregular cell.
References AllCovered, AllRegular, HasIrregular, isDefined(), Proto::CellNode::isIrregular(), m_internals, and m_tag.
Referenced by coarsenFaces(), coarsenVoFs(), Proto::CellNode::getCutFaces(), Proto::Normalizor< order >::getNormalAndBoundaryArea(), EBCM::EBCM_Graph< order >::makeTheBlobs(), and refine().
isCovered() [1/2]
bool Proto::EBGraph::isCovered (const Box & a_box) const inline
Return true if every cell in a_box is a covered cell.
References AllCovered, AllRegular, HasIrregular, isDefined(), and m_tag.
Referenced by coarsen(), coarsenVoFs(), copy(), EBLevelBoxData< cent, NUMCOMPS >::copyHostToFAB(), EBCM::EBCM_Graph< order >::createEBCM_Volume(), LevelGeometryService< order >::fillEBFaceAlpha(), LevelGeometryService< order >::fillKappa(), Proto::CellNode::getFaceInfo(), EBCM::EBCM_Graph< order >::getRefinedCoarseVolume(), Proto::EBStencilArchive< CELL, CELL, order, double >::getRestrictionStencil(), Proto::CellNode::getVoFs(), isFaceCovered(), Proto::Normalizor< order >::normalizedBndryMoments(), Proto::Normalizor< order >::normalizedVoluMoments(), BaseExactSolution::operator()(), refine(), Proto::Normalizor< order >::sumArea(), EBCM::EBCM_Graph< order >::unpackEBDescription(), and writeEBLevelHDF5().
isRegular() [1/2]
bool Proto::EBGraph::isRegular (const Box & a_box) const inline
Return true if every cell in a_box is a regular cell.
References AllCovered, AllRegular, getXFaces(), HasIrregular, isDefined(), and m_tag.
Referenced by coarsen(), coarsenVoFs(), copy(), EBCM::EBCM_Graph< order >::createEBCM_Volume(), LevelGeometryService< order >::fillEBFaceAlpha(), LevelGeometryService< order >::fillKappa(), Proto::CellNode::getFaceInfo(), EBCM::EBCM_Graph< order >::getRefinedCoarseVolume(), Proto::EBStencilArchive< CELL, CELL, order, double >::getSecondOrderPoissonStencil(), Proto::CellNode::getVoFs(), isFaceRegular(), EBCM::EBCM_Graph< order >::makeTheBlobs(), Proto::Normalizor< order >::normalizedBndryMoments(), Proto::Normalizor< order >::normalizedVoluMoments(), BaseExactSolution::operator()(), refine(), Proto::Normalizor< order >::sumArea(), and EBCM::EBCM_Graph< order >::unpackEBDescription().
isRegular() [2/2]
bool Proto::EBGraph::isRegular (const Point & a_iv) const inline
References AllCovered, AllRegular, HasIrregular, isDefined(), isFaceRegular(), Proto::CellNode::isRegular(), m_internals, and m_tag.
isCovered() [2/2]
bool Proto::EBGraph::isCovered (const Point & a_iv) const inline
References AllCovered, AllRegular, HasIrregular, Proto::CellNode::isCovered(), isDefined(), m_internals, and m_tag.
isConnected()
bool Proto::EBGraph::isConnected (const EBIndex< CELL > & a_vof1, const EBIndex< CELL > & a_vof2) const inline
References Box::contains(), getXFaces(), getYFaces(), isDefined(), Proto::EBIndex< cent >::m_pt, m_region, and Proto::EBIndex< cent >::m_vofIDMe.
Referenced by coarsenFaces(), getAdjacentFace(), getVoFSets(), and refine().
getXFaces()
vector< EBIndex< XFACE > > Proto::EBGraph::getXFaces (const EBIndex< CELL > & a_vof, const Side::LoHiSide & a_sd) const inline
Return the faces on the side and direction of the input VoF.
References AllCovered, AllRegular, Box::contains(), Proto::CellNode::getXFaces(), getYFaces(), HasIrregular, isDefined(), m_domain, m_internals, Proto::EBIndex< cent >::m_pt, m_tag, and Proto::EBIndex< cent >::m_vofIDMe.
Referenced by Proto::SecondOrderStencil< order >::get2ndOrderDivFStencil(), getAdjacentFace(), Proto::getFaces(), hasBoundaryFaces(), isConnected(), isRegular(), and Proto::Normalizor< order >::sumArea().
getYFaces()
vector< EBIndex< YFACE > > Proto::EBGraph::getYFaces (const EBIndex< CELL > & a_vof, const Side::LoHiSide & a_sd) const inline
Return the faces on the side and direction of the input VoF.
References AllCovered, AllRegular, Box::contains(), Proto::CellNode::getYFaces(), HasIrregular, isDefined(), m_domain, m_internals, Proto::EBIndex< cent >::m_pt, m_tag, and Proto::EBIndex< cent >::m_vofIDMe.
Referenced by Proto::SecondOrderStencil< order >::get2ndOrderDivFStencil(), getAdjacentFace(), Proto::getFaces(), getXFaces(), hasBoundaryFaces(), isConnected(), and Proto::Normalizor< order >::sumArea().
getNeighborVoFs()
vector<EBIndex<CELL> > Proto::EBGraph::getNeighborVoFs (const EBIndex< CELL > & a_vof, const unsigned int & a_dir, const Side::LoHiSide & a_sd) const inline
References Proto::EBIndex< cent >::getVoF(), and Proto::EBIndex< cent >::m_isBoundary.
Referenced by Proto::EBStencilArchive< CELL, CELL, order, double >::getSlopeStencil().
defineFromPrimitives()
void Proto::EBGraph::defineFromPrimitives (const Box & a_validBox, const HostBoxData< int > & a_regIrregCovered, const vector< IrregGraph > & a_irregGraph, const Box & a_validRegion, const Box & a_domain, bool singleValuedOnly = true) inline
Completely construct the graph from IrregGraphs. This makes a DENSE representation of the graph. To make sparse representations of all regular or all covered graphs, use setToAllRegular or setToAllCovered.\ irregGraph contains a complete list of irregular vofs. \ validRegion is the the region of the graph \ domain is the domain of compuation \ regIrregCovered = 1 for regular, 0 for irregular, -1 for covered. regIrregCovered must contain the valid region grown by 1. \ In chombospeak, \ regIrregCovered.box().contains(grow(validRegion, 1) & domain); \ otherwise an error will result. SingleValuedOnly signals that the geometry generator can only generate single-valued cut cells (GeometryService has this quality). Coarsening can still create multi-valued cells.
References Box::contains(), Proto::ebp_index(), HasIrregular, Proto::CellNode::isCovered(), Proto::CellNode::isRegular(), Proto::IrregGraph::m_arc, Proto::CellNode::IrrGraphNode::m_arc, Proto::IrregGraph::m_cell, m_domain, m_internals, m_isDefined, m_region, m_tag, and m_validBox.
defineAsAllRegular()
void Proto::EBGraph::defineAsAllRegular (const Box & a_validBox, const Box & a_region, const Box & a_domain) inline
Set the graph to all regular cells (sparse);
References AllRegular, defineAsAllCovered(), m_domain, m_internals, m_isDefined, m_region, m_tag, and m_validBox.
Referenced by coarsenFaces(), and copy().
defineAsAllCovered()
void Proto::EBGraph::defineAsAllCovered (const Box & a_validBox, const Box & a_region, const Box & a_domain) inline
Set the graph to all regular cells (sparse);
References AllCovered, m_domain, m_internals, m_isDefined, m_region, m_tag, and m_validBox.
Referenced by copy(), and defineAsAllRegular().
getRegion()
const Box& Proto::EBGraph::getRegion () const inline
Referenced by EBCM::EBCM_Graph< order >::getRefinedCoarseVolume(), and EBCM::EBCM_Graph< order >::makeTheBlobs().
validBox()
const Box& Proto::EBGraph::validBox () const inline
Referenced by EBCM::EBCM_Graph< order >::unpackEBDescription().
box()
const Box& Proto::EBGraph::box () const inline
getDomain()
const Box& Proto::EBGraph::getDomain () const inline
Referenced by Proto::HostIrregData< cent, data_t, ncomp >::define(), Proto::IrregData< cent, data_t, ncomp >::define(), Proto::getAllFaces(), Proto::EBStencilArchive< CELL, fcent, order, double >::getCellToFaceAveStencil(), Proto::EBStencilArchive< CELL, fcent, order, double >::getCellToFaceStencil(), Proto::Base2ndOrderFlux< facecent, order >::getFaceInterpStencil(), Proto::getIrregFaces(), Proto::EBStencilArchive< fcent, CELL, order, double >::getIrregLocations(), Proto::EBStencilArchive< CELL, CELL, order, double >::getIrregLocations(), Proto::EBStencilArchive< CELL, fcent, order, double >::getMACGradientStencil(), Proto::EBStencilArchive< CELL, CELL, order, double >::getNormalizationStencil(), Proto::EBStencilArchive< CELL, CELL, order, double >::getSlopeStencil(), Proto::EBStencilArchive< CELL, BOUNDARY, order, double >::getStencil(), Proto::EBStencilArchive< BOUNDARY, CELL, order, double >::getStencil(), and Proto::EBCrossStencilArchive< srcCenter, dstCenter, order >::getStencil().
isDefined()
bool Proto::EBGraph::isDefined () const inline
Referenced by copy(), getCutFaces(), getVoFs(), getXFaces(), getYFaces(), isConnected(), isCovered(), isIrregular(), and isRegular().
getIrregCells()
PointSet Proto::EBGraph::getIrregCells (const Box & a_box) const inline
Referenced by Proto::getIrregFaces(), Proto::EBStencilArchive< fcent, CELL, order, double >::getIrregLocations(), and Proto::EBStencilArchive< CELL, CELL, order, double >::getIrregLocations().
getIrregVoFs()
vector< EBIndex<CELL> > Proto::EBGraph::getIrregVoFs (const Box & a_box) const inline
References Proto::PointSetIterator::ok().
Referenced by Proto::getIrregIndicies(), Proto::EBStencilArchive< CELL, CELL, order, double >::getNormalizationStencil(), Proto::EBStencilArchive< CELL, CELL, order, double >::getProlongationStencil(), Proto::EBStencilArchive< CELL, CELL, order, double >::getRedistributionStencil(), Proto::EBStencilArchive< CELL, CELL, order, double >::getRestrictionStencil(), and Proto::EBStencilArchive< BOUNDARY, CELL, order, double >::getStencil().
getVoFSets()
vector< set< EBIndex< CELL > > > Proto::EBGraph::getVoFSets (const Box & a_region) const inline
used in coarsening–get collections of connected vofs
i can start at ivof+1 here because 0 to ivof
References coarsenFaces(), getVoFs(), and isConnected().
Referenced by coarsenVoFs().
hasBoundaryFaces() [1/2]
bool Proto::EBGraph::hasBoundaryFaces (const EBIndex< CELL > & a_vof, int a_idir, Side::LoHiSide a_sd) inline
Referenced by coarsenFaces().
getCutFaces() [1/2]
vector< EBIndex< BOUNDARY > > Proto::EBGraph::getCutFaces (const Point & a_pt) const inline
References Proto::CellNode::getCutFaces(), HasIrregular, isDefined(), Proto::CellNode::isIrregular(), m_internals, and m_tag.
Referenced by Proto::getAllFaces(), Proto::getIrregFaces(), and Proto::EBStencilArchive< CELL, BOUNDARY, order, double >::getStencil().
getCutFaces() [2/2]
vector< EBIndex<BOUNDARY> > Proto::EBGraph::getCutFaces (const Box & a_box) const inline
get the cut faces (basically the same as above
References Proto::PointSetIterator::ok().
getAllVoFs()
vector<EBIndex<CELL> > Proto::EBGraph::getAllVoFs (const Box & a_box) const inline
References Proto::coarsen(), and refine().
Referenced by Proto::getAllIndicies(), Proto::EBStencilArchive< fcent, CELL, order, double >::getDivergenceStencil(), Proto::EBStencilArchive< fcent, CELL, order, double >::getFaceToCellAveStencil(), and Proto::EBStencilArchive< CELL, CELL, order, double >::getSecondOrderPoissonStencil().
refine() [1/4]
template<CENTERING cent> vector< EBIndex< cent > > Proto::EBGraph::refine (const EBIndex< cent > & a_ind, const EBGraph & a_finer) const inline
for faces
References Box::contains(), Proto::EBIndex< cent >::getVoF(), isConnected(), m_domain, Proto::EBIndex< cent >::m_isBoundary, Proto::EBIndex< cent >::m_pt, Proto::EBIndex< cent >::m_vofIDLo, Proto::EBIndex< cent >::m_vofIDMe, Box::refine(), Proto::YFACE, and Proto::ZFACE.
Referenced by coarsenFaces(), Proto::EBStencilArchive< CELL, CELL, order, double >::getProlongationStencil(), Proto::EBStencilArchive< CELL, CELL, order, double >::getRestrictionStencil(), linearOut(), and refine().
coarsen()
template<CENTERING cent> EBIndex< cent > Proto::EBGraph::coarsen (const EBIndex< cent > & a_cent) const inline
References Proto::CELL, Box::contains(), getAdjacentFace(), Proto::EBIndex< cent >::getVoF(), isCovered(), isRegular(), Proto::CellNode::m_cellList, Proto::CellNode::IrrGraphNode::m_coarser, m_domain, m_internals, Proto::EBIndex< cent >::m_isBoundary, Proto::EBIndex< cent >::m_pt, Proto::EBIndex< cent >::m_vofIDLo, and Proto::EBIndex< cent >::m_vofIDMe.
Referenced by Proto::EBStencilArchive< CELL, CELL, order, double >::getProlongationStencil(), and Proto::EBIndex< CELL >::getRefinedRegular().
refine() [2/4]
vector< EBIndex< CELL > > Proto::EBGraph::refine (const EBIndex< CELL > & a_vof) const inline
References Proto::EBIndex< cent >::getRefinedRegular(), isCovered(), isRegular(), Proto::CellNode::m_cellList, m_domain, Proto::CellNode::IrrGraphNode::m_finer, m_internals, Proto::EBIndex< cent >::m_pt, Proto::EBIndex< cent >::m_vofIDMe, and Box::refine().
coarsenVoFs()
void Proto::EBGraph::coarsenVoFs (const Box & a_validBox, EBGraph & a_fineEBGraph, const Box & a_vofRegionCoar) inline
References AllCovered, AllRegular, Box::coarsen(), Proto::CellNode::defineAsIrregular(), getVoFSets(), HasIrregular, isCovered(), isIrregular(), isRegular(), Proto::CellNode::m_cellList, m_domain, m_internals, m_isDefined, Proto::EBIndex< cent >::m_pt, m_region, m_tag, m_validBox, Proto::EBIndex< cent >::m_vofIDMe, and Box::refine().
Referenced by Proto::CellNode::getCutFaces().
coarsenFaces() [1/2]
void Proto::EBGraph::coarsenFaces (const EBGraph & a_fineEBGraph, const Box & a_regionCoar) inline
region coar is a cell centered region that represents how far out we know the cell centered data.
References Proto::ebp_index(), getVoFs(), hasBoundaryFaces(), isIrregular(), Proto::CellNode::IrrGraphNode::m_arc, and m_internals.
Referenced by getVoFSets(), and hasBoundaryFaces().
coarsenFaces() [2/2]
vector< int > Proto::EBGraph::coarsenFaces (const EBGraph & a_fineEBGraph, const Box & a_regionCoar, const EBIndex< CELL > & a_vofCoar, const int & a_idir, const Side::LoHiSide & a_sd) inline
References Box::contains(), defineAsAllRegular(), getVoFs(), hasBoundaryFaces(), isConnected(), m_domain, Proto::EBIndex< cent >::m_pt, Proto::EBIndex< cent >::m_vofIDMe, and refine().
hasBoundaryFaces() [2/2]
bool Proto::EBGraph::hasBoundaryFaces (const EBIndex< CELL > & a_vof, int a_idir, Side::LoHiSide a_sd) const inline
References coarsenFaces(), getXFaces(), and getYFaces().
energize()
void Proto::EBGraph::energize (void * a_buf, size_t a_expected_size, bool a_printStuff = false) const inline
References AllCovered, AllRegular, EBGraph(), HasIrregular, ProtoSer::linearCharBufSize(), ProtoSer::linearOutToCharBuf(), m_domain, m_internals, m_region, m_tag, m_validBox, and pout().
Referenced by charsize(), and linearOut().
charsize()
std::size_t Proto::EBGraph::charsize (const Box & a_bx, unsigned int a_startcomp, unsigned int a_numcomps, bool a_printStuff = false) const inline virtual
Chombo leveldata serialization routines.
References energize(), HasIrregular, ProtoSer::linearCharBufSize(), m_domain, m_internals, m_region, m_tag, m_validBox, and pout().
Referenced by copy().
linearIn()
void Proto::EBGraph::linearIn (void * a_buf, size_t a_expectedSize, const Box & a_bx, unsigned int a_startcomp, unsigned int a_numcomps, bool a_printStuff = false) inline virtual
References copy(), linearOut(), and pout().
Referenced by EBGraph().
linearOut()
void Proto::EBGraph::linearOut (void * a_buf, size_t a_expectedSize, const Box & a_bx, unsigned int a_startcomp, unsigned int a_numcomps, bool a_printStuff = false) const inline virtual
References energize(), pout(), and refine().
Referenced by linearIn().
defineAsFullIrregular()
void Proto::EBGraph::defineAsFullIrregular (const Box & a_validBox, const Box & a_region, const Box & a_domain) inline private
References HasIrregular, m_domain, m_internals, m_isDefined, m_region, m_tag, and m_validBox.
Referenced by copy().
defineAsEmptyIrregular()
void Proto::EBGraph::defineAsEmptyIrregular (const Box & a_validBox, const Box & a_region, const Box & a_domain) inline private
References HasIrregular, m_domain, m_internals, m_isDefined, m_region, m_tag, and m_validBox.
Referenced by copy().
refine() [3/4]
template<> vector< EBIndex<BOUNDARY> > Proto::EBGraph::refine (const EBIndex< BOUNDARY > & a_ind, const EBGraph & a_finer) const inline
References isIrregular(), Proto::EBIndex< cent >::m_isBoundary, Proto::EBIndex< cent >::m_pt, Proto::EBIndex< cent >::m_vofIDLo, Proto::EBIndex< cent >::m_vofIDMe, and refine().
refine() [4/4]
template<> vector< EBIndex<CELL> > Proto::EBGraph::refine (const EBIndex< CELL > & a_ind, const EBGraph & a_finer) const inline
References refine().
Member Data Documentation
m_tag
TAG Proto::EBGraph::m_tag private
If this is allregular or allcovered, the HostBoxData below is undefined.
Referenced by charsize(), coarsenVoFs(), defineAsAllCovered(), defineAsAllRegular(), defineAsEmptyIrregular(), defineAsFullIrregular(), defineFromPrimitives(), EBGraph(), energize(), getCutFaces(), getVoFs(), getXFaces(), getYFaces(), isCovered(), isIrregular(), and isRegular().
m_region
Box Proto::EBGraph::m_region private
box over which this graph is defined
Referenced by charsize(), coarsenVoFs(), copy(), defineAsAllCovered(), defineAsAllRegular(), defineAsEmptyIrregular(), defineAsFullIrregular(), defineFromPrimitives(), EBGraph(), energize(), getVoFs(), and isConnected().
m_validBox
Box Proto::EBGraph::m_validBox private
Referenced by charsize(), coarsenVoFs(), copy(), defineAsAllCovered(), defineAsAllRegular(), defineAsEmptyIrregular(), defineAsFullIrregular(), defineFromPrimitives(), EBGraph(), and energize().
m_domain
Box Proto::EBGraph::m_domain private
computational domain at this level of refinement
Referenced by charsize(), coarsen(), coarsenFaces(), coarsenVoFs(), copy(), defineAsAllCovered(), defineAsAllRegular(), defineAsEmptyIrregular(), defineAsFullIrregular(), defineFromPrimitives(), EBGraph(), energize(), getAdjacentFace(), getXFaces(), getYFaces(), isFaceCovered(), isFaceRegular(), and refine().
m_isDefined
bool Proto::EBGraph::m_isDefined private
Referenced by coarsenVoFs(), defineAsAllCovered(), defineAsAllRegular(), defineAsEmptyIrregular(), defineAsFullIrregular(), defineFromPrimitives(), and EBGraph().
m_internals
shared_ptr<localData> Proto::EBGraph::m_internals private
Referenced by charsize(), coarsen(), coarsenFaces(), coarsenVoFs(), copy(), defineAsAllCovered(), defineAsAllRegular(), defineAsEmptyIrregular(), defineAsFullIrregular(), defineFromPrimitives(), EBGraph(), energize(), getCutFaces(), getVoFs(), getXFaces(), getYFaces(), isCovered(), isIrregular(), isRegular(), and refine().
The documentation for this class was generated from the following files:
Proto_EBGraph.H
Proto_EBGraphImplem.H