Chombo_4: Proto::BaseIF Class Reference
Proto::BaseIF Class Reference abstract
Class that specifies and implicit function.
#include <Proto_BaseIF.H>
Public Member Functions
BaseIF ()
Default constructor.
virtual ~BaseIF ()
Default destructor.
virtual double value (const IndexTM< int, DIM > &a_partialDerivative, const IndexTM< double, DIM > &a_point) const =0
virtual bool entireBoxRegular (const Proto::Box &a_box, const RealVect &a_origin, const double &a_dx)
virtual bool entireBoxCovered (const Proto::Box &a_box, const RealVect &a_origin, const double &a_dx)
overwrite if you have a fast way of knowing if a whole region is regular
virtual BaseIF * newImplicitFunction () const =0
factory method
Detailed Description
Class that specifies and implicit function.
This is the base class for an implicit function specification of geometry. All that is needed is a constructor/destructor, a method to give the value of the function at any point in space (in 2D or 3D), and a factory method (these will probably all be very similar).
Constructor & Destructor Documentation
BaseIF()
Proto::BaseIF::BaseIF () inline
Default constructor.
~BaseIF()
virtual Proto::BaseIF::~BaseIF () inline virtual
Default destructor.
References value().
Member Function Documentation
value()
virtual double Proto::BaseIF::value (const IndexTM< int, DIM > & a_partialDerivative, const IndexTM< double, DIM > & a_point) const pure virtual
Return the value of the function at a_point. When delineating a domain, the level set value=0 represents the boundary and value<0 is inside the fluid.
Implemented in Proto::SimpleCosSurfIF, Proto::SimpleSinProductIF, Proto::PlaneIF, Proto::AllRegularIF, Proto::SimpleEllipsoidIF, Proto::SimpleCylinderIF, ComplementIF, IntersectionIF, Chombo4::SmoothUnion, SmoothIntersection, and UnionIF.
Referenced by Proto::PlaneIF::entireBoxCovered(), Proto::PlaneIF::entireBoxRegular(), Proto::SimpleCylinderIF::value(), Proto::SimpleEllipsoidIF::value(), and ~BaseIF().
entireBoxRegular()
virtual bool Proto::BaseIF::entireBoxRegular (const Proto::Box & a_box, const RealVect & a_origin, const double & a_dx) inline virtual
entireBoxCovered()
virtual bool Proto::BaseIF::entireBoxCovered (const Proto::Box & a_box, const RealVect & a_origin, const double & a_dx) inline virtual
overwrite if you have a fast way of knowing if a whole region is regular
References newImplicitFunction().
newImplicitFunction()
virtual BaseIF* Proto::BaseIF::newImplicitFunction () const pure virtual
factory method
Return a newly allocated derived class. The responsibility for deleting the memory is left to the calling function.
Implemented in Proto::SimpleCosSurfIF, Proto::SimpleSinProductIF, Proto::PlaneIF, Proto::AllRegularIF, Proto::SimpleEllipsoidIF, Proto::SimpleCylinderIF, ComplementIF, IntersectionIF, Chombo4::SmoothUnion, SmoothIntersection, and UnionIF.
Referenced by entireBoxCovered(), and Proto::IFSlicer< DIM >::IFSlicer().
The documentation for this class was generated from the following file:
Proto_BaseIF.H