Chombo_4: Proto::PointSet Class Reference
Proto::PointSet Class Reference
PointSet implementation based std::set.
#include <Proto_PointSet.H>
Public Member Functions
PointSet ()
PointSet (const Box &a_box)
PointSet (const PointSet &a_sivs)
~PointSet ()
void define (const Box &)
void define (const PointSet &a_sivs)
PointSet & operator= (const PointSet &a_sivs)
PointSet & operator|= (const PointSet &a_sivs)
or
PointSet & operator|= (const Point &a_iv)
PointSet & operator|= (const Box &a_box)
PointSet & operator &= (const PointSet &s_sivs)
and
PointSet & operator &= (const Box &a_box)
and
PointSet & operator-= (const PointSet &a_sivs)
not
PointSet & operator-= (const Point &a_iv)
not
PointSet & operator-= (const Box &a_box)
not
bool operator== (const PointSet &lhs) const
returns true if
bool contains (const Point &iv) const
bool contains (const Box &box) const
void grow (int igrow)
void grow (int idir, int igrow)
void refine (int iref=2)
void coarsen (int iref=2)
void shift (const Point &iv)
void clear ()
Box minBox () const
bool isEmpty () const
void makeEmpty ()
int numPts () const
size_t linearSize () const
void linearOut (char *a_buf) const
void linearIn (const char *a_buf)
Private Attributes
std::set< Point > m_stdSet
Friends
class PointSetIterator
Detailed Description
PointSet implementation based std::set.
Constructor & Destructor Documentation
PointSet() [1/3]
Proto::PointSet::PointSet () inline
Referenced by define(), and PointSet().
PointSet() [2/3]
Proto::PointSet::PointSet (const Box & a_box) inline
References PointSet().
PointSet() [3/3]
Proto::PointSet::PointSet (const PointSet & a_sivs) inline
References define(), and m_stdSet.
~PointSet()
Proto::PointSet::~PointSet () inline
References clear(), coarsen(), contains(), define(), grow(), isEmpty(), makeEmpty(), minBox(), numPts(), operator &=(), operator-=(), operator=(), operator==(), operator|=(), refine(), and shift().
Member Function Documentation
define() [1/2]
void Proto::PointSet::define (const Box & a_box) inline
References PointSet().
Referenced by PointSet(), and ~PointSet().
define() [2/2]
void Proto::PointSet::define (const PointSet & a_sivs) inline
References m_stdSet, and operator=().
operator=()
PointSet & Proto::PointSet::operator= (const PointSet & a_sivs) inline
References m_stdSet, and operator|=().
Referenced by define(), and ~PointSet().
operator|=() [1/3]
PointSet & Proto::PointSet::operator|= (const PointSet & a_sivs) inline
or
References m_stdSet.
Referenced by operator=(), operator|=(), and ~PointSet().
operator|=() [2/3]
PointSet & Proto::PointSet::operator|= (const Point & a_iv) inline
References m_stdSet, and operator|=().
operator|=() [3/3]
PointSet & Proto::PointSet::operator|= (const Box & a_box) inline
References contains(), Box::contains(), m_stdSet, operator &=(), and operator-=().
operator &=() [1/2]
PointSet& Proto::PointSet::operator&= (const PointSet & s_sivs) inline
and
Referenced by operator|=(), and ~PointSet().
operator &=() [2/2]
PointSet& Proto::PointSet::operator&= (const Box & a_box) inline
and
operator-=() [1/3]
PointSet & Proto::PointSet::operator-= (const PointSet & a_sivs) inline
not
References contains(), and m_stdSet.
Referenced by operator-=(), operator|=(), and ~PointSet().
operator-=() [2/3]
PointSet & Proto::PointSet::operator-= (const Point & a_iv) inline
not
References contains(), m_stdSet, and operator-=().
operator-=() [3/3]
PointSet & Proto::PointSet::operator-= (const Box & a_box) inline
not
References operator==().
operator==()
bool Proto::PointSet::operator== (const PointSet & lhs) const inline
returns true if
References contains(), and m_stdSet.
Referenced by operator-=(), and ~PointSet().
contains() [1/2]
bool Proto::PointSet::contains (const Point & iv) const inline
References m_stdSet.
Referenced by contains(), operator-=(), operator==(), operator|=(), and ~PointSet().
contains() [2/2]
bool Proto::PointSet::contains (const Box & box) const inline
References contains(), and grow().
grow() [1/2]
void Proto::PointSet::grow (int igrow) inline
References Box::grow(), and m_stdSet.
Referenced by contains(), Proto::EBStencilArchive< fcent, CELL, order, double >::getIrregLocations(), Proto::EBStencilArchive< CELL, CELL, order, double >::getIrregLocations(), and ~PointSet().
grow() [2/2]
void Proto::PointSet::grow (int idir, int igrow) inline
References Box::grow(), m_stdSet, and refine().
refine()
void Proto::PointSet::refine (int iref = 2) inline
References coarsen(), m_stdSet, and Box::refine().
Referenced by grow(), and ~PointSet().
coarsen()
void Proto::PointSet::coarsen (int iref = 2) inline
References m_stdSet, and shift().
Referenced by refine(), and ~PointSet().
shift()
void Proto::PointSet::shift (const Point & iv) inline
References clear(), and m_stdSet.
Referenced by coarsen(), and ~PointSet().
clear()
void Proto::PointSet::clear () inline
References m_stdSet, and minBox().
Referenced by makeEmpty(), shift(), and ~PointSet().
minBox()
Box Proto::PointSet::minBox () const inline
References isEmpty(), m_stdSet, max(), and min().
Referenced by clear(), and ~PointSet().
isEmpty()
bool Proto::PointSet::isEmpty () const inline
References m_stdSet, and makeEmpty().
Referenced by minBox(), and ~PointSet().
makeEmpty()
void Proto::PointSet::makeEmpty () inline
References clear(), and numPts().
Referenced by isEmpty(), linearIn(), and ~PointSet().
numPts()
int Proto::PointSet::numPts () const inline
References m_stdSet, and Proto::PointSetIterator::PointSetIterator().
Referenced by linearOut(), makeEmpty(), and ~PointSet().
linearSize()
size_t Proto::PointSet::linearSize (void) const inline
References m_stdSet.
linearOut()
void Proto::PointSet::linearOut (char * a_buf) const inline
References m_stdSet, and numPts().
linearIn()
void Proto::PointSet::linearIn (const char * a_buf) inline
References makeEmpty().
Friends And Related Function Documentation
PointSetIterator
friend class PointSetIterator friend
Member Data Documentation
m_stdSet
std::set<Point> Proto::PointSet::m_stdSet private
Referenced by clear(), coarsen(), contains(), define(), Proto::PointSetIterator::define(), grow(), isEmpty(), linearOut(), linearSize(), minBox(), numPts(), operator-=(), operator=(), operator==(), operator|=(), PointSet(), Proto::PointSetIterator::PointSetIterator(), refine(), and shift().
The documentation for this class was generated from the following files:
Proto_PointSet.H
Proto_PointSetImplem.H