Chombo_4: Proto::CutCellMoments< 1 > Class Template Reference
Proto::CutCellMoments< 1 > Class Template Reference
#include <Proto_CutCellMoments.H>
Public Types
typedef map< IndexTM< int, 1 >, double > OneDMoments
Public Member Functions
CutCellMoments ()
CutCellMoments (const CutCellMoments< 1 > &a_cutCellMoments)
CutCellMoments (const IFData< 1 > &a_info)
~CutCellMoments ()
double changeMomentCoordinates (OneDMoments &a_refinedMap, const IndexTM< int, 1 > &a_monomial, const IndexTM< double, 1 > &a_refinedCenterDelta)
void changeMomentCoordinatesToCellCenter ()
void changeMomentCoordinatesToParentCenter ()
void initialize (CutCellMoments< 1 > &a_refinedCutCell)
void initializeMap (OneDMoments &a_map1, OneDMoments &a_map2)
double getBdMoment (const IndexTM< int, 1 > &a_mono, const IFData< 2 > &a_IFData, const IndexTM< double, 1 > &a_refinedCenterDelta, OneDMoments a_fullCellMap=OneDMoments())
double getBdEBMoment (const IndexTM< int, 1 > &a_mono, const IFData< 2 > &a_IFData, const IndexTM< double, 1 > &a_refinedCenterDelta)
void addBdMoments (CutCellMoments< 1 > &a_coarseCutCell, const IFData< 2 > &a_IFData, const int &a_degreePmax, const bool &a_useConstraints, const IndexTM< double, 1 > &a_refinedCenterDelta, const IndexTM< int, 1 > &a_localHilo)
double getMoment (const IndexTM< int, 1 > &a_mono, const EBorVol &a_EBorVOL) const
double getMoment (const IndexTM< int, 1 > &a_mono) const
double getVol (const EBorVol &a_EBorVol) const
IndexTM< double, 1 > getCentroid (const EBorVol &a_EBorVol) const
bool isCovered () const
bool isRegular () const
void operator= (const CutCellMoments< 1 > &a_cutCellMoments)
Public Attributes
OneDMoments m_moments
IFData< 1 > m_IFData
bool m_bdCCOn
int m_numActiveBounds
bool m_badNormal
OneDMoments m_EBmoments
Member Typedef Documentation
OneDMoments
typedef map<IndexTM<int,1>,double> Proto::CutCellMoments< 1 >::OneDMoments
Constructor & Destructor Documentation
CutCellMoments() [1/3]
Proto::CutCellMoments< 1 >::CutCellMoments () inline
CutCellMoments() [2/3]
Proto::CutCellMoments< 1 >::CutCellMoments (const CutCellMoments< 1 > & a_cutCellMoments) inline
CutCellMoments() [3/3]
Proto::CutCellMoments< 1 >::CutCellMoments (const IFData< 1 > & a_info) inline
References Proto::CutCellMoments< dim >::m_badNormal.
~CutCellMoments()
Proto::CutCellMoments< 1 >::~CutCellMoments () inline
Member Function Documentation
changeMomentCoordinates()
double Proto::CutCellMoments< 1 >::changeMomentCoordinates (OneDMoments & a_refinedMap, const IndexTM< int, 1 > & a_monomial, const IndexTM< double, 1 > & a_refinedCenterDelta) inline
References Proto::factorial().
changeMomentCoordinatesToCellCenter()
void Proto::CutCellMoments< 1 >::changeMomentCoordinatesToCellCenter () inline
References Proto::CutCellMoments< dim >::changeMomentCoordinates(), Proto::CutCellMoments< dim >::m_IFData, and Proto::CutCellMoments< dim >::m_moments.
changeMomentCoordinatesToParentCenter()
void Proto::CutCellMoments< 1 >::changeMomentCoordinatesToParentCenter () inline
References Proto::CutCellMoments< dim >::changeMomentCoordinates(), Proto::CutCellMoments< dim >::m_IFData, and Proto::CutCellMoments< dim >::m_moments.
initialize()
void Proto::CutCellMoments< 1 >::initialize (CutCellMoments< 1 > & a_refinedCutCell) inline
References Proto::CutCellMoments< dim >::initializeMap(), Proto::CutCellMoments< dim >::m_EBmoments, m_EBmoments, Proto::CutCellMoments< dim >::m_moments, and m_moments.
initializeMap()
void Proto::CutCellMoments< 1 >::initializeMap (OneDMoments & a_map1, OneDMoments & a_map2) inline
getBdMoment()
double Proto::CutCellMoments< 1 >::getBdMoment (const IndexTM< int, 1 > & a_mono, const IFData< 2 > & a_IFData, const IndexTM< double, 1 > & a_refinedCenterDelta, OneDMoments a_fullCellMap = OneDMoments()) inline
References Proto::CutCellMoments< dim >::changeMomentCoordinates(), LARGEREALVAL, Proto::IFData< dim >::m_allVerticesIn, Proto::IFData< dim >::m_allVerticesOut, Proto::CutCellMoments< dim >::m_IFData, and Proto::CutCellMoments< dim >::m_moments.
getBdEBMoment()
double Proto::CutCellMoments< 1 >::getBdEBMoment (const IndexTM< int, 1 > & a_mono, const IFData< 2 > & a_IFData, const IndexTM< double, 1 > & a_refinedCenterDelta) inline
addBdMoments()
void Proto::CutCellMoments< 1 >::addBdMoments (CutCellMoments< 1 > & a_coarseCutCell, const IFData< 2 > & a_IFData, const int & a_degreePmax, const bool & a_useConstraints, const IndexTM< double, 1 > & a_refinedCenterDelta, const IndexTM< int, 1 > & a_localHilo) inline
References Proto::CutCellMoments< dim >::getBdMoment(), Proto::IFData< dim >::m_allVerticesIn, Proto::CutCellMoments< dim >::m_IFData, and m_moments.
getMoment() [1/2]
double Proto::CutCellMoments< 1 >::getMoment (const IndexTM< int, 1 > & a_mono, const EBorVol & a_EBorVOL) const inline
References Proto::CutCellMoments< dim >::getMoment().
getMoment() [2/2]
double Proto::CutCellMoments< 1 >::getMoment (const IndexTM< int, 1 > & a_mono) const inline
References LARGEREALVAL, and Proto::CutCellMoments< dim >::m_moments.
getVol()
double Proto::CutCellMoments< 1 >::getVol (const EBorVol & a_EBorVol) const inline
References Proto::CutCellMoments< dim >::getMoment().
getCentroid()
IndexTM< double, 1 > Proto::CutCellMoments< 1 >::getCentroid (const EBorVol & a_EBorVol) const inline
References Proto::CutCellMoments< dim >::getMoment(), and Proto::CutCellMoments< dim >::getVol().
isCovered()
bool Proto::CutCellMoments< 1 >::isCovered () const inline
References Proto::CutCellMoments< dim >::m_IFData.
isRegular()
bool Proto::CutCellMoments< 1 >::isRegular () const inline
References Proto::CutCellMoments< dim >::m_IFData.
operator=()
void Proto::CutCellMoments< 1 >::operator= (const CutCellMoments< 1 > & a_cutCellMoments) inline
References Proto::CutCellMoments< dim >::m_IFData, m_IFData, Proto::CutCellMoments< dim >::m_moments, and m_moments.
Member Data Documentation
m_moments
OneDMoments Proto::CutCellMoments< 1 >::m_moments
Referenced by addBdMoments(), initialize(), and operator=().
m_IFData
IFData<1> Proto::CutCellMoments< 1 >::m_IFData
Referenced by operator=().
m_bdCCOn
bool Proto::CutCellMoments< 1 >::m_bdCCOn
m_numActiveBounds
int Proto::CutCellMoments< 1 >::m_numActiveBounds
m_badNormal
bool Proto::CutCellMoments< 1 >::m_badNormal
m_EBmoments
OneDMoments Proto::CutCellMoments< 1 >::m_EBmoments
Referenced by initialize().
The documentation for this class was generated from the following files:
Proto_CutCellMoments.H
Proto_CutCellMomentsImplem.H