Chombo_4: Proto::Base2ndOrderFlux< cent, order > Class Template Reference
Proto::Base2ndOrderFlux< cent, order > Class Template Reference
stuff in common for all second order flux calculations
#include <Proto_SecondOrderCell.H>
Public Types
typedef IndexedMoments< DIM, order > IndMomDIM
typedef IndexedMoments< DIM-1, order > IndMomSDMinOne
typedef MomentIterator< DIM, order > MomItDIM
typedef MomentIterator< DIM-1, order > MomItSDMinOne
Public Member Functions
virtual void getFaceCenteredFluxStencil (LocalStencil< CELL, double > &a_facesten, const EBIndex< cent > &a_face, const EBGraph &a_graph, const HostIrregData< cent, IndMomSDMinOne, 1 > &a_facdata, string a_dombc, double a_dx) const
void getFaceInterpStencil (LocalStencil< cent, double > &a_sten, const EBIndex< cent > &a_face, const EBGraph &a_graph, const HostIrregData< cent, IndMomSDMinOne, 1 > &a_facdata, double a_dx) const
void getCentroidStencil (LocalStencil< CELL, double > &a_sten, const EBIndex< cent > &a_face, const EBGraph &a_graph, const HostIrregData< cent, IndMomSDMinOne, 1 > &a_facdata, string a_dombc, double a_dx) const
Detailed Description
template<CENTERING cent, int order>
class Proto::Base2ndOrderFlux< cent, order >
stuff in common for all second order flux calculations
Member Typedef Documentation
IndMomDIM
template<CENTERING cent, int order> typedef IndexedMoments<DIM , order> Proto::Base2ndOrderFlux< cent, order >::IndMomDIM
IndMomSDMinOne
template<CENTERING cent, int order> typedef IndexedMoments<DIM-1, order> Proto::Base2ndOrderFlux< cent, order >::IndMomSDMinOne
MomItDIM
template<CENTERING cent, int order> typedef MomentIterator<DIM , order> Proto::Base2ndOrderFlux< cent, order >::MomItDIM
MomItSDMinOne
template<CENTERING cent, int order> typedef MomentIterator<DIM-1, order> Proto::Base2ndOrderFlux< cent, order >::MomItSDMinOne
Member Function Documentation
getFaceCenteredFluxStencil()
template<CENTERING cent, int order> virtual void Proto::Base2ndOrderFlux< cent, order >::getFaceCenteredFluxStencil (LocalStencil< CELL, double > & a_facesten, const EBIndex< cent > & a_face, const EBGraph & a_graph, const HostIrregData< cent, IndMomSDMinOne, 1 > & a_facdata, string a_dombc, double a_dx) const inline virtual
Reimplemented in Proto::Poisson2ndOrder< facecent, order >.
getFaceInterpStencil()
template<CENTERING cent, int order> void Proto::Base2ndOrderFlux< cent, order >::getFaceInterpStencil (LocalStencil< cent, double > & a_sten, const EBIndex< cent > & a_face, const EBGraph & a_graph, const HostIrregData< cent, IndMomSDMinOne, 1 > & a_facdata, double a_dx) const
Referenced by Proto::getFaceCentroidInterpStencil().
getCentroidStencil()
template<CENTERING cent, int order> void Proto::Base2ndOrderFlux< cent, order >::getCentroidStencil (LocalStencil< CELL, double > & a_sten, const EBIndex< cent > & a_face, const EBGraph & a_graph, const HostIrregData< cent, IndMomSDMinOne, 1 > & a_facdata, string a_dombc, double a_dx) const
Referenced by Proto::SecondOrderStencil< order >::get2ndOrderDivFStencil(), and Proto::Base2ndOrderFlux< facecent, order >::getFaceInterpStencil().
The documentation for this class was generated from the following files:
Proto_SecondOrderCell.H
Proto_SecondOrderCellImplem.H