Chombo_4: AliasDataFactory< T > Class Template Reference
AliasDataFactory< T > Class Template Reference
#include <Chombo_BoxLayoutData.H>
Public Member Functions
virtual ~AliasDataFactory ()
AliasDataFactory (BoxLayoutData< T > *a_original, const Interval &interval)
void define (BoxLayoutData< T > *a_original, const Interval &interval)
virtual T * create (const Box &box, int ncomps, const DataIndex &a_datInd) const
Public Member Functions inherited from DataFactory< T >
virtual ~DataFactory ()
virtual bool callDelete () const
virtual bool graphConstructor () const
Protected Attributes
BoxLayoutData< T > * m_origPointer
Interval m_interval
Constructor & Destructor Documentation
~AliasDataFactory()
template<class T> virtual AliasDataFactory< T >::~AliasDataFactory () inline virtual
References DataFactory< T >::create().
AliasDataFactory()
template<class T > AliasDataFactory< T >::AliasDataFactory (BoxLayoutData< T > * a_original, const Interval & interval)
References BoxLayoutData< T >::define().
Member Function Documentation
define()
template<class T > void AliasDataFactory< T >::define (BoxLayoutData< T > * a_original, const Interval & interval)
References BoxLayoutData< T >::interval().
create()
template<class T > T * AliasDataFactory< T >::create (const Box & box, int ncomps, const DataIndex & a_datInd) const virtual
creates a new 'T' object and returns a pointer to it. Responsiblitly for calling operator 'delete' on this pointer is passed to the user.
Implements DataFactory< T >.
References CH_assert, and BoxLayoutData< T >::makeItSo().
Member Data Documentation
m_origPointer
template<class T> BoxLayoutData<T>* AliasDataFactory< T >::m_origPointer protected
m_interval
template<class T> Interval AliasDataFactory< T >::m_interval protected
The documentation for this class was generated from the following files:
Chombo_BoxLayoutData.H
Chombo_BoxLayoutDataI.H