Chombo_4: Proto::EBStencilArchive< CELL, BOUNDARY, order, double > Class Template Reference
Proto::EBStencilArchive< CELL, BOUNDARY, order, double > Class Template Reference
#include <Proto_EBStencilArchive.H>
Public Types
typedef IndexedMoments< DIM, order > IndMomDIM
typedef IndexedMoments< DIM-1, order > IndMomSDMinOne
typedef MomentIterator< DIM, order > MomItDIM
typedef MomentIterator< DIM-1, order > MomItSDMinOne
typedef HostIrregData< CELL, IndMomDIM, 1 > VoluData
typedef HostIrregData< BOUNDARY, IndMomDIM, 1 > EBFaData
typedef HostIrregData< XFACE, IndMomSDMinOne, 1 > XFacData
typedef HostIrregData< YFACE, IndMomSDMinOne, 1 > YFacData
typedef HostIrregData< ZFACE, IndMomSDMinOne, 1 > ZFacData
Public Member Functions
EBStencilArchive ()
~EBStencilArchive ()
Static Public Member Functions
static bool getStencil (vector< EBIndex< BOUNDARY > > &a_dstVoFs, vector< LocalStencil< CELL, double > > &a_stencil, Stencil< double > &a_regStencil, vector< Stencil< double > > a_regStencilBCS[2 *DIM], vector< Box > a_BCApplyBoxes[2 *DIM], Box &a_regApplyBox, bool &a_bcOnly, bool &a_irregOnly, string a_stencilName, string a_domainBCName[2 *DIM], string a_ebbcName, const Box &a_srcValid, const Box &a_dstValid, const Box &a_srcDomain, const Box &a_dstDomain, const Point &a_srcGhost, const Point &a_dstGhost, const EBGraph &a_srcGraph, const EBGraph &a_dstGraph, const VoluData &a_voludata, const EBFaData &a_ebfadata, const XFacData &a_xfacdata, const YFacData &a_yfacdata, const ZFacData &a_zfacdata, double a_dx, bool a_periodiconly, Point a_dstGrown)
returns true if there are domain boundary conditions
Detailed Description
template<int order>
class Proto::EBStencilArchive< CELL, BOUNDARY, order, double >
Stuff to go from CELL to BOUNDARYs
Member Typedef Documentation
IndMomDIM
template<int order> typedef IndexedMoments<DIM , order> Proto::EBStencilArchive< CELL, BOUNDARY, order, double >::IndMomDIM
IndMomSDMinOne
template<int order> typedef IndexedMoments<DIM-1, order> Proto::EBStencilArchive< CELL, BOUNDARY, order, double >::IndMomSDMinOne
MomItDIM
template<int order> typedef MomentIterator<DIM , order> Proto::EBStencilArchive< CELL, BOUNDARY, order, double >::MomItDIM
MomItSDMinOne
template<int order> typedef MomentIterator<DIM-1, order> Proto::EBStencilArchive< CELL, BOUNDARY, order, double >::MomItSDMinOne
VoluData
template<int order> typedef HostIrregData<CELL, IndMomDIM , 1> Proto::EBStencilArchive< CELL, BOUNDARY, order, double >::VoluData
EBFaData
template<int order> typedef HostIrregData<BOUNDARY, IndMomDIM , 1> Proto::EBStencilArchive< CELL, BOUNDARY, order, double >::EBFaData
XFacData
template<int order> typedef HostIrregData<XFACE, IndMomSDMinOne, 1> Proto::EBStencilArchive< CELL, BOUNDARY, order, double >::XFacData
YFacData
template<int order> typedef HostIrregData<YFACE, IndMomSDMinOne, 1> Proto::EBStencilArchive< CELL, BOUNDARY, order, double >::YFacData
ZFacData
template<int order> typedef HostIrregData<ZFACE, IndMomSDMinOne, 1> Proto::EBStencilArchive< CELL, BOUNDARY, order, double >::ZFacData
Constructor & Destructor Documentation
EBStencilArchive()
template<int order> Proto::EBStencilArchive< CELL, BOUNDARY, order, double >::EBStencilArchive () inline
~EBStencilArchive()
template<int order> Proto::EBStencilArchive< CELL, BOUNDARY, order, double >::~EBStencilArchive () inline
References Proto::EBStencilArchive< srcCenter, dstCenter, order, data_t >::getStencil().
Member Function Documentation
getStencil()
template<int order> bool Proto::EBStencilArchive< CELL, BOUNDARY, order, double >::getStencil (vector< EBIndex< BOUNDARY > > & a_dstVoFs, vector< LocalStencil< CELL, double > > & a_stencil, Stencil< double > & a_regStencil, vector< Stencil< double > > a_regStencilBCS[2 *DIM], vector< Box > a_BCApplyBoxes[2 *DIM], Box & a_regApplyBox, bool & a_bcOnly, bool & a_irregOnly, string a_stencilName, string a_domainBCName[2 *DIM], string a_ebbcName, const Box & a_srcValid, const Box & a_dstValid, const Box & a_srcDomain, const Box & a_dstDomain, const Point & a_srcGhost, const Point & a_dstGhost, const EBGraph & a_srcGraph, const EBGraph & a_dstGraph, const VoluData & a_voludata, const EBFaData & a_ebfadata, const XFacData & a_xfacdata, const YFacData & a_yfacdata, const ZFacData & a_zfacdata, double a_dx, bool a_periodiconly, Point a_dstGrown) inline static
returns true if there are domain boundary conditions
References Proto::EBGraph::getCutFaces(), Proto::EBGraph::getDomain(), and Proto::EBStencilArchive< srcCenter, dstCenter, order, data_t >::getStencil().
The documentation for this class was generated from the following files:
Proto_EBStencilArchive.H
Proto_EBStencilArchiveImplem.H