Chombo_4: Proto::BaseMomentIterator< D > Class Template Reference
Proto::BaseMomentIterator< D > Class Template Reference abstract
class to enable template containment
#include <Proto_MomentIterator.H>
Public Member Functions
BaseMomentIterator ()
virtual ~BaseMomentIterator ()
virtual void reset ()=0
virtual void operator++ ()=0
virtual const IndexTM< int, D > & operator() () const =0
virtual bool ok ()=0
virtual int size () const =0
Detailed Description
template<int D>
class Proto::BaseMomentIterator< D >
class to enable template containment
Constructor & Destructor Documentation
BaseMomentIterator()
template<int D> Proto::BaseMomentIterator< D >::BaseMomentIterator () inline
~BaseMomentIterator()
template<int D> virtual Proto::BaseMomentIterator< D >::~BaseMomentIterator () inline virtual
References Proto::BaseMomentIterator< D >::ok(), Proto::BaseMomentIterator< D >::operator()(), Proto::BaseMomentIterator< D >::operator++(), Proto::BaseMomentIterator< D >::reset(), and Proto::BaseMomentIterator< D >::size().
Member Function Documentation
reset()
template<int D> virtual void Proto::BaseMomentIterator< D >::reset () pure virtual
Implemented in Proto::MomentIterator< D, P >.
Referenced by Proto::BaseMomentIterator< D >::~BaseMomentIterator().
operator++()
template<int D> virtual void Proto::BaseMomentIterator< D >::operator++ () pure virtual
Implemented in Proto::MomentIterator< D, P >.
Referenced by Proto::BaseMomentIterator< D >::~BaseMomentIterator().
operator()()
template<int D> virtual const IndexTM<int, D>& Proto::BaseMomentIterator< D >::operator() () const pure virtual
Implemented in Proto::MomentIterator< D, P >.
Referenced by Proto::BaseMomentIterator< D >::~BaseMomentIterator().
ok()
template<int D> virtual bool Proto::BaseMomentIterator< D >::ok () pure virtual
Implemented in Proto::MomentIterator< D, P >.
Referenced by Proto::BaseMomentIterator< D >::~BaseMomentIterator().
size()
template<int D> virtual int Proto::BaseMomentIterator< D >::size () const pure virtual
Implemented in Proto::MomentIterator< D, P >.
Referenced by Proto::BaseMomentIterator< D >::~BaseMomentIterator().
The documentation for this class was generated from the following file:
Proto_MomentIterator.H