Chombo_4: EBCM::Algorithm_Framework< ebcm_order > Class Template Reference
EBCM::Algorithm_Framework< ebcm_order > Class Template Reference
#include <Chombo_EBCM_Algorithm_Framework.H>
Classes
class condition_t
struct neighborhood_t
Public Types
typedef EBCM::HostLevelData< double, 1, ebcm_order > ebcm_leveldata
typedef EBCM::MetaDataLevel< ebcm_order > ebcm_meta
typedef EBCM::SubVolumeVector< ebcm_order > ebcm_subvol_vec
typedef EBCM::EBCM_Volu< ebcm_order > ebcm_volu
typedef EBCM::EBCM_Graph< ebcm_order > ebcm_graph
typedef Chombo4::GeometryService< ebcm_order > ch_geoserv
typedef Proto::IndexedMoments< DIM, ebcm_order > pr_mom_dim
typedef Proto::IndexedMoments< DIM-1, ebcm_order > pr_mom_dmo
Public Member Functions
Algorithm_Framework ()
Static Public Member Functions
static void getConditionNumberData (shared_ptr< ebcm_leveldata > &a_data, shared_ptr< condition_t > &a_worst, const shared_ptr< ebcm_meta > &a_ebcm, const string &a_dom_bc, const string &a_eb_bc)
static void getWorstConditionNumberInfo (double &a_invCondNumber, double &a_maxEigenvalue, double &a_minEigenvalue, int &a_face_dir, int &a_vec_index, const ebcm_volu &a_volu, const ebcm_graph &a_graph, const string &a_dom_bc, const string &a_eb_bc, bool a_print)
gets the worst condition number info for any face in the vof
template<CENTERING cent>
static shared_ptr< eigen_mat > getSystemMatrix (const EBCM_Face< cent, ebcm_order > &a_face, const ebcm_graph &a_graph, int a_nghost, int a_weight_power, const string &a_dom_bc, const string &a_eb_bc, bool a_print)
static shared_ptr< eigen_mat > getEBSystemMatrix (const IrregFace< ebcm_order > &a_face, const ebcm_graph &a_graph, int a_nghost, int a_weight_power, const string &a_dom_bc, const string &a_eb_bc, bool a_print)
I could probably have gotten some code reuse from above if I had made better choices in life.
template<CENTERING cent>
static void getWorstConditionNumberInfo (double &a_invCondNumber, double &a_maxEigenvalue, double &a_minEigenvalue, int &a_vec_index, const vector< EBCM_Face< cent, ebcm_order > > &a_faces, const ebcm_graph &a_graph, int a_stenrad, int a_weightpower, const string &a_dom_bc, const string &a_eb_bc, bool a_print)
gets the worst condition number info for any face in the vector
static void getWorstEBConditionNumberInfo (double &a_invCondNumber, double &a_maxEigenvalue, double &a_minEigenvalue, int &a_vec_index, const vector< IrregFace< ebcm_order > > &a_faces, const ebcm_graph &a_graph, int a_stenrad, int a_weightpower, const string &a_dom_bc, const string &a_eb_bc, bool a_print)
same thing but for the cut face. once again, code reuse eludes me.
static void checkKappa (double &a_maxKappa, double &a_minKappa, shared_ptr< ebcm_meta > a_meta, const ch_dbl &a_grids)
static void run_hoeb_petsc_tests (shared_ptr< ebcm_meta > &a_ebcm)
test function for example/EBCM/hoeb_petsc_test
static shared_ptr< pr_baseif > getImplicitFunction ()
static void makeMergedGeometry (shared_ptr< ebcm_meta > &a_ebcm, ch_dbl &a_grids, double &a_dx, ch_probdom &a_domain, bool a_outputGraph, bool a_print)
static shared_ptr< eigen_mat > getWeightMatrix (shared_ptr< neighborhood_t > a_locality, bool a_print)
static void shiftMomentAndFillRow (eigen_mat &a_mat, const pr_mom_dim &a_moment, const pr_rv &a_distance, const int &a_currentRow, bool a_print)
static void fillNeumannDomBCRow (eigen_mat &a_mat, const pr_mom_dim &a_moment, const pr_rv &a_distance, const int &a_face_dir, const int &a_currentRow, bool a_print)
static void fillDirichletDomBCRow (eigen_mat &a_mat, const pr_mom_dim &a_moment, const pr_rv &a_distance, const int &a_face_dir, const int &a_currentRow, bool a_print)
static void fillNeumannEBBCRow (eigen_mat &a_mat, const IrregFace< ebcm_order > &a_cut_face, const pr_rv &a_distance, const int &a_currentRow, bool a_print)
static void fillDirichletEBBCRow (eigen_mat &a_mat, const IrregFace< ebcm_order > &a_cut_face, const pr_rv &a_distance, const int &a_currentRow, bool a_print)
static shared_ptr< eigen_mat > getMomentMatrix (shared_ptr< neighborhood_t > a_locality, const string &a_dom_bc, const string &a_eb_bc, bool a_print)
Detailed Description
template<int ebcm_order>
class EBCM::Algorithm_Framework< ebcm_order >
Purely functional framework for doing tests in EBCM. The framework has no data but lots of common typedefs. All functions are static.
Member Typedef Documentation
ebcm_leveldata
template<int ebcm_order> typedef EBCM::HostLevelData<double, 1, ebcm_order > EBCM::Algorithm_Framework< ebcm_order >::ebcm_leveldata
ebcm_meta
template<int ebcm_order> typedef EBCM::MetaDataLevel< ebcm_order > EBCM::Algorithm_Framework< ebcm_order >::ebcm_meta
ebcm_subvol_vec
template<int ebcm_order> typedef EBCM::SubVolumeVector< ebcm_order > EBCM::Algorithm_Framework< ebcm_order >::ebcm_subvol_vec
ebcm_volu
template<int ebcm_order> typedef EBCM::EBCM_Volu< ebcm_order > EBCM::Algorithm_Framework< ebcm_order >::ebcm_volu
ebcm_graph
template<int ebcm_order> typedef EBCM::EBCM_Graph< ebcm_order > EBCM::Algorithm_Framework< ebcm_order >::ebcm_graph
ch_geoserv
template<int ebcm_order> typedef Chombo4::GeometryService< ebcm_order > EBCM::Algorithm_Framework< ebcm_order >::ch_geoserv
pr_mom_dim
template<int ebcm_order> typedef Proto::IndexedMoments<DIM , ebcm_order > EBCM::Algorithm_Framework< ebcm_order >::pr_mom_dim
pr_mom_dmo
template<int ebcm_order> typedef Proto::IndexedMoments<DIM-1, ebcm_order > EBCM::Algorithm_Framework< ebcm_order >::pr_mom_dmo
Constructor & Destructor Documentation
Algorithm_Framework()
template<int ebcm_order> EBCM::Algorithm_Framework< ebcm_order >::Algorithm_Framework () inline
Member Function Documentation
getConditionNumberData()
template<int ebcm_order> static void EBCM::Algorithm_Framework< ebcm_order >::getConditionNumberData (shared_ptr< ebcm_leveldata > & a_data, shared_ptr< condition_t > & a_worst, const shared_ptr< ebcm_meta > & a_ebcm, const string & a_dom_bc, const string & a_eb_bc) inline static
set to zero everywhere so covered cells get something
info about where the worst one was
References CH_TIME, and EBCM::Algorithm_Framework< ebcm_order >::getWorstConditionNumberInfo().
Referenced by EBCM::Algorithm_Framework< ebcm_order >::run_hoeb_petsc_tests().
getWorstConditionNumberInfo() [1/2]
template<int ebcm_order> static void EBCM::Algorithm_Framework< ebcm_order >::getWorstConditionNumberInfo (double & a_invCondNumber, double & a_maxEigenvalue, double & a_minEigenvalue, int & a_face_dir, int & a_vec_index, const ebcm_volu & a_volu, const ebcm_graph & a_graph, const string & a_dom_bc, const string & a_eb_bc, bool a_print) inline static
gets the worst condition number info for any face in the vof
References CH_TIME, ParmParse::get(), EBCM::Algorithm_Framework< ebcm_order >::getWorstEBConditionNumberInfo(), EBCM::EBCM_Volu< order >::m_ifaces, EBCM::EBCM_Volu< order >::m_xfaces, EBCM::EBCM_Volu< order >::m_yfaces, EBCM::EBCM_Volu< order >::m_zfaces, and pout().
Referenced by EBCM::Algorithm_Framework< ebcm_order >::getConditionNumberData().
getSystemMatrix()
template<int ebcm_order> template<CENTERING cent> static shared_ptr<eigen_mat> EBCM::Algorithm_Framework< ebcm_order >::getSystemMatrix (const EBCM_Face< cent, ebcm_order > & a_face, const ebcm_graph & a_graph, int a_nghost, int a_weight_power, const string & a_dom_bc, const string & a_eb_bc, bool a_print) inline static
References CH_TIME, EBCM::Algorithm_Framework< ebcm_order >::getMomentMatrix(), EBCM::Algorithm_Framework< ebcm_order >::getWeightMatrix(), EBCM::EBCM_Face< cent, order >::m_hi, EBCM::EBCM_Face< cent, order >::m_lo, multiply(), pout(), ch_eigen::Matrix::poutAll(), and ch_eigen::Matrix::transpose().
Referenced by EBCM::Algorithm_Framework< ebcm_order >::getWorstConditionNumberInfo().
getEBSystemMatrix()
template<int ebcm_order> static shared_ptr<eigen_mat> EBCM::Algorithm_Framework< ebcm_order >::getEBSystemMatrix (const IrregFace< ebcm_order > & a_face, const ebcm_graph & a_graph, int a_nghost, int a_weight_power, const string & a_dom_bc, const string & a_eb_bc, bool a_print) inline static
I could probably have gotten some code reuse from above if I had made better choices in life.
References CH_TIME, EBCM::Algorithm_Framework< ebcm_order >::getMomentMatrix(), EBCM::Algorithm_Framework< ebcm_order >::getWeightMatrix(), EBCM::IrregFace< order >::m_pt, multiply(), pout(), ch_eigen::Matrix::poutAll(), and ch_eigen::Matrix::transpose().
Referenced by EBCM::Algorithm_Framework< ebcm_order >::getWorstEBConditionNumberInfo().
getWorstConditionNumberInfo() [2/2]
template<int ebcm_order> template<CENTERING cent> static void EBCM::Algorithm_Framework< ebcm_order >::getWorstConditionNumberInfo (double & a_invCondNumber, double & a_maxEigenvalue, double & a_minEigenvalue, int & a_vec_index, const vector< EBCM_Face< cent, ebcm_order > > & a_faces, const ebcm_graph & a_graph, int a_stenrad, int a_weightpower, const string & a_dom_bc, const string & a_eb_bc, bool a_print) inline static
gets the worst condition number info for any face in the vector
References EBCM::Algorithm_Framework< ebcm_order >::getSystemMatrix(), and pout().
getWorstEBConditionNumberInfo()
template<int ebcm_order> static void EBCM::Algorithm_Framework< ebcm_order >::getWorstEBConditionNumberInfo (double & a_invCondNumber, double & a_maxEigenvalue, double & a_minEigenvalue, int & a_vec_index, const vector< IrregFace< ebcm_order > > & a_faces, const ebcm_graph & a_graph, int a_stenrad, int a_weightpower, const string & a_dom_bc, const string & a_eb_bc, bool a_print) inline static
same thing but for the cut face. once again, code reuse eludes me.
References EBCM::Algorithm_Framework< ebcm_order >::getEBSystemMatrix(), and pout().
Referenced by EBCM::Algorithm_Framework< ebcm_order >::getWorstConditionNumberInfo().
checkKappa()
template<int ebcm_order> static void EBCM::Algorithm_Framework< ebcm_order >::checkKappa (double & a_maxKappa, double & a_minKappa, shared_ptr< ebcm_meta > a_meta, const ch_dbl & a_grids) inline static
Print out max and min volume fraction in a meta.
References CH_TIME, max(), min(), and pout().
Referenced by EBCM::Algorithm_Framework< ebcm_order >::run_hoeb_petsc_tests().
run_hoeb_petsc_tests()
template<int ebcm_order> static void EBCM::Algorithm_Framework< ebcm_order >::run_hoeb_petsc_tests (shared_ptr< ebcm_meta > & a_ebcm) inline static
test function for example/EBCM/hoeb_petsc_test
getting meta data out for reuse
References CH_TIME, EBCM::Algorithm_Framework< ebcm_order >::checkKappa(), ParmParse::get(), EBCM::Algorithm_Framework< ebcm_order >::getConditionNumberData(), EBCM::Algorithm_Framework< ebcm_order >::makeMergedGeometry(), and pout().
getImplicitFunction()
template<int ebcm_order> static shared_ptr<pr_baseif> EBCM::Algorithm_Framework< ebcm_order >::getImplicitFunction () inline static
References CH_TIME, ParmParse::get(), ParmParse::getarr(), and pout().
Referenced by EBCM::Algorithm_Framework< ebcm_order >::makeMergedGeometry().
makeMergedGeometry()
template<int ebcm_order> static void EBCM::Algorithm_Framework< ebcm_order >::makeMergedGeometry (shared_ptr< ebcm_meta > & a_ebcm, ch_dbl & a_grids, double & a_dx, ch_probdom & a_domain, bool a_outputGraph, bool a_print) inline static
References CH_TIME, GeometryService< order >::generateGrids(), ParmParse::get(), EBCM::Algorithm_Framework< ebcm_order >::getImplicitFunction(), pout(), and Proto::RealVect::Zero().
Referenced by EBCM::Algorithm_Framework< ebcm_order >::run_hoeb_petsc_tests(), and EBCM::PETSc_Framework< ebcm_order >::run_hoeb_truncation_tests().
getWeightMatrix()
template<int ebcm_order> static shared_ptr<eigen_mat> EBCM::Algorithm_Framework< ebcm_order >::getWeightMatrix (shared_ptr< neighborhood_t > a_locality, bool a_print) inline static
Referenced by EBCM::Algorithm_Framework< ebcm_order >::getEBSystemMatrix(), and EBCM::Algorithm_Framework< ebcm_order >::getSystemMatrix().
shiftMomentAndFillRow()
template<int ebcm_order> static void EBCM::Algorithm_Framework< ebcm_order >::shiftMomentAndFillRow (eigen_mat & a_mat, const pr_mom_dim & a_moment, const pr_rv & a_distance, const int & a_currentRow, bool a_print) inline static
References CH_TIME, Proto::IndexedMoments< Dim, P >::indexOf(), Proto::MomentIterator< D, P >::ok(), pout(), ch_eigen::Matrix::poutRow(), Proto::IndexedMoments< Dim, P >::print(), ch_eigen::Matrix::setSmallCellRow(), Proto::IndexedMoments< Dim, P >::shift(), and Proto::IndexTM< T, N >::Zero.
Referenced by EBCM::Algorithm_Framework< ebcm_order >::getMomentMatrix().
fillNeumannDomBCRow()
template<int ebcm_order> static void EBCM::Algorithm_Framework< ebcm_order >::fillNeumannDomBCRow (eigen_mat & a_mat, const pr_mom_dim & a_moment, const pr_rv & a_distance, const int & a_face_dir, const int & a_currentRow, bool a_print) inline static
References CH_TIME, Proto::IndexedMoments< Dim, P >::indexOf(), Proto::MomentIterator< D, P >::ok(), pout(), ch_eigen::Matrix::poutRow(), Proto::IndexedMoments< Dim, P >::print(), and Proto::IndexedMoments< Dim, P >::shift().
Referenced by EBCM::Algorithm_Framework< ebcm_order >::getMomentMatrix().
fillDirichletDomBCRow()
template<int ebcm_order> static void EBCM::Algorithm_Framework< ebcm_order >::fillDirichletDomBCRow (eigen_mat & a_mat, const pr_mom_dim & a_moment, const pr_rv & a_distance, const int & a_face_dir, const int & a_currentRow, bool a_print) inline static
References CH_TIME, Proto::IndexedMoments< Dim, P >::indexOf(), Proto::MomentIterator< D, P >::ok(), pout(), ch_eigen::Matrix::poutRow(), Proto::IndexedMoments< Dim, P >::print(), and Proto::IndexedMoments< Dim, P >::shift().
Referenced by EBCM::Algorithm_Framework< ebcm_order >::getMomentMatrix().
fillNeumannEBBCRow()
template<int ebcm_order> static void EBCM::Algorithm_Framework< ebcm_order >::fillNeumannEBBCRow (eigen_mat & a_mat, const IrregFace< ebcm_order > & a_cut_face, const pr_rv & a_distance, const int & a_currentRow, bool a_print) inline static
References CH_TIME, EBCM::IrregFace< order >::getNormalMoment(), Proto::IndexedMoments< Dim, P >::indexOf(), Proto::MomentIterator< D, P >::ok(), pout(), ch_eigen::Matrix::poutRow(), and Proto::IndexedMoments< Dim, P >::shift().
Referenced by EBCM::Algorithm_Framework< ebcm_order >::getMomentMatrix().
fillDirichletEBBCRow()
template<int ebcm_order> static void EBCM::Algorithm_Framework< ebcm_order >::fillDirichletEBBCRow (eigen_mat & a_mat, const IrregFace< ebcm_order > & a_cut_face, const pr_rv & a_distance, const int & a_currentRow, bool a_print) inline static
References CH_TIME, Proto::IndexedMoments< Dim, P >::indexOf(), EBCM::IrregFace< order >::m_ebfmom, Proto::MomentIterator< D, P >::ok(), pout(), ch_eigen::Matrix::poutRow(), and Proto::IndexedMoments< Dim, P >::shift().
Referenced by EBCM::Algorithm_Framework< ebcm_order >::getMomentMatrix().
getMomentMatrix()
template<int ebcm_order> static shared_ptr<eigen_mat> EBCM::Algorithm_Framework< ebcm_order >::getMomentMatrix (shared_ptr< neighborhood_t > a_locality, const string & a_dom_bc, const string & a_eb_bc, bool a_print) inline static
This is the face mom with all derivatives in a_neigh_dir set to zero.
This is the face mom with all derivatives in a_neigh_dir set to zero.
References CH_TIME, EBCM::Algorithm_Framework< ebcm_order >::fillDirichletDomBCRow(), EBCM::Algorithm_Framework< ebcm_order >::fillDirichletEBBCRow(), EBCM::Algorithm_Framework< ebcm_order >::fillNeumannDomBCRow(), EBCM::Algorithm_Framework< ebcm_order >::fillNeumannEBBCRow(), ebcm_basics::getVolMomFromFacMom(), pout(), EBCM::Algorithm_Framework< ebcm_order >::shiftMomentAndFillRow(), and Proto::IndexedMoments< Dim, P >::size().
Referenced by EBCM::Algorithm_Framework< ebcm_order >::getEBSystemMatrix(), and EBCM::Algorithm_Framework< ebcm_order >::getSystemMatrix().
The documentation for this class was generated from the following file:
Chombo_EBCM_Algorithm_Framework.H