Chombo_4: ch_eigen::Matrix Class Reference
ch_eigen::Matrix Class Reference
#include <Chombo_EigenMatrix.H>
Public Member Functions
Matrix ()
Matrix (int a_nrow, int a_ncol)
Matrix (const Matrix &a_input)
deep copy constructor
double norm () const
returns the L-2 norm (what Eigen calls the Euclidean norm).
void setToIdentity ()
Eigen probably has way faster ways to do this.
void setVal (const double &a_val)
Eigen probably has way faster ways to do this.
const double & operator() (int irow, int icol) const
double & operator() (int irow, int icol)
std::pair< int, int > dims () const
return pair <nrow, ncol>
Matrix & operator= (const Matrix &a_input)
deep assign.
Matrix & operator+= (const Matrix &a_matrix)
increment
Matrix & operator-= (const Matrix &a_matrix)
decrement
Matrix & operator*= (const double &a_scalingFactor)
scale
double invConditionNumber () const
get 1/condition number. Goes to zero if poorly conditioned.
void getLargestAndSmallestEigenvalues (double &a_biggestEigenvalue, double &a_smallestEigenvalue) const
void poutEigenvalues () const
void writeToFile (std::string a_filename) const
Eigen probably has way faster ways to do this.
void poutMaxMins () const
debugging aid
void poutAll () const
debugging aid
void poutRow (int a_row) const
debugging aid
void poutDiag () const
debugging aid
void invert ()
void setSmallCellRow (const int &a_irow)
void transpose ()
Public Attributes
std::shared_ptr< eigen_mat > m_mat_p
This is the actual matrix. The class has no other data.
Detailed Description
Very simple wrapper around Eigen::matrix class designed to be a transition from between the LAPACKMatrix class and simply using the excellent Eigen infrastructure for our linear algebra needs.
Constructor & Destructor Documentation
Matrix() [1/3]
ch_eigen::Matrix::Matrix () inline
Matrix() [2/3]
ch_eigen::Matrix::Matrix (int a_nrow, int a_ncol) inline
Matrix() [3/3]
ch_eigen::Matrix::Matrix (const Matrix & a_input) inline
deep copy constructor
References m_mat_p.
Member Function Documentation
norm()
double ch_eigen::Matrix::norm () const inline
returns the L-2 norm (what Eigen calls the Euclidean norm).
setToIdentity()
void ch_eigen::Matrix::setToIdentity () inline
Eigen probably has way faster ways to do this.
setVal()
void ch_eigen::Matrix::setVal (const double & a_val) inline
Eigen probably has way faster ways to do this.
operator()() [1/2]
const double& ch_eigen::Matrix::operator() (int irow, int icol) const inline
operator()() [2/2]
double& ch_eigen::Matrix::operator() (int irow, int icol) inline
dims()
std::pair<int, int> ch_eigen::Matrix::dims () const inline
return pair <nrow, ncol>
operator=()
Matrix& ch_eigen::Matrix::operator= (const Matrix & a_input) inline
deep assign.
References m_mat_p.
operator+=()
Matrix& ch_eigen::Matrix::operator+= (const Matrix & a_matrix) inline
increment
References m_mat_p.
operator-=()
Matrix& ch_eigen::Matrix::operator-= (const Matrix & a_matrix) inline
decrement
References m_mat_p.
operator*=()
Matrix& ch_eigen::Matrix::operator*= (const double & a_scalingFactor) inline
scale
invConditionNumber()
double ch_eigen::Matrix::invConditionNumber () const inline
get 1/condition number. Goes to zero if poorly conditioned.
References getLargestAndSmallestEigenvalues().
getLargestAndSmallestEigenvalues()
void ch_eigen::Matrix::getLargestAndSmallestEigenvalues (double & a_biggestEigenvalue, double & a_smallestEigenvalue) const inline
Referenced by invConditionNumber().
poutEigenvalues()
void ch_eigen::Matrix::poutEigenvalues () const inline
References pout().
writeToFile()
void ch_eigen::Matrix::writeToFile (std::string a_filename) const inline
Eigen probably has way faster ways to do this.
poutMaxMins()
void ch_eigen::Matrix::poutMaxMins () const inline
debugging aid
References pout().
poutAll()
void ch_eigen::Matrix::poutAll () const inline
debugging aid
References pout().
Referenced by EBCM::Algorithm_Framework< ebcm_order >::getEBSystemMatrix(), and EBCM::Algorithm_Framework< ebcm_order >::getSystemMatrix().
poutRow()
void ch_eigen::Matrix::poutRow (int a_row) const inline
debugging aid
References pout().
Referenced by EBCM::Algorithm_Framework< ebcm_order >::fillDirichletDomBCRow(), EBCM::Algorithm_Framework< ebcm_order >::fillDirichletEBBCRow(), EBCM::Algorithm_Framework< ebcm_order >::fillNeumannDomBCRow(), EBCM::Algorithm_Framework< ebcm_order >::fillNeumannEBBCRow(), and EBCM::Algorithm_Framework< ebcm_order >::shiftMomentAndFillRow().
poutDiag()
void ch_eigen::Matrix::poutDiag () const inline
debugging aid
References pout().
invert()
void ch_eigen::Matrix::invert () inline
This function inverts this matix in place. I only want this to work when the matrix is square as I prefer to deal with Moore-Penrose manually.
setSmallCellRow()
void ch_eigen::Matrix::setSmallCellRow (const int & a_irow) inline
Referenced by EBCM::Algorithm_Framework< ebcm_order >::shiftMomentAndFillRow().
transpose()
void ch_eigen::Matrix::transpose () inline
References m_mat_p.
Referenced by EBCM::Algorithm_Framework< ebcm_order >::getEBSystemMatrix(), and EBCM::Algorithm_Framework< ebcm_order >::getSystemMatrix().
Member Data Documentation
m_mat_p
std::shared_ptr<eigen_mat> ch_eigen::Matrix::m_mat_p
This is the actual matrix. The class has no other data.
Referenced by Matrix(), ch_eigen::multiply(), operator+=(), operator-=(), operator=(), and transpose().
The documentation for this class was generated from the following file:
Chombo_EigenMatrix.H