Chombo_4: ScalarAliasFactory< srcComp, dstComp > Class Template Reference
ScalarAliasFactory< srcComp, dstComp > Class Template Reference
#include <Chombo_EBLevelBoxData.H>
Public Types
typedef CH4_Data_Choreography::DistributedData< EBBoxData< CELL, Real, srcComp > > devi_src_comp_t
typedef CH4_Data_Choreography::DistributedData< EBHostData< CELL, Real, srcComp > > host_src_comp_t
typedef CH4_Data_Choreography::DistributedData< EBBoxData< CELL, Real, dstComp > > devi_dst_comp_t
typedef CH4_Data_Choreography::DistributedData< EBHostData< CELL, Real, dstComp > > host_dst_comp_t
Public Member Functions
ScalarAliasFactory (devi_src_comp_t *a_source, unsigned int a_whichcomp)
virtual ~ScalarAliasFactory ()
virtual EBBoxData< CELL, Real, dstComp > * create (const Box &a_box, int ncomps, const DataIndex &a_datInd) const
factory function. creates a new 'T' object
Public Member Functions inherited from DataFactory< EBBoxData< CELL, Real, dstComp > >
virtual ~DataFactory ()
virtual bool callDelete () const
virtual bool graphConstructor () const
Private Member Functions
ScalarAliasFactory ()
Private Attributes
devi_src_comp_t * m_source
unsigned int m_whichcomp
Member Typedef Documentation
devi_src_comp_t
template<unsigned int srcComp, unsigned int dstComp> typedef CH4_Data_Choreography::DistributedData<EBBoxData< CELL, Real, srcComp> > ScalarAliasFactory< srcComp, dstComp >::devi_src_comp_t
host_src_comp_t
template<unsigned int srcComp, unsigned int dstComp> typedef CH4_Data_Choreography::DistributedData<EBHostData<CELL, Real, srcComp> > ScalarAliasFactory< srcComp, dstComp >::host_src_comp_t
devi_dst_comp_t
template<unsigned int srcComp, unsigned int dstComp> typedef CH4_Data_Choreography::DistributedData<EBBoxData< CELL, Real, dstComp> > ScalarAliasFactory< srcComp, dstComp >::devi_dst_comp_t
host_dst_comp_t
template<unsigned int srcComp, unsigned int dstComp> typedef CH4_Data_Choreography::DistributedData<EBHostData<CELL, Real, dstComp> > ScalarAliasFactory< srcComp, dstComp >::host_dst_comp_t
Constructor & Destructor Documentation
ScalarAliasFactory() [1/2]
template<unsigned int srcComp, unsigned int dstComp> ScalarAliasFactory< srcComp, dstComp >::ScalarAliasFactory (devi_src_comp_t * a_source, unsigned int a_whichcomp) inline
References ScalarAliasFactory< srcComp, dstComp >::m_source, and ScalarAliasFactory< srcComp, dstComp >::m_whichcomp.
~ScalarAliasFactory()
template<unsigned int srcComp, unsigned int dstComp> virtual ScalarAliasFactory< srcComp, dstComp >::~ScalarAliasFactory () inline virtual
ScalarAliasFactory() [2/2]
template<unsigned int srcComp, unsigned int dstComp> ScalarAliasFactory< srcComp, dstComp >::ScalarAliasFactory () private
Referenced by ScalarAliasFactory< srcComp, dstComp >::create().
Member Function Documentation
create()
template<unsigned int srcComp, unsigned int dstComp> virtual EBBoxData<CELL, Real, dstComp>* ScalarAliasFactory< srcComp, dstComp >::create (const Box & a_box, int ncomps, const DataIndex & a_datInd) const inline virtual
factory function. creates a new 'T' object
creates a new 'T' object and returns a pointer to it.
Implements DataFactory< EBBoxData< CELL, Real, dstComp > >.
References Proto::EBBoxData< cent, data_t, ncomp >::define(), ScalarAliasFactory< srcComp, dstComp >::m_whichcomp, and ScalarAliasFactory< srcComp, dstComp >::ScalarAliasFactory().
Member Data Documentation
m_source
template<unsigned int srcComp, unsigned int dstComp> devi_src_comp_t* ScalarAliasFactory< srcComp, dstComp >::m_source private
Referenced by ScalarAliasFactory< srcComp, dstComp >::ScalarAliasFactory().
m_whichcomp
template<unsigned int srcComp, unsigned int dstComp> unsigned int ScalarAliasFactory< srcComp, dstComp >::m_whichcomp private
Referenced by ScalarAliasFactory< srcComp, dstComp >::create(), and ScalarAliasFactory< srcComp, dstComp >::ScalarAliasFactory().
The documentation for this class was generated from the following file:
Chombo_EBLevelBoxData.H