Chombo_4: Proto::DirichletEBFlux< order > Class Template Reference
Proto::DirichletEBFlux< order > Class Template Reference
#include <Proto_SecondOrderCell.H>
Public Types
typedef IndexedMoments< DIM, order > IndMomDIM
typedef IndexedMoments< DIM-1, order > IndMomSDMinOne
typedef HostIrregData< CELL, IndMomDIM, 1 > VoluData
typedef HostIrregData< BOUNDARY, IndMomDIM, 1 > EBFaData
typedef HostIrregData< XFACE, IndMomSDMinOne, 1 > XFacData
typedef HostIrregData< YFACE, IndMomSDMinOne, 1 > YFacData
typedef HostIrregData< ZFACE, IndMomSDMinOne, 1 > ZFacData
Public Member Functions
DirichletEBFlux ()
virtual ~DirichletEBFlux ()
Static Public Member Functions
static void getEBFluxStencil (LocalStencil< CELL, double > &a_facesten, double &a_weight, const EBIndex< BOUNDARY > &a_face, const EBGraph &a_graph, const VoluData &a_voludata, const EBFaData &a_ebfadata, const XFacData &a_xfacdata, const YFacData &a_yfacdata, const ZFacData &a_zfacdata, const double &a_dx)
static void calculateWeightingMatrix (RealVect x0, vector< RealVect > &xp, vector< RealVect > &weightMatrix, bool &detZero)
Member Typedef Documentation
IndMomDIM
template<int order> typedef IndexedMoments<DIM , order> Proto::DirichletEBFlux< order >::IndMomDIM
IndMomSDMinOne
template<int order> typedef IndexedMoments<DIM-1, order> Proto::DirichletEBFlux< order >::IndMomSDMinOne
VoluData
template<int order> typedef HostIrregData<CELL , IndMomDIM , 1> Proto::DirichletEBFlux< order >::VoluData
EBFaData
template<int order> typedef HostIrregData<BOUNDARY, IndMomDIM , 1> Proto::DirichletEBFlux< order >::EBFaData
XFacData
template<int order> typedef HostIrregData<XFACE, IndMomSDMinOne, 1> Proto::DirichletEBFlux< order >::XFacData
YFacData
template<int order> typedef HostIrregData<YFACE, IndMomSDMinOne, 1> Proto::DirichletEBFlux< order >::YFacData
ZFacData
template<int order> typedef HostIrregData<ZFACE, IndMomSDMinOne, 1> Proto::DirichletEBFlux< order >::ZFacData
Constructor & Destructor Documentation
DirichletEBFlux()
template<int order> Proto::DirichletEBFlux< order >::DirichletEBFlux () inline
~DirichletEBFlux()
template<int order> virtual Proto::DirichletEBFlux< order >::~DirichletEBFlux () inline virtual
References Proto::NeumannEBFlux< order >::getEBFluxStencil().
Member Function Documentation
getEBFluxStencil()
template<int order> void Proto::DirichletEBFlux< order >::getEBFluxStencil (LocalStencil< CELL, double > & a_facesten, double & a_weight, const EBIndex< BOUNDARY > & a_face, const EBGraph & a_graph, const VoluData & a_voludata, const EBFaData & a_ebfadata, const XFacData & a_xfacdata, const YFacData & a_yfacdata, const ZFacData & a_zfacdata, const double & a_dx) inline static
References Proto::LocalStencil< cent, data_t >::add(), Proto::LocalStencil< cent, data_t >::clear(), Proto::EBGraph::getAllVoFsWithinRadius(), Proto::Normalizor< order >::getNormalAndBoundaryArea(), Proto::EBIndex< cent >::getVoF(), Proto::EBIndex< cent >::m_pt, Proto::Normalizor< order >::normalizedBndryMoments(), and Proto::RealVect::Zero().
Referenced by Proto::DirichletEBFlux< order >::calculateWeightingMatrix(), and Proto::SecondOrderStencil< order >::get2ndOrderDivFStencil().
calculateWeightingMatrix()
template<int order> void Proto::DirichletEBFlux< order >::calculateWeightingMatrix (RealVect x0, vector< RealVect > & xp, vector< RealVect > & weightMatrix, bool & detZero) inline static
References Proto::DirichletEBFlux< order >::getEBFluxStencil(), and Proto::RealVect::Zero().
Referenced by Proto::SecondOrderStencil< order >::get2ndOrderDivFStencil().
The documentation for this class was generated from the following files:
Proto_SecondOrderCell.H
Proto_SecondOrderCellImplem.H