Chombo_4: Proto::faceMo Class Reference
Proto::faceMo Class Reference
#include <Proto_Moments.H>
Public Member Functions
faceMo ()
void define (const edgeMo a_edges[4], const int &a_faceNormal, const bool &a_covered, const bool &a_regular, const bool &a_dontKnow)
void setFaceArea (const double &a_area)
double getFaceArea () const
void setFaceCentroid (const RealVect &a_centroid)
RealVect getFaceCentroid () const
bool isRegular () const
bool isCovered () const
bool dontKnow () const
double getBdLength () const
void getNormal (double a_normal[2]) const
void getEdges (edgeMo a_Edges[4]) const
edgeMo retrieveEdge (int &a_iEdge) const
int getFaceNormal () const
void makeNormal ()
void normalize (double a_normalVec[2])
Private Member Functions
void operator= (const faceMo &a_input)
faceMo (const faceMo &a_input)
Private Attributes
edgeMo m_edges [4]
double m_normalVec [2]
bool m_covered
bool m_regular
bool m_dontKnow
RealVect m_centroid
double m_areaFrac
int m_faceNormal
double m_bdLength
Constructor & Destructor Documentation
faceMo() [1/2]
Proto::faceMo::faceMo () inline
References Proto::edgeMo::define(), Proto::edgeMo::dontKnow(), Proto::edgeMo::isCovered(), and Proto::edgeMo::isRegular().
faceMo() [2/2]
Proto::faceMo::faceMo (const faceMo & a_input) private
Member Function Documentation
define()
void Proto::faceMo::define (const edgeMo a_edges[4], const int & a_faceNormal, const bool & a_covered, const bool & a_regular, const bool & a_dontKnow)
References Proto::edgeMo::m_covered, Proto::edgeMo::m_dontKnow, and Proto::edgeMo::m_regular.
Referenced by Proto::vofMo::getFaces().
setFaceArea()
void Proto::faceMo::setFaceArea (const double & a_area)
getFaceArea()
double Proto::faceMo::getFaceArea () const
setFaceCentroid()
void Proto::faceMo::setFaceCentroid (const RealVect & a_centroid)
getFaceCentroid()
RealVect Proto::faceMo::getFaceCentroid () const
isRegular()
bool Proto::faceMo::isRegular () const
References Proto::edgeMo::m_regular.
Referenced by Proto::vofMo::define().
isCovered()
bool Proto::faceMo::isCovered () const
References Proto::edgeMo::m_covered.
Referenced by Proto::vofMo::define(), and Proto::Moments::momentCalc3D().
dontKnow()
bool Proto::faceMo::dontKnow () const
References Proto::edgeMo::m_dontKnow.
Referenced by Proto::vofMo::define().
getBdLength()
double Proto::faceMo::getBdLength () const
getNormal()
void Proto::faceMo::getNormal (double a_normal[2]) const
Referenced by Proto::Moments::momentCalc2D().
getEdges()
void Proto::faceMo::getEdges (edgeMo a_Edges[4]) const
Referenced by Proto::vofMo::define(), and Proto::Moments::momentCalc2D().
retrieveEdge()
edgeMo Proto::faceMo::retrieveEdge (int & a_iEdge) const
getFaceNormal()
int Proto::faceMo::getFaceNormal () const
Referenced by Proto::vofMo::define(), and Proto::Moments::momentCalc2D().
makeNormal()
void Proto::faceMo::makeNormal ()
References Proto::edgeMo::moment().
normalize()
void Proto::faceMo::normalize (double a_normalVec[2])
operator=()
void Proto::faceMo::operator= (const faceMo & a_input) private
Member Data Documentation
m_edges
edgeMo Proto::faceMo::m_edges[4] private
m_normalVec
double Proto::faceMo::m_normalVec[2] private
m_covered
bool Proto::faceMo::m_covered private
m_regular
bool Proto::faceMo::m_regular private
m_dontKnow
bool Proto::faceMo::m_dontKnow private
m_centroid
RealVect Proto::faceMo::m_centroid private
m_areaFrac
double Proto::faceMo::m_areaFrac private
m_faceNormal
int Proto::faceMo::m_faceNormal private
m_bdLength
double Proto::faceMo::m_bdLength private
The documentation for this class was generated from the following files:
Proto_Moments.H
Proto_MomentsImplem.H