Chombo_4: LevelBoxData< NUMCOMPS > Class Template Reference
LevelBoxData< NUMCOMPS > Class Template Reference
#include <Chombo_LevelBoxData.H>
Public Member Functions
LevelBoxData ()
LevelBoxData (const DisjointBoxLayout &a_dp, const IntVect &a_ghost=IntVect::Zero)
virtual ~LevelBoxData ()
void define (const DisjointBoxLayout &a_dp, const IntVect &a_ghost=IntVect::Zero)
void define (const LevelBoxData< NUMCOMPS > &a_lbd)
void copyTo (const Interval &a_srcComps, LevelData< BoxData< Real, NUMCOMPS > > &a_dst, const Interval &a_dstComps, const Copier &a_copier)
virtual void exchange (const Copier &copier)
void writeToFileHDF5 (const string &a_filename) const
Public Member Functions inherited from LevelData< BoxData< Real, NUMCOMPS > >
LevelData ()
LevelData (const DisjointBoxLayout &dp, int comps, const IntVect &ghost=IntVect::Zero, const DataFactory< BoxData< Real, NUMCOMPS > > &a_factory=DefaultDataFactory< BoxData< Real, NUMCOMPS > >())
virtual ~LevelData ()
void define (const DisjointBoxLayout &dp, int comps, const IntVect &ghost=IntVect::Zero, const DataFactory< BoxData< Real, NUMCOMPS > > &a_factory=DefaultDataFactory< BoxData< Real, NUMCOMPS > >())
void define (const LevelData< BoxData< Real, NUMCOMPS > > &da, const DataFactory< BoxData< Real, NUMCOMPS > > &a_factory=DefaultDataFactory< BoxData< Real, NUMCOMPS > >())
void define (const LevelData< BoxData< Real, NUMCOMPS > > &da, const Interval &comps, const DataFactory< BoxData< Real, NUMCOMPS > > &a_factory=DefaultDataFactory< BoxData< Real, NUMCOMPS > >())
void copyTo (const Interval &srcComps, BoxLayoutData< BoxData< Real, NUMCOMPS > > &dest, const Interval &destComps) const
void copyTo (BoxLayoutData< BoxData< Real, NUMCOMPS > > &dest) const
Simplest case – assumes source and dest have same interval.
void copyTo (const Interval &srcComps, BoxLayoutData< BoxData< Real, NUMCOMPS > > &dest, const Interval &destComps, const Copier &copier, const LDOperator< BoxData< Real, NUMCOMPS > > &a_op=LDOperator< BoxData< Real, NUMCOMPS > >()) const
void copyTo (BoxLayoutData< BoxData< Real, NUMCOMPS > > &dest, const Copier &copier, const LDOperator< BoxData< Real, NUMCOMPS > > &a_op=LDOperator< BoxData< Real, NUMCOMPS > >()) const
Simplest case – assumes source and dest have same interval.
void copyTo (const Interval &srcComps, LevelData< BoxData< Real, NUMCOMPS > > &dest, const Interval &destComps) const
void copyTo (LevelData< BoxData< Real, NUMCOMPS > > &dest) const
Simplest case – assumes source and dest have same interval.
void copyTo (const Interval &srcComps, LevelData< BoxData< Real, NUMCOMPS > > &dest, const Interval &destComps, const Copier &copier, const LDOperator< BoxData< Real, NUMCOMPS > > &a_op=LDOperator< BoxData< Real, NUMCOMPS > >()) const
void copyTo (LevelData< BoxData< Real, NUMCOMPS > > &dest, const Copier &copier, const LDOperator< BoxData< Real, NUMCOMPS > > &a_op=LDOperator< BoxData< Real, NUMCOMPS > >()) const
Simplest case – assumes source and dest have same interval.
void localCopyTo (const Interval &srcComps, LevelData< BoxData< Real, NUMCOMPS > > &dest, const Interval &destComps) const
only works if source and dest have the same disjointboxlayout
void localCopyTo (LevelData< BoxData< Real, NUMCOMPS > > &dest) const
assumes source and dest have same interval
void exchange (bool a_printStuff=false)
Simplest case – do all components.
void exchange (const Copier &copier, bool a_printStuff=false)
Simplest case – do all components. Accepts a pre-built copier.
void exchange (const Interval &comps, bool a_printStuff=false)
Accepts an arbitrary component range.
void exchange (const Interval &comps, const Copier &copier, const LDOperator< BoxData< Real, NUMCOMPS > > &a_op=LDOperator< BoxData< Real, NUMCOMPS > >(), bool a_printStuff=false)
void exchangeBegin (const Copier &copier)
asynchronous exchange start. load and fire off messages.
void exchangeEnd ()
finish asynchronous exchange
void exchangeNoOverlap (const Copier &copier)
const IntVect & ghostVect () const
const DisjointBoxLayout & getBoxes () const
const DisjointBoxLayout & disjointBoxLayout () const
void apply (void(*a_Function)(const Box &, int, BoxData< Real, NUMCOMPS > &))
void apply (const ApplyFunctor &)
void degenerate (LevelData< BoxData< Real, NUMCOMPS > > &a_to, const SliceSpec &a_ss) const
void degenerateLocalOnly (LevelData< BoxData< Real, NUMCOMPS > > &a_to, const SliceSpec &a_ss) const
version of degenerate which does strictly local copying
void degenerateLocalOnly (LevelData< FluxBox > &a_to, const SliceSpec &a_ss) const
void define (const BoxLayout &dp, int comps, const DataFactory< BoxData< Real, NUMCOMPS > > &factory)
void define (const BoxLayoutData< BoxData< Real, NUMCOMPS > > &da, const DataFactory< BoxData< Real, NUMCOMPS > > &factory=DefaultDataFactory< BoxData< Real, NUMCOMPS > >())
void define (const BoxLayoutData< BoxData< Real, NUMCOMPS > > &da, const Interval &comps, const DataFactory< BoxData< Real, NUMCOMPS > > &factory=DefaultDataFactory< BoxData< Real, NUMCOMPS > >())
void define (const BoxLayout &deadFunction)
overridden and throws an error.
Public Member Functions inherited from BoxLayoutData< BoxData< Real, NUMCOMPS > >
BoxLayoutData ()
BoxLayoutData (const BoxLayout &boxes, int comps, const DataFactory< BoxData< Real, NUMCOMPS > > &factory=DefaultDataFactory< BoxData< Real, NUMCOMPS > >())
virtual ~BoxLayoutData ()
int nComp () const
Interval interval () const
void generalCopyTo (const BoxLayout &a_destGrids, LayoutData< std::vector< RefCountedPtr< BoxData< Real, NUMCOMPS > > > > &a_dest, const Interval &a_interval, const ProblemDomain &a_domain, const DataFactory< BoxData< Real, NUMCOMPS > > &factory=DefaultDataFactory< BoxData< Real, NUMCOMPS > >()) const
General data copying operation.
void generalCopyTo (const BoxLayout &a_destGrids, LayoutData< std::vector< RefCountedPtr< BoxData< Real, NUMCOMPS > > > > &a_dest, const Interval &a_interval, const ProblemDomain &a_domain, const Copier &a_copier, const DataFactory< BoxData< Real, NUMCOMPS > > &factory=DefaultDataFactory< BoxData< Real, NUMCOMPS > >()) const
void addTo (const Interval &a_srcComps, BoxLayoutData< BoxData< Real, NUMCOMPS > > &a_dest, const Interval &a_destComps, const ProblemDomain &a_domain) const
void addTo (const Interval &a_srcComps, BoxLayoutData< BoxData< Real, NUMCOMPS > > &a_dest, const Interval &a_destComps, const ProblemDomain &a_domain, const Copier &a_copier) const
void addToBegin (const Interval &a_srcComps, BoxLayoutData< BoxData< Real, NUMCOMPS > > &a_dest, const Interval &a_destComps, const Copier &a_copier) const
void addToEnd (const Interval &a_destComps)
you call this on the destination BoxLayoutData, not the source.
virtual void apply (void(*a_Function)(const Box &box, int comps, BoxData< Real, NUMCOMPS > &t))
virtual bool isDefined () const
virtual void clear ()
Public Member Functions inherited from LayoutData< BoxData< Real, NUMCOMPS > >
LayoutData ()
LayoutData (const BoxLayout &a_dp)
virtual ~LayoutData ()
DataIterator dataIterator () const
TimedDataIterator timedDataIterator () const
const BoxData< Real, NUMCOMPS > & operator[] (const DataIndex &a_index) const
const accessor function
const BoxData< Real, NUMCOMPS > & operator[] (const DataIterator &a_iterator) const
const accessor function
BoxData< Real, NUMCOMPS > & operator[] (const DataIndex &a_index)
non-const accessor function
BoxData< Real, NUMCOMPS > & operator[] (const DataIterator &a_iterator)
non-const accessor function
Box box (const DataIndex &a_index) const
Box box (const DataIterator &a_iterator) const
const BoxLayout & boxLayout () const
Static Public Member Functions
static void copyToHost (LevelData< FArrayBox > &a_hostDat, const LevelData< BoxData< Real, NUMCOMPS > > &a_deviDat)
This function is no longer used in exchange due to the Gpu to Gpu strategy.
static void copyToDevice (LevelData< BoxData< Real, NUMCOMPS > > &a_deviDat, const LevelData< FArrayBox > &a_hostDat)
Private Attributes
LevelData< FArrayBox > m_host
LevelData< FArrayBox > m_hostSrc
LevelData< FArrayBox > m_hostDst
Additional Inherited Members
Protected Member Functions inherited from BoxLayoutData< BoxData< Real, NUMCOMPS > >
void setVector (const BoxLayoutData< BoxData< Real, NUMCOMPS > > &da, const Interval &srcComps, const Interval &destComps)
void allocateGhostVector (const DataFactory< BoxData< Real, NUMCOMPS > > &factory, const IntVect &ghost=IntVect::Zero)
void makeItSo (const Interval &a_srcComps, const BoxLayoutData< BoxData< Real, NUMCOMPS > > &a_src, BoxLayoutData< BoxData< Real, NUMCOMPS > > &a_dest, const Interval &a_destComps, const Copier &a_copier, const LDOperator< BoxData< Real, NUMCOMPS > > &a_op=LDOperator< BoxData< Real, NUMCOMPS > >(), bool a_printStuff=false) const
void makeItSoBegin (const Interval &a_srcComps, const BoxLayoutData< BoxData< Real, NUMCOMPS > > &a_src, BoxLayoutData< BoxData< Real, NUMCOMPS > > &a_dest, const Interval &a_destComps, const Copier &a_copier, const LDOperator< BoxData< Real, NUMCOMPS > > &a_op=LDOperator< BoxData< Real, NUMCOMPS > >(), bool a_printStuff=false) const
void makeItSoLocalCopy (const Interval &a_srcComps, const BoxLayoutData< BoxData< Real, NUMCOMPS > > &a_src, BoxLayoutData< BoxData< Real, NUMCOMPS > > &a_dest, const Interval &a_destComps, const Copier &a_copier, const LDOperator< BoxData< Real, NUMCOMPS > > &a_op=LDOperator< BoxData< Real, NUMCOMPS > >(), bool a_printStuff=false) const
void makeItSoEnd (const Interval &a_destComps, const LDOperator< BoxData< Real, NUMCOMPS > > &a_op=LDOperator< BoxData< Real, NUMCOMPS > >(), bool a_printStuff=false)
void completePendingSends () const
void allocateBuffers (const BoxLayoutData< BoxData< Real, NUMCOMPS > > &a_src, const Interval &a_srcComps, const BoxLayoutData< BoxData< Real, NUMCOMPS > > &a_dest, const Interval &a_destComps, const Copier &a_copier, const LDOperator< BoxData< Real, NUMCOMPS > > &a_op, bool a_printStuff=false) const
void writeSendDataFromMeIntoBuffers (const BoxLayoutData< BoxData< Real, NUMCOMPS > > &a_src, const Interval &a_srcComps, const LDOperator< BoxData< Real, NUMCOMPS > > &a_op) const
void postSendsFromMe () const
void postReceivesToMe () const
void unpackReceivesToMe (const Interval &a_destComps, const LDOperator< BoxData< Real, NUMCOMPS > > &a_op)
void unpackReceivesToMe_append (LayoutData< std::vector< RefCountedPtr< BoxData< Real, NUMCOMPS > > > > &a_dest, const Interval &a_destComps, int ncomp, const DataFactory< BoxData< Real, NUMCOMPS > > &factory, const LDOperator< BoxData< Real, NUMCOMPS > > &a_op)
Protected Attributes inherited from LevelData< BoxData< Real, NUMCOMPS > >
DisjointBoxLayout m_disjointBoxLayout
IntVect m_ghost
Copier m_exchangeCopier
Protected Attributes inherited from BoxLayoutData< BoxData< Real, NUMCOMPS > >
int m_comps
bool m_isdefined
CopierBuffer * m_buff
Protected Attributes inherited from LayoutData< BoxData< Real, NUMCOMPS > >
BoxLayout m_boxLayout
std::vector< BoxData< Real, NUMCOMPS > *> m_vector
bool m_callDelete
Constructor & Destructor Documentation
LevelBoxData() [1/2]
template<int NUMCOMPS> LevelBoxData< NUMCOMPS >::LevelBoxData () inline
LevelBoxData() [2/2]
template<int NUMCOMPS> LevelBoxData< NUMCOMPS >::LevelBoxData (const DisjointBoxLayout & a_dp, const IntVect & a_ghost = IntVect::Zero) inline
~LevelBoxData()
template<int NUMCOMPS> virtual LevelBoxData< NUMCOMPS >::~LevelBoxData () inline virtual
Member Function Documentation
define() [1/2]
template<int NUMCOMPS> void LevelBoxData< NUMCOMPS >::define (const DisjointBoxLayout & a_dp, const IntVect & a_ghost = IntVect::Zero) inline
References IntVect::Zero.
define() [2/2]
template<int NUMCOMPS> void LevelBoxData< NUMCOMPS >::define (const LevelBoxData< NUMCOMPS > & a_lbd) inline
copyTo()
template<int NUMCOMPS> void LevelBoxData< NUMCOMPS >::copyTo (const Interval & a_srcComps, LevelData< BoxData< Real, NUMCOMPS > > & a_dst, const Interval & a_dstComps, const Copier & a_copier) inline
References LevelData< T >::copyTo().
exchange()
template<int NUMCOMPS> virtual void LevelBoxData< NUMCOMPS >::exchange (const Copier & copier) inline virtual
References CH_START, CH_STOP, CH_TIMER, and CH_TIMERS.
writeToFileHDF5()
template<int NUMCOMPS> void LevelBoxData< NUMCOMPS >::writeToFileHDF5 (const string & a_filename) const inline
References writeLevelname().
copyToHost()
template<int NUMCOMPS> static void LevelBoxData< NUMCOMPS >::copyToHost (LevelData< FArrayBox > & a_hostDat, const LevelData< BoxData< Real, NUMCOMPS > > & a_deviDat) inline static
This function is no longer used in exchange due to the Gpu to Gpu strategy.
References LayoutData< T >::dataIterator(), and BaseFab< T >::dataPtr().
copyToDevice()
template<int NUMCOMPS> static void LevelBoxData< NUMCOMPS >::copyToDevice (LevelData< BoxData< Real, NUMCOMPS > > & a_deviDat, const LevelData< FArrayBox > & a_hostDat) inline static
References LayoutData< T >::dataIterator(), and BaseFab< T >::dataPtr().
Member Data Documentation
m_host
template<int NUMCOMPS> LevelData<FArrayBox> LevelBoxData< NUMCOMPS >::m_host private
m_hostSrc
template<int NUMCOMPS> LevelData<FArrayBox> LevelBoxData< NUMCOMPS >::m_hostSrc private
m_hostDst
template<int NUMCOMPS> LevelData<FArrayBox> LevelBoxData< NUMCOMPS >::m_hostDst private
The documentation for this class was generated from the following file:
Chombo_LevelBoxData.H