Chombo_4: DataIterator Class Reference
DataIterator Class Reference
#include <Chombo_DataIterator.H>
Public Member Functions
virtual ~DataIterator ()
DataIterator ()
DataIterator (const BoxLayout &a_layout)
const DataIndex & operator() () const
return the index that this iterator is at
DataIndex i () const
return a copy of the index that this iterator is at
int size () const
DataIndex operator[] (int ivec) const
void clearTime ()
load balancing function. no-op in serial
void clearPeak ()
load balancing function. no-op in serial
std::vector< unsigned long long > getTime () const
load balancing function. no-op in serial
std::vector< unsigned long long > getPeak () const
std::vector< Box > getBoxes () const
void enableTime ()
load balancing function. no-op in serial
void enablePeak ()
void disableTime ()
load balancing function. no-op in serial
void disablePeak ()
void mergeTime ()
load balancing function. no-op in serial
void mergePeak ()
Public Member Functions inherited from LayoutIterator
LayoutIterator ()
a null constructed LayoutIterator will return false on ok()
virtual ~LayoutIterator ()
const LayoutIndex & operator() () const
return the index that this iterator is at
LayoutIndex i () const
return a copy of the index that this iterator is at
virtual void operator++ ()
move the iterator to the next Box in the layout
void incr ()
move the iterator to the next Box in the layout
virtual bool ok () const
return true if this iterator is still in its Layout
void begin ()
initialize this iterator to the first Box in its Layout
void reset ()
same as begin()
void end ()
move this iterator to after the last Box in the layout
const LayoutIndex & operator[] (int ivec) const
LayoutIndex & operator[] (int ivec)
Protected Member Functions
DataIterator (const BoxLayout &boxlayout, const int *layoutID)
Protected Member Functions inherited from LayoutIterator
LayoutIterator (const BoxLayout &a_boxlayout, const int *a_layoutID)
Friends
class BoxLayout
class DisjointBoxLayout
class TimedDataIterator
Additional Inherited Members
Protected Attributes inherited from LayoutIterator
BoxLayout m_layout
RefCountedPtr< std::vector< LayoutIndex > > m_indicies
unsigned int m_current
Constructor & Destructor Documentation
~DataIterator()
virtual DataIterator::~DataIterator () inline virtual
DataIterator() [1/3]
DataIterator::DataIterator () inline
DataIterator() [2/3]
DataIterator::DataIterator (const BoxLayout & a_layout) inline
References BoxLayout::dataIterator().
DataIterator() [3/3]
DataIterator::DataIterator (const BoxLayout & boxlayout, const int * layoutID) inline protected
Member Function Documentation
operator()()
const DataIndex& DataIterator::operator() () const inline
return the index that this iterator is at
Aborts if the iterator is not ok()
References LayoutIterator::operator()().
i()
DataIndex DataIterator::i () const inline
return a copy of the index that this iterator is at
Aborts if the iterator is not ok()
References LayoutIterator::operator()().
size()
int DataIterator::size () const inline
References LayoutIterator::m_layout, and BoxLayout::size().
Referenced by LevelGeometryService< order >::coarsenData(), LevelGeometryService< order >::coarsenGraph(), LevelGeometryService< order >::defineFinestLevel(), EBDictionary< order, data_t, srcCenter, dstCenter >::EBDictionary(), LevelGeometryService< order >::LevelGeometryService(), and EBDictionary< order, data_t, srcCenter, dstCenter >::registerStencil().
operator[]()
DataIndex DataIterator::operator[] (int ivec) const inline
clearTime()
void DataIterator::clearTime () inline
load balancing function. no-op in serial
clearPeak()
void DataIterator::clearPeak () inline
load balancing function. no-op in serial
getTime()
std::vector<unsigned long long> DataIterator::getTime () const inline
load balancing function. no-op in serial
References LayoutIterator::m_layout, and BoxLayout::size().
getPeak()
std::vector<unsigned long long> DataIterator::getPeak () const inline
References LayoutIterator::m_layout, and BoxLayout::size().
getBoxes()
std::vector<Box> DataIterator::getBoxes () const inline
References BoxLayout::boxArray(), and LayoutIterator::m_layout.
enableTime()
void DataIterator::enableTime () inline
load balancing function. no-op in serial
enablePeak()
void DataIterator::enablePeak () inline
disableTime()
void DataIterator::disableTime () inline
load balancing function. no-op in serial
disablePeak()
void DataIterator::disablePeak () inline
mergeTime()
void DataIterator::mergeTime () inline
load balancing function. no-op in serial
mergePeak()
void DataIterator::mergePeak () inline
Friends And Related Function Documentation
BoxLayout
friend class BoxLayout friend
DisjointBoxLayout
friend class DisjointBoxLayout friend
TimedDataIterator
friend class TimedDataIterator friend
The documentation for this class was generated from the following file:
Chombo_DataIterator.H