Chombo_4: Proto::AggStencil< srcCenter, dstCenter, data_t > Class Template Reference
Proto::AggStencil< srcCenter, dstCenter, data_t > Class Template Reference
#include <Proto_AggStencil.H>
Public Types
typedef vector< pair_t< data_t > > stencil_t
EBDataLoc defined in Proto_EBBoxData.H.
Public Member Functions
AggStencil (const vector< EBIndex< dstCenter > > &a_dstVoFs, const vector< LocalStencil< srcCenter, data_t > > &a_stencil, const EBGraph &a_srcGraph, const EBGraph &a_dstGraph, const Box &a_srcValid, const Box &a_dstValid, const Point &a_srcGhost, const Point &a_dstGhost)
~AggStencil ()
void apply (EBBoxData< dstCenter, data_t, 1 > &a_lph, const EBBoxData< srcCenter, data_t, 1 > &a_phi, const data_t &a_scale, bool a_incrementOnly, bool a_printStuff=false) const
Protected Member Functions
void hostAggStencilIndexer (int a_begin, int a_end, int idx, const data_t *a_dataPtrsSrc[2], data_t *a_dataPtrsDst[2], const pair_t< data_t > *a_ebstencil, const uint64_t *a_stensizes, const uint64_t *a_stenstart, const EBDataLoc *a_dstaccess, bool a_incrementOnly, data_t a_scale, bool a_printStuff) const
void hostApply (EBBoxData< dstCenter, data_t, 1 > &a_lph, const EBBoxData< srcCenter, data_t, 1 > &a_phi, const data_t &a_scale, bool a_incrementOnly, bool a_printStuff=false) const
void hostPrep (const vector< pair_t< data_t > > &h_serializedStenInfo, const vector< uint64_t > &h_stenSizes, const vector< uint64_t > &h_stenStart)
void hostRelease ()
Protected Attributes
vector< stencil_t > m_ebstencil
this stuff lives on the host
vector< EBDataLoc > m_dstAccess
int m_flopsThisApply = 0
pair_t< data_t > * d_ebstencil = nullptr
this stuff lives on the device
EBDataLoc * d_dstaccess = nullptr
uint64_t * d_stensizes = nullptr
uint64_t * d_stenstart = nullptr
Box m_srcBox
Box m_dstBox
Private Member Functions
AggStencil ()
disallowed operators.
AggStencil & operator= (const AggStencil &stenin)
AggStencil (const AggStencil &stenin)
Member Typedef Documentation
stencil_t
template<CENTERING srcCenter, CENTERING dstCenter, typename data_t > typedef vector< pair_t<data_t> > Proto::AggStencil< srcCenter, dstCenter, data_t >::stencil_t
EBDataLoc defined in Proto_EBBoxData.H.
Constructor & Destructor Documentation
AggStencil() [1/3]
template<CENTERING srcCenter, CENTERING dstCenter, typename data_t > Proto::AggStencil< srcCenter, dstCenter, data_t >::AggStencil (const vector< EBIndex< dstCenter > > & a_dstVoFs, const vector< LocalStencil< srcCenter, data_t > > & a_stencil, const EBGraph & a_srcGraph, const EBGraph & a_dstGraph, const Box & a_srcValid, const Box & a_dstValid, const Point & a_srcGhost, const Point & a_dstGhost)
References Box::grow(), Proto::AggStencil< srcCenter, dstCenter, data_t >::hostPrep(), Proto::EBBoxData< cent, data_t, ncomp >::indexInfo(), Proto::LocalStencil< cent, data_t >::m_entries, and Proto::LocalStencil< cent, data_t >::size().
~AggStencil()
template<CENTERING srcCenter, CENTERING dstCenter, typename data_t > Proto::AggStencil< srcCenter, dstCenter, data_t >::~AggStencil () inline
AggStencil() [2/3]
template<CENTERING srcCenter, CENTERING dstCenter, typename data_t > Proto::AggStencil< srcCenter, dstCenter, data_t >::AggStencil () private
disallowed operators.
AggStencil() [3/3]
template<CENTERING srcCenter, CENTERING dstCenter, typename data_t > Proto::AggStencil< srcCenter, dstCenter, data_t >::AggStencil (const AggStencil< srcCenter, dstCenter, data_t > & stenin) private
Member Function Documentation
apply()
template<CENTERING srcCenter, CENTERING dstCenter, typename data_t > void Proto::AggStencil< srcCenter, dstCenter, data_t >::apply (EBBoxData< dstCenter, data_t, 1 > & a_lph, const EBBoxData< srcCenter, data_t, 1 > & a_phi, const data_t & a_scale, bool a_incrementOnly, bool a_printStuff = false) const
lphi = L(phi)
References Proto::AggStencil< srcCenter, dstCenter, data_t >::hostAggStencilIndexer(), and Proto::EBBoxData< cent, data_t, ncomp >::inputBox().
Referenced by Proto::AggStencil< srcCenter, dstCenter, data_t >::hostPrep().
hostAggStencilIndexer()
template<CENTERING srcCenter, CENTERING dstCenter, typename data_t > void Proto::AggStencil< srcCenter, dstCenter, data_t >::hostAggStencilIndexer (int a_begin, int a_end, int idx, const data_t * a_dataPtrsSrc[2], data_t * a_dataPtrsDst[2], const pair_t< data_t > * a_ebstencil, const uint64_t * a_stensizes, const uint64_t * a_stenstart, const EBDataLoc * a_dstaccess, bool a_incrementOnly, data_t a_scale, bool a_printStuff) const protected
References Proto::pair_t< data_t >::first, Proto::AggStencil< srcCenter, dstCenter, data_t >::hostApply(), Proto::EBDataLoc::m_dataID, Proto::EBDataLoc::m_offset, and Proto::pair_t< data_t >::second.
Referenced by Proto::AggStencil< srcCenter, dstCenter, data_t >::apply().
hostApply()
template<CENTERING srcCenter, CENTERING dstCenter, typename data_t > void Proto::AggStencil< srcCenter, dstCenter, data_t >::hostApply (EBBoxData< dstCenter, data_t, 1 > & a_lph, const EBBoxData< srcCenter, data_t, 1 > & a_phi, const data_t & a_scale, bool a_incrementOnly, bool a_printStuff = false) const protected
References Proto::EBBoxData< cent, data_t, ncomp >::dataPtr(), and Proto::AggStencil< srcCenter, dstCenter, data_t >::hostRelease().
Referenced by Proto::AggStencil< srcCenter, dstCenter, data_t >::hostAggStencilIndexer().
hostPrep()
template<CENTERING srcCenter, CENTERING dstCenter, typename data_t > void Proto::AggStencil< srcCenter, dstCenter, data_t >::hostPrep (const vector< pair_t< data_t > > & h_serializedStenInfo, const vector< uint64_t > & h_stenSizes, const vector< uint64_t > & h_stenStart) protected
allocate memory on the device
copy from the host
References Proto::AggStencil< srcCenter, dstCenter, data_t >::apply().
Referenced by Proto::AggStencil< srcCenter, dstCenter, data_t >::AggStencil().
hostRelease()
template<CENTERING srcCenter, CENTERING dstCenter, typename data_t > void Proto::AggStencil< srcCenter, dstCenter, data_t >::hostRelease () protected
Referenced by Proto::AggStencil< srcCenter, dstCenter, data_t >::hostApply().
operator=()
template<CENTERING srcCenter, CENTERING dstCenter, typename data_t > AggStencil& Proto::AggStencil< srcCenter, dstCenter, data_t >::operator= (const AggStencil< srcCenter, dstCenter, data_t > & stenin) private
Member Data Documentation
m_ebstencil
template<CENTERING srcCenter, CENTERING dstCenter, typename data_t > vector<stencil_t> Proto::AggStencil< srcCenter, dstCenter, data_t >::m_ebstencil protected
this stuff lives on the host
m_dstAccess
template<CENTERING srcCenter, CENTERING dstCenter, typename data_t > vector<EBDataLoc> Proto::AggStencil< srcCenter, dstCenter, data_t >::m_dstAccess protected
m_flopsThisApply
template<CENTERING srcCenter, CENTERING dstCenter, typename data_t > int Proto::AggStencil< srcCenter, dstCenter, data_t >::m_flopsThisApply = 0 protected
d_ebstencil
template<CENTERING srcCenter, CENTERING dstCenter, typename data_t > pair_t<data_t>* Proto::AggStencil< srcCenter, dstCenter, data_t >::d_ebstencil = nullptr protected
this stuff lives on the device
d_dstaccess
template<CENTERING srcCenter, CENTERING dstCenter, typename data_t > EBDataLoc* Proto::AggStencil< srcCenter, dstCenter, data_t >::d_dstaccess = nullptr protected
d_stensizes
template<CENTERING srcCenter, CENTERING dstCenter, typename data_t > uint64_t* Proto::AggStencil< srcCenter, dstCenter, data_t >::d_stensizes = nullptr protected
d_stenstart
template<CENTERING srcCenter, CENTERING dstCenter, typename data_t > uint64_t* Proto::AggStencil< srcCenter, dstCenter, data_t >::d_stenstart = nullptr protected
m_srcBox
template<CENTERING srcCenter, CENTERING dstCenter, typename data_t > Box Proto::AggStencil< srcCenter, dstCenter, data_t >::m_srcBox protected
m_dstBox
template<CENTERING srcCenter, CENTERING dstCenter, typename data_t > Box Proto::AggStencil< srcCenter, dstCenter, data_t >::m_dstBox protected
The documentation for this class was generated from the following files:
Proto_AggStencil.H
Proto_AggStencilImplem.H