Chombo_4: Proto::MomentIterator< D, P > Class Template Reference
Proto::MomentIterator< D, P > Class Template Reference
iterates through the indices of a IndexedMoment
#include <Proto_MomentIterator.H>
Public Member Functions
MomentIterator ()
virtual ~MomentIterator ()
virtual void reset ()
virtual void operator++ ()
virtual const IndexTM< int, D > & operator() () const
virtual bool ok ()
virtual int size () const
Public Member Functions inherited from Proto::BaseMomentIterator< D >
BaseMomentIterator ()
virtual ~BaseMomentIterator ()
Protected Attributes
const vector< IndexTM< int, D > > * m_indicies
points to the (static) powers that live in IndexedMoments
int m_current
Detailed Description
template<int D, int P>
class Proto::MomentIterator< D, P >
iterates through the indices of a IndexedMoment
MomentIterator iterates through the multi-indices of a IndexedMoments.
Constructor & Destructor Documentation
MomentIterator()
template<int D, int P> Proto::MomentIterator< D, P >::MomentIterator () inline
References Proto::IndexedMoments< Dim, P >::getMonomialPowers().
~MomentIterator()
template<int D, int P> virtual Proto::MomentIterator< D, P >::~MomentIterator () inline virtual
Member Function Documentation
reset()
template<int D, int P> virtual void Proto::MomentIterator< D, P >::reset () inline virtual
Implements Proto::BaseMomentIterator< D >.
Referenced by Proto::checkMoments().
operator++()
template<int D, int P> virtual void Proto::MomentIterator< D, P >::operator++ () inline virtual
Implements Proto::BaseMomentIterator< D >.
operator()()
template<int D, int P> virtual const IndexTM<int, D>& Proto::MomentIterator< D, P >::operator() () const inline virtual
Returns the moment of the current multi-index of this MomentIterator.
Implements Proto::BaseMomentIterator< D >.
ok()
template<int D, int P> virtual bool Proto::MomentIterator< D, P >::ok () inline virtual
Returns true if this MomentIterator's location is within its IndexedMoment.
Implements Proto::BaseMomentIterator< D >.
Referenced by Proto::checkMoments(), Proto::IndexedMoments< DIM-1, order >::divideByFactorial(), EBCM::Algorithm_Framework< ebcm_order >::fillDirichletDomBCRow(), EBCM::Algorithm_Framework< ebcm_order >::fillDirichletEBBCRow(), EBCM::Algorithm_Framework< ebcm_order >::fillNeumannDomBCRow(), EBCM::Algorithm_Framework< ebcm_order >::fillNeumannEBBCRow(), ebcm_basics::getVolMomFromFacMom(), Proto::IndexedMoments< DIM-1, order >::multiplyByFactorial(), Proto::Normalizor< order >::normalizeFaceMoment(), Proto::Normalizor< order >::normalizeVolumeMoment(), BaseExactSolution::operator()(), Proto::IndexedMoments< DIM-1, order >::operator*=(), Proto::IndexedMoments< DIM-1, order >::operator+=(), Proto::IndexedMoments< DIM-1, order >::operator=(), Proto::IndexedMoments< DIM-1, order >::print(), Proto::IndexedMoments< DIM-1, order >::setToTruncatedMultiply(), Proto::IndexedMoments< DIM-1, order >::shift(), and EBCM::Algorithm_Framework< ebcm_order >::shiftMomentAndFillRow().
size()
template<int D, int P> virtual int Proto::MomentIterator< D, P >::size () const inline virtual
Implements Proto::BaseMomentIterator< D >.
Member Data Documentation
m_indicies
template<int D, int P> const vector<IndexTM<int,D> >* Proto::MomentIterator< D, P >::m_indicies protected
points to the (static) powers that live in IndexedMoments
m_current
template<int D, int P> int Proto::MomentIterator< D, P >::m_current protected
The documentation for this class was generated from the following file:
Proto_MomentIterator.H