Chombo_4: LayoutData< T > Class Template Reference
LayoutData< T > Class Template Reference
Data that maintains a one-to-one mapping of T to the boxes in a BoxLayout.
#include <Chombo_LayoutData.H>
Public Member Functions
LayoutData ()
LayoutData (const BoxLayout &a_dp)
virtual ~LayoutData ()
virtual void define (const BoxLayout &a_dp)
DataIterator dataIterator () const
TimedDataIterator timedDataIterator () const
const T & operator[] (const DataIndex &a_index) const
const accessor function
const T & operator[] (const DataIterator &a_iterator) const
const accessor function
T & operator[] (const DataIndex &a_index)
non-const accessor function
T & operator[] (const DataIterator &a_iterator)
non-const accessor function
Box box (const DataIndex &a_index) const
Box box (const DataIterator &a_iterator) const
const BoxLayout & boxLayout () const
Protected Attributes
BoxLayout m_boxLayout
std::vector< T * > m_vector
bool m_callDelete
Private Member Functions
LayoutData< T > & operator= (const LayoutData< T > &a_rhs)
LayoutData (const LayoutData &a_rhs)
void allocate ()
Friends
class BoxLayout
Detailed Description
template<class T>
class LayoutData< T >
Data that maintains a one-to-one mapping of T to the boxes in a BoxLayout.
A collection of Box-oriented objects. The arrangement of the T objects is given by the underlying BoxLayout object. LayoutData does not attempt to prevent users from manipulating the template class T to become out of synch with the boxes in the BoxLayout. Caveat emptor.
Non-local (off-processor access) to a LayoutData index is an error. You can assure that access to the data stored in a LayoutData is local to your processor by using the DataIterator object for indexing.
Data in a LayoutData CANNOT be communicated to other processors using the API presented in LevelData.
class T must provide the following methods:
{
  T()
}
This class is useful for processor-local data that needs to be indexable along with a BoxLayoutData. Auxillary data objects, etc.
Constructor & Destructor Documentation
LayoutData() [1/3]
template<class T > LayoutData< T >::LayoutData () inline
LayoutData() [2/3]
template<class T > LayoutData< T >::LayoutData (const BoxLayout & a_dp) inline
constructor. allocates a T object for every box in the BoxLayout a_dp using the T null constructor. a_dp must be closed.
~LayoutData()
template<class T > LayoutData< T >::~LayoutData () inline virtual
LayoutData() [3/3]
template<class T> LayoutData< T >::LayoutData (const LayoutData< T > & a_rhs) private
Member Function Documentation
define()
template<class T > void LayoutData< T >::define (const BoxLayout & a_dp) inline virtual
constructor. allocates a T object for every box in the BoxLayout a_dp using the T null constructor. a_dp must be closed. previously stored T objects are removed
Reimplemented in BoxLayoutData< T >, BoxLayoutData< FluxBox >, BoxLayoutData< BoxData< Real, NUMCOMPS > >, BoxLayoutData< FArrayBox >, LevelData< T >, LevelData< BoxData< Real, NUMCOMPS > >, and LevelData< FArrayBox >.
Referenced by LevelGeometryService< order >::defineFinestLevel().
dataIterator()
template<class T > DataIterator LayoutData< T >::dataIterator () const inline
Referenced by LayoutData< FArrayBox >::allocate(), BoxLayoutData< FArrayBox >::allocateGhostVector(), LevelData< FArrayBox >::apply(), BoxLayoutData< FArrayBox >::apply(), LevelData< FArrayBox >::copyTo(), LevelBoxData< NUMCOMPS >::copyToDevice(), LevelBoxData< NUMCOMPS >::copyToHost(), LevelData< FArrayBox >::define(), LevelData< FArrayBox >::degenerateLocalOnly(), LevelData< FArrayBox >::localCopyTo(), read(), BoxLayoutData< FArrayBox >::setVector(), write(), WriteMultiData< T >::writeData(), and LayoutData< FArrayBox >::~LayoutData().
timedDataIterator()
template<class T > TimedDataIterator LayoutData< T >::timedDataIterator () const inline
operator[]() [1/4]
template<class T > const T & LayoutData< T >::operator[] (const DataIndex & a_index) const inline
const accessor function
Referenced by LevelData< FArrayBox >::degenerateLocalOnly().
operator[]() [2/4]
template<class T > const T & LayoutData< T >::operator[] (const DataIterator & a_iterator) const inline
const accessor function
Returns member for which DataIterator is currently indexed to. Equivalent to layout[a_iterator()]
operator[]() [3/4]
template<class T > T & LayoutData< T >::operator[] (const DataIndex & a_index) inline
non-const accessor function
operator[]() [4/4]
template<class T > T & LayoutData< T >::operator[] (const DataIterator & a_iterator) inline
non-const accessor function
box() [1/2]
template<class T > Box LayoutData< T >::box (const DataIndex & a_index) const inline
Referenced by BoxLayoutData< FArrayBox >::allocateGhostVector(), BoxLayoutData< FArrayBox >::apply(), LevelData< FArrayBox >::copyTo(), LevelData< FArrayBox >::define(), LevelData< FArrayBox >::localCopyTo(), read(), BoxLayoutData< FArrayBox >::setVector(), write(), and WriteMultiData< T >::writeData().
box() [2/2]
template<class T > Box LayoutData< T >::box (const DataIterator & a_iterator) const inline
boxLayout()
template<class T> const BoxLayout& LayoutData< T >::boxLayout () const inline
Referenced by LevelData< FArrayBox >::copyTo(), BoxLayoutData< FArrayBox >::define(), getOffsets(), read(), write(), and WriteMultiData< T >::writeData().
operator=()
template<class T> LayoutData<T>& LayoutData< T >::operator= (const LayoutData< T > & a_rhs) private
allocate()
template<class T > void LayoutData< T >::allocate () inline private
Referenced by LayoutData< FArrayBox >::define(), and LayoutData< FArrayBox >::LayoutData().
Friends And Related Function Documentation
BoxLayout
template<class T> friend class BoxLayout friend
Member Data Documentation
m_boxLayout
template<class T> BoxLayout LayoutData< T >::m_boxLayout protected
Referenced by BoxLayoutData< FArrayBox >::addTo(), LayoutData< FArrayBox >::boxLayout(), BoxLayoutData< FArrayBox >::BoxLayoutData(), LevelData< FArrayBox >::define(), LayoutData< FArrayBox >::define(), BoxLayoutData< FArrayBox >::define(), BoxLayoutData< FArrayBox >::generalCopyTo(), and LevelData< FArrayBox >::LevelData().
m_vector
template<class T> std::vector<T*> LayoutData< T >::m_vector protected
Referenced by LayoutData< FArrayBox >::allocate(), BoxLayoutData< FArrayBox >::allocateGhostVector(), LevelData< FArrayBox >::apply(), BoxLayoutData< FArrayBox >::apply(), BoxLayoutData< FArrayBox >::clear(), LevelData< FArrayBox >::define(), BoxLayoutData< FArrayBox >::setVector(), and LayoutData< FArrayBox >::~LayoutData().
m_callDelete
template<class T> bool LayoutData< T >::m_callDelete protected
Referenced by LayoutData< FArrayBox >::allocate(), BoxLayoutData< FArrayBox >::allocateGhostVector(), BoxLayoutData< FArrayBox >::clear(), LayoutData< FArrayBox >::LayoutData(), and LayoutData< FArrayBox >::~LayoutData().
The documentation for this class was generated from the following files:
Chombo_LayoutData.H
Chombo_LayoutDataI.H