Chombo_4: BaseExactSolution Class Reference
BaseExactSolution Class Reference abstract
#include <Proto_EBExactSolutions.H>
Public Types
typedef Proto::IndexTM< int, DIM > IvDIM
Public Member Functions
virtual ~BaseExactSolution ()
BaseExactSolution ()
template<int order>
Real operator() (const EBGraph &a_graph, const Real &a_dx, const Proto::HostIrregData< CELL, Proto::IndexedMoments< DIM, order >, 1 > &a_voldat, const EBIndex< CELL > &a_vof, const IvDIM &a_baseDeriv=IvDIM::Zero) const
virtual Real getDerivative (IvDIM a_power, RealVect a_loc) const =0
Member Typedef Documentation
IvDIM
typedef Proto::IndexTM<int, DIM> BaseExactSolution::IvDIM
Constructor & Destructor Documentation
~BaseExactSolution()
virtual BaseExactSolution::~BaseExactSolution () inline virtual
BaseExactSolution()
BaseExactSolution::BaseExactSolution () inline
Member Function Documentation
operator()()
template<int order> Real BaseExactSolution::operator() (const EBGraph & a_graph, const Real & a_dx, const Proto::HostIrregData< CELL, Proto::IndexedMoments< DIM, order >, 1 > & a_voldat, const EBIndex< CELL > & a_vof, const IvDIM & a_baseDeriv = IvDIM::Zero) const inline
References Proto::IndexTM< T, N >::factorial(), getDerivative(), Proto::EBGraph::isCovered(), Proto::EBGraph::isRegular(), Proto::EBIndex< cent >::m_pt, Proto::MomentIterator< D, P >::ok(), Proto::power(), Proto::IndexedMoments< Dim, P >::setToRegular(), Proto::IndexTM< T, N >::sum(), and Proto::IndexTM< T, N >::Zero.
getDerivative()
virtual Real BaseExactSolution::getDerivative (IvDIM a_power, RealVect a_loc) const pure virtual
Implemented in StokesLiquidDrop, CosSurf, ExponentialProduct, RotatingSphere, PseudoGaussian, GaussianBlob, OneDimSinProduct, OneDimCosProduct, PolynomialEF, MonomialEF, SineSphereEF, UniformSolution, ZeroSolution, and FunctionSumSolution.
Referenced by PseudoGaussian::getPhiPoint(), RotatingSphere::getPhiPoint(), StokesLiquidDrop::getPhiPoint(), and operator()().
The documentation for this class was generated from the following file:
Proto_EBExactSolutions.H