Chombo_4: DataFactory< T > Class Template Reference
DataFactory< T > Class Template Reference abstract
Factory object to data members of a BoxLayoutData container.
#include <Chombo_BoxLayoutData.H>
Public Member Functions
virtual ~DataFactory ()
virtual T * create (const Box &box, int ncomps, const DataIndex &a_datInd) const =0
factory function. creates a new 'T' object
virtual bool callDelete () const
virtual bool graphConstructor () const
Detailed Description
template<class T>
class DataFactory< T >
Factory object to data members of a BoxLayoutData container.
Constructor & Destructor Documentation
~DataFactory()
template<class T> virtual DataFactory< T >::~DataFactory () inline virtual
Member Function Documentation
create()
template<class T> virtual T* DataFactory< T >::create (const Box & box, int ncomps, const DataIndex & a_datInd) const pure virtual
factory function. creates a new 'T' object
creates a new 'T' object and returns a pointer to it.
Implemented in DefaultDataFactory< T >, DefaultDataFactory< T >, FaceFabDataFactory, GraphConstructorFactory< DataHolder >, FABAliasFlBxDataFactory, AliasDataFactory< T >, NullConstructorDataFactory< DataHolder >, FABAliasDataFactory, DefaultDataFactory< T >, ScalarAliasFactory< srcComp, dstComp >, DeviToHostAliasFactory< cent, data_t, ncomp >, and DefaultBoxDataFactory< NUMCOMPS >.
Referenced by BoxLayoutData< FArrayBox >::allocateGhostVector(), BoxLayoutData< FArrayBox >::generalCopyTo(), BoxLayoutData< FArrayBox >::unpackReceivesToMe_append(), AliasDataFactory< T >::~AliasDataFactory(), DataFactory< EBFluxData< Real, dstComp > >::~DataFactory(), FABAliasDataFactory::~FABAliasDataFactory(), FABAliasFlBxDataFactory::~FABAliasFlBxDataFactory(), and FaceFabDataFactory::~FaceFabDataFactory().
callDelete()
template<class T> virtual bool DataFactory< T >::callDelete () const inline virtual
Reimplemented in GraphConstructorFactory< DataHolder >, NullConstructorDataFactory< DataHolder >, and DeviToHostAliasFactory< cent, data_t, ncomp >.
Referenced by BoxLayoutData< FArrayBox >::allocateGhostVector().
graphConstructor()
template<class T> virtual bool DataFactory< T >::graphConstructor () const inline virtual
Reimplemented in GraphConstructorFactory< DataHolder >, and DeviToHostAliasFactory< cent, data_t, ncomp >.
The documentation for this class was generated from the following file:
Chombo_BoxLayoutData.H