Chombo_4: EBCM::EBCM_Volu< order > Class Template Reference
EBCM::EBCM_Volu< order > Class Template Reference
#include <Chombo_EBCM_Graph.H>
Public Types
typedef Chombo4::GeometryService< order > ch_geoserv
typedef Proto::IndexedMoments< DIM-1, order > IndMomSDMinOne
typedef Proto::IndexedMoments< DIM, order > IndMomSpaceDim
typedef EBCM::EBCM_Face< XFACE, order > ebcm_xface
typedef EBCM::EBCM_Face< YFACE, order > ebcm_yface
typedef EBCM::EBCM_Face< ZFACE, order > ebcm_zface
typedef EBCM::IrregFace< order > ebcm_iface
Public Member Functions
void energize (char *a_outbuf, size_t a_expected_size) const
The usual set of functions involved in serialization.
void linearIn (const char *a_inbuf, size_t a_expected_size)
define this object via bytestream
size_t charsize () const
Get the bytestream size required to hold this object.
void linearOut (char *a_outbuf, size_t a_expected_size) const
older name for energize (bit more gravitas, I guess)
void print () const
bool operator< (const EBCM_Volu< order > &a_input) const
template<CENTERING cent>
void fillFaceData (vector< EBCM_Face< cent, order > > &a_facedata, const vector< EBIndex< cent > > &a_ebfaces, const HostIrregData< cent, IndMomSDMinOne, 1 > &a_facedat)
void defineAsIrregular (const pr_vof &a_vof, const shared_ptr< ch_geoserv > &a_geoserv, const ch_box &a_domain, const ch_datind &a_dit, const double &a_dx)
void defineDerivedMeasures (double a_dx)
void defineAsRegular (pr_pt a_pt, double a_dx)
Static Public Member Functions
template<CENTERING cent>
static bool foundMatch (const vector< EBCM_Face< cent, order > > &a_vecOne, const vector< EBCM_Face< cent, order > > &a_vecTwo)
static bool connected (const EBCM_Volu< order > &a_volOne, const EBCM_Volu< order > &a_volTwo)
Public Attributes
bool m_regular
RealVect m_centroid
double m_kappa
IndexedMoments< DIM, order > m_volmom
Point m_pt
double m_dx
vector< ebcm_xface > m_xfaces
vector< ebcm_yface > m_yfaces
vector< ebcm_zface > m_zfaces
vector< ebcm_iface > m_ifaces
vector< Point > m_cells
Member Typedef Documentation
ch_geoserv
template<int order> typedef Chombo4::GeometryService<order> EBCM::EBCM_Volu< order >::ch_geoserv
Data: this is another one of those classes with its data just hanging out in the breeze
IndMomSDMinOne
template<int order> typedef Proto::IndexedMoments<DIM-1, order> EBCM::EBCM_Volu< order >::IndMomSDMinOne
IndMomSpaceDim
template<int order> typedef Proto::IndexedMoments<DIM , order> EBCM::EBCM_Volu< order >::IndMomSpaceDim
ebcm_xface
template<int order> typedef EBCM::EBCM_Face<XFACE, order> EBCM::EBCM_Volu< order >::ebcm_xface
ebcm_yface
template<int order> typedef EBCM::EBCM_Face<YFACE, order> EBCM::EBCM_Volu< order >::ebcm_yface
ebcm_zface
template<int order> typedef EBCM::EBCM_Face<ZFACE, order> EBCM::EBCM_Volu< order >::ebcm_zface
ebcm_iface
template<int order> typedef EBCM::IrregFace< order> EBCM::EBCM_Volu< order >::ebcm_iface
Member Function Documentation
energize()
template<int order> void EBCM::EBCM_Volu< order >::energize (char * a_outbuf, size_t a_expected_size) const inline
The usual set of functions involved in serialization.
fill a bytestream with the necessary data to reproduce this class
flag for m_regular
m_dx
References EBCM::vector_charsize(), and EBCM::vector_energize().
linearIn()
template<int order> void EBCM::EBCM_Volu< order >::linearIn (const char * a_inbuf, size_t a_expected_size) inline
define this object via bytestream
flag for m_regular
m_dx
References EBCM::vector_linearIn().
charsize()
template<int order> size_t EBCM::EBCM_Volu< order >::charsize () const inline
Get the bytestream size required to hold this object.
m_dx
References EBCM::vector_charsize().
linearOut()
template<int order> void EBCM::EBCM_Volu< order >::linearOut (char * a_outbuf, size_t a_expected_size) const inline
older name for energize (bit more gravitas, I guess)
References EBCM::EBCM_Face< cent, order >::energize().
print()
template<int order> void EBCM::EBCM_Volu< order >::print () const inline
References pout().
operator<()
template<int order> bool EBCM::EBCM_Volu< order >::operator< (const EBCM_Volu< order > & a_input) const inline
foundMatch()
template<int order> template<CENTERING cent> static bool EBCM::EBCM_Volu< order >::foundMatch (const vector< EBCM_Face< cent, order > > & a_vecOne, const vector< EBCM_Face< cent, order > > & a_vecTwo) inline static
connected()
template<int order> static bool EBCM::EBCM_Volu< order >::connected (const EBCM_Volu< order > & a_volOne, const EBCM_Volu< order > & a_volTwo) inline static
References EBCM::EBCM_Volu< order >::m_xfaces, EBCM::EBCM_Volu< order >::m_yfaces, and EBCM::EBCM_Volu< order >::m_zfaces.
Referenced by EBCM::EBCM_Graph< order >::volumesConnected().
fillFaceData()
template<int order> template<CENTERING cent> void EBCM::EBCM_Volu< order >::fillFaceData (vector< EBCM_Face< cent, order > > & a_facedata, const vector< EBIndex< cent > > & a_ebfaces, const HostIrregData< cent, IndMomSDMinOne, 1 > & a_facedat) inline
defineAsIrregular()
template<int order> void EBCM::EBCM_Volu< order >::defineAsIrregular (const pr_vof & a_vof, const shared_ptr< ch_geoserv > & a_geoserv, const ch_box & a_domain, const ch_datind & a_dit, const double & a_dx) inline
References Proto::EBIndex< cent >::getCutFace(), and Proto::EBIndex< cent >::m_pt.
Referenced by EBCM::EBCM_Graph< order >::createEBCM_Volume().
defineDerivedMeasures()
template<int order> void EBCM::EBCM_Volu< order >::defineDerivedMeasures (double a_dx) inline
Referenced by EBCM::EBCM_Graph< order >::mergeTwoVolumesIntoThird().
defineAsRegular()
template<int order> void EBCM::EBCM_Volu< order >::defineAsRegular (pr_pt a_pt, double a_dx) inline
Referenced by EBCM::EBCM_Graph< order >::createEBCM_Volume(), EBCM::EBCM_Graph< order >::getVolumeCoveringPoint(), and EBCM::EBCM_Graph< order >::mergeSmallVolumesWithNeighbors().
Member Data Documentation
m_regular
template<int order> bool EBCM::EBCM_Volu< order >::m_regular
Referenced by EBCM::EBCM_Graph< order >::mergeTwoVolumesIntoThird().
m_centroid
template<int order> RealVect EBCM::EBCM_Volu< order >::m_centroid
m_kappa
template<int order> double EBCM::EBCM_Volu< order >::m_kappa
Referenced by EBCM::EBCM_Graph< order >::createEBCM_Volume(), and EBCM::EBCM_Graph< order >::makeTheBlobs().
m_volmom
template<int order> IndexedMoments<DIM, order> EBCM::EBCM_Volu< order >::m_volmom
Referenced by EBCM::EBCM_Graph< order >::shiftAndMergeVolumeData().
m_pt
template<int order> Point EBCM::EBCM_Volu< order >::m_pt
Referenced by EBCM::faceSign(), EBCM::EBCM_Graph< order >::getRegularNeighborPoint(), EBCM::EBCM_Graph< order >::getShifts(), and EBCM::EBCM_Graph< order >::mergeTwoVolumesIntoThird().
m_dx
template<int order> double EBCM::EBCM_Volu< order >::m_dx
Referenced by EBCM::EBCM_Graph< order >::getShifts().
m_xfaces
template<int order> vector<ebcm_xface> EBCM::EBCM_Volu< order >::m_xfaces
Referenced by EBCM::EBCM_Volu< order >::connected(), EBCM::EBCM_Graph< order >::consolidateFacesAllDirections(), EBCM::PETSc_Framework< ebcm_order >::HelmholtzOp::getLocalStencil(), and EBCM::Algorithm_Framework< ebcm_order >::getWorstConditionNumberInfo().
m_yfaces
template<int order> vector<ebcm_yface> EBCM::EBCM_Volu< order >::m_yfaces
Referenced by EBCM::EBCM_Volu< order >::connected(), EBCM::EBCM_Graph< order >::consolidateFacesAllDirections(), and EBCM::Algorithm_Framework< ebcm_order >::getWorstConditionNumberInfo().
m_zfaces
template<int order> vector<ebcm_zface> EBCM::EBCM_Volu< order >::m_zfaces
Referenced by EBCM::EBCM_Volu< order >::connected(), EBCM::EBCM_Graph< order >::consolidateFacesAllDirections(), and EBCM::Algorithm_Framework< ebcm_order >::getWorstConditionNumberInfo().
m_ifaces
template<int order> vector<ebcm_iface> EBCM::EBCM_Volu< order >::m_ifaces
Referenced by EBCM::Algorithm_Framework< ebcm_order >::getWorstConditionNumberInfo(), and EBCM::EBCM_Graph< order >::shiftAndMergeIrregData().
m_cells
template<int order> vector<Point> EBCM::EBCM_Volu< order >::m_cells
Referenced by EBCM::EBCM_Graph< order >::copy(), EBCM::EBCM_Graph< order >::mergeSmallVolumesWithNeighbors(), and EBCM::EBCM_Graph< order >::mergeTwoVolumesIntoThird().
The documentation for this class was generated from the following file:
Chombo_EBCM_Graph.H