Chombo_4: Proto::EBDictionary< order, data_t, srcCenter, dstCenter > Class Template Reference
Proto::EBDictionary< order, data_t, srcCenter, dstCenter > Class Template Reference
class that creates and stores EBStencils
#include <Proto_EBDictionary.H>
Classes
struct stencilKey
Public Types
typedef EBStencil< order, data_t, srcCenter, dstCenter > ebstencil_t
typedef IndexedMoments< DIM, order > IndMomDIM
typedef IndexedMoments< DIM-1, order > IndMomSDMinOne
typedef MomentIterator< DIM, order > MomItDIM
typedef MomentIterator< DIM-1, order > MomItSDMinOne
typedef IrregNode< order > inode
typedef HostIrregData< CELL, IndMomDIM, 1 > VoluData
typedef HostIrregData< BOUNDARY, IndMomDIM, 1 > EBFaData
typedef HostIrregData< XFACE, IndMomSDMinOne, 1 > XFacData
typedef HostIrregData< YFACE, IndMomSDMinOne, 1 > YFacData
typedef HostIrregData< ZFACE, IndMomSDMinOne, 1 > ZFacData
Public Member Functions
EBDictionary (const shared_ptr< GeometryService< order > > &a_geoserv, const DisjointBoxLayout &a_grids, Point a_srcGhost, Point a_dstGhost, data_t a_dx, bool a_periodiconly)
void registerStencil (string a_stencilName, string a_domainBCName, string a_ebbcName)
shared_ptr< ebstencil_t > getEBStencil (const string &a_stencilName, const string &a_ebbcName, const int &a_boxid)
int numLevels () const
void close ()
after this is done, you cannot register any more stencils. This will delete the moment information.
Protected Attributes
vector< map< stencilKey, shared_ptr< ebstencil_t > > > m_registeredStencils
one per box in the grid
shared_ptr< GeometryService< order > > m_geoserv
Point m_srcGhost
Point m_dstGhost
DisjointBoxLayout m_grids
bool m_isClosed
data_t m_dx
bool m_periodiconly
Private Member Functions
EBDictionary ()
EBDictionary (const EBDictionary< order, data_t, srcCenter, dstCenter > &a_inp)
void operator= (const EBDictionary< order, data_t, srcCenter, dstCenter > &a_inp)
Detailed Description
template<int order, typename data_t, CENTERING srcCenter, CENTERING dstCenter>
class Proto::EBDictionary< order, data_t, srcCenter, dstCenter >
class that creates and stores EBStencils
class that creates and stores EBStencils You register a particular stencil at a particular refinement and after that you can always retrieve it. This is a simple implementation. The Chombo version is better.
Member Typedef Documentation
ebstencil_t
template<int order, typename data_t, CENTERING srcCenter, CENTERING dstCenter> typedef EBStencil<order, data_t, srcCenter, dstCenter> Proto::EBDictionary< order, data_t, srcCenter, dstCenter >::ebstencil_t
IndMomDIM
template<int order, typename data_t, CENTERING srcCenter, CENTERING dstCenter> typedef IndexedMoments<DIM , order> Proto::EBDictionary< order, data_t, srcCenter, dstCenter >::IndMomDIM
IndMomSDMinOne
template<int order, typename data_t, CENTERING srcCenter, CENTERING dstCenter> typedef IndexedMoments<DIM-1, order> Proto::EBDictionary< order, data_t, srcCenter, dstCenter >::IndMomSDMinOne
MomItDIM
template<int order, typename data_t, CENTERING srcCenter, CENTERING dstCenter> typedef MomentIterator<DIM , order> Proto::EBDictionary< order, data_t, srcCenter, dstCenter >::MomItDIM
MomItSDMinOne
template<int order, typename data_t, CENTERING srcCenter, CENTERING dstCenter> typedef MomentIterator<DIM-1, order> Proto::EBDictionary< order, data_t, srcCenter, dstCenter >::MomItSDMinOne
inode
template<int order, typename data_t, CENTERING srcCenter, CENTERING dstCenter> typedef IrregNode<order> Proto::EBDictionary< order, data_t, srcCenter, dstCenter >::inode
VoluData
template<int order, typename data_t, CENTERING srcCenter, CENTERING dstCenter> typedef HostIrregData<CELL , IndMomDIM , 1> Proto::EBDictionary< order, data_t, srcCenter, dstCenter >::VoluData
EBFaData
template<int order, typename data_t, CENTERING srcCenter, CENTERING dstCenter> typedef HostIrregData<BOUNDARY, IndMomDIM , 1> Proto::EBDictionary< order, data_t, srcCenter, dstCenter >::EBFaData
XFacData
template<int order, typename data_t, CENTERING srcCenter, CENTERING dstCenter> typedef HostIrregData<XFACE, IndMomSDMinOne, 1> Proto::EBDictionary< order, data_t, srcCenter, dstCenter >::XFacData
YFacData
template<int order, typename data_t, CENTERING srcCenter, CENTERING dstCenter> typedef HostIrregData<YFACE, IndMomSDMinOne, 1> Proto::EBDictionary< order, data_t, srcCenter, dstCenter >::YFacData
ZFacData
template<int order, typename data_t, CENTERING srcCenter, CENTERING dstCenter> typedef HostIrregData<ZFACE, IndMomSDMinOne, 1> Proto::EBDictionary< order, data_t, srcCenter, dstCenter >::ZFacData
Constructor & Destructor Documentation
EBDictionary() [1/3]
template<int order, typename data_t , CENTERING srcCenter, CENTERING dstCenter> EBDictionary< order, data_t, srcCenter, dstCenter >::EBDictionary (const shared_ptr< GeometryService< order > > & a_geoserv, const DisjointBoxLayout & a_grids, Point a_srcGhost, Point a_dstGhost, data_t a_dx, bool a_periodiconly)
geoserv is the holder for all momeent information \ a_grids is the layout over which that data is held. \ a_ghost is the number of ghost cells your data will hold. It must be at least as big as the stencil span in each direction..
a_ghost is the number of ghost cells your data will hold. It must be at least as big as the stencil span in each direction..
References Proto::EBDictionary< order, data_t, srcCenter, dstCenter >::registerStencil().
EBDictionary() [2/3]
template<int order, typename data_t, CENTERING srcCenter, CENTERING dstCenter> Proto::EBDictionary< order, data_t, srcCenter, dstCenter >::EBDictionary () private
EBDictionary() [3/3]
template<int order, typename data_t, CENTERING srcCenter, CENTERING dstCenter> Proto::EBDictionary< order, data_t, srcCenter, dstCenter >::EBDictionary (const EBDictionary< order, data_t, srcCenter, dstCenter > & a_inp) private
Member Function Documentation
registerStencil()
template<int order, typename data_t , CENTERING srcCenter, CENTERING dstCenter> void EBDictionary< order, data_t, srcCenter, dstCenter >::registerStencil (string a_stencilName, string a_domainBCName, string a_ebbcName) inline
This is how you store a stencil. The string must match one of the appropriate centering in EBStencilArchive. stencilName is the name of the stencil \ domainBC name is the name of the domain boundary condition to be applied (this can be turned off) \ domainBC name is the name of the Cut cell boundary condition to be applied (this can be turned off)
References Proto::EBDictionary< order, data_t, srcCenter, dstCenter >::getEBStencil(), Proto::EBDictionary< order, data_t, srcCenter, dstCenter >::stencilKey::m_ebbcName, and Proto::EBDictionary< order, data_t, srcCenter, dstCenter >::stencilKey::m_stencilName.
Referenced by Proto::EBDictionary< order, data_t, srcCenter, dstCenter >::EBDictionary().
getEBStencil()
template<int order, typename data_t , CENTERING srcCenter, CENTERING dstCenter> shared_ptr< EBStencil< order, data_t, srcCenter, dstCenter > > EBDictionary< order, data_t, srcCenter, dstCenter >::getEBStencil (const string & a_stencilName, const string & a_ebbcName, const int & a_boxid) inline
Retrieve the stencil for a particular box at a particular level of refinement. The input strings must match the register call
References Proto::EBDictionary< order, data_t, srcCenter, dstCenter >::stencilKey::m_ebbcName, and Proto::EBDictionary< order, data_t, srcCenter, dstCenter >::stencilKey::m_stencilName.
Referenced by Proto::EBDictionary< order, data_t, srcCenter, dstCenter >::registerStencil().
numLevels()
template<int order, typename data_t, CENTERING srcCenter, CENTERING dstCenter> int Proto::EBDictionary< order, data_t, srcCenter, dstCenter >::numLevels () const inline
References Proto::EBDictionary< order, data_t, srcCenter, dstCenter >::m_registeredStencils.
close()
template<int order, typename data_t, CENTERING srcCenter, CENTERING dstCenter> void Proto::EBDictionary< order, data_t, srcCenter, dstCenter >::close () inline
after this is done, you cannot register any more stencils. This will delete the moment information.
References Proto::EBDictionary< order, data_t, srcCenter, dstCenter >::m_geoserv.
operator=()
template<int order, typename data_t, CENTERING srcCenter, CENTERING dstCenter> void Proto::EBDictionary< order, data_t, srcCenter, dstCenter >::operator= (const EBDictionary< order, data_t, srcCenter, dstCenter > & a_inp) private
Member Data Documentation
m_registeredStencils
template<int order, typename data_t, CENTERING srcCenter, CENTERING dstCenter> vector< map< stencilKey, shared_ptr< ebstencil_t> > > Proto::EBDictionary< order, data_t, srcCenter, dstCenter >::m_registeredStencils protected
one per box in the grid
Referenced by Proto::EBDictionary< order, data_t, srcCenter, dstCenter >::numLevels().
m_geoserv
template<int order, typename data_t, CENTERING srcCenter, CENTERING dstCenter> shared_ptr<GeometryService<order> > Proto::EBDictionary< order, data_t, srcCenter, dstCenter >::m_geoserv protected
Referenced by Proto::EBDictionary< order, data_t, srcCenter, dstCenter >::close().
m_srcGhost
template<int order, typename data_t, CENTERING srcCenter, CENTERING dstCenter> Point Proto::EBDictionary< order, data_t, srcCenter, dstCenter >::m_srcGhost protected
m_dstGhost
template<int order, typename data_t, CENTERING srcCenter, CENTERING dstCenter> Point Proto::EBDictionary< order, data_t, srcCenter, dstCenter >::m_dstGhost protected
m_grids
template<int order, typename data_t, CENTERING srcCenter, CENTERING dstCenter> DisjointBoxLayout Proto::EBDictionary< order, data_t, srcCenter, dstCenter >::m_grids protected
m_isClosed
template<int order, typename data_t, CENTERING srcCenter, CENTERING dstCenter> bool Proto::EBDictionary< order, data_t, srcCenter, dstCenter >::m_isClosed protected
m_dx
template<int order, typename data_t, CENTERING srcCenter, CENTERING dstCenter> data_t Proto::EBDictionary< order, data_t, srcCenter, dstCenter >::m_dx protected
m_periodiconly
template<int order, typename data_t, CENTERING srcCenter, CENTERING dstCenter> bool Proto::EBDictionary< order, data_t, srcCenter, dstCenter >::m_periodiconly protected
The documentation for this class was generated from the following files:
Proto_EBDictionary.H
Proto_EBDictionaryImplem.H