Chombo_4: Proto::CellNode Class Reference
Proto::CellNode Class Reference
#include <Proto_EBGraph.H>
Classes
struct IrrGraphNode
Public Member Functions
template<CENTERING cent>
void getFaceInfo (vector< EBIndex< cent > > &a_faces, const int &a_dir, const EBIndex< CELL > &a_vof, const Side::LoHiSide &a_sd, const Box &a_domain) const
template<CENTERING cent>
void setFaceStuff (EBIndex< cent > &a_face, const int &a_inputIndex, const int &a_otherIndex, const Point &a_inputIV, const Point &a_otherIV, const Side::LoHiSide &a_sd, const Box &a_domain) const
CellNode ()
~CellNode ()
bool isCovered () const
bool isRegular () const
bool isIrregular () const
void defineAsRegular ()
void defineAsFullIrregular (const Point &a_pt, const Box &a_domain)
void defineAsIrregular ()
void defineAsCovered ()
vector< EBIndex< XFACE > > getXFaces (const EBIndex< CELL > &a_vof, const Side::LoHiSide &a_sd, const Box &a_domain) const
vector< EBIndex< YFACE > > getYFaces (const EBIndex< CELL > &a_vof, const Side::LoHiSide &a_sd, const Box &a_domain) const
vector< EBIndex< CELL > > getVoFs (const Point &a_iv) const
vector< EBIndex< BOUNDARY > > getCutFaces (const Point &a_iv) const
return vofs labelled as irregular (only places where an EB can happen)
CellNode (const CellNode &a_ebin)
CellNode & operator= (const CellNode &a_ebin)
size_t linearSize () const
for serialization (chombo uses this in parallel code)
void linearIn (const char *a_buf)
for serialization (chombo uses this in parallel code)
void linearOut (char *a_buf) const
for serialization (chombo uses this in parallel code)
Static Public Member Functions
static bool constantMemorySize ()
for serialization (chombo uses this in parallel code)
Public Attributes
vector< IrrGraphNode > * m_cellList
Detailed Description
This is a list showing the connectivity of a given cell. This has the special property of also being able to set itself to regular or covered by setting the current nodeimplem pointer to 1 or 0.
Constructor & Destructor Documentation
CellNode() [1/2]
Proto::CellNode::CellNode () inline
~CellNode()
Proto::CellNode::~CellNode () inline
CellNode() [2/2]
Proto::CellNode::CellNode (const CellNode & a_ebin) inline
Member Function Documentation
getFaceInfo()
template<CENTERING cent> void Proto::CellNode::getFaceInfo (vector< EBIndex< cent > > & a_faces, const int & a_dir, const EBIndex< CELL > & a_vof, const Side::LoHiSide & a_sd, const Box & a_domain) const inline
References Box::contains(), Proto::ebp_index(), getXFaces(), Proto::EBGraph::isCovered(), Proto::EBGraph::isRegular(), Proto::CellNode::IrrGraphNode::m_arc, Proto::EBIndex< cent >::m_pt, and Proto::EBIndex< cent >::m_vofIDMe.
Referenced by setFaceStuff().
setFaceStuff()
template<CENTERING cent> void Proto::CellNode::setFaceStuff (EBIndex< cent > & a_face, const int & a_inputIndex, const int & a_otherIndex, const Point & a_inputIV, const Point & a_otherIV, const Side::LoHiSide & a_sd, const Box & a_domain) const inline
References Box::contains(), getFaceInfo(), Proto::EBIndex< cent >::m_isBoundary, Proto::EBIndex< cent >::m_pt, Proto::EBIndex< cent >::m_vofIDLo, and Proto::EBIndex< cent >::m_vofIDMe.
Referenced by Proto::EBGraph::getAdjacentFace().
isCovered()
bool Proto::CellNode::isCovered () const inline
Return true if the node is covered (m_cellList==0).
Referenced by Proto::EBGraph::defineFromPrimitives(), Proto::EBGraph::isCovered(), and operator=().
isRegular()
bool Proto::CellNode::isRegular () const inline
Return true if the node is regular.
Referenced by Proto::EBGraph::defineFromPrimitives(), Proto::EBGraph::isRegular(), and operator=().
isIrregular()
bool Proto::CellNode::isIrregular () const inline
Return true if the node is neither regular or covered.
Referenced by Proto::EBGraph::getCutFaces(), and Proto::EBGraph::isIrregular().
defineAsRegular()
void Proto::CellNode::defineAsRegular () inline
Set Node to regular. If previously set to irregular, deletes their memory.
Referenced by Proto::EBGraph::copy().
defineAsFullIrregular()
void Proto::CellNode::defineAsFullIrregular (const Point & a_pt, const Box & a_domain) inline
References Box::contains(), Proto::EBIndex< cent >::defineAsRegular(), Proto::ebp_index(), and Proto::EBIndex< cent >::getRefinedRegular().
defineAsIrregular()
void Proto::CellNode::defineAsIrregular () inline
Referenced by Proto::EBGraph::coarsenVoFs().
defineAsCovered()
void Proto::CellNode::defineAsCovered () inline
Set Node to covered. If previously set to irregular, deletes their memory.
Referenced by Proto::EBGraph::copy().
getXFaces()
vector< EBIndex< XFACE > > Proto::CellNode::getXFaces (const EBIndex< CELL > & a_vof, const Side::LoHiSide & a_sd, const Box & a_domain) const inline
Get the faces in the direction and side for the vof in the list. if the vof's cell index is not found in the list, abort. Use the input vof's grid index for a the grid index of the list.
References Box::contains(), getYFaces(), and Proto::EBIndex< cent >::m_pt.
Referenced by getFaceInfo(), and Proto::EBGraph::getXFaces().
getYFaces()
vector< EBIndex< YFACE > > Proto::CellNode::getYFaces (const EBIndex< CELL > & a_vof, const Side::LoHiSide & a_sd, const Box & a_domain) const inline
References Box::contains(), getVoFs(), and Proto::EBIndex< cent >::m_pt.
Referenced by getXFaces(), and Proto::EBGraph::getYFaces().
getVoFs()
vector< EBIndex< CELL > > Proto::CellNode::getVoFs (const Point & a_iv) const inline
Return all the vofs in the list, using the input intvect for the gridIndex
References getCutFaces(), Proto::EBGraph::isCovered(), and Proto::EBGraph::isRegular().
Referenced by Proto::EBGraph::getVoFs(), and getYFaces().
getCutFaces()
vector< EBIndex< BOUNDARY > > Proto::CellNode::getCutFaces (const Point & a_iv) const inline
return vofs labelled as irregular (only places where an EB can happen)
References Proto::EBGraph::coarsenVoFs(), and Proto::EBGraph::isIrregular().
Referenced by Proto::EBGraph::getCutFaces(), and getVoFs().
operator=()
CellNode& Proto::CellNode::operator= (const CellNode & a_ebin) inline
References Proto::EBIndex< cent >::defineAsRegular(), isCovered(), isRegular(), and m_cellList.
constantMemorySize()
static bool Proto::CellNode::constantMemorySize () inline static
for serialization (chombo uses this in parallel code)
linearSize()
size_t Proto::CellNode::linearSize (void) const inline
for serialization (chombo uses this in parallel code)
linearIn()
void Proto::CellNode::linearIn (const char * a_buf) inline
for serialization (chombo uses this in parallel code)
References Proto::EBIndex< cent >::defineAsRegular().
linearOut()
void Proto::CellNode::linearOut (char * a_buf) const inline
for serialization (chombo uses this in parallel code)
Member Data Documentation
m_cellList
vector<IrrGraphNode>* Proto::CellNode::m_cellList
The connectivity data at this point. If m_cellList == 0, node is covered. If m_cellList == 1, node is regular and parent is single-valued. otherwise, it is a real list (node may still be regular).
Referenced by Proto::EBGraph::coarsen(), Proto::EBGraph::coarsenVoFs(), operator=(), and Proto::EBGraph::refine().
The documentation for this class was generated from the following files:
Proto_EBGraph.H
Proto_EBGraphImplem.H