Chombo_4: Proto::EBStencilArchive< CELL, fcent, order, double > Class Template Reference
Proto::EBStencilArchive< CELL, fcent, order, double > Class Template Reference
#include <Proto_EBStencilArchive.H>
Public Types
typedef IndexedMoments< DIM, order > IndMomDIM
typedef IndexedMoments< DIM-1, order > IndMomSDMinOne
typedef MomentIterator< DIM, order > MomItDIM
typedef MomentIterator< DIM-1, order > MomItSDMinOne
typedef HostIrregData< CELL, IndMomDIM, 1 > VoluData
typedef HostIrregData< BOUNDARY, IndMomDIM, 1 > EBFaData
typedef HostIrregData< XFACE, IndMomSDMinOne, 1 > XFacData
typedef HostIrregData< YFACE, IndMomSDMinOne, 1 > YFacData
typedef HostIrregData< ZFACE, IndMomSDMinOne, 1 > ZFacData
Public Member Functions
EBStencilArchive ()
~EBStencilArchive ()
Static Public Member Functions
static bool getStencil (vector< EBIndex< fcent > > &a_dstVoFs, vector< LocalStencil< CELL, double > > &a_stencil, Stencil< double > &a_regStencil, vector< Stencil< double > > a_regStencilBCS[2 *DIM], vector< Box > a_BCApplyBoxes[2 *DIM], Box &a_regApplyBox, bool &a_bcOnly, bool &a_irregOnly, string a_stencilName, string a_domainBCName[2 *DIM], string a_ebbcName, const Box &a_srcValid, const Box &a_dstValid, const Box &a_srcDomain, const Box &a_dstDomain, const Point &a_srcGhost, const Point &a_dstGhost, const EBGraph &a_srcGraph, const EBGraph &a_dstGraph, const VoluData &a_voludata, const EBFaData &a_ebfadata, const XFacData &a_xfacdata, const YFacData &a_yfacdata, const ZFacData &a_zfacdata, double a_dx, bool a_periodiconly, Point a_dstGrown)
returns true if there are domain boundary conditions
static bool getCellToFaceAveStencil (vector< EBIndex< fcent > > &a_dstVoFs, vector< LocalStencil< CELL, double > > &a_stencil, Stencil< double > &a_regStencilInterior, vector< Stencil< double > > a_regStencilBCS[2 *DIM], vector< Box > a_BCApplyBoxes[2 *DIM], Box &a_regApplyBox, string a_domainBCName[2 *DIM], const Box &a_srcValid, const Box &a_srcDomain, const Point &a_srcGhost, const Point &a_dstGhost, const EBGraph &a_dstGraph, double a_dx, Point a_dstGrown)
for averaging cell centered stuff to face centers
static bool getCellToFaceStencil (vector< EBIndex< fcent > > &a_dstFaces, vector< LocalStencil< CELL, double > > &a_stencil, Stencil< double > &a_regStencil, Box &a_regApplyBox, const Box &a_validBox, const Box &a_srcDomain, const Point &a_srcGhost, const Point &a_dstGhost, const EBGraph &a_graph, double a_dx, Point a_dstGrown, Side::LoHiSide a_side)
static bool getMACGradientStencil (vector< EBIndex< fcent > > &a_dstFaces, vector< LocalStencil< CELL, double > > &a_stencil, Stencil< double > &a_regStencil, vector< Stencil< double > > a_regStencilBCS[2 *DIM], vector< Box > a_BCApplyBoxes[2 *DIM], Box &a_regApplyBox, const Box &a_validBox, const Box &a_srcDomain, const Point &a_srcGhost, const Point &a_dstGhost, const EBGraph &a_graph, double a_dx, Point a_dstGrown)
Detailed Description
template<CENTERING fcent, int order>
class Proto::EBStencilArchive< CELL, fcent, order, double >
Stuff to go from cells to faces
Member Typedef Documentation
IndMomDIM
template<CENTERING fcent, int order> typedef IndexedMoments<DIM , order> Proto::EBStencilArchive< CELL, fcent, order, double >::IndMomDIM
IndMomSDMinOne
template<CENTERING fcent, int order> typedef IndexedMoments<DIM-1, order> Proto::EBStencilArchive< CELL, fcent, order, double >::IndMomSDMinOne
MomItDIM
template<CENTERING fcent, int order> typedef MomentIterator<DIM , order> Proto::EBStencilArchive< CELL, fcent, order, double >::MomItDIM
MomItSDMinOne
template<CENTERING fcent, int order> typedef MomentIterator<DIM-1, order> Proto::EBStencilArchive< CELL, fcent, order, double >::MomItSDMinOne
VoluData
template<CENTERING fcent, int order> typedef HostIrregData<CELL, IndMomDIM , 1> Proto::EBStencilArchive< CELL, fcent, order, double >::VoluData
EBFaData
template<CENTERING fcent, int order> typedef HostIrregData<BOUNDARY, IndMomDIM , 1> Proto::EBStencilArchive< CELL, fcent, order, double >::EBFaData
XFacData
template<CENTERING fcent, int order> typedef HostIrregData<XFACE, IndMomSDMinOne, 1> Proto::EBStencilArchive< CELL, fcent, order, double >::XFacData
YFacData
template<CENTERING fcent, int order> typedef HostIrregData<YFACE, IndMomSDMinOne, 1> Proto::EBStencilArchive< CELL, fcent, order, double >::YFacData
ZFacData
template<CENTERING fcent, int order> typedef HostIrregData<ZFACE, IndMomSDMinOne, 1> Proto::EBStencilArchive< CELL, fcent, order, double >::ZFacData
Constructor & Destructor Documentation
EBStencilArchive()
template<CENTERING fcent, int order> Proto::EBStencilArchive< CELL, fcent, order, double >::EBStencilArchive () inline
~EBStencilArchive()
template<CENTERING fcent, int order> Proto::EBStencilArchive< CELL, fcent, order, double >::~EBStencilArchive () inline
References Proto::EBStencilArchive< srcCenter, dstCenter, order, data_t >::getStencil().
Member Function Documentation
getStencil()
template<CENTERING fcent, int order> bool Proto::EBStencilArchive< CELL, fcent, order, double >::getStencil (vector< EBIndex< fcent > > & a_dstFaces, vector< LocalStencil< CELL, double > > & a_stencil, Stencil< double > & a_regStencil, vector< Stencil< double > > a_regStencilBCS[2 *DIM], vector< Box > a_BCApplyBoxes[2 *DIM], Box & a_regApplyBox, bool & a_bcOnly, bool & a_irregOnly, string a_stencilName, string a_domainBCName[2 *DIM], string a_ebbcName, const Box & a_srcValid, const Box & a_dstValid, const Box & a_srcDomain, const Box & a_dstDomain, const Point & a_srcGhost, const Point & a_dstGhost, const EBGraph & a_srcGraph, const EBGraph & a_dstGraph, const VoluData & a_voludata, const EBFaData & a_ebfadata, const XFacData & a_xfacdata, const YFacData & a_yfacdata, const ZFacData & a_zfacdata, double a_dx, bool a_periodiconly, Point a_dstGrown) inline static
returns true if there are domain boundary conditions
begin CELL to fcent this deep down in the bowels, everything is a template specialization returns whether there are domain boundary conditions
getCellToFaceAveStencil()
template<CENTERING fcent, int order> bool Proto::EBStencilArchive< CELL, fcent, order, double >::getCellToFaceAveStencil (vector< EBIndex< fcent > > & a_dstVoFs, vector< LocalStencil< CELL, double > > & a_stencil, Stencil< double > & a_regStencilInterior, vector< Stencil< double > > a_regStencilBCS[2 *DIM], vector< Box > a_BCApplyBoxes[2 *DIM], Box & a_regApplyBox, string a_domainBCName[2 *DIM], const Box & a_srcValid, const Box & a_srcDomain, const Point & a_srcGhost, const Point & a_dstGhost, const EBGraph & a_dstGraph, double a_dx, Point a_dstGrown) inline static
for averaging cell centered stuff to face centers
References Proto::EBGraph::getDomain(), Proto::SecondOrderStencil< order >::getDomainBCs(), Proto::EBIndex< cent >::getVoF(), and Box::grow().
getCellToFaceStencil()
template<CENTERING fcent, int order> bool Proto::EBStencilArchive< CELL, fcent, order, double >::getCellToFaceStencil (vector< EBIndex< fcent > > & a_dstFaces, vector< LocalStencil< CELL, double > > & a_stencil, Stencil< double > & a_regStencil, Box & a_regApplyBox, const Box & a_validBox, const Box & a_srcDomain, const Point & a_srcGhost, const Point & a_dstGhost, const EBGraph & a_graph, double a_dx, Point a_dstGrown, Side::LoHiSide a_side) inline static
References Proto::EBGraph::getDomain(), Proto::EBIndex< cent >::getVoF(), and Box::grow().
getMACGradientStencil()
template<CENTERING fcent, int order> bool Proto::EBStencilArchive< CELL, fcent, order, double >::getMACGradientStencil (vector< EBIndex< fcent > > & a_dstFaces, vector< LocalStencil< CELL, double > > & a_stencil, Stencil< double > & a_regStencil, vector< Stencil< double > > a_regStencilBCS[2 *DIM], vector< Box > a_BCApplyBoxes[2 *DIM], Box & a_regApplyBox, const Box & a_validBox, const Box & a_srcDomain, const Point & a_srcGhost, const Point & a_dstGhost, const EBGraph & a_graph, double a_dx, Point a_dstGrown) inline static
References Proto::EBGraph::getDomain(), Proto::SecondOrderStencil< order >::getDomainBCs(), Proto::EBStencilArchive< srcCenter, dstCenter, order, data_t >::getStencil(), Proto::EBIndex< cent >::getVoF(), and Box::grow().
The documentation for this class was generated from the following files:
Proto_EBStencilArchive.H
Proto_EBStencilArchiveImplem.H