Chombo_4: LevelGeometryService< order > Class Template Reference
LevelGeometryService< order > Class Template Reference
#include <Chombo_GeometryService.H>
Public Types
typedef Proto::IndexTM< int, 2 > Iv2
typedef IndexedMoments< DIM, order > IndMomDIM
typedef IndexedMoments< DIM-1, order > IndMomSDMinOne
typedef MomentIterator< DIM, order > MomItDIM
typedef MomentIterator< DIM-1, order > MomItSDMinOne
typedef IrregNode< order > inode
typedef HostIrregData< CELL, IndMomDIM, 1 > VoluData
typedef HostIrregData< BOUNDARY, IndMomDIM, 1 > EBFaData
typedef HostIrregData< XFACE, IndMomSDMinOne, 1 > XFacData
typedef HostIrregData< YFACE, IndMomSDMinOne, 1 > YFacData
typedef HostIrregData< ZFACE, IndMomSDMinOne, 1 > ZFacData
typedef HostIrregData< CELL, IndMomDIM, 1 > EBNormalData
typedef CH4_Data_Choreography::DistributedData< EBGraph > graph_distrib_t
typedef CH4_Data_Choreography::DistributedData< VoluData > volu_distrib_t
typedef CH4_Data_Choreography::DistributedData< EBFaData > ebfa_distrib_t
typedef CH4_Data_Choreography::DistributedData< XFacData > xfac_distrib_t
typedef CH4_Data_Choreography::DistributedData< YFacData > yfac_distrib_t
typedef CH4_Data_Choreography::DistributedData< ZFacData > zfac_distrib_t
typedef CH4_Data_Choreography::DistributedData< EBNormalData > ebnorm_distrib_t
Public Member Functions
LevelGeometryService (const shared_ptr< BaseIF > &a_baseIF, const RealVect &a_origin, const double &a_dx, const Box &a_domain, const DisjointBoxLayout &a_grids, const int &a_ghost, bool a_printStuff=false)
LevelGeometryService (const LevelGeometryService &a_finerLevel, const DisjointBoxLayout &a_grids, bool a_printStuff=false)
void fillGraph (HostBoxData< int > &a_regIrregCovered, vector< inode > &a_nodes, const Box &a_validRegion, const Box &a_ghostRegion, const Box &a_smghRegion, const Box &a_domain) const
Real dx () const
DisjointBoxLayout const getDBL ()
const shared_ptr< graph_distrib_t > getGraphs () const
const shared_ptr< volu_distrib_t > getVoluData () const
const shared_ptr< ebfa_distrib_t > getEBFaceData () const
const shared_ptr< xfac_distrib_t > getXFaceData () const
const shared_ptr< yfac_distrib_t > getYFaceData () const
const shared_ptr< zfac_distrib_t > getZFaceData () const
const shared_ptr< LevelData< HostIrregData< XFACE, IndMomSDMinOne, 1 > > > getFaceData_dispatch (typenameTag< XFACE >) const
const shared_ptr< LevelData< HostIrregData< YFACE, IndMomSDMinOne, 1 > > > getFaceData_dispatch (typenameTag< YFACE >) const
const shared_ptr< LevelData< HostIrregData< ZFACE, IndMomSDMinOne, 1 > > > getFaceData_dispatch (typenameTag< ZFACE >) const
template<CENTERING cent>
const shared_ptr< LevelData< HostIrregData< cent, IndMomSDMinOne, 1 > > > getFaceData () const
ONE ACCESSOR TO RULE THEM ALL.
const shared_ptr< ebnorm_distrib_t > getEBNormalData_x () const
Get eb moment in the x direction.
const shared_ptr< ebnorm_distrib_t > getEBNormalData_y () const
Get eb moment in the y direction.
const shared_ptr< ebnorm_distrib_t > getEBNormalData_z () const
Get eb moment in the z direction.
const shared_ptr< LevelData< EBNormalData > > getEBNormalData (const int a_dir) const
Get eb moment in the.
const Proto::MomentHolder< order > getAllMomentData (const DataIndex a_dit) const
void fillKappa (EBHostData< CELL, Real, 1 > &a_kappa, const Box &a_grbx, const DataIndex &a_dit) const
fill data holder with values of the volume fraction.
void fillEBFaceAlpha (EBHostData< CELL, Real, 1 > &a_ebfacedata, const Box &a_grbx, const DataIndex &a_dit) const
better name—fills with area fraction
IntVect ghostVect () const
Protected Member Functions
template<CENTERING cent>
void shiftAndIncrement (IndMomDIM &a_output, const IndMomDIM &a_input, const EBIndex< cent > &a_coarVoF, const EBIndex< cent > &a_fineVoF, const LevelGeometryService &a_finerLevel)
template<CENTERING cent>
void shiftAndIncrement (IndMomSDMinOne &a_output, const IndMomSDMinOne &a_input, const EBIndex< cent > &a_coarFace, const EBIndex< cent > &a_fineFace, const LevelGeometryService &a_finerLevel)
void coarsenVoFData (const vector< EBIndex< CELL > > &a_vofs, const LevelGeometryService &a_finerLevel, const DataIndex &a_dit)
void coarsenXFaceData (const vector< EBIndex< XFACE > > &a_faces, const LevelGeometryService &a_finerLevel, const DataIndex &a_dit)
void coarsenYFaceData (const vector< EBIndex< YFACE > > &a_faces, const LevelGeometryService &a_finerLevel, const DataIndex &a_dit)
void defineFinestLevel (const RealVect &a_origin, const double &a_dx, bool a_printStuff=false)
void defineData ()
void coarsenGraph (const LevelGeometryService &a_finerLevel)
void coarsenData (const LevelGeometryService &a_finerLevel)
void define (const RealVect &a_origin, const double &a_dx)
bool onBoxBoundary (const Point &a_iv, const Box &a_box, const int &a_dir, const Side::LoHiSide &a_sd) const
RealVect convert2RelativeCoord (const RealVect &a_rVect) const
RealVect convert2RelativeCoord (const IndexTM< double, DIM > &a_rVect) const
void fillNewNode (inode &a_node, const PointSet &a_ivsIrreg, const Point &a_iv) const
shared_ptr< BaseIF > getBaseIF () const
Private Member Functions
LevelGeometryService (const LevelGeometryService &a_fineLevel, const LevelGeometryService &a_coarLevel, bool a_printStuff=false)
void fixRegularCellsNextToCovered (vector< inode > &a_nodes, HostBoxData< int > &a_regIrregCovered, const Box &a_validRegion, const Point &a_iv) const
void getFullNodeWithCoveredFace (inode &a_newNode, const HostBoxData< int > &a_regIrregCovered, const Point &a_iv) const
void exchange (bool a_printStuff=false)
calls exchange on everything
void fillArc (vector< int > a_arc[DIM], CutCellMoments< DIM > &a_cutCellMoments, const int &a_hilo, const PointSet &a_ivsIrreg, const Point &a_curriv) const
LevelGeometryService ()
LevelGeometryService (const LevelGeometryService &a_workshopin)
void operator= (const LevelGeometryService &a_workshopin)
Private Attributes
Box m_domain
DisjointBoxLayout m_grids
shared_ptr< graph_distrib_t > m_graphs
shared_ptr< volu_distrib_t > m_voludata
shared_ptr< ebfa_distrib_t > m_ebfadata
shared_ptr< xfac_distrib_t > m_xfacdata
shared_ptr< yfac_distrib_t > m_yfacdata
shared_ptr< zfac_distrib_t > m_zfacdata
shared_ptr< ebnorm_distrib_t > m_ebnormaldata [3]
RealVect m_origin
int m_order
int m_degreeP
Real m_dx
Real m_cellVol
IntVect m_geomgrow
shared_ptr< BaseIF > m_baseIF
Detailed Description
template<int order>
class LevelGeometryService< order >
makes geometric description from an implicit function.
Member Typedef Documentation
Iv2
template<int order> typedef Proto::IndexTM<int,2> LevelGeometryService< order >::Iv2
IndMomDIM
template<int order> typedef IndexedMoments<DIM , order> LevelGeometryService< order >::IndMomDIM
IndMomSDMinOne
template<int order> typedef IndexedMoments<DIM-1, order> LevelGeometryService< order >::IndMomSDMinOne
MomItDIM
template<int order> typedef MomentIterator<DIM , order> LevelGeometryService< order >::MomItDIM
MomItSDMinOne
template<int order> typedef MomentIterator<DIM-1, order> LevelGeometryService< order >::MomItSDMinOne
inode
template<int order> typedef IrregNode<order> LevelGeometryService< order >::inode
VoluData
template<int order> typedef HostIrregData<CELL, IndMomDIM , 1> LevelGeometryService< order >::VoluData
EBFaData
template<int order> typedef HostIrregData<BOUNDARY, IndMomDIM , 1> LevelGeometryService< order >::EBFaData
XFacData
template<int order> typedef HostIrregData<XFACE, IndMomSDMinOne, 1> LevelGeometryService< order >::XFacData
YFacData
template<int order> typedef HostIrregData<YFACE, IndMomSDMinOne, 1> LevelGeometryService< order >::YFacData
ZFacData
template<int order> typedef HostIrregData<ZFACE, IndMomSDMinOne, 1> LevelGeometryService< order >::ZFacData
EBNormalData
template<int order> typedef HostIrregData<CELL, IndMomDIM , 1> LevelGeometryService< order >::EBNormalData
graph_distrib_t
template<int order> typedef CH4_Data_Choreography::DistributedData<EBGraph> LevelGeometryService< order >::graph_distrib_t
volu_distrib_t
template<int order> typedef CH4_Data_Choreography::DistributedData<VoluData> LevelGeometryService< order >::volu_distrib_t
ebfa_distrib_t
template<int order> typedef CH4_Data_Choreography::DistributedData<EBFaData> LevelGeometryService< order >::ebfa_distrib_t
xfac_distrib_t
template<int order> typedef CH4_Data_Choreography::DistributedData<XFacData> LevelGeometryService< order >::xfac_distrib_t
yfac_distrib_t
template<int order> typedef CH4_Data_Choreography::DistributedData<YFacData> LevelGeometryService< order >::yfac_distrib_t
zfac_distrib_t
template<int order> typedef CH4_Data_Choreography::DistributedData<ZFacData> LevelGeometryService< order >::zfac_distrib_t
ebnorm_distrib_t
template<int order> typedef CH4_Data_Choreography::DistributedData<EBNormalData> LevelGeometryService< order >::ebnorm_distrib_t
Constructor & Destructor Documentation
LevelGeometryService() [1/5]
template<int order> LevelGeometryService< order >::LevelGeometryService (const shared_ptr< BaseIF > & a_baseIF, const RealVect & a_origin, const double & a_dx, const Box & a_domain, const DisjointBoxLayout & a_grids, const int & a_ghost, bool a_printStuff = false)
basif : implicit function origin : location of the lower left corner of the domain dx : grid spacing domain : finest domain in the calculation grids : layout of the domain ghost : maximum number of ghost cells needed in calculation maxCoarsen : maximum level of coarsening
LevelGeometryService() [2/5]
template<int order> LevelGeometryService< order >::LevelGeometryService (const LevelGeometryService< order > & a_finerLevel, const DisjointBoxLayout & a_grids, bool a_printStuff = false)
References coarsen(), LevelGeometryService< order >::coarsenGraph(), BoxLayout::compatible(), LevelGeometryService< order >::m_baseIF, LevelGeometryService< order >::m_degreeP, LevelGeometryService< order >::m_domain, LevelGeometryService< order >::m_dx, LevelGeometryService< order >::m_geomgrow, LevelGeometryService< order >::m_grids, LevelGeometryService< order >::m_origin, and pout().
LevelGeometryService() [3/5]
template<int order> LevelGeometryService< order >::LevelGeometryService (const LevelGeometryService< order > & a_fineLevel, const LevelGeometryService< order > & a_coarLevel, bool a_printStuff = false) private
References LevelGeometryService< order >::defineData(), grow(), LevelGeometryService< order >::LevelGeometryService(), LevelGeometryService< order >::m_baseIF, LevelGeometryService< order >::m_degreeP, LevelGeometryService< order >::m_domain, LevelGeometryService< order >::m_dx, LevelGeometryService< order >::m_ebfadata, LevelGeometryService< order >::m_ebnormaldata, LevelGeometryService< order >::m_geomgrow, LevelGeometryService< order >::m_graphs, LevelGeometryService< order >::m_grids, LevelGeometryService< order >::m_origin, LevelGeometryService< order >::m_voludata, LevelGeometryService< order >::m_xfacdata, LevelGeometryService< order >::m_yfacdata, LevelGeometryService< order >::m_zfacdata, pout(), refine(), DataIterator::size(), and IntVect::Unit.
LevelGeometryService() [4/5]
template<int order> LevelGeometryService< order >::LevelGeometryService () private
Referenced by LevelGeometryService< order >::exchange(), and LevelGeometryService< order >::LevelGeometryService().
LevelGeometryService() [5/5]
template<int order> LevelGeometryService< order >::LevelGeometryService (const LevelGeometryService< order > & a_workshopin) private
Member Function Documentation
fillGraph()
template<int order> void LevelGeometryService< order >::fillGraph (HostBoxData< int > & a_regIrregCovered, vector< inode > & a_nodes, const Box & a_validRegion, const Box & a_ghostRegion, const Box & a_smghRegion, const Box & a_domain) const inline
Define the internals of the input ebisRegion. Public for testing.
References Proto::ebp_index(), LevelGeometryService< order >::fixRegularCellsNextToCovered(), Proto::IrregNode< order >::m_volumeMoments, IndexTM< T, N >::setAll(), and Proto::IndexTM< T, N >::Zero.
Referenced by LevelGeometryService< order >::coarsenYFaceData().
dx()
template<int order> Real LevelGeometryService< order >::dx () const inline
Referenced by fillFaceAlpha().
getDBL()
template<int order> DisjointBoxLayout const LevelGeometryService< order >::getDBL () inline
getGraphs()
template<int order> const shared_ptr<graph_distrib_t> LevelGeometryService< order >::getGraphs () const inline
Referenced by fillFaceAlpha().
getVoluData()
template<int order> const shared_ptr<volu_distrib_t> LevelGeometryService< order >::getVoluData () const inline
getEBFaceData()
template<int order> const shared_ptr<ebfa_distrib_t > LevelGeometryService< order >::getEBFaceData () const inline
getXFaceData()
template<int order> const shared_ptr<xfac_distrib_t > LevelGeometryService< order >::getXFaceData () const inline
Referenced by fillFaceAlpha().
getYFaceData()
template<int order> const shared_ptr<yfac_distrib_t > LevelGeometryService< order >::getYFaceData () const inline
Referenced by fillFaceAlpha().
getZFaceData()
template<int order> const shared_ptr<zfac_distrib_t > LevelGeometryService< order >::getZFaceData () const inline
Referenced by fillFaceAlpha().
getFaceData_dispatch() [1/3]
template<int order> const shared_ptr< LevelData< HostIrregData< XFACE, IndexedMoments< DIM-1, order >, 1 > > > LevelGeometryService< order >::getFaceData_dispatch (typenameTag< XFACE >) const
References Proto::YFACE.
getFaceData_dispatch() [2/3]
template<int order> const shared_ptr< LevelData< HostIrregData< YFACE, IndexedMoments< DIM-1, order >, 1 > > > LevelGeometryService< order >::getFaceData_dispatch (typenameTag< YFACE >) const
References Proto::ZFACE.
getFaceData_dispatch() [3/3]
template<int order> const shared_ptr< LevelData< HostIrregData< ZFACE, IndexedMoments< DIM-1, order >, 1 > > > LevelGeometryService< order >::getFaceData_dispatch (typenameTag< ZFACE >) const
getFaceData()
template<int order> template<CENTERING cent> const shared_ptr<LevelData<HostIrregData<cent, IndMomSDMinOne, 1> > > LevelGeometryService< order >::getFaceData () const inline
ONE ACCESSOR TO RULE THEM ALL.
getEBNormalData_x()
template<int order> const shared_ptr<ebnorm_distrib_t > LevelGeometryService< order >::getEBNormalData_x () const inline
Get eb moment in the x direction.
getEBNormalData_y()
template<int order> const shared_ptr<ebnorm_distrib_t> LevelGeometryService< order >::getEBNormalData_y () const inline
Get eb moment in the y direction.
getEBNormalData_z()
template<int order> const shared_ptr<ebnorm_distrib_t > LevelGeometryService< order >::getEBNormalData_z () const inline
Get eb moment in the z direction.
getEBNormalData()
template<int order> const shared_ptr<LevelData<EBNormalData> > LevelGeometryService< order >::getEBNormalData (const int a_dir) const inline
Get eb moment in the.
References CH_assert, and SpaceDim.
getAllMomentData()
template<int order> const Proto::MomentHolder<order> LevelGeometryService< order >::getAllMomentData (const DataIndex a_dit) const inline
fillKappa()
template<int order> void LevelGeometryService< order >::fillKappa (EBHostData< CELL, Real, 1 > & a_kappa, const Box & a_grbx, const DataIndex & a_dit) const inline
fill data holder with values of the volume fraction.
References Proto::EBHostData< cent, data_t, ncomp >::getIrrData(), ProtoCh::getPoint(), Proto::EBHostData< cent, data_t, ncomp >::getRegData(), Proto::EBGraph::getVoFs(), Proto::EBGraph::isCovered(), Proto::EBGraph::isRegular(), and BoxIterator::ok().
fillEBFaceAlpha()
template<int order> void LevelGeometryService< order >::fillEBFaceAlpha (EBHostData< CELL, Real, 1 > & a_ebfacedata, const Box & a_grbx, const DataIndex & a_dit) const inline
better name—fills with area fraction
References Proto::EBIndex< cent >::getCutFace(), Proto::EBHostData< cent, data_t, ncomp >::getIrrData(), ProtoCh::getPoint(), Proto::EBHostData< cent, data_t, ncomp >::getRegData(), Proto::EBGraph::getVoFs(), Proto::EBGraph::isCovered(), Proto::EBGraph::isRegular(), Proto::EBIndex< cent >::m_pt, and BoxIterator::ok().
ghostVect()
template<int order> IntVect LevelGeometryService< order >::ghostVect () const inline
shiftAndIncrement() [1/2]
template<int order> template<CENTERING cent> void LevelGeometryService< order >::shiftAndIncrement (IndMomDIM & a_output, const IndMomDIM & a_input, const EBIndex< cent > & a_coarVoF, const EBIndex< cent > & a_fineVoF, const LevelGeometryService< order > & a_finerLevel) inline protected
References Proto::indexLoc(), LevelGeometryService< order >::m_dx, Proto::IndexedMoments< Dim, P >::shift(), and SpaceDim.
shiftAndIncrement() [2/2]
template<int order> template<CENTERING cent> void LevelGeometryService< order >::shiftAndIncrement (IndMomSDMinOne & a_output, const IndMomSDMinOne & a_input, const EBIndex< cent > & a_coarFace, const EBIndex< cent > & a_fineFace, const LevelGeometryService< order > & a_finerLevel) inline protected
References Proto::EBIndex< cent >::direction(), Proto::indexLoc(), LevelGeometryService< order >::m_dx, Proto::IndexedMoments< Dim, P >::shift(), and SpaceDim.
coarsenVoFData()
template<int order> void LevelGeometryService< order >::coarsenVoFData (const vector< EBIndex< CELL > > & a_vofs, const LevelGeometryService< order > & a_finerLevel, const DataIndex & a_dit) protected
References LevelGeometryService< order >::coarsenXFaceData(), LevelGeometryService< order >::m_dx, LevelGeometryService< order >::m_ebfadata, LevelGeometryService< order >::m_ebnormaldata, LevelGeometryService< order >::m_graphs, LevelGeometryService< order >::m_voludata, Proto::IndexedMoments< Dim, P >::setToRegular(), and Proto::IndexedMoments< Dim, P >::setToZero().
Referenced by LevelGeometryService< order >::coarsenData().
coarsenXFaceData()
template<int order> void LevelGeometryService< order >::coarsenXFaceData (const vector< EBIndex< XFACE > > & a_faces, const LevelGeometryService< order > & a_finerLevel, const DataIndex & a_dit) protected
References LevelGeometryService< order >::coarsenYFaceData(), LevelGeometryService< order >::m_dx, LevelGeometryService< order >::m_graphs, LevelGeometryService< order >::m_xfacdata, Proto::IndexedMoments< Dim, P >::setToRegular(), Proto::IndexedMoments< Dim, P >::setToZero(), and Proto::XFACE.
Referenced by LevelGeometryService< order >::coarsenVoFData().
coarsenYFaceData()
template<int order> void LevelGeometryService< order >::coarsenYFaceData (const vector< EBIndex< YFACE > > & a_faces, const LevelGeometryService< order > & a_finerLevel, const DataIndex & a_dit) protected
References LevelGeometryService< order >::fillGraph(), LevelGeometryService< order >::m_dx, LevelGeometryService< order >::m_graphs, LevelGeometryService< order >::m_yfacdata, LevelGeometryService< order >::m_zfacdata, Proto::IndexedMoments< Dim, P >::setToRegular(), Proto::IndexedMoments< Dim, P >::setToZero(), Proto::YFACE, and Proto::ZFACE.
Referenced by LevelGeometryService< order >::coarsenXFaceData().
defineFinestLevel()
template<int order> void LevelGeometryService< order >::defineFinestLevel (const RealVect & a_origin, const double & a_dx, bool a_printStuff = false) protected
References CH4_SPMD::barrier(), LayoutData< T >::define(), Proto::ebp_index(), LevelGeometryService< order >::exchange(), Proto::getIrregGraphFromNodes(), grow(), pout(), and DataIterator::size().
Referenced by LevelGeometryService< order >::defineData().
defineData()
template<int order> void LevelGeometryService< order >::defineData () protected
References LevelGeometryService< order >::defineFinestLevel().
Referenced by LevelGeometryService< order >::LevelGeometryService().
coarsenGraph()
template<int order> void LevelGeometryService< order >::coarsenGraph (const LevelGeometryService< order > & a_finerLevel) protected
References LevelGeometryService< order >::coarsenData(), Box::grow(), LevelGeometryService< order >::m_graphs, and DataIterator::size().
Referenced by LevelGeometryService< order >::LevelGeometryService().
coarsenData()
template<int order> void LevelGeometryService< order >::coarsenData (const LevelGeometryService< order > & a_finerLevel) protected
boundary faces are coarsenable. faces one in from vof boundary are coarsenable.
References LevelGeometryService< order >::coarsenVoFData(), Box::grow(), and DataIterator::size().
Referenced by LevelGeometryService< order >::coarsenGraph().
define()
template<int order> void LevelGeometryService< order >::define (const RealVect & a_origin, const double & a_dx) protected
onBoxBoundary()
template<int order> bool LevelGeometryService< order >::onBoxBoundary (const Point & a_iv, const Box & a_box, const int & a_dir, const Side::LoHiSide & a_sd) const protected
convert2RelativeCoord() [1/2]
template<int order> RealVect LevelGeometryService< order >::convert2RelativeCoord (const RealVect & a_rVect) const inline protected
convert2RelativeCoord() [2/2]
template<int order> RealVect LevelGeometryService< order >::convert2RelativeCoord (const IndexTM< double, DIM > & a_rVect) const inline protected
fillNewNode()
template<int order> void LevelGeometryService< order >::fillNewNode (inode & a_node, const PointSet & a_ivsIrreg, const Point & a_iv) const inline protected
References BDID_DIR, BDID_HILO, Proto::convertToITM(), Proto::ebp_index(), LevelGeometryService< order >::fillArc(), Proto::generateMultiIndices(), Proto::IrregNode< order >::m_arc, Proto::IrregNode< order >::m_cell, Proto::IrregNode< order >::m_cellIndex, Proto::IrregNode< order >::m_EBMoments, Proto::IrregNode< order >::m_EBNormalMomentsDir, Proto::IrregNode< order >::m_faceMoments, Proto::IrregNode< order >::m_normalPartialDeriv, Proto::IrregNode< order >::m_volumeMoments, Proto::pfactorial(), IndexTM< T, N >::setAll(), and Proto::IndexedMoments< Dim, P >::setToZero().
Referenced by LevelGeometryService< order >::getFullNodeWithCoveredFace().
getBaseIF()
template<int order> shared_ptr<BaseIF> LevelGeometryService< order >::getBaseIF () const inline protected
fixRegularCellsNextToCovered()
template<int order> void LevelGeometryService< order >::fixRegularCellsNextToCovered (vector< inode > & a_nodes, HostBoxData< int > & a_regIrregCovered, const Box & a_validRegion, const Point & a_iv) const inline private
References LevelGeometryService< order >::getFullNodeWithCoveredFace(), and Proto::IrregNode< order >::makeRegular().
Referenced by LevelGeometryService< order >::fillGraph().
getFullNodeWithCoveredFace()
template<int order> void LevelGeometryService< order >::getFullNodeWithCoveredFace (inode & a_newNode, const HostBoxData< int > & a_regIrregCovered, const Point & a_iv) const inline private
References Proto::ebp_index(), LevelGeometryService< order >::fillNewNode(), Proto::IrregNode< order >::m_arc, Proto::IrregNode< order >::m_faceMoments, Proto::IrregNode< order >::makeRegular(), Proto::IndexedMoments< Dim, P >::setToRegular(), and Proto::IndexedMoments< Dim, P >::setToZero().
Referenced by LevelGeometryService< order >::fixRegularCellsNextToCovered().
exchange()
template<int order> void LevelGeometryService< order >::exchange (bool a_printStuff = false) private
calls exchange on everything
References CH4_SPMD::barrier(), LevelGeometryService< order >::LevelGeometryService(), and pout().
Referenced by LevelGeometryService< order >::defineFinestLevel().
fillArc()
template<int order> void LevelGeometryService< order >::fillArc (vector< int > a_arc[DIM], CutCellMoments< DIM > & a_cutCellMoments, const int & a_hilo, const PointSet & a_ivsIrreg, const Point & a_curriv) const inline private
References BDID_DIR, and BDID_HILO.
Referenced by LevelGeometryService< order >::fillNewNode().
operator=()
template<int order> void LevelGeometryService< order >::operator= (const LevelGeometryService< order > & a_workshopin) private
Member Data Documentation
m_domain
template<int order> Box LevelGeometryService< order >::m_domain private
Referenced by LevelGeometryService< order >::LevelGeometryService().
m_grids
template<int order> DisjointBoxLayout LevelGeometryService< order >::m_grids private
Referenced by LevelGeometryService< order >::LevelGeometryService().
m_graphs
template<int order> shared_ptr<graph_distrib_t > LevelGeometryService< order >::m_graphs private
Referenced by LevelGeometryService< order >::coarsenGraph(), LevelGeometryService< order >::coarsenVoFData(), LevelGeometryService< order >::coarsenXFaceData(), LevelGeometryService< order >::coarsenYFaceData(), and LevelGeometryService< order >::LevelGeometryService().
m_voludata
template<int order> shared_ptr<volu_distrib_t > LevelGeometryService< order >::m_voludata private
Referenced by LevelGeometryService< order >::coarsenVoFData(), and LevelGeometryService< order >::LevelGeometryService().
m_ebfadata
template<int order> shared_ptr<ebfa_distrib_t > LevelGeometryService< order >::m_ebfadata private
Referenced by LevelGeometryService< order >::coarsenVoFData(), and LevelGeometryService< order >::LevelGeometryService().
m_xfacdata
template<int order> shared_ptr<xfac_distrib_t > LevelGeometryService< order >::m_xfacdata private
Referenced by LevelGeometryService< order >::coarsenXFaceData(), and LevelGeometryService< order >::LevelGeometryService().
m_yfacdata
template<int order> shared_ptr<yfac_distrib_t > LevelGeometryService< order >::m_yfacdata private
Referenced by LevelGeometryService< order >::coarsenYFaceData(), and LevelGeometryService< order >::LevelGeometryService().
m_zfacdata
template<int order> shared_ptr<zfac_distrib_t > LevelGeometryService< order >::m_zfacdata private
Referenced by LevelGeometryService< order >::coarsenYFaceData(), and LevelGeometryService< order >::LevelGeometryService().
m_ebnormaldata
template<int order> shared_ptr<ebnorm_distrib_t > LevelGeometryService< order >::m_ebnormaldata[3] private
Referenced by LevelGeometryService< order >::coarsenVoFData(), and LevelGeometryService< order >::LevelGeometryService().
m_origin
template<int order> RealVect LevelGeometryService< order >::m_origin private
Referenced by LevelGeometryService< order >::LevelGeometryService().
m_order
template<int order> int LevelGeometryService< order >::m_order private
m_degreeP
template<int order> int LevelGeometryService< order >::m_degreeP private
Referenced by LevelGeometryService< order >::LevelGeometryService().
m_dx
template<int order> Real LevelGeometryService< order >::m_dx private
Referenced by LevelGeometryService< order >::coarsenVoFData(), LevelGeometryService< order >::coarsenXFaceData(), LevelGeometryService< order >::coarsenYFaceData(), LevelGeometryService< order >::LevelGeometryService(), and LevelGeometryService< order >::shiftAndIncrement().
m_cellVol
template<int order> Real LevelGeometryService< order >::m_cellVol private
m_geomgrow
template<int order> IntVect LevelGeometryService< order >::m_geomgrow private
Referenced by LevelGeometryService< order >::LevelGeometryService().
m_baseIF
template<int order> shared_ptr<BaseIF> LevelGeometryService< order >::m_baseIF private
Referenced by LevelGeometryService< order >::LevelGeometryService().
The documentation for this class was generated from the following files:
Chombo_GeometryService.H
Chombo_GeometryServiceImplem.H