Chombo_4: Proto::IndexedMoments< Dim, P > Class Template Reference
Proto::IndexedMoments< Dim, P > Class Template Reference
#include <Proto_IndexedMoments.H>
Public Member Functions
IndexedMoments ()
constructor—make statics first time called
~IndexedMoments ()
Destructor.
double maxAbs () const
not semantically sensible but makes for easier diagnostics
double & operator[] (int a_i)
const double & operator[] (int a_i) const
double & operator[] (const IndexTM< int, Dim > &a_index)
const double & operator[] (const IndexTM< int, Dim > &a_index) const
IndexedMoments< Dim, P > & operator+= (const IndexedMoments< Dim, P > &increment)
add compoenentwise
IndexedMoments< Dim, P > & operator-= (const IndexedMoments< Dim, P > &increment)
IndexedMoments< Dim, P > & operator*= (const double &a_factor)
multiply each component by constant
void energize (char *a_outbuf) const
seeking out strange new APIs
void linearOut (void *const a_outbuf) const
void linearIn (const void *const a_inbuf)
void setRegular (const double a_dx)
set to a regular IndexTM
void setToRegular (const double a_dx)
bool isRegular () const
IndexedMoments< Dim, P > & operator= (const map< IndexTM< int, Dim >, double > &a_mapin)
for use with irregnode
IndexedMoments< Dim, P > & operator= (const IndexedMoments< Dim, P > &a_input)
void shift (const IndexTM< double, Dim > &a_distance)
shift moment by the input distance.
void setToZero ()
void setVal (double a_val)
void print () const
outputs the current state to std out
void setToTruncatedMultiply (const IndexedMoments< Dim, P > &a_CA, const IndexedMoments< Dim, P > &a_CB)
void divideByFactorial ()
divides each entry by p!
void multiplyByFactorial ()
multiply each entry by p!
Static Public Member Functions
static int size ()
number of reals in the vector
static size_t linearSize ()
for linearization
static size_t charsize ()
another new name for an old thing
static const vector< IndexTM< int, Dim > > & getMonomialPowers ()
monomial powers
static int indexOf (IndexTM< int, Dim > a_index)
Calculate what linear index this multi-index is.
static IndexTM< int, Dim > getIndex (const int &a_linearIndex)
Protected Member Functions
double getMoment (const IndexTM< int, Dim > &a_mono, const map< IndexTM< int, Dim >, double > &a_mapin) const
Static Protected Member Functions
static void setStatics ()
static void setMultiIndicies ()
static void setSize ()
Static Protected Attributes
static bool s_staticsSet = false
static int s_size = 0
static vector< IndexTM< int, Dim > > s_multiIndicies = vector<IndexTM<int, Dim> >()
Private Attributes
int m_isRegular
vector< double > m_moms
Detailed Description
template<int Dim, int P>
class Proto::IndexedMoments< Dim, P >
vector-like container for multi-indexed Real values up to some max multi-index P (sum of indicies <= P). Layout is 0th dim first, then 1st, etc.
Template Parameters
D The Dimension of the container
Constructor & Destructor Documentation
IndexedMoments()
template<int Dim, int P> Proto::IndexedMoments< Dim, P >::IndexedMoments ()
constructor—make statics first time called
Referenced by Proto::IndexedMoments< DIM-1, order >::setStatics().
~IndexedMoments()
template<int Dim, int P> Proto::IndexedMoments< Dim, P >::~IndexedMoments () inline
Destructor.
Member Function Documentation
maxAbs()
template<int Dim, int P> double Proto::IndexedMoments< Dim, P >::maxAbs () const inline
not semantically sensible but makes for easier diagnostics
operator[]() [1/4]
template<int Dim, int P> double& Proto::IndexedMoments< Dim, P >::operator[] (int a_i) inline
Retrieve the moment from the index a_index The lexigraphical index to the data
operator[]() [2/4]
template<int Dim, int P> const double& Proto::IndexedMoments< Dim, P >::operator[] (int a_i) const inline
Retrieve the moment from the index a_index The lexigraphical index to the data
operator[]() [3/4]
template<int Dim, int P> double& Proto::IndexedMoments< Dim, P >::operator[] (const IndexTM< int, Dim > & a_index) inline
Retrieve the moment from the index a_index The multi-index that's needed
operator[]() [4/4]
template<int Dim, int P> const double& Proto::IndexedMoments< Dim, P >::operator[] (const IndexTM< int, Dim > & a_index) const inline
Retrieve the moment from the index a_index The multi-index that's needed
operator+=()
template<int Dim, int P> IndexedMoments< Dim, P > & Proto::IndexedMoments< Dim, P >::operator+= (const IndexedMoments< Dim, P > & increment)
add compoenentwise
Referenced by Proto::IndexedMoments< DIM-1, order >::operator*=(), and Proto::IndexedMoments< DIM-1, order >::operator[]().
operator-=()
template<int Dim, int P> IndexedMoments<Dim, P>& Proto::IndexedMoments< Dim, P >::operator-= (const IndexedMoments< Dim, P > & increment) inline
operator*=()
template<int Dim, int P> IndexedMoments< Dim, P > & Proto::IndexedMoments< Dim, P >::operator*= (const double & a_factor)
multiply each component by constant
multiply each component by factor
Referenced by Proto::IndexedMoments< DIM-1, order >::getMoment(), and Proto::IndexedMoments< DIM-1, order >::operator-=().
size()
template<int Dim, int P> static int Proto::IndexedMoments< Dim, P >::size () inline static
number of reals in the vector
Referenced by EBCM::Algorithm_Framework< ebcm_order >::neighborhood_t::fillDerived(), Proto::getIndMomSize(), EBCM::Algorithm_Framework< ebcm_order >::getMomentMatrix(), Proto::IndexedMoments< DIM-1, order >::linearIn(), Proto::IndexedMoments< DIM-1, order >::linearOut(), Proto::IndexedMoments< DIM-1, order >::linearSize(), and Proto::IndexedMoments< DIM-1, order >::maxAbs().
linearSize()
template<int Dim, int P> static size_t Proto::IndexedMoments< Dim, P >::linearSize (void) inline static
for linearization
Referenced by Proto::IndexedMoments< DIM-1, order >::charsize().
energize()
template<int Dim, int P> void Proto::IndexedMoments< Dim, P >::energize (char * a_outbuf) const inline
seeking out strange new APIs
charsize()
template<int Dim, int P> static size_t Proto::IndexedMoments< Dim, P >::charsize () inline static
another new name for an old thing
linearOut()
template<int Dim, int P> void Proto::IndexedMoments< Dim, P >::linearOut (void *const a_outbuf) const inline
Referenced by Proto::IndexedMoments< DIM-1, order >::energize().
linearIn()
template<int Dim, int P> void Proto::IndexedMoments< Dim, P >::linearIn (const void *const a_inbuf) inline
setRegular()
template<int Dim, int P> void Proto::IndexedMoments< Dim, P >::setRegular (const double a_dx)
set to a regular IndexTM
Only moments with an even multi-index are non-zero
Referenced by Proto::IndexedMoments< DIM-1, order >::IndexedMoments(), Proto::IndexedMoments< DIM-1, order >::linearIn(), and Proto::IndexedMoments< DIM-1, order >::setToRegular().
setToRegular()
template<int Dim, int P> void Proto::IndexedMoments< Dim, P >::setToRegular (const double a_dx) inline
Referenced by LevelGeometryService< order >::coarsenVoFData(), LevelGeometryService< order >::coarsenXFaceData(), LevelGeometryService< order >::coarsenYFaceData(), LevelGeometryService< order >::getFullNodeWithCoveredFace(), BaseExactSolution::operator()(), and Proto::IrregNode< order >::setMomentsToRegular().
getMonomialPowers()
template<int Dim, int P> static const vector<IndexTM<int,Dim> >& Proto::IndexedMoments< Dim, P >::getMonomialPowers () inline static
monomial powers
Referenced by Proto::MomentIterator< D, P >::MomentIterator(), and Proto::IndexedMoments< DIM-1, order >::setRegular().
isRegular()
template<int Dim, int P> bool Proto::IndexedMoments< Dim, P >::isRegular () const inline
operator=() [1/2]
template<int Dim, int P> IndexedMoments< Dim, P > & Proto::IndexedMoments< Dim, P >::operator= (const map< IndexTM< int, Dim >, double > & a_mapin)
for use with irregnode
Referenced by Proto::IndexedMoments< DIM-1, order >::isRegular(), and Proto::IndexedMoments< DIM-1, order >::shift().
operator=() [2/2]
template<int Dim, int P> IndexedMoments<Dim, P>& Proto::IndexedMoments< Dim, P >::operator= (const IndexedMoments< Dim, P > & a_input) inline
shift()
template<int Dim, int P> void Proto::IndexedMoments< Dim, P >::shift (const IndexTM< double, Dim > & a_distance)
shift moment by the input distance.
shift moment by the input vector distance. this changes the current object from integral(x^p) to integral((x+x0)^p), where x0 = a_distance
Referenced by Proto::checkMoments(), EBCM::Algorithm_Framework< ebcm_order >::fillDirichletDomBCRow(), EBCM::Algorithm_Framework< ebcm_order >::fillDirichletEBBCRow(), EBCM::Algorithm_Framework< ebcm_order >::fillNeumannDomBCRow(), EBCM::Algorithm_Framework< ebcm_order >::fillNeumannEBBCRow(), Proto::IndexedMoments< DIM-1, order >::operator+=(), Proto::IndexedMoments< DIM-1, order >::operator=(), LevelGeometryService< order >::shiftAndIncrement(), EBCM::EBCM_Graph< order >::shiftAndMergeVolumeData(), and EBCM::Algorithm_Framework< ebcm_order >::shiftMomentAndFillRow().
setToZero()
template<int Dim, int P> void Proto::IndexedMoments< Dim, P >::setToZero () inline
Referenced by LevelGeometryService< order >::coarsenVoFData(), LevelGeometryService< order >::coarsenXFaceData(), LevelGeometryService< order >::coarsenYFaceData(), LevelGeometryService< order >::fillNewNode(), LevelGeometryService< order >::getFullNodeWithCoveredFace(), Proto::IrregNode< order >::setMomentsToRegular(), and Proto::IrregNode< order >::setMomentsToZero().
setVal()
template<int Dim, int P> void Proto::IndexedMoments< Dim, P >::setVal (double a_val) inline
indexOf()
template<int Dim, int P> int Proto::IndexedMoments< Dim, P >::indexOf (IndexTM< int, Dim > a_index) static
Calculate what linear index this multi-index is.
Referenced by Proto::allPositive(), EBCM::Algorithm_Framework< ebcm_order >::fillDirichletDomBCRow(), EBCM::Algorithm_Framework< ebcm_order >::fillDirichletEBBCRow(), EBCM::Algorithm_Framework< ebcm_order >::fillNeumannDomBCRow(), EBCM::Algorithm_Framework< ebcm_order >::fillNeumannEBBCRow(), Proto::getIndMomLinearIndex(), Proto::IndexedMoments< DIM-1, order >::operator[](), Proto::IndexedMoments< DIM-1, order >::setVal(), and EBCM::Algorithm_Framework< ebcm_order >::shiftMomentAndFillRow().
getIndex()
template<int Dim, int P> static IndexTM<int,Dim> Proto::IndexedMoments< Dim, P >::getIndex (const int & a_linearIndex) inline static
Referenced by Proto::getIndMomMultiIndex().
print()
template<const int Dim, const int P> void Proto::IndexedMoments< Dim, P >::print () const inline
outputs the current state to std out
Referenced by Proto::checkMoments(), EBCM::Algorithm_Framework< ebcm_order >::fillDirichletDomBCRow(), EBCM::Algorithm_Framework< ebcm_order >::fillNeumannDomBCRow(), Proto::IndexedMoments< DIM-1, order >::getIndex(), Proto::IrregNode< order >::print(), and EBCM::Algorithm_Framework< ebcm_order >::shiftMomentAndFillRow().
setToTruncatedMultiply()
template<int Dim, int P> void Proto::IndexedMoments< Dim, P >::setToTruncatedMultiply (const IndexedMoments< Dim, P > & a_CA, const IndexedMoments< Dim, P > & a_CB)
Say = sum_p(CA m^p), and = sum_q(CB m^q).
This sets the current data to the set of coefficents M such that <AB> = sum_r(M m^r) + O(h^P+1).
We drop all coefficents for powers s.t. p + q > P.
Referenced by Proto::IndexedMoments< DIM-1, order >::getIndex(), and Proto::IndexedMoments< DIM-1, order >::setMultiIndicies().
divideByFactorial()
template<int Dim, int P> void Proto::IndexedMoments< Dim, P >::divideByFactorial ()
divides each entry by p!
Referenced by Proto::IndexedMoments< DIM-1, order >::getIndex(), and Proto::IndexedMoments< DIM-1, order >::setToTruncatedMultiply().
multiplyByFactorial()
template<int Dim, int P> void Proto::IndexedMoments< Dim, P >::multiplyByFactorial ()
multiply each entry by p!
Referenced by Proto::IndexedMoments< DIM-1, order >::divideByFactorial(), and Proto::IndexedMoments< DIM-1, order >::getIndex().
getMoment()
template<const int Dim, const int P> double Proto::IndexedMoments< Dim, P >::getMoment (const IndexTM< int, Dim > & a_mono, const map< IndexTM< int, Dim >, double > & a_mapin) const protected
Referenced by Proto::IndexedMoments< DIM-1, order >::getIndex(), and Proto::IndexedMoments< DIM-1, order >::print().
setStatics()
template<int Dim, int P> void Proto::IndexedMoments< Dim, P >::setStatics () static protected
Referenced by Proto::IndexedMoments< DIM-1, order >::getIndex(), Proto::IndexedMoments< DIM-1, order >::getMonomialPowers(), Proto::IndexedMoments< DIM-1, order >::indexOf(), and Proto::IndexedMoments< DIM-1, order >::size().
setMultiIndicies()
template<int Dim, int P> void Proto::IndexedMoments< Dim, P >::setMultiIndicies () static protected
Referenced by Proto::IndexedMoments< DIM-1, order >::setSize().
setSize()
template<int Dim, int P> void Proto::IndexedMoments< Dim, P >::setSize () static protected
Referenced by Proto::IndexedMoments< DIM-1, order >::setRegular().
Member Data Documentation
s_staticsSet
template<int Dim, int P> bool Proto::IndexedMoments< Dim, P >::s_staticsSet = false static protected
Referenced by Proto::IndexedMoments< DIM-1, order >::getMonomialPowers(), and Proto::IndexedMoments< DIM-1, order >::size().
s_size
template<int Dim, int P> int Proto::IndexedMoments< Dim, P >::s_size = 0 static protected
Referenced by Proto::IndexedMoments< DIM-1, order >::setToZero(), Proto::IndexedMoments< DIM-1, order >::setVal(), and Proto::IndexedMoments< DIM-1, order >::size().
s_multiIndicies
template<int Dim, int P> vector< IndexTM< int, Dim > > Proto::IndexedMoments< Dim, P >::s_multiIndicies = vector<IndexTM<int, Dim> >() static protected
Referenced by Proto::IndexedMoments< DIM-1, order >::getIndex(), and Proto::IndexedMoments< DIM-1, order >::getMonomialPowers().
m_isRegular
template<int Dim, int P> int Proto::IndexedMoments< Dim, P >::m_isRegular private
Referenced by Proto::IndexedMoments< DIM-1, order >::isRegular(), Proto::IndexedMoments< DIM-1, order >::linearIn(), Proto::IndexedMoments< DIM-1, order >::linearOut(), and Proto::IndexedMoments< DIM-1, order >::operator=().
m_moms
template<int Dim, int P> vector<double> Proto::IndexedMoments< Dim, P >::m_moms private
Referenced by Proto::IndexedMoments< DIM-1, order >::linearIn(), Proto::IndexedMoments< DIM-1, order >::linearOut(), Proto::IndexedMoments< DIM-1, order >::operator=(), Proto::IndexedMoments< DIM-1, order >::operator[](), Proto::IndexedMoments< DIM-1, order >::setToZero(), and Proto::IndexedMoments< DIM-1, order >::setVal().
The documentation for this class was generated from the following files:
Proto_IndexedMoments.H
Proto_IndexedMomentsImplem.H