Chombo_4: EBCM::SubVolumeVector< order > Class Template Reference
EBCM::SubVolumeVector< order > Class Template Reference
#include <Chombo_EBCM_Graph.H>
Public Types
typedef Proto::HostBoxData< int, 1 > pr_hbd
typedef Proto::Point pr_pt
typedef Proto::Box pr_bx
typedef Chombo4::MayDay ch_mayday
Public Member Functions
virtual ~SubVolumeVector ()
const EBCM_Volu< order > & operator() (const pr_pt &a_index)
not using square bracket because that is confusing with vector
SubVolumeVector (const EBCM_Graph< order > &a_graph, const ch_box &a_region, bool a_printStuff)
Private Member Functions
SubVolumeVector ()
Private Attributes
shared_ptr< pr_hbd > m_indexMap
maps points to vector indices
pr_bx m_inputBx
Detailed Description
template<int order>
class EBCM::SubVolumeVector< order >
Subvolume is a a vector<ebcm_volumes> that corresponds with all the volumes in region defined by a box. This can be used to find the volumes within the neighborhood of a particular cell. I am putting a fast indexing mask over it so I can get to which volume is at a point more quickly than constantly searching through the vector.
This complicates the design. Now this is not just a vector but also has this other (not independent!) data. I have reasons for this particular deviation from keeping this stuff as simple as possible. For the record, here are the reasons. (1) These vectors are not necessarily small, so a naive linear search could be slow. (a) A typical neighborhood is O(10^2) points in 3d (343 for the Devendran stencil away from boundaries). (b) This will also be used over an entire grid, so the vector could be as long as 32^3. (2) Apparently this is the only graph walking tool I am making. (3) Making graph walking too slow will make this stuff unusable. (4) The memory cost here is negligble compared to the moment data. (5) The information was just lying there and it seemed a shame to throw it away.
Member Typedef Documentation
pr_hbd
template<int order> typedef Proto::HostBoxData<int, 1> EBCM::SubVolumeVector< order >::pr_hbd
pr_pt
template<int order> typedef Proto::Point EBCM::SubVolumeVector< order >::pr_pt
pr_bx
template<int order> typedef Proto::Box EBCM::SubVolumeVector< order >::pr_bx
ch_mayday
template<int order> typedef Chombo4::MayDay EBCM::SubVolumeVector< order >::ch_mayday
Constructor & Destructor Documentation
~SubVolumeVector()
template<int order> virtual EBCM::SubVolumeVector< order >::~SubVolumeVector () inline virtual
SubVolumeVector() [1/2]
template<int order> EBCM::SubVolumeVector< order >::SubVolumeVector (const EBCM_Graph< order > & a_graph, const ch_box & a_region, bool a_printStuff) inline
References EBCM::EBCM_Graph< order >::hasIrregular(), EBCM::EBCM_Graph< order >::isRegular(), EBCM::EBCM_Graph< order >::m_dx, EBCM::EBCM_Graph< order >::m_volumes, and pout().
SubVolumeVector() [2/2]
template<int order> EBCM::SubVolumeVector< order >::SubVolumeVector () private
Member Function Documentation
operator()()
template<int order> const EBCM_Volu<order>& EBCM::SubVolumeVector< order >::operator() (const pr_pt & a_index) inline
not using square bracket because that is confusing with vector
References pout().
Member Data Documentation
m_indexMap
template<int order> shared_ptr<pr_hbd> EBCM::SubVolumeVector< order >::m_indexMap private
maps points to vector indices
m_inputBx
template<int order> pr_bx EBCM::SubVolumeVector< order >::m_inputBx private
The documentation for this class was generated from the following file:
Chombo_EBCM_Graph.H