Chombo_4: Proto::edgeMo Class Reference
Proto::edgeMo Class Reference
#include <Proto_Moments.H>
Public Member Functions
edgeMo ()
void define (const RealVect &a_loPt, const RealVect &a_hiPt, const bool &a_intersectLo, const int &a_direction, const bool &a_covered, const bool &a_regular, const bool &a_dontKnow)
RealVect getLo () const
access member data
RealVect getHi () const
bool getIntersectLo () const
double getEdgeLength () const
RealVect getEdgeCentroid () const
bool isCovered () const
bool isRegular () const
bool dontKnow () const
int direction () const
double moment (const Point &a_exponent) const
integrate monomial
Private Attributes
RealVect m_Lo
RealVect m_Hi
bool m_intersectLo
double m_edgeLength
RealVect m_edgeCentroid
bool m_covered
bool m_regular
bool m_dontKnow
int m_varOfInt
Detailed Description
class edgeMo/////////////////////////////////// This class stores data about an edge of a control volume
Constructor & Destructor Documentation
edgeMo()
Proto::edgeMo::edgeMo () inline
References define(), direction(), dontKnow(), getEdgeCentroid(), getEdgeLength(), getHi(), getIntersectLo(), getLo(), isCovered(), isRegular(), and moment().
Member Function Documentation
define()
void Proto::edgeMo::define (const RealVect & a_loPt, const RealVect & a_hiPt, const bool & a_intersectLo, const int & a_direction, const bool & a_covered, const bool & a_regular, const bool & a_dontKnow)
References m_covered, m_dontKnow, m_edgeCentroid, m_edgeLength, m_Hi, m_intersectLo, m_Lo, m_regular, and m_varOfInt.
Referenced by edgeMo(), Proto::faceMo::faceMo(), and Proto::vofMo::vofMo().
getLo()
RealVect Proto::edgeMo::getLo () const
access member data
References m_Lo.
Referenced by edgeMo().
getHi()
RealVect Proto::edgeMo::getHi () const
References m_Hi.
Referenced by edgeMo().
getIntersectLo()
bool Proto::edgeMo::getIntersectLo () const
References m_intersectLo.
Referenced by edgeMo().
getEdgeLength()
double Proto::edgeMo::getEdgeLength () const
References m_edgeLength.
Referenced by edgeMo().
getEdgeCentroid()
RealVect Proto::edgeMo::getEdgeCentroid () const
References m_edgeCentroid.
Referenced by edgeMo().
isCovered()
bool Proto::edgeMo::isCovered () const
References m_covered.
Referenced by edgeMo(), and Proto::faceMo::faceMo().
isRegular()
bool Proto::edgeMo::isRegular () const
References m_regular.
Referenced by edgeMo(), Proto::faceMo::faceMo(), and Proto::vofMo::getFaces().
dontKnow()
bool Proto::edgeMo::dontKnow () const
References m_dontKnow.
Referenced by Proto::vofMo::define(), edgeMo(), Proto::faceMo::faceMo(), and Proto::vofMo::getFaces().
direction()
int Proto::edgeMo::direction () const
References m_varOfInt.
Referenced by edgeMo().
moment()
double Proto::edgeMo::moment (const Point & a_exponent) const
integrate monomial
References m_Hi, m_Lo, and m_varOfInt.
Referenced by edgeMo(), Proto::faceMo::makeNormal(), and Proto::Moments::momentCalc2D().
Member Data Documentation
m_Lo
RealVect Proto::edgeMo::m_Lo private
Referenced by define(), getLo(), and moment().
m_Hi
RealVect Proto::edgeMo::m_Hi private
Referenced by define(), getHi(), and moment().
m_intersectLo
bool Proto::edgeMo::m_intersectLo private
Referenced by define(), and getIntersectLo().
m_edgeLength
double Proto::edgeMo::m_edgeLength private
Referenced by define(), and getEdgeLength().
m_edgeCentroid
RealVect Proto::edgeMo::m_edgeCentroid private
Referenced by define(), and getEdgeCentroid().
m_covered
bool Proto::edgeMo::m_covered private
Referenced by define(), Proto::faceMo::define(), isCovered(), and Proto::faceMo::isCovered().
m_regular
bool Proto::edgeMo::m_regular private
Referenced by define(), Proto::faceMo::define(), isRegular(), and Proto::faceMo::isRegular().
m_dontKnow
bool Proto::edgeMo::m_dontKnow private
Referenced by define(), Proto::faceMo::define(), dontKnow(), and Proto::faceMo::dontKnow().
m_varOfInt
int Proto::edgeMo::m_varOfInt private
Referenced by define(), direction(), and moment().
The documentation for this class was generated from the following files:
Proto_Moments.H
Proto_MomentsImplem.H