Chombo_4: Proto::NormalDerivativeNew< dim > Class Template Reference
Proto::NormalDerivativeNew< dim > Class Template Reference
This computes the derivatives of the normal of a sliced implicit function.
#include <Proto_NormalDerivativeNew.H>
Public Types
typedef IndexTM< int, dim > IvDim
typedef IndexTM< double, dim > RvDim
typedef map< IvDim, double, LexLT< IvDim > > ScalarPowerMap
typedef map< IvDim, RvDim, LexLT< IvDim > > NormalDerivativeMap
Public Member Functions
NormalDerivativeNew ()
Null constructor.
virtual ~NormalDerivativeNew ()
Destructor.
double normal (const int &a_direction, const RvDim &a_point, const IFSlicer< dim > *a_implicitFunction) const
Evaluate the normal of a BaseIF subclass.
NormalDerivativeMap calculateAll (const int &a_maxP, const RvDim &a_point, const IFSlicer< dim > *a_implicitFunction)
Evaluate all derivatives of the normal of an IFSlicer class.
Protected Member Functions
void calculatePhiDerivs (ScalarPowerMap &a_phiDerivs, const RvDim &a_point, const IFSlicer< dim > *a_implicitFunction, const int &a_maxPartial)
void addLDeriv (ScalarPowerMap &a_lDerivs, ScalarPowerMap &a_phiDerivs, NormalDerivativeMap &a_nDerivs, const IvDim &a_deriv)
void addNDeriv (NormalDerivativeMap &a_nDerivs, ScalarPowerMap &a_phiDerivs, ScalarPowerMap &a_lDerivs, const IvDim &a_deriv)
Static Protected Member Functions
static int nChoosek (const IvDim &a_n, const IvDim &a_k)
Private Member Functions
NormalDerivativeNew (const NormalDerivativeNew &a_input)
void operator= (const NormalDerivativeNew &a_input)
Detailed Description
template<int dim>
class Proto::NormalDerivativeNew< dim >
This computes the derivatives of the normal of a sliced implicit function.
This computes the derivatives of the normal of a sliced implicit function
Member Typedef Documentation
IvDim
template<int dim> typedef IndexTM<int,dim> Proto::NormalDerivativeNew< dim >::IvDim
RvDim
template<int dim> typedef IndexTM<double,dim> Proto::NormalDerivativeNew< dim >::RvDim
ScalarPowerMap
template<int dim> typedef map<IvDim,double,LexLT<IvDim> > Proto::NormalDerivativeNew< dim >::ScalarPowerMap
NormalDerivativeMap
template<int dim> typedef map<IvDim,RvDim,LexLT<IvDim> > Proto::NormalDerivativeNew< dim >::NormalDerivativeMap
Constructor & Destructor Documentation
NormalDerivativeNew() [1/2]
template<int dim> Proto::NormalDerivativeNew< dim >::NormalDerivativeNew () inline
Null constructor.
Null constructor
Referenced by Proto::NormalDerivativeNew< dim >::nChoosek().
~NormalDerivativeNew()
template<int dim> virtual Proto::NormalDerivativeNew< dim >::~NormalDerivativeNew () inline virtual
Destructor.
Destructor
NormalDerivativeNew() [2/2]
template<int dim> Proto::NormalDerivativeNew< dim >::NormalDerivativeNew (const NormalDerivativeNew< dim > & a_input) private
Member Function Documentation
normal()
template<int dim> double Proto::NormalDerivativeNew< dim >::normal (const int & a_direction, const RvDim & a_point, const IFSlicer< dim > * a_implicitFunction) const inline
Evaluate the normal of a BaseIF subclass.
Evaluate the normal. a_direction specifies which component of the normal use, a_point is the point in space to evaluate the derivative, and a_ifSlicer is a sliced function whose gradient is the normal.
calculateAll()
template<int dim> NormalDerivativeMap Proto::NormalDerivativeNew< dim >::calculateAll (const int & a_maxP, const RvDim & a_point, const IFSlicer< dim > * a_implicitFunction) inline
Evaluate all derivatives of the normal of an IFSlicer class.
Evaluate all derivatives of the normal, a_maxP specifies the max sum of derivatives to take in any coordinate direction, a_point is the point in space to evaluate the derivatives, and a_ifSlicer is a sliced function whose gradient is the normal.
References Proto::NormalDerivativeNew< dim >::addLDeriv(), Proto::NormalDerivativeNew< dim >::addNDeriv(), Proto::NormalDerivativeNew< dim >::calculatePhiDerivs(), Proto::IndexTM< T, N >::sum(), and Proto::IndexTM< double, dim >::Zero.
Referenced by Proto::IFData< dim >::setNormalDerivatives().
calculatePhiDerivs()
template<int dim> void Proto::NormalDerivativeNew< dim >::calculatePhiDerivs (ScalarPowerMap & a_phiDerivs, const RvDim & a_point, const IFSlicer< dim > * a_implicitFunction, const int & a_maxPartial) inline protected
References Proto::IFSlicer< dim >::value().
Referenced by Proto::NormalDerivativeNew< dim >::calculateAll().
addLDeriv()
template<int dim> void Proto::NormalDerivativeNew< dim >::addLDeriv (ScalarPowerMap & a_lDerivs, ScalarPowerMap & a_phiDerivs, NormalDerivativeMap & a_nDerivs, const IvDim & a_deriv) inline protected
References Proto::NormalDerivativeNew< dim >::nChoosek(), and Proto::IndexTM< T, N >::Zero.
Referenced by Proto::NormalDerivativeNew< dim >::calculateAll().
addNDeriv()
template<int dim> void Proto::NormalDerivativeNew< dim >::addNDeriv (NormalDerivativeMap & a_nDerivs, ScalarPowerMap & a_phiDerivs, ScalarPowerMap & a_lDerivs, const IvDim & a_deriv) inline protected
References Proto::NormalDerivativeNew< dim >::nChoosek(), Proto::IndexTM< T, N >::Zero, and Proto::IndexTM< double, dim >::Zero.
Referenced by Proto::NormalDerivativeNew< dim >::calculateAll().
nChoosek()
template<int dim> static int Proto::NormalDerivativeNew< dim >::nChoosek (const IvDim & a_n, const IvDim & a_k) inline static protected
References Proto::NormalDerivativeNew< dim >::NormalDerivativeNew(), Proto::NormalDerivativeNew< dim >::operator=(), and Proto::IndexTM< T, N >::Zero.
Referenced by Proto::NormalDerivativeNew< dim >::addLDeriv(), and Proto::NormalDerivativeNew< dim >::addNDeriv().
operator=()
template<int dim> void Proto::NormalDerivativeNew< dim >::operator= (const NormalDerivativeNew< dim > & a_input) private
Referenced by Proto::NormalDerivativeNew< dim >::nChoosek().
The documentation for this class was generated from the following file:
Proto_NormalDerivativeNew.H