Chombo_4: MayDay Class Reference
MayDay Class Reference
Error-reporting Functions.
#include <Chombo_MayDay.H>
Static Public Member Functions
static void Error (const char *const a_msg=m_nullString, int m_exitCode=CH_DEFAULT_ERROR_CODE)
Print out message to cerr and exit with the specified exit code.
static void Abort (const char *const a_msg=m_nullString)
Print out message to cerr and exit via abort() (if serial) or MPI_Abort() (if parallel).
static void Warning (const char *const a_msg=m_nullString)
Print out message to cerr and continue.
static void Error (const char *const a_msg=m_nullString, int m_exitCode=CH_DEFAULT_ERROR_CODE)
Print out message to cerr and exit with the specified exit code.
static void Abort (const char *const a_msg=m_nullString)
Print out message to cerr and exit via abort() (if serial) or MPI_Abort() (if parallel).
static void Warning (const char *const a_msg=m_nullString)
Print out message to cerr and continue.
Static Public Attributes
static bool s_debugSpew
static const char *const version
Static Protected Attributes
static const char *const m_nullString
A null string used as a default argument by the other member functions.
Detailed Description
Error-reporting Functions.
This class consists entirely of static error-reporting functions that are used throughout the MayDay implementation together with a version string. In the best of all possible worlds we'd use a namespace, but we aren't there, yet :-) Note that all the output functions add a terminating exclamation mark, so there is no need to add any punction to sentences that get output explicitly.
Member Function Documentation
Error() [1/2]
static void MayDay::Error (const char *const a_msg = m_nullString, int m_exitCode = CH_DEFAULT_ERROR_CODE) static
Print out message to cerr and exit with the specified exit code.
Referenced by LayoutData< FArrayBox >::allocate(), BoxLayoutData< FArrayBox >::allocateBuffers(), BoxLayoutData< FArrayBox >::allocateGhostVector(), EBCrossFaceStencil< order, data_t >::apply(), EBLevelBoxData< cent, NUMCOMPS >::checkIfPeriodic(), CopyIterator::CopyIterator(), LevelData< FArrayBox >::copyTo(), EBLevelBoxData< cent, NUMCOMPS >::copyToDevice(), LevelData< FArrayBox >::define(), BoxLayoutData< FArrayBox >::define(), BaseFab< Real >::degenerate(), EBDictionary< order, data_t, srcCenter, dstCenter >::getIndex(), GeometryService< order >::getLevel(), getOffsets(), H5Type(), IndexTM< T, N >::IndexTM(), LevelData< FArrayBox >::LevelData(), LDaddOp< T >::linearIn(), LevelData< FArrayBox >::localCopyTo(), EBLevelBoxData< cent, NUMCOMPS >::max(), EBLevelFluxData< NUMCOMPS >::maxNorm(), EBLevelBoxData< cent, NUMCOMPS >::maxNorm(), EBLevelBoxData< cent, NUMCOMPS >::maxNormSplit(), EBCM::EBCM_Graph< order >::mergeManyIntoOne(), EBCM::EBCM_Graph< order >::mergeSmallVolumesWithNeighbors(), EBLevelBoxData< cent, NUMCOMPS >::min(), EBLevelBoxData< cent, NUMCOMPS >::pNormSplit(), read(), EBLevelBoxData< cent, NUMCOMPS >::sum(), write(), and WriteMultiData< T >::writeData().
Abort() [1/2]
static void MayDay::Abort (const char *const a_msg = m_nullString) static
Print out message to cerr and exit via abort() (if serial) or MPI_Abort() (if parallel).
The exit code depends on the compiler and MPI implementation.
Referenced by ParmParse::getarr(), LDOperator< T >::op(), operator<<(), and operator>>().
Warning() [1/2]
static void MayDay::Warning (const char *const a_msg = m_nullString) static
Print out message to cerr and continue.
Referenced by read(), and BaseFab< Real >::testBoxAndComp().
Error() [2/2]
static void MayDay::Error (const char *const a_msg = m_nullString, int m_exitCode = CH_DEFAULT_ERROR_CODE) static
Print out message to cerr and exit with the specified exit code.
Abort() [2/2]
static void MayDay::Abort (const char *const a_msg = m_nullString) static
Print out message to cerr and exit via abort() (if serial) or MPI_Abort() (if parallel).
The exit code depends on the compiler and MPI implementation.
Warning() [2/2]
static void MayDay::Warning (const char *const a_msg = m_nullString) static
Print out message to cerr and continue.
Member Data Documentation
s_debugSpew
static bool MayDay::s_debugSpew static
version
static const char *const MayDay::version static
m_nullString
static const char *const MayDay::m_nullString static protected
A null string used as a default argument by the other member functions.
The documentation for this class was generated from the following files:
Chombo_MayDay.H
MayDay.H