Chombo_4: Proto::PlaneIF Class Reference
Proto::PlaneIF Class Reference
#include <Proto_SimpleImplicitFunctions.H>
Public Member Functions
PlaneIF (RealVect a_startPt, RealVect a_normal)
virtual ~PlaneIF ()
Default destructor.
virtual double value (const IndexTM< int, DIM > &a_partialDerivative, const IndexTM< double, DIM > &a_point) const
virtual bool entireBoxRegular (const Box &a_box, const RealVect &a_origin, const double &a_dx)
return true if the box is entirely in the fluid
virtual bool entireBoxCovered (const Box &a_box, const RealVect &a_origin, const double &a_dx)
return true if the entire box is covered by the plane
virtual BaseIF * newImplicitFunction () const
factory method
Public Member Functions inherited from Proto::SimpleGeometry
IndexTM< double, DIM > getIndexTM (const RealVect &a_rv)
vector< RealVect > getCornerLocations (const Box &a_box, const RealVect &a_origin, const double &a_dx)
Public Member Functions inherited from Proto::BaseIF
BaseIF ()
Default constructor.
virtual ~BaseIF ()
Default destructor.
virtual bool entireBoxRegular (const Proto::Box &a_box, const RealVect &a_origin, const double &a_dx)
virtual bool entireBoxCovered (const Proto::Box &a_box, const RealVect &a_origin, const double &a_dx)
overwrite if you have a fast way of knowing if a whole region is regular
Private Member Functions
PlaneIF ()
Private Attributes
RealVect m_startPt
RealVect m_normal
Detailed Description
IF where all cells are regular
Constructor & Destructor Documentation
PlaneIF() [1/2]
Proto::PlaneIF::PlaneIF (RealVect a_startPt, RealVect a_normal) inline
Default constructor Assumes normal facing outward from the interior
~PlaneIF()
virtual Proto::PlaneIF::~PlaneIF () inline virtual
Default destructor.
PlaneIF() [2/2]
Proto::PlaneIF::PlaneIF () private
Member Function Documentation
value()
virtual double Proto::PlaneIF::value (const IndexTM< int, DIM > & a_partialDerivative, const IndexTM< double, DIM > & a_point) const inline virtual
Return the value of the function at a_point. When delineating a domain, the level set value=0 represents the boundary and value<0 is inside the fluid.
Implements Proto::BaseIF.
References Proto::IndexTM< T, N >::sum().
entireBoxRegular()
virtual bool Proto::PlaneIF::entireBoxRegular (const Box & a_box, const RealVect & a_origin, const double & a_dx) inline virtual
return true if the box is entirely in the fluid
References Proto::SimpleGeometry::getCornerLocations(), Proto::SimpleGeometry::getIndexTM(), Proto::IndexTM< T, N >::setAll(), and Proto::BaseIF::value().
entireBoxCovered()
virtual bool Proto::PlaneIF::entireBoxCovered (const Box & a_box, const RealVect & a_origin, const double & a_dx) inline virtual
return true if the entire box is covered by the plane
References Proto::SimpleGeometry::getCornerLocations(), Proto::SimpleGeometry::getIndexTM(), Proto::IndexTM< T, N >::setAll(), and Proto::BaseIF::value().
newImplicitFunction()
virtual BaseIF* Proto::PlaneIF::newImplicitFunction () const inline virtual
factory method
Return a newly allocated derived class. The responsibility for deleting the memory is left to the calling function.
Implements Proto::BaseIF.
Member Data Documentation
m_startPt
RealVect Proto::PlaneIF::m_startPt private
m_normal
RealVect Proto::PlaneIF::m_normal private
The documentation for this class was generated from the following file:
Proto_SimpleImplicitFunctions.H