Chombo_4: IndexTMI.H File Reference
IndexTMI.H File Reference
#include <iostream>
#include "MayDay.H"
#include "Misc.H"
#include "IndexTM.H"
#include "parstream.H"
#include <cmath>
#include <algorithm>
#include <functional>
#include <numeric>
#include "Metaprograms.H"
#include "BaseNamespaceHeader.H"
#include "BaseNamespaceFooter.H"
Macros
#define _INDEXTMI_H_
#define CH_IGNORE_MAX 100000
Functions
template<typename T , int N>
ostream & operator<< (ostream &a_os, const IndexTM< T, N > &a_p)
template<typename T , int N>
istream & operator>> (istream &a_is, IndexTM< T, N > &a_p)
template<typename T >
static bool abscompare (const T &a_a, const T &a_b)
template<typename T >
static T ourmin (T a_a, T a_b)
template<typename T >
static T ourmax (T a_a, T a_b)
template<typename T , int N>
IndexTM< T, N > scale (const IndexTM< T, N > &a_p, T a_s)
template<typename T , int N>
IndexTM< T, N > diagShift (const IndexTM< T, N > &a_p, T a_s)
template<typename T , int N>
IndexTM< T, N > min (const IndexTM< T, N > &a_p1, const IndexTM< T, N > &a_p2)
template<typename T , int N>
IndexTM< T, N > max (const IndexTM< T, N > &a_p1, const IndexTM< T, N > &a_p2)
template<typename T , int N>
IndexTM< T, N > BASISV_TM (int a_dir)
template<typename T , int N>
IndexTM< T, N > reflect (const IndexTM< T, N > &a_a, T a_refIx, int a_idir)
template<typename T >
static T ourcoarsen (T a_a, T a_b)
template<typename T , int N>
IndexTM< T, N > coarsen (const IndexTM< T, N > &a_p, T a_s)
template<typename T , int N>
IndexTM< T, N > coarsen (const IndexTM< T, N > &a_p1, const IndexTM< T, N > &a_p2)
Macro Definition Documentation
_INDEXTMI_H_
#define _INDEXTMI_H_
CH_IGNORE_MAX
#define CH_IGNORE_MAX 100000
Referenced by operator>>().
Function Documentation
operator<<()
template<typename T , int N> ostream& operator<< (ostream & a_os, const IndexTM< T, N > & a_p)
References MayDay::Abort(), and N.
operator>>()
template<typename T , int N> istream& operator>> (istream & a_is, IndexTM< T, N > & a_p)
References MayDay::Abort(), CH_IGNORE_MAX, and N.
abscompare()
template<typename T > static bool abscompare (const T & a_a, const T & a_b) static
References Abs().
ourmin()
template<typename T > static T ourmin (T a_a, T a_b) static
ourmax()
template<typename T > static T ourmax (T a_a, T a_b) static
scale()
template<typename T , int N> IndexTM<T,N> scale (const IndexTM< T, N > & a_p, T a_s) inline
diagShift()
template<typename T , int N> IndexTM<T,N> diagShift (const IndexTM< T, N > & a_p, T a_s) inline
min()
template<typename T , int N> IndexTM<T,N> min (const IndexTM< T, N > & a_p1, const IndexTM< T, N > & a_p2) inline
References IndexTM< T, N >::min().
max()
template<typename T , int N> IndexTM<T,N> max (const IndexTM< T, N > & a_p1, const IndexTM< T, N > & a_p2) inline
References IndexTM< T, N >::max().
BASISV_TM()
template<typename T , int N> IndexTM<T,N> BASISV_TM (int a_dir) inline
Returns a basis vector in the given coordinate direction.
In 3-D: BASISV(0) == (1,0,0); BASISV(1) == (0,1,0); BASISV(2) == (0,0,1).
In 2-D: BASISV(0) == (1,0); BASISV(1) == (0,1).
Note that the coordinate directions are based at zero.
References CH_assert, IndexTM< T, N >::dataPtr(), and N.
reflect()
template<typename T , int N> IndexTM<T,N> reflect (const IndexTM< T, N > & a_a, T a_refIx, int a_idir) inline
References IndexTM< T, N >::reflect().
ourcoarsen()
template<typename T > static T ourcoarsen (T a_a, T a_b) static
References Abs().
coarsen() [1/2]
template<typename T , int N> IndexTM<T,N> coarsen (const IndexTM< T, N > & a_p, T a_s) inline
References IndexTM< T, N >::coarsen().
coarsen() [2/2]
template<typename T , int N> IndexTM<T,N> coarsen (const IndexTM< T, N > & a_p1, const IndexTM< T, N > & a_p2) inline
References IndexTM< T, N >::coarsen().