Chombo_4: IntVect.H File Reference
IntVect.H File Reference
#include <cstddef>
#include <cstdlib>
#include <cstring>
#include <iostream>
#include "SPACE.H"
#include "Vector.H"
#include "IndexTM.H"
#include <cstdint>
#include "SPMD.H"
#include "Misc.H"
#include <functional>
#include "NamespaceHeader.H"
#include "NamespaceFooter.H"
#include "BaseNamespaceHeader.H"
#include "NamespaceVar.H"
#include "BaseNamespaceFooter.H"
Classes
class IntVect
An integer vector in SpaceDim-dimensional space.
Namespaces
BLfacade
std
Macros
#define _INTVECT_H_
Functions
template<>
int linearSize (const CH_XDIR::IntVect &a_iv)
functions for linearization
template<>
void linearIn (CH_XDIR::IntVect &a_iv, const void *a_inBuf)
functions for linearization
template<>
void linearOut (void *a_outBuf, const CH_XDIR::IntVect &a_iv)
functions for linearization
template<>
int linearSize (const Vector< CH_XDIR::IntVect > &a_input)
template<>
void linearIn (Vector< CH_XDIR::IntVect > &a_outputT, const void *const inBuf)
template<>
void linearOut (void *const a_outBuf, const Vector< CH_XDIR::IntVect > &a_inputT)
template<>
int linearSize (const Vector< Vector< CH_XDIR::IntVect > > &a_input)
template<>
void linearIn (Vector< Vector< CH_XDIR::IntVect > > &a_outputT, const void *const inBuf)
template<>
void linearOut (void *const a_outBuf, const Vector< Vector< CH_XDIR::IntVect > > &a_inputT)
IntVect operator+ (int s, const IntVect &p)
IntVect operator- (int s, const IntVect &p)
IntVect operator* (int s, const IntVect &p)
IntVect scale (const IntVect &p, int s)
const IntVect absolute (const IntVect &p)
IntVect diagShift (const IntVect &p, int s)
IntVect min (const IntVect &p1, const IntVect &p2)
IntVect max (const IntVect &p1, const IntVect &p2)
IntVect BASISV (int dir)
IntVect reflect (const IntVect &a, int ref_ix, int idir)
IntVect coarsen (const IntVect &p, int s)
IntVect coarsen (const IntVect &p1, const IntVect &p2)
Variables
static int s_dummyForIntVectH = IntVect::InitStatics()
Macro Definition Documentation
_INTVECT_H_
#define _INTVECT_H_
Function Documentation
linearSize() [1/3]
template<> int linearSize (const CH_XDIR::IntVect & a_iv)
functions for linearization
Referenced by IntVect::min().
linearIn() [1/3]
template<> void linearIn (CH_XDIR::IntVect & a_iv, const void * a_inBuf)
functions for linearization
Referenced by IntVect::min().
linearOut() [1/3]
template<> void linearOut (void * a_outBuf, const CH_XDIR::IntVect & a_iv)
functions for linearization
Referenced by IntVect::min().
linearSize() [2/3]
template<> int linearSize (const Vector< CH_XDIR::IntVect > & a_input)
linearIn() [2/3]
template<> void linearIn (Vector< CH_XDIR::IntVect > & a_outputT, const void *const inBuf)
linearOut() [2/3]
template<> void linearOut (void *const a_outBuf, const Vector< CH_XDIR::IntVect > & a_inputT)
linearSize() [3/3]
template<> int linearSize (const Vector< Vector< CH_XDIR::IntVect > > & a_input)
linearIn() [3/3]
template<> void linearIn (Vector< Vector< CH_XDIR::IntVect > > & a_outputT, const void *const inBuf)
linearOut() [3/3]
template<> void linearOut (void *const a_outBuf, const Vector< Vector< CH_XDIR::IntVect > > & a_inputT)
operator+()
IntVect operator+ (int s, const IntVect & p) inline
Returns an IntVect that is an IntVect p with a scalar s added to each component.
Referenced by IntVect::copy().
operator-()
IntVect operator- (int s, const IntVect & p) inline
Returns s - p.
Referenced by IntVect::copy().
operator*()
IntVect operator* (int s, const IntVect & p) inline
Returns an IntVect that is an IntVect p with each component multiplied by a scalar s.
Referenced by IntVect::copy().
scale()
IntVect scale (const IntVect & p, int s) inline
Returns an IntVect obtained by multiplying each of the components of the given IntVect by a scalar.
Referenced by IntVect::min().
absolute()
const IntVect absolute (const IntVect & p) inline
Referenced by IntVect::min().
diagShift()
IntVect diagShift (const IntVect & p, int s) inline
Returns IntVect obtained by adding a scalar to each of the components of the given IntVect.
Referenced by IntVect::min().
min()
IntVect min (const IntVect & p1, const IntVect & p2) inline
Returns the IntVect that is the component-wise minimum of two argument IntVects.
References IntVect::min().
Referenced by IntVect::copy().
max()
IntVect max (const IntVect & p1, const IntVect & p2) inline
Returns the IntVect that is the component-wise maximum of two argument IntVects.
References IntVect::max().
Referenced by IntVect::copy(), and IntVect::min().
BASISV()
IntVect BASISV (int dir) inline
Returns a basis vector in the given coordinate direction.
In 3-D: BASISV(0) == (1,0,0); BASISV(1) == (0,1,0); BASISV(2) == (0,0,1).
In 2-D: BASISV(0) == (1,0); BASISV(1) == (0,1).
Note that the coordinate directions are based at zero.
References CH_assert, SpaceDim, IntVect::vect, and IntVect::Zero.
Referenced by IntVect::min().
reflect()
IntVect reflect (const IntVect & a, int ref_ix, int idir) inline
Returns an IntVect that is the reflection of the given IntVect in the plane which passes through ref_ix and normal to the coordinate direction idir.
References CH_assert, SpaceDim, and IntVect::vect.
Referenced by IntVect::min().
coarsen() [1/2]
IntVect coarsen (const IntVect & p, int s) inline
Returns an IntVect that is the component-wise integer projection of p by s.
References CH_assert, and IntVect::vect.
Referenced by IntVect::min().
coarsen() [2/2]
IntVect coarsen (const IntVect & p1, const IntVect & p2) inline
Returns an IntVect which is the component-wise integer projection of IntVect p1 by IntVect p2.
References CH_assert, CH_SPACEDIM, IntVect::coarsen(), IntVect::hash(), SpaceDim, IntVect::vect, and IntVect::Zero.
Variable Documentation
s_dummyForIntVectH
int s_dummyForIntVectH = IntVect::InitStatics() static