Chombo_4: Misc.H File Reference
Misc.H File Reference
#include "CH_assert.H"
#include "REAL.H"
#include <cmath>
#include "BaseNamespaceHeader.H"
#include "BaseNamespaceFooter.H"
Classes
class Misc::TypeTr< T >
Test for class type.
struct Misc::TypeTr< T >::Two
Namespaces
Misc
Macros
#define _MISC_H_
Functions
template<class T >
T Min (const T &a_a, const T &a_b)
template<class T >
T Max (const T &a_a, const T &a_b)
template<class T >
T Abs (const T &a_a)
template<class T >
void Swap (T &a_a, T &a_b)
template<unsigned int P>
constexpr int ipow (int M)
template<>
constexpr int ipow< 0 > (int M)
int ipow (int a, int b)
Real ipow (const Real &a, const int &b)
bool Misc::isPower2 (const int a_i)
Test if integer is a power of 2.
Macro Definition Documentation
_MISC_H_
#define _MISC_H_
Function Documentation
Min()
template<class T > T Min (const T & a_a, const T & a_b) inline
Returns a copy of the minimum of the two values. Will work with any type T that supplies a T::operator<(const T, const T), or an equivalent construct, as well as a copy constructor. In particular, it will work with any integral or floating-point intrinsic type.
Referenced by IntVect::min().
Max()
template<class T > T Max (const T & a_a, const T & a_b) inline
Returns a copy of the maximum of the two values. Will work with any type T that supplies a T::operator>(const T, const T), or an equivalent construct, as well as a copy constructor. In particular, it will work with any integral or floating-point intrinsic type.
Referenced by IntVect::max().
Abs()
template<class T > T Abs (const T & a_a) inline
Returns a copy of the absolute value of the value. Will work with any type T that can be compared against zero with T::operator>(const T, const T), or an equivalent construct, as well as a copy constructor, and an T::operator-() or equivalent. In particular, it will work with any integral or floating-point intrinsic type.
Referenced by abscompare(), and ourcoarsen().
Swap()
template<class T > void Swap (T & a_a, T & a_b) inline
Swaps the two values. Type T must have a copy constructor and an assignment operator.
ipow() [1/3]
template<unsigned int P> constexpr int ipow (int M) inline
References M, and P.
Referenced by SmoothAbsoluteValue::POW(), and Proto::power().
ipow< 0 >()
template<> constexpr int ipow< 0 > (int M) inline
ipow() [2/3]
int ipow (int a, int b) inline
References CH_assert.
ipow() [3/3]
Real ipow (const Real & a, const int & b) inline