Chombo_4: ProtoCh Namespace Reference
ProtoCh Namespace Reference
these functions are meant to interface with the Proto language.
Functions
Point getPoint (const IntVect &a_iv)
get point from intvect
IntVect getIntVect (const Point &a_pt)
get intvect from point
Box getBox (const ::Proto::Box &a_bx)
get chombo box from proto box
Box getChomboBox (const ::Proto::Box &a_bx)
get chombo box from proto box
Detailed Description
these functions are meant to interface with the Proto language.
Function Documentation
getPoint()
Point ProtoCh::getPoint (const IntVect & a_iv)
get point from intvect
Referenced by LevelGeometryService< order >::fillEBFaceAlpha(), fillFaceAlpha(), LevelGeometryService< order >::fillKappa(), EBLevelBoxData< cent, NUMCOMPS >::sum(), and EBCM::HostLevelData< data_t, ncomp, order >::writeToHDF5().
getIntVect()
IntVect ProtoCh::getIntVect (const Point & a_pt)
get intvect from point
Referenced by EBLevelBoxData< cent, NUMCOMPS >::copyHostToFAB(), EBCM::MetaDataLevel< order >::outputGraphMapAsHDF5(), and writeEBLevelHDF5().
getBox()
Box ProtoCh::getBox (const ::Proto::Box & a_bx)
get chombo box from proto box
Referenced by BaseFab< Real >::charsize(), BaseFab< Real >::copy(), BaseFab< Real >::define(), BaseFab< Real >::linearIn(), BaseFab< Real >::linearOut(), and EBDictionary< order, data_t, srcCenter, dstCenter >::registerStencil().
getChomboBox()
Box ProtoCh::getChomboBox (const ::Proto::Box & a_bx)
get chombo box from proto box