Chombo_4: EBCM Namespace Reference
EBCM Namespace Reference
okay, maybe not the greatest choice of namespace name
Classes
class Algorithm_Framework
class EBCM_Face
class EBCM_Graph
class EBCM_Volu
class HostLevelData
Simple structure to hold data on a level in an ebcm context. volume data only.
class IrregFace
class MetaDataLevel
class PETSc_Framework
class SubVolumeVector
Typedefs
typedef Chombo4::Box ch_box
typedef Chombo4::DisjointBoxLayout ch_dbl
typedef Chombo4::ProblemDomain ch_probdom
typedef Chombo4::IntVect ch_iv
typedef Chombo4::MayDay ch_mayday
typedef Proto::RealVect pr_rv
typedef Proto::IndexTM< double, DIM > pr_itm_r_dim
typedef Proto::IndexTM< int, DIM > pr_itm_i_dim
typedef Proto::IndexTM< double, DIM-1 > pr_itm_r_dmo
typedef Proto::IndexTM< int, DIM-1 > pr_itm_i_dmo
typedef Proto::BaseIF pr_baseif
typedef Proto::Point pr_pt
typedef ch_eigen::Matrix eigen_mat
typedef Proto::EBGraph pr_ebgrap
typedef Proto::EBIndex< CELL > pr_vof
typedef Proto::Box pr_box
typedef Proto::HostBoxData< int, 1 > pr_hbd_int
typedef Chombo4::DataIterator ch_dit
typedef Chombo4::DataIndex ch_datind
Functions
template<typename entry_t >
size_t vector_charsize (const vector< entry_t > &a_vec)
get the serialization size of this vector
template<typename entry_t >
size_t vector_energize (char *a_outbuf, const vector< entry_t > &a_vec, size_t a_expected_size)
output this vector to a bytestream
template<typename entry_t >
size_t vector_linearIn (char *a_inbuf, vector< entry_t > &a_vec, size_t a_expected_size)
define this vector from a bytestream
template<CENTERING cent, int order>
double faceSign (const EBCM_Volu< order > &a_volume, const EBCM_Face< cent, order > &a_face)
Get the sign that will be used on the flux F when computing Div(F)
Detailed Description
okay, maybe not the greatest choice of namespace name
An EBCM interface to the magical world of PETSc, where the evil bits of distributed linear algebra are done for us.
Chombo_EBCM_Graph.H is where MetaDataLevel lives. It made sense at the time. I should use this opportunity to apologize to the world for the many awful choices I have made in this life in relation to file names and organization. I regret all the consternation I have caused. I plan to use this for everything. Geometric multigrid requires more infrastructure than I am willing to write so I will use PETSc for solves and truncation error tests and I will be hooking in SLEPc to do the eigenvalue analysis. –dtg
Typedef Documentation
ch_box
typedef Chombo4::Box EBCM::ch_box
ch_dbl
typedef Chombo4::DisjointBoxLayout EBCM::ch_dbl
ch_probdom
typedef Chombo4::ProblemDomain EBCM::ch_probdom
ch_iv
typedef Chombo4::IntVect EBCM::ch_iv
ch_mayday
typedef Chombo4::MayDay EBCM::ch_mayday
pr_rv
typedef Proto::RealVect EBCM::pr_rv
pr_itm_r_dim
typedef Proto::IndexTM<double, DIM> EBCM::pr_itm_r_dim
pr_itm_i_dim
typedef Proto::IndexTM<int , DIM> EBCM::pr_itm_i_dim
pr_itm_r_dmo
typedef Proto::IndexTM<double, DIM-1> EBCM::pr_itm_r_dmo
pr_itm_i_dmo
typedef Proto::IndexTM<int , DIM-1> EBCM::pr_itm_i_dmo
pr_baseif
typedef Proto::BaseIF EBCM::pr_baseif
pr_pt
typedef Proto::Point EBCM::pr_pt
eigen_mat
typedef ch_eigen::Matrix EBCM::eigen_mat
pr_ebgrap
typedef Proto::EBGraph EBCM::pr_ebgrap
pr_vof
typedef Proto::EBIndex<CELL> EBCM::pr_vof
pr_box
typedef Proto::Box EBCM::pr_box
pr_hbd_int
typedef Proto::HostBoxData<int, 1> EBCM::pr_hbd_int
ch_dit
typedef Chombo4::DataIterator EBCM::ch_dit
ch_datind
typedef Chombo4::DataIndex EBCM::ch_datind
Function Documentation
vector_charsize()
template<typename entry_t > size_t EBCM::vector_charsize (const vector< entry_t > & a_vec)
get the serialization size of this vector
Referenced by EBCM::EBCM_Volu< order >::charsize(), EBCM::EBCM_Graph< order >::charsize(), EBCM::EBCM_Volu< order >::energize(), and EBCM::EBCM_Graph< order >::energize().
vector_energize()
template<typename entry_t > size_t EBCM::vector_energize (char * a_outbuf, const vector< entry_t > & a_vec, size_t a_expected_size)
output this vector to a bytestream
Referenced by EBCM::EBCM_Volu< order >::energize(), and EBCM::EBCM_Graph< order >::energize().
vector_linearIn()
template<typename entry_t > size_t EBCM::vector_linearIn (char * a_inbuf, vector< entry_t > & a_vec, size_t a_expected_size)
define this vector from a bytestream
Referenced by EBCM::EBCM_Graph< order >::EBCM_Graph(), and EBCM::EBCM_Volu< order >::linearIn().
faceSign()
template<CENTERING cent, int order> double EBCM::faceSign (const EBCM_Volu< order > & a_volume, const EBCM_Face< cent, order > & a_face)
Get the sign that will be used on the flux F when computing Div(F)
return +1 if face is on the high side of the volume, return -1 if face is on the low side of the volume, Hit's our evil lair's well-labelled self-destruct button if the face is not related to the volume.
References EBCM::EBCM_Face< cent, order >::m_hi, EBCM::EBCM_Face< cent, order >::m_lo, EBCM::EBCM_Volu< order >::m_pt, and pout().
Referenced by EBCM::PETSc_Framework< ebcm_order >::HelmholtzOp::getLocalStencil().