Chombo_4: CH4_SPMD Namespace Reference
CH4_SPMD Namespace Reference
functions for linearization
Classes
class SerialTask
Functions
int reportMPIStats ()
int procID ()
local process ID
int CHprocID ()
unsigned int numProc ()
number of parallel processes
void barrier (void)
all ranks wait here to sync-up
template<class T >
size_t linearSize (const T &inputT)
template<class T >
void linearIn (T &a_outputT, const void *const inBuf)
template<class T >
void linearOut (void *const a_outBuf, const T &inputT)
template<>
size_t linearSize (const int &inputT)
int specialization
template<>
void linearIn (int &a_outputT, const void *const a_inBuf)
template<>
void linearOut (void *const a_outBuf, const int &a_input)
template<class T >
size_t linearListSize (const std::vector< T > &a_input, bool a_printStuff)
template<class T >
void linearListIn (std::vector< T > &a_outputT, size_t a_expectedSize, const void *const a_inBuf, bool a_printStuff)
template<class T >
void linearListOut (void *const a_outBuf, size_t a_expectedSize, const std::vector< T > &a_inputT, bool a_printStuff)
template<>
size_t linearSize (const std::vector< int > &inputT)
vector<int> specialization
template<>
void linearIn (std::vector< int > &a_outputT, const void *const a_inBuf)
template<>
void linearOut (void *const a_outBuf, const std::vector< int > &a_input)
template<class T >
void broadcast (T &a_inAndOut, int a_src, bool a_printStuff=false)
broadcast to every process
int GetPID (int rank)
int GetRank (int pid)
int uniqueProc (const SerialTask::task &a_task)
template<class T >
void gather (std::vector< T > &a_outVec, const T &a_input, int a_dest, bool a_printStuff)
template<>
size_t linearSize (const OffsetBuffer &a_input)
template<>
void linearIn (OffsetBuffer &a_outputT, const void *const a_inBuf)
template<>
void linearOut (void *const a_outBuf, const OffsetBuffer &a_inputT)
template<>
size_t linearSize (const std::vector< OffsetBuffer > &a_input)
template<>
void linearIn (std::vector< OffsetBuffer > &a_outputT, const void *const inBuf)
template<>
void linearOut (void *const a_outBuf, const std::vector< OffsetBuffer > &a_inputT)
Variables
int num_procs
unsigned long long CH_MAX_MPI_MESSAGE_SIZE
unsigned long long CH_MaxMPISendSize
unsigned long long CH_MaxMPIRecvSize
Detailed Description
functions for linearization
Function Documentation
reportMPIStats()
int CH4_SPMD::reportMPIStats ()
procID()
int CH4_SPMD::procID ()
local process ID
Returns the ID of the locally running process in the range 0 <= procID() < numProc(). This has no relation to the operating system pid. There is always a procID() == 0.
Referenced by CH4_Data_Choreography::BoxPattern::BoxPattern(), CH_TIMER_SETFILE(), CHprocID(), CH4_Data_Choreography::DistributedData< EBFluxData< Real, NUMCOMPS > >::communicate(), CH4_Data_Choreography::CommunicationMetaData< fabtype_t >::CommunicationMetaData(), EBCM::PETSc_Framework< ebcm_order >::Base_PETSc_Op::createMatrixRowMap(), CH4_Data_Choreography::DistributedData< EBFluxData< Real, NUMCOMPS > >::define(), write(), WriteMultiData< T >::WriteMultiData(), and BaseTransform::~BaseTransform().
CHprocID()
int CH4_SPMD::CHprocID () inline
References barrier(), numProc(), and procID().
numProc()
unsigned int CH4_SPMD::numProc ()
number of parallel processes
Returns the number of parallel processes running. Always returns at least 1.
Referenced by BoxLayoutData< FArrayBox >::allocateBuffers(), CH4_Data_Choreography::BoxPattern::BoxPattern(), CHprocID(), CH4_Data_Choreography::DistributedData< EBFluxData< Real, NUMCOMPS > >::communicate(), CH4_Data_Choreography::CommunicationMetaData< fabtype_t >::CommunicationMetaData(), EBCM::PETSc_Framework< ebcm_order >::Base_PETSc_Op::createMatrixRowMap(), BoxLayout::printBalance(), and CH4_Data_Choreography::BoxPattern::printStuff().
barrier()
void CH4_SPMD::barrier (void) inline
all ranks wait here to sync-up
All MPI ranks wait here to sync-up. Calls MPI_Barrier(comm)
Referenced by CHprocID(), CH4_Data_Choreography::CommunicationMetaData< fabtype_t >::CommunicationMetaData(), LevelGeometryService< order >::defineFinestLevel(), LevelGeometryService< order >::exchange(), and EBLevelBoxData< cent, NUMCOMPS >::exchangeWithGPU().
linearSize() [1/5]
template<class T > size_t CH4_SPMD::linearSize (const T & inputT)
Referenced by linearListOut(), and linearListSize().
linearIn() [1/5]
template<class T > void CH4_SPMD::linearIn (T & a_outputT, const void *const inBuf)
Referenced by BaseFab< Real >::linearIn(), linearListIn(), and LDOperator< T >::op().
linearOut() [1/5]
template<class T > void CH4_SPMD::linearOut (void *const a_outBuf, const T & inputT)
Referenced by linearListOut(), BaseFab< Real >::linearOut(), and LDOperator< T >::op().
linearSize() [2/5]
template<> size_t CH4_SPMD::linearSize (const int & inputT) inline
int specialization
linearIn() [2/5]
template<> void CH4_SPMD::linearIn (int & a_outputT, const void *const a_inBuf) inline
linearOut() [2/5]
template<> void CH4_SPMD::linearOut (void *const a_outBuf, const int & a_input) inline
References linearListIn(), linearListOut(), and linearListSize().
linearListSize()
template<class T > size_t CH4_SPMD::linearListSize (const std::vector< T > & a_input, bool a_printStuff)
References linearSize().
Referenced by linearOut(), and linearSize().
linearListIn()
template<class T > void CH4_SPMD::linearListIn (std::vector< T > & a_outputT, size_t a_expectedSize, const void *const a_inBuf, bool a_printStuff)
References linearIn(), and pout().
Referenced by linearIn(), and linearOut().
linearListOut()
template<class T > void CH4_SPMD::linearListOut (void *const a_outBuf, size_t a_expectedSize, const std::vector< T > & a_inputT, bool a_printStuff)
References linearOut(), linearSize(), and pout().
Referenced by linearOut().
linearSize() [3/5]
template<> size_t CH4_SPMD::linearSize (const std::vector< int > & inputT) inline
vector<int> specialization
References linearListSize().
linearIn() [3/5]
template<> void CH4_SPMD::linearIn (std::vector< int > & a_outputT, const void *const a_inBuf) inline
References linearListIn().
linearOut() [3/5]
template<> void CH4_SPMD::linearOut (void *const a_outBuf, const std::vector< int > & a_input) inline
References broadcast(), gather(), linearListOut(), and linearListSize().
broadcast()
template<class T > void CH4_SPMD::broadcast (T & a_inAndOut, int a_src, bool a_printStuff = false) inline
broadcast to every process
Broadcasts a_inAndOut to every process from process number a_src. It is an error if a_src < 0 or a_src >= numProc(). \
T must have have the following functions: \
int linearSize<T>(const T& inputT); \ void linearIn<T>(T& a_outputT, const void* const inBuf); \ void linearOut<T>(void* a_outBuf, const T& inputT); \
Referenced by linearOut().
GetPID()
int CH4_SPMD::GetPID (int rank)
GetRank()
int CH4_SPMD::GetRank (int pid)
uniqueProc()
int CH4_SPMD::uniqueProc (const SerialTask::task & a_task)
gather()
template<class T > void CH4_SPMD::gather (std::vector< T > & a_outVec, const T & a_input, int a_dest, bool a_printStuff) inline
Referenced by linearOut().
linearSize() [4/5]
template<> size_t CH4_SPMD::linearSize (const OffsetBuffer & a_input)
linearIn() [4/5]
template<> void CH4_SPMD::linearIn (OffsetBuffer & a_outputT, const void *const a_inBuf)
linearOut() [4/5]
template<> void CH4_SPMD::linearOut (void *const a_outBuf, const OffsetBuffer & a_inputT)
linearSize() [5/5]
template<> size_t CH4_SPMD::linearSize (const std::vector< OffsetBuffer > & a_input)
linearIn() [5/5]
template<> void CH4_SPMD::linearIn (std::vector< OffsetBuffer > & a_outputT, const void *const inBuf)
linearOut() [5/5]
template<> void CH4_SPMD::linearOut (void *const a_outBuf, const std::vector< OffsetBuffer > & a_inputT)
Variable Documentation
num_procs
int CH4_SPMD::num_procs
CH_MAX_MPI_MESSAGE_SIZE
unsigned long long CH4_SPMD::CH_MAX_MPI_MESSAGE_SIZE
Referenced by BoxLayoutData< FArrayBox >::postReceivesToMe(), and BoxLayoutData< FArrayBox >::postSendsFromMe().
CH_MaxMPISendSize
unsigned long long CH4_SPMD::CH_MaxMPISendSize
Referenced by BoxLayoutData< FArrayBox >::postSendsFromMe().
CH_MaxMPIRecvSize
unsigned long long CH4_SPMD::CH_MaxMPIRecvSize
Referenced by BoxLayoutData< FArrayBox >::postReceivesToMe().