Chombo_4: ebcm_basics Namespace Reference
ebcm_basics Namespace Reference
Functions
IndexTM< int, DIM > getVolIndexFromFace (const IndexTM< int, DIM-1 > &a_facind, int a_facedir)
IndexTM< int, DIM-1 > getFaceIndexFromVolIndex (const IndexTM< int, DIM > &a_volind, int a_facedir)
template<int ebcm_order>
IndexedMoments< DIM, ebcm_order > getVolMomFromFacMom (const IndexedMoments< DIM-1, ebcm_order > &a_facmom, int a_facedir)
Function Documentation
getVolIndexFromFace()
IndexTM<int, DIM> ebcm_basics::getVolIndexFromFace (const IndexTM< int, DIM-1 > & a_facind, int a_facedir)
getFaceIndexFromVolIndex()
IndexTM<int, DIM-1> ebcm_basics::getFaceIndexFromVolIndex (const IndexTM< int, DIM > & a_volind, int a_facedir)
Referenced by getVolMomFromFacMom().
getVolMomFromFacMom()
template<int ebcm_order> IndexedMoments<DIM, ebcm_order> ebcm_basics::getVolMomFromFacMom (const IndexedMoments< DIM-1, ebcm_order > & a_facmom, int a_facedir)
References getFaceIndexFromVolIndex(), and Proto::MomentIterator< D, P >::ok().
Referenced by EBCM::Algorithm_Framework< ebcm_order >::neighborhood_t::getFaceDetails(), and EBCM::Algorithm_Framework< ebcm_order >::getMomentMatrix().