Chombo_4: ProtoSer Namespace Reference
ProtoSer Namespace Reference
Functions
template<typename data_t >
size_t linearCharBufSize (const data_t &a_dat)
return serialization length (in number of characters)
template<typename data_t >
void linearInFromCharBuf (data_t &a_dat, const char *a_buf)
define from string of bits
template<typename data_t >
void linearOutToCharBuf (char *a_buf, const data_t &a_dat)
fill string of bits from internals
template<>
size_t linearCharBufSize< double > (const double &a_dat)
and now for all the template specializations needed for intrinsic data types.
template<>
void linearInFromCharBuf< double > (double &a_dat, const char *a_buf)
template<>
void linearOutToCharBuf< double > (char *a_buf, const double &a_dat)
template<>
size_t linearCharBufSize< int > (const int &a_dat)
template<>
void linearInFromCharBuf< int > (int &a_dat, const char *a_buf)
template<>
void linearOutToCharBuf< int > (char *a_buf, const int &a_dat)
template<>
size_t linearCharBufSize< float > (const float &a_dat)
template<>
void linearInFromCharBuf< float > (float &a_dat, const char *a_buf)
template<>
void linearOutToCharBuf< float > (char *a_buf, const float &a_dat)
Function Documentation
linearCharBufSize()
template<typename data_t > size_t ProtoSer::linearCharBufSize (const data_t & a_dat) inline
return serialization length (in number of characters)
Referenced by Proto::HostBoxData< Proto::CellNode, 1 >::charsize(), Proto::HostIrregData< cent, data_t, ncomp >::charsize(), Proto::EBGraph::charsize(), EBCM::EBCM_Graph< order >::charsize(), Proto::EBGraph::EBGraph(), Proto::HostIrregData< cent, data_t, ncomp >::energize(), Proto::EBGraph::energize(), Proto::HostIrregData< cent, data_t, ncomp >::HostIrregData(), Proto::HostBoxData< Proto::CellNode, 1 >::linearIn(), and Proto::HostBoxData< Proto::CellNode, 1 >::linearOut().
linearInFromCharBuf()
template<typename data_t > void ProtoSer::linearInFromCharBuf (data_t & a_dat, const char * a_buf) inline
define from string of bits
Referenced by Proto::EBGraph::EBGraph(), Proto::HostIrregData< cent, data_t, ncomp >::HostIrregData(), and Proto::HostBoxData< Proto::CellNode, 1 >::linearIn().
linearOutToCharBuf()
template<typename data_t > void ProtoSer::linearOutToCharBuf (char * a_buf, const data_t & a_dat) inline
fill string of bits from internals
Referenced by Proto::HostIrregData< cent, data_t, ncomp >::energize(), Proto::EBGraph::energize(), and Proto::HostBoxData< Proto::CellNode, 1 >::linearOut().
linearCharBufSize< double >()
template<> size_t ProtoSer::linearCharBufSize< double > (const double & a_dat) inline
and now for all the template specializations needed for intrinsic data types.
linearInFromCharBuf< double >()
template<> void ProtoSer::linearInFromCharBuf< double > (double & a_dat, const char * a_buf) inline
linearOutToCharBuf< double >()
template<> void ProtoSer::linearOutToCharBuf< double > (char * a_buf, const double & a_dat) inline
linearCharBufSize< int >()
template<> size_t ProtoSer::linearCharBufSize< int > (const int & a_dat) inline
linearInFromCharBuf< int >()
template<> void ProtoSer::linearInFromCharBuf< int > (int & a_dat, const char * a_buf) inline
linearOutToCharBuf< int >()
template<> void ProtoSer::linearOutToCharBuf< int > (char * a_buf, const int & a_dat) inline
linearCharBufSize< float >()
template<> size_t ProtoSer::linearCharBufSize< float > (const float & a_dat) inline
linearInFromCharBuf< float >()
template<> void ProtoSer::linearInFromCharBuf< float > (float & a_dat, const char * a_buf) inline
linearOutToCharBuf< float >()
template<> void ProtoSer::linearOutToCharBuf< float > (char * a_buf, const float & a_dat) inline