Chombo_4: Proto Namespace Reference
Proto Namespace Reference
more ted-isms
Namespaces
Metaprograms
Classes
class AggStencil
class AllRegularIF
class Base2ndOrderFlux
stuff in common for all second order flux calculations
class BaseIF
Class that specifies and implicit function.
class BaseMomentIterator
class to enable template containment
class CellNode
class CoordinateSystem
class CutCellMoments
class CutCellMoments< 1 >
class DirichletEBFlux
class EBBoxData
Holder for EB data over a box.
class EBCrossStencilArchive
end face to cell
struct EBDataLoc
class EBDictionary
class that creates and stores EBStencils
class EBFluxData
Convenience structure that holds coordinate face data in all directions.
class EBGraph
Geometric description within a box.
class EBHostData
Holder for EB data over a box.
class EBHostFluxData
EBFluxData that lives on the host.
class EBIndex
class EBIrregStruct
class EBStencil
class to encapsulate evaluating a stencil for an embedded boundary calculation
class EBStencilArchive
class EBStencilArchive< BOUNDARY, CELL, order, double >
class EBStencilArchive< CELL, BOUNDARY, order, double >
class EBStencilArchive< CELL, CELL, order, double >
class EBStencilArchive< CELL, fcent, order, double >
class EBStencilArchive< fcent, CELL, order, double >
class EBStencilArchive< fcent, fcent, order, double >
class EBStencilArchive< XFACE, YFACE, order, double >
class EBStencilArchive< XFACE, ZFACE, order, double >
class EBStencilArchive< YFACE, XFACE, order, double >
class EBStencilArchive< YFACE, ZFACE, order, double >
class EBStencilArchive< ZFACE, XFACE, order, double >
class EBStencilArchive< ZFACE, YFACE, order, double >
class edgeMo
class faceMo
struct GenericArithmeticable
class HostBoxData
Multidimensional Rectangular Array that lives on the host.
class HostIrregData
class IFData
class IFData< 1 >
class IFSlicer
class IFSlicer< DIM >
class IndexedMoments
class IndexTM
struct IndexTraits
struct IndexTraits< int >
class IrregData
struct IrregGraph
simple struct to allow me to keep EBGraph untemplated
class IrregNode
struct LexLT
class LocalStencil
replacement for Chombo's vofstencil and facestencil
class LSProblem
class LSProblem< 1 >
class LSquares
class MinimalCCCM
class MinimalCCCM< 1 >
struct MomentHolder
class MomentIterator
iterates through the indices of a IndexedMoment
class Moments
class NeumannEBFlux
class NormalDerivativeNew
This computes the derivatives of the normal of a sliced implicit function.
class Normalizor
This class is used to provide nomalized moments (removes dependence on grid spacing)
struct pair_t
struct pairPtr
//
class PlaneIF
class PointSet
PointSet implementation based std::set.
class PointSetIterator
class Poisson2ndOrder
second order Poisson flux
class RealVect
A double vector in DIM-dimensional space.
class SecondOrderStencil
some basic infrastructure to support the second order stuff
class SimpleCosSurfIF
Cos surfaces.
class SimpleCylinderIF
Cylinder.
class SimpleEllipsoidIF
Ellipsoid.
class SimpleGeometry
truly simple geometries can have some simplified bits about what is all covered or regular
class SimpleSinProductIF
Sin bubbles.
class SimpleSphereIF
Sphere.
struct typenameTag
class vofMo
Typedefs
template<CENTERING cent, typename data_t , unsigned int ncomp>
using uglystruct_t = EBIrregStruct< cent, data_t, ncomp >
using IndexIDim = IndexTM< int, DIM >
using IndexICodim = IndexTM< int, DIM-1 >
typedef IndexTM< int, 2 > Iv2
typedef IndexTM< int, DIM > IvgDim
typedef IndexTM< int, DIM-1 > IvgLess1
typedef IndexTM< double, DIM > RvgDim
Enumerations
enum CENTERING {
CELL =0, BOUNDARY, XFACE, YFACE,
ZFACE
}
enum EBorVol { EBMoment = 0, VolMoment = 1 }
Functions
int FACE_DIR (CENTERING cent)
int ebp_index (const int a_idir, const Side::LoHiSide a_side)
void ebp_face (const int a_index, int &a_idir, Side::LoHiSide &a_side)
Get the side and direction from a vector index.
template<typename data_t >
void maxLocCell (const EBBoxData< CELL, data_t, 1 > &data, const Box &a_grid, string a_prefix)
template<CENTERING cent, typename data_t >
void maxLocFace (const EBBoxData< cent, data_t, 1 > &data, const Box &a_grid, string a_prefix)
template<CENTERING cent>
std::ostream & operator<< (std::ostream &a_os, const EBIndex< cent > &a_rv)
template<CENTERING dstCent, CENTERING srcCent>
EBIndex< dstCent > getEBIndex (const EBIndex< srcCent > &a_src)
template<CENTERING cent>
RealVect indexLoc (const EBIndex< cent > &a_index, const RealVect &a_origin, double a_dx)
template<>
RealVect indexLoc (const EBIndex< CELL > &a_index, const RealVect &a_origin, double a_dx)
template<>
RealVect indexLoc (const EBIndex< BOUNDARY > &a_index, const RealVect &a_origin, double a_dx)
template<CENTERING cent>
vector< EBIndex< cent > > getFaces (const EBIndex< CELL > &a_vof, const Side::LoHiSide &a_sd, const EBGraph &a_graph)
template<>
vector< EBIndex< XFACE > > getFaces (const EBIndex< CELL > &a_vof, const Side::LoHiSide &a_sd, const EBGraph &a_graph)
template<>
vector< EBIndex< YFACE > > getFaces (const EBIndex< CELL > &a_vof, const Side::LoHiSide &a_sd, const EBGraph &a_graph)
template<CENTERING cent>
vector< EBIndex< cent > > getIrregFaces (const Box &a_box, const EBGraph &a_graph)
template<CENTERING cent>
vector< EBIndex< cent > > getAllFaces (const Box &a_box, const EBGraph &a_graph)
template<>
vector< EBIndex< BOUNDARY > > getIrregFaces (const Box &a_box, const EBGraph &a_graph)
template<>
vector< EBIndex< BOUNDARY > > getAllFaces (const Box &a_box, const EBGraph &a_graph)
template<CENTERING cent>
vector< EBIndex< cent > > getAllIndicies (const Box &a_box, const EBGraph &a_graph)
template<CENTERING cent>
vector< EBIndex< cent > > getIrregIndicies (const Box &a_box, const EBGraph &a_graph)
template<>
vector< EBIndex< CELL > > getAllIndicies (const Box &a_box, const EBGraph &a_graph)
template<>
vector< EBIndex< CELL > > getIrregIndicies (const Box &a_box, const EBGraph &a_graph)
template<CENTERING cent>
vector< EBIndex< cent > > getSideFaces (const EBIndex< CELL > a_vof, Side::LoHiSide a_sd, const EBGraph &a_graph)
template<typename data_t , unsigned int ncomp>
data_t maxNormCell (EBIndex< CELL > &a_vofmax, const EBHostData< CELL, data_t, ncomp > &a_src, const Box &a_grid, unsigned int a_icomp)
template specialization for cell
template<typename data_t , unsigned int ncomp>
data_t maxCell (const EBHostData< CELL, data_t, ncomp > &a_src, const Box &a_grid, unsigned int a_icomp)
template specialization for cell
template<typename data_t , unsigned int ncomp>
data_t minCell (const EBHostData< CELL, data_t, ncomp > &a_src, const Box &a_grid, unsigned int a_icomp)
template specialization for cell
template<CENTERING cent, typename data_t , unsigned int ncomp>
data_t maxNormFace (EBIndex< cent > &a_facemax, const EBHostData< cent, data_t, ncomp > &a_src, const Box &a_grid, unsigned int a_icomp)
template<CENTERING cent>
void dumpArea (const EBBoxData< cent, double, 1 > &a_fab, string a_prefix)
template<>
void dumpArea (const EBBoxData< CELL, double, 1 > &a_fab, string a_prefix)
std::ostream & operator<< (std::ostream &a_os, const RealVect &a_rv)
RealVect operator* (double s, const RealVect &p)
RealVect operator+ (double s, const RealVect &p)
RealVect operator- (double s, const RealVect &p)
RealVect operator* (const RealVect &s, const RealVect &p)
RealVect operator+ (const RealVect &s, const RealVect &p)
RealVect operator- (const RealVect &s, const RealVect &p)
RealVect BASISREALV (int idir)
void convertToITM (IndexTM< double, DIM > &a_itmpoint, const RealVect &a_rvpoint)
template<typename T >
T & getIrregData (T &a_s)
template<CENTERING cent, typename data_t , unsigned int ncomp>
IrregData< cent, data_t, ncomp > & getIrregData (EBBoxData< cent, data_t, ncomp > &a_s)
template<CENTERING cent, typename data_t , unsigned int ncomp>
IrregData< cent, data_t, ncomp > & getIrregData (const EBBoxData< cent, data_t, ncomp > &a_s)
template<CENTERING cent, typename T >
T getEBIrregStruct (const vector< EBIndex< cent > > &a_indices, T &a_T)
template<CENTERING cent, typename data_t , unsigned int ncomp>
vector< EBIrregStruct< cent, data_t, ncomp > > getEBIrregStruct (const vector< EBIndex< cent > > &a_indices, IrregData< cent, data_t, ncomp > &a_s)
template<typename T >
T & getBoxData (T &a_s)
template<CENTERING cent, typename data_t , unsigned int ncomp>
BoxData< data_t, ncomp > & getBoxData (EBBoxData< cent, data_t, ncomp > &a_s)
template<CENTERING cent, typename data_t , unsigned int ncomp>
const BoxData< data_t, ncomp > & getBoxData (const EBBoxData< cent, data_t, ncomp > &a_s)
template<typename... Srcs>
void emptyFunc (Srcs... a_srcs)
template<typename T >
T getVar (unsigned int ivec, T a_s)
template<CENTERING cent, typename data_t , unsigned int ncomp>
Var< data_t, ncomp > getVar (unsigned int a_ivec, EBIrregStruct< cent, data_t, ncomp > *a_dst)
template<CENTERING cent, typename data_t , unsigned int ncomp, typename Func , typename... Srcs>
void vec_indexer (unsigned int a_begin, unsigned int a_end, const Func &a_F, EBIrregStruct< cent, data_t, ncomp > *a_dst, Srcs... a_srcs)
template<CENTERING cent, typename data_t , unsigned int ncomp, typename Func , typename... Srcs>
void vec_indexer_i (unsigned int a_begin, unsigned int a_end, const Func &a_F, EBIrregStruct< cent, data_t, ncomp > *a_dst, Srcs... a_srcs)
template<CENTERING cent, typename data_t , unsigned int ncomp, typename Func , typename... Srcs>
void protoVectorFunc (const Func &a_F, unsigned int a_Nvec, EBIrregStruct< cent, data_t, ncomp > *a_dst, Srcs... a_srcs)
template<CENTERING cent, typename data_t , unsigned int ncomp, typename Func , typename... Srcs>
void protoVectorFunc_i (const Func &a_F, unsigned int a_Nvec, EBIrregStruct< cent, data_t, ncomp > *a_dst, Srcs... a_srcs)
template<typename T >
T protogetEBIrregStruct (T &a_T)
template<CENTERING cent, typename data_t , unsigned int ncomp>
EBIrregStruct< cent, data_t, ncomp > * protogetEBIrregStruct (IrregData< cent, data_t, ncomp > &a_s)
template<CENTERING cent, typename data_t , unsigned int ncomp, typename Func , typename... Srcs>
void protoEBForAllIrreg (const Func &a_F, IrregData< cent, data_t, ncomp > &a_dst, Srcs &... a_srcs)
template<CENTERING cent, typename data_t , unsigned int ncomp, typename Func , typename... Srcs>
void protoEBForAllIrreg_i (const Func &a_F, IrregData< cent, data_t, ncomp > &a_dst, Srcs &... a_srcs)
going into this srcs are IrregDatas and other stuff
template<typename Func , typename... Srcs>
void protoEBforall (const Func &a_F, const Box a_box, Srcs &... a_srcs)
template<typename Func , typename... Srcs>
void protoEBforall_i (const Func &a_F, const Box a_box, Srcs &... a_srcs)
template<typename Func , typename... Srcs>
void ebforallInPlace (unsigned long long int a_num_flops_point, const char *a_timername, const Func &a_F, const Box a_box, Srcs &... a_srcs)
version that does not send the point to the function
template<typename Func , typename... Srcs>
void ebforallInPlace_i (unsigned long long int a_num_flops_point, const char *a_timername, const Func &a_F, const Box a_box, Srcs &... a_srcs)
version that sends the point to the function
template<typename Func , typename... Srcs>
void ebforallIrreg (const char *a_timername, const Func &a_F, const Box a_box, Srcs &... a_srcs)
version that only touches cut cells
template<typename Func , typename... Srcs>
void ebforallIrreg_i (const char *a_timername, const Func &a_F, const Box a_box, Srcs &... a_srcs)
version that only touches cut cells
template<typename T >
T & checkBox (Box a_inputBox, T &a_T)
template<CENTERING cent, typename data_t , unsigned int ncomp>
EBBoxData< cent, data_t, ncomp > & checkBox (Box a_box, EBBoxData< cent, data_t, ncomp > &a_s)
template<typename Func , typename... Srcs>
void ebforall_i (const Box &a_inputBox, const Func &a_F, Box a_box, Srcs &... a_srcs)
simplest version
template<typename Func , typename... Srcs>
void ebforall (const Box &a_inputBox, const Func &a_F, Box a_box, Srcs &... a_srcs)
simplest version
template<CENTERING fcent, int order>
LocalStencil< fcent, double > getFaceCentroidInterpStencil (const EBIndex< fcent > &a_face, const HostIrregData< XFACE, IndexedMoments< DIM-1, order >, 1 > &a_xfacdata, const HostIrregData< YFACE, IndexedMoments< DIM-1, order >, 1 > &a_yfacdata, const HostIrregData< ZFACE, IndexedMoments< DIM-1, order >, 1 > &a_zfacdata, const EBGraph &a_graph, const double &a_dx)
template<int order>
LocalStencil< XFACE, double > getFaceCentroidInterpStencil (const EBIndex< XFACE > &a_face, const HostIrregData< XFACE, IndexedMoments< DIM-1, order >, 1 > &a_xfacdata, const HostIrregData< YFACE, IndexedMoments< DIM-1, order >, 1 > &a_yfacdata, const HostIrregData< ZFACE, IndexedMoments< DIM-1, order >, 1 > &a_zfacdata, const EBGraph &a_graph, const double &a_dx)
template<int order>
LocalStencil< YFACE, double > getFaceCentroidInterpStencil (const EBIndex< YFACE > &a_face, const HostIrregData< XFACE, IndexedMoments< DIM-1, order >, 1 > &a_xfacdata, const HostIrregData< YFACE, IndexedMoments< DIM-1, order >, 1 > &a_yfacdata, const HostIrregData< ZFACE, IndexedMoments< DIM-1, order >, 1 > &a_zfacdata, const EBGraph &a_graph, const double &a_dx)
template<int order>
LocalStencil< ZFACE, double > getFaceCentroidInterpStencil (const EBIndex< ZFACE > &a_face, const HostIrregData< XFACE, IndexedMoments< DIM-1, order >, 1 > &a_xfacdata, const HostIrregData< YFACE, IndexedMoments< DIM-1, order >, 1 > &a_yfacdata, const HostIrregData< ZFACE, IndexedMoments< DIM-1, order >, 1 > &a_zfacdata, const EBGraph &a_graph, const double &a_dx)
double factorial (const int n)
Calculates factorial for an integer.
double POW (const double &a_x, const int &a_p)
computes x^p
double nCk (const int n, const int k)
Calculates the binomial coefficient, "n choose k".
template<int Dim>
double pfactorial (const IndexTM< int, Dim > p)
Calculates factorials for a multinomial.
template<int Dim>
double pCk (const IndexTM< int, Dim > &p, const IndexTM< int, Dim > &k)
Calculates the multinomial coefficient, "p choose k".
template<int Dim>
double power (const IndexTM< double, Dim > &a_x, const IndexTM< int, Dim > &a_p)
calculate x^p
template<class C >
C::self_type operator+ (const C &, const C &)
template<class C >
C::self_type operator+ (const C &, const typename C::scalar_type &)
template<class C >
C::self_type operator+ (const typename C::scalar_type &, const C &)
template<class C >
C::self_type operator* (const C &, const C &)
template<class C >
C::self_type operator* (const C &, const typename C::scalar_type &)
template<class C >
C::self_type operator* (const typename C::scalar_type &, const C &)
template<class C >
C::self_type operator- (const C &, const C &)
template<class C >
C::self_type operator- (const C &, const typename C::scalar_type &)
template<class C >
C::self_type operator- (const typename C::scalar_type &, const C &)
template<class C >
C::self_type operator/ (const C &, const C &)
template<class C >
C::self_type operator/ (const C &, const typename C::scalar_type &)
template<class C >
C::self_type operator/ (const typename C::scalar_type &, const C &)
template<class C >
C operatorOp (const C &c1, const C &c2, C &(C::*op)(const C &))
template<class C >
C operatorOpScalar (const C &c1, const typename C::scalar_type &x, C &(C::*op)(const typename C::scalar_type &))
template<int Dim>
int getIndMomLinearIndex (const IndexTM< int, Dim > &a_index, const int &a_order)
template<int Dim>
const IndexTM< int, Dim > getIndMomMultiIndex (const int &a_index, const int &a_order)
template<int Dim>
int getIndMomSize (const int &a_order)
template<int Dim>
bool allEven (const IndexTM< int, Dim > &a_p)
to see if all powers of p are even
template<int Dim>
double POW (const double &a_x, const IndexTM< int, Dim > a_p)
computes x^p
template<int Dim, int ORDER>
void checkMoments (IndexedMoments< Dim, ORDER > &a_moments, vector< IndexTM< int, Dim > > &a_bogusPowers, const double &a_dx, const double &a_tolerance, const bool &a_ebMoment, const bool &a_bindMoments)
template<int Dim>
bool allPositive (const IndexTM< int, Dim > &a_index)
unsigned int s_max_sizes (unsigned int D, unsigned int P)
template<typename T , int N>
IndexTM< T, N > min (const IndexTM< T, N > &a_p1, const IndexTM< T, N > &a_p2)
template<typename T , int N>
IndexTM< T, N > max (const IndexTM< T, N > &a_p1, const IndexTM< T, N > &a_p2)
template<typename T , int N>
IndexTM< T, N > scale (const IndexTM< T, N > &a_p, T a_s)
template<typename T , int N>
IndexTM< T, N > reflect (const IndexTM< T, N > &a_a, T a_refIx, int a_idir)
template<typename T , int N>
IndexTM< T, N > diagShift (const IndexTM< T, N > &a_p, T a_s)
template<typename T , int N>
IndexTM< T, N > coarsen (const IndexTM< T, N > &a_p, T a_s)
template<typename T , int N>
IndexTM< T, N > coarsen (const IndexTM< T, N > &a_p1, const IndexTM< T, N > &a_p2)
template<typename T , int N>
std::ostream & operator<< (std::ostream &a_os, const IndexTM< T, N > &a_iv)
template<typename T , int N>
IndexTM< T, N > BASISV_TM (int a_dir)
template<typename T , int N>
ostream & operator<< (ostream &a_os, const IndexTM< T, N > &a_p)
template<typename T >
static bool abscompare (const T &a_a, const T &a_b)
template<typename T >
static T ourmin (T a_a, T a_b)
template<typename T >
static T ourmax (T a_a, T a_b)
template<typename T >
static T ourcoarsen (T a_a, T a_b)
template<int order>
void getIrregGraphFromNodes (vector< IrregGraph > &a_graph, const vector< IrregNode< order > > &a_nodes)
template<int dim>
void generateMultiIndices (vector< IndexTM< int, dim > > &a_indices, const int &a_magnitude)
Real getRegularVolume (const Real a_dx)
Real getRegularArea (const Real a_dx)
double getStenSign (string a_domainBCName)
Variables
constexpr std::array< CENTERING, DIM > REG_FACES
constexpr std::array< CENTERING, DIM+1 > ALL_FACES
Detailed Description
more ted-isms
Typedef Documentation
uglystruct_t
template<CENTERING cent, typename data_t , unsigned int ncomp> using Proto::uglystruct_t = typedef EBIrregStruct<cent, data_t, ncomp>
IndexIDim
using Proto::IndexIDim = typedef IndexTM<int, DIM>
IndexICodim
using Proto::IndexICodim = typedef IndexTM<int, DIM-1>
Iv2
typedef IndexTM<int,2> Proto::Iv2
IvgDim
typedef IndexTM<int,DIM> Proto::IvgDim
IvgLess1
typedef IndexTM<int,DIM-1 > Proto::IvgLess1
RvgDim
typedef IndexTM<double,DIM> Proto::RvgDim
Enumeration Type Documentation
CENTERING
enum Proto::CENTERING
Enumerator
CELL
BOUNDARY
XFACE
YFACE
ZFACE
EBorVol
enum Proto::EBorVol
Enumerator
EBMoment
VolMoment
Function Documentation
FACE_DIR()
int Proto::FACE_DIR (CENTERING cent) inline
References XFACE, and YFACE.
ebp_index()
int Proto::ebp_index (const int a_idir, const Side::LoHiSide a_side) inline
Return the index into a SpaceDim*2 vector use case is: for (int dir = 0; dir != SpaceDim; dir++) { for (SideIterator sit; sit.ok(); ++sit) { int faceIndex = ebp_index(dir, side); val[faceIndex] = side.sign() * flux[dir]; } }
Referenced by Proto::EBGraph::coarsenFaces(), Proto::CellNode::defineAsFullIrregular(), LevelGeometryService< order >::defineFinestLevel(), Proto::EBGraph::defineFromPrimitives(), LevelGeometryService< order >::fillGraph(), LevelGeometryService< order >::fillNewNode(), Proto::SecondOrderStencil< order >::get2ndOrderDivFStencil(), Proto::SecondOrderStencil< order >::getDomainBCs(), Proto::CellNode::getFaceInfo(), LevelGeometryService< order >::getFullNodeWithCoveredFace(), and Proto::EBStencilArchive< CELL, CELL, order, double >::getRegularPoissonBoundaryStencil().
ebp_face()
void Proto::ebp_face (const int a_index, int & a_idir, Side::LoHiSide & a_side) inline
Get the side and direction from a vector index.
for (int faceIdx = 0; faceIdx != 2*SpaceDim; faceIdx++) { int faceDir; Side::LoHiSide faceSide ebp_face(faceIndx, faceDir, faceSide) val[faceIndex] = faceSide.sign() * flux[faceDir]; }
maxLocCell()
template<typename data_t > void Proto::maxLocCell (const EBBoxData< CELL, data_t, 1 > & data, const Box & a_grid, string a_prefix) inline
References Proto::EBBoxData< cent, data_t, ncomp >::ebgraph(), Proto::EBGraph::getVoFs(), and Proto::EBIndex< cent >::m_pt.
maxLocFace()
template<CENTERING cent, typename data_t > void Proto::maxLocFace (const EBBoxData< cent, data_t, 1 > & data, const Box & a_grid, string a_prefix) inline
References Proto::EBBoxData< cent, data_t, ncomp >::ebgraph(), Proto::EBGraph::getVoFs(), and Proto::EBIndex< cent >::m_pt.
operator<<() [1/4]
template<CENTERING cent> std::ostream& Proto::operator<< (std::ostream & a_os, const EBIndex< cent > & a_rv) inline
References Proto::EBIndex< cent >::m_isBoundary, Proto::EBIndex< cent >::m_pt, Proto::EBIndex< cent >::m_vofIDLo, and Proto::EBIndex< cent >::m_vofIDMe.
getEBIndex()
template<CENTERING dstCent, CENTERING srcCent> EBIndex<dstCent> Proto::getEBIndex (const EBIndex< srcCent > & a_src)
References Proto::EBIndex< cent >::m_isBoundary, Proto::EBIndex< cent >::m_pt, Proto::EBIndex< cent >::m_vofIDLo, and Proto::EBIndex< cent >::m_vofIDMe.
indexLoc() [1/3]
template<CENTERING cent> RealVect Proto::indexLoc (const EBIndex< cent > & a_index, const RealVect & a_origin, double a_dx) inline
References Proto::EBIndex< cent >::direction(), and Proto::EBIndex< cent >::m_pt.
Referenced by LevelGeometryService< order >::shiftAndIncrement().
indexLoc() [2/3]
template<> RealVect Proto::indexLoc (const EBIndex< CELL > & a_index, const RealVect & a_origin, double a_dx) inline
References Proto::EBIndex< cent >::m_pt.
indexLoc() [3/3]
template<> RealVect Proto::indexLoc (const EBIndex< BOUNDARY > & a_index, const RealVect & a_origin, double a_dx) inline
References Proto::EBIndex< cent >::m_pt.
getFaces() [1/3]
template<CENTERING cent> vector<EBIndex<cent> > Proto::getFaces (const EBIndex< CELL > & a_vof, const Side::LoHiSide & a_sd, const EBGraph & a_graph) inline
Referenced by getFaces(), and Proto::vofMo::vofMo().
getFaces() [2/3]
template<> vector<EBIndex<XFACE> > Proto::getFaces (const EBIndex< CELL > & a_vof, const Side::LoHiSide & a_sd, const EBGraph & a_graph) inline
References Proto::EBGraph::getXFaces().
getFaces() [3/3]
template<> vector<EBIndex<YFACE> > Proto::getFaces (const EBIndex< CELL > & a_vof, const Side::LoHiSide & a_sd, const EBGraph & a_graph) inline
References getFaces(), and Proto::EBGraph::getYFaces().
getIrregFaces() [1/2]
template<CENTERING cent> vector<EBIndex<cent> > Proto::getIrregFaces (const Box & a_box, const EBGraph & a_graph) inline
References Proto::EBGraph::getDomain(), Proto::EBGraph::getIrregCells(), Proto::EBGraph::getVoFs(), and Proto::PointSetIterator::ok().
getAllFaces() [1/2]
template<CENTERING cent> vector<EBIndex<cent> > Proto::getAllFaces (const Box & a_box, const EBGraph & a_graph) inline
References Proto::EBGraph::getDomain(), Proto::EBGraph::getVoFs(), and Proto::PointSetIterator::ok().
getIrregFaces() [2/2]
template<> vector<EBIndex<BOUNDARY> > Proto::getIrregFaces (const Box & a_box, const EBGraph & a_graph) inline
References Proto::EBGraph::getCutFaces().
getAllFaces() [2/2]
template<> vector<EBIndex<BOUNDARY> > Proto::getAllFaces (const Box & a_box, const EBGraph & a_graph) inline
References Proto::EBGraph::getCutFaces().
getAllIndicies() [1/2]
template<CENTERING cent> vector<EBIndex<cent> > Proto::getAllIndicies (const Box & a_box, const EBGraph & a_graph) inline
getIrregIndicies() [1/2]
template<CENTERING cent> vector<EBIndex<cent> > Proto::getIrregIndicies (const Box & a_box, const EBGraph & a_graph) inline
getAllIndicies() [2/2]
template<> vector<EBIndex<CELL> > Proto::getAllIndicies (const Box & a_box, const EBGraph & a_graph) inline
References Proto::EBGraph::getAllVoFs().
getIrregIndicies() [2/2]
template<> vector<EBIndex<CELL> > Proto::getIrregIndicies (const Box & a_box, const EBGraph & a_graph) inline
References Proto::EBGraph::getIrregVoFs().
getSideFaces()
template<CENTERING cent> vector<EBIndex<cent> > Proto::getSideFaces (const EBIndex< CELL > a_vof, Side::LoHiSide a_sd, const EBGraph & a_graph) inline
maxNormCell()
template<typename data_t , unsigned int ncomp> data_t Proto::maxNormCell (EBIndex< CELL > & a_vofmax, const EBHostData< CELL, data_t, ncomp > & a_src, const Box & a_grid, unsigned int a_icomp)
template specialization for cell
References Proto::EBHostData< cent, data_t, ncomp >::ebgraph(), and max().
Referenced by EBLevelBoxData< cent, NUMCOMPS >::checkAnswer(), and EBLevelBoxData< cent, NUMCOMPS >::maxNorm().
maxCell()
template<typename data_t , unsigned int ncomp> data_t Proto::maxCell (const EBHostData< CELL, data_t, ncomp > & a_src, const Box & a_grid, unsigned int a_icomp)
template specialization for cell
References Proto::EBHostData< cent, data_t, ncomp >::ebgraph(), and max().
Referenced by EBLevelBoxData< cent, NUMCOMPS >::max().
minCell()
template<typename data_t , unsigned int ncomp> data_t Proto::minCell (const EBHostData< CELL, data_t, ncomp > & a_src, const Box & a_grid, unsigned int a_icomp)
template specialization for cell
References Proto::EBHostData< cent, data_t, ncomp >::ebgraph(), and max().
Referenced by EBLevelBoxData< cent, NUMCOMPS >::min().
maxNormFace()
template<CENTERING cent, typename data_t , unsigned int ncomp> data_t Proto::maxNormFace (EBIndex< cent > & a_facemax, const EBHostData< cent, data_t, ncomp > & a_src, const Box & a_grid, unsigned int a_icomp)
References Proto::EBHostData< cent, data_t, ncomp >::ebgraph().
dumpArea() [1/2]
template<CENTERING cent> void Proto::dumpArea (const EBBoxData< cent, double, 1 > & a_fab, string a_prefix) inline
References pout().
Referenced by Proto::EBStencil< order, data_t, srcCenter, dstCenter >::applyITZ().
dumpArea() [2/2]
template<> void Proto::dumpArea (const EBBoxData< CELL, double, 1 > & a_fab, string a_prefix) inline
References Proto::EBBoxData< cent, data_t, ncomp >::box(), and Proto::EBBoxData< cent, data_t, ncomp >::ebgraph().
operator<<() [2/4]
std::ostream& Proto::operator<< (std::ostream & a_os, const RealVect & a_rv) inline
operator*() [1/5]
RealVect Proto::operator* (double s, const RealVect & p) inline
operator+() [1/5]
RealVect Proto::operator+ (double s, const RealVect & p) inline
operator-() [1/5]
RealVect Proto::operator- (double s, const RealVect & p) inline
operator*() [2/5]
RealVect Proto::operator* (const RealVect & s, const RealVect & p) inline
operator+() [2/5]
RealVect Proto::operator+ (const RealVect & s, const RealVect & p) inline
operator-() [2/5]
RealVect Proto::operator- (const RealVect & s, const RealVect & p) inline
BASISREALV()
RealVect Proto::BASISREALV (int idir) inline
References Proto::RealVect::Zero().
Referenced by Proto::Normalizor< order >::getNormalAndBoundaryArea().
convertToITM()
void Proto::convertToITM (IndexTM< double, DIM > & a_itmpoint, const RealVect & a_rvpoint) inline
Referenced by LevelGeometryService< order >::fillNewNode().
getIrregData() [1/3]
template<typename T > T& Proto::getIrregData (T & a_s) inline
Referenced by ebforallIrreg(), ebforallIrreg_i(), protoEBforall(), and protoEBforall_i().
getIrregData() [2/3]
template<CENTERING cent, typename data_t , unsigned int ncomp> IrregData<cent, data_t, ncomp>& Proto::getIrregData (EBBoxData< cent, data_t, ncomp > & a_s) inline
References Proto::EBBoxData< cent, data_t, ncomp >::getIrregData().
getIrregData() [3/3]
template<CENTERING cent, typename data_t , unsigned int ncomp> IrregData<cent, data_t, ncomp>& Proto::getIrregData (const EBBoxData< cent, data_t, ncomp > & a_s) inline
References Proto::EBBoxData< cent, data_t, ncomp >::getIrregData().
getEBIrregStruct() [1/2]
template<CENTERING cent, typename T > T Proto::getEBIrregStruct (const vector< EBIndex< cent > > & a_indices, T & a_T) inline
Referenced by Proto::IrregData< cent, data_t, ncomp >::defineEBIrregData().
getEBIrregStruct() [2/2]
template<CENTERING cent, typename data_t , unsigned int ncomp> vector< EBIrregStruct<cent, data_t, ncomp> > Proto::getEBIrregStruct (const vector< EBIndex< cent > > & a_indices, IrregData< cent, data_t, ncomp > & a_s) inline
References Proto::IrregData< cent, data_t, ncomp >::data(), Proto::IrregData< cent, data_t, ncomp >::index(), Proto::EBIrregStruct< cent, data_t, ncomp >::m_index, Proto::EBIrregStruct< cent, data_t, ncomp >::m_offset, Proto::EBIrregStruct< cent, data_t, ncomp >::m_startPtr, Proto::EBIrregStruct< cent, data_t, ncomp >::m_varsize, and Proto::IrregData< cent, data_t, ncomp >::vecsize().
getBoxData() [1/3]
template<typename T > T& Proto::getBoxData (T & a_s) inline
Referenced by protoEBforall(), and protoEBforall_i().
getBoxData() [2/3]
template<CENTERING cent, typename data_t , unsigned int ncomp> BoxData<data_t, ncomp>& Proto::getBoxData (EBBoxData< cent, data_t, ncomp > & a_s) inline
References Proto::EBBoxData< cent, data_t, ncomp >::getRegData().
getBoxData() [3/3]
template<CENTERING cent, typename data_t , unsigned int ncomp> const BoxData<data_t, ncomp>& Proto::getBoxData (const EBBoxData< cent, data_t, ncomp > & a_s) inline
References Proto::EBBoxData< cent, data_t, ncomp >::getRegData().
emptyFunc()
template<typename... Srcs> void Proto::emptyFunc (Srcs... a_srcs) inline
References Proto::EBIrregStruct< cent, data_t, ncomp >::m_startPtr, Proto::EBIrregStruct< cent, data_t, ncomp >::m_varsize, vec_indexer(), and vec_indexer_i().
getVar() [1/2]
template<typename T > T Proto::getVar (unsigned int ivec, T a_s) inline
Referenced by vec_indexer(), and vec_indexer_i().
getVar() [2/2]
template<CENTERING cent, typename data_t , unsigned int ncomp> Var<data_t, ncomp> Proto::getVar (unsigned int a_ivec, EBIrregStruct< cent, data_t, ncomp > * a_dst) inline
References Proto::EBIrregStruct< cent, data_t, ncomp >::m_offset, Proto::EBIrregStruct< cent, data_t, ncomp >::m_startPtr, and Proto::EBIrregStruct< cent, data_t, ncomp >::m_varsize.
vec_indexer()
template<CENTERING cent, typename data_t , unsigned int ncomp, typename Func , typename... Srcs> void Proto::vec_indexer (unsigned int a_begin, unsigned int a_end, const Func & a_F, EBIrregStruct< cent, data_t, ncomp > * a_dst, Srcs... a_srcs) inline
References getVar().
Referenced by emptyFunc(), and protoVectorFunc().
vec_indexer_i()
template<CENTERING cent, typename data_t , unsigned int ncomp, typename Func , typename... Srcs> void Proto::vec_indexer_i (unsigned int a_begin, unsigned int a_end, const Func & a_F, EBIrregStruct< cent, data_t, ncomp > * a_dst, Srcs... a_srcs) inline
References getVar(), and Proto::EBIrregStruct< cent, data_t, ncomp >::m_index.
Referenced by emptyFunc(), and protoVectorFunc_i().
protoVectorFunc()
template<CENTERING cent, typename data_t , unsigned int ncomp, typename Func , typename... Srcs> void Proto::protoVectorFunc (const Func & a_F, unsigned int a_Nvec, EBIrregStruct< cent, data_t, ncomp > * a_dst, Srcs... a_srcs) inline
References N, and vec_indexer().
Referenced by protoEBForAllIrreg().
protoVectorFunc_i()
template<CENTERING cent, typename data_t , unsigned int ncomp, typename Func , typename... Srcs> void Proto::protoVectorFunc_i (const Func & a_F, unsigned int a_Nvec, EBIrregStruct< cent, data_t, ncomp > * a_dst, Srcs... a_srcs) inline
References N, and vec_indexer_i().
Referenced by protoEBForAllIrreg_i().
protogetEBIrregStruct() [1/2]
template<typename T > T Proto::protogetEBIrregStruct (T & a_T) inline
Referenced by protoEBForAllIrreg(), and protoEBForAllIrreg_i().
protogetEBIrregStruct() [2/2]
template<CENTERING cent, typename data_t , unsigned int ncomp> EBIrregStruct<cent, data_t, ncomp>* Proto::protogetEBIrregStruct (IrregData< cent, data_t, ncomp > & a_s) inline
References Proto::IrregData< cent, data_t, ncomp >::getEBIrregDataPtr().
protoEBForAllIrreg()
template<CENTERING cent, typename data_t , unsigned int ncomp, typename Func , typename... Srcs> void Proto::protoEBForAllIrreg (const Func & a_F, IrregData< cent, data_t, ncomp > & a_dst, Srcs &... a_srcs) inline
References protogetEBIrregStruct(), protoVectorFunc(), and Proto::IrregData< cent, data_t, ncomp >::vecsize().
Referenced by ebforallIrreg(), and protoEBforall().
protoEBForAllIrreg_i()
template<CENTERING cent, typename data_t , unsigned int ncomp, typename Func , typename... Srcs> void Proto::protoEBForAllIrreg_i (const Func & a_F, IrregData< cent, data_t, ncomp > & a_dst, Srcs &... a_srcs) inline
going into this srcs are IrregDatas and other stuff
References protogetEBIrregStruct(), protoVectorFunc_i(), and Proto::IrregData< cent, data_t, ncomp >::vecsize().
Referenced by ebforallIrreg_i(), and protoEBforall_i().
protoEBforall()
template<typename Func , typename... Srcs> void Proto::protoEBforall (const Func & a_F, const Box a_box, Srcs &... a_srcs) inline
References getBoxData(), getIrregData(), and protoEBForAllIrreg().
Referenced by ebforallInPlace().
protoEBforall_i()
template<typename Func , typename... Srcs> void Proto::protoEBforall_i (const Func & a_F, const Box a_box, Srcs &... a_srcs) inline
References getBoxData(), getIrregData(), and protoEBForAllIrreg_i().
Referenced by ebforallInPlace_i().
ebforallInPlace()
template<typename Func , typename... Srcs> void Proto::ebforallInPlace (unsigned long long int a_num_flops_point, const char * a_timername, const Func & a_F, const Box a_box, Srcs &... a_srcs) inline
version that does not send the point to the function
References protoEBforall(), and Box::size().
Referenced by ebforall().
ebforallInPlace_i()
template<typename Func , typename... Srcs> void Proto::ebforallInPlace_i (unsigned long long int a_num_flops_point, const char * a_timername, const Func & a_F, const Box a_box, Srcs &... a_srcs) inline
version that sends the point to the function
References protoEBforall_i(), and Box::size().
Referenced by ebforall_i().
ebforallIrreg()
template<typename Func , typename... Srcs> void Proto::ebforallIrreg (const char * a_timername, const Func & a_F, const Box a_box, Srcs &... a_srcs) inline
version that only touches cut cells
References getIrregData(), and protoEBForAllIrreg().
ebforallIrreg_i()
template<typename Func , typename... Srcs> void Proto::ebforallIrreg_i (const char * a_timername, const Func & a_F, const Box a_box, Srcs &... a_srcs) inline
version that only touches cut cells
References getIrregData(), and protoEBForAllIrreg_i().
checkBox() [1/2]
template<typename T > T& Proto::checkBox (Box a_inputBox, T & a_T) inline
Referenced by ebforall(), and ebforall_i().
checkBox() [2/2]
template<CENTERING cent, typename data_t , unsigned int ncomp> EBBoxData<cent, data_t, ncomp>& Proto::checkBox (Box a_box, EBBoxData< cent, data_t, ncomp > & a_s) inline
References Proto::EBBoxData< cent, data_t, ncomp >::inputBox().
ebforall_i()
template<typename Func , typename... Srcs> void Proto::ebforall_i (const Box & a_inputBox, const Func & a_F, Box a_box, Srcs &... a_srcs) inline
simplest version
References checkBox(), and ebforallInPlace_i().
ebforall()
template<typename Func , typename... Srcs> void Proto::ebforall (const Box & a_inputBox, const Func & a_F, Box a_box, Srcs &... a_srcs) inline
simplest version
References checkBox(), and ebforallInPlace().
getFaceCentroidInterpStencil() [1/4]
template<CENTERING fcent, int order> LocalStencil<fcent, double> Proto::getFaceCentroidInterpStencil (const EBIndex< fcent > & a_face, const HostIrregData< XFACE, IndexedMoments< DIM-1, order >, 1 > & a_xfacdata, const HostIrregData< YFACE, IndexedMoments< DIM-1, order >, 1 > & a_yfacdata, const HostIrregData< ZFACE, IndexedMoments< DIM-1, order >, 1 > & a_zfacdata, const EBGraph & a_graph, const double & a_dx) inline
Referenced by Proto::EBStencilArchive< fcent, fcent, order, double >::getFaceCentroidInterpStencil(), Proto::EBStencilArchive< fcent, fcent, order, double >::getStencil(), and Proto::EBStencilArchive< fcent, fcent, order, double >::~EBStencilArchive().
getFaceCentroidInterpStencil() [2/4]
template<int order> LocalStencil<XFACE, double> Proto::getFaceCentroidInterpStencil (const EBIndex< XFACE > & a_face, const HostIrregData< XFACE, IndexedMoments< DIM-1, order >, 1 > & a_xfacdata, const HostIrregData< YFACE, IndexedMoments< DIM-1, order >, 1 > & a_yfacdata, const HostIrregData< ZFACE, IndexedMoments< DIM-1, order >, 1 > & a_zfacdata, const EBGraph & a_graph, const double & a_dx) inline
References Proto::Base2ndOrderFlux< cent, order >::getFaceInterpStencil().
getFaceCentroidInterpStencil() [3/4]
template<int order> LocalStencil<YFACE, double> Proto::getFaceCentroidInterpStencil (const EBIndex< YFACE > & a_face, const HostIrregData< XFACE, IndexedMoments< DIM-1, order >, 1 > & a_xfacdata, const HostIrregData< YFACE, IndexedMoments< DIM-1, order >, 1 > & a_yfacdata, const HostIrregData< ZFACE, IndexedMoments< DIM-1, order >, 1 > & a_zfacdata, const EBGraph & a_graph, const double & a_dx) inline
References Proto::Base2ndOrderFlux< cent, order >::getFaceInterpStencil().
getFaceCentroidInterpStencil() [4/4]
template<int order> LocalStencil<ZFACE, double> Proto::getFaceCentroidInterpStencil (const EBIndex< ZFACE > & a_face, const HostIrregData< XFACE, IndexedMoments< DIM-1, order >, 1 > & a_xfacdata, const HostIrregData< YFACE, IndexedMoments< DIM-1, order >, 1 > & a_yfacdata, const HostIrregData< ZFACE, IndexedMoments< DIM-1, order >, 1 > & a_zfacdata, const EBGraph & a_graph, const double & a_dx) inline
References Proto::Base2ndOrderFlux< cent, order >::getFaceInterpStencil().
factorial()
double Proto::factorial (const int n) inline
Calculates factorial for an integer.
These helper functions calculate factorials, binomial coeff, etc. for multinomials.
Referenced by Proto::CutCellMoments< dim >::changeMomentCoordinates(), Proto::CutCellMoments< 1 >::changeMomentCoordinates(), Proto::IndexedMoments< DIM-1, order >::divideByFactorial(), Proto::IndexedMoments< DIM-1, order >::multiplyByFactorial(), nCk(), and pfactorial().
POW() [1/2]
double Proto::POW (const double & a_x, const int & a_p) inline
computes x^p
Referenced by Proto::MinimalCCCM< 1 >::computeMomentsUsingBinomial(), Proto::MinimalCCCM< dim >::computeRhs(), Proto::LSProblem< dim >::momentBounds(), Proto::LSProblem< dim >::monoMaxMin(), Proto::Normalizor< order >::normalizeFaceMoment(), Proto::Normalizor< order >::normalizeVolumeMoment(), Proto::IndexedMoments< DIM-1, order >::setRegular(), Proto::IndexedMoments< DIM-1, order >::shift(), and Proto::MinimalCCCM< 1 >::simpleComputeMoments().
nCk()
double Proto::nCk (const int n, const int k) inline
Calculates the binomial coefficient, "n choose k".
References factorial().
Referenced by pCk().
pfactorial()
template<int Dim> double Proto::pfactorial (const IndexTM< int, Dim > p) inline
Calculates factorials for a multinomial.
References factorial().
Referenced by Proto::IndexedMoments< DIM-1, order >::divideByFactorial(), LevelGeometryService< order >::fillNewNode(), and Proto::IndexedMoments< DIM-1, order >::multiplyByFactorial().
pCk()
template<int Dim> double Proto::pCk (const IndexTM< int, Dim > & p, const IndexTM< int, Dim > & k) inline
Calculates the multinomial coefficient, "p choose k".
References nCk().
power()
template<int Dim> double Proto::power (const IndexTM< double, Dim > & a_x, const IndexTM< int, Dim > & a_p) inline
calculate x^p
References ipow().
Referenced by BaseExactSolution::operator()().
operator+() [3/5]
template<class C > C::self_type Proto::operator+ (const C & c1, const C & c2)
operator+() [4/5]
template<class C > C::self_type Proto::operator+ (const C & c, const typename C::scalar_type & x)
operator+() [5/5]
template<class C > C::self_type Proto::operator+ (const typename C::scalar_type & x, const C & c)
operator*() [3/5]
template<class C > C::self_type Proto::operator* (const C & c1, const C & c2)
operator*() [4/5]
template<class C > C::self_type Proto::operator* (const C & c, const typename C::scalar_type & x)
operator*() [5/5]
template<class C > C::self_type Proto::operator* (const typename C::scalar_type & x, const C & c)
operator-() [3/5]
template<class C > C::self_type Proto::operator- (const C & c1, const C & c2)
operator-() [4/5]
template<class C > C::self_type Proto::operator- (const C & c, const typename C::scalar_type & x)
operator-() [5/5]
template<class C > C::self_type Proto::operator- (const typename C::scalar_type & x, const C & c)
References C.
operator/() [1/3]
template<class C > C::self_type Proto::operator/ (const C & c1, const C & c2)
Referenced by IntVect::copy().
operator/() [2/3]
template<class C > C::self_type Proto::operator/ (const C & c, const typename C::scalar_type & x)
operator/() [3/3]
template<class C > C::self_type Proto::operator/ (const typename C::scalar_type & x, const C & c)
References C.
operatorOp()
template<class C > C Proto::operatorOp (const C & c1, const C & c2, C &(C::*)(const C &) op)
References C.
operatorOpScalar()
template<class C > C Proto::operatorOpScalar (const C & c1, const typename C::scalar_type & x, C &(C::*)(const typename C::scalar_type &) op)
References C.
getIndMomLinearIndex()
template<int Dim> int Proto::getIndMomLinearIndex (const IndexTM< int, Dim > & a_index, const int & a_order)
Calculate what linear index this multi-index is without the order stuff
References Proto::IndexedMoments< Dim, P >::indexOf().
getIndMomMultiIndex()
template<int Dim> const IndexTM<int,Dim> Proto::getIndMomMultiIndex (const int & a_index, const int & a_order)
References Proto::IndexedMoments< Dim, P >::getIndex().
getIndMomSize()
template<int Dim> int Proto::getIndMomSize (const int & a_order)
References Proto::IndexedMoments< Dim, P >::size().
allEven()
template<int Dim> bool Proto::allEven (const IndexTM< int, Dim > & a_p)
to see if all powers of p are even
POW() [2/2]
template<int Dim> double Proto::POW (const double & a_x, const IndexTM< int, Dim > a_p)
computes x^p
References allPositive(), and checkMoments().
checkMoments()
template<int Dim, int ORDER> void Proto::checkMoments (IndexedMoments< Dim, ORDER > & a_moments, vector< IndexTM< int, Dim > > & a_bogusPowers, const double & a_dx, const double & a_tolerance, const bool & a_ebMoment, const bool & a_bindMoments)
Moments are centered at the center of the cell. For each of these moments I shift them to the lowest corner of the cell, where I know what the bounds of the integrals is (lower bound always zero, upper bound = dx^d dx^px dx^py dx^pz If the shifted moment is out of bounds, I bound it. The tolerance is about verbosity. If the moment is outside the tolerance then it gets included into a_bogusPowers. EBMoments do not get checked for maxvals.
Moments are centered at the center of the cell. For each of these moments I shift them to the lowest corner of the cell, where I know what the bounds of the integrals is (lower bound always zero, upper bound = dx^d dx^px dx^py dx^pz If the shifted moment is out of bounds, I bound it throw a message. tolerance is about verbosity.
References Proto::MomentIterator< D, P >::ok(), Proto::IndexedMoments< Dim, P >::print(), Proto::MomentIterator< D, P >::reset(), Proto::IndexTM< T, N >::setAll(), Proto::IndexedMoments< Dim, P >::shift(), and Proto::IndexTM< T, N >::sum().
Referenced by POW().
allPositive()
template<int Dim> bool Proto::allPositive (const IndexTM< int, Dim > & a_index)
return true if all of a_index >= 0, false otherwise
References Proto::IndexedMoments< Dim, P >::indexOf().
Referenced by Proto::IndexedMoments< DIM-1, order >::indexOf(), and POW().
s_max_sizes()
unsigned int Proto::s_max_sizes (unsigned int D, unsigned int P) inline
References P.
Referenced by Proto::IndexedMoments< DIM-1, order >::indexOf(), and Proto::IndexedMoments< DIM-1, order >::setSize().
min()
template<typename T , int N> IndexTM< T, N > Proto::min (const IndexTM< T, N > & a_p1, const IndexTM< T, N > & a_p2) inline
References Proto::IndexTM< T, N >::min().
max()
template<typename T , int N> IndexTM< T, N > Proto::max (const IndexTM< T, N > & a_p1, const IndexTM< T, N > & a_p2) inline
References Proto::IndexTM< T, N >::max().
Referenced by Proto::LSquares::findPivot().
scale()
template<typename T , int N> IndexTM< T, N > Proto::scale (const IndexTM< T, N > & a_p, T a_s) inline
reflect()
template<typename T , int N> IndexTM< T, N > Proto::reflect (const IndexTM< T, N > & a_a, T a_refIx, int a_idir) inline
References Proto::IndexTM< T, N >::reflect().
diagShift()
template<typename T , int N> IndexTM< T, N > Proto::diagShift (const IndexTM< T, N > & a_p, T a_s) inline
coarsen() [1/2]
template<typename T , int N> IndexTM< T, N > Proto::coarsen (const IndexTM< T, N > & a_p, T a_s) inline
References Proto::IndexTM< T, N >::coarsen().
Referenced by Proto::EBGraph::getAllVoFs(), and Proto::EBGraph::getVoFsThatCoarsenTo().
coarsen() [2/2]
template<typename T , int N> IndexTM< T, N > Proto::coarsen (const IndexTM< T, N > & a_p1, const IndexTM< T, N > & a_p2) inline
References Proto::IndexTM< T, N >::coarsen().
operator<<() [3/4]
template<typename T , int N> std::ostream& Proto::operator<< (std::ostream & a_os, const IndexTM< T, N > & a_iv)
BASISV_TM()
template<typename T , int N> IndexTM< T, N > Proto::BASISV_TM (int a_dir) inline
Returns a basis vector in the given coordinate direction.
In 3-D: BASISV(0) == (1,0,0); BASISV(1) == (0,1,0); BASISV(2) == (0,0,1).
In 2-D: BASISV(0) == (1,0); BASISV(1) == (0,1).
Note that the coordinate directions are based at zero.
References Proto::IndexTM< T, N >::dataPtr().
Referenced by Proto::Normalizor< order >::normalizedFaceMoments().
operator<<() [4/4]
template<typename T , int N> ostream& Proto::operator<< (ostream & a_os, const IndexTM< T, N > & a_p)
References N.
abscompare()
template<typename T > static bool Proto::abscompare (const T & a_a, const T & a_b) static
ourmin()
template<typename T > static T Proto::ourmin (T a_a, T a_b) static
ourmax()
template<typename T > static T Proto::ourmax (T a_a, T a_b) static
ourcoarsen()
template<typename T > static T Proto::ourcoarsen (T a_a, T a_b) static
getIrregGraphFromNodes()
template<int order> void Proto::getIrregGraphFromNodes (vector< IrregGraph > & a_graph, const vector< IrregNode< order > > & a_nodes) inline
Referenced by LevelGeometryService< order >::defineFinestLevel().
generateMultiIndices()
template<int dim> void Proto::generateMultiIndices (vector< IndexTM< int, dim > > & a_indices, const int & a_magnitude) inline
Referenced by Proto::MinimalCCCM< dim >::computeRhs(), Proto::LSProblem< dim >::fillMap(), LevelGeometryService< order >::fillNewNode(), and Proto::IFData< dim >::setNormalDerivatives().
getRegularVolume()
Real Proto::getRegularVolume (const Real a_dx) inline
Referenced by Proto::Normalizor< order >::normalizeVolumeMoment().
getRegularArea()
Real Proto::getRegularArea (const Real a_dx) inline
Referenced by Proto::Normalizor< order >::normalizeFaceMoment().
getStenSign()
double Proto::getStenSign (string a_domainBCName) inline
References Proto::SecondOrderStencil< order >::getDomainBCs().
Referenced by Proto::SecondOrderStencil< order >::getDomainBCs().
Variable Documentation
REG_FACES
constexpr std::array<CENTERING, DIM> Proto::REG_FACES
Initial value:
{
    XFACE
  }
ALL_FACES
constexpr std::array<CENTERING, DIM+1> Proto::ALL_FACES
Initial value:
{BOUNDARY,
    XFACE
  }