Chombo_4: BFMImpl< D, T1, T2, F > Struct Template Reference
BFMImpl< D, T1, T2, F > Struct Template Reference
#include <Chombo_BFM.H>
Static Public Member Functions
static void f (T1 *__restrict t1, const T2 *__restrict t2, int *lo1, int *lo2, int *stride1, int *stride2, int *counting, F f)
Member Function Documentation
f()
template<unsigned char D, typename T1 , typename T2 , typename F > static void BFMImpl< D, T1, T2, F >::f (T1 *__restrict t1, const T2 *__restrict t2, int * lo1, int * lo2, int * stride1, int * stride2, int * counting, F f) inline static
References D.
Referenced by BFM(), BFMImpl< 0, T1, T2, F >::f(), and BFMImpl1< 0, T1, F >::f().
The documentation for this struct was generated from the following file:
Chombo_BFM.H