Chombo_4: EBCM::Algorithm_Framework< ebcm_order >::neighborhood_t Struct Reference
EBCM::Algorithm_Framework< ebcm_order >::neighborhood_t Struct Reference
#include <Chombo_EBCM_Algorithm_Framework.H>
Classes
struct cut_face_t
struct dom_face_t
structure to remember where there are domain faces.
Public Member Functions
neighborhood_t (const ebcm_graph &a_graph, const ch_iv &a_facelo, const ch_iv &a_facehi, int a_nghost, int a_weight_power, bool a_print)
Public Attributes
ch_iv m_facelo
ch_iv m_facehi
int m_nghost
pr_rv m_startloc
shared_ptr< ebcm_subvol_vec > m_volumes
shared_ptr< vector< dom_face_t > > m_dom_faces
shared_ptr< vector< cut_face_t > > m_cut_faces
vector< pr_rv > m_xbar_volumes
vector< pr_rv > m_xbar_dom_faces
vector< pr_rv > m_xbar_cut_faces
vector< double > m_dist_volumes
this is the distance used in calculating weights
vector< double > m_dist_dom_faces
vector< double > m_dist_cut_faces
vector< double > m_weig_volumes
this is the weight of each equation (the diagonal of the weight matrix)
vector< double > m_weig_dom_faces
vector< double > m_weig_cut_faces
Protected Member Functions
void fillDerived (const ebcm_graph &a_graph, int a_nghost, int a_weight_power, bool a_print)
template<CENTERING cent>
void getFaceDetails (pr_pt &a_neigh_lo, pr_pt &a_neigh_hi, pr_rv &a_neigh_centroid, const int &a_neigh_dir, const EBCM_Face< cent, ebcm_order > &a_neigh_face, const double &a_dx)
void getFaceInfo (pr_rv &a_neigh_xbar, double &a_neigh_dist, double &a_neigh_weig, const dom_face_t &a_curfac, const ebcm_graph &a_graph, const int &a_weight_power)
void getBoundaryDerived (const ebcm_graph &a_graph, int a_nghost, int a_weight_power, bool a_print)
void getVolumeDerived (const ebcm_graph &a_graph, int a_nghost, int a_weight_power, bool a_print)
void getDistanceAndWeight (double &a_distance, double &a_weight, const ch_iv &a_start, const ch_iv &a_end, int a_weight_power)
double getManhattanDistance (const ch_iv &a_start, const ch_iv &a_end)
Constructor & Destructor Documentation
neighborhood_t()
template<int ebcm_order> EBCM::Algorithm_Framework< ebcm_order >::neighborhood_t::neighborhood_t (const ebcm_graph & a_graph, const ch_iv & a_facelo, const ch_iv & a_facehi, int a_nghost, int a_weight_power, bool a_print) inline
References CH_TIME, EBCM::EBCM_Graph< order >::m_domain, EBCM::EBCM_Graph< order >::m_dx, and Proto::RealVect::setToCCLocation().
Member Function Documentation
fillDerived()
template<int ebcm_order> void EBCM::Algorithm_Framework< ebcm_order >::neighborhood_t::fillDerived (const ebcm_graph & a_graph, int a_nghost, int a_weight_power, bool a_print) inline protected
first get the addresses of domain and cut faces around each volume
References pout(), and Proto::IndexedMoments< Dim, P >::size().
getFaceDetails()
template<int ebcm_order> template<CENTERING cent> void EBCM::Algorithm_Framework< ebcm_order >::neighborhood_t::getFaceDetails (pr_pt & a_neigh_lo, pr_pt & a_neigh_hi, pr_rv & a_neigh_centroid, const int & a_neigh_dir, const EBCM_Face< cent, ebcm_order > & a_neigh_face, const double & a_dx) inline protected
This is the face mom with all derivatives in a_neigh_dir set to zero.
References ebcm_basics::getVolMomFromFacMom(), EBCM::EBCM_Face< cent, order >::m_facmom, EBCM::EBCM_Face< cent, order >::m_hi, and EBCM::EBCM_Face< cent, order >::m_lo.
getFaceInfo()
template<int ebcm_order> void EBCM::Algorithm_Framework< ebcm_order >::neighborhood_t::getFaceInfo (pr_rv & a_neigh_xbar, double & a_neigh_dist, double & a_neigh_weig, const dom_face_t & a_curfac, const ebcm_graph & a_graph, const int & a_weight_power) inline protected
References EBCM::Algorithm_Framework< ebcm_order >::neighborhood_t::dom_face_t::m_direction, EBCM::EBCM_Graph< order >::m_dx, EBCM::Algorithm_Framework< ebcm_order >::neighborhood_t::dom_face_t::m_subvol_index, EBCM::Algorithm_Framework< ebcm_order >::neighborhood_t::dom_face_t::m_volume_index, EBCM::EBCM_Graph< order >::m_volumes, and pout().
getBoundaryDerived()
template<int ebcm_order> void EBCM::Algorithm_Framework< ebcm_order >::neighborhood_t::getBoundaryDerived (const ebcm_graph & a_graph, int a_nghost, int a_weight_power, bool a_print) inline protected
this fills in the hooks to boundary condition informaiton
References EBCM::EBCM_Graph< order >::m_dx.
getVolumeDerived()
template<int ebcm_order> void EBCM::Algorithm_Framework< ebcm_order >::neighborhood_t::getVolumeDerived (const ebcm_graph & a_graph, int a_nghost, int a_weight_power, bool a_print) inline protected
getDistanceAndWeight()
template<int ebcm_order> void EBCM::Algorithm_Framework< ebcm_order >::neighborhood_t::getDistanceAndWeight (double & a_distance, double & a_weight, const ch_iv & a_start, const ch_iv & a_end, int a_weight_power) inline protected
getManhattanDistance()
template<int ebcm_order> double EBCM::Algorithm_Framework< ebcm_order >::neighborhood_t::getManhattanDistance (const ch_iv & a_start, const ch_iv & a_end) inline protected
Member Data Documentation
m_facelo
template<int ebcm_order> ch_iv EBCM::Algorithm_Framework< ebcm_order >::neighborhood_t::m_facelo
m_facehi
template<int ebcm_order> ch_iv EBCM::Algorithm_Framework< ebcm_order >::neighborhood_t::m_facehi
m_nghost
template<int ebcm_order> int EBCM::Algorithm_Framework< ebcm_order >::neighborhood_t::m_nghost
m_startloc
template<int ebcm_order> pr_rv EBCM::Algorithm_Framework< ebcm_order >::neighborhood_t::m_startloc
m_volumes
template<int ebcm_order> shared_ptr<ebcm_subvol_vec> EBCM::Algorithm_Framework< ebcm_order >::neighborhood_t::m_volumes
m_dom_faces
template<int ebcm_order> shared_ptr< vector< dom_face_t > > EBCM::Algorithm_Framework< ebcm_order >::neighborhood_t::m_dom_faces
m_cut_faces
template<int ebcm_order> shared_ptr< vector< cut_face_t > > EBCM::Algorithm_Framework< ebcm_order >::neighborhood_t::m_cut_faces
m_xbar_volumes
template<int ebcm_order> vector<pr_rv> EBCM::Algorithm_Framework< ebcm_order >::neighborhood_t::m_xbar_volumes
m_xbar_dom_faces
template<int ebcm_order> vector<pr_rv> EBCM::Algorithm_Framework< ebcm_order >::neighborhood_t::m_xbar_dom_faces
m_xbar_cut_faces
template<int ebcm_order> vector<pr_rv> EBCM::Algorithm_Framework< ebcm_order >::neighborhood_t::m_xbar_cut_faces
m_dist_volumes
template<int ebcm_order> vector<double> EBCM::Algorithm_Framework< ebcm_order >::neighborhood_t::m_dist_volumes
this is the distance used in calculating weights
m_dist_dom_faces
template<int ebcm_order> vector<double> EBCM::Algorithm_Framework< ebcm_order >::neighborhood_t::m_dist_dom_faces
m_dist_cut_faces
template<int ebcm_order> vector<double> EBCM::Algorithm_Framework< ebcm_order >::neighborhood_t::m_dist_cut_faces
m_weig_volumes
template<int ebcm_order> vector<double> EBCM::Algorithm_Framework< ebcm_order >::neighborhood_t::m_weig_volumes
this is the weight of each equation (the diagonal of the weight matrix)
m_weig_dom_faces
template<int ebcm_order> vector<double> EBCM::Algorithm_Framework< ebcm_order >::neighborhood_t::m_weig_dom_faces
m_weig_cut_faces
template<int ebcm_order> vector<double> EBCM::Algorithm_Framework< ebcm_order >::neighborhood_t::m_weig_cut_faces
The documentation for this struct was generated from the following file:
Chombo_EBCM_Algorithm_Framework.H