Chombo_4: Proto::GenericArithmeticable< ScalarT, SelfT > Struct Template Reference
Proto::GenericArithmeticable< ScalarT, SelfT > Struct Template Reference
#include <Proto_GenericArithmetic.H>
Public Types
typedef ScalarT scalar_type
typedef SelfT self_type
Public Member Functions
virtual ~GenericArithmeticable ()
GenericArithmeticable (SelfT *s)
bool operator< (const SelfT &) const
bool operator> (const SelfT &) const
bool operator<= (const SelfT &) const
bool operator>= (const SelfT &) const
SelfT & operator+= (const SelfT &)
SelfT & operator+= (const ScalarT &)
SelfT & operator-= (const SelfT &)
SelfT & operator-= (const ScalarT &)
SelfT & operator*= (const SelfT &)
SelfT & operator*= (const ScalarT &)
SelfT & operator/= (const SelfT &)
SelfT & operator/= (const ScalarT &)
Private Attributes
SelfT * m_child
Detailed Description
template<typename ScalarT, typename SelfT>
struct Proto::GenericArithmeticable< ScalarT, SelfT >
Class that you need to derive from, if you want the global operators below to be available for your class. For example: class Foo : public GenericArithmeticable<double,Foo> { public: Foo() : GenericArithmeticable<double,Foo>(this) { } Foo& operator+=(const Foo&); Foo& operator+=(const double&); [etc] };
If, in addition, you want the member-function operators, you'll need to implement some generic operator-appliers in your derived class: see, in GenericArithmeticI.H, operatorCompare() and operatorOpEquals(). If you implement operator<, operator+= etc in your derived class, then that'll override the ones here (regardless of whether you've defined operatorCompare() and operatorOpEquals() in your derived class, though it would then be weird if you did).
Member Typedef Documentation
scalar_type
template<typename ScalarT, typename SelfT> typedef ScalarT Proto::GenericArithmeticable< ScalarT, SelfT >::scalar_type
self_type
template<typename ScalarT, typename SelfT> typedef SelfT Proto::GenericArithmeticable< ScalarT, SelfT >::self_type
Constructor & Destructor Documentation
~GenericArithmeticable()
template<typename ScalarT, typename SelfT> virtual Proto::GenericArithmeticable< ScalarT, SelfT >::~GenericArithmeticable () inline virtual
GenericArithmeticable()
template<typename ScalarT, typename SelfT> Proto::GenericArithmeticable< ScalarT, SelfT >::GenericArithmeticable (SelfT * s) inline
Member Function Documentation
operator<()
template<typename ScalarT , typename SelfT> bool GenericArithmeticable< ScalarT, SelfT >::operator< (const SelfT & rhs) const
Referenced by Proto::GenericArithmeticable< double, IndexTM< double, N > >::GenericArithmeticable().
operator>()
template<typename ScalarT , typename SelfT> bool GenericArithmeticable< ScalarT, SelfT >::operator> (const SelfT & rhs) const
Referenced by Proto::GenericArithmeticable< double, IndexTM< double, N > >::GenericArithmeticable().
operator<=()
template<typename ScalarT , typename SelfT> bool GenericArithmeticable< ScalarT, SelfT >::operator<= (const SelfT & rhs) const
Referenced by Proto::GenericArithmeticable< double, IndexTM< double, N > >::GenericArithmeticable().
operator>=()
template<typename ScalarT , typename SelfT> bool GenericArithmeticable< ScalarT, SelfT >::operator>= (const SelfT & rhs) const
Referenced by Proto::GenericArithmeticable< double, IndexTM< double, N > >::GenericArithmeticable().
operator+=() [1/2]
template<typename ScalarT , typename SelfT> SelfT & GenericArithmeticable< ScalarT, SelfT >::operator+= (const SelfT & rhs)
Referenced by Proto::GenericArithmeticable< double, IndexTM< double, N > >::GenericArithmeticable().
operator+=() [2/2]
template<typename ScalarT, typename SelfT> SelfT & GenericArithmeticable< ScalarT, SelfT >::operator+= (const ScalarT & a)
operator-=() [1/2]
template<typename ScalarT , typename SelfT> SelfT & GenericArithmeticable< ScalarT, SelfT >::operator-= (const SelfT & rhs)
Referenced by Proto::GenericArithmeticable< double, IndexTM< double, N > >::GenericArithmeticable().
operator-=() [2/2]
template<typename ScalarT, typename SelfT> SelfT & GenericArithmeticable< ScalarT, SelfT >::operator-= (const ScalarT & a)
operator*=() [1/2]
template<typename ScalarT , typename SelfT> SelfT & GenericArithmeticable< ScalarT, SelfT >::operator*= (const SelfT & rhs)
Referenced by Proto::GenericArithmeticable< double, IndexTM< double, N > >::GenericArithmeticable().
operator*=() [2/2]
template<typename ScalarT, typename SelfT> SelfT & GenericArithmeticable< ScalarT, SelfT >::operator*= (const ScalarT & a)
operator/=() [1/2]
template<typename ScalarT , typename SelfT> SelfT & GenericArithmeticable< ScalarT, SelfT >::operator/= (const SelfT & rhs)
Referenced by Proto::GenericArithmeticable< double, IndexTM< double, N > >::GenericArithmeticable().
operator/=() [2/2]
template<typename ScalarT, typename SelfT> SelfT & GenericArithmeticable< ScalarT, SelfT >::operator/= (const ScalarT & a)
Member Data Documentation
m_child
template<typename ScalarT, typename SelfT> SelfT* Proto::GenericArithmeticable< ScalarT, SelfT >::m_child private
The documentation for this struct was generated from the following files:
Proto_GenericArithmetic.H
Proto_GenericArithmeticImplem.H