Chombo_4: Interval Struct Reference
Interval Struct Reference
Structure for passing component ranges in code.
#include <Chombo_Interval.H>
Public Member Functions
Interval ()
Interval (int a_firstComp, int a_lastComp)
Interval & operator= (const Interval &p)
void define (int a_firstComp, int a_lastComp)
int begin () const
int end () const
int size () const
bool contains (int a_val) const
bool operator== (const Interval &p) const
test for equality
Private Attributes
int m_begin
int m_end
Friends
std::ostream & operator<< (std::ostream &os, const Interval &dit)
Detailed Description
Structure for passing component ranges in code.
A class to encapsulate component ranges
Constructor & Destructor Documentation
Interval() [1/2]
Interval::Interval () inline
Interval() [2/2]
Interval::Interval (int a_firstComp, int a_lastComp) inline
initialize with first and last component numbers
Member Function Documentation
operator=()
Interval& Interval::operator= (const Interval & p) inline
Copy from another Interval
References m_begin, and m_end.
define()
void Interval::define (int a_firstComp, int a_lastComp) inline
References begin(), end(), m_begin, and m_end.
Referenced by WriteMultiData< T >::WriteMultiData().
begin()
int Interval::begin () const inline
return first component number
References m_begin.
Referenced by BaseFab< Real >::copy(), LevelData< FArrayBox >::copyTo(), dataSize(), define(), LevelData< FArrayBox >::define(), BaseFab< Real >::define(), BoxLayoutData< FArrayBox >::define(), LDOperator< T >::linearIn(), BaseFab< Real >::linearIn(), BaseFab< Real >::linearIn2(), LDOperator< T >::linearOut(), BaseFab< Real >::linearOut2(), LDOperator< T >::op(), LDaddOp< T >::op(), read(), BoxLayoutData< FArrayBox >::setVector(), LDOperator< T >::size(), write(), and WriteMultiData< T >::writeData().
end()
int Interval::end () const inline
return last component number
References m_end.
Referenced by define(), BoxLayoutData< FArrayBox >::define(), BaseFab< Real >::linearIn(), BaseFab< Real >::linearIn2(), BaseFab< Real >::linearOut2(), read(), and WriteMultiData< T >::writeData().
size()
int Interval::size () const inline
return last - first + 1
References m_begin, and m_end.
Referenced by aliasLevelData(), BoxLayoutData< FArrayBox >::allocateBuffers(), BaseFab< Real >::copy(), LevelData< FArrayBox >::copyTo(), dataSize(), LevelData< FArrayBox >::define(), BaseFab< Real >::define(), BoxLayoutData< FArrayBox >::define(), BoxLayoutData< FArrayBox >::generalCopyTo(), LDOperator< T >::linearIn(), LDOperator< T >::linearOut(), LDOperator< T >::op(), LDaddOp< T >::op(), read(), BoxLayoutData< FArrayBox >::setVector(), LDOperator< T >::size(), BaseFab< Real >::size(), write(), WriteMultiData< T >::writeData(), and WriteMultiData< T >::WriteMultiData().
contains()
bool Interval::contains (int a_val) const inline
References m_begin, and m_end.
operator==()
bool Interval::operator== (const Interval & p) const inline
test for equality
References m_begin, m_end, and operator<<.
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const Interval & dit) friend
Referenced by operator==().
Member Data Documentation
m_begin
int Interval::m_begin private
Referenced by begin(), contains(), define(), operator=(), operator==(), and size().
m_end
int Interval::m_end private
Referenced by contains(), define(), end(), operator=(), operator==(), and size().
The documentation for this struct was generated from the following file:
Chombo_Interval.H