Chombo_4: LevelData< T >::ApplyFunctor Struct Reference
LevelData< T >::ApplyFunctor Struct Reference abstract
#include <Chombo_LevelData.H>
Public Member Functions
~ApplyFunctor ()
void operator() (const Box &, int, T &) const =0
Detailed Description
template<class T>
struct LevelData< T >::ApplyFunctor
For use with apply(const ApplyFunctor&)
Constructor & Destructor Documentation
~ApplyFunctor()
template<class T> LevelData< T >::ApplyFunctor::~ApplyFunctor () inline
References LevelData< T >::apply(), LevelData< T >::degenerate(), LevelData< T >::degenerateLocalOnly(), and LevelData< T >::ApplyFunctor::operator()().
Member Function Documentation
operator()()
template<class T> void LevelData< T >::ApplyFunctor::operator() (const Box & , int , T &) const pure virtual
Referenced by LevelData< T >::ApplyFunctor::~ApplyFunctor().
The documentation for this struct was generated from the following file:
Chombo_LevelData.H