#ifdef CH_LANG_CC
/*
 *      _______              __
 *     / ___/ /  ___  __ _  / /  ___
 *    / /__/ _ \/ _ \/  V \/ _ \/ _ \
 *    \___/_//_/\___/_/_/_/_.__/\___/
 *    Please refer to Copyright.txt, in Chombo's root directory.
 */
#endif

#ifndef _LOHISIDE_H_
#define _LOHISIDE_H_
#include "BaseNamespaceHeader.H"
#include "Proto_LoHiSide.H"

using Proto::Side;
using Proto::SideIterator;

#include "BaseNamespaceFooter.H"
#endif
