#ifdef CH_LANG_CC
/*
 *      _______              __
 *     / ___/ /  ___  __ _  / /  ___
 *    / /__/ _ \/ _ \/  V \/ _ \/ _ \
 *    \___/_//_/\___/_/_/_/_.__/\___/
 *    Please refer to Copyright.txt, in Chombo's root directory.
 */
#endif

#ifndef _Chombo_REALVECT_H_
#define _Chombo_REALVECT_H_

#include <cstddef>
#include <cstdlib>
#include <cstring>
#include <iostream>
#include <vector>

#include "Chombo_SPACE.H"
#include "Chombo_REAL.H"
#include "Chombo_IntVect.H"
#include "Chombo_SPMD.H"
#include "Proto_RealVect.H"
#include "Chombo_NamespaceHeader.H"

using ::Proto::RealVect;

#include "Chombo_NamespaceFooter.H"

#endif
