#ifdef CH_LANG_CC
/*
 *      _______              __
 *     / ___/ /  ___  __ _  / /  ___
 *    / /__/ _ \/ _ \/  V \/ _ \/ _ \
 *    \___/_//_/\___/_/_/_/_.__/\___/
 *    Please refer to Copyright.txt, in Chombo's root directory.
 */
#endif

#ifndef _REALVECT_H_
#define _REALVECT_H_

#include <cstddef>
#include <cstdlib>
#include <cstring>
#include <iostream>

#include "SPACE.H"

#include "REAL.H"
#include "SPACE.H"
#include "IntVect.H"
#include <vector>
#include "SPMD.H"
#include "Proto_RealVect.H"

#include "NamespaceHeader.H"

using Proto::RealVect;

#include "NamespaceFooter.H"

#endif
