#!/usr/bin/python
from argparse import *
import os
import glob
import platform
from datetime import date

today = date.today()

print("Today's date:", today)

parser = ArgumentParser()

parser.add_argument('--max_taylor_order', type=int, help='highest [4]'  ,default='4')
parser.add_argument('--max_weight_power', type=int, help='weight power [5]'   ,default='5')
parser.add_argument('--input', type=str, help='input file template'   ,default="_input_templates/all_regular.inputs")
parser.add_argument('--batch', type=str, help='batch file template'   ,default="_batch_templates/serial.batch")
parser.add_argument('--prefix', type=str, help='name of test["test"]',default="test")

args = parser.parse_args()
print(args)

homestr = os.getcwd();
print ("homedir = " + homestr)
neartopstr = homestr + "/_" +args.prefix
strtoday =str(today.month) + "_" + str(today.day) + "_" + str(today.year)
f_inputtemplate = open(args.input,'r')
f_batchtemplate = open(args.batch,'r')


topstr = neartopstr +"_" + strtoday
print ("topstr = " + topstr)

if not os.path.exists(topstr):
    printstr = "making directory " + topstr
    print (printstr)
    os.mkdir(topstr)

print ("changing directory to " + topstr)
os.chdir(topstr);

submitstr = "submit."  + args.prefix + ".jobs"
r = open(submitstr,'w')
r.write('#/usr/bin/csh\n')

max_taylor = args.max_taylor_order
max_weight = args.max_weight_power
taylor_P = 1

submitstr = "submit."  + args.prefix + ".jobs"
subfile = open(submitstr,'w')
subfile.write('#/usr/bin/csh\n')
inputfilename = os.path.basename(args.input)
batchfilename = os.path.basename(args.batch)

while taylor_P <= max_taylor:
    weight_P = 1
    while weight_P <= max_weight:

        configstr = "__taylorP_eq_" + str(taylor_P) + "__weightP_eq_" + str(weight_P)
        print (configstr);

        print ("changing directory to " + homestr)
        os.chdir(homestr);

        print ("changing directory to " + topstr)
        os.chdir(topstr);

        dir_str = configstr
        
        commstr = "cd " + dir_str  + "; source " + batchfilename + "; cd .. \n"
        subfile.write(commstr)

        if not os.path.exists(dir_str):
            printstr = "making directory " + dir_str
            print (printstr)
            os.mkdir(dir_str)
        
        print ("changing directory to " + dir_str)
        os.chdir(dir_str)

        f_inp = open(inputfilename,'w')
        f_bat = open(batchfilename,'w')
        print ("processing input file")
        for inputstr in f_inputtemplate:
            t1str = inputstr;
            t2str = t1str.replace("TAYLOR_MAX", str(taylor_P))
            t3str = t2str.replace("WGT_POWER",  str(weight_P))
            f_inp.write(t3str)
        
        print ("processing batch file")
        executablename  = "../../../main.exe"
        for batchster in f_batchtemplate:
            t1str = batchster
            t2str = t1str.replace("INPUT_FILE", inputfilename)
            t3str = t2str.replace("EXECUTABLE_FILE", executablename)
            f_bat.write(t3str)

        f_bat.close()
        f_inp.close()
        weight_P +=  1
#       end inner scope        
    taylor_P += 1
#   end outer scope

print("out of loop")
f_inputtemplate.close()
f_batchtemplate.close()
subfile.close();

    
