name: Chombo CI with Proto

on:
  push:
    branches: [ configure ]
  pull_request:
    branches: [ configure ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
      - name: Setup default branch
        run: git config --global init.defaultBranch configure
      - uses: actions/checkout@master
        with:
          repository: git@bitbucket.org:berkleleylab/proto.git
          submodules: true
          path: ${{github.workspace}}/proto
      - uses: actions/checkout@master
        with:
          submodules: true
          path: ${{github.workspace}}/chombo

        # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
        # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      - name: Configure Proto
        run: cmake -B ${{github.workspace}}/proto/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
      - name: Make Proto
        working-directory: ${{github.workspace}}/proto/build
        run: make -j

      - name: Configure Chombo
        run: cmake -B ${{github.workspace}}/chombo/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
      - name: Make Chombo
        working-directory: ${{github.workspace}}/chombo/build
        run: make -j
      - name: Run Google Test
        working-directory: ${{github.workspace}}/chombo/build
        run: make test
