name: linux

on: [push, pull_request]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug

jobs:
  chombo_gnu:
    name: GNU@9.3
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master  # Checkout Chombo
        with:
          submodules: true
      - name: Dependencies
        run: .github/workflows/dependencies/host.sh
      - name: Build Proto
        working-directory: proto
        run: |
          cmake -S . -B host -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DBLT_SOURCE_DIR=${{github.workspace}}/blt
          cmake --build host --parallel
      - name: Build & Install Chombo
        run: |
          cmake -S . -B host_build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
          cmake --build host_build --parallel
      - name: Run Google Test
        working-directory: host_build
        run: make test TEST_ARGS="-VV"
    
  chombo_nvcc:
    name: NVCC@11.0
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master  # Checkout Chombo
        with:
          submodules: true
      - name: Install Dependencies
        run: .github/workflows/dependencies/cuda.sh
      - name: Build Proto
        working-directory: proto
        run: |
          export PATH=/usr/local/cuda/bin:${PATH}
          export LD_LIBRARY_PATH=/usr/local/cuda/lib64:/usr/local/cuda/lib:${LD_LIBRARY_PATH}
          which nvcc || echo "NVCC NOT IN PATH"
          cmake -S . -B cuda_build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} \
          -DBLT_SOURCE_DIR=${{github.workspace}}/blt -DENABLE_CUDA=ON \
          -DENABLE_EXAMPLES=OFF -DENABLE_TESTS=OFF
          cmake --build cuda_build --parallel
      - name: Build & Install Chombo
        run: |
          export PATH=/usr/local/cuda/bin:${PATH}
          export LD_LIBRARY_PATH=/usr/local/cuda/lib64:/usr/local/cuda/lib:${LD_LIBRARY_PATH}
          which nvcc || echo "NVCC NOT IN PATH"
          cmake -S . -B cuda_build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DENABLE_CUDA=ON
          cmake --build cuda_build --parallel
      - name: Run Google Test
        working-directory: cuda_build
        run: make test TEST_ARGS="-VV"
